import { EDITORIAL_TEAM } from "@/lib/editorialTrust";
import { ATLAS_COLLECTION_REVIEWER } from "@/lib/atlasCollectionsExpansion";

const CHECKED_AT = "2026-09-07";

const source = (id, name, url, claimScope, type = "independent") => ({
  id,
  name,
  url,
  claimScope,
  type,
  confidence: "high",
  checkedAt: CHECKED_AT,
});

const editorial = (collection, note) => ({
  ...collection,
  author: EDITORIAL_TEAM,
  reviewer: ATLAS_COLLECTION_REVIEWER,
  publishedAt: CHECKED_AT,
  updatedAt: CHECKED_AT,
  changeLog: [{ date: CHECKED_AT, note }],
});

export const AUDIENCE_ATLAS_COLLECTIONS = [
  editorial({
    id: "best-gay-friendly-destinations-over-40",
    slug: "best-gay-friendly-destinations-over-40",
    title: "Best Gay-Friendly Destinations for Travelers Over 40",
    eyebrow: "Travel at your own tempo",
    filter: "solo",
    intent: "best gay friendly destinations for travelers over 40 mature gay travel",
    summary: "Six places where culture, conversation, comfort, and queer social life offer more than a youth-coded club circuit.",
    methodology: "Selected for useful daytime culture, compact or navigable queer geography, varied evening formats, accommodation choice, and a social scene that does not depend on being the youngest person in the room. This is not an age ranking: atmosphere changes by venue, season, and event, and accessibility must still be checked separately.",
    bestFor: "Travelers over 40 who want queer visibility without building the entire trip around a club queue",
    mood: "Confident, sociable, unhurried",
    price: "Mid-range to premium",
    editorialNote: "The useful question is not whether a city is ‘for older travelers.’ It is whether the trip still works when good food, culture, beach time, conversation, and an early drink matter as much as dancing until sunrise.",
    updated: "7 September 2026",
    cities: ["Palm Springs", "Sitges", "Brighton", "Montreal", "Copenhagen", "Lisbon"],
    items: ["Palm Springs", "Sitges", "Brighton", "Montreal", "Copenhagen", "Lisbon"],
    itemNotes: [
      "Palm Springs makes a relaxed queer trip easy to read: resort time, modernist design, desert excursions, restaurants, and LGBTQ+ events coexist year-round. A car can broaden the itinerary, while extreme summer heat makes season more important than nightlife proximity.",
      "Sitges compresses beach, old-town walks, restaurants, museums, terraces, and gay social life into a small coastal town. It is especially useful when you want choices without constant transit; festival dates bring energy but also crowds and higher room rates.",
      "Brighton offers a walkable seafront, independent culture, queer history, community space, cabaret, pubs, and Kemptown’s relaxed village rhythm. Hills and older buildings can complicate access, but the trip does not collapse if a late club is not the priority.",
      "Montreal balances the Village with food, museums, performance, parks, and queer life across other neighborhoods. Terraces and the pedestrianized summer street favor sociability; winter creates a much more indoor, weather-dependent version of the city.",
      "Copenhagen suits a design-and-food city break with compact central queer bars, cultural programming, harbor routes, and reliable transit. It is easy to keep the pace civilised, although dining and accommodation can make a spontaneous weekend expensive.",
      "Lisbon combines viewpoints, food, queer bookstores and bars, museums, and coastal day trips without requiring a party-first itinerary. Príncipe Real is a useful base; steep streets, summer heat, and late dining should shape the daily rhythm.",
    ],
    tags: ["Over 40", "Gay travel", "Culture and comfort"],
    href: "/now/collections/best-gay-friendly-destinations-over-40",
    accent: "amber",
    sources: [
      source("over40-palm-springs", "Visit Greater Palm Springs — LGBTQ+", "https://www.visitgreaterpalmsprings.com/lgbtq/", "Official year-round LGBTQ+ stays, events, bars, and destination context.", "official"),
      source("over40-sitges", "Visit Sitges", "https://www.visitsitges.com/en/", "Official beach, heritage, museum, event, and LGBTQ+ visitor context.", "official"),
      source("over40-brighton", "Visit Brighton — LGBTQIA+", "https://www.visitbrighton.com/plan-your-visit/about-the-area/lgbtqia", "Official Kemptown, community, culture, cabaret, and visitor context.", "official"),
      source("over40-montreal", "Tourisme Montréal — The Village", "https://www.mtl.org/en/city/about-montreal/neighbourhoods/montreal-the-village", "Official day-and-night neighborhood, dining, shopping, and transit context.", "official"),
      source("over40-copenhagen", "Visit Copenhagen — LGBTQIA+ guide", "https://www.visitcopenhagen.com/copenhagen/this-is-copenhagen/reasons-to-go/the-ultimate-lgbtqia-guide-to-copenhagen", "Official queer culture, history, cafes, bars, and city-planning context.", "official"),
      source("over40-lisbon", "Visit Lisboa", "https://www.visitlisboa.com/en", "Official city culture, neighborhoods, food, coast, and trip-planning context.", "official"),
    ],
  }, "Published with an age-aware but non-ageist method, six individual destination trade-offs, and official visitor sources."),

  editorial({
    id: "best-sapphic-destinations-solo-travelers",
    slug: "best-sapphic-destinations-solo-travelers",
    title: "Best Lesbian and Sapphic Destinations for Solo Travelers",
    eyebrow: "Arrive solo, find the scene",
    filter: "women",
    intent: "best lesbian sapphic destinations solo travelers queer women travel",
    summary: "Six cities with enough women-led culture, low-pressure entry points, and navigable queer life to make a solo trip feel intentional.",
    methodology: "This edit weighs permanent sapphic anchors, recurring women-led calendars, daytime community space, public transport, neighborhood legibility, and ways to participate without arriving with a group. A lesbian venue is not automatically inclusive of every trans or nonbinary guest; current audience and access language must be checked directly.",
    bestFor: "Lesbian, bi, queer, trans, and nonbinary travelers who want a credible way into the city when arriving alone",
    mood: "Independent, connected, curious",
    price: "Mixed",
    editorialNote: "Solo usefulness is the distinction here. Each city offers more than visibility: it offers at least one practical first move—a bookstore, community room, bar, tour, or recurring event—from which the rest of the trip can unfold.",
    updated: "7 September 2026",
    cities: ["London", "Montreal", "Berlin", "Melbourne", "New York", "Madrid"],
    items: ["London", "Montreal", "Berlin", "Melbourne", "New York", "Madrid"],
    itemNotes: [
      "London gives a solo visitor several distinct openings: Gay’s the Word by day, SHE Soho for a central dedicated bar, Queer Britain for context, and women-led nights across East London. The scene is deep but dispersed, so choose one neighborhood cluster per evening.",
      "Montreal works through queer bookstores, comedy, sports gatherings, ballroom, magazines, and roving sapphic events beyond the Village. The metro is helpful and summer streets invite casual contact; check whether an event runs in French, English, or both.",
      "Berlin’s sapphic map combines Begine, SilverFuture, queer archives, FLINTA-focused nights, and historical routes. It rewards travelers who select the program before the address; door policies and identity language vary more than a generic city guide suggests.",
      "Melbourne’s inner north supports a flexible route through cafes, live music, film, sport, and parties such as Tomboy. Trams reduce planning friction, while event-led sapphic nightlife means the strongest weekend depends on the current calendar.",
      "New York has rare permanent lesbian-bar infrastructure alongside bookstores, museums, comedy, performance, and rotating Brooklyn events. It offers real choice for different energies, but borough distances make a tightly grouped plan more social than venue-hopping across the city.",
      "Madrid pairs Berkana’s bookshop history and Chueca’s easy orientation with women-led parties and broader queer culture. The late local timetable can challenge a first solo evening, so a bookstore or early bar is a better entry point than waiting for a club to fill.",
    ],
    tags: ["Sapphic", "Solo travel", "Women-led"],
    href: "/now/collections/best-sapphic-destinations-solo-travelers",
    accent: "fuchsia",
    sources: [
      source("sapphic-solo-london", "Visit London — LGBTQ+ London", "https://www.visitlondon.com/things-to-do/lgbt", "Official queer culture, attractions, neighborhoods, and nightlife context.", "official"),
      source("sapphic-solo-montreal", "Tourisme Montréal — Queer Montréal stretches city-wide", "https://www.mtl.org/en/experience/queer-mtl-stretches-city-wide", "Current women-led, literary, ballroom, sports, and neighborhood context.", "official"),
      source("sapphic-solo-berlin", "visitBerlin — Berlin for women", "https://www.visitberlin.de/en/berlin-women", "Official lesbian history, cultural anchors, bars, and visitor routes.", "official"),
      source("sapphic-solo-melbourne", "Visit Melbourne — LGBTQIA+", "https://www.visitmelbourne.com/regions/melbourne/see-and-do/lgbtqia", "Official queer-women events, neighborhoods, film, and nightlife context.", "official"),
      source("sapphic-solo-bars", "The Lesbian Bar Project", "https://www.lesbianbarproject.com/", "Independent record of dedicated lesbian venues and their scarcity.", "research"),
      source("sapphic-solo-guides", "Autostraddle — Queer Girl City Guides", "https://www.autostraddle.com/tag/queer-girl-city-guide/", "Specialist city reporting through queer women and nonbinary perspectives.", "independent"),
    ],
  }, "Published as a solo-first sapphic edit with low-pressure entry points, explicit inclusion caveats, and six city-specific routes."),

  editorial({
    id: "best-body-positive-gay-destinations-bears-bigger-guys",
    slug: "best-body-positive-gay-destinations-bears-bigger-guys",
    title: "Best Body-Positive Gay Destinations for Bears and Bigger Guys",
    eyebrow: "More room to belong",
    filter: "events",
    intent: "best body positive gay destinations bears bigger guys travel",
    summary: "Six destinations where bear organizations, social spaces, and recurring gatherings create a more legible route for bigger gay men and admirers.",
    methodology: "Selected for visible bear or chub community infrastructure, recurring social programming, destination usefulness outside one party, and a credible way to verify the current scene. Bear branding is not proof that every body, race, age, trans person, or disabled guest will experience equal welcome; organizer policies and venue access still matter.",
    bestFor: "Bears, cubs, chubs, bigger gay men, and admirers seeking visible community rather than a generic circuit weekend",
    mood: "Warm, social, proudly physical",
    price: "Accessible to event-premium",
    editorialNote: "Body-positive is an editorial test, not a marketing sticker. These destinations have identifiable community infrastructure, but no scene is free from exclusion. Read the host, audience, accessibility, and conduct information before treating a bear logo as a guarantee.",
    updated: "7 September 2026",
    cities: ["Sitges", "Madrid", "Palm Springs", "Provincetown", "Berlin", "Montreal"],
    items: ["Sitges", "Madrid", "Palm Springs", "Provincetown", "Berlin", "Montreal"],
    itemNotes: [
      "Sitges has a visible year-round gay town plus a large September bear gathering with beaches, daytime meetups, dining, cultural activities, and a central Bear Village. The event transforms the town, so book early and distinguish festival atmosphere from quieter dates.",
      "Madrid supports bear travel through MAD.BEAR programming and a broader Chueca nightlife network. Its advantage is choice beyond the headline party—food, culture, bars, and late social hours—although individual rooms can still be age-, style-, or fetish-specific.",
      "Palm Springs combines gay resorts and a year-round LGBTQ+ calendar with major bear weekends in a low-rise desert setting. Pool culture can be liberating for some and exposing for others; property audience, clothing policy, and accessibility deserve a direct check.",
      "Provincetown turns Bear Week into a town-wide trip of shows, beach time, tea dance, restaurants, and repeated social contact rather than one sealed-off venue. Summer lodging and ferry demand are the main friction, and the dense center still includes uneven historic access.",
      "Berlin offers bear and leather organizations, Schöneberg bars, saunas, shops, and recurring events inside a much larger queer ecosystem. That breadth supports different comfort levels, but dress codes and men-only policies must never be inferred from the city label.",
      "Montreal adds bear and leather venues to a walkable Village, patios, drag, food, and major event weekends. Summer is the easiest social version; winter favors planned indoor stops, and venue-specific language matters more than a broad promise of body positivity.",
    ],
    tags: ["Bears", "Body positive", "Gay travel"],
    href: "/now/collections/best-body-positive-gay-destinations-bears-bigger-guys",
    accent: "emerald",
    sources: [
      source("body-sitges-tourism", "Visit Sitges — Bears Sitges Week", "https://www.visitsitges.com/agenda/bears-sitges-week-2026/", "Official event dates, daytime, cultural, dining, beach, and Bear Village context.", "official"),
      source("body-sitges-org", "Bears Sitges", "https://bearssitges.org/", "Organizer identity, year-round community positioning, map, and programme.", "official"),
      source("body-madrid", "MAD.BEAR", "https://madbear.org/", "Official Madrid bear organization and current event information.", "official"),
      source("body-palm-springs", "Visit Greater Palm Springs — LGBTQ+", "https://www.visitgreaterpalmsprings.com/lgbtq/", "Official resort, LGBTQ+ event, and destination context.", "official"),
      source("body-ptown", "Provincetown Bears", "https://ptownbears.org/", "Official Bear Week organizer and current programme context.", "official"),
      source("body-montreal", "Tourisme Montréal — The Village", "https://www.mtl.org/en/city/about-montreal/neighbourhoods/montreal-the-village", "Official neighborhood, event, venue, and seasonal context.", "official"),
    ],
  }, "Published with a body-positive editorial test, six year-round destination routes, direct organizer sources, and explicit limits on what bear branding guarantees."),

  editorial({
    id: "best-lgbtq-destinations-first-international-trip",
    slug: "best-lgbtq-destinations-first-international-trip",
    title: "Best LGBTQ+ Destinations for First-Time International Travelers",
    eyebrow: "A confident first crossing",
    filter: "access",
    intent: "best LGBTQ destinations first international trip gay travel beginner",
    summary: "Six cities where arrival, transit, queer orientation, and a worthwhile wider trip are unusually easy to understand.",
    methodology: "Selected for airport-to-city simplicity, public transport, concentrated or well-documented queer geography, broad visitor infrastructure, current LGBTQ+ context, and enough non-nightlife value to recover from inevitable first-trip mistakes. No destination is universally safe; laws, lived experience, documentation, identity, race, disability, and neighborhood conditions are assessed separately.",
    bestFor: "Queer travelers planning their first trip across a national border",
    mood: "Reassuring, exciting, easy to decode",
    price: "Mixed",
    editorialNote: "A good first international destination reduces avoidable friction without making the trip bland. These cities offer clear arrival logistics and queer points of orientation, while still rewarding curiosity beyond the familiar visitor district.",
    updated: "7 September 2026",
    cities: ["Amsterdam", "Madrid", "Copenhagen", "Montreal", "Lisbon", "Brighton"],
    items: ["Amsterdam", "Madrid", "Copenhagen", "Montreal", "Lisbon", "Brighton"],
    itemNotes: [
      "Amsterdam offers direct airport rail, English-friendly visitor infrastructure, compact central geography, LGBTQ+ history, and several distinct queer scenes. The center is easy to over-tour; use the tram and ferry network to avoid reducing the city to canals and Reguliersdwarsstraat.",
      "Madrid makes orientation simple through metro access, Chueca’s central position, late street life, museums, food, and a substantial official LGBTQ+ guide. The clock is the adjustment: dinner and nightlife begin later than many first-time visitors expect.",
      "Copenhagen’s airport metro reaches the center quickly, and much of the queer bar geography sits near City Hall and the Latin Quarter. Clear wayfinding and a compact core reduce friction; price, not complexity, is the main planning constraint.",
      "Montreal combines bilingual visitor services, metro-linked neighborhoods, a highly visible Village, and culture that works beyond nightlife. Border documentation and winter weather deserve more preparation than the city layout itself.",
      "Lisbon provides a manageable center, metro connection, established queer areas, food, viewpoints, and easy coastal extensions. Hills and cobbles are genuine accessibility factors, and late-night transport should be planned rather than assumed.",
      "Brighton is a small, readable seaside destination with a concentrated Kemptown scene, community center, queer history, and straightforward rail arrival from London Gatwick. It works best as a first international city break rather than a single-stop introduction to the entire UK.",
    ],
    tags: ["First trip", "International travel", "Planning"],
    href: "/now/collections/best-lgbtq-destinations-first-international-trip",
    accent: "cyan",
    sources: [
      source("first-trip-booking", "Booking.com — Travel Proud research 2026", "https://news.booking.com/closet-cationers-latest-bookingcom-research-reveals-majority-of-lgbtq-travelers-conceal-their-identity-when-traveling/", "Current evidence on identity concealment, planning, and traveler confidence.", "research"),
      source("first-trip-iglta", "IGLTA — LGBTQ+ Safety Guide", "https://www.iglta.org/destinations/travel-guides/lgbtq-safety-guide/", "Identity-aware preparation, local context, documents, and emergency planning.", "research"),
      source("first-trip-amsterdam", "I amsterdam — LGBTQI+", "https://www.iamsterdam.com/en/whats-on/lgbtqi", "Official queer events, culture, nightlife, and visitor orientation.", "official"),
      source("first-trip-madrid", "Tourism Madrid — LGBT guide", "https://www.esmadrid.com/en/madrid-lgbt", "Official neighborhood, culture, events, and nightlife guidance.", "official"),
      source("first-trip-copenhagen", "Visit Copenhagen — LGBTQIA+ guide", "https://www.visitcopenhagen.com/copenhagen/this-is-copenhagen/reasons-to-go/the-ultimate-lgbtqia-guide-to-copenhagen", "Official queer geography, history, culture, and venue context.", "official"),
      source("first-trip-brighton", "Visit Brighton — LGBTQIA+", "https://www.visitbrighton.com/plan-your-visit/about-the-area/lgbtqia", "Official compact queer neighborhood, community, and arrival context.", "official"),
    ],
  }, "Published with a first-international-trip friction model, identity-aware safety caveats, and six practical arrival-to-neighborhood routes."),

  editorial({
    id: "best-queer-nightlife-cities-without-techno",
    slug: "best-queer-nightlife-cities-without-techno",
    title: "Best Queer Nightlife Cities If You Don’t Like Techno",
    eyebrow: "A different dance floor",
    filter: "nightlife",
    intent: "best queer nightlife cities without techno gay pop drag cabaret",
    summary: "Six cities where drag, pop, cabaret, karaoke, live performance, Latin music, and neighborhood bars can carry the night.",
    methodology: "Selected for consistent queer nightlife formats that are not dependent on techno: drag and cabaret, pop floors, piano or karaoke, live performance, Latin and local genres, and conversational bars. Individual listings describe a route, not a promise that every venue in the city avoids electronic music.",
    bestFor: "Travelers who want a full queer night without treating a hard techno floor as compulsory",
    mood: "Theatrical, melodic, social",
    price: "Drinks to ticketed shows",
    editorialNote: "‘Not techno’ is not code for ‘quiet.’ These are cities where a night can be loud, sweaty, camp, musical, or spectacular—just driven by a different soundtrack and a more varied set of rooms.",
    updated: "7 September 2026",
    cities: ["London", "Madrid", "New York", "Montreal", "Bangkok", "Mexico City"],
    items: ["London: cabaret, pubs, pop and performance", "Madrid: drag, divas and Spanish pop", "New York: piano, drag, disco and live rooms", "Montreal: Mado, karaoke and Village bars", "Bangkok: drag spectacle and commercial dance", "Mexico City: drag, reggaeton and cabaret"],
    itemNotes: [
      "London can move from a historic pub to Two Brewers cabaret, an East London performance room, or a pop-led club without touching a techno bill. The variety is the asset; long cross-city transfers are the reason to commit to one cluster each night.",
      "Madrid’s Chueca supports drag-hosted bars, mainstream pop, Spanish divas, karaoke, and performance at rooms such as DLRO Live. Parties change venue, but the central district makes it practical to redirect the night on foot.",
      "New York offers piano-bar singalongs, close-up drag, Broadway voices, disco, lesbian bars, comedy, and hybrid live rooms. West Village and Hell’s Kitchen work as separate routes; adding Bushwick expands choice but changes the logistics.",
      "Montreal’s Village gives non-techno travelers Cabaret Mado, karaoke, drag, patios, and accessible bar-to-bar movement. Programming may switch between French and English, which is part of the city’s character rather than a barrier to every show.",
      "Bangkok’s Silom circuit is built around polished drag shows, commercial pop, social bars, and large-format dance as much as electronic club culture. Showtimes and audience policies vary, so choose the performance first and let the wider night follow.",
      "Mexico City supports drag cabaret, reggaeton, pop, karaoke, and flamboyant multi-room venues across Zona Rosa, Centro, and beyond. Distances and late hours make app-based transport and one-neighborhood planning more useful than an ambitious bar crawl.",
    ],
    tags: ["Nightlife", "Drag and cabaret", "Pop"],
    href: "/now/collections/best-queer-nightlife-cities-without-techno",
    accent: "rose",
    sources: [
      source("no-techno-london", "Visit London — LGBTQ+ bars and clubs", "https://www.visitlondon.com/things-to-do/food-and-drink/pub-and-bar/gay-bar", "Official cabaret, drag, burlesque, live music, pop, and pub context.", "official"),
      source("no-techno-madrid", "Tourism Madrid — DLRO Live", "https://www.esmadrid.com/en/nightlife/delirio-live", "Official drag, singer, dance, themed-night, and performance context.", "official"),
      source("no-techno-montreal", "Tourisme Montréal — The Village", "https://www.mtl.org/en/city/about-montreal/neighbourhoods/montreal-the-village", "Official drag, restaurants, terraces, bars, and neighborhood context.", "official"),
      source("no-techno-nyc", "NYC Tourism — LGBTQ+", "https://www.nyctourism.com/articles/lgbtq-guide/", "Official queer neighborhood, culture, entertainment, and nightlife orientation.", "official"),
      source("no-techno-bangkok", "Tourism Authority of Thailand — Travel Proud", "https://www.tourismthailand.org/Articles/travel-proud-en", "Official LGBTQ+ hospitality and destination context.", "official"),
      source("no-techno-mexico", "Mexico City — Zona Rosa for LGBTQ+ travelers", "https://www.mexicocity.cdmx.gob.mx/venues/zona-rosa-lgbt/?lang=en", "Official gay and lesbian nightlife, district history, and venue-turnover context.", "official"),
    ],
  }, "Published with six music-and-format-specific nightlife routes and a clear distinction between city variety and individual event programming."),

  editorial({
    id: "best-quiet-lgbtq-escapes-couples",
    slug: "best-quiet-lgbtq-escapes-couples",
    title: "Best Quiet LGBTQ+ Escapes for Couples",
    eyebrow: "Less noise, more time together",
    filter: "stays",
    intent: "best quiet LGBTQ escapes couples romantic gay lesbian travel",
    summary: "Six lower-pressure escapes where walking, water, food, culture, and shared time matter more than a packed queer nightlife schedule.",
    methodology: "Selected for a calmer daily rhythm, compact routes, nature or waterfront access, couple-worthy food and culture, and a visible or documented LGBTQ+ welcome. Quiet describes the proposed itinerary, not the absence of local life; public affection and safety still depend on context and identity.",
    bestFor: "Couples who want queer ease, good days, and room in the itinerary",
    mood: "Intimate, restorative, softly social",
    price: "Mid-range to premium",
    editorialNote: "This is deliberately different from a honeymoon fantasy list. The test is whether an ordinary two-person escape can feel complete with one neighborhood, one long meal, one landscape, and no obligation to chase the biggest night.",
    updated: "7 September 2026",
    cities: ["Copenhagen", "Ljubljana", "Valencia", "Brighton", "Porto", "Reykjavik"],
    items: ["Copenhagen’s canals and Frederiksberg", "Ljubljana and the river", "Valencia from Turia to the sea", "Brighton and the South Downs", "Porto and Foz do Douro", "Reykjavik and a geothermal day"],
    itemNotes: [
      "Copenhagen can be edited down beautifully: canals in Christianshavn, design, a harbor sauna, a long dinner, and a park walk in Frederiksberg. The airport metro and compact core protect a short escape from excessive logistics.",
      "Ljubljana’s car-light center, riverside cafes, castle, cultural spaces, and nearby green routes create a gentle weekend with an identifiable LGBTQ+ community context. The queer scene is small, so choose it for intimacy and city texture rather than abundance.",
      "Valencia lets a couple cycle or walk through the Turia gardens, explore markets and architecture, and finish at the Mediterranean. Its center is manageable and its queer infrastructure visible; major festivals and Gay Games dates produce a much louder version.",
      "Brighton pairs Kemptown’s everyday queer visibility with the seafront, independent food, the Royal Pavilion, and easy access to the South Downs. Summer weekends can be busy, while shoulder-season dates better match the quiet-escape promise.",
      "Porto works as a slow sequence of tiled streets, river views, markets, galleries, dinner, and an Atlantic walk at Foz. The queer scene is modest and hills are substantial, but a compact itinerary allows the relationship—not venue collecting—to remain central.",
      "Reykjavik offers a small city base, visible queer community, design and food, then geothermal water or landscape beyond the center. Weather and excursion conditions can reshape the plan quickly, so leave real slack rather than scheduling every hour.",
    ],
    tags: ["Couples", "Quiet travel", "Slow city breaks"],
    href: "/now/collections/best-quiet-lgbtq-escapes-couples",
    accent: "violet",
    sources: [
      source("quiet-copenhagen", "Visit Copenhagen — Romantic weekend", "https://www.visitcopenhagen.com/copenhagen/planning/a-romantic-weekend-in-copenhagen-the-perfect-friday-to-sunday-itinerary", "Official couples itinerary, neighborhoods, transport, design, and wellness context.", "official"),
      source("quiet-ljubljana", "Visit Ljubljana — LGBTQI+", "https://www.visitljubljana.com/en/visitors/travel-information/lgbtqi", "Official queer community, organizations, culture, bars, and festivals.", "official"),
      source("quiet-ljubljana-green", "Visit Ljubljana — Things to do", "https://www.visitljubljana.com/en/visitors/sights-and-activities/things-to-do-in-ljubljana", "Official compact-center, river, neighborhood, cycling, and nature context.", "official"),
      source("quiet-valencia", "Visit Valencia — LGBTIQ+ friendly", "https://www.visitvalencia.com/en/what-to-do-valencia/valencia-lgbti-friendly-city", "Official city scale, walking, nature, culture, and LGBTQ+ context.", "official"),
      source("quiet-brighton", "Visit Brighton — LGBTQIA+", "https://www.visitbrighton.com/plan-your-visit/about-the-area/lgbtqia", "Official seafront, Kemptown, community, culture, and South Downs context.", "official"),
      source("quiet-iceland", "Visit Reykjavík — LGBTQ+ Reykjavík", "https://visitreykjavik.is/lgbtq-reykjavik", "Official LGBTQ+ city, culture, and visitor context.", "official"),
    ],
  }, "Published with six couple-first slow routes, explicit seasonal trade-offs, and a clear distinction from honeymoon and nightlife collections."),

  editorial({
    id: "best-lgbtq-cities-48-hour-weekend",
    slug: "best-lgbtq-cities-48-hour-weekend",
    title: "Best LGBTQ+ Cities for a 48-Hour Weekend",
    eyebrow: "Two days, one smart route",
    filter: "neighborhoods",
    intent: "best LGBTQ cities 48 hour weekend gay city break itinerary",
    summary: "Six compact city edits designed around arrival friction, one strong base, and a realistic queer route from Friday to Sunday.",
    methodology: "Selected for direct arrival, public transport, concentrated visitor and queer geography, strong daytime value, and enough evening choice to recover when one plan changes. Each pick is a route architecture rather than a minute-by-minute schedule; opening times and current events must be checked before travel.",
    bestFor: "Travelers who want a complete queer city break without pretending 48 hours can cover an entire capital",
    mood: "Focused, energetic, achievable",
    price: "Mixed",
    editorialNote: "The premium move on a short weekend is subtraction. Stay near the route, group experiences by neighborhood, protect one flexible evening, and leave the airport-day fantasy itinerary behind.",
    updated: "7 September 2026",
    cities: ["Madrid", "Amsterdam", "Copenhagen", "Lisbon", "Montreal", "Berlin"],
    items: ["Madrid: Chueca, the Prado edge and Retiro", "Amsterdam: canals, queer history and De Pijp", "Copenhagen: Latin Quarter to the harbor", "Lisbon: Príncipe Real to Alfama", "Montreal: the Village and Plateau", "Berlin: Schöneberg plus one cultural axis"],
    itemNotes: [
      "Base near Chueca. Use Saturday for the Prado–Retiro axis and a long lunch, then return to the neighborhood for drag, bars, or dancing; reserve Sunday morning for Malasaña or a market rather than attempting a Toledo day trip.",
      "Stay inside the tram ring but outside the most compressed station streets. Pair canal and museum time with Homomonument and Reguliersdwarsstraat, then give the second half-day to De Pijp or Noord instead of crossing the city repeatedly.",
      "Let the airport metro do the work. Connect the Latin Quarter’s queer history and bars with design, Christianshavn canals, and one harbor experience; distances are small enough to preserve spontaneity if weather changes.",
      "Use Príncipe Real as the hinge between queer evening life, Baixa, viewpoints, and a westward tram or train. Alfama and the river can fill one coherent day; skip a Sintra detour unless the city itself is not the priority.",
      "Stay near a useful metro interchange. The Village supplies an easy first evening, while the Plateau or Mile End adds food and neighborhood texture on Saturday; seasonal street life makes summer notably easier than deep winter.",
      "Choose one Berlin. Schöneberg plus the Kulturforum and Tiergarten creates a coherent classic route; Kreuzberg or Neukölln creates another. Combining all three in 48 hours sacrifices the very neighborhood depth that makes Berlin useful.",
    ],
    tags: ["48 hours", "Weekend", "City routes"],
    href: "/now/collections/best-lgbtq-cities-48-hour-weekend",
    accent: "cyan",
    sources: [
      source("48-madrid", "Tourism Madrid — LGBT Madrid", "https://www.esmadrid.com/en/madrid-lgbt", "Official Chueca, culture, event, shopping, and nightlife context.", "official"),
      source("48-amsterdam", "I amsterdam — LGBTQI+", "https://www.iamsterdam.com/en/whats-on/lgbtqi", "Official queer history, culture, events, and neighborhood context.", "official"),
      source("48-copenhagen", "Visit Copenhagen — Romantic weekend", "https://www.visitcopenhagen.com/copenhagen/planning/a-romantic-weekend-in-copenhagen-the-perfect-friday-to-sunday-itinerary", "Official Friday-to-Sunday structure, airport metro, and neighborhood timing.", "official"),
      source("48-lisbon", "Visit Lisboa", "https://www.visitlisboa.com/en", "Official neighborhoods, transport, cultural attractions, and coast planning.", "official"),
      source("48-montreal", "Tourisme Montréal — The Village", "https://www.mtl.org/en/city/about-montreal/neighbourhoods/montreal-the-village", "Official metro-linked queer neighborhood and seasonal context.", "official"),
      source("48-berlin", "visitBerlin — LGBTQ+ Berlin", "https://www.visitberlin.de/en/lgbtq-berlin", "Official queer neighborhoods, culture, history, and trip-planning context.", "official"),
    ],
  }, "Published with six realistic Friday-to-Sunday routes, neighborhood-level constraints, and a subtraction-first short-trip method."),
];
