const spanish = (copy) => Object.freeze(copy);

const SPANISH_COLLECTION_SEARCH_TERMS = Object.freeze({
  "best-queer-techno-clubs-world": ["mejores clubs techno queer", "clubes techno gay", "fiestas techno LGBTQ+"],
  "best-queer-beaches-europe": ["mejores playas gay de Europa", "playas queer Europa", "playas LGBTQ+ Europa"],
  "best-lesbian-bars-europe": ["mejores bares lésbicos de Europa", "bares sáficos Europa", "bares para lesbianas"],
  "best-drag-venues": ["mejores shows drag", "bares drag", "locales de drag queer"],
  "hidden-queer-cafes": ["cafés queer", "cafeterías LGBTQ+", "lugares queer tranquilos"],
  "best-first-night-bars-solo": ["bares gay para viajar solo", "primera noche queer", "viaje LGBTQ+ en solitario"],
  "best-queer-neighborhoods-world": ["mejores barrios gay del mundo", "barrios queer", "zonas LGBTQ+"],
  "best-lgbtq-destinations-solo-travel": ["mejores destinos LGBTQ+ para viajar solo", "viaje gay solo", "viaje queer en solitario"],
  "best-queer-nightlife-districts": ["mejores zonas de vida nocturna gay", "distritos queer", "barrios gay para salir"],
  "best-pride-festivals-worth-travelling-for": ["mejores Pride del mundo", "festivales LGBTQ+ 2026", "viajes para el Orgullo"],
  "emerging-queer-destinations": ["destinos queer emergentes", "ciudades gay alternativas", "nuevos destinos LGBTQ+"],
  "best-destinations-trans-nonbinary-travelers": ["viajes trans seguros", "destinos para personas no binarias", "destinos LGBTQ+ trans"],
  "best-affordable-lgbtq-city-breaks": ["destinos gay baratos", "escapadas LGBTQ+ económicas", "ciudades queer asequibles"],
  "best-sapphic-city-breaks-world": ["viajes sáficos", "escapadas lésbicas", "ciudades para lesbianas"],
  "best-lgbtq-honeymoon-destinations": ["luna de miel gay", "luna de miel LGBTQ+", "viajes queer en pareja"],
  "best-queer-nightlife-cities-without-techno": ["vida nocturna gay sin techno", "bares queer con drag", "salir de fiesta LGBTQ+"],
  "best-lgbtq-cities-48-hour-weekend": ["escapada gay de fin de semana", "ciudades LGBTQ+ para 48 horas", "viaje queer corto"],
});

export const SPANISH_COLLECTIONS = Object.freeze({
  "best-queer-techno-clubs-world": spanish({
    title: "Los mejores clubs de techno queer del mundo", eyebrow: "Después de medianoche", summary: "Una ruta precisa por clubs y ciudades de fiesta conocidos por sus pistas queer, sonido contundente, cultura de puerta y energía nocturna.", methodology: "Seleccionada por relevancia queer, fuerza de la noche local, profundidad de programación, utilidad para visitantes y contexto de seguridad actual.", bestFor: "Viajeras y viajeros que priorizan el sonido, noches largas y pistas expresivas", mood: "Oscuro, cinético, sin concesiones", price: "Variado", editorialNote: "No es una lista de fantasía de terciopelo: reúne salas donde la música, la autoría queer y el carácter del público importan tanto como la escala.", tags: ["Techno", "Vida nocturna", "Global"],
    itemNotes: ["El punto de referencia berlinés: sonido serio, noche larga y una puerta que premia leer la sala.", "La opción comunitaria de Ámsterdam para programación audaz y una pista intencional.", "Un contrapunto ibicenco donde producción y espectáculo encuentran un ritmo nocturno más pulido.", "Intensidad londinense: identidad musical, sesiones largas y público dispuesto a quedarse.", "Una opción parisina para priorizar vida nocturna inequívocamente queer frente a un superclub anónimo.", "Una llegada neoyorquina más abierta: aire libre, selectores sólidos y espacio para una ruta de día a noche."],
  }),
  "best-queer-beaches-europe": spanish({
    title: "Las mejores playas gay y queer de Europa", eyebrow: "Escapadas de playa", summary: "Playas y pueblos costeros donde visibilidad queer, ritmo social de día y vida nocturna cercana crean un destino completo.", methodology: "Selección basada en datos de ciudades del Atlas, rutas de playa conocidas, peso de eventos estivales, accesibilidad y contexto de seguridad.", bestFor: "Viajes guiados por el sol que también necesitan un ritmo social queer sencillo", mood: "Abierto, luminoso, pausado", price: "De gratis a premium", editorialNote: "Una playa queer rara vez es solo un punto en la arena: estas selecciones funcionan por el pueblo, el transporte, la tarde social y las opciones después del atardecer.", tags: ["Playa", "Europa", "Verano"],
    itemNotes: ["El día de playa más completo: visible, social y conectado de forma natural con la noche de Sitges.", "Más que un lugar único, es un ritmo útil entre el agua y la noche compacta de La Nogalera.", "Para una experiencia de playa más intensa y producida, diseñada para continuar hasta la noche.", "Un clásico de Gran Canaria centrado en el paisaje; cuenta con distancia, calor y otro ritmo.", "La opción práctica de ciudad y mar en Barcelona sin renunciar al resto de la ciudad.", "Una base maltesa flexible para quien prefiere una ruta urbana de verano a una única playa señalada."],
  }),
  "best-lesbian-bars-europe": spanish({
    title: "Los mejores bares lésbicos de Europa", eyebrow: "Noches sáficas", summary: "Una selección editorial de bares lésbicos, noches lideradas por mujeres, espacios sáficos y comunidades que merecen mayor visibilidad.", methodology: "Prioriza locales lésbicos permanentes cuando existen, después noches recurrentes lideradas por mujeres, seguridad inclusiva y consistencia comunitaria.", bestFor: "Viajeras sáficas que buscan espacios propios y programación liderada por mujeres", mood: "Social, comunitario, diverso", price: "Mayormente accesible", editorialNote: "Los bares lésbicos permanentes son escasos; esta selección distingue entre locales dedicados, noches recurrentes y rutas sáficas sin fingir que son lo mismo.", tags: ["Bares lésbicos", "Liderado por mujeres", "Europa"],
    itemNotes: ["Un local céntrico londinense con la inmediatez de un bar compacto y no de una cita mensual.", "Un ancla cálida en Neukölln para conversación, comunidad y una noche menos performativa.", "Madrid funciona mejor como ruta: consulta el calendario de noches lideradas por mujeres.", "París con filo activista y cultural; ve por su carácter comunitario, no por coreografía de cócteles.", "Una elección guiada por calendario: promotora, sala y público cambian, así que importa el detalle actual.", "Las experiencias sáficas más fuertes de Ámsterdam viven en la programación; elige la noche antes que la dirección."],
  }),
  "best-drag-venues": spanish({
    title: "Los mejores espacios de drag", eyebrow: "Salas de espectáculo", summary: "Cabarets, bares drag y espacios donde el show no es decoración: es la razón por la que la sala tiene pulso.", methodology: "Valora consistencia de programación, reputación drag local, utilidad para visitantes, atmósfera y conexión con eventos urbanos.", bestFor: "Quien quiere que el show sea el evento principal", mood: "Teatral, ruidoso, juguetón", price: "De copas a espectáculos con entrada", editorialNote: "La mejor sala drag no siempre es la mayor: priorizamos lugares donde quienes actúan sostienen la sala y el público entiende que el drag es cultura, trabajo y noche.", tags: ["Drag", "Espectáculo", "Vida nocturna"],
    itemNotes: ["Energía de performance del este de Londres en una sala construida alrededor del trabajo queer.", "Un bar neoyorquino de alta energía para shows cercanos, interacción y una noche clásica del Village.", "Espectáculo de Bangkok con producción pulida y un reparto que define la identidad de la sala.", "Un clásico de Mánchester donde cabaret y ambiente de bar de barrio caben en la misma noche.", "Una referencia madrileña para presentaciones afiladas, drag en español y una sala que sigue al escenario.", "Una experiencia de Manila de gran formato, extrovertida y pensada como una noche completa."],
  }),
  "hidden-queer-cafes": spanish({
    title: "Cafés queer escondidos", eyebrow: "Descubrimiento tranquilo", summary: "Cafés, librerías, terrazas y espacios diurnos de baja presión para entrar en la vida queer sin empezar a medianoche.", methodology: "Selección basada en contexto de guías urbanas, lugares tipo café del Atlas, historias de miembros y utilidad social tranquila.", bestFor: "Conexión de día, llegadas en solitario y descubrimiento queer más calmado", mood: "Suave, local, atento", price: "Amigable con el presupuesto", editorialNote: "Son puntos de partida deliberadamente tranquilos: algunos son espacios queer dedicados y otros rutas donde la vida queer se ve sin exigir entrada a un club.", tags: ["Cafés", "Joyas escondidas", "De día"],
    itemNotes: ["Mejor como paseo lento entre librerías, terrazas y calles queer conocidas, no como un único mostrador obligatorio.", "Ámsterdam fuera del circuito visitante más ruidoso, con espacio para café, conversación y una tarde sin presión.", "Una apertura lisboeta para quien busca barrio creativo antes de decidir el tono de la noche.", "El Village de Montreal se lee especialmente bien de día, útil para orientarse sin comprometerse con una salida.", "Una ruta comunitaria de Zagreb donde el contexto cultural y la agenda local importan más que la hospitalidad brillante.", "Palermo recompensa caminar: usa la ruta como puente entre cafés, diseño, cena y el ritmo queer posterior."],
  }),
  "best-first-night-bars-solo": spanish({
    title: "Los mejores bares para una primera noche queer a solas", eyebrow: "Amigable para viajar a solas", summary: "Primeras paradas accesibles donde quien viaja sola o solo puede leer la ciudad, hablar con gente y decidir el ritmo de la noche.", methodology: "Pondera barrios legibles, espacios sociales, facilidad de transporte, contexto de seguridad y una primera decisión sin fricción.", bestFor: "Llegadas en solitario que buscan una primera parada clara, no una gran noche forzada", mood: "Acogedor, conversacional, flexible", price: "Principalmente precio medio", editorialNote: "Un buen primer bar deja opciones: quedarte, conocer a alguien o salir con una lectura más clara de la ciudad. Estas rutas priorizan esa libertad antes que el hype.", tags: ["Viaje en solitario", "Bares", "Seguridad"],
    itemNotes: ["Berlín sin empezar por la puerta más dura: calles queer consolidadas ayudan a leer la noche en tiempo real.", "Geografía compacta y ritmo de bares temprano para probar el ambiente sin sobreplanificar.", "El Village de Toronto ofrece varias opciones cercanas y una salida sencilla si una sala no encaja.", "La ruta de Kemptown en Brighton funciona por proximidad: empieza pequeño, camina y deja que el público decida.", "Un inicio lisboeta con terrazas y conversación antes de que la noche crezca en otro sitio.", "Fitzroy encaja con quien prefiere textura de barrio y salas sociales mixtas a un distrito gay formal."],
  }),
  "best-queer-neighborhoods-world": spanish({ title: "Los mejores barrios queer del mundo", eyebrow: "Textura urbana", summary: "Ocho barrios donde historia queer, visibilidad cotidiana, hospitalidad y vida nocturna siguen siendo una puerta útil hacia la ciudad.", methodology: "Seleccionada por identidad queer duradera, concentración de lugares útiles, historia pública, legibilidad para visitantes y evidencia de vida más allá del Pride.", bestFor: "Quien decide dónde alojarse, caminar, comer y empezar la noche", mood: "Visible, complejo, vivido", price: "De económico a premium", editorialNote: "Un barrio queer vale cuando ayuda a leer una ciudad, no solo cuando un mapa repite una etiqueta antigua.", tags: ["Barrios", "Cultura", "Vida nocturna"] }),
  "best-lgbtq-destinations-solo-travel": spanish({ title: "Los mejores destinos LGBTQ+ para viajar a solas", eyebrow: "A tu manera", summary: "Ciudades donde transporte, geografía queer legible, cultura diurna y puntos sociales hacen posible viajar sola o solo sin depender de una app.", methodology: "Pondera navegabilidad, transporte público, espacios queer de baja presión, utilidad diurna, contexto de seguridad y flexibilidad para cambiar de plan.", bestFor: "Viajeras y viajeros independientes que quieren opciones sin sobreplanificar", mood: "Abierto, flexible, autónomo", price: "Variado", editorialNote: "El mejor destino en solitario permite cambiar de idea: entrar en una sala, salir, caminar a un lugar más tranquilo o tener un día completo sin depender de la noche.", tags: ["Viaje en solitario", "Escapadas urbanas", "Práctico"] }),
  "best-queer-nightlife-districts": spanish({ title: "Los mejores barrios de vida nocturna queer", eyebrow: "Geografía nocturna", summary: "Ocho distritos para construir una noche a pie o con un trayecto corto, cada uno con su mezcla de locales, visitantes, bares, clubs y comida tardía.", methodology: "Seleccionada por concentración de noche queer activa, facilidad entre salas, utilidad nocturna y relevancia actual para visitantes.", bestFor: "Quien elige dónde basar un fin de semana centrado en la noche", mood: "Denso, tardío, socialmente legible", price: "Principalmente precio medio", editorialNote: "El mejor distrito nocturno no es el que tiene más locales: es donde una puerta cerrada o un público equivocado no acaba con la noche.", tags: ["Vida nocturna", "Barrios", "Fin de semana"] }),
  "best-pride-festivals-worth-travelling-for": spanish({ title: "Pride y festivales queer que merecen el viaje", eyebrow: "Fechas clave", summary: "Una selección deliberadamente diversa de marchas masivas, encuentros políticos, festivales culturales y semanas de destino que pueden sostener un viaje entero.", methodology: "Seleccionada por relevancia internacional recurrente, carácter local, profundidad cultural o política, utilidad de viaje y continuidad organizadora. Confirma fechas oficiales antes de reservar.", bestFor: "Quien planea un viaje alrededor de un gran encuentro queer", mood: "Colectivo, público, celebratorio", price: "De marchas gratis a festivales con entrada", editorialNote: "Pride no es un solo producto: una marcha multitudinaria, una manifestación trans y una semana en una playa queer piden cosas distintas a quien viaja.", tags: ["Pride", "Festivales", "Eventos"] }),
  "emerging-queer-destinations": spanish({ title: "Destinos queer emergentes más allá de las capitales habituales", eyebrow: "Energía de próxima ciudad", summary: "Ocho ciudades donde organizadores, espacios independientes, cultura y una escala más local son una alternativa convincente al circuito habitual.", methodology: "Seleccionada entre ciudades con infraestructura LGBTQ+ anual identificable, eventos públicos recurrentes, lugares útiles y profundidad cultural suficiente para sostener un viaje.", bestFor: "Quien repite viaje y prefiere textura local a mitología de escena", mood: "Independiente, cambiante, específico de cada ciudad", price: "Principalmente accesible", editorialNote: "Estas ciudades no esperan ser descubiertas por visitantes: ya tienen historias y comunidades queer; lo que emerge es su visibilidad para una audiencia viajera más amplia.", tags: ["Ciudades emergentes", "Cultura local", "Alternativas"] }),
  "best-destinations-trans-nonbinary-travelers": spanish({ title: "Mejores destinos para viajeros trans y no binarios", eyebrow: "Viajar con contexto", summary: "Destinos seleccionados por señales prácticas de inclusión, comunidad, acceso a servicios y utilidad real para personas trans y no binarias.", methodology: "Valora derechos, aceptación vivida, infraestructura comunitaria, utilidad cotidiana y transparencia sobre límites y contexto local.", bestFor: "Personas trans y no binarias que priorizan información práctica y contexto", mood: "Informado, cuidadoso, afirmativo", price: "Variado", editorialNote: "Ningún destino garantiza una experiencia idéntica para todas las personas: la información local, la documentación y las redes de apoyo siguen importando.", tags: ["Trans", "No binario", "Seguridad"] }),
  "accessible-queer-city-breaks": spanish({ title: "Escapadas queer urbanas más accesibles", eyebrow: "Acceso primero", summary: "Ciudades donde movilidad, información práctica y espacios queer ayudan a planear una escapada con menos fricción.", methodology: "Considera transporte, accesibilidad publicada, concentración de lugares, ritmo urbano y la facilidad de ajustar un plan.", bestFor: "Viajeras y viajeros que necesitan una planificación urbana más accesible", mood: "Práctico, claro, inclusivo", price: "Variado", editorialNote: "La accesibilidad no es una promesa genérica: conviene confirmar accesos, baños, entradas y transporte con cada espacio.", tags: ["Accesibilidad", "Escapadas urbanas", "Planificación"] }),
  "best-queer-cities-beyond-nightlife": spanish({ title: "Mejores ciudades queer más allá de la vida nocturna", eyebrow: "Queer de día", summary: "Ciudades para vivir cultura, historia, cafés, librerías, naturaleza y comunidad sin depender de una pista de baile.", methodology: "Seleccionada por densidad cultural queer, espacios diurnos, historia, comunidad y utilidad para visitantes a distintos ritmos.", bestFor: "Quien quiere un viaje queer completo sin que la noche sea el centro", mood: "Cultural, pausado, conectado", price: "Variado", editorialNote: "Una ciudad queer sólida también se reconoce a pleno día: en sus librerías, museos, cafés, rutas y conversaciones.", tags: ["Cultura", "De día", "Comunidad"] }),
  "sober-queer-nightlife": spanish({ title: "Noches queer sobrias y de bajo consumo de alcohol", eyebrow: "Otra forma de salir", summary: "Espacios, eventos y rutas queer donde la conversación, el espectáculo y la comunidad no dependen de beber.", methodology: "Prioriza alternativas recurrentes, espacios de baja presión, programación cultural y opciones verificables para una noche más sobria.", bestFor: "Quien busca conexión queer sin que el alcohol marque el plan", mood: "Consciente, social, tranquilo", price: "Accesible a medio", editorialNote: "Salir sobria o sobrio no significa renunciar a la energía de una noche; significa elegir una sala que respete otro ritmo.", tags: ["Sobriedad", "Vida nocturna", "Comunidad"] }),
  "best-queer-bookstores-cultural-spaces": spanish({ title: "Librerías y espacios culturales queer que merecen un viaje", eyebrow: "Cultura con memoria", summary: "Librerías, archivos, centros culturales y espacios de encuentro donde la historia queer se conserva, se discute y se vive.", methodology: "Seleccionada por relevancia cultural, programación, continuidad comunitaria, valor para visitantes y conexión con la ciudad.", bestFor: "Quien viaja por cultura queer, libros, historia y conversación", mood: "Curioso, reflexivo, comunitario", price: "Principalmente accesible", editorialNote: "Estos lugares no son solo paradas bonitas: son infraestructura cultural para la memoria, el pensamiento y la comunidad queer.", tags: ["Librerías", "Cultura", "Historia"] }),
  "genuinely-queer-welcoming-hotels": spanish({ title: "Hoteles realmente acogedores con viajeros queer", eyebrow: "Estancias con criterio", summary: "Una selección de hoteles y estancias donde la acogida queer se demuestra con contexto, servicio y relación real con la comunidad.", methodology: "Prioriza señales verificables de inclusión, experiencia de huésped, contexto local y utilidad práctica por encima del marketing arcoíris.", bestFor: "Quien busca una estancia con hospitalidad queer genuina", mood: "Cuidado, cómodo, afirmativo", price: "De medio a premium", editorialNote: "Un hotel inclusivo no se define por una bandera: se nota en políticas, personal, contexto y la experiencia completa de llegar.", tags: ["Hoteles", "Hospitalidad", "Viajes queer"] }),
  "best-lgbtq-beach-towns": spanish({ title: "Las mejores ciudades de playa LGBTQ+", eyebrow: "Mar y comunidad", summary: "Pueblos y ciudades costeras donde playa, visibilidad queer y vida social cercana forman una escapada completa.", methodology: "Seleccionada por conexión entre playa, comunidad, opciones de estancia, vida nocturna y contexto de seguridad.", bestFor: "Quien quiere playa sin renunciar a vida queer y comunidad", mood: "Solar, social, relajado", price: "Variado", editorialNote: "La mejor ciudad de playa LGBTQ+ funciona más allá de la arena: la llegada, la tarde, la cena y la noche también importan.", tags: ["Playa", "LGBTQ+", "Escapadas"] }),
  "best-gay-ski-weeks": spanish({ title: "Las mejores semanas de esquí gay y queer", eyebrow: "Nieve y comunidad", summary: "Semanas de montaña que combinan esquí, comunidad queer, fiestas y logística real para una escapada de invierno.", methodology: "Valora continuidad del evento, calidad de montaña, accesibilidad, alojamiento, comunidad y utilidad para visitantes.", bestFor: "Quien busca nieve, comunidad y programación queer", mood: "Festivo, alpino, colectivo", price: "Premium", editorialNote: "Una semana de esquí queer exige tanto una buena montaña como una organización que haga fácil encontrar comunidad fuera de la pista.", tags: ["Esquí", "Invierno", "Eventos"] }),
  "best-lesbian-sapphic-festivals": spanish({ title: "Los mejores festivales lésbicos y sáficos", eyebrow: "Comunidad sáfica", summary: "Festivales y encuentros donde artistas, comunidad y público sáfico crean una razón propia para viajar.", methodology: "Seleccionada por continuidad, claridad de programación, relevancia comunitaria, seguridad y utilidad para visitantes.", bestFor: "Viajeras sáficas que buscan comunidad, cultura y celebración", mood: "Expresivo, comunitario, festivo", price: "De accesible a premium", editorialNote: "Los mejores encuentros sáficos no se reducen a una fiesta: construyen espacio para cultura, conversación, visibilidad y comunidad.", tags: ["Sáfico", "Festivales", "Mujeres"] }),
  "queer-summer-without-biggest-crowds": spanish({ title: "Verano queer sin las mayores multitudes", eyebrow: "Otra temporada", summary: "Destinos de verano con playa, cultura y señal queer para viajar con más espacio, ritmo y margen.", methodology: "Valora alternativas a los picos masivos, temporada, conexión de transporte, vida local y utilidad para una escapada queer.", bestFor: "Quien busca verano queer con menos presión y más calma", mood: "Ligero, local, pausado", price: "De medio a premium", editorialNote: "Evitar las mayores multitudes no significa renunciar a comunidad: significa elegir fecha, base y ritmo con más intención.", tags: ["Verano", "Escapadas", "Menos multitudes"] }),
  "best-lgbtq-honeymoon-destinations": spanish({ title: "Mejores destinos para una luna de miel LGBTQ+", eyebrow: "Viaje para dos", summary: "Destinos para una luna de miel LGBTQ+ que equilibran intimidad, hospitalidad, contexto y experiencias que justifican el viaje.", methodology: "Considera seguridad, calidad de estancia, experiencias compartidas, accesibilidad y señales reales de bienvenida LGBTQ+.", bestFor: "Parejas que planean una celebración queer cuidada", mood: "Íntimo, especial, relajado", price: "De medio a premium", editorialNote: "Una gran luna de miel no necesita copiar un guion: necesita un lugar donde la pareja pueda estar presente y cómoda.", tags: ["Luna de miel", "Parejas", "LGBTQ+"] }),
  "best-queer-owned-hotels-resorts": spanish({ title: "Mejores hoteles y resorts de propiedad queer", eyebrow: "Hospitalidad con comunidad", summary: "Estancias donde propiedad, programación y relación con comunidad queer aportan algo más que una etiqueta de marketing.", methodology: "Prioriza propiedad o liderazgo queer verificable, reputación de huéspedes, utilidad de viaje y conexión comunitaria.", bestFor: "Quien quiere que el gasto de alojamiento apoye comunidad queer", mood: "Cálido, intencional, hospitalario", price: "De medio a premium", editorialNote: "La propiedad queer no sustituye una buena estancia, pero puede convertir el hotel en parte real de la experiencia y no solo en una cama.", tags: ["Propiedad queer", "Hoteles", "Comunidad"] }),
  "best-affordable-lgbtq-city-breaks": spanish({ title: "Mejores citybreaks LGBTQ+ asequibles", eyebrow: "Viajar mejor con menos", summary: "Ciudades queer donde alojamiento, comida, transporte y vida local permiten una escapada con presupuesto más realista.", methodology: "Compara coste de estancia, transporte, comida, entrada a eventos y profundidad de experiencia, sin prometer precios fijos.", bestFor: "Quien busca una escapada LGBTQ+ con buen valor", mood: "Práctico, vivo, accesible", price: "Económico a medio", editorialNote: "Un destino asequible no es el más barato sobre el papel: es el que permite vivir la ciudad sin que cada decisión agote el presupuesto.", tags: ["Asequible", "Escapadas urbanas", "LGBTQ+"] }),
  "best-sapphic-city-breaks-world": spanish({ title: "Mejores citybreaks sáficos del mundo", eyebrow: "Rutas sáficas", summary: "Ciudades con espacios, programación y vida cultural que ofrecen una escapada sáfica más rica que una sola noche.", methodology: "Valora continuidad de espacios sáficos, eventos liderados por mujeres, cultura, seguridad y utilidad de ciudad completa.", bestFor: "Viajeras sáficas que quieren comunidad y una ciudad para explorar", mood: "Social, cultural, afirmativo", price: "Variado", editorialNote: "Una escapada sáfica fuerte se construye entre cultura de día, programación de noche y espacios donde la comunidad no es una excepción.", tags: ["Sáfico", "Escapadas", "Ciudades"] }),
  "best-bear-weeks-festivals": spanish({ title: "Mejores semanas y festivales bear", eyebrow: "Comunidad bear", summary: "Semanas, festivales y destinos donde la comunidad bear encuentra programación, encuentro y una razón clara para viajar.", methodology: "Selecciona por continuidad, escala comunitaria, claridad de programa, destino y utilidad para visitantes.", bestFor: "Viajeros bear y quienes buscan una escena corporalmente positiva", mood: "Expresivo, social, festivo", price: "De medio a premium", editorialNote: "La mejor semana bear no depende solo de una fiesta: crea espacio para encuentro, comunidad y una ciudad que acompañe el viaje.", tags: ["Bear", "Festivales", "Comunidad"] }),
  "best-queer-wellness-retreats": spanish({ title: "Mejores retiros de bienestar queer", eyebrow: "Descansar con intención", summary: "Retiros y destinos para bajar el ritmo, conectar con bienestar y encontrar una hospitalidad queer más consciente.", methodology: "Valora programas de bienestar, inclusión verificable, calidad de entorno, accesibilidad y utilidad para diferentes ritmos de viaje.", bestFor: "Quien busca descanso, bienestar y contexto queer", mood: "Restaurador, sereno, cuidado", price: "De medio a premium", editorialNote: "El bienestar queer no es solo spa: también es poder descansar sin explicar quién eres ni encogerte en el espacio.", tags: ["Bienestar", "Retiros", "Queer"] }),
  "best-cities-queer-food-restaurants": spanish({ title: "Mejores ciudades para comida y restaurantes queer", eyebrow: "Comer es cultura", summary: "Ciudades donde gastronomía, comunidad y vida queer se cruzan en mercados, cafés, restaurantes y largas sobremesas.", methodology: "Valora profundidad gastronómica, cultura queer local, diversidad de barrios, accesibilidad y utilidad para visitantes.", bestFor: "Quien viaja siguiendo comida, conversación y cultura queer", mood: "Generoso, social, local", price: "Variado", editorialNote: "La comida queer no siempre tiene una dirección señalada: vive en barrios, sobremesas, mercados y las personas con quienes compartes mesa.", tags: ["Comida", "Restaurantes", "Cultura"] }),
  "best-gay-friendly-destinations-over-40": spanish({ title: "Mejores destinos gay-friendly para mayores de 40", eyebrow: "Viajar a tu ritmo", summary: "Destinos queer con cultura, hoteles, gastronomía y comunidad para una escapada más allá del guion de club nocturno.", methodology: "Valora calidad de estancia, cultura, vida social, accesibilidad, seguridad y amplitud de experiencias.", bestFor: "Personas mayores de 40 que buscan viajes queer con profundidad", mood: "Cómodo, sofisticado, social", price: "De medio a premium", editorialNote: "Un gran viaje queer no tiene edad única: depende de poder elegir ritmo, conversación, cultura y noche en tus propios términos.", tags: ["Mayores de 40", "Gay-friendly", "Viajes"] }),
  "best-sapphic-destinations-solo-travelers": spanish({ title: "Mejores destinos sáficos para viajar sola", eyebrow: "Sola, conectada", summary: "Ciudades y destinos donde las viajeras sáficas encuentran cultura, espacios, programación y una entrada comunitaria más clara.", methodology: "Prioriza continuidad de programación sáfica, seguridad, cultura diurna, espacios de baja presión y navegabilidad.", bestFor: "Viajeras sáficas que quieren independencia y posibilidades de conexión", mood: "Seguro, social, autónomo", price: "Variado", editorialNote: "Viajar sola no implica viajar aislada: la mejor ciudad ofrece opciones para entrar, quedarse o cambiar de plan sin presión.", tags: ["Sáfico", "Viaje en solitario", "Comunidad"] }),
  "best-body-positive-gay-destinations-bears-bigger-guys": spanish({ title: "Destinos gay más inclusivos para bears y cuerpos grandes", eyebrow: "Cuerpo y pertenencia", summary: "Destinos y comunidades donde cuerpos diversos, cultura bear y vida gay encuentran una bienvenida más amplia y visible.", methodology: "Valora continuidad de espacios bear, programación, cultura corporal positiva, seguridad y utilidad para visitantes.", bestFor: "Bears, hombres corpulentos y quien busca una escena gay más corporalmente inclusiva", mood: "Abierto, afirmativo, social", price: "Variado", editorialNote: "La inclusión corporal no es un filtro estético: es poder entrar en una sala y sentir que no tienes que reducirte para pertenecer.", tags: ["Bear", "Cuerpo positivo", "Gay"] }),
  "best-lgbtq-destinations-first-international-trip": spanish({ title: "Mejores destinos LGBTQ+ para tu primer viaje internacional", eyebrow: "Primer gran paso", summary: "Destinos que hacen más fácil una primera experiencia internacional LGBTQ+ con transporte, señal queer, cultura y planificación clara.", methodology: "Pondera navegabilidad, visibilidad, transporte, opciones de estancia, contexto de seguridad y facilidad de orientar el viaje.", bestFor: "Quien prepara su primer viaje LGBTQ+ fuera de su país", mood: "Claro, acogedor, confiado", price: "Variado", editorialNote: "El primer viaje internacional no necesita ser el más lejano ni el más intenso: necesita darte confianza para hacer el siguiente.", tags: ["Primer viaje", "LGBTQ+", "Planificación"] }),
  "best-queer-nightlife-cities-without-techno": spanish({ title: "Mejores ciudades queer para salir sin techno", eyebrow: "Otra pista", summary: "Ciudades donde drag, pop, cabaret, bares, actuaciones y comunidad sostienen una gran noche queer sin depender del techno.", methodology: "Valora variedad de programación, espacios de espectáculo, bares, cultura y utilidad para distintos gustos musicales.", bestFor: "Quien quiere vida nocturna queer más allá de la pista techno", mood: "Teatral, social, diverso", price: "De accesible a medio", editorialNote: "La vida nocturna queer no tiene un único sonido: una gran ciudad ofrece elección, desde un cabaret hasta una conversación larga en un bar.", tags: ["Vida nocturna", "Drag", "Pop"] }),
  "best-quiet-lgbtq-escapes-couples": spanish({ title: "Escapadas LGBTQ+ tranquilas para parejas", eyebrow: "Tiempo para dos", summary: "Destinos donde paisaje, hotel, gastronomía y hospitalidad queer permiten una escapada íntima sin perseguir una agenda intensa.", methodology: "Considera privacidad, calidad de estancia, contexto de bienvenida, paisaje, gastronomía y facilidad logística.", bestFor: "Parejas LGBTQ+ que buscan calma y conexión", mood: "Íntimo, sereno, cuidado", price: "De medio a premium", editorialNote: "Una escapada tranquila funciona cuando no tienes que justificar tu relación y el destino deja espacio para estar juntos.", tags: ["Parejas", "Escapadas", "Tranquilo"] }),
  "best-lgbtq-cities-48-hour-weekend": spanish({ title: "Mejores ciudades LGBTQ+ para un fin de semana de 48 horas", eyebrow: "Escapada breve", summary: "Ciudades que rinden en un fin de semana: llegada sencilla, barrios legibles, buena comida, señal queer y planes que encajan en dos días.", methodology: "Valora conexiones, escala urbana, transporte, densidad de experiencias y capacidad de construir una ruta breve sin agotarse.", bestFor: "Quien quiere aprovechar al máximo una escapada LGBTQ+ de dos días", mood: "Ágil, urbano, satisfactorio", price: "Variado", editorialNote: "Un gran fin de semana no consiste en hacerlo todo: consiste en elegir una ciudad que dé mucho sin convertir cada hora en logística.", tags: ["Fin de semana", "48 horas", "Ciudades"] }),
});

export function getLocalizedAtlasCollection(collection, locale = "en") {
  if (String(locale || "en").toLowerCase().split("-")[0] !== "es") return collection;
  const translated = SPANISH_COLLECTIONS[collection?.slug];
  if (!translated) return collection;
  const itemNotes = translated.itemNotes || (Array.isArray(collection.items) ? collection.items : []).map((item) => `Selección editorial de Queer Atlas para esta ruta: ${item}. Consulta la agenda, el acceso y el contexto local antes de ir.`);
  return { ...collection, ...translated, itemNotes };
}

export function hasSpanishCollectionTranslation(slug) {
  return Boolean(SPANISH_COLLECTIONS[String(slug || "")]);
}

export function getSpanishCollectionSearchTerms(collection) {
  const slug = String(collection?.slug || "");
  const localized = getLocalizedAtlasCollection(collection, "es");
  return SPANISH_COLLECTION_SEARCH_TERMS[slug] || [localized?.title, "guía queer de viajes", "viajes LGBTQ+"].filter(Boolean);
}
