import { EDITORIAL_TEAM } from "@/lib/editorialTrust";

const CHECKED_AT = "2026-08-12";

export const ATLAS_COLLECTION_REVIEWER = {
  id: "queer-atlas-research-desk",
  name: "Queer Atlas Research Desk",
  type: "Organization",
  role: "Fact-check and source review",
  href: "/contributors#queer-atlas-editorial-team",
  bio: "The Queer Atlas research desk checks source quality, scope, dates, and the distinction between official fact, editorial judgment, and community experience.",
};

function source(id, name, url, claimScope, type = "independent") {
  return { id, name, url, claimScope, type, confidence: "high", checkedAt: CHECKED_AT };
}

function editorial(collection, launchNote) {
  return {
    ...collection,
    author: EDITORIAL_TEAM,
    reviewer: ATLAS_COLLECTION_REVIEWER,
    publishedAt: CHECKED_AT,
    updatedAt: CHECKED_AT,
    changeLog: [
      { date: CHECKED_AT, note: launchNote || "Collection first published with individual selection notes, source record, methodology, and editorial review." },
    ],
  };
}

export const EXPANDED_ATLAS_COLLECTIONS = [
  editorial({
    id: "best-queer-neighborhoods-world",
    slug: "best-queer-neighborhoods-world",
    title: "Best Queer Neighborhoods in the World",
    eyebrow: "City texture",
    filter: "neighborhoods",
    intent: "best queer neighborhoods world",
    summary: "Eight districts where queer history, everyday visibility, hospitality, and nightlife still create a useful way into the wider city.",
    methodology: "Selected for durable queer identity, concentration of useful places, public history, visitor legibility, and evidence that the district functions beyond a Pride-season label. We also note where tourism and gentrification have changed the local balance.",
    bestFor: "Travelers choosing where to stay, walk, eat, and begin a night",
    mood: "Visible, layered, lived-in",
    price: "Budget to premium",
    editorialNote: "A queer district is valuable when it helps you read a city—not simply when maps repeat an old label. These neighborhoods remain useful, but none should be mistaken for the whole local community.",
    updated: "12 August 2026",
    cities: ["Paris", "Berlin", "Madrid", "San Francisco", "Toronto", "Mexico City", "Tokyo", "Cape Town"],
    items: ["Le Marais", "Schöneberg around Nollendorfplatz", "Chueca", "The Castro", "Church–Wellesley Village", "Zona Rosa", "Shinjuku Ni-chōme", "De Waterkant"],
    itemNotes: [
      "Le Marais remains Paris's most immediately legible queer district, especially for a first visit. Come for walkability, bookstores, bars, and history, while expecting a polished central neighborhood with a heavy visitor presence rather than an untouched local enclave.",
      "Schöneberg offers the clearest bridge between Berlin's queer past and its everyday present. The streets around Nollendorfplatz work well for bars, leather history, cafes, and an older mixed-age rhythm; the city's more experimental parties are usually elsewhere.",
      "Chueca is exceptionally easy to navigate and still concentrates hospitality, terraces, Pride infrastructure, and late-night options. Its success has also made it expensive and tourist-facing, so read it as Madrid's visible gateway rather than the full geography of local queer life.",
      "The Castro carries an unusual density of movement history, memorial sites, longstanding businesses, and public symbolism. It is strongest as a daytime-to-evening cultural route; San Francisco's current queer nightlife and communities stretch well beyond its famous blocks.",
      "Church–Wellesley remains Toronto's most readable first base, with drag, community institutions, patios, and Pride history in close reach. Queen Street West and other parts of the city add younger and less district-bound queer energy.",
      "Zona Rosa makes a practical central entry point through nightlife, services, restaurants, and transit around Colonia Juárez. The crowd can feel commercial and visitor-heavy, while Mexico City's wider queer scene increasingly spills into Centro, Roma, and other neighborhoods.",
      "Ni-chōme compresses a remarkable number of small bars into a few Tokyo blocks. Many rooms are intimate, specialized, or regular-led, so the best experience comes from checking who a venue serves rather than assuming every door works like an open Western gay bar.",
      "De Waterkant is compact, visually polished, and convenient for a Cape Town city break, with established queer hospitality near the centre. It is useful but not socially representative of the city's full LGBTQ+ population or its racial and geographic complexity.",
    ],
    tags: ["Neighborhoods", "Culture", "Nightlife"],
    href: "/now/collections/best-queer-neighborhoods-world",
    accent: "cyan",
    sources: [
      source("neighborhoods-forbes", "Forbes — LGBTQ+ districts search analysis", "https://www.forbes.com/sites/melissakravitz/2026/06/19/lgbtq-tourism-boom-searches-surge-for-queer-districts-worldwide/", "Search interest and contemporary relevance of major queer districts."),
      source("neighborhoods-berlin", "visitBerlin — Nollendorfplatz and Winterfeldtplatz", "https://www.visitberlin.de/en/nollendorfplatz-winterfeldtplatz", "Schöneberg history, culture, events, and visitor context.", "official"),
      source("neighborhoods-madrid", "Madrid Tourism — Chueca", "https://www.esmadrid.com/en/madrid-neighbourhoods/chueca", "Chueca visitor geography, culture, hospitality, and Pride context.", "official"),
      source("neighborhoods-toronto", "Destination Toronto — Church-Wellesley Village", "https://www.destinationtoronto.com/leisure-blog/post/church-wellesley-village-things-to-do/", "Church-Wellesley history, venues, and year-round queer role.", "official"),
      source("neighborhoods-cdmx", "Mexico City Tourism — LGBTTTI travel guide", "https://www.turismo.cdmx.gob.mx/storage/app/media/info_25/CAPITAL_LGBTTTI_2025.pdf", "Zona Rosa and wider Mexico City LGBTQ+ visitor context.", "official"),
      source("neighborhoods-research", "Urban Studies — queer urban spaces", "https://journals.sagepub.com/doi/10.1177/00420980241256821", "Comparative context for Castro, Soho, Chueca, and Le Marais.", "research"),
    ],
  }),

  editorial({
    id: "best-lgbtq-destinations-solo-travel",
    slug: "best-lgbtq-destinations-solo-travel",
    title: "Best LGBTQ+ Destinations for Solo Travelers",
    eyebrow: "Go your own way",
    filter: "solo",
    intent: "best LGBTQ destinations solo travel",
    summary: "Cities where transport, readable queer geography, daytime culture, and social entry points make a solo trip feel possible without forcing every connection through an app.",
    methodology: "Weighted toward navigability, public transport, range of low-pressure queer spaces, daytime usefulness, safety context, and the ability to change plans without losing the night. This is not a guarantee of personal safety or instant community.",
    bestFor: "Independent travelers who want options without overplanning",
    mood: "Open, flexible, self-directed",
    price: "Mixed",
    editorialNote: "The strongest solo destination gives you permission to change your mind. You can join a room, leave it, walk somewhere calmer, or have a full day without depending on nightlife for the trip to feel queer.",
    updated: "12 August 2026",
    cities: ["Copenhagen", "Berlin", "Amsterdam", "Lisbon", "Montreal", "Madrid", "Melbourne", "Bangkok"],
    items: ["Copenhagen", "Berlin", "Amsterdam", "Lisbon", "Montreal", "Madrid", "Melbourne", "Bangkok"],
    itemNotes: [
      "Copenhagen is compact, easy to move through, and comfortable for a trip built around design, food, swimming, and a few established queer stops. The scene is smaller than Berlin or Madrid, which can be a relief for a first solo city break but requires checking the event calendar.",
      "Berlin gives a solo traveler enormous choice: historic neighborhood bars, museums, cafes, community spaces, and music-led clubs. The trade-off is fragmentation—research the specific night and door rather than expecting the city's reputation to do the planning for you.",
      "Amsterdam pairs intuitive transport and English-language ease with a queer scene that is woven through the centre and recurring programming. It works particularly well for a short solo stay, though accommodation prices can make spontaneity expensive.",
      "Lisbon offers a softer social tempo around Príncipe Real, Arroios, and Intendente, with terraces and compact late-night routes. Hills and uneven streets matter for mobility, and many of the best queer experiences are calendar-led rather than permanently signposted.",
      "Montreal makes it easy to combine the Village with food, festivals, parks, and Francophone culture. The metro and long summer evenings support a low-friction solo rhythm; winter changes both movement and the social calendar considerably.",
      "Madrid is unusually forgiving when you arrive alone because people eat and go out late, Chueca is readable, and multiple neighborhoods remain active. Peak weekends are busy and prices in the central queer district no longer feel especially local.",
      "Melbourne rewards a traveler willing to follow neighborhoods rather than one gay village. Fitzroy, Collingwood, and event-led queer culture create depth, while the distance between venues makes a current plan and late transport check useful.",
      "Bangkok gives solo visitors a broad spectrum—from visible Silom bars and drag to markets, temples, food, and newer queer programming. Heat, traffic, and venue-specific audience expectations mean a neighborhood-based plan works better than crossing the city repeatedly.",
    ],
    tags: ["Solo travel", "City breaks", "Practical"],
    href: "/now/collections/best-lgbtq-destinations-solo-travel",
    accent: "emerald",
    sources: [
      source("solo-google", "Google Travel Trends 2025", "https://trends.withgoogle.com/trends/us/travel-trends-2025/?hl=en-US", "Record search interest in solo travel and broader trip-planning context.", "research"),
      source("solo-expedia", "Expedia Group — Inclusive Travel report", "https://partner.expediagroup.com/content/dam/unified/partner/documents/reports/2024-reports/2024-Expedia-Inclusive-Travel-report_en-us.pdf", "LGBTQIA+ traveler priorities, respect, inclusion, and booking trust.", "research"),
      source("solo-iglta", "IGLTA — LGBTQ+ travel network", "https://www.iglta.org/", "Destination and travel-business context across the selected cities.", "official"),
      source("solo-natgeo", "National Geographic — LGBTQ-friendly destinations", "https://www.nationalgeographic.com/travel/article/must-see-lgbtq-friendly-destinations", "Culture, neighborhoods, businesses, and community-led travel ideas."),
    ],
  }),

  editorial({
    id: "best-queer-nightlife-districts",
    slug: "best-queer-nightlife-districts",
    title: "Best Queer Nightlife Districts",
    eyebrow: "After-dark geography",
    filter: "nightlife",
    intent: "best queer nightlife districts",
    summary: "Eight districts that let you build a night on foot or with a short ride—each with a different balance of local regulars, visitors, bars, clubs, and late food.",
    methodology: "Chosen for concentration of active queer nightlife, ease of moving between different kinds of rooms, late-night usefulness, and current visitor relevance. District boundaries are editorial approximations; scenes change faster than neighborhoods do.",
    bestFor: "Travelers choosing where to base a nightlife-led weekend",
    mood: "Dense, late, socially legible",
    price: "Mostly mid-range",
    editorialNote: "The best nightlife district is not the place with the longest venue list. It is the place where one closed door or wrong crowd does not end the evening.",
    updated: "12 August 2026",
    cities: ["Berlin", "Madrid", "London", "New York", "Torremolinos", "Tokyo", "Bangkok", "São Paulo"],
    items: ["Kreuzberg–Friedrichshain", "Chueca and Gran Vía", "Soho to Vauxhall", "Hell's Kitchen", "La Nogalera", "Shinjuku Ni-chōme", "Silom", "Frei Caneca and Centro"],
    itemNotes: [
      "Berlin's strongest late-night geography is a network rather than a strip. Kreuzberg and Friedrichshain put music-first clubs, bars, and queer parties within workable transit reach, but the correct event matters more than the building name.",
      "Chueca gives Madrid its easiest bar-to-bar route, while larger clubs and pop nights spill toward Gran Vía and beyond. It is busy, mixed, and visitor-friendly; locals increasingly move through Lavapiés, Arganzuela, and promoter-led events too.",
      "Soho is the accessible first drink; Vauxhall is the later, clubbier commitment. Treat them as two linked London chapters rather than one walkable district, and check closing times and the specific promoter before crossing the river.",
      "Hell's Kitchen has become New York's most convenient concentration of gay bars, drag, and pre-club energy. It is easy for visitors but can skew polished and male; Brooklyn's queer party calendar offers a different, less district-bound night.",
      "La Nogalera is compact enough to improvise, with terraces, bars, and clubs stacked around a small pedestrian complex. Its rhythm is seasonal and strongly visitor-facing, but that concentration makes Torremolinos unusually easy for a short nightlife escape.",
      "Ni-chōme rewards curiosity and precision. Dozens of tiny rooms sit close together, yet audience, language, gender, and regular culture vary sharply; a welcoming first bar or local introduction changes the experience.",
      "Silom is Bangkok's clearest visible nightlife base, with bars and performance close to the BTS. It is practical and international, while more experimental queer nights appear elsewhere and require following current organizers.",
      "São Paulo's queer nightlife cannot be reduced to one street, but Frei Caneca and nearby Centro provide a useful bridge between bars, clubs, cultural spaces, and an enormous event-led scene. Distances and nighttime transport deserve real planning.",
    ],
    tags: ["Nightlife", "Districts", "Weekend"],
    href: "/now/collections/best-queer-nightlife-districts",
    accent: "violet",
    sources: [
      source("districts-berlin", "visitBerlin — LGBTQI+ Berlin", "https://www.visitberlin.de/en/lgbtqi-berlin", "Berlin queer neighborhoods, events, culture, and nightlife.", "official"),
      source("districts-madrid", "Madrid Tourism — Chueca", "https://www.esmadrid.com/en/madrid-neighbourhoods/chueca", "Chueca hospitality, nightlife density, and visitor role.", "official"),
      source("districts-london", "Visit London — LGBTQ+ London", "https://www.visitlondon.com/things-to-do/whats-on/pride/lgbt-london", "London LGBTQ+ neighborhoods, venues, and nightlife context.", "official"),
      source("districts-torremolinos", "Torremolinos Tourism", "https://turismotorremolinos.es/en/", "Destination layout and visitor logistics around La Nogalera.", "official"),
      source("districts-cdmx", "Forbes — global queer districts", "https://www.forbes.com/sites/melissakravitz/2026/06/19/lgbtq-tourism-boom-searches-surge-for-queer-districts-worldwide/", "Contemporary search demand and comparative district context."),
    ],
  }),

  editorial({
    id: "best-pride-festivals-worth-travelling-for",
    slug: "best-pride-festivals-worth-travelling-for",
    title: "Pride Festivals Worth Travelling For",
    eyebrow: "Calendar anchors",
    filter: "events",
    intent: "best Pride festivals world",
    summary: "A deliberately varied Pride edit: mass marches, political gatherings, cultural festivals, and smaller destination weeks that can hold an entire trip.",
    methodology: "Selected for recurring international relevance, distinct local character, cultural or political depth, travel usefulness, and organizer continuity. This is not a size ranking. Future dates must be confirmed with the official organizer before booking.",
    bestFor: "Travelers planning a trip around a major queer gathering",
    mood: "Collective, public, celebratory",
    price: "Free marches to ticketed festivals",
    editorialNote: "Pride is not one product. A march of millions, a trans-led demonstration, and a week in a queer beach town ask different things of a traveler—and that difference is the reason to choose carefully.",
    updated: "12 August 2026",
    cities: ["Sydney", "São Paulo", "Madrid", "New York", "Taipei", "Provincetown", "Cape Town", "Amsterdam"],
    items: ["Sydney Gay and Lesbian Mardi Gras", "São Paulo LGBT Pride", "Madrid Orgullo", "NYC Pride", "Taiwan LGBT+ Pride", "Provincetown Pride and Carnival season", "Cape Town Pride", "WorldPride Amsterdam legacy programme"],
    itemNotes: [
      "Sydney turns Pride into a multiweek arts, community, nightlife, and public-culture programme, with the Mardi Gras Parade as its global image rather than its only reason to travel.",
      "São Paulo delivers extraordinary public scale and a citywide queer weekend. The parade is free and politically significant; distance, crowd density, weather, and post-parade transport need planning.",
      "Madrid's Pride is built into central city life, with Chueca, public stages, the demonstration, and late-night programming operating as one enormous urban festival. Book early and expect intense heat and crowding.",
      "NYC Pride connects a globally recognized march with the movement history of Greenwich Village and a much wider calendar of borough, community, and identity-specific events. Choose the programme, not merely the headline weekend.",
      "Taiwan Pride is one of Asia's most important public LGBTQ+ gatherings, pairing a major Taipei march with the visibility of the region's first jurisdiction to establish marriage equality.",
      "Provincetown offers the opposite of a metropolis Pride: a compact queer destination where Pride, Carnival, themed weeks, galleries, beaches, and nightlife reshape the whole town across the season.",
      "Cape Town Pride brings public visibility and a multi-event programme to a city whose constitutional protections coexist with major social and geographic inequalities. Local context belongs in the trip, not outside it.",
      "Amsterdam's 2026 WorldPride and Canal Parade infrastructure reaffirmed the city's role as a major gathering point. For later travel, verify which parts of that expanded programme continue under Amsterdam Pride.",
    ],
    tags: ["Pride", "Festivals", "Events"],
    href: "/now/collections/best-pride-festivals-worth-travelling-for",
    accent: "rose",
    sources: [
      source("pride-iglta", "IGLTA — Global Pride Calendar", "https://www.iglta.org/events/pride-calendar/", "International event discovery and official organizer routing.", "official"),
      source("pride-sydney", "Sydney Gay and Lesbian Mardi Gras", "https://www.mardigras.org.au/", "Official Sydney programme and future event updates.", "official"),
      source("pride-madrid", "Madrid Orgullo", "https://www.madridorgullo.com/", "Official Madrid Pride programme and organizer information.", "official"),
      source("pride-nyc", "NYC Pride", "https://www.nycpride.org/", "Official New York Pride events and updates.", "official"),
      source("pride-taiwan", "Taiwan LGBT+ Pride", "https://www.taiwanpride.lgbt/", "Official Taipei march and organizer context.", "official"),
      source("pride-lonelyplanet", "Lonely Planet — Pride destinations 2026", "https://www.lonelyplanet.com/articles/most-gay-friendly-cities", "Independent comparison of Pride-led destination experiences."),
    ],
  }),

  editorial({
    id: "emerging-queer-destinations",
    slug: "emerging-queer-destinations",
    title: "Emerging Queer Destinations Beyond the Usual Capitals",
    eyebrow: "Next-city energy",
    filter: "hidden",
    intent: "emerging queer travel destinations",
    summary: "Eight cities where community organizers, independent venues, culture, and a more local scale make a convincing alternative to the familiar queer-capital circuit.",
    methodology: "Selected from cities with identifiable year-round LGBTQ+ infrastructure, recurring public events, multiple useful place types, and enough wider cultural depth to sustain a trip. Emerging does not mean newly queer or uniformly safe.",
    bestFor: "Repeat travelers who want local texture over scene mythology",
    mood: "Independent, changing, city-specific",
    price: "Mostly accessible",
    editorialNote: "These cities are not waiting to be discovered by outsiders. They already contain queer histories and communities; what is emerging is their visibility to a wider travel audience.",
    updated: "12 August 2026",
    cities: ["Leipzig", "Bristol", "Toulouse", "Detroit", "Gothenburg", "Rotterdam", "Salvador", "Porto"],
    items: ["Leipzig", "Bristol", "Toulouse", "Detroit", "Gothenburg", "Rotterdam", "Salvador da Bahia", "Porto"],
    itemNotes: [
      "Leipzig combines alternative music, art, student life, and recurring queer organizing without Berlin's scale or visitor machinery. The scene is event-led, so a strong weekend depends on the current programme rather than a long permanent venue list.",
      "Bristol's queer energy is distributed through independent clubs, arts spaces, community projects, and a politically expressive local culture. It rewards following promoters and neighborhoods instead of searching for one formal gay village.",
      "Toulouse offers a southern French city break with established associations, Pride, bars, and cultural life at a more manageable scale than Paris. The scene can feel locally networked, making event timing especially important for visitors.",
      "Detroit's queer story sits inside a city of Black cultural history, electronic music, reinvention, and strong regional identity. Distances are significant and transport planning matters; this is not a compact bar-crawl destination.",
      "Gothenburg pairs West Pride, music, islands, design, and a socially progressive baseline with a relatively small permanent scene. It works best when the trip includes the whole city rather than treating nightlife as the only proof of queer life.",
      "Rotterdam's architecture, port-city energy, festivals, and promoter-led queer nights offer a sharper, less postcarded alternative to Amsterdam. Venues and events are dispersed, but public transport keeps the city workable.",
      "Salvador brings Afro-Brazilian culture, music, coastline, and a visible LGBTQ+ population into a destination unlike the usual European circuit. Racism, class, neighborhood safety, and local transport require context rather than romantic shorthand.",
      "Porto is increasingly useful for queer travelers who want food, design, river and coast alongside a modest but visible scene. Expect fewer permanent LGBTQ+ venues than Lisbon and plan around current community programming.",
    ],
    tags: ["Emerging cities", "Local culture", "Alternatives"],
    href: "/now/collections/emerging-queer-destinations",
    accent: "amber",
    sources: [
      source("emerging-iglta", "IGLTA — LGBTQ+ travel network", "https://www.iglta.org/", "Destination and LGBTQ+ travel-business context.", "official"),
      source("emerging-cn", "Condé Nast Traveler — beyond the usual LGBTQ+ destinations", "https://www.cntraveler.com/story/best-destinations-for-lgbtq-travelers-off-the-beaten-path", "Independent framing for less obvious LGBTQ+ destinations."),
      source("emerging-leipzig", "CSD Leipzig", "https://csd-leipzig.de/", "Leipzig community organization and annual public programme.", "official"),
      source("emerging-bristol", "Bristol Pride", "https://bristolpride.co.uk/", "Bristol's official Pride programme and community network.", "official"),
      source("emerging-gothenburg", "West Pride", "https://www.westpride.se/", "Gothenburg's official LGBTQ+ arts and Pride programme.", "official"),
      source("emerging-rotterdam", "Rotterdam Pride", "https://rotterdam-pride.com/", "Rotterdam Pride organization and current event context.", "official"),
    ],
  }),
];
