import { EDITORIAL_TEAM } from "@/lib/editorialTrust";
import { ATLAS_COLLECTION_REVIEWER } from "@/lib/atlasCollectionsExpansion";

const CHECKED_AT = "2026-08-21";
const source = (id, name, url, claimScope, type = "independent") => ({
  id,
  name,
  url,
  claimScope,
  type,
  confidence: "high",
  checkedAt: CHECKED_AT,
});
const editorial = (collection, note) => ({
  ...collection,
  author: EDITORIAL_TEAM,
  reviewer: ATLAS_COLLECTION_REVIEWER,
  publishedAt: CHECKED_AT,
  updatedAt: CHECKED_AT,
  changeLog: [{ date: CHECKED_AT, note }],
});

export const GROWTH_ATLAS_COLLECTIONS = [
  editorial({
    id: "best-lgbtq-honeymoon-destinations",
    slug: "best-lgbtq-honeymoon-destinations",
    title: "Best LGBTQ+ Honeymoon Destinations",
    eyebrow: "Queer romance",
    filter: "stays",
    intent: "best LGBTQ honeymoon destinations gay lesbian couples",
    summary: "Six romantic trips where scenery, memorable stays, shared experiences, and a credible LGBTQ+ welcome can exist in the same itinerary.",
    methodology: "Selected for romantic trip value, public LGBTQ+ visitor context, couple-friendly experiences, and enough range to build a honeymoon beyond one hotel. Laws, lived experience, season, health requirements, and neighborhood-level safety were considered separately; inclusion is not a guarantee of identical treatment everywhere.",
    bestFor: "Newlyweds who want romance without editing themselves out of the trip",
    mood: "Intimate, celebratory, unhurried",
    price: "Mid-range to once-in-a-lifetime",
    editorialNote: "A honeymoon should not require choosing between romance and queer ease. These destinations offer different versions of both, but the right season, neighborhood, and accommodation still matter more than a rainbow badge.",
    updated: "21 August 2026",
    cities: ["Puerto Vallarta", "Costa Rica", "Bangkok and Koh Samui", "Cape Town", "Lisbon", "Malta and Gozo"],
    items: ["Puerto Vallarta", "Arenal and Manuel Antonio", "Bangkok and Koh Samui", "Cape Town and the Winelands", "Lisbon and Cascais", "Valletta and Gozo"],
    itemNotes: [
      "Puerto Vallarta makes the romantic logistics unusually easy: sunset walks, spas, restaurants, queer beach life, and the Zona Romantica sit inside one legible trip. It is social and visitor-facing rather than secluded, and hills, heat, and peak-season pricing should shape the hotel choice.",
      "Costa Rica suits couples who want rainforest, wildlife, hot springs, and Pacific coast time rather than a single resort bubble. Arenal and Manuel Antonio make a strong two-part route; transfers consume time, so fewer bases usually produce a better honeymoon.",
      "Thailand can pair Bangkok's food and design with a slower island finish on Koh Samui. Marriage equality and established LGBTQ+ tourism strengthen the context, while resort atmosphere and public visibility still vary by island, neighborhood, and property.",
      "Cape Town combines ocean, mountain, design, food, and wine-country day trips with a visible queer city culture. The scenery is exceptional, but urban safety is neighborhood-specific: use current local advice and plan transport after dark.",
      "Lisbon offers tiled streets, viewpoints, food, nightlife, and easy coastal days around Cascais and Costa da Caparica. It works best as a city honeymoon with romantic excursions; steep terrain, summer heat, and rising accommodation costs are real trade-offs.",
      "Malta and Gozo offer compact Mediterranean history, swimming, short ferry journeys, and some of Europe's strongest legal LGBTQ+ protections. Valletta supplies culture and restaurants while Gozo slows the pace; religious tradition remains visible alongside modern rights.",
    ],
    tags: ["Honeymoon", "Couples", "Romance"],
    href: "/now/collections/best-lgbtq-honeymoon-destinations",
    accent: "rose",
    sources: [
      source("honeymoon-pv", "Puerto Vallarta Tourism — LGBT vacations", "https://visitpuertovallarta.com/plan-your-trip/lgbt", "Official LGBTQ+ visitor, romance, restaurant, spa, beach, and neighborhood context.", "official"),
      source("honeymoon-costa-rica", "Visit Costa Rica — 2SLGBTQI itinerary", "https://www.visitcostarica.com/planning-your-trip/itineraries/2slgbtqi", "Official LGBTQ+ itinerary and multi-region trip planning.", "official"),
      source("honeymoon-thailand", "Tourism Authority of Thailand — Travel Proud", "https://www.tourismthailand.org/Articles/travel-proud-en", "Official hospitality-inclusion and accommodation context.", "official"),
      source("honeymoon-cape-town", "Cape Town Tourism — LGBTQ+ destination recognition", "https://www.capetown.travel/cape-town-scoops-best-lgbtq-city-destination-at-global-travel-awards/", "Official current LGBTQ+ destination and local inclusion context.", "official"),
      source("honeymoon-lisbon", "Visit Lisboa", "https://www.visitlisboa.com/en/p/homepage", "Official city-break, transport, culture, food, and coastal trip planning.", "official"),
      source("honeymoon-malta", "Visit Malta", "https://www.visitmalta.com/en/", "Official Malta and Gozo travel, short-break, swimming, food, and wedding context.", "official"),
    ],
  }, "Collection published with six couple-first itineraries, destination-specific trade-offs, and official tourism sources."),

  editorial({
    id: "best-queer-owned-hotels-resorts",
    slug: "best-queer-owned-hotels-resorts",
    title: "Best Queer-Owned Hotels and Resorts",
    eyebrow: "Stay in the community",
    filter: "stays",
    intent: "best queer owned hotels LGBTQ owned resorts",
    summary: "Six independently verified stays where LGBTQ+ ownership is part of the property story, not an inference from inclusive marketing.",
    methodology: "Ownership was included only when the property or a credible public record explicitly identifies an LGBTQ+ owner, founder, or operator. We then considered guest fit, destination value, facilities, and community role. This first edition is a considered shortlist, not a claim to represent every region or every LGBTQ+ identity equally.",
    bestFor: "Travelers who want more of their accommodation spend to remain inside queer hospitality",
    mood: "Hosted, expressive, community-rooted",
    price: "Boutique to premium",
    editorialNote: "Queer-owned and queer-friendly are not synonyms. This edit uses a stricter ownership test and states each property's audience plainly, including when a stay is designed primarily for gay men.",
    updated: "21 August 2026",
    cities: ["Puerto Vallarta", "Palm Springs", "Miami Beach", "Fort Lauderdale", "Newfane", "Saugatuck-Douglas"],
    items: ["Casa Cupula", "Trixie Motel", "Hotel Gaythering", "Pineapple Point", "Frog Meadow", "The Dunes Resort"],
    itemNotes: [
      "Casa Cupula is a gay-owned boutique hotel above Puerto Vallarta's Zona Romantica, combining calm views, pools, gym, spa, and a direct relationship with local LGBTQ+ causes. The hillside setting is beautiful but should be checked against mobility needs.",
      "Trixie Motel turns a seven-room Palm Springs stay into a maximalist drag-design experience owned by Trixie Mattel and co-owner David Silver. Choose it for personality, pool time, and a very specific fantasy—not anonymity or conventional resort scale.",
      "Hotel Gaythering is a gay-owned and operated Miami Beach hotel built around social space, a bar, and sauna as much as bedrooms. Its adults-oriented, gay-male center of gravity is part of the product and should be read before booking.",
      "Pineapple Point is an owner-led, clothing-optional Fort Lauderdale resort for gay men, set across a lush private property with pools, jacuzzis, gym, and massage studios. It prioritizes quiet luxury and hosted familiarity over beachfront high-rise energy.",
      "Frog Meadow is a queer-owned Vermont bed-and-breakfast and retreat setting for men, with cottages, trails, massage, hot tub, gardens, and a deliberately slow social rhythm. The rural location is the appeal, but a car and comfort with an all-male environment are important.",
      "The Dunes is a long-running LGBTQ+ resort in Saugatuck-Douglas where lodging, pool culture, nightlife, and community history share one campus. It is the most event-led choice here; room type and festival weekend can substantially change the experience.",
    ],
    tags: ["Queer-owned", "Hotels", "Resorts"],
    href: "/now/collections/best-queer-owned-hotels-resorts",
    accent: "violet",
    sources: [
      source("owned-casa-cupula", "Casa Cupula — Our story", "https://casacupula.com/about-casa-cupula/", "Explicit gay ownership, operation, property history, and community role.", "official"),
      source("owned-trixie", "Trixie Motel — Story", "https://trixiemotel.com/about/", "Owner identities, property history, room count, and concept.", "official"),
      source("owned-gaythering", "Hotel Gaythering", "https://www.gaythering.com/", "Explicit gay ownership and operation, facilities, and guest positioning.", "official"),
      source("owned-pineapple", "Pineapple Point — About", "https://pineapplepoint.com/about/", "Named founders and owners, history, audience, and service model.", "official"),
      source("owned-frog-meadow", "Frog Meadow — About", "https://frogmeadow.com/about-us/", "Current queer ownership, innkeepers, property history, and retreat character.", "official"),
      source("owned-dunes", "The Dunes Resort — Our story", "https://dunesresort.com/about/", "LGBTQ+ resort history, named ownership, and current community role.", "official"),
    ],
  }, "Collection published with a strict public ownership test, direct property sources, and audience-specific caveats."),

  editorial({
    id: "best-affordable-lgbtq-city-breaks",
    slug: "best-affordable-lgbtq-city-breaks",
    title: "Best Affordable LGBTQ+ City Breaks",
    eyebrow: "More trip for the spend",
    filter: "solo",
    intent: "best affordable LGBTQ city breaks budget gay travel",
    summary: "Six city breaks where queer context, public transport, food, culture, and social life can work without requiring a luxury itinerary.",
    methodology: "Value is assessed relatively, not through a fixed daily-price promise: accommodation range, public transport, walkability, free or low-cost culture, food choice, and queer infrastructure all matter. Airfare, exchange rates, major events, and individual safety needs can reverse the ranking for a specific traveler.",
    bestFor: "Travelers who want a credible queer city trip with room to control the budget",
    mood: "Lively, practical, flexible",
    price: "Budget-conscious to mid-range",
    editorialNote: "Affordable does not mean cheapest. It means a city gives you several good versions of the trip—without forcing every meaningful experience behind a premium hotel, taxi, or event pass.",
    updated: "21 August 2026",
    cities: ["Porto", "Athens", "Valencia", "Mexico City", "Buenos Aires", "Bangkok"],
    items: ["Porto", "Athens", "Valencia", "Mexico City", "Buenos Aires", "Bangkok"],
    itemNotes: [
      "Porto offers river walks, Atlantic day trips, food, design, and a smaller queer circuit at a scale that rewards walking. Prices have risen, but shoulder dates, transit, and a city-first itinerary can still undercut Europe's largest queer capitals.",
      "Athens combines major historical sites, long evenings, inexpensive everyday food, and Gazi nightlife with easy access to the coast. Summer heat and headline attractions can strain both energy and budget, so spring and autumn often provide stronger value.",
      "Valencia gives a traveler beach, architecture, cycling, markets, and LGBTQ+ social life without Barcelona's level of compression. Las Fallas and peak beach weeks are exceptions; outside them, the city is unusually easy to enjoy without constant paid attractions.",
      "Mexico City rewards longer stays with metro access, museums, street food, neighborhoods, and multiple queer scenes beyond Zona Rosa. The scale is the challenge: saving on daily costs is easier when accommodation is chosen near the experiences you actually want.",
      "Buenos Aires offers architecture, bookstores, performance, late dining, and deep LGBTQ+ history with many free public pleasures. Inflation and exchange conditions change rapidly, so avoid publishing or relying on a fixed foreign-currency daily budget.",
      "Bangkok offers exceptional food range, extensive rail transit, design, temples, shopping, and an established queer nightlife map. International hotels can be premium, but everyday meals and movement leave real budget flexibility; heat and distance reward planning by neighborhood.",
    ],
    tags: ["Affordable travel", "City breaks", "Budget"],
    href: "/now/collections/best-affordable-lgbtq-city-breaks",
    accent: "emerald",
    sources: [
      source("value-market", "CBI — Entering the European LGBTQ+ tourism market", "https://www.cbi.eu/sites/default/files/pdf/research/1217.pdf", "Current LGBTQ+ tourism products, traveler needs, and comparative market-price context.", "research"),
      source("value-europe", "Two Bad Tourists — LGBTQ+ budget cities", "https://twobadtourists.com/lgbtq-budget-cities-eastern-europe/", "Independent current budget-travel methodology and queer-city considerations.", "independent"),
      source("value-porto", "Porto Pride", "https://www.portopride.com/", "Current local LGBTQ+ event and community context.", "official"),
      source("value-mexico", "Mexico City — Zona Rosa for LGBTQ+ travelers", "https://www.mexicocity.cdmx.gob.mx/venues/zona-rosa-lgbt/?lang=en", "Official queer district, nightlife, and changeability context.", "official"),
      source("value-thailand", "Tourism Authority of Thailand — Travel Proud", "https://www.tourismthailand.org/Articles/travel-proud-en", "Official LGBTQ+ hospitality and destination-planning context.", "official"),
      source("value-equality", "ILGA World Database", "https://database.ilga.org/en", "Country-level law and policy context used separately from daily cost and city atmosphere.", "research"),
    ],
  }, "Collection published with a relative-value methodology, no fixed price claims, and explicit event, exchange-rate, and airfare caveats."),

  editorial({
    id: "best-sapphic-city-breaks-world",
    slug: "best-sapphic-city-breaks-world",
    title: "Best Sapphic City Breaks in the World",
    eyebrow: "Cities through a sapphic lens",
    filter: "women",
    intent: "best sapphic city breaks lesbian travel destinations",
    summary: "Six cities where queer women, trans, and nonbinary travelers can build a trip through community events, culture, daytime spaces, and nightlife—not one token bar.",
    methodology: "Selected for recurring women-led or sapphic programming, broader queer infrastructure, cultural value, and a city rhythm that works beyond nightlife. Permanent lesbian bars are rare, so event calendars, collectives, bookstores, sport, and community media are weighted alongside venues. Inclusion language should be checked with each organizer.",
    bestFor: "Sapphic travelers who want a whole city break, not a single pin",
    mood: "Creative, social, self-directed",
    price: "Mixed",
    editorialNote: "The sapphic map is often mobile. A recurring party, reading group, football night, book fair, or queer-owned cafe may matter more than a permanent bar, so every pick here rewards checking the calendar before choosing dates.",
    updated: "21 August 2026",
    cities: ["New York", "Montreal", "Melbourne", "Berlin", "Mexico City", "London"],
    items: ["Brooklyn and Lower Manhattan", "Montreal beyond the Village", "Melbourne's inner north", "Berlin's event-led sapphic circuit", "Mexico City from Zona Rosa outward", "London across Soho and East London"],
    itemNotes: [
      "New York has the deepest permanent sapphic venue bench in this edit, but the better trip stretches beyond bar collecting into Brooklyn cafes, bookstores, performance, queer history, and roving parties. Neighborhood choice matters more than proximity to Times Square.",
      "Montreal's strongest sapphic energy is distributed through promoters, comedy, ballroom, magazines, book events, sports-bar gatherings, and queer-owned hospitality beyond the historic Village. Its bilingual culture gives the scene a character few cities can copy.",
      "Melbourne pairs queer-women parties such as Tomboy with film, sport, cafes, live music, and the inner north's everyday queer visibility. Event nights move, while trams and neighborhood density make a flexible weekend easy to assemble.",
      "Berlin supports dedicated bars, recurring FLINTA-focused nights, archives, festivals, and alternative cultural spaces rather than one polished lesbian district. Door policy and audience language matter; select the event before selecting the venue.",
      "Mexico City's lesbian history and nightlife touch Zona Rosa but do not stop there: Juarez, Centro, Roma, cultural events, and changing women-led rooms make it a route. Venues turn over quickly, so current local calendars are essential.",
      "London combines a dedicated central lesbian bar with queer-women club nights, bookshops, comedy, performance, football culture, and East London collectives. The strength is volume and variety; the trade-off is cost and travel time across the city.",
    ],
    tags: ["Sapphic", "Lesbian travel", "City breaks"],
    href: "/now/collections/best-sapphic-city-breaks-world",
    accent: "fuchsia",
    sources: [
      source("sapphic-montreal", "Tourisme Montreal — Queer Montreal city-wide", "https://www.mtl.org/en/experience/queer-mtl-stretches-city-wide", "Current lesbian-led events, queer-owned spaces, ballroom, books, and neighborhood context.", "official"),
      source("sapphic-melbourne", "Visit Melbourne — LGBTQIA+", "https://www.visitmelbourne.com/regions/melbourne/see-and-do/lgbtqia", "Official queer-women events, neighborhoods, film, and nightlife context.", "official"),
      source("sapphic-mexico", "Mexico City — Zona Rosa for LGBTQ+ travelers", "https://www.mexicocity.cdmx.gob.mx/venues/zona-rosa-lgbt/?lang=en", "Official gay and lesbian nightlife history and venue-turnover warning.", "official"),
      source("sapphic-global", "Travel Gay Women", "https://www.travelgay.com/women", "Specialist international lesbian destination and nightlife coverage.", "independent"),
      source("sapphic-guides", "Autostraddle — Queer Girl City Guides", "https://www.autostraddle.com/tag/queer-girl-city-guide/", "Long-running specialist city reporting through a queer-women lens.", "independent"),
      source("sapphic-bars", "The Lesbian Bar Project", "https://www.lesbianbarproject.com/", "Independent documentation of dedicated lesbian venues and their scarcity.", "research"),
    ],
  }, "Collection published with six full-city sapphic routes, calendar-first guidance, and sources centered on queer women rather than generic gay travel."),

  editorial({
    id: "best-bear-weeks-festivals",
    slug: "best-bear-weeks-festivals",
    title: "Best Bear Weeks and Bear Festivals",
    eyebrow: "Big-hearted gatherings",
    filter: "events",
    intent: "best bear weeks gay bear festivals world",
    summary: "Six recurring bear gatherings with enough community, destination character, and daytime life to justify the journey—not only the closing party.",
    methodology: "Selected from recurring events with a public organizer, current programme, clear destination value, and activities beyond one club night. We considered first-timer usefulness, social formats, season, accommodation pressure, and community purpose. Dates and host venues change annually and must be confirmed with organizers.",
    bestFor: "Bears, cubs, otters, chubs, admirers, and travelers who prefer community with the party",
    mood: "Warm, social, body-positive",
    price: "Free gatherings to premium event weeks",
    editorialNote: "Bear events are not one uniform scene. These picks range from beach-village intensity to redwood camp energy and Icelandic excursions; the best match depends on whether you want dance floors, outdoor time, easy conversation, or all three.",
    updated: "21 August 2026",
    cities: ["Sitges", "Provincetown", "Guerneville", "Puerto Vallarta", "Maspalomas", "Reykjavik"],
    items: ["International Bears Sitges Week", "Bear Week Provincetown", "Lazy Bear Week", "BeefDip Bear Week", "Bear Carnival Maspalomas", "Reykjavik Bear"],
    itemNotes: [
      "Sitges turns its seafront and compact old town into a roughly ten-day international gathering, making beach, bars, meals, and the Bear Village easy to connect on foot. Scale and September demand mean accommodation should be secured far ahead.",
      "Provincetown layers pool events, shows, food, beaches, galleries, and late nights onto a town already built around LGBTQ+ visitors. It is exceptionally sociable and exceptionally expensive in peak summer; ferry and room planning are part of the event.",
      "Lazy Bear Week brings thousands to Guerneville for pool parties, campfires, tea dances, games, outdoor activities, and fundraising beneath the Russian River redwoods. The spread-out rural setting makes housing and rides more consequential than at a compact beach town.",
      "BeefDip places a large winter bear gathering inside Puerto Vallarta's walkable queer resort infrastructure, combining parties with beach and vacation time. The visitor-heavy format is easy for a first trip, while premium dates and a male-centered crowd should be expected.",
      "Bear Carnival runs alongside the energy of Maspalomas with pool, beach, social, boat, wellness, and nightlife formats around the Yumbo area. Resort distances and overlapping public carnival activity can complicate transport and crowd levels.",
      "Reykjavik Bear is the smaller, excursion-led counterpoint: city events sit beside lagoon visits, landscape tours, food, and a nonprofit community ethos. Iceland's costs are high, but the contained programme can be more readable for a first-time solo attendee.",
    ],
    tags: ["Bear community", "Festivals", "Events"],
    href: "/now/collections/best-bear-weeks-festivals",
    accent: "amber",
    sources: [
      source("bear-sitges", "Sitges Tourism — Bears Sitges Week", "https://www.sitgesanytime.com/es/actualidad/agenda/pln330/bears-sitges-week", "Official current dates, duration, destination context, and organizer link.", "official"),
      source("bear-ptown", "Provincetown Business Guild — Bear Week", "https://ptown.org/calendars/bears/", "Official current Bear Week planning, public events, and visitor information.", "official"),
      source("bear-lazy", "Lazy Bear Fund", "https://www.lazybearfund.org/events", "Official event scale, programme character, dates, and charitable purpose.", "official"),
      source("bear-beefdip", "BeefDip Bear Week", "https://beefdip.com/", "Official Puerto Vallarta event programme and booking information.", "official"),
      source("bear-maspalomas", "Bear Carnival", "https://bearcarnival.com/final-bear-week-programme-for-2026/", "Official current pool, beach, social, wellness, and nightlife programme.", "official"),
      source("bear-reykjavik", "Reykjavik Bear", "https://reykjavikbear.is/about/", "Official event history, nonprofit mission, audience, and destination format.", "official"),
    ],
  }, "Collection published with six organizer-verified events, first-timer logistics, and annual-date caveats."),

  editorial({
    id: "best-queer-wellness-retreats",
    slug: "best-queer-wellness-retreats",
    title: "Best Queer Wellness Retreats and Restorative Escapes",
    eyebrow: "Rest without shrinking",
    filter: "culture",
    intent: "best LGBTQ wellness retreats queer yoga spa escapes",
    summary: "Six queer-centered retreats where rest, movement, nature, reflection, and community are the substance of the trip rather than a Pride-month add-on.",
    methodology: "Included programmes publicly center an LGBTQ+ audience and offer a structured restorative element such as yoga, movement, nature, reflection, massage, recovery, or facilitated community time. We reviewed organizer identity, audience language, accommodation, and current programme evidence; this is travel guidance, not medical or therapeutic endorsement.",
    bestFor: "Travelers seeking queer community at a slower, more intentional pace",
    mood: "Restorative, embodied, connected",
    price: "Retreat package pricing",
    editorialNote: "Wellness language can overpromise. These picks are included for the clarity of their audience and programme—not because Queer Atlas can validate a health outcome. Read facilitator credentials, cancellation terms, access, and intensity before paying a deposit.",
    updated: "21 August 2026",
    cities: ["Greenwich, New York", "Newfane, Vermont", "Portugal", "Indian Springs, Georgia", "Mykonos", "Mornington Peninsula"],
    items: ["Easton Mountain", "Frog Meadow", "People Like Us Portugal", "Shades Retreat", "Mykonos Active", "Will & Justin Queer Men's Retreat"],
    itemNotes: [
      "Easton Mountain is a gay-men-created retreat center and sanctuary with a broad calendar spanning recovery, creativity, body work, spirituality, social weekends, and outdoor time. Programmes differ sharply, so the individual retreat—not only the venue—must fit the traveler.",
      "Frog Meadow offers an unstructured restorative stay for men through quiet lodging, gardens, trails, massage, hot tub, swimming, and long communal breakfasts. It is closer to a slow queer country retreat than a scheduled wellness bootcamp.",
      "People Like Us creates small Portugal retreats for queer women, trans, and nonbinary people around yoga, meditation, breathwork, countryside quiet, and community. Its explicit audience fills a gap in a wellness market still heavily oriented toward gay men.",
      "Shades Retreat centers LGBTQI women of color through a defined health-and-wellness weekend at Indian Springs State Park. Its specificity is the strength; prospective guests should use the current edition for programme, lodging, access, and facilitator details.",
      "Mykonos Active combines daily yoga, Pilates, fitness, hiking, beach time, and a gay-men-focused group inside a destination better known for nightlife. The balance works for active travelers, but this is structured movement rather than a passive spa holiday.",
      "Will and Justin's Mornington Peninsula retreat offers queer men yoga, meditation, breathwork, meals, and small-group connection in a coastal property. Limited capacity supports intimacy; travel logistics and the programme's group nature should be part of the decision.",
    ],
    tags: ["Wellness", "Retreats", "Slow travel"],
    href: "/now/collections/best-queer-wellness-retreats",
    accent: "cyan",
    sources: [
      source("wellness-easton", "Easton Mountain — Mission", "https://www.eastonmountain.org/mission", "Official sanctuary, retreat mission, audience, accessibility intent, and programme purpose.", "official"),
      source("wellness-frog", "Frog Meadow — About", "https://frogmeadow.com/about-us/", "Official ownership, audience, restorative facilities, massage, and property rhythm.", "official"),
      source("wellness-people", "People Like Us — Portugal retreats", "https://www.wearepeoplelikeus.com/portugal-july-2026", "Official queer women, trans, and nonbinary audience plus current retreat programme.", "official"),
      source("wellness-shades", "Shades Retreat", "https://www.shadesretreat.org/", "Official LGBTQI women-of-color focus, location, date, and health-and-wellness purpose.", "official"),
      source("wellness-mykonos", "Mykonos Active", "https://www.mykonosactive.com/", "Official gay-men-focused yoga, Pilates, fitness, hiking, and retreat schedule.", "official"),
      source("wellness-australia", "Will & Justin — Gay and queer men's retreat", "https://www.willandjustin.com/gay-mens-retreat-2026", "Official audience, capacity, accommodation, meals, movement, and meditation programme.", "official"),
    ],
  }, "Collection published with six audience-specific restorative formats, direct organizer sources, and a clear non-medical disclaimer."),

  editorial({
    id: "best-cities-queer-food-restaurants",
    slug: "best-cities-queer-food-restaurants",
    title: "Best Cities for Queer Food and LGBTQ+-Owned Restaurants",
    eyebrow: "Eat with the community",
    filter: "culture",
    intent: "best cities queer food LGBTQ owned restaurants travel",
    summary: "Six cities where queer-owned restaurants, cafes, bakeries, bars with serious kitchens, and community hospitality can shape an entire food-led trip.",
    methodology: "Selected for multiple publicly identified LGBTQ+-owned food businesses, wider destination value, and enough range to build more than one meal. Ownership is verified at business level where sources allow; a city's inclusion does not mean every listed restaurant or neighborhood is queer-owned or uniformly welcoming.",
    bestFor: "Travelers who use breakfast, dinner, and the table between them to understand a city",
    mood: "Generous, local, celebratory",
    price: "Counter service to special occasion",
    editorialNote: "Queer food culture is not only drag brunch. These cities let travelers support LGBTQ+ owners across coffee, bakeries, street food, wine, comfort food, and chef-led dining—while still choosing places because the food earns the stop.",
    updated: "21 August 2026",
    cities: ["Atlanta", "Portland", "Miami", "New York", "Austin", "New Orleans"],
    items: ["Atlanta", "Portland, Oregon", "Miami and Miami Beach", "New York City", "Austin", "New Orleans"],
    itemNotes: [
      "Atlanta has enough queer-owned restaurants and cafes to build a genuine food route rather than a symbolic stop, from bakeries and brunch to wine bars and dinner rooms. The scene is spread across neighborhoods, so group meals geographically.",
      "Portland connects queer-owned Vietnamese comfort food, tacos, vegan cooking, coffee, bars, and independent maker culture. Many businesses are small and hours change; current direct checks matter more than an old Pride-month roundup.",
      "Miami and Miami Beach offer an unusually well-documented mix of LGBTQ+-owned all-day cafes, Cuban food, drag brunch, nightlife dining, and neighborhood institutions. South Beach pricing varies sharply, so the strongest route should extend beyond Ocean Drive.",
      "New York's scale supports queer-owned breakfast, bakeries, neighborhood restaurants, bars with kitchens, and occasion dining across boroughs. The opportunity is enormous and the churn is real: verify every business before turning a saved map into an itinerary.",
      "Austin pairs queer-owned coffeehouses and restaurants with a wider food-truck, barbecue, patio, and nightlife culture. The city is easy to enjoy casually but difficult without planning transport; cluster meals with neighborhoods and evening plans.",
      "New Orleans makes food inseparable from neighborhood and music culture, with queer- and woman-owned restaurants adding Honduran, Creole, cafe, and bar routes to the trip. Festival weekends and heat change both reservations and pacing.",
    ],
    tags: ["Queer-owned", "Food", "Restaurants"],
    href: "/now/collections/best-cities-queer-food-restaurants",
    accent: "rose",
    sources: [
      source("food-atlanta", "The Infatuation — Queer-owned Atlanta restaurants", "https://www.theinfatuation.com/atlanta/guides/lgbtq-owned-restaurants-atlanta", "Current independent restaurant selection and public ownership context.", "independent"),
      source("food-portland", "Travel Portland — Gay Portland", "https://www.travelportland.com/culture/gay-portland/", "Official queer-owned restaurant, cafe, bar, and neighborhood context.", "official"),
      source("food-miami", "Greater Miami and Miami Beach — Dining with Pride", "https://www.miamiandbeaches.com/travel-interests/lgbtq-miami/lgbtq-owned-restaurants-in-miami", "Official current LGBTQ+-owned dining guide with named ownership.", "official"),
      source("food-new-york", "The Infatuation — Queer-owned restaurants in NYC", "https://www.theinfatuation.com/new-york/guides/best-queer-owned-restaurants-nyc", "Independent multi-format dining guide and ownership context.", "independent"),
      source("food-austin", "Visit Austin — LGBTQ+ food and drink", "https://www.austintexas.org/explore/lgbtq/food-drink/", "Official queer-owned restaurant, coffeehouse, and founder context.", "official"),
      source("food-new-orleans", "New Orleans — Queer women's guide", "https://www.neworleans.com/blog/post/the-queer-womans-guide-to-new-orleans/", "Official queer- and woman-owned restaurant and neighborhood context.", "official"),
    ],
  }, "Collection published with six city-scale food routes, business-level ownership evidence, and venue-churn warnings."),
];
