import { EDITORIAL_TEAM } from "@/lib/editorialTrust";
import { ATLAS_COLLECTION_REVIEWER } from "@/lib/atlasCollectionsExpansion";

const CHECKED_AT = "2026-08-12";
const source = (id, name, url, claimScope, type = "independent") => ({ id, name, url, claimScope, type, confidence: "high", checkedAt: CHECKED_AT });
const editorial = (collection, note) => ({ ...collection, author: EDITORIAL_TEAM, reviewer: ATLAS_COLLECTION_REVIEWER, publishedAt: CHECKED_AT, updatedAt: CHECKED_AT, changeLog: [{ date: CHECKED_AT, note }] });

export const SEASONAL_ATLAS_COLLECTIONS = [
  editorial({
    id: "genuinely-queer-welcoming-hotels",
    slug: "genuinely-queer-welcoming-hotels",
    title: "Genuinely Queer-Welcoming Hotels",
    eyebrow: "Stay with context",
    filter: "stays",
    intent: "best LGBTQ hotels queer welcoming stays",
    summary: "Eight stays that make a public, specific commitment to queer guests through their concept, ownership, programming, community role, or independent accreditation.",
    methodology: "Inclusion language alone is not enough. We looked for explicit LGBTQ+ positioning, queer-focused operation, community programming, or recognized accreditation, then assessed location and trip usefulness. This is not a room-by-room inspection or a guarantee about every staff interaction, access need, or guest mix.",
    bestFor: "Travelers who want their accommodation to understand the trip",
    mood: "Social, intentional, hosted",
    price: "Mid-range to premium",
    editorialNote: "A rainbow on a booking page is easy. A useful queer stay is clearer about whom it serves, where it sits in local life, and what kind of atmosphere a guest is actually buying into.",
    updated: "12 August 2026",
    cities: ["Miami Beach", "Barcelona", "Lisbon", "Berlin", "Maspalomas", "Fort Lauderdale", "Puerto Vallarta", "Provincetown"],
    items: ["Hotel Gaythering", "Axel Hotel Barcelona", "The Late Birds Lisbon", "Two Hotel Berlin by Axel", "Seven Hotel & Wellness", "The Grand Resort and Spa", "Almar Resort", "The Brass Key"],
    itemNotes: [
      "Hotel Gaythering is gay-owned and operated, with a deliberately social Miami Beach identity built around communal space rather than anonymous resort polish. Its men-focused positioning should be read plainly when deciding whether the atmosphere fits.",
      "Axel's original Barcelona property sits in the Gaixample and makes LGBTQ+ identity central to the brand, not a seasonal campaign. The rooftop and social energy are part of the proposition; travelers seeking quiet should choose room and dates carefully.",
      "The Late Birds occupies a restored Bairro Alto building with a garden and pool, framing itself as a home for gay men and the wider LGBTIQA+ community, friends, and allies. Its intimate guesthouse rhythm is more hosted than conventional chain service.",
      "Two Hotel Berlin by Axel offers a newer, more design-led base near Schöneberg with direct transport into the wider city. It suits guests who want a visibly queer hotel but do not need to sleep directly above the historic bar cluster.",
      "Seven is an adults-only Maspalomas stay marketed specifically to gay men, with suites, pool, and a residential setting away from the loudest Yumbo traffic. That separation is a strength for recovery time, but it is not the most walk-out-the-door nightlife option.",
      "The Grand is a gay men-focused Fort Lauderdale resort where pool culture, spa, and social familiarity are the point. It is better understood as a community-oriented resort experience than a neutral city hotel.",
      "Almar pairs a beachfront setting above Puerto Vallarta's gay beach zone with an explicitly LGBTQ+ resort identity. The vertical site, premium pricing, and scene-forward atmosphere make access questions and room location worth confirming directly.",
      "The Brass Key is a long-established Provincetown resort whose courtyards, pool, and social events place guests inside the town's queer seasonal rhythm. Peak-week energy and pricing change sharply across the calendar.",
    ],
    tags: ["Hotels", "Queer-owned", "Trip planning"],
    href: "/now/collections/genuinely-queer-welcoming-hotels",
    accent: "rose",
    sources: [
      source("hotel-gaythering", "Hotel Gaythering", "https://www.gaythering.com/", "Official ownership, guest focus, facilities, and Miami Beach positioning.", "official"),
      source("hotel-axel", "Axel Hotels", "https://www.axelhotels.com/en/home", "Official LGBTQIA+ hotel concept, properties, and locations.", "official"),
      source("hotel-latebirds", "The Late Birds Lisbon", "https://www.thelatebirdslisbon.com/", "Official guesthouse concept, location, facilities, and audience.", "official"),
      source("hotel-seven", "Seven Hotel & Wellness", "https://sevenhotelwellness.com/", "Official Maspalomas hotel audience and facilities.", "official"),
      source("hotel-grand", "The Grand Resort and Spa", "https://grandresort.net/", "Official Fort Lauderdale resort positioning and guest information.", "official"),
      source("hotel-almar", "Almar Resort", "https://www.almarresort.com/", "Official Puerto Vallarta property, location, and LGBTQ+ positioning.", "official"),
      source("hotel-iglta", "IGLTA Accredited", "https://www.iglta.org/iglta-accredited/", "Independent accreditation framework and inclusion standards.", "research"),
    ],
  }, "Collection published with property-specific positioning, audience caveats, direct hotel sources, and an accreditation reference."),

  editorial({
    id: "best-lgbtq-beach-towns",
    slug: "best-lgbtq-beach-towns",
    title: "Best LGBTQ+ Beach Towns",
    eyebrow: "Sea, sand, chosen family",
    filter: "beach",
    intent: "best LGBTQ beach towns gay beach destinations",
    summary: "Eight coastal destinations where the queer social map reaches from beach towel to dinner, community space, and late-night plan.",
    methodology: "Selected for durable LGBTQ+ visitor culture, identifiable queer beach or waterfront life, enough hospitality to support a trip, and a personality beyond one annual party. Season, weather, access, and audience vary significantly.",
    bestFor: "Travelers who want a queer trip with salt water in it",
    mood: "Social, sunlit, seasonal",
    price: "Accessible to premium",
    editorialNote: "A queer beach town works when the day does not end at the shoreline. These places connect swimming, walking, flirting, food, community, and nightlife—but each does so for a very different crowd.",
    updated: "12 August 2026",
    cities: ["Sitges", "Provincetown", "Puerto Vallarta", "Torremolinos", "Maspalomas", "Fire Island", "Brighton", "Florianópolis"],
    items: ["Sitges", "Provincetown", "Puerto Vallarta", "Torremolinos", "Maspalomas", "Cherry Grove and Fire Island Pines", "Brighton and Hove", "Florianópolis"],
    itemNotes: [
      "Sitges is compact enough to move from Bassa Rodona or Balmins to galleries, dinner, and bars without rebuilding the day. Pride, Bears Week, and August change both crowd and price; quieter shoulder dates reveal more of the town itself.",
      "Provincetown is a full queer ecosystem of beaches, galleries, performance, bookstores, guesthouses, and themed weeks. The absence of easy car access can feel freeing, but accommodation scarcity makes early planning essential.",
      "Puerto Vallarta's Romantic Zone links queer beach clubs, hotels, restaurants, nightlife, and boat days into one legible vacation. It is polished and visitor-heavy; heat, hills, and premium beachfront pricing should be part of the decision.",
      "Torremolinos offers a practical Andalusian combination: rail from Málaga, long urban beach, daytime chiringuitos, and the dense La Nogalera nightlife complex. The tone is relaxed, mixed-age, international, and much less manicured than a luxury island resort.",
      "Maspalomas is built around winter sun, dunes, the queer stretch of beach near the kiosks, and the Yumbo's enormous evening circuit. Distances across the resort and a heavily male visitor profile make the exact accommodation location important.",
      "Cherry Grove and the Pines share one barrier-island setting but not one social personality. Ferries, boardwalks, house culture, beach days, and seasonal parties create the magic; high costs and limited inventory demand coordination.",
      "Brighton gives a seaside trip the infrastructure of a real city: Kemptown, queer culture, the pier, independent food, and year-round rail access from London. The English Channel is bracing and summer weekends crowd quickly.",
      "Florianópolis combines a major Brazilian island destination with celebrated beaches, summer parties, and a broader nature itinerary. The queer map is spread out and car-dependent, so choose a beach base before building nights around it.",
    ],
    tags: ["Beach", "Summer", "Resorts"],
    href: "/now/collections/best-lgbtq-beach-towns",
    accent: "cyan",
    sources: [
      source("beach-sitges", "Sitges Pride", "https://sitgespride.com/", "Official visitor map, seafront context, and seasonal event information.", "official"),
      source("beach-ptown", "Provincetown Tourism", "https://ptowntourism.com/", "Official beaches, events, transport, and accommodation planning.", "official"),
      source("beach-pv", "Puerto Vallarta Tourism — LGBT travel", "https://visitpuertovallarta.com/plan-your-trip/lgbt", "Official LGBTQ+ visitor, beach, and hospitality context.", "official"),
      source("beach-torremolinos", "Torremolinos Tourism — LGTBI", "https://turismotorremolinos.es/en/what-to-do/lgtbi-gay-friendly-torremolinos/", "Official local LGBTQ+ history, beach-town identity, and nightlife.", "official"),
      source("beach-maspalomas", "Maspalomas Pride", "https://www.maspalomaspride.com/maspalomas-gay/", "Official destination, gay beach, and Yumbo context.", "official"),
      source("beach-fireisland", "Fire Island National Seashore", "https://www.nps.gov/fiis/planyourvisit/index.htm", "Official ferry, environment, access, and visitor planning.", "official"),
    ],
  }, "Collection published with eight distinct beach-town profiles, seasonal trade-offs, and official destination sources."),

  editorial({
    id: "best-gay-ski-weeks",
    slug: "best-gay-ski-weeks",
    title: "Best Gay Ski Weeks and Queer Winter Festivals",
    eyebrow: "Pride at altitude",
    filter: "events",
    intent: "best gay ski weeks queer winter festivals",
    summary: "Seven mountain gatherings where ski groups, après, drag, wellness, food, and community turn a winter trip into more than a lift pass.",
    methodology: "Included events must have a recurring public organizer, a recognizable mountain programme, and enough off-slope activity for mixed-ability groups. Dates, resorts, ticket bundles, snow conditions, and accessibility change annually and must be checked before booking.",
    bestFor: "Skiers, non-skiers, groups, and high-altitude social trips",
    mood: "Bright, communal, expensive",
    price: "Premium",
    editorialNote: "The best ski week makes room for beginners, serious riders, non-skiers, early dinners, and very late dancing. Mountain glamour is real; so are altitude, weather, cost, and the need to book the correct village.",
    updated: "12 August 2026",
    cities: ["Arosa", "Aspen", "Whistler", "Queenstown", "Mammoth Lakes", "Park City", "Tignes"],
    items: ["Arosa Gay Ski Week", "Aspen Gay Ski Week", "Whistler Pride and Ski Festival", "Winter Pride Queenstown", "Elevation Mammoth", "Utah Gay Ski Week", "European Snow Pride"],
    itemNotes: [
      "Arosa builds a friendly Swiss week around hosted skiing, après, cabaret, parties, and access to a large linked ski area. The village scale encourages repeat encounters; Swiss lodging and lift costs make packages worth comparing early.",
      "Aspen is the heritage heavyweight, mixing major fundraising, mountain groups, pool and après events, and polished town hospitality. It is also unapologetically expensive, so accommodation geography and free public events can determine whether the week feels inclusive.",
      "Whistler runs as an eight-day festival across sport, food, wellness, culture, and nightlife. Its pedestrian village is unusually convenient, while the resort's size means the official schedule is crucial for finding your people.",
      "Queenstown's Winter Pride brings a distinctly Australasian crowd to mountain days and a broad social programme. Weather can disrupt plans and the town is busy even without Pride, so flexible bookings carry real value.",
      "Elevation Mammoth has a big-party California personality with ski meetups and après built for people who want immediate social energy. The drive and storm logistics are part of the trip; do not treat Mammoth like an urban weekend.",
      "Utah Gay Ski Week uses Park City's strong terrain and compact main street as a backdrop for group skiing and social events. The local political context is more complex than the resort bubble, which makes organizer guidance worth reading.",
      "European Snow Pride pairs the vast Tignes–Val d'Isère ski domain with a multilingual European crowd and daily programming. Choose accommodation with event transport in mind: the linked terrain does not make every village equally convenient at night.",
    ],
    tags: ["Ski", "Winter", "Festivals"],
    href: "/now/collections/best-gay-ski-weeks",
    accent: "violet",
    sources: [
      source("ski-arosa", "Arosa Gay Ski Week", "https://www.arosagayskiweek.com/", "Official programme, ski area, packages, and event identity.", "official"),
      source("ski-aspen", "Aspen Gay Ski Week", "https://gayskiweek.com/", "Official Aspen programme and community fundraising.", "official"),
      source("ski-whistler", "Whistler Pride and Ski Festival", "https://whistlerpride.com/about", "Official festival scope across sport, culture, wellness, and social events.", "official"),
      source("ski-queenstown", "Winter Pride Queenstown", "https://winterpride.co.nz/about/", "Official history and New Zealand winter festival programme.", "official"),
      source("ski-elevation", "Elevation Gay Ski Week", "https://elevationgayski.com/", "Official Mammoth event dates and programme.", "official"),
      source("ski-europe", "European Snow Pride", "https://www.europeansnowpride.com/", "Official Tignes programme, accommodation, and resort information.", "official"),
    ],
  }, "Collection published with event-specific audience, logistics, cost, and non-skier context plus direct organizer sources."),

  editorial({
    id: "best-lesbian-sapphic-festivals",
    slug: "best-lesbian-sapphic-festivals",
    title: "Best Lesbian and Sapphic Festivals",
    eyebrow: "A room built around us",
    filter: "women",
    intent: "best lesbian sapphic festivals women queer events",
    summary: "Seven recurring gatherings where music, sport, beach time, film, comedy, and intergenerational community center lesbian, bisexual, trans, nonbinary, and sapphic audiences.",
    methodology: "Selected for a clear sapphic or LBTQ+ focus, recurring organizer, distinct destination value, and programming beyond a single club night. Audience language differs by organizer and can evolve; travelers should read each inclusion policy directly.",
    bestFor: "Sapphic travelers choosing a trip with a built-in community",
    mood: "Joyful, specific, collective",
    price: "Day tickets to resort packages",
    editorialNote: "Sapphic festivals are not interchangeable: a Palm Springs pool weekend, a Spanish music festival, and an intergenerational Provincetown week create radically different rooms. That specificity is the point.",
    updated: "12 August 2026",
    cities: ["Palm Springs", "Fuengirola", "Ibiza", "Mallorca", "Provincetown", "Los Angeles", "Berlin"],
    items: ["The Dinah", "Fulanita Fest", "Velvet Ibiza", "ELLA Festival", "Women's Week Provincetown", "Outfest Los Angeles", "Lesbisch-Schwules Stadtfest women's programme"],
    itemNotes: [
      "The Dinah is the high-gloss, high-energy option: hotel pools, major performers, DJs, comedy, and a large female and nonbinary crowd in Palm Springs. Choose it for scale and pop-culture spectacle, not for a quiet retreat.",
      "Fulanita Fest has grown into a substantial Costa del Sol week with concerts, sport, cinema, visual art, talks, and an explicitly LBT focus. Fuengirola's beach setting makes the trip work even when you skip the largest stage.",
      "Velvet Ibiza is a contained hotel-format experience that combines beach holiday ease with women-centered parties and social time. The package model simplifies meeting people but creates a more curated, less city-integrated trip.",
      "ELLA builds international programmes around women, nonbinary people, culture, wellbeing, talks, and music, with Mallorca as its best-known destination. Read the current edition carefully because locations and formats can change.",
      "Women's Week turns Provincetown into an intergenerational programme of comedy, authors, music, community events, and social nights. It feels rooted in town history rather than parachuted into a generic resort.",
      "Outfest is a film festival rather than a party week, and that is its strength: filmmakers, audiences, premieres, archives, and conversations put queer women's stories inside a wider LGBTQ+ screen culture.",
      "Berlin's large Stadtfest is mixed-community, but women-centered stages, organizations, and neighborhood programming can offer a more locally embedded alternative to a fly-in resort festival. Confirm the year's programme before building the trip around it.",
    ],
    tags: ["Lesbian", "Sapphic", "Festivals"],
    href: "/now/collections/best-lesbian-sapphic-festivals",
    accent: "fuchsia",
    sources: [
      source("sapphic-dinah", "The Dinah", "https://thedinah.com/", "Official audience, performers, venues, and festival programme.", "official"),
      source("sapphic-fulanita", "Fulanita Fest", "https://fulanitafest.com/en/", "Official LBT music, culture, sport, and film programme.", "official"),
      source("sapphic-velvet", "Velvet Ibiza", "https://www.velvetibiza.es/", "Official women-focused festival and accommodation format.", "official"),
      source("sapphic-ella", "ELLA Global Community", "https://www.ellaglobalcommunity.org/", "Official event mission, audience, destinations, and programme.", "official"),
      source("sapphic-ptown", "Women's Week Provincetown", "https://womensweekprovincetown.com/", "Official annual schedule and visitor programme.", "official"),
      source("sapphic-outfest", "Outfest", "https://www.outfest.org/", "Official LGBTQ+ film festival and artist programmes.", "official"),
    ],
  }, "Collection published with seven format-specific festival profiles and explicit organizer-language caveats around audience inclusion."),

  editorial({
    id: "queer-summer-without-biggest-crowds",
    slug: "queer-summer-without-biggest-crowds",
    title: "Queer Summer Without the Biggest Crowds",
    eyebrow: "A softer high season",
    filter: "hidden",
    intent: "quiet queer summer destinations alternative Pride cities",
    summary: "Eight summer cities with water, parks, culture, and queer programming—chosen as alternatives to the most compressed Pride capitals and island party weeks.",
    methodology: "We selected cities with a credible warm-season identity, recurring queer infrastructure, and enough non-nightlife value for a full trip, while avoiding claims that they are empty or undiscovered. Festival weekends can still sell out; crowd levels must be checked against local calendars.",
    bestFor: "Travelers who want queer signal without peak-resort intensity",
    mood: "Loose, local, outdoors",
    price: "Mostly accessible",
    editorialNote: "Less crowded does not mean secret. It means choosing a city where queer life can sit alongside a swim, park, tram ride, gallery, long dinner, or neighborhood festival without every hour becoming a queue.",
    updated: "12 August 2026",
    cities: ["Gothenburg", "Malmö", "Leipzig", "Bristol", "Rotterdam", "Porto", "Montevideo", "Marseille"],
    items: ["Gothenburg", "Malmö", "Leipzig", "Bristol", "Rotterdam", "Porto", "Montevideo", "Marseille"],
    itemNotes: [
      "Gothenburg's summer strength is the combination of West Pride, trams, music, harbor air, parks, and easy island ferries. The permanent queer venue list is modest, which keeps the trip city-first and makes current event timing important.",
      "Malmö offers beaches, cycling, parks, food, and a queer community shaped by both Sweden and the nearby Copenhagen region. It is compact enough for slow days; Malmö Pride and major events are the obvious exceptions to the quieter rhythm.",
      "Leipzig trades Berlin's constant decision pressure for lakes, alternative culture, inexpensive neighborhood time, and promoter-led queer nights. CSD week is busy, while the rest of summer rewards checking small calendars rather than chasing famous doors.",
      "Bristol connects harbor walks, music, street art, independent food, and a distributed queer scene. Pride draws large crowds, but ordinary summer weekends still feel like a city with queer life rather than a purpose-built LGBTQ+ resort.",
      "Rotterdam is spacious, architectural, and event-led, with river terraces, museums, and fast transport between scattered queer nights. It is an easy alternative for travelers who find central Amsterdam beautiful but exhausting in peak season.",
      "Porto's river, Atlantic edge, food, design, and smaller queer circuit make it better for mixed-energy travel than nonstop scene tourism. Hills and heat shape the day, and São João or Pride dates can radically change crowd pressure.",
      "Montevideo comes alive through the Rambla, beaches, markets, cafes, and Uruguay's strong public LGBTQ+ visibility. Southern-hemisphere seasons matter: its true summer is December to March, not the European vacation window.",
      "Marseille offers coves, ferries, North African and Mediterranean food cultures, contemporary art, and an independent queer event scene. The city is geographically rough-edged and transport to the Calanques requires planning, but it resists polished resort sameness.",
    ],
    tags: ["Summer", "Alternatives", "Slow travel"],
    href: "/now/collections/queer-summer-without-biggest-crowds",
    accent: "emerald",
    sources: [
      source("summer-gothenburg", "West Pride", "https://www.westpride.se/", "Official Gothenburg Pride and cultural programme.", "official"),
      source("summer-malmo", "Malmö Pride", "https://malmopride.com/", "Official Malmö Pride dates and community programme.", "official"),
      source("summer-leipzig", "CSD Leipzig", "https://csd-leipzig.de/", "Official Leipzig Pride and local organization.", "official"),
      source("summer-bristol", "Bristol Pride", "https://bristolpride.co.uk/", "Official Bristol Pride, culture, and community programme.", "official"),
      source("summer-rotterdam", "Rotterdam Pride", "https://rotterdam-pride.com/", "Official Rotterdam events and community context.", "official"),
      source("summer-porto", "Porto Pride", "https://www.portopride.com/", "Official Porto Pride and current summer event information.", "official"),
      source("summer-montevideo", "Uruguay Natural — LGBT tourism", "https://uruguaynatural.com/en/experiences/lgbt/", "Official national and Montevideo LGBTQ+ visitor context.", "official"),
    ],
  }, "Collection published with season-aware, city-specific alternatives and explicit warnings against calling living communities undiscovered."),
];
