import { MODULAR_CITY_SLUGS, modularSeedEvents } from "./seed/regions/emergingLatinAndBalkans.js";

import { BOLOGNA_CITY_SLUGS, bolognaSeedEvents } from "./seed/regions/bologna.js";
import { CRETE_CITY_SLUGS, creteSeedEvents } from "./seed/regions/crete.js";
import { CYPRUS_CITY_SLUGS, cyprusSeedEvents } from "./seed/regions/cyprus.js";
import { CHIANG_MAI_CITY_SLUGS, chiangMaiSeedEvents } from "./seed/regions/chiangMai.js";
import { KOH_SAMUI_CITY_SLUGS, kohSamuiSeedEvents } from "./seed/regions/kohSamui.js";
import { LJUBLJANA_CITY_SLUGS, ljubljanaSeedEvents } from "./seed/regions/ljubljana.js";
import { MARSEILLE_CITY_SLUGS, marseilleSeedEvents } from "./seed/regions/marseille.js";

function normalizeSeedKey(value = "") {
  return String(value)
    .replace(/[Ã¸Ã˜]/g, "o")
    .replace(/[Ã¦Ã†]/g, "ae")
    .replace(/[Ã¥Ã…]/g, "a")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function createEvent({ id, city, name, description, link = "", date = "", lat, lng }) {
  return {
    id,
    city,
    name,
    description,
    link,
    date,
    lat,
    lng,
    seeded: true,
  };
}

export const seedEvents = [
  createEvent({
    id: "seed-event-toronto-pride",
    city: "toronto",
    name: "Pride Toronto",
    description: "The cities flagship queer takeover. Parade scale, community programming, street heat, and a full-spectrum Toronto crowd.",
    link: "https://www.destinationtoronto.com/plan-your-trip/trip-ideas-and-itineraries/lgbtq/",
    lat: 43.6648,
    lng: -79.3832,
  }),
  createEvent({
    id: "seed-event-montreal-fierte",
    city: "montreal",
    name: "Fierte Montreal",
    description: "Montreals signature queer festival season, where The Village turns into a dense strip of terraces, performance, and community drag.",
    link: "https://www.mtl.org/en/experience/summer-village",
    lat: 45.5191,
    lng: -73.555,
  }),
  createEvent({
    id: "seed-event-vancouver-pride",
    city: "vancouver",
    name: "Vancouver Pride Season",
    description: "A Davie-and-beyond summer arc of parties, community events, and West Coast queer visibility.",
    link: "https://numbers.ca/",
    lat: 49.2838,
    lng: -123.1319,
  }),
  createEvent({
    id: "seed-event-bangkok-pride",
    city: "bangkok",
    name: "Bangkok Pride Circuit",
    description: "A citywide queer surge where nightlife, drag, and street-scale visibility fold together into one humid high-energy run.",
    link: "",
    lat: 13.729,
    lng: 100.5313,
  }),
  createEvent({
    id: "seed-event-sydney-mardi-gras",
    city: "sydney",
    name: "Sydney Mardi Gras Season",
    description: "The city's biggest queer pulse point: parade, parties, performance, and weeks of nightlife pressure around Oxford Street.",
    link: "https://www.universal.sydney/about-us/new-page-1-fjztx",
    lat: -33.8768,
    lng: 151.2178,
  }),
  createEvent({
    id: "seed-event-puertovallarta-pride",
    city: "puerto_vallarta",
    name: "Puerto Vallarta Pride",
    description: "Beach-city queer week with parades, block-party energy, and that effortless Vallarta mix of holiday ease and nightlife excess.",
    link: "https://en.wikipedia.org/wiki/Puerto_Vallarta_Pride",
    lat: 20.6049,
    lng: -105.234,
  }),
  createEvent({
    id: "seed-event-sanfrancisco-pride",
    city: "san_francisco",
    name: "San Francisco Pride",
    description: "Historic, political, and still emotionally oversized. Pride here feels like movement memory plus full-city queer presence.",
    link: "https://www.sftravel.com/article/lgbtq-san-francisco",
    lat: 37.7793,
    lng: -122.4192,
  }),
  createEvent({
    id: "seed-event-newyork-pride",
    city: "new_york",
    name: "NYC Pride",
    description: "Parade scale, protest history, nightlife overflow, and the kind of citywide queer saturation only New York can really pull off.",
    link: "https://www.nycpride.org/",
    lat: 40.7336,
    lng: -74.0027,
  }),
  createEvent({
    id: "seed-event-buenosaires-pride",
    city: "buenos_aires",
    name: "Buenos Aires Pride",
    description: "A huge, expressive citywide show of queer visibility where politics, style, and nightlife all blur together.",
    link: "https://turismo.buenosaires.gob.ar/en",
    lat: -34.6036,
    lng: -58.3817,
  }),
  createEvent({
    id: "seed-event-saopaulo-pride",
    city: "sao_paulo",
    name: "Sao Paulo Pride",
    description: "One of the worlds biggest pride-scale eruptions: massive avenue energy, street spectacle, and impossible crowd density.",
    link: "https://www.cidadedesaopaulo.com/",
    lat: -23.5614,
    lng: -46.6558,
  }),
  createEvent({
    id: "seed-event-rio-pride",
    city: "rio_de_janeiro",
    name: "Rio Pride Week",
    description: "Beach-city queer visibility with parade heat, nightlife spillover, and Rio at its most performative and free-feeling.",
    link: "https://riotur.rio/en/welcome/",
    lat: -22.9711,
    lng: -43.1822,
  }),
  createEvent({
    id: "seed-event-mexicocity-pride",
    city: "mexico_city",
    name: "Mexico City Pride",
    description: "A giant capital-city march with real cultural weight, high visibility, and major after-dark energy across Zona Rosa and beyond.",
    link: "https://mexicocity.cdmx.gob.mx/",
    lat: 19.427,
    lng: -99.1671,
  }),
  createEvent({
    id: "seed-event-bogota-pride",
    city: "bogota",
    name: "Bogota Pride",
    description: "High-altitude, high-volume queer visibility with nightlife momentum that carries well past the march itself.",
    link: "https://www.visitbogota.co/en",
    lat: 4.6097,
    lng: -74.0817,
  }),
  createEvent({
    id: "seed-event-bogota-festival-igualdad",
    city: "bogota",
    name: "Festival por la Igualdad (Bogota)",
    description: "Citywide rights-and-culture program under Bogota's public institutions, combining community events, policy visibility, and LGBTI-focused programming windows.",
    link: "https://www.sdp.gov.co/eventos-palabras-clave/festival-la-igualdad",
    lat: 4.6296,
    lng: -74.0892,
  }),
  createEvent({
    id: "seed-event-bogota-marcha-distrital-lgbti",
    city: "bogota",
    name: "Marcha Distrital LGBTI de Bogota",
    description: "Major public visibility march route in Bogota, commonly running from Parque Nacional toward Plaza de Bolivar with broad community participation.",
    link: "https://bogota.gov.co/que-hacer/cultura/marcha-distrital-lgbti",
    lat: 4.6226,
    lng: -74.0662,
  }),
  createEvent({
    id: "seed-event-bogota-kuir-festival",
    city: "bogota",
    name: "Kuir Bogota Queer Arts & Film Festival",
    description: "International queer arts-and-cinema platform in Bogota with screenings, performance, ballroom culture, and multidisciplinary programming.",
    link: "https://www.kuirbogota.com/",
    lat: 4.6486,
    lng: -74.0705,
  }),
  createEvent({
    id: "seed-event-bogota-ciclo-rosa",
    city: "bogota",
    name: "Ciclo Rosa (Cinemateca Distrital)",
    description: "Long-running LGBTIQ film program in Bogota's Cinemateca ecosystem, focused on queer cinema, discussion, and cultural memory.",
    link: "https://bogota.gov.co/que-hacer/cultura/ciclo-rosa-en-la-cinemateca-distrital",
    lat: 4.6091,
    lng: -74.0717,
  }),
  createEvent({
    id: "seed-event-bogota-groseros-party",
    city: "bogota",
    name: "Groseros Party (Sunday Circuit)",
    description: "Sunday men-focused sex-party circuit running across rotating Bogota venues, usually coordinated via social channels and WhatsApp registration.",
    link: "https://www.instagram.com/groserosparty/",
    lat: 4.6488,
    lng: -74.0625,
  }),
  createEvent({
    id: "seed-event-bogota-angels-naked-party",
    city: "bogota",
    name: "Angel's Naked Party (MegaOrgy Series)",
    description: "Rotating themed men-focused party format in Bogota, known for high-volume special editions and strict entry rules announced through social channels.",
    link: "https://www.instagram.com/angelsnakedparty/",
    lat: 4.6488,
    lng: -74.0625,
  }),
  createEvent({
    id: "seed-event-medellin-pride",
    city: "medellin",
    name: "Medellin Pride",
    description: "A warmer, more social pride rhythm built on street visibility, group energy, and nightlife that stretches the feeling into the weekend.",
    link: "",
    lat: 6.2442,
    lng: -75.5812,
  }),
  createEvent({
    id: "seed-event-taipei-pride",
    city: "taipei",
    name: "Taipei Pride",
    description: "One of Asias defining queer events, combining political visibility, strong community presence, and nightlife that radiates outward from the march.",
    link: "https://www.travel.taipei/en",
    lat: 25.0334,
    lng: 121.5645,
  }),
  createEvent({
    id: "seed-event-athens-pride",
    city: "athens",
    name: "Athens Pride",
    description: "Athens gets louder, hotter, and more public during pride, with that specific blend of activism, terrace culture, and late-night release.",
    link: "https://www.thisisathens.org/",
    lat: 37.9836,
    lng: 23.7275,
  }),
  createEvent({
    id: "seed-event-zurich-pride",
    city: "zurich",
    name: "Zurich Pride Festival",
    description: "A polished but high-energy queer weekend with parade presence, city-center visibility, and strong organization beneath the glitter.",
    link: "https://www.zuerich.com/en/visit/lgbtqia",
    lat: 47.3769,
    lng: 8.5417,
  }),
  createEvent({
    id: "seed-event-geneva-pride",
    city: "geneva",
    name: "Geneva Pride",
    description: "Smaller than the giant capitals, but meaningful, visible, and deeply community-shaped in a city that usually runs more discreet.",
    link: "https://www.geneve.com/en/",
    lat: 46.2044,
    lng: 6.1432,
  }),
  createEvent({
    id: "seed-event-taipei-redhouse-weekend",
    city: "taipei",
    name: "Red House Weekend Flow",
    description: "Less one-ticket event and more a recurring queer Taipei pulse: terrace drinks, bar-hopping, and late-night movement through the district.",
    link: "https://www.travel.taipei/en",
    lat: 25.0422,
    lng: 121.5081,
  }),
  createEvent({
    id: "seed-event-puertovallarta-beachflow",
    city: "puerto_vallarta",
    name: "Romantic Zone Weekend Flow",
    description: "Beach club by day, drag and bar circuit by night, with the whole neighborhood reading like one extended queer event.",
    link: "https://visitpuertovallarta.com/",
    lat: 20.6044,
    lng: -105.2349,
  }),
  createEvent({
    id: "seed-event-geneva-weekender",
    city: "geneva",
    name: "Geneva Queer Weekender",
    description: "A compact but high-signal weekend pattern of bars, pop-up parties, and international crowd crossover that gives Geneva extra lift.",
    link: "https://www.geneve.com/en/",
    lat: 46.2017,
    lng: 6.1452,
  }),
  createEvent({
    id: "seed-event-malta-island-weekend",
    city: "malta",
    name: "Malta Island Queer Weekend",
    description: "A nightlife-and-beach rhythm more than a formal festival, built around St Julian's, Valletta, and visitors chasing sunshine with their scene.",
    link: "https://www.visitmalta.com/en/lgbtqia-travellers/",
    lat: 35.9213,
    lng: 14.4895,
  }),
  createEvent({
    id: "seed-event-telaviv-pride",
    city: "tel_aviv",
    name: "Tel Aviv Pride",
    description: "Beach, parade, parties, and full-city queer visibility. One of the most recognizable pride-week atmospheres in the region.",
    link: "https://visit.tel-aviv.gov.il/",
    lat: 32.0853,
    lng: 34.7818,
  }),
  createEvent({
    id: "seed-event-malta-pride",
    city: "malta",
    name: "Malta Pride",
    description: "Compact island pride with strong visibility, tourism crossover, and an easy shift from march energy into nightlife.",
    link: "https://www.visitmalta.com/en/lgbtqia-travellers/",
    lat: 35.8989,
    lng: 14.5146,
  }),
  createEvent({
    id: "seed-event-la-pride",
    city: "los_angeles",
    name: "LA Pride",
    description: "Massive parade energy, WeHo overflow, drag, DJs, and one of the clearest examples of Los Angeles doing queer visibility at full scale.",
    link: "",
    lat: 34.0908,
    lng: -118.3863,
  }),
  createEvent({
    id: "seed-event-miami-pride",
    city: "miami",
    name: "Miami Beach Pride",
    description: "Beachfront visibility, drag-heavy programming, and a city that becomes even more body-conscious and celebratory than usual.",
    link: "",
    lat: 25.7907,
    lng: -80.13,
  }),
  createEvent({
    id: "seed-event-tokyo-pride",
    city: "tokyo",
    name: "Tokyo Rainbow Pride",
    description: "One of Asias most important queer visibility events, with community energy in the day and Ni-chome nightlife carrying the pulse into the night.",
    link: "",
    lat: 35.6699,
    lng: 139.6949,
  }),
  createEvent({
    id: "seed-event-ptown-carnival",
    city: "provincetown",
    name: "Provincetown Carnival",
    description: "A legendary summer blowout of costumes, drag, beach-town absurdity, and queer spectacle that takes over the whole town.",
    link: "",
    lat: 42.0584,
    lng: -70.1786,
  }),
  createEvent({
    id: "seed-event-capetown-pride",
    city: "cape_town",
    name: "Cape Town Pride",
    description: "Parade, parties, and De Waterkant nightlife giving the city an extra jolt of queer visibility against one of the most cinematic backdrops in the world.",
    link: "",
    lat: -33.9249,
    lng: 18.4241,
  }),
  createEvent({
    id: "seed-event-seoul-pride",
    city: "seoul",
    name: "Seoul Queer Culture Festival",
    description: "A major visibility moment in South Korea, with political charge by day and nightlife concentration in Itaewon later on.",
    link: "",
    lat: 37.5665,
    lng: 126.978,
  }),
  createEvent({
    id: "seed-event-ibiza-pride",
    city: "ibiza",
    name: "Ibiza Pride",
    description: "Beach, boats, bars, and island party energy folded into one of Europes most indulgent queer pride settings.",
    link: "",
    lat: 38.9067,
    lng: 1.432,
  }),
  createEvent({
    id: "seed-event-santiago-pride",
    city: "santiago",
    name: "Santiago Pride",
    description: "Urban visibility, political edge, and nightlife that gives the city a bigger and brighter queer profile for the weekend.",
    link: "",
    lat: -33.4489,
    lng: -70.6693,
  }),
  createEvent({
    id: "seed-event-hamburg-csd",
    city: "hamburg",
    name: "Hamburg Pride (CSD Hamburg)",
    description: "Harbor-city pride season with parade visibility, drag programming, and heavy weekend nightlife around St. Georg and St. Pauli.",
    link: "",
    lat: 53.5511,
    lng: 9.9937,
  }),
  createEvent({
    id: "seed-event-munich-csd",
    city: "munich",
    name: "Munich Pride (CSD MÃ¼nchen)",
    description: "A polished but high-energy citywide pride run with strong community presence and major weekend dance-floor spillover.",
    link: "",
    lat: 48.1374,
    lng: 11.5755,
  }),
  createEvent({
    id: "seed-event-frankfurt-csd",
    city: "frankfurt",
    name: "Frankfurt Pride (CSD Frankfurt)",
    description: "Compact but high-signal pride wave that gives Frankfurt extra queer street visibility and nightlife heat.",
    link: "",
    lat: 50.1109,
    lng: 8.6821,
  }),
  createEvent({
    id: "seed-event-chicago-marketdays",
    city: "chicago",
    name: "Northalsted Market Days",
    description: "One of the biggest U.S. queer street-festival weekends with massive bar spillover, stages, and full neighborhood takeover.",
    link: "",
    lat: 41.9476,
    lng: -87.6554,
  }),
  createEvent({
    id: "seed-event-lasvegas-pride",
    city: "las_vegas",
    name: "Las Vegas Pride",
    description: "Desert-night pride signal with parade programming and high-energy afterparties across off-Strip queer venues.",
    link: "",
    lat: 36.1699,
    lng: -115.1398,
  }),
  createEvent({
    id: "seed-event-sandiego-pride",
    city: "san_diego",
    name: "San Diego Pride",
    description: "Hillcrest and beyond get a full-spectrum queer surge with parade, festivals, and strong club-weekend momentum.",
    link: "",
    lat: 32.7157,
    lng: -117.1611,
  }),
  createEvent({
    id: "seed-event-philly-pride",
    city: "philadelphia",
    name: "Philadelphia Pride",
    description: "A history-rich pride cycle combining civic visibility, local community energy, and Gayborhood nightlife pressure.",
    link: "",
    lat: 39.9526,
    lng: -75.1652,
  }),
  createEvent({
    id: "seed-event-neworleans-southerndecadence",
    city: "new_orleans",
    name: "Southern Decadence",
    description: "Legendary New Orleans queer weekend where street carnival, bars, and all-night hedonism blur into one giant circuit.",
    link: "",
    lat: 29.9589,
    lng: -90.065,
  }),
  createEvent({
    id: "seed-event-orlando-pride",
    city: "orlando",
    name: "Orlando Pride",
    description: "A major Florida queer weekend with festival programming and strong after-dark venue flow across the city.",
    link: "",
    lat: 28.5383,
    lng: -81.3792,
  }),
  createEvent({
    id: "seed-event-melbourne-pride",
    city: "melbourne",
    name: "Melbourne Pride Season",
    description: "A citywide queer cultural run with parties, performance, and neighborhood nightlife peaks across Melbourne's core scene zones.",
    link: "",
    lat: -37.8136,
    lng: 144.9631,
  }),
  createEvent({
    id: "seed-event-budapest-pride",
    city: "budapest",
    name: "Budapest Pride",
    description: "High-impact annual visibility moment with strong community presence, cultural programming, and pride-week nightlife.",
    link: "",
    lat: 47.4979,
    lng: 19.0402,
  }),
  createEvent({
    id: "seed-event-valencia-pride",
    city: "valencia",
    name: "Valencia Pride",
    description: "Mediterranean pride energy with street signal, terrace culture, and city-center nightlife escalation.",
    link: "",
    lat: 39.4699,
    lng: -0.3763,
  }),
  createEvent({
    id: "seed-event-seville-pride",
    city: "seville",
    name: "Seville Pride",
    description: "Andalusian late-night pride rhythm mixing visibility, celebration, and dense old-town queer nightlife.",
    link: "",
    lat: 37.3891,
    lng: -5.9845,
  }),
  createEvent({
    id: "seed-event-hamburg-pinkinc-weekend",
    city: "hamburg",
    name: "PiNK INC Weekend",
    description: "Large-format queer dance weekend with heavy club density and strong local/visitor crossover in Hamburg.",
    link: "",
    lat: 53.5498,
    lng: 9.9679,
  }),
  createEvent({
    id: "seed-event-munich-pinkchristmas",
    city: "munich",
    name: "Pink Christmas Munich",
    description: "A festive seasonal queer city event that turns winter Munich into a social, high-vibe community run.",
    link: "",
    lat: 48.1372,
    lng: 11.5758,
  }),
  createEvent({
    id: "seed-event-frankfurt-pride-weekend",
    city: "frankfurt",
    name: "Frankfurt Pride Weekend",
    description: "A multi-day city-center queer weekend with parade visibility and concentrated nightlife programming.",
    link: "",
    lat: 50.1109,
    lng: 8.6821,
  }),
  createEvent({
    id: "seed-event-chicago-pride",
    city: "chicago",
    name: "Chicago Pride Parade Weekend",
    description: "Massive annual parade weekend with citywide queer visibility and nonstop Northalsted nightlife overflow.",
    link: "",
    lat: 41.9476,
    lng: -87.6554,
  }),
  createEvent({
    id: "seed-event-lasvegas-pride-festival",
    city: "las_vegas",
    name: "Las Vegas Pride Festival & Night Parade",
    description: "Desert-city pride weekend with evening parade, festival programming, and heavy afterparty flow across queer venues.",
    link: "",
    lat: 36.1699,
    lng: -115.1398,
  }),
  createEvent({
    id: "seed-event-sandiego-pride-weekend",
    city: "san_diego",
    name: "San Diego Pride Weekend",
    description: "A full city-wide pride peak with parade, festival stages, and strong Hillcrest nightlife extension.",
    link: "",
    lat: 32.7487,
    lng: -117.1611,
  }),
  createEvent({
    id: "seed-event-philly-pride-march",
    city: "philadelphia",
    name: "Philadelphia Pride March & Festival",
    description: "A high-visibility local-community pride cycle with Gayborhood street energy and late-night event spillover.",
    link: "",
    lat: 39.9526,
    lng: -75.1652,
  }),
  createEvent({
    id: "seed-event-neworleans-pride",
    city: "new_orleans",
    name: "New Orleans Pride",
    description: "A high-heat French Quarter pride run with parade visibility and relentless nightlife continuation after dark.",
    link: "",
    lat: 29.9589,
    lng: -90.065,
  }),
  createEvent({
    id: "seed-event-orlando-comeoutwithpride",
    city: "orlando",
    name: "Come Out With Pride Orlando",
    description: "Orlando's marquee pride weekend with major city turnout, stages, and strong post-festival nightlife momentum.",
    link: "https://www.comeoutwithpride.org/",
    lat: 28.5383,
    lng: -81.3792,
  }),
  createEvent({
    id: "seed-event-melbourne-midsumma",
    city: "melbourne",
    name: "Midsumma Festival",
    description: "Melbourne's signature queer arts and nightlife season with performances, parties, and citywide community programming.",
    link: "https://www.midsumma.org.au/",
    lat: -37.8136,
    lng: 144.9631,
  }),
  createEvent({
    id: "seed-event-budapest-pride-week",
    city: "budapest",
    name: "Budapest Pride Week",
    description: "A week-long queer city program with culture, discussion, parties, and a high-impact visibility weekend.",
    link: "",
    lat: 47.4979,
    lng: 19.0402,
  }),
  createEvent({
    id: "seed-event-valencia-fallas-queer-flow",
    city: "valencia",
    name: "Valencia Fallas Queer Flow",
    description: "During Fallas, Valencia's queer nightlife surges with packed bars, late dance rooms, and high social energy across old-town routes.",
    link: "",
    lat: 39.4699,
    lng: -0.3763,
  }),
  createEvent({
    id: "seed-event-seville-pride-weekend",
    city: "seville",
    name: "Seville Pride Weekend",
    description: "Old-town summer pride burst with terrace spillover, street visibility, and late dance-floor momentum.",
    link: "",
    lat: 37.3891,
    lng: -5.9845,
  }),
  createEvent({
    id: "seed-event-chicago-iml-weekend",
    city: "chicago",
    name: "International Mr. Leather Weekend",
    description: "One of the world's most iconic leather weekends, with parties, contest energy, and citywide after-dark escalation in Chicago.",
    link: "",
    date: "2026-05-23",
    lat: 41.8781,
    lng: -87.6298,
  }),
  createEvent({
    id: "seed-event-lasvegas-sincityclassic",
    city: "las_vegas",
    name: "Sin City Classic",
    description: "Large LGBTQ+ sports and nightlife weekend that floods Las Vegas with tournament days and party nights.",
    link: "",
    date: "2026-01-15",
    lat: 36.1699,
    lng: -115.1398,
  }),
  createEvent({
    id: "seed-event-neworleans-gayeasterparade",
    city: "new_orleans",
    name: "New Orleans Gay Easter Parade",
    description: "A camp-heavy spring parade through the French Quarter that mixes costumes, street celebration, and classic New Orleans queer charm.",
    link: "",
    date: "2026-04-05",
    lat: 29.959,
    lng: -90.0655,
  }),
  createEvent({
    id: "seed-event-philly-outfest",
    city: "philadelphia",
    name: "Philadelphia OutFest",
    description: "National Coming Out Day street festival in the Gayborhood with daytime community programming and strong nightlife continuation.",
    link: "",
    lat: 39.9526,
    lng: -75.1652,
  }),
  createEvent({
    id: "seed-event-palmsprings-pride",
    city: "palm_springs",
    name: "Palm Springs Pride",
    description: "Desert pride weekend with parade, festival grounds, and nonstop Arenas Road afterparties.",
    link: "",
    date: "2026-11-06",
    lat: 33.8233,
    lng: -116.546,
  }),
  createEvent({
    id: "seed-event-palmsprings-dinah",
    city: "palm_springs",
    name: "The Dinah Weekend",
    description: "Legendary queer women-focused party weekend with pool events, club nights, and destination-level crowd draw.",
    link: "",
    lat: 33.8303,
    lng: -116.5453,
  }),
  createEvent({
    id: "seed-event-orlando-gaydays",
    city: "orlando",
    name: "Gay Days Orlando",
    description: "Major annual Orlando takeover mixing park-day visibility with large nightlife programming across the city.",
    link: "",
    date: "2026-06-04",
    lat: 28.5383,
    lng: -81.3792,
  }),
  createEvent({
    id: "seed-event-orlando-onemagicalweekend",
    city: "orlando",
    name: "One Magical Weekend",
    description: "High-energy Orlando weekend of pool parties, dance events, and late-night circuit flow.",
    link: "",
    date: "2026-06-04",
    lat: 28.5383,
    lng: -81.3792,
  }),
  createEvent({
    id: "seed-event-sandiego-cityfest",
    city: "san_diego",
    name: "Hillcrest CityFest",
    description: "Street festival in San Diego's queer core with live stages, vendor lanes, and neighborhood nightlife surge after sunset.",
    link: "",
    lat: 32.748,
    lng: -117.161,
  }),
  createEvent({
    id: "seed-event-provincetown-bearweek",
    city: "provincetown",
    name: "Provincetown Bear Week",
    description: "One of the biggest bear-community weeks in the world, with beach days, bar runs, themed parties, and full-town social chemistry.",
    link: "",
    date: "2026-07-11",
    lat: 42.0584,
    lng: -70.1786,
  }),
  createEvent({
    id: "seed-event-provincetown-womensweek",
    city: "provincetown",
    name: "Provincetown Women's Week",
    description: "Long-running annual women-centered week with performances, community events, parties, and destination-scale queer travel energy.",
    link: "",
    lat: 42.0584,
    lng: -70.1786,
  }),
  createEvent({
    id: "seed-event-lima-pride-marcha",
    city: "lima",
    name: "Marcha del Orgullo Lima",
    description: "Lima's key annual pride march and community visibility moment, with downtown momentum and strong nightlife continuation after the march.",
    link: "",
    date: "2026-06-27",
    lat: -12.0464,
    lng: -77.0428,
  }),
  createEvent({
    id: "seed-event-lima-valetodo-weekender",
    city: "lima",
    name: "ValeTodo Weekender",
    description: "High-energy weekend dance run in Lima's queer club circuit, with drag-pop rooms and post-midnight floor pressure.",
    link: "",
    date: "2026-08-15",
    lat: -12.0466,
    lng: -77.0302,
  }),
  createEvent({
    id: "seed-event-quito-orgullo",
    city: "quito",
    name: "Orgullo Quito",
    description: "Quito's flagship Pride weekend: march visibility, community culture, and after-dark nightlife surge across the city's queer lanes.",
    link: "https://www.facebook.com/orgulloquito/",
    date: "2026-06-27",
    lat: -0.2199,
    lng: -78.5123,
  }),
  createEvent({
    id: "seed-event-quito-queer-culture-week",
    city: "quito",
    name: "Quito Queer Culture Week",
    description: "A citywide cultural run of screenings, performance nights, and community gatherings that bridge art-space daytime with queer nightlife momentum.",
    link: "",
    date: "2026-11-14",
    lat: -0.2202,
    lng: -78.5119,
  }),
  createEvent({
    id: "seed-event-bucharest-pride",
    city: "bucharest",
    name: "Bucharest PRIDE March",
    description: "Romania's flagship LGBTQ+ visibility moment: march route, community programming, and a citywide queer nightlife continuation into the weekend.",
    link: "https://acceptromania.ro/",
    date: "2026-06-27",
    lat: 44.4268,
    lng: 26.1025,
  }),
  createEvent({
    id: "seed-event-bucharest-pride-closing-night",
    city: "bucharest",
    name: "Pride Closing Club Night Bucharest",
    description: "A high-energy closing night format with drag blocks, local DJs, and full dance-floor release for the post-march crowd.",
    link: "",
    date: "2026-06-28",
    lat: 44.4314,
    lng: 26.1011,
  }),
  createEvent({
    id: "seed-event-sofia-pride",
    city: "sofia",
    name: "Sofia Pride",
    description: "Bulgaria's major queer visibility weekend with march energy, community programming, and central-city nightlife continuation.",
    link: "",
    date: "2026-06-13",
    lat: 42.6977,
    lng: 23.3219,
  }),
  createEvent({
    id: "seed-event-sofia-queer-forum",
    city: "sofia",
    name: "Sofia Queer Forum Week",
    description: "A culture-forward queer city week blending talks, screenings, and late-night social events across Sofia's core scene lanes.",
    link: "",
    date: "2026-09-19",
    lat: 42.6991,
    lng: 23.3172,
  }),
  createEvent({
    id: "seed-event-montevideo-marcha-diversidad",
    city: "montevideo",
    name: "Marcha por la Diversidad Montevideo",
    description: "Montevideo's flagship diversity march with broad community turnout and after-dark momentum through queer bars and clubs.",
    link: "",
    date: "2026-09-25",
    lat: -34.9011,
    lng: -56.1645,
  }),
  createEvent({
    id: "seed-event-montevideo-chains-anniversary",
    city: "montevideo",
    name: "Chains Anniversary Weekend",
    description: "A local-favorite Montevideo weekend run with DJ nights, drag moments, and a packed crowd across the city's late queer circuit.",
    link: "",
    date: "2026-11-14",
    lat: -34.9052,
    lng: -56.1905,
  }),
  createEvent({
    id: "seed-event-oslo-pride-week",
    city: "oslo",
    name: "Oslo Pride Week",
    description: "Norway's biggest queer rights and culture week with citywide programming, community stages, and nightlife escalation across central Oslo.",
    link: "https://www.oslopride.no/?lang=en",
    date: "2026-06-19",
    lat: 59.9139,
    lng: 10.7522,
  }),
  createEvent({
    id: "seed-event-oslo-pride-parade",
    city: "oslo",
    name: "Oslo Pride Parade",
    description: "The main Pride procession and visibility peak of Oslo Pride week, followed by full-spectrum queer nightlife continuation.",
    link: "https://www.oslopride.no/?lang=en",
    date: "2026-06-27",
    lat: 59.9139,
    lng: 10.7522,
  }),
  createEvent({
    id: "seed-event-helsinki-pride-week",
    city: "helsinki",
    name: "Helsinki Pride Week",
    description: "Finland's largest LGBTQIA+ culture and rights week with community programming, Pride House events, and citywide queer momentum.",
    link: "https://pride.fi/en/helsinki-pride-2026/",
    date: "2026-06-22",
    lat: 60.1699,
    lng: 24.9384,
  }),
  createEvent({
    id: "seed-event-helsinki-pride-parade",
    city: "helsinki",
    name: "Helsinki Pride Parade",
    description: "The major equality march and park festival day that closes Pride week in Helsinki with massive turnout and high emotional signal.",
    link: "https://pride.fi/en/helsinki-pride-2026/",
    date: "2026-06-27",
    lat: 60.1619,
    lng: 24.9522,
  }),
  createEvent({
    id: "seed-event-helsinki-flow-festival",
    city: "helsinki",
    name: "Flow Festival Helsinki",
    description: "High-impact summer festival weekend in Suvilahti with international acts, design-forward production, and strong queer crowd crossover.",
    link: "https://www.flowfestival.com/en/",
    date: "2026-08-14",
    lat: 60.1864,
    lng: 24.9771,
  }),
  createEvent({
    id: "seed-event-reykjavik-pride-week",
    city: "reykjavik",
    name: "Reykjavik Pride Week",
    description: "One of the world's biggest little Prides: citywide queer celebration, community events, and high-visibility solidarity in central Reykjavik.",
    link: "https://visitreykjavik.is/festivals-and-events-reykjavik/reykjavik-pride",
    date: "2026-08-04",
    lat: 64.1466,
    lng: -21.9426,
  }),
  createEvent({
    id: "seed-event-reykjavik-pride-parade",
    city: "reykjavik",
    name: "Reykjavik Pride Parade",
    description: "Reykjavik's signature Pride procession and emotional peak, followed by concerts and full-night city-center queer celebration.",
    link: "https://visitreykjavik.is/festivals-and-events-reykjavik/reykjavik-pride",
    date: "2026-08-08",
    lat: 64.1466,
    lng: -21.9426,
  }),
  createEvent({
    id: "seed-event-sanjuan-pride-weekend",
    city: "san_juan",
    name: "San Juan Pride Weekend",
    description: "Citywide June pride momentum with march visibility, drag nights, and packed Condado/Santurce after-dark programming.",
    link: "",
    date: "2026-06-27",
    lat: 18.4655,
    lng: -66.1057,
  }),
  createEvent({
    id: "seed-event-sanjuan-circuit-nights",
    city: "san_juan",
    name: "San Juan Summer Circuit Nights",
    description: "Peak-summer queer nightlife surge with guest DJs, themed nights, and heavy late-floor turnout across San Juan's core venues.",
    link: "",
    date: "2026-08-01",
    lat: 18.4558,
    lng: -66.0702,
  }),
  createEvent({
    id: "seed-event-edinburgh-pride",
    city: "edinburgh",
    name: "Pride Edinburgh",
    description: "Scotland's flagship free Pride march and festival day with major city-center visibility and full-night queer continuation.",
    link: "https://www.prideedinburgh.org/",
    date: "2026-06-20",
    lat: 55.9533,
    lng: -3.1883,
  }),
  createEvent({
    id: "seed-event-edinburgh-fringe-queer",
    city: "edinburgh",
    name: "Edinburgh Fringe Queer Weekender",
    description: "Fringe-season queer performance wave with cabaret, late-night parties, and packed bar-to-club crossover in central Edinburgh.",
    link: "https://www.edfringe.com/",
    date: "2026-08-22",
    lat: 55.9496,
    lng: -3.1902,
  }),
  createEvent({
    id: "seed-event-gdl-marcha-orgullo",
    city: "guadalajara",
    name: "Marcha del Orgullo GDL",
    description: "One of Mexicos biggest Pride mobilizations, with a massive downtown march and high-impact nightlife continuation.",
    link: "https://www.uniondiversadejalisco.org/",
    date: "2026-06-13",
    lat: 20.6736,
    lng: -103.3832,
  }),
  createEvent({
    id: "seed-event-gdl-pride-festival",
    city: "guadalajara",
    name: "Guadalajara Pride Festival",
    description: "Weeklong June city pulse of drag shows, queer parties, and post-march festival programming across Centro and Chapultepec lanes.",
    link: "",
    date: "2026-06-20",
    lat: 20.6767,
    lng: -103.3475,
  }),
  createEvent({
    id: "seed-event-istanbul-trans-pride-week",
    city: "istanbul",
    name: "Istanbul Trans Pride Week",
    description: "Community-led Trans+ pride organizing week in Istanbul with solidarity actions, visibility moments, and coordinated community programming.",
    link: "https://transprideistanbul.com/en/",
    date: "2026-06-21",
    lat: 41.0365,
    lng: 28.977,
  }),
  createEvent({
    id: "seed-event-istanbul-queer-olympix",
    city: "istanbul",
    name: "Queer Olympix Istanbul",
    description: "Annual queer sports and community gathering in Istanbul focused on safe participation, visibility, and collective joy across multiple activities.",
    link: "https://queerolympix.com/en/",
    date: "2026-09-12",
    lat: 40.9806,
    lng: 29.0488,
  }),
  createEvent({
    id: "seed-event-sanjose-pride-festival",
    city: "san_jose",
    name: "Orgullo Costa Rica Festival Week",
    description: "San Jose's annual June Pride programming with inclusive fair events, community activities, and nightlife uplift across the capital.",
    link: "https://orgullocostarica.com/",
    date: "2026-06-20",
    lat: 9.9342,
    lng: -84.0841,
  }),
  createEvent({
    id: "seed-event-sanjose-marcha-diversidad",
    city: "san_jose",
    name: "Marcha del Orgullo San Jose",
    description: "The capital's main Pride march and visibility peak, bringing broad community turnout and city-center queer momentum.",
    link: "https://orgullocostarica.com/",
    date: "2026-06-28",
    lat: 9.9326,
    lng: -84.0866,
  }),
  createEvent({
    id: "seed-event-bratislava-duhovy-pride",
    city: "bratislava",
    name: "Duhovy PRIDE Bratislava",
    description: "Slovakias flagship Pride gathering with central-city programming, community visibility, and major annual turnout in Bratislava.",
    link: "https://duhovypride.sk/",
    date: "2026-07-18",
    lat: 48.1518,
    lng: 17.1128,
  }),
  createEvent({
    id: "seed-event-bratislava-pride-week",
    city: "bratislava",
    name: "Bratislava Pride Community Week",
    description: "Pride-adjacent week of queer community events, cultural programming, and social meetups leading into the main city Pride day.",
    link: "https://duhovypride.sk/",
    date: "2026-07-13",
    lat: 48.1482,
    lng: 17.1067,
  }),
  createEvent({
    id: "seed-event-bratislava-homomat",
    city: "bratislava",
    name: "HOMOMAT @ Re:FRESH Club",
    description: "Recurring queer dance party in central Bratislava known for house-led sets and event-night crowd surges.",
    link: "https://queerslovakia.sk/",
    date: "2026-09-26",
    lat: 48.1445,
    lng: 17.1093,
  }),
  createEvent({
    id: "seed-event-bratislava-tutti-frutti",
    city: "bratislava",
    name: "Tutti Frutti @ HSC",
    description: "Pop-forward recurring queer party format in Bratislava with dance-floor focus and mixed local crowd turnout.",
    link: "https://queerslovakia.sk/",
    date: "2026-10-17",
    lat: 48.1457,
    lng: 17.1119,
  }),
  createEvent({
    id: "seed-event-panamacity-pride",
    city: "panama_city",
    name: "Panama Pride March",
    description: "Panama City's annual Pride march and festival season with central-city visibility actions, cultural programming, and large public turnout.",
    link: "https://www.panamapride.org/",
    date: "2026-06-27",
    lat: 8.981,
    lng: -79.5262,
  }),
  createEvent({
    id: "seed-event-panamacity-pride-village",
    city: "panama_city",
    name: "Panama Pride Village",
    description: "Pride Village marketplace and community activation with creators, organizations, and live-programmed Pride-day participation.",
    link: "https://www.panamapride.org/pridevillage/",
    date: "2026-06-27",
    lat: 8.9514,
    lng: -79.533,
  }),
  createEvent({
    id: "seed-event-caracas-pride-march",
    city: "caracas",
    name: "Caracas Pride March",
    description: "Annual Caracas Pride march and rights-focused visibility event bringing community groups and allies into central-city mobilization.",
    link: "https://unionradio.net/enfotos-la-marcha-del-orgullo-lgbtiq-en-caracas/",
    date: "2026-06-28",
    lat: 10.4923,
    lng: -66.8609,
  }),
  createEvent({
    id: "seed-event-caracas-plural-pride-week",
    city: "caracas",
    name: "Pais Plural Pride Week",
    description: "Pride-season community and culture block coordinated by local organizers, centered on inclusion, education, and safe-space participation.",
    link: "https://www.paisplural.org/",
    date: "2026-06-24",
    lat: 10.4889,
    lng: -66.8792,
  }),
  createEvent({
    id: "seed-event-asuncion-marcha-orgullo",
    city: "asuncion",
    name: "Marcha del Orgullo Asuncion",
    description: "Asuncion's annual Pride march and downtown celebration focused on visibility, rights, and broad LGBTIQ+ community turnout.",
    link: "https://www.abc.com.py/nacionales/2023/07/01/el-orgullo-gay-marcha-en-el-centro-de-asuncion/",
    date: "2026-06-28",
    lat: -25.2828,
    lng: -57.6359,
  }),
  createEvent({
    id: "seed-event-asuncion-somosgay-pride-week",
    city: "asuncion",
    name: "SOMOSGAY Pride Community Week",
    description: "Community-led Pride-week programming in Asuncion with advocacy, public discussion, and cultural activities around the annual march period.",
    link: "https://somosgay.org/",
    date: "2026-06-24",
    lat: -25.2893,
    lng: -57.6383,
  }),
  createEvent({
    id: "seed-event-washdc-capital-pride",
    city: "washington_dc",
    name: "Capital Pride Parade & Festival",
    description: "Washington, DC's flagship Pride weekend with parade visibility, festival programming, and major nightlife continuation.",
    link: "https://www.capitalpride.org/the-capital-pride-alliance-announces-dates-and-registration-for-the-annual-pride-celebration/",
    date: "2026-06-20",
    lat: 38.9072,
    lng: -77.0369,
  }),
  createEvent({
    id: "seed-event-washdc-capital-pride-block-party",
    city: "washington_dc",
    name: "Capital Pride Block Party",
    description: "High-energy Capital Pride nightlife event format with DJs, performances, and city-center crowd density.",
    link: "https://www.capitalpride.org/",
    date: "2026-06-21",
    lat: 38.9072,
    lng: -77.0369,
  }),
  createEvent({
    id: "seed-event-seattle-pride-parade",
    city: "seattle",
    name: "Seattle Pride Parade Weekend",
    description: "One of the largest Pride gatherings in the region with parade, in-park programming, and citywide LGBTQIA+ turnout.",
    link: "https://seattlepride.org/seattlepride",
    date: "2026-06-28",
    lat: 47.6062,
    lng: -122.3321,
  }),
  createEvent({
    id: "seed-event-seattle-pridefest",
    city: "seattle",
    name: "Seattle PrideFest",
    description: "Downtown Pride festival programming with performances, community stages, and post-festival nightlife continuation.",
    link: "https://www.seattlepridefest.org/",
    date: "2026-06-27",
    lat: 47.608,
    lng: -122.3352,
  }),
  createEvent({
    id: "seed-event-atlanta-pride-festival",
    city: "atlanta",
    name: "Atlanta Pride Festival",
    description: "One of the largest free Pride festivals in the U.S. with city-center visibility and major Southeast community draw.",
    link: "https://atlantapride.org/about-us/mission/",
    date: "2026-10-10",
    lat: 33.749,
    lng: -84.388,
  }),
  createEvent({
    id: "seed-event-atlanta-black-pride-weekend",
    city: "atlanta",
    name: "Atlanta Black Pride Weekend",
    description: "Major annual Black queer celebration weekend with nightlife, community programming, and strong regional turnout.",
    link: "https://atlantablackpride.org/",
    date: "2026-09-06",
    lat: 33.749,
    lng: -84.388,
  }),
  createEvent({
    id: "seed-event-boston-pride-for-the-people",
    city: "boston",
    name: "Boston Pride For The People",
    description: "Large-format Pride parade and festival celebrating LGBTQ+ visibility and community culture across Boston.",
    link: "https://www.bostonprideforthepeople.org/",
    date: "2026-06-06",
    lat: 42.3601,
    lng: -71.0589,
  }),
  createEvent({
    id: "seed-event-boston-queer-film-festival",
    city: "boston",
    name: "Wicked Queer Film Festival",
    description: "Long-running LGBTQ+ film festival showcasing queer cinema, filmmakers, and community screenings across Boston.",
    link: "https://wickedqueer.org/",
    date: "2026-04-05",
    lat: 42.3601,
    lng: -71.0589,
  }),
  createEvent({
    id: "seed-event-dallas-pride-downtown",
    city: "dallas",
    name: "Dallas Pride Downtown Weekend",
    description: "Dallas Pride's downtown parade and festival weekend with major Oak Lawn and city-center nightlife spillover.",
    link: "https://dallaspride.org/",
    date: "2026-09-19",
    lat: 32.7767,
    lng: -96.797,
  }),
  createEvent({
    id: "seed-event-dallas-black-tie-dinner",
    city: "dallas",
    name: "Black Tie Dinner Weekend",
    description: "Landmark LGBTQ+ fundraising weekend and gala drawing broad community and ally participation in Dallas.",
    link: "https://blacktie.org/",
    date: "2026-11-15",
    lat: 32.7831,
    lng: -96.8067,
  }),
  createEvent({
    id: "seed-event-denver-pridefest",
    city: "denver",
    name: "Denver PrideFest",
    description: "A top U.S. Pride event with high-volume attendance, civic visibility, and a full weekend queer city takeover.",
    link: "https://visitdenver.com/about-denver/lgbtq/",
    date: "2026-06-27",
    lat: 39.7392,
    lng: -104.9903,
  }),
  createEvent({
    id: "seed-event-denver-queer-affair",
    city: "denver",
    name: "The Denver Gay Affair",
    description: "LGBTQ+ social and nightlife weekend activation known for dance events and citywide queer meetups.",
    link: "https://thedenvergayaffair.com/",
    date: "2026-07-18",
    lat: 39.7392,
    lng: -104.9903,
  }),
  createEvent({
    id: "seed-event-austin-pride-festival",
    city: "austin",
    name: "Austin Pride Festival + Parade",
    description: "Austin's annual Pride festival and parade with citywide community programming and strong nightlife continuation.",
    link: "https://austinpride.org/",
    date: "2026-08-22",
    lat: 30.2672,
    lng: -97.7431,
  }),
  createEvent({
    id: "seed-event-austin-qmmunity-showcase",
    city: "austin",
    name: "Qmmunity Showcase",
    description: "Austin queer community showcase and social programming highlighting local performers, organizers, and nightlife connectors.",
    link: "https://www.austintexas.org/austin-insider-blog/post/lgbtq-queer-austin/",
    date: "2026-05-23",
    lat: 30.2672,
    lng: -97.7431,
  }),
  createEvent({
    id: "seed-event-auckland-pride-festival",
    city: "auckland",
    name: "Auckland Pride Festival",
    description: "Aotearoa's largest Takatapui and Rainbow arts-and-community festival with citywide programming each February.",
    link: "https://aucklandpride.org.nz/event-registration-guide/",
    date: "2026-02-14",
    lat: -36.8485,
    lng: 174.7633,
  }),
  createEvent({
    id: "seed-event-wellington-pride-festival",
    city: "wellington",
    name: "Wellington Pride Festival",
    description: "The longest-running annual Pride celebration in Aotearoa, with two-week community and cultural programming.",
    link: "https://www.wellingtonpridefestival.com/about-wpf",
    date: "2026-03-15",
    lat: -41.2865,
    lng: 174.7772,
  }),
  createEvent({
    id: "seed-event-brisbane-pride-festival",
    city: "brisbane",
    name: "Brisbane Pride Festival",
    description: "Queensland's flagship Pride season featuring rally and march, fair day, and large community celebrations.",
    link: "https://www.brisbanepride.org.au/",
    date: "2026-09-12",
    lat: -27.4698,
    lng: 153.0251,
  }),
  createEvent({
    id: "seed-event-singapore-pink-dot",
    city: "singapore",
    name: "Pink Dot Singapore",
    description: "Singapore's landmark LGBTQ+ community movement event centered on visibility, belonging, and collective support.",
    link: "https://pinkdot.sg/",
    date: "2026-06-27",
    lat: 1.285,
    lng: 103.845,
  }),
  createEvent({
    id: "seed-event-hongkong-hklgff",
    city: "hong_kong",
    name: "Hong Kong Lesbian & Gay Film Festival",
    description: "Asia's longest-running LGBTQ+ film festival with screenings, Q&As, and cultural programming across Hong Kong.",
    link: "https://www.hklgff.hk/",
    date: "2026-09-12",
    lat: 22.3193,
    lng: 114.1694,
  }),
  createEvent({
    id: "seed-event-wellington-pride-parade",
    city: "wellington",
    name: "Wellington Pride Parade",
    description: "City-center Pride parade and visibility celebration that anchors Wellington's annual festival period.",
    link: "https://www.wellingtonpridefestival.com/",
    date: "2026-03-21",
    lat: -41.2865,
    lng: 174.7772,
  }),
  createEvent({
    id: "seed-event-brisbane-fair-day",
    city: "brisbane",
    name: "Brisbane Pride Fair Day",
    description: "Community fair-day format with live programming, stalls, and all-day queer social energy during Pride season.",
    link: "https://www.brisbanepride.org.au/",
    date: "2026-09-13",
    lat: -27.4698,
    lng: 153.0251,
  }),
  createEvent({
    id: "seed-event-singapore-pride-month-arts",
    city: "singapore",
    name: "Pink Fest Singapore",
    description: "Annual LGBTQ+ arts, talks, and social programming cluster aligned with Pink Dot season in Singapore.",
    link: "https://pinkfest.sg/",
    date: "2026-06-15",
    lat: 1.29,
    lng: 103.85,
  }),
  createEvent({
    id: "seed-event-hongkong-pride-parade",
    city: "hong_kong",
    name: "Hong Kong Pride Parade",
    description: "Annual city Pride parade with broad local and regional participation focused on visibility and rights advocacy.",
    link: "https://hkprideparade.com/",
    date: "2026-11-14",
    lat: 22.3193,
    lng: 114.1694,
  }),
  createEvent({
    id: "seed-event-auckland-pride-march",
    city: "auckland",
    name: "Auckland Pride March",
    description: "Community-led Pride march through central Auckland focused on visibility, inclusion, and collective celebration.",
    link: "https://aucklandpride.org.nz/",
    date: "2026-02-21",
    lat: -36.8523,
    lng: 174.7631,
  }),
  createEvent({
    id: "seed-event-zagreb-pride",
    city: "zagreb",
    name: "Zagreb Pride",
    description: "Annual community-organized Pride march and rights-focused programming window across Zagreb.",
    link: "https://zagreb-pride.net/",
    date: "2026-06-13",
    lat: 45.815,
    lng: 15.9819,
  }),
  createEvent({
    id: "seed-event-zagreb-queer-zagreb-season",
    city: "zagreb",
    name: "Queer Zagreb Season",
    description: "Multi-week queer arts and performance program built around theatre, talks, screenings, and activist culture.",
    link: "https://www.festivalfinder.eu/festivals/queer-zagreb-season",
    date: "2026-05-22",
    lat: 45.8114,
    lng: 15.9743,
  }),
  createEvent({
    id: "seed-event-belgrade-pride-week",
    city: "belgrade",
    name: "Belgrade Pride Week",
    description: "Citywide Pride week with panels, performances, community events, and the annual protest march.",
    link: "https://prajd.rs/en/",
    date: "2026-08-31",
    lat: 44.8125,
    lng: 20.4612,
  }),
  createEvent({
    id: "seed-event-belgrade-pride-march",
    city: "belgrade",
    name: "Belgrade Pride Protest March",
    description: "Belgrade's main annual Pride march centered on visibility, equality, and legal rights demands.",
    link: "https://prajd.rs/en/",
    date: "2026-09-05",
    lat: 44.8067,
    lng: 20.4585,
  }),
  createEvent({
    id: "seed-event-manila-love-laban-2026",
    city: "manila",
    name: "Love Laban Pride Festival 2026",
    description: "Pride PH's annual flagship march and festival in Metro Manila. 2026 date announced for June 27, with detailed program rollout closer to event week.",
    link: "https://philstarlife.com/geeky/655904-quezon-city-pride-festival-2026-date",
    date: "2026-06-27",
    lat: 14.6514468,
    lng: 121.0492878,
  }),
  createEvent({
    id: "seed-event-manila-metro-pride-2026",
    city: "manila",
    name: "Metro Manila Pride March & Festival 2026",
    description: "Metro Manila Pride's annual citywide march-and-festival window, typically anchored in late June with visibility, protest, and community programming.",
    link: "https://www.facebook.com/mmprideorg/",
    date: "2026-06-27",
    lat: 14.5995,
    lng: 120.9842,
  }),
  createEvent({
    id: "seed-event-manila-loveyourself-pride-night-2026",
    city: "manila",
    name: "LoveYourself Pride Night 2026",
    description: "Community Pride-month kickoff event featuring performances and advocacy programming in Metro Manila's Pasig corridor.",
    link: "https://www.thegayagenda.fyi/manila/events/loveyourself-pride-night-jun-6-2026/",
    date: "2026-06-06",
    lat: 14.5605166,
    lng: 121.0764343,
  }),
  createEvent({
    id: "seed-event-fireisland-invasion-2026",
    city: "fireisland",
    name: "Fire Island Invasion 2026",
    description: "Historic July drag flotilla and parade ritual from Cherry Grove to Fire Island Pines, one of the island's defining annual queer traditions.",
    link: "https://invasionfireisland.com/",
    date: "2026-07-04",
    lat: 40.6601,
    lng: -73.0896,
  }),
  createEvent({
    id: "seed-event-fireisland-pines-party-2026",
    city: "fireisland",
    name: "Pines Party 2026",
    description: "Major Fire Island summer fundraiser weekend with beach-party scale production, multi-event programming, and peak queer crowd concentration.",
    link: "https://www.pinesparty.com/",
    date: "2026-07-31",
    lat: 40.6446,
    lng: -73.0691,
  }),
  createEvent({
    id: "seed-event-fireisland-dance-festival-2026",
    city: "fireisland",
    name: "Fire Island Dance Festival",
    description: "Annual dance and fundraising weekend on Fire Island with performance-led programming and strong community visibility.",
    link: "https://www.dradance.org/",
    date: "",
    lat: 40.6453,
    lng: -73.0695,
  }),
  createEvent({
    id: "seed-event-bilbao-harro-pride-2026",
    city: "bilbao",
    name: "Bilbao Bizkaia HARRO Pride",
    description: "Bilbao's flagship Pride framework with community events, nightlife programming, and broad citywide LGBTQIA+ visibility moments.",
    link: "https://bilbaobizkaiapride.com/",
    date: "",
    lat: 43.263,
    lng: -2.935,
  }),
  createEvent({
    id: "seed-event-bilbao-zinegoak-2026",
    city: "bilbao",
    name: "Zinegoak 2026",
    description: "International LGBTQIA+ film and performing arts festival in Bilbao, combining screenings, talks, and community-facing culture programming.",
    link: "https://zinegoak.com/",
    date: "2026-06-22",
    lat: 43.263,
    lng: -2.935,
  }),
  createEvent({
    id: "seed-event-bilbao-zinebi-2026",
    city: "bilbao",
    name: "ZINEBI 2026 Queer Program Highlights",
    description: "Bilbao's international documentary and short-film festival with recurring queer-interest screenings and cinema-culture crossover.",
    link: "https://zinebi.eus/en/",
    date: "2026-11-20",
    lat: 43.2633,
    lng: -2.935,
  }),
  createEvent({
    id: "seed-event-krakow-maj-rownosci-2026",
    city: "krakow",
    name: "Maj Rownosci Krakow 2026",
    description: "Month-long equality and queer-inclusive civic program in Krakow with talks, exhibitions, workshops, and community programming.",
    link: "https://rownosc.krakow.pl/",
    date: "2026-04-27",
    lat: 50.0606,
    lng: 19.9373,
  }),
  createEvent({
    id: "seed-event-krakow-marsz-rownosci-2026",
    city: "krakow",
    name: "XXII Marsz Rownosci w Krakowie",
    description: "Krakow's annual Equality March and visibility action, positioned as the flagship public moment of Queerowy Maj season.",
    link: "https://rownosc.krakow.pl/aktualnosci/318948%2C2295%2Ckomunikat%2Cprogram_maja_rownosci_2026.html",
    date: "2026-05-23",
    lat: 50.0606,
    lng: 19.9236,
  }),
  createEvent({
    id: "seed-event-krakow-queerowy-maj-festival-2026",
    city: "krakow",
    name: "Queerowy Maj Festival",
    description: "Community-led queer culture and rights festival in Krakow featuring screenings, parties, conversations, and activist solidarity events.",
    link: "https://www.facebook.com/queerowymaj",
    date: "",
    lat: 50.0647,
    lng: 19.945,
  }),
  createEvent({
    id: "seed-event-nice-lou-queernaval-2026",
    city: "nice",
    name: "Lou Queernaval Nice 2026",
    description: "Official queer carnival night in Nice with drag-led street energy, costumes, and public visibility inside the broader Carnaval de Nice calendar.",
    link: "https://www.nicecarnaval.com/en/programme/lou-queernaval/",
    date: "2026-02-27",
    lat: 43.6958,
    lng: 7.2684,
  }),
  createEvent({
    id: "seed-event-nice-inout-2026",
    city: "nice",
    name: "In & Out Festival Nice 2026",
    description: "Queer film and culture festival run by Les Ouvreurs, with screenings, talks, and community programming in Nice.",
    link: "https://www.lesouvreurs.com/inout",
    date: "2026-04-23",
    lat: 43.7048,
    lng: 7.2672,
  }),
  createEvent({
    id: "seed-event-nice-gaymes-2026",
    city: "nice",
    name: "Nice Gaymes 2026",
    description: "Multisport LGBTQIA+ tournament weekend in Nice with social programming, team meetups, and citywide community momentum.",
    link: "https://www.nicegaymes.com/",
    date: "2026-09-18",
    lat: 43.7102,
    lng: 7.262,
  }),
  createEvent({
    id: "seed-event-tallinn-baltic-pride-week-2026",
    city: "tallinn",
    name: "Baltic Pride Tallinn 2026",
    description: "Regional Pride week hosted in Tallinn with community events, performances, rights-focused programming, and citywide queer visibility.",
    link: "https://balticpride.ee/",
    date: "2026-06-01",
    lat: 59.437,
    lng: 24.7536,
  }),
  createEvent({
    id: "seed-event-tallinn-baltic-pride-march-2026",
    city: "tallinn",
    name: "Baltic Pride March Tallinn",
    description: "Flagship Baltic Pride march route through central Tallinn, ending in a public celebration format. Date aligns with official Pride-week program window.",
    link: "https://balticpride.ee/events/",
    date: "2026-06-06",
    lat: 59.4367,
    lng: 24.7429,
  }),
  createEvent({
    id: "seed-event-tallinn-baltic-pride-concert-2026",
    city: "tallinn",
    name: "Baltic Pride Open Air Concert",
    description: "Baltic Pride's evening concert activation at Telliskivi with live performance and post-march community celebration.",
    link: "https://balticpride.ee/events/",
    date: "2026-06-06",
    lat: 59.4395,
    lng: 24.7285,
  }),
  createEvent({
    id: "seed-event-florence-out-loud-2026",
    city: "florence",
    name: "OUT LOUD - A Queer Stand-Up Night",
    description: "Queer comedy night in Florence hosted with community focus and performance-first social atmosphere at IREOS.",
    link: "https://billetto.it/en/e/out-loud-a-queer-stand-up-night-billets-1321946",
    date: "2026-04-18",
    lat: 43.7709,
    lng: 11.2683,
  }),
  createEvent({
    id: "seed-event-florence-queer-festival-2026",
    city: "florence",
    name: "Florence Queer Festival",
    description: "Annual queer cinema and culture festival in Florence with screenings, debates, and independent LGBTQIA+ artistic programming.",
    link: "https://www.florencequeerfestival.it/",
    date: "",
    lat: 43.7731,
    lng: 11.2588,
  }),
  createEvent({
    id: "seed-event-phnompenh-pride-fest-2026",
    city: "phnom_penh",
    name: "Pride Fest Cambodia 2026",
    description: "Phnom Penh's flagship Pride day with community stages, drag-led programming, visibility actions, and citywide nightlife continuation.",
    link: "https://pridecambodia.org/",
    date: "2026-06-20",
    lat: 11.5467,
    lng: 104.9369,
  }),
  createEvent({
    id: "seed-event-phnompenh-rainbow-run-2026",
    city: "phnom_penh",
    name: "Pride Rainbow Run Phnom Penh",
    description: "Pride Cambodia's community run format linked to Pride Fest programming, designed to blend visibility, wellness, and social kickoff energy.",
    link: "https://pridecambodia.org/",
    date: "2026-06-20",
    lat: 11.5616,
    lng: 104.9318,
  }),
  createEvent({
    id: "seed-event-phnompenh-reajiny-stage-2026",
    city: "phnom_penh",
    name: "Reajiny Pride Stage",
    description: "Pride-weekend drag and performance window in Phnom Penh spotlighting local queer talent and activist-community messaging.",
    link: "https://khmer.lgbt/event/agenda-for-pride-fest-cambodia-june-20th-2026/",
    date: "2026-06-20",
    lat: 11.5467,
    lng: 104.9369,
  }),
  createEvent({
    id: "seed-event-hochiminh-vietpride-2026",
    city: "ho_chi_minh",
    name: "VietPride Ho Chi Minh City",
    description: "Annual VietPride city programming in Ho Chi Minh City with talks, creative activations, and community visibility moments coordinated with local organizers.",
    link: "https://ics.org.vn/",
    date: "",
    lat: 10.7765,
    lng: 106.7009,
  }),
  createEvent({
    id: "seed-event-hochiminh-idahobit-2026",
    city: "ho_chi_minh",
    name: "IDAHOBIT Saigon Community Actions",
    description: "May 17 rights-visibility programming in Ho Chi Minh City led by community groups and allies through public education and solidarity actions.",
    link: "https://ics.org.vn/",
    date: "2026-05-17",
    lat: 10.7765,
    lng: 106.7009,
  }),
  createEvent({
    id: "seed-event-hochiminh-vietpride-community-week-2026",
    city: "ho_chi_minh",
    name: "VietPride Community Week Saigon",
    description: "Community-led Pride week format in Saigon with social gatherings, workshops, and nightlife-linked events around annual VietPride momentum.",
    link: "https://www.facebook.com/VietPride/",
    date: "",
    lat: 10.7728,
    lng: 106.6982,
  }),
  createEvent({
    id: "seed-event-shanghai-shqff-2026",
    city: "shanghai",
    name: "Shanghai Queer Film Festival",
    description: "Volunteer-run queer film festival programming in Shanghai focused on screening culture, dialogue, and independent LGBTQIA+ storytelling.",
    link: "https://www.shqff.org/",
    date: "",
    lat: 31.2304,
    lng: 121.4737,
  }),
  createEvent({
    id: "seed-event-shanghai-cinemq-series-2026",
    city: "shanghai",
    name: "CINEMQ Screening Series",
    description: "Ongoing queer cinema nights and popup screening format in Shanghai, built around independent curators and community-hosted events.",
    link: "https://filmfreeway.com/CINEMQ",
    date: "",
    lat: 31.2304,
    lng: 121.4737,
  }),
  createEvent({
    id: "seed-event-shanghai-pride-community-2026",
    city: "shanghai",
    name: "Shanghai Pride Community Programming",
    description: "Community-linked workshops, talks, and collaborative events inspired by Shanghai Pride's legacy, coordinated through local and diaspora organizers.",
    link: "https://www.shpride.com/",
    date: "",
    lat: 31.2304,
    lng: 121.4737,
  }),
  createEvent({
    id: "seed-event-havana-jornada-diversidad-2026",
    city: "havana",
    name: "Jornada Cubana contra la Homofobia y la Transfobia",
    description: "CENESEX-led national anti-homophobia and transphobia program cycle with education, visibility actions, and public queer community events in Havana.",
    link: "https://www.cenesex.org/construccion/",
    date: "2026-05-17",
    lat: 23.1308,
    lng: -82.3914,
  }),
  createEvent({
    id: "seed-event-havana-conga-diversidad-2026",
    city: "havana",
    name: "Havana Conga por la Diversidad",
    description: "Public street visibility action linked to Havana's annual anti-homophobia program window, blending activism, culture, and community turnout.",
    link: "https://www.cenesex.org/construccion/",
    date: "",
    lat: 23.1363,
    lng: -82.3589,
  }),
  createEvent({
    id: "seed-event-beijing-bjqff-2026",
    city: "beijing",
    name: "Beijing Queer Film Festival",
    description: "Long-running queer film and culture platform in Beijing, presenting screenings, talks, and community-led cinema programming.",
    link: "https://www.bjqff.com/",
    date: "",
    lat: 39.9042,
    lng: 116.4074,
  }),
  createEvent({
    id: "seed-event-beijing-destination-electro-2026",
    city: "beijing",
    name: "Destination Electro Party",
    description: "High-energy electronic party format at Destination Beijing, part of the venue's recurring weekend program cycle.",
    link: "https://www.bjdestination.com.cn/",
    date: "2026-04-11",
    lat: 39.9338,
    lng: 116.4473,
  }),
  createEvent({
    id: "seed-event-beijing-destination-boy-party-2026",
    city: "beijing",
    name: "Destination Boy Party",
    description: "Recurring Saturday pressure-night format at Destination with dance-floor-first crowd momentum.",
    link: "https://www.bjdestination.com.cn/",
    date: "2026-04-12",
    lat: 39.9338,
    lng: 116.4473,
  }),
  createEvent({
    id: "seed-event-newdelhi-pride-parade-2026",
    city: "new_delhi",
    name: "Delhi Queer Pride Parade 2026",
    description: "Annual Delhi Queer Pride march and public visibility action with rights-first community messaging and broad city participation.",
    link: "https://indianexpress.com/article/cities/delhi/delhi-hosts-18th-queer-pride-parade-9822936/",
    date: "2026-02-08",
    lat: 28.6358,
    lng: 77.2245,
  }),
  createEvent({
    id: "seed-event-newdelhi-kittysu-pride-series-2026",
    city: "new_delhi",
    name: "Kitty Su Pride Month Series Delhi",
    description: "Pride-season drag and performance programming at Kitty Su Pop Up Delhi, typically spanning multiple nights across June.",
    link: "https://www.kittysu.com/location/delhi",
    date: "",
    lat: 28.6283,
    lng: 77.2284,
  }),
  createEvent({
    id: "seed-event-newdelhi-naz-pride-dialogues-2026",
    city: "new_delhi",
    name: "Naz Pride Dialogues Delhi",
    description: "Community-facing rights and wellbeing dialogue format led by Naz Foundation around Pride-season advocacy and support themes.",
    link: "https://www.nazindia.org/lgbtqia/",
    date: "",
    lat: 28.5533,
    lng: 77.2489,
  }),
  createEvent({
    id: "seed-event-malaga-pride-community-2026",
    city: "malaga",
    name: "Malaga Pride Community March",
    description: "Annual city Pride visibility march format in Malaga with community programming, public talks, and after-dark social continuation.",
    link: "https://www.instagram.com/pridemalaga/",
    date: "",
    lat: 36.7219,
    lng: -4.4213,
  }),
  createEvent({
    id: "seed-event-naples-pride-2026",
    city: "naples",
    name: "Napoli Pride 2026",
    description: "Naples flagship Pride calendar with public march, rights programming, Pride Park culture schedule, and citywide queer nightlife momentum.",
    link: "https://napolipride.org/",
    date: "2026-06-27",
    lat: 40.8389,
    lng: 14.2545,
  }),
  createEvent({
    id: "seed-event-naples-menxtreme-2026",
    city: "naples",
    name: "MenXtreme Party Series",
    description: "Recurring men-only dresscode party in Naples, mapped as a high-intensity nightlife option with fetish-coded dance-floor energy.",
    link: "https://www.instagram.com/menxtremenapoli/",
    date: "",
    lat: 40.853,
    lng: 14.286,
  }),
  createEvent({
    id: "seed-event-santorini-summer-queer-nights-2026",
    city: "santorini",
    name: "Santorini Summer Queer Nights",
    description: "Seasonal queer-friendly nightlife wave across Fira bars and clubs, strongest during high-summer weekends and sunset-to-late circuits.",
    link: "https://www.instagram.com/kooclub_official/",
    date: "",
    lat: 36.4198,
    lng: 25.4315,
  }),
  createEvent({
    id: "seed-event-tenerife-arn-pride-2026",
    city: "tenerife",
    name: "ARN Culture & Business Pride Tenerife",
    description: "Tenerife Pride framework combining culture, business networking, visibility programming, and nightlife-linked community events.",
    link: "https://www.arnculturebusinesspride.com/",
    date: "",
    lat: 28.4636,
    lng: -16.2518,
  }),
  createEvent({
    id: "seed-event-kyoto-rainbow-pride-2026",
    city: "kyoto",
    name: "Kyoto Rainbow Pride 2026",
    description: "Community-led Pride day in Kyoto with parade visibility, stage programming, and local organization booths centered in Umekoji Park.",
    link: "https://kyotorainbowpride.studio.site/",
    date: "2026-04-18",
    lat: 34.9876,
    lng: 135.7487,
  }),
  createEvent({
    id: "seed-event-kyoto-pride-in-kyoto-2026",
    city: "kyoto",
    name: "Pride in Kyoto",
    description: "Independent Kyoto queer culture event series with talks, performances, and community organizing format across mixed venues.",
    link: "https://prideinkyoto.com/",
    date: "",
    lat: 35.0116,
    lng: 135.7681,
  }),
  createEvent({
    id: "seed-event-kyoto-diamond-night-metro",
    city: "kyoto",
    name: "Diamond Night @ CLUB METRO",
    description: "Recurring LGBTQ-oriented club night in Kyoto with drag-adjacent performances and mixed dance-floor momentum in the Metro circuit.",
    link: "http://www.metro.ne.jp/",
    date: "",
    lat: 35.0139,
    lng: 135.7725,
  }),
  createEvent({
    id: "seed-event-cancun-pride-march-2026",
    city: "cancun",
    name: "Cancun Pride March 2026",
    description: "Annual Cancun Pride march and city-center visibility action with civic backing and linked nightlife activations.",
    link: "https://quintanaroo.quadratin.com.mx/alistan-marcha-cancun-pride-2025/",
    date: "2026-06-06",
    lat: 21.1587,
    lng: -86.8288,
  }),
  createEvent({
    id: "seed-event-cancun-vive-con-orgullo",
    city: "cancun",
    name: "Festival Vive con Orgullo Cancun",
    description: "Pride-week cultural format in Cancun with community art, public programming, and visibility activities around downtown and beach corridors.",
    link: "https://quintanaroo.quadratin.com.mx/alistan-marcha-cancun-pride-2025/",
    date: "",
    lat: 21.1619,
    lng: -86.8515,
  }),
  createEvent({
    id: "seed-event-cancun-pride-weekend-club-series",
    city: "cancun",
    name: "Cancun Pride Weekend Club Series",
    description: "Cluster of drag and dance nights across Cancun LGBTQ+ clubs during Pride window, strongest in downtown venues and late-night circuits.",
    link: "https://www.facebook.com/1111club/",
    date: "",
    lat: 21.1615,
    lng: -86.8261,
  }),
  createEvent({
    id: "seed-event-nice-pink-parade-2026",
    city: "nice",
    name: "Pink Parade Nice 2026",
    description: "Nice's annual Pride march and seaside celebration format run by local LGBTQ+ organizers with parade route and Pink Drink after-program.",
    link: "https://www.facebook.com/AglaeLGBT",
    date: "2026-07-11",
    lat: 43.6961,
    lng: 7.2858,
  }),
];

export function mergeSeedEvents(databaseEvents = []) {
  const baseSeedEvents = seedEvents.filter(
    (event) =>
      !MODULAR_CITY_SLUGS.has(String(event.city || "")) &&
      !BOLOGNA_CITY_SLUGS.has(String(event.city || "")) &&
      !CRETE_CITY_SLUGS.has(String(event.city || "")) &&
      !CYPRUS_CITY_SLUGS.has(String(event.city || "")) &&
      !CHIANG_MAI_CITY_SLUGS.has(String(event.city || "")) &&
      !KOH_SAMUI_CITY_SLUGS.has(String(event.city || "")) &&
      !LJUBLJANA_CITY_SLUGS.has(String(event.city || "")) &&
      !MARSEILLE_CITY_SLUGS.has(String(event.city || "")),
  );
  const effectiveSeedEvents = [
    ...baseSeedEvents,
    ...modularSeedEvents,
    ...creteSeedEvents,
    ...cyprusSeedEvents,
    ...chiangMaiSeedEvents,
    ...kohSamuiSeedEvents,
    ...ljubljanaSeedEvents,
    ...marseilleSeedEvents,
    ...bolognaSeedEvents,
  ];
  const seenIds = new Set(databaseEvents.map((event) => String(event.id)));
  const seenEventKeys = new Set(
    databaseEvents.map((event) =>
      `${normalizeSeedKey(event.city)}::${normalizeSeedKey(event.name)}`,
    ),
  );
  const uniqueSeedEvents = [];

  effectiveSeedEvents.forEach((event) => {
    const id = String(event.id);
    const eventKey = `${normalizeSeedKey(event.city)}::${normalizeSeedKey(event.name)}`;
    if (seenIds.has(id) || seenEventKeys.has(eventKey)) return;

    seenIds.add(id);
    seenEventKeys.add(eventKey);
    uniqueSeedEvents.push(event);
  });

  return [
    ...databaseEvents,
    ...uniqueSeedEvents,
  ];
}
