-- Queer Atlas: Ulaanbaatar, Mongolia city package. Verified 2026-09-14; idempotent.
begin;

with raw(data) as (values
 ('{"name":"C.U.M Gay Bar","type":"bar","description":"A compact gay bar wrapped in queer art, house music and the kind of apple margarita that has become local shorthand. C.U.M is intimate rather than glossy: easy conversation early, dancing later and a Wednesday drag pulse that gives Mongolia’s young scene a visible room of its own.","vibe":"queer-art dive bar with strong drinks and a small dance floor","hours":"Daily approximately 19:00-02:00; Wednesday drag is commonly advertised from 21:00. Verify the current social post.","link":"https://www.instagram.com/cum.ulaanbaatar/","location":"Tourist Street, Chingeltei District, 3rd Khoroo, Ulaanbaatar 15172, Mongolia","lat":47.9186,"lng":106.9071,"q":"The room is small enough that Wednesday drag and weekend arrivals can turn into a capacity wait after 22:00. Earlier hours are easier for a first drink and introductions.","best":"Wednesday is the signature drag night; Friday and Saturday bring the liveliest dance-floor rhythm. An ordinary early weekday is more conversational.","crowd":"Gay and bisexual Mongolian men are prominent, joined by trans and queer regulars, local friends and international visitors.","dress":"Relaxed nightlife clothes and expressive looks both fit. Bring identification and never photograph another guest without consent.","staff":"C.U.M explicitly operates as a gay bar and recent visitors consistently describe socially engaged staff; no detailed public accessibility policy was located.","sources":["https://www.instagram.com/cum.ulaanbaatar/","https://wanderlog.com/place/details/12294534/cum-gay-bar"]}'::jsonb),
 ('{"name":"Cortez","type":"bar","description":"A women-owned bar and café with a lesbian-centred reputation, playful neon-dark interiors and a crowd broader than any single label. Cocktails, guest singers and occasional drag make Cortez feel like a social salon that can suddenly tilt into a four-in-the-morning dance night.","vibe":"women-owned cocktail hideaway with lesbian roots and late-night glow","hours":"Reported daily 18:00-04:00; Friday singers and drag dates vary. Confirm directly before travel.","link":"https://www.instagram.com/cortez.bar/","location":"1-40 Myangat, 1st Khoroo, Sukhbaatar District, Ulaanbaatar 14220, Mongolia","lat":47.9127,"lng":106.9202,"q":"Cortez fills through table and bar density rather than a formal club line. Friday singer dates and drag programmes can make the intimate room tight after 22:00.","best":"Friday is associated with live singers, while individual drag dates draw the clearest queer crowd. Earlier evenings preserve the cocktail-bar character.","crowd":"Lesbian and queer women form the venue’s cultural centre, with queer men, mixed friend groups and cocktail regulars also present.","dress":"Creative casual and polished bar looks both work under the neon. No verified formal door code is published.","staff":"The business is listed as women-owned and current local community reports identify it as lesbian-centred with drag programming; no written safeguarding policy was found.","sources":["https://www.instagram.com/cortez.bar/","https://www.top-rated.online/cities/Ulaanbaatar/place/p/9539423/Cortez"]}'::jsonb),
 ('{"name":"DIEX Club / Black w60","type":"club","description":"Ulaanbaatar’s larger queer dance floor, known interchangeably as DIEX and Black w60, runs on pop, house and drag spectacle. Friday and Saturday are the headline nights: local queens, a crowd ready to meet rather than hide in corners, and enough room for the city’s scene to feel much bigger than its map suggests.","vibe":"big-room gay club energy with weekend drag at its centre","hours":"Friday-Saturday approximately 21:30-03:30; other nights may be closed or event-only. Check the current programme.","link":"https://www.facebook.com/blackw60/","location":"6th Khoroo, Bayanzurkh District, Ulaanbaatar 13373, Mongolia","lat":47.9182,"lng":106.9381,"q":"Weekend drag concentrates arrivals from about 22:00; ID, security and the building entrance can slow first-time visitors.","best":"Friday and Saturday are the verified drag-and-dance peak. Check the current Black w60 or DIEX post because weekday opening is inconsistent.","crowd":"Gay men, trans guests, drag audiences, younger Mongolian regulars and respectful allies create one of the city’s broadest queer crowds.","dress":"Club-casual, pop-night glamour and drag-ready looks all appear. Carry identification and confirm any theme-night rule.","staff":"DIEX is a dedicated gay club with recurring local drag and community-event partnerships. Public sources support trans visibility, but no formal accessibility protocol is published.","sources":["https://www.facebook.com/blackw60/","https://may17.org/event/2025-idahobit-party-mongolia/","https://nomadicboys.com/gay-life-in-mongolia/"]}'::jsonb),
 ('{"name":"Melody Karaoke (Hanzo)","type":"bar","description":"The latest chapter of Hanzo, Mongolia’s shape-shifting gay-bar institution, trades a fixed brand mythology for karaoke, drag and a discreet door near the railway station. Come for the history carried by owner Zorig and for a night where singing badly can be the fastest route into the room.","vibe":"wandering queer karaoke institution near the railway tracks","hours":"Reported daily 15:00-00:00; queer karaoke, drag and after-party hours are programme-dependent. Contact before visiting.","link":"https://www.facebook.com/hanzo.mongolia/","location":"WV6R+H7V, Teeverchid Street, 3rd Khoroo, Bayangol District, Ulaanbaatar 16051, Mongolia","lat":47.9115,"lng":106.8910,"q":"The discreet railway-area entrance is the main first-visit friction rather than a long queue. Message or call ahead so a doorway change does not become a late-night search.","best":"Choose a specifically announced karaoke, drag or Pride after-party night. Ordinary afternoon business hours do not guarantee a queer programme.","crowd":"Long-time gay regulars, karaoke groups, drag performers and friends of owner Zorig connect the room to several generations of queer nightlife.","dress":"Everyday karaoke clothing works; winter footwear and a direct return ride matter more than fashion rules.","staff":"Owner Zorig has operated successive gay-bar identities and co-organised Equality Walk activity for years. The changing name and location make direct confirmation essential.","sources":["https://nomadicboys.com/the-only-gay-bar-in-mongolia-story/","https://www.bizkontakte.com/MN/melody-karaoke-8810-4855"]}'::jsonb),
 ('{"name":"Shangri-La Ulaanbaatar","type":"hotel","description":"A 290-room five-star anchor with a serious sports club, pool, spa and several polished dining rooms. Its central Olympic Street position makes it a controlled landing pad for couples who want international service, walkable landmarks and a calm reset between UB’s more improvised nights.","vibe":"full-scale city sanctuary beside the square and cultural core","hours":"Hotel open daily; check-in 14:00 and check-out 12:00 according to the hotel.","link":"https://www.shangri-la.com/ulaanbaatar/shangrila/","location":"19 Olympic Street, 1st Khoroo, Sukhbaatar District, Ulaanbaatar 14241, Mongolia","lat":47.9131,"lng":106.9225,"q":"Express check-in is available, but airport transfers and rooms should be arranged in advance because traffic is unpredictable.","best":"Use the property as a central recovery base or for an early Naadam Bar drink before a verified queer event.","crowd":"International executives, diplomatic and conference visitors, affluent local diners, families and leisure travellers.","dress":"Smart casual fits the lobby bars and restaurants; sports club, pool and spa areas have separate attire.","staff":"The hotel publishes extensive guest services but no Ulaanbaatar-specific LGBTQ+ training. Confirm names, room setup and companion access directly.","sources":["https://www.shangri-la.com/ulaanbaatar/shangrila/about/"]}'::jsonb),
 ('{"name":"Holiday Inn Ulaanbaatar","type":"hotel","description":"A practical international base with mountain-view rooms, a sports bar and useful accessibility detail published before arrival. It lacks boutique theatre, but that is part of the appeal: predictable check-in, staffed reception and an easy route to central sights without inventing a queer-hotel identity.","vibe":"straightforward international comfort west of the central square","hours":"Hotel open daily; check-in 14:00 and check-out 12:00; minimum check-in age 18.","link":"https://www.ihg.com/holidayinn/hotels/us/en/ulaanbaatar/ulnss/hoteldetail","location":"24 Sambuu Street, 5th Khoroo, Chingeltei District, Ulaanbaatar 15141, Mongolia","lat":47.9212,"lng":106.8974,"q":"The published 14:00 check-in and 12:00 checkout create the main reception peaks. Confirm early arrival and airport transport.","best":"Choose it for reliable logistics and the Titem Sports Bar rather than a dedicated queer social programme.","crowd":"Business travellers, tour guests, conference groups and independent international visitors.","dress":"Everyday travel clothing is normal, with casual attire in the sports bar and conventional gym or spa wear.","staff":"IHG publishes concrete ramp, parking and restaurant-access details. No local LGBTQ+ training claim is public, so privacy requests should be confirmed.","sources":["https://www.ihg.com/holidayinn/hotels/us/en/ulaanbaatar/ulnss/hoteldetail/directions"]}'::jsonb),
 ('{"name":"Kempinski Hotel Khan Palace","type":"hotel","description":"A long-established international hotel where oversized rooms, Japanese dining and a quieter East Cross Road setting create breathing space from the capital’s traffic. It suits travellers who value formal service and privacy over being directly above the weekend scene.","vibe":"quiet European-style service at the eastern edge of the centre","hours":"Hotel open daily; check-in 14:00 and check-out 12:00. Confirm early or late arrangements directly.","link":"https://www.kempinski.com/en/hotel-khan-palace","location":"Ikh Toiruu 178, East Cross Road, Bayanzurkh District, Ulaanbaatar 13345, Mongolia","lat":47.9180,"lng":106.9467,"q":"Check-in begins at 14:00 and checkout is at noon. A late arrival should be confirmed directly.","best":"The quieter eastern location suits recovery, formal dining and business-heavy stays; travel to queer bars for a named event.","crowd":"International business guests, organised tours, diplomatic travellers and local diners favour a formal environment.","dress":"Polished casual clothing fits public areas and restaurants; there is no unusual hotel-wide fashion requirement.","staff":"Kempinski supplies a direct concierge, but no property-specific LGBTQ+ protocol was found. Confirm privacy, names and visitor access in writing.","sources":["https://www.kempinski.com/en/hotel-khan-palace","https://www.kempinski.com/en/hotel-khan-palace/imprint"]}'::jsonb)
), rows as (select data, jsonb_build_object('queue_wait',data->>'q','best_nights',data->>'best','crowd_mix',data->>'crowd','dress_code',data->>'dress','staff_inclusivity',data->>'staff','source_urls',data->'sources','research_status','current_operator_and_editorial_sources','updated_at','2026-09-14T00:00:00Z') intel from raw), upd as (
 update public.places p set type=r.data->>'type',description=r.data->>'description',vibe=r.data->>'vibe',hours=r.data->>'hours',link=r.data->>'link',location=r.data->>'location',lat=(r.data->>'lat')::numeric,lng=(r.data->>'lng')::numeric,venue_intel=r.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from rows r where lower(trim(p.city))='ulaanbaatar' and lower(trim(p.name))=lower(r.data->>'name') returning p.id)
insert into public.places(name,city,type,description,vibe,hours,link,location,lat,lng,venue_intel,seo_indexable,seo_quality_status)
select data->>'name','ulaanbaatar',data->>'type',data->>'description',data->>'vibe',data->>'hours',data->>'link',data->>'location',(data->>'lat')::numeric,(data->>'lng')::numeric,intel,true,'approved' from rows r where not exists(select 1 from public.places p where lower(trim(p.city))='ulaanbaatar' and lower(trim(p.name))=lower(r.data->>'name'));

with s(name,type,provider_name,contact,booking_link,description,hours,link,location,vibe,tags,source) as (values
 ('LGBT Centre Mongolia','other','LGBT Centre Mongolia','info@lgbtcentre.mn · +976 7011 0323','https://www.lgbtcentre.mn/en/home/','Mongolia’s principal LGBTQI+ rights organisation runs youth, health, legal and cultural programmes and preserves the movement’s history. Contact first; do not rely on an old office address.','Programme and appointment-led; contact before visiting.','https://www.lgbtcentre.mn/en/home/','Contact-led service, Ulaanbaatar, Mongolia','national LGBTQI+ rights, youth, health and archive hub',array['service','social','cultural']::text[],'LGBT Centre Mongolia official website'),
 ('Trans for Unity','other','Trans for Unity Mongolia','Use the current official social channel.','https://www.instagram.com/trans4unity/','A trans-led community organisation active in rights work, Pride collaboration and a small community café programme. Confirm the current café location privately before visiting.','Programme-led; confirm the current café and event hours.','https://www.instagram.com/trans4unity/','Contact-led service, Ulaanbaatar, Mongolia','trans-led organising and community connection',array['service','social','cultural']::text[],'Trans for Unity official social channel'),
 ('Youth for Health Centre','other','Youth for Health Centre Mongolia','Contact through current programme channels.','https://www.facebook.com/yfhmongolia/','A community health organisation serving gay and bisexual men and transgender women through HIV and STI prevention, education, outreach and referral work.','Appointment and outreach-led; verify current testing access.','https://www.facebook.com/yfhmongolia/','Contact-led health service, Ulaanbaatar, Mongolia','community-led sexual health, prevention and referral',array['service','relax']::text[],'APCOM and current Mongolia HIV-sector sources')
), upd as (update public.services x set type=s.type,provider_name=s.provider_name,contact=s.contact,booking_link=s.booking_link,description=s.description,hours=s.hours,link=s.link,location=s.location,vibe=s.vibe,vibe_tags=s.tags,source=s.source,"lastChecked"='2026-09-14'::date,verified=true from s where lower(trim(x.city))='ulaanbaatar' and lower(trim(x.name))=lower(trim(s.name)) returning x.id)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified)
select name,'ulaanbaatar',type,provider_name,contact,booking_link,description,hours,link,array[]::text[],location,47.9189,106.9057,'$',vibe,tags,source,'2026-09-14'::date,true from s where not exists(select 1 from public.services x where lower(trim(x.city))='ulaanbaatar' and lower(trim(x.name))=lower(trim(s.name)));

insert into public.qa_country_rights_profiles(country,legal_level,rights_level,safety_level,same_sex_relations_status,union_status,legal_gender_recognition_status,anti_discrimination_status,what_this_means,confidence,source_legal_url,source_rights_url,source_safety_url,source_checked_at,needs_manual_review) values
('Mongolia','good','mixed','risk','legal','no_protection','restricted','partial_coverage','Same-sex relations are legal and parts of criminal and labour law protect sexual orientation and gender identity. Relationship recognition is absent, legal gender change requires surgery, and documented discrimination plus weak enforcement make discretion important beyond trusted venues.','high','https://www.equaldex.com/region/mongolia','https://outrightinternational.org/our-work/asia/mongolia','https://www.theadvocatesforhumanrights.org/International_Submissions/A/Index?id=536','2026-09-14'::date,false)
on conflict(country) do update set legal_level=excluded.legal_level,rights_level=excluded.rights_level,safety_level=excluded.safety_level,same_sex_relations_status=excluded.same_sex_relations_status,union_status=excluded.union_status,legal_gender_recognition_status=excluded.legal_gender_recognition_status,anti_discrimination_status=excluded.anti_discrimination_status,what_this_means=excluded.what_this_means,confidence=excluded.confidence,source_legal_url=excluded.source_legal_url,source_rights_url=excluded.source_rights_url,source_safety_url=excluded.source_safety_url,source_checked_at=excluded.source_checked_at,needs_manual_review=excluded.needs_manual_review;

insert into public.qa_qari_profiles(destination_key,scope_type,country,city_key,legal_risk,social_risk,digital_risk,risk_floor,confidence,summary,methodology_version,reviewed_by,reviewed_at,is_published) values
('country:mongolia','country','Mongolia',null,45,82,38,0,'high','Same-sex relations are legal and targeted criminal and employment protections exist, but no couple recognition, surgery-based gender recognition, low public acceptance and inconsistent enforcement keep practical risk elevated.','1.0','Queer Atlas editorial review','2026-09-14'::date,true)
on conflict(destination_key) do update set legal_risk=excluded.legal_risk,social_risk=excluded.social_risk,digital_risk=excluded.digital_risk,risk_floor=excluded.risk_floor,confidence=excluded.confidence,summary=excluded.summary,methodology_version=excluded.methodology_version,reviewed_by=excluded.reviewed_by,reviewed_at=excluded.reviewed_at,is_published=excluded.is_published;

delete from public.qa_qari_sources where destination_key='country:mongolia';
insert into public.qa_qari_sources(destination_key,axis,source_type,label,url,supports_claim,published_at,checked_at) values
('country:mongolia','legal','legal_database','Equaldex · Mongolia','https://www.equaldex.com/region/mongolia','Documents legal same-sex relations, partial protections, banned marriage and surgery-based gender recognition.',null,'2026-09-14'::date),
('country:mongolia','social','legal_database','Equaldex · Mongolia public opinion','https://www.equaldex.com/region/mongolia','Reports 10% describing their area as a good place for gay and lesbian people in the 2024 Gallup measure.',null,'2026-09-14'::date),
('country:mongolia','social','ngo_report','Outright International · Mongolia','https://outrightinternational.org/our-work/asia/mongolia','Documents fragmented protection, inconsistent enforcement and discrimination.','2026-03-12'::date,'2026-09-14'::date),
('country:mongolia','digital','ngo_report','The Advocates for Human Rights · Mongolia','https://www.theadvocatesforhumanrights.org/International_Submissions/A/Index?id=536','Documents violence, institutional bias and fear of reporting crimes.','2025-02-03'::date,'2026-09-14'::date);

commit;

