-- Queer Atlas: North America hotel batch 1
-- Cancun, Chicago, Dallas, Denver, Fire Island, Las Vegas, New Orleans,
-- Orlando, Palm Springs, Philadelphia, San Diego, Seattle and Washington DC.
-- Three researched LGBTQ+-focused or LGBTQ+-welcoming hotels per destination.
-- Editorial and source check: 2026-08-23.
--
-- No ratings or review totals are manufactured. "LGBTQ+-welcoming" is used only
-- where a current specialist LGBTQ+ directory or the property itself supplies
-- that signal. Coordinates identify the individual hotel building, not a city
-- centroid. Safe to run more than once; city + hotel name is the natural key.

begin;

alter table if exists public.places
  add column if not exists venue_intel jsonb not null default '{}'::jsonb;

with raw_hotels as (
  select *
  from jsonb_to_recordset($hotels$
[
 {"name":"Presidente InterContinental Cancun Resort","city":"cancun","description":"A polished beachfront resort on the calmer northern stretch of Cancun's Hotel Zone. Its current Travel Gay Approved listing makes it a documented LGBTQ+-welcoming full-service option with beach, pools, spa and resort dining.","vibe":"welcoming beachfront luxury on a calm Caribbean bay","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; restaurants, spa, pools and beach services follow current resort schedules.","link":"https://presidenteiccancun.com/en/home/","location":"Boulevard Kukulcan Km 7.5, Zona Hotelera, 77500 Cancun, Quintana Roo, Mexico","lat":21.13545757,"lng":-86.75445776,"arrival":"Standard resort check-in; allow extra time on holiday weekends and reserve spa or dining separately.","best_for":"A quiet-water beach stay with Hotel Zone access rather than an adults-only party hotel.","audience":"LGBTQ+ travellers, couples, families and international resort guests in a broad mixed setting.","dress":"Resort casual by day; restaurants and spa areas apply their own practical rules.","inclusion":"The resort has a current Travel Gay Approved listing and publishes a Pride-oriented welcome page.","basis":"Current Travel Gay Approved listing plus the resort's own Pride welcome content.","hotel_class":"Luxury beachfront resort","coordinate_source":"Mapbox hotel POI checked against the official Km 7.5 address.","source_urls":["https://www.travelgay.com/gay-cancun-hotels","https://presidenteiccancun.com/hotel-presidente-intercontinental-cancun-resort/"]},
 {"name":"Occidental Costa Cancun","city":"cancun","description":"A four-star all-inclusive resort at the northern entrance to Cancun's Hotel Zone, with Caribbean frontage, pool, spa and several restaurants. Travel Gay currently identifies it as an Approved LGBTQ+-welcoming hotel.","vibe":"easygoing all-inclusive resort near the Hotel Zone entrance","tags_csv":"relax,mixed,social","hours":"Hotel reception operates 24 hours; restaurants, bars, spa and activities use the current resort timetable.","link":"https://www.barcelo.com/en-ww/occidental-costa-cancun/","location":"Boulevard Kukulcan Km 4.5, Zona Hotelera, 77500 Cancun, Quintana Roo, Mexico","lat":21.14507,"lng":-86.78895,"arrival":"Package and group arrivals can briefly slow reception; confirm transfers and room access before travel.","best_for":"An all-inclusive beach base with daytime facilities and easy access toward downtown Cancun.","audience":"A broad international resort crowd including couples, families, groups and LGBTQ+ guests.","dress":"Resort wear is suitable by day; à-la-carte dining may request smart-casual clothing.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and a welcoming service standard.","basis":"Current Travel Gay Approved listing paired with the official Barceló property record.","hotel_class":"4-star all-inclusive resort","coordinate_source":"Hotel building coordinate cross-checked with OpenStreetMap and the official Km 4.5 address.","source_urls":["https://www.travelgay.com/gay-cancun-hotels","https://www.barcelo.com/en-ww/occidental-costa-cancun/"]},
 {"name":"Paradisus Cancun","city":"cancun","description":"A five-star all-inclusive resort distinguished by its pyramid architecture, long beach frontage, spa and multiple dining concepts. Its current Travel Gay Approved listing supplies the LGBTQ+-welcoming evidence for this entry.","vibe":"high-service Caribbean resort with landmark pyramid architecture","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; restaurants, pools, spa and experiences follow live resort schedules.","link":"https://www.melia.com/en/hotels/mexico/cancun/paradisus-cancun","location":"Boulevard Kukulcan Km 16.5, Zona Hotelera, 77500 Cancun, Quintana Roo, Mexico","lat":21.08371813,"lng":-86.7721755,"arrival":"Large-resort check-in can peak around transfer arrivals; premium services and restaurants may need advance booking.","best_for":"Travellers wanting a self-contained luxury resort with beach, wellness and dining in one property.","audience":"International couples, families, groups and LGBTQ+ guests across a mixed resort audience.","dress":"Resort casual works broadly; selected restaurants and experiences can set venue-specific guidance.","inclusion":"The current Travel Gay Approved record documents LGBTQ+ acceptance without presenting the resort as queer-exclusive.","basis":"Current Travel Gay Approved listing plus official Meliá property information.","hotel_class":"5-star all-inclusive resort","coordinate_source":"Mapbox hotel POI checked against the official Km 16.5 address.","source_urls":["https://www.travelgay.com/gay-cancun-hotels","https://www.melia.com/en/hotels/mexico/cancun/paradisus-cancun"]},

 {"name":"Best Western Plus Hawthorne Terrace Hotel","city":"chicago","description":"A boutique-scale hotel on North Broadway in Lakeview, a short walk from Northalsted and Center on Halsted. The official hotel page highlights its proximity to Chicago Pride activity, while Travel Gay lists it for LGBTQ+ travellers.","vibe":"neighbourhood boutique base beside Chicago's main queer district","tags_csv":"social,cozy,mixed","hours":"Hotel reception operates 24 hours; breakfast, fitness and sauna access follow current hotel schedules.","link":"https://www.bestwestern.com/en_US/book/chicago/hotel-rooms/best-western-plus-hawthorne-terrace-hotel/propertyCode.14151.html","location":"3434 N Broadway, Chicago, IL 60657, United States","lat":41.94415,"lng":-87.645901,"arrival":"A compact neighbourhood lobby; Pride and Cubs weekends reward early booking and advance parking plans.","best_for":"Walking access to Northalsted bars, community institutions and Lake Michigan.","audience":"Queer visitors, couples, families and general Lakeview travellers in a mixed hotel environment.","dress":"No hotel dress code; nearby nightlife venues set their own entry rules.","inclusion":"The hotel officially references Pride Fest and Center on Halsted, reinforced by its specialist LGBTQ+ travel listing.","basis":"Official neighbourhood/Pride information plus current Travel Gay listing.","hotel_class":"Boutique neighbourhood hotel","coordinate_source":"Mapbox exact-address building result checked against the official property page.","source_urls":["https://www.travelgay.com/gay-chicago-hotels","https://www.bestwestern.com/en_US/book/chicago/hotel-rooms/best-western-plus-hawthorne-terrace-hotel/propertyCode.14151.html"]},
 {"name":"Hotel Lincoln","city":"chicago","description":"A characterful Lincoln Park hotel opposite the park and close to Old Town, with rooftop and lake access. Travel Gay's current Chicago guide identifies it as a gay-friendly choice with practical access to Northalsted.","vibe":"playful park-side boutique stay with rooftop city energy","tags_csv":"social,cultural,mixed","hours":"Hotel reception operates 24 hours; rooftop and dining hours vary and should be checked directly.","link":"https://www.jdvhotels.com/hotels/illinois/chicago/hotel-lincoln","location":"1816 N Clark Street, Chicago, IL 60614, United States","lat":41.915346,"lng":-87.634498,"arrival":"Rooftop demand and Lincoln Park events are separate from room check-in; reserve public spaces when important.","best_for":"A design-led stay near the lake, park and Old Town with a short trip to Northalsted.","audience":"Couples, solo travellers, weekend groups and LGBTQ+ guests in a broad boutique-hotel crowd.","dress":"Relaxed city clothing works; rooftop programming may lean smart-casual.","inclusion":"Current specialist LGBTQ+ travel coverage presents the hotel as a welcoming Chicago option.","basis":"Current Travel Gay Chicago hotel listing plus official hotel information.","hotel_class":"Boutique JDV by Hyatt hotel","coordinate_source":"Mapbox exact-address building result checked against the official address.","source_urls":["https://www.travelgay.com/gay-chicago-hotels","https://www.jdvhotels.com/hotels/illinois/chicago/hotel-lincoln"]},
 {"name":"The Hotel at Midtown","city":"chicago","description":"A contemporary hotel integrated into Midtown Athletic Club, combining rooms with extensive fitness, pool, spa and social facilities. Travel Gay currently lists it as an LGBTQ+-welcoming Chicago stay.","vibe":"wellness-led urban club stay with serious fitness facilities","tags_csv":"luxury,relax,social","hours":"Hotel reception operates 24 hours; club, pool, spa and class schedules are managed separately.","link":"https://www.midtown.com/hotel","location":"2444 N Elston Avenue, Chicago, IL 60647, United States","lat":41.926114,"lng":-87.679691,"arrival":"Hotel arrival is straightforward, but classes, spa treatments and club amenities may require reservations.","best_for":"Travellers who want a full athletic club and wellness programme more than immediate nightlife frontage.","audience":"Fitness travellers, couples, business guests and LGBTQ+ visitors in a mixed membership-club setting.","dress":"Everyday hotel wear; athletic, pool and spa spaces have activity-specific attire rules.","inclusion":"Travel Gay's current listing supplies the LGBTQ+-welcoming travel signal; the property serves a broad audience.","basis":"Current Travel Gay Chicago hotel listing plus the official Midtown property record.","hotel_class":"Luxury fitness-club hotel","coordinate_source":"Mapbox exact-address building result checked against the official address.","source_urls":["https://www.travelgay.com/gay-chicago-hotels","https://www.midtown.com/hotel"]},

 {"name":"Warwick Melrose Dallas","city":"dallas","description":"A historic luxury hotel on Oak Lawn Avenue, placing guests directly in Dallas's best-known LGBTQ+ district. Its current Travel Gay listing and neighbourhood position make it the strongest scene-access choice in this Dallas batch.","vibe":"historic Oak Lawn elegance beside Dallas's queer nightlife","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; dining, lounge and valet schedules should be checked directly.","link":"https://www.warwickhotels.com/warwick-melrose-dallas","location":"3015 Oak Lawn Avenue, Dallas, TX 75219, United States","lat":32.80895,"lng":-96.809425,"arrival":"Valet and event traffic can peak on weekends; Pride and large city dates require early room planning.","best_for":"Walking or short-ride access to Oak Lawn bars, restaurants and community life.","audience":"Queer visitors, couples, business travellers and luxury guests in a broad adult hotel crowd.","dress":"No hotel-wide code; smart-casual suits the bar and dining room.","inclusion":"Current Travel Gay coverage pairs a welcoming hotel signal with a verifiable Oak Lawn location.","basis":"Current Travel Gay Dallas hotel listing plus official hotel address and services.","hotel_class":"Historic luxury hotel","coordinate_source":"Mapbox exact-address result checked against Warwick's official location page.","source_urls":["https://www.travelgay.com/gay-dallas-hotels","https://www.warwickhotels.com/warwick-melrose-dallas/contact-and-location"]},
 {"name":"The Highland Dallas","city":"dallas","description":"An upscale Curio Collection hotel opposite the Mockingbird Station area, with spa, pool and destination dining. Travel Gay currently includes it among Dallas's LGBTQ+-welcoming hotel choices.","vibe":"polished modern luxury with spa and city access","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; spa, pool and restaurant access follow current schedules.","link":"https://www.thehighlanddallas.com/","location":"5300 E Mockingbird Lane, Dallas, TX 75206, United States","lat":32.836267,"lng":-96.777765,"arrival":"Book spa and dining separately from the room; event weekends can tighten valet and lobby capacity.","best_for":"A high-service stay near SMU and rail connections, with Oak Lawn reached by a short ride.","audience":"Couples, business travellers, spa guests and LGBTQ+ visitors in a mixed upscale setting.","dress":"Smart-casual is useful for dining; pool and spa have practical attire rules.","inclusion":"The current Travel Gay Dallas guide identifies the hotel as a welcoming option for LGBTQ+ guests.","basis":"Current specialist LGBTQ+ travel listing plus official property information.","hotel_class":"Luxury Curio Collection hotel","coordinate_source":"Mapbox exact-address result checked against the official hotel address.","source_urls":["https://www.travelgay.com/gay-dallas-hotels","https://www.thehighlanddallas.com/"]},
 {"name":"Omni Dallas Hotel","city":"dallas","description":"A large downtown convention hotel connected to the Dallas convention centre, with rooftop pool, spa and multiple restaurants. Travel Gay's current Dallas guide lists it as an LGBTQ+-welcoming central option.","vibe":"high-service downtown landmark with rooftop and convention energy","tags_csv":"luxury,massive,mixed","hours":"Hotel reception operates 24 hours; restaurants, spa and rooftop pool follow live schedules.","link":"https://www.omnihotels.com/hotels/dallas","location":"555 S Lamar Street, Dallas, TX 75202, United States","lat":32.775335,"lng":-96.804029,"arrival":"Convention arrivals can create busy check-in waves; reserve spa and dining in advance during major events.","best_for":"Downtown sights, conferences and a full-service base with Oak Lawn reachable by ride or transit.","audience":"Convention groups, couples, families, business guests and LGBTQ+ visitors in a large mixed hotel.","dress":"No hotel-wide code; individual restaurants may be smart-casual.","inclusion":"Current LGBTQ+ specialist travel coverage documents the hotel as a welcoming Dallas selection.","basis":"Current Travel Gay Dallas hotel listing plus official Omni property information.","hotel_class":"Large downtown convention hotel","coordinate_source":"Mapbox exact-address result checked against Omni's official address.","source_urls":["https://www.travelgay.com/gay-dallas-hotels","https://www.omnihotels.com/hotels/dallas"]},

 {"name":"Kimpton Hotel Monaco Denver","city":"denver","description":"A design-forward downtown Kimpton near the 16th Street corridor, with restaurant and social lobby. Kimpton's long-running LGBTQ+ positioning and its current Travel Gay listing provide a stronger inclusion basis than location alone.","vibe":"colourful downtown boutique stay with established queer-friendly credentials","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; restaurant, social hour and fitness services use current schedules.","link":"https://www.monaco-denver.com/","location":"1717 Champa Street, Denver, CO 80202, United States","lat":39.747855,"lng":-104.992645,"arrival":"Normal boutique check-in; downtown events can pressure valet parking and restaurant availability.","best_for":"A central, personality-led hotel with straightforward access to downtown culture and queer nightlife.","audience":"LGBTQ+ couples, solo travellers, pet travellers and general boutique-hotel guests.","dress":"Expressive and casual city styles are appropriate; the restaurant is typically smart-casual.","inclusion":"Kimpton publicly markets gay-friendly stays and supports LGBTQ+ organisations, reinforced by current Travel Gay coverage.","basis":"Official Kimpton LGBTQ+ programme plus current Travel Gay Denver listing.","hotel_class":"Upscale boutique Kimpton hotel","coordinate_source":"Mapbox exact-address building result checked against the official hotel address.","source_urls":["https://www.travelgay.com/gay-denver-hotels","https://www.ihg.com/kimptonhotels/content/us/en/stay/gay-friendly-hotels"]},
 {"name":"Hyatt Place Denver Cherry Creek","city":"denver","description":"A renovated Hyatt Place at the Denver–Glendale boundary, close to Cherry Creek and Infinity Park, with spacious rooms and 24-hour dining. Travel Gay currently includes it as an LGBTQ+-welcoming Denver-area option.","vibe":"relaxed modern base for Cherry Creek and south-central Denver","tags_csv":"relax,mixed,social","hours":"Hotel reception and selected dining operate 24 hours; bar and fitness schedules should be checked directly.","link":"https://www.hyatt.com/hyatt-place/en-US/denzc-hyatt-place-denver-cherry-creek","location":"4150 E Mississippi Avenue, Glendale, CO 80246, United States","lat":39.69553,"lng":-104.93861,"arrival":"Straightforward hotel check-in with parking; share accessibility or late-arrival needs before travel.","best_for":"Cherry Creek, Infinity Park and car-based Denver trips rather than a downtown nightlife doorstep.","audience":"Couples, families, business travellers and LGBTQ+ guests in a broad mixed hotel.","dress":"No hotel dress code; everyday city and travel clothing works.","inclusion":"Travel Gay's current Denver guide supplies the LGBTQ+-welcoming signal; the official Hyatt page confirms the property sits in Glendale.","basis":"Current Travel Gay Denver listing plus official Hyatt information; municipal location stated transparently.","hotel_class":"Modern select-service hotel","coordinate_source":"Hotel-building coordinate checked against Hyatt's official 4150 E Mississippi address.","source_urls":["https://www.travelgay.com/gay-denver-hotels","https://www.hyatt.com/hyatt-place/en-US/denzc-hyatt-place-denver-cherry-creek"]},
 {"name":"Residence Inn Denver City Center","city":"denver","description":"An all-suite downtown hotel with kitchens and longer-stay practicality, close to the 16th Street corridor. Travel Gay currently lists it as an LGBTQ+-welcoming Denver hotel.","vibe":"central extended-stay comfort with practical city access","tags_csv":"relax,mixed,cozy","hours":"Hotel reception operates 24 hours; breakfast, fitness and housekeeping follow current Marriott schedules.","link":"https://www.marriott.com/en-us/hotels/denrd-residence-inn-denver-city-center/overview/","location":"1725 Champa Street, Denver, CO 80202, United States","lat":39.748233,"lng":-104.992169,"arrival":"Conventional check-in; longer stays should confirm housekeeping frequency and parking before arrival.","best_for":"Travellers wanting a kitchen, workspace and central location for multi-night Denver visits.","audience":"Solo travellers, couples, families, business guests and LGBTQ+ visitors in a mixed extended-stay setting.","dress":"No dress code; everyday city clothing is appropriate.","inclusion":"Current Travel Gay coverage identifies the property as an LGBTQ+-welcoming Denver selection.","basis":"Current Travel Gay Denver hotel listing plus official Marriott property information.","hotel_class":"All-suite extended-stay hotel","coordinate_source":"Mapbox exact-address result checked against Marriott's official address.","source_urls":["https://www.travelgay.com/gay-denver-hotels","https://www.marriott.com/en-us/hotels/denrd-residence-inn-denver-city-center/overview/"]},

 {"name":"The Madison Fire Island Pines","city":"fireisland","description":"A boutique guesthouse in Fire Island Pines with a pool-focused social setting and direct access to one of the world's best-known gay resort communities. Its current Travel Gay Approved listing and Pines location make the queer context explicit.","vibe":"intimate gay resort-community stay with poolside social energy","tags_csv":"social,relax,men_only","hours":"Seasonal guesthouse; confirm ferry-season dates, check-in procedure, pool rules and visitor policy directly.","link":"https://themadisonfi.com/","location":"22 Atlantic Walk, Fire Island Pines, NY 11782, United States","lat":40.664632,"lng":-73.069215,"arrival":"There are no cars in the Pines; coordinate ferry, luggage and the property's seasonal arrival instructions.","best_for":"Immersive Pines nightlife, beach and community access without a mainland commute.","audience":"Primarily gay men and queer adult travellers in the Pines; confirm the property's current guest policy directly.","dress":"Beach and resort casual; pool, shared spaces and individual events may set specific rules.","inclusion":"The guesthouse is located within Fire Island Pines' gay resort community and is currently Travel Gay Approved.","basis":"Current Travel Gay Approved listing plus the official property record.","hotel_class":"Seasonal boutique guesthouse","coordinate_source":"Mapbox Searchbox hotel/building result checked against 22 Atlantic Walk.","source_urls":["https://www.travelgay.com/gay-fire-island-hotels","https://themadisonfi.com/"]},
 {"name":"Dune Point Guest House","city":"fireisland","description":"A beach guesthouse directly in Cherry Grove, one of Fire Island's historic LGBTQ+ communities. Apartment-style options and an oceanfront setting make it useful for longer, self-contained queer-island stays.","vibe":"laid-back Cherry Grove beach living in a historic queer community","tags_csv":"relax,social,mixed","hours":"Seasonal accommodation; verify ferry-season opening, arrival window, minimum stay and guest policy before booking.","link":"https://www.dunepointfireisland.com/","location":"134 Lewis Walk, Cherry Grove, NY 11782, United States","lat":40.659175,"lng":-73.088157,"arrival":"Plan around the Cherry Grove ferry and pedestrian boardwalks; luggage handling requires more preparation than a city hotel.","best_for":"A beach-first Cherry Grove stay with local queer nightlife and community spaces on foot.","audience":"LGBTQ+ couples, friends and solo travellers alongside a welcoming mixed adult beach audience.","dress":"Beach casual; respect shared guesthouse areas and venue-specific night-time rules.","inclusion":"Cherry Grove is a historic LGBTQ+ destination and Dune Point is listed as its local lodging by Fire Island's destination guide.","basis":"Official Fire Island lodging record plus documented Cherry Grove LGBTQ+ context.","hotel_class":"Seasonal beach guesthouse and apartments","coordinate_source":"Mapbox Searchbox building result checked against the official 134 Lewis Walk address.","source_urls":["https://fireisland.com/stay/","https://www.dunepointfireisland.com/"]},
 {"name":"The Grove Hotel","city":"fireisland","description":"An adults-only Cherry Grove hotel whose own policy explicitly welcomes GLBTQ+ guests and people of all orientations, identities and genders. The Ocean Walk address places guests directly inside the island's queer cultural and nightlife core.","vibe":"adult queer-island stay at the centre of Cherry Grove","tags_csv":"social,mixed,relax","hours":"Seasonal 21+ accommodation; verify ferry dates, check-in, pool and visitor policies directly.","link":"https://www.grovehotel.com/","location":"1 Ocean Walk, Cherry Grove, NY 11782, United States","lat":40.65944219,"lng":-73.09000147,"arrival":"Arrive by Cherry Grove ferry and follow the hotel's pedestrian directions; late arrivals need advance coordination.","best_for":"Adults wanting immediate access to Cherry Grove's beach, bars, drag and community atmosphere.","audience":"A diverse 21+ LGBTQ+ and allied adult crowd; the hotel explicitly welcomes all orientations and gender identities.","dress":"Island and beach casual; nightlife events and shared pool areas may publish separate rules.","inclusion":"The hotel's own About page explicitly defines it as a GLBTQ+ destination and publishes a broad welcome policy.","basis":"First-party LGBTQ+ inclusion statement and official property address.","hotel_class":"Seasonal 21+ resort hotel","coordinate_source":"Hotel POI coordinate checked against the official 1 Ocean Walk address in Cherry Grove.","source_urls":["https://www.grovehotel.com/about-us/","https://www.grovehotel.com/"]},

 {"name":"New York-New York Hotel & Casino","city":"las_vegas","description":"A large Strip resort opposite T-Mobile Arena, combining casino, pool, entertainment and extensive dining. Travel Gay currently lists it among Las Vegas's LGBTQ+-welcoming hotels.","vibe":"high-energy Strip resort with entertainment at the door","tags_csv":"massive,social,mixed","hours":"Hotel and casino operate 24 hours; pool, attractions, shows and restaurants use separate schedules.","link":"https://www.mgmresorts.com/en/hotels/new-york-new-york.html","location":"3790 S Las Vegas Boulevard, Las Vegas, NV 89109, United States","lat":36.10226,"lng":-115.174358,"arrival":"Casino-resort check-in can queue on weekends and event dates; mobile check-in may reduce lobby time.","best_for":"First-time Strip access, arena events and a self-contained entertainment resort.","audience":"Large international mixed crowd including couples, groups, families and LGBTQ+ travellers.","dress":"Casino casual by day; clubs, restaurants and shows set their own requirements.","inclusion":"Current specialist LGBTQ+ travel coverage identifies the resort as a welcoming Las Vegas option.","basis":"Current Travel Gay Las Vegas hotel listing plus official MGM property information.","hotel_class":"Large Strip casino resort","coordinate_source":"Mapbox exact-address hotel result checked against MGM's official address.","source_urls":["https://www.travelgay.com/gay-las-vegas-hotels","https://www.mgmresorts.com/en/hotels/new-york-new-york.html"]},
 {"name":"MGM Grand","city":"las_vegas","description":"One of the Strip's largest casino resorts, with major shows, pools, restaurants and nightlife under one roof. Travel Gay currently includes MGM Grand in its LGBTQ+-welcoming Las Vegas hotel selection.","vibe":"maximalist Strip spectacle with nonstop resort energy","tags_csv":"massive,luxury,social","hours":"Hotel and casino operate 24 hours; pools, clubs, shows, spa and dining use ticketed or seasonal schedules.","link":"https://www.mgmresorts.com/en/hotels/mgm-grand-las-vegas.html","location":"3799 S Las Vegas Boulevard, Las Vegas, NV 89109, United States","lat":36.102121,"lng":-115.168934,"arrival":"Expect peak queues around weekend check-in and arena/show arrivals; use digital check-in when available.","best_for":"Travellers who want major entertainment, pool complexes and nightlife within one vast resort.","audience":"A very broad global resort crowd, including LGBTQ+ couples and groups.","dress":"Resort casual in public areas; clubs, fine dining and shows can enforce their own codes.","inclusion":"Travel Gay's current Las Vegas guide supplies the LGBTQ+-welcoming travel signal.","basis":"Current Travel Gay listing paired with official MGM resort information.","hotel_class":"Large luxury casino resort","coordinate_source":"Mapbox exact-address hotel result checked against MGM's official address.","source_urls":["https://www.travelgay.com/gay-las-vegas-hotels","https://www.mgmresorts.com/en/hotels/mgm-grand-las-vegas.html"]},
 {"name":"Flamingo Las Vegas","city":"las_vegas","description":"A classic centre-Strip casino hotel with tropical grounds, pools and direct LINQ-area access. Its current Travel Gay listing documents it as an LGBTQ+-welcoming choice in a highly walkable Strip position.","vibe":"classic neon Vegas with a playful tropical centre-Strip setting","tags_csv":"massive,social,mixed","hours":"Hotel and casino operate 24 hours; pools, restaurants and entertainment follow current schedules.","link":"https://www.caesars.com/flamingo-las-vegas","location":"3555 S Las Vegas Boulevard, Las Vegas, NV 89109, United States","lat":36.1163,"lng":-115.172227,"arrival":"Central location and large room inventory create busy arrival periods; digital check-in can help.","best_for":"A lively, central Strip stay with easy pedestrian access to multiple resorts.","audience":"Couples, groups, value seekers and LGBTQ+ travellers in a broad casino-resort crowd.","dress":"Casual resort wear is common; nightlife and restaurants can set separate rules.","inclusion":"Current LGBTQ+ specialist travel coverage includes Flamingo as a welcoming Las Vegas hotel.","basis":"Current Travel Gay Las Vegas listing plus official Caesars property information.","hotel_class":"Large centre-Strip casino hotel","coordinate_source":"Mapbox exact-address hotel result checked against Caesars' official address.","source_urls":["https://www.travelgay.com/gay-las-vegas-hotels","https://www.caesars.com/flamingo-las-vegas"]},

 {"name":"Hotel Mazarin","city":"new_orleans","description":"A courtyard boutique hotel in the French Quarter, close to Bourbon Street and the Lavender Line. Travel Gay currently lists it as an LGBTQ+-welcoming New Orleans option.","vibe":"romantic French Quarter courtyard stay near queer nightlife","tags_csv":"cozy,cultural,social","hours":"Hotel reception operates 24 hours; breakfast, bar and courtyard services follow current schedules.","link":"https://hotelmazarin.com/","location":"730 Bienville Street, New Orleans, LA 70130, United States","lat":29.955161,"lng":-90.068214,"arrival":"French Quarter traffic and festivals can complicate drop-off; confirm parking and street access before arrival.","best_for":"Walking access to the Quarter, Bourbon Street and central queer bars while retaining a courtyard retreat.","audience":"Couples, culture travellers, celebration groups and LGBTQ+ visitors in a mixed boutique setting.","dress":"No hotel code; comfortable walking clothes suit the Quarter, while venues set their own rules.","inclusion":"Current Travel Gay coverage presents the hotel as welcoming to LGBTQ+ New Orleans travellers.","basis":"Current Travel Gay New Orleans listing plus official hotel information.","hotel_class":"French Quarter boutique hotel","coordinate_source":"Mapbox exact-address building result checked against the official hotel address.","source_urls":["https://www.travelgay.com/gay-new-orleans-hotels","https://hotelmazarin.com/"]},
 {"name":"Hotel Le Marais","city":"new_orleans","description":"A polished boutique hotel on Conti Street in the French Quarter, with courtyard pool and quick walking access to Bourbon Street's LGBTQ+ venues. Travel Gay currently lists it as gay-friendly.","vibe":"quiet-luxe Quarter hideaway close to late-night energy","tags_csv":"luxury,cozy,social","hours":"Hotel reception operates 24 hours; courtyard, pool and bar schedules should be checked directly.","link":"https://hotellemarais.com/","location":"717 Conti Street, New Orleans, LA 70130, United States","lat":29.956088,"lng":-90.067199,"arrival":"Plan vehicle access around Quarter restrictions and major festivals; the intimate lobby is not designed for mass arrivals.","best_for":"Travellers who want queer nightlife on foot and a calmer boutique atmosphere at the hotel.","audience":"Couples, solo visitors and LGBTQ+ city-break travellers in an adult-leaning mixed setting.","dress":"Relaxed city clothing works; nearby bars and event spaces set their own entrance policies.","inclusion":"The hotel's current specialist LGBTQ+ travel listing supplies the gay-friendly evidence.","basis":"Current Travel Gay New Orleans hotel listing plus official property details.","hotel_class":"Upscale French Quarter boutique hotel","coordinate_source":"Mapbox exact-address result checked against the official Conti Street address.","source_urls":["https://www.travelgay.com/gay-new-orleans-hotels","https://hotellemarais.com/"]},
 {"name":"Dauphine Orleans Hotel","city":"new_orleans","description":"A historic French Quarter hotel spanning several buildings, with courtyard pool and a location between Bourbon and Dauphine nightlife. Travel Gay currently includes it as an LGBTQ+-welcoming New Orleans stay.","vibe":"historic Quarter character with a secluded courtyard pool","tags_csv":"cultural,cozy,mixed","hours":"Hotel reception operates 24 hours; pool, breakfast and bar arrangements follow current hotel schedules.","link":"https://www.dauphineorleans.com/","location":"415 Dauphine Street, New Orleans, LA 70112, United States","lat":29.95731,"lng":-90.0684,"arrival":"Historic-building layouts vary; request accessibility and room-position details, and plan parking before arrival.","best_for":"A character-led French Quarter stay within walking distance of queer bars and cultural sights.","audience":"History travellers, couples, groups and LGBTQ+ guests across a mixed hotel audience.","dress":"No hotel-wide dress code; practical Quarter footwear is useful.","inclusion":"Current Travel Gay coverage identifies the hotel as an LGBTQ+-welcoming city option.","basis":"Current Travel Gay New Orleans listing plus official hotel information.","hotel_class":"Historic French Quarter hotel","coordinate_source":"Mapbox exact-address result checked against the official Dauphine Street address.","source_urls":["https://www.travelgay.com/gay-new-orleans-hotels","https://www.dauphineorleans.com/"]},

 {"name":"Hyatt Regency Orlando","city":"orlando","description":"A major convention resort on International Drive with multiple pools, spa and extensive dining. Travel Gay currently lists it among Orlando's LGBTQ+-welcoming hotels.","vibe":"full-service convention resort with poolside Orlando energy","tags_csv":"massive,luxury,mixed","hours":"Hotel reception operates 24 hours; pools, spa, restaurants and convention facilities use separate schedules.","link":"https://www.hyatt.com/hyatt-regency/en-US/mcoro-hyatt-regency-orlando","location":"9801 International Drive, Orlando, FL 32819, United States","lat":28.427426,"lng":-81.467606,"arrival":"Convention and group arrivals can create queues; mobile check-in and pre-booked dining help on major dates.","best_for":"International Drive, Orange County Convention Center and resort facilities between park days.","audience":"Convention groups, couples, families and LGBTQ+ travellers in a very broad hotel crowd.","dress":"Resort and business casual; pools, spa and restaurants apply activity-specific rules.","inclusion":"Current Travel Gay coverage documents the hotel as an LGBTQ+-welcoming Orlando selection.","basis":"Current Travel Gay Orlando listing plus official Hyatt property information.","hotel_class":"Large upscale convention resort","coordinate_source":"Mapbox exact-address hotel result checked against Hyatt's official address.","source_urls":["https://www.travelgay.com/gay-orlando-hotels","https://www.hyatt.com/hyatt-regency/en-US/mcoro-hyatt-regency-orlando"]},
 {"name":"Hilton Orlando Buena Vista Palace","city":"orlando","description":"A large official Walt Disney World hotel beside Disney Springs, with a pedestrian skybridge, pools and a lazy river. Travel Gay currently includes it as an LGBTQ+-welcoming Orlando-area resort; the physical address is transparently in Lake Buena Vista.","vibe":"playful Disney Springs resort with expansive pool facilities","tags_csv":"massive,relax,mixed","hours":"Hotel reception operates 24 hours; shuttles, pools, restaurants and Disney benefits follow live schedules.","link":"https://www.hilton.com/en/hotels/mcobuhh-hilton-orlando-buena-vista-palace/","location":"1900 E Buena Vista Drive, Lake Buena Vista, FL 32830, United States","lat":28.37702,"lng":-81.51462,"arrival":"Large family and group waves can slow check-in; verify park transport and benefit rules before travel.","best_for":"Disney Springs access, park transport and resort-pool days in the wider Orlando destination.","audience":"Families, couples, groups and LGBTQ+ guests in a broad Disney-area resort crowd.","dress":"Resort casual; restaurants and pools apply their own practical guidance.","inclusion":"Current Travel Gay Orlando coverage supplies the LGBTQ+-welcoming signal; no queer-exclusive positioning is implied.","basis":"Current Travel Gay Orlando listing plus official Hilton address; Lake Buena Vista location stated transparently.","hotel_class":"Large official Walt Disney World resort","coordinate_source":"Hotel-building coordinate checked against Hilton's official 1900 E Buena Vista Drive address.","source_urls":["https://www.travelgay.com/gay-orlando-hotels","https://buenavistapalace.com/location/"]},
 {"name":"Grand Bohemian Hotel Orlando","city":"orlando","description":"An art-filled luxury hotel in downtown Orlando, with rooftop pool, spa and destination dining. Travel Gay currently identifies it as an LGBTQ+-welcoming alternative to the theme-park resort corridor.","vibe":"art-led downtown luxury with a sophisticated social rhythm","tags_csv":"luxury,cultural,mixed","hours":"Hotel reception operates 24 hours; spa, rooftop pool, restaurant and events follow current schedules.","link":"https://www.marriott.com/en-us/hotels/mcoak-grand-bohemian-orlando-autograph-collection/overview/","location":"325 S Orange Avenue, Orlando, FL 32801, United States","lat":28.538683,"lng":-81.378668,"arrival":"Downtown events can affect valet and dining capacity; reserve spa and restaurant separately.","best_for":"Downtown culture, performing arts and city nightlife rather than an on-property theme-park experience.","audience":"Couples, arts travellers, business guests and LGBTQ+ visitors in a mixed luxury setting.","dress":"Smart-casual suits the restaurant and events; the rest of the hotel is relaxed upscale.","inclusion":"Current Travel Gay coverage lists the hotel as an LGBTQ+-welcoming Orlando stay.","basis":"Current Travel Gay Orlando hotel listing plus official Marriott information.","hotel_class":"Luxury Autograph Collection hotel","coordinate_source":"Mapbox exact-address result checked against Marriott's official address.","source_urls":["https://www.travelgay.com/gay-orlando-hotels","https://www.marriott.com/en-us/hotels/mcoak-grand-bohemian-orlando-autograph-collection/overview/"]},

 {"name":"The Hacienda at Warm Sands","city":"palm_springs","description":"A luxury clothing-optional resort created for gay men in Palm Springs' Warm Sands district. The small scale, pools and explicit audience make it a genuine queer specialist stay rather than a generic friendly hotel.","vibe":"private gay men's luxury with serene clothing-optional pools","tags_csv":"luxury,relax,men_only","hours":"Adult resort accommodation; confirm check-in, day access, pool and guest policies directly.","link":"https://thehacienda.com/","location":"586 S Warm Sands Drive, Palm Springs, CA 92264, United States","lat":33.814316,"lng":-116.536066,"arrival":"A small resort with personalised arrival; share timing and access needs in advance.","best_for":"Gay men seeking quiet luxury, privacy and clothing-optional pool time in Warm Sands.","audience":"The property explicitly serves gay men; confirm current eligibility and visitor rules before booking.","dress":"Clothing optional in designated resort areas; normal practical rules apply at reception and off property.","inclusion":"The hotel's own brand explicitly identifies it as a luxury gay men's resort.","basis":"First-party gay men's resort positioning and official property information.","hotel_class":"Luxury gay men's resort","coordinate_source":"Mapbox exact-address hotel result checked against the official property address.","source_urls":["https://www.travelgay.com/gay-palm-springs-hotels","https://thehacienda.com/"]},
 {"name":"Triangle Inn Palm Springs","city":"palm_springs","description":"A clothing-optional gay men's resort in a mid-century Palm Springs compound, offering an intimate pool-centred alternative to larger hotels. Its audience is stated directly by the property.","vibe":"intimate mid-century gay men's hideaway","tags_csv":"relax,cozy,men_only","hours":"Adult resort accommodation; verify check-in, pool, visitor and clothing-optional policies directly.","link":"https://triangle-inn.com/","location":"555 E San Lorenzo Road, Palm Springs, CA 92264, United States","lat":33.809131,"lng":-116.542555,"arrival":"Small-property arrival is best coordinated in advance, especially outside standard reception times.","best_for":"A quiet, social and clothing-optional gay men's stay close to central Palm Springs.","audience":"Gay men; the resort publishes its specialist audience and adult environment.","dress":"Clothing optional in designated private areas; city clothing is needed beyond the property.","inclusion":"The official property describes Triangle Inn as a gay men's resort.","basis":"First-party gay men's resort positioning plus official address.","hotel_class":"Boutique clothing-optional gay men's resort","coordinate_source":"Mapbox exact-address result checked against the official property address.","source_urls":["https://www.travelgay.com/gay-palm-springs-hotels","https://triangle-inn.com/"]},
 {"name":"Vista Grande Resort","city":"palm_springs","description":"A long-running gay men's resort in Warm Sands with landscaped grounds, pools and clothing-optional areas. The property is explicitly designed for gay men and belongs to Palm Springs' specialist queer resort tradition.","vibe":"lush gay men's resort with social pools and desert calm","tags_csv":"social,relax,men_only","hours":"Adult resort accommodation; confirm seasonal reception, pool, visitor and day-pass policies directly.","link":"https://vistagranderesort.com/","location":"574 S Warm Sands Drive, Palm Springs, CA 92264, United States","lat":33.81457,"lng":-116.53589,"arrival":"Coordinate arrival with the resort; festival and Pride periods can sell out well ahead.","best_for":"Gay men wanting a larger clothing-optional Warm Sands resort with both social and quiet areas.","audience":"The property explicitly serves gay men; current guest and visitor policies should be checked directly.","dress":"Clothing optional in designated resort spaces; external venues set their own rules.","inclusion":"The resort's first-party material explicitly states its gay men's focus.","basis":"First-party gay men's resort positioning and current specialist travel coverage.","hotel_class":"Clothing-optional gay men's resort","coordinate_source":"Mapbox exact-address hotel result checked against the official address.","source_urls":["https://www.travelgay.com/gay-palm-springs-hotels","https://vistagranderesort.com/"]},

 {"name":"Kimpton Hotel Palomar Philadelphia","city":"philadelphia","description":"A design-led Kimpton near Rittenhouse Square and the Gayborhood, with an established brand-level LGBTQ+ inclusion programme. Travel Gay currently recommends it for queer Philadelphia stays.","vibe":"confident boutique design close to the Gayborhood","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; restaurant, social hour and fitness access use current schedules.","link":"https://www.hotelpalomar-philadelphia.com/","location":"117 S 17th Street, Philadelphia, PA 19103, United States","lat":39.950805,"lng":-75.16873,"arrival":"Valet and restaurant demand can rise on event weekends; standard hotel check-in otherwise applies.","best_for":"Rittenhouse Square, Center City culture and walking access toward the Gayborhood.","audience":"LGBTQ+ couples, solo travellers, pet travellers and general boutique-hotel guests.","dress":"Expressive city style is welcome; dining is generally smart-casual.","inclusion":"Kimpton publishes an LGBTQ+ hotel programme and partnerships, supported by current Travel Gay coverage.","basis":"Official Kimpton LGBTQ+ programme plus current Travel Gay Philadelphia listing.","hotel_class":"Upscale boutique Kimpton hotel","coordinate_source":"Mapbox exact-address building result checked against the official hotel address.","source_urls":["https://www.travelgay.com/gay-philadelphia-hotels/","https://www.ihg.com/kimptonhotels/content/us/en/stay/gay-friendly-hotels"]},
 {"name":"Warwick Hotel Rittenhouse Square","city":"philadelphia","description":"A large historic-modern hotel near Rittenhouse Square, within walking distance of Center City and the Gayborhood. Travel Gay currently includes it among Philadelphia's LGBTQ+-welcoming hotels.","vibe":"classic Center City scale with contemporary polish","tags_csv":"luxury,mixed,social","hours":"Hotel reception operates 24 hours; dining, fitness and event facilities use current schedules.","link":"https://www.warwickrittenhouse.com/","location":"220 S 17th Street, Philadelphia, PA 19103, United States","lat":39.949139,"lng":-75.169477,"arrival":"Large events can create lobby and valet peaks; communicate room and accessibility needs in advance.","best_for":"A central full-service base near Rittenhouse, museums and the Gayborhood.","audience":"Couples, business travellers, groups and LGBTQ+ guests in a broad city-hotel crowd.","dress":"No hotel-wide code; smart-casual suits restaurants and events.","inclusion":"Current specialist LGBTQ+ travel coverage documents the hotel as a welcoming Philadelphia option.","basis":"Current Travel Gay Philadelphia listing plus official hotel information.","hotel_class":"Large upscale Center City hotel","coordinate_source":"Mapbox exact-address result checked against the official address.","source_urls":["https://www.travelgay.com/gay-philadelphia-hotels/","https://www.warwickrittenhouse.com/"]},
 {"name":"Alexander Inn","city":"philadelphia","description":"An independent boutique hotel in a restored Center City building, positioned within the Gayborhood and known for straightforward local character. Travel Gay currently lists it for LGBTQ+ Philadelphia visitors.","vibe":"independent Gayborhood-adjacent stay with local character","tags_csv":"cozy,cultural,mixed","hours":"Hotel reception operates 24 hours; breakfast and guest services follow current schedules.","link":"https://www.alexanderinn.com/","location":"301 S 12th Street, Philadelphia, PA 19107, United States","lat":39.946241,"lng":-75.161009,"arrival":"Compact urban hotel arrival; confirm parking separately and expect event-period street activity.","best_for":"Travellers prioritising the Gayborhood, walkability and an independent hotel over resort facilities.","audience":"Queer visitors, couples, solo travellers and general city guests in a mixed boutique environment.","dress":"No hotel dress code; nearby nightlife venues establish their own policies.","inclusion":"Its current Travel Gay listing and direct Gayborhood location provide the LGBTQ+ travel context.","basis":"Current Travel Gay Philadelphia listing plus official property address.","hotel_class":"Independent boutique hotel","coordinate_source":"Mapbox exact-address building result checked against the official address.","source_urls":["https://www.travelgay.com/gay-philadelphia-hotels/","https://www.alexanderinn.com/"]},

 {"name":"Andaz San Diego","city":"san_diego","description":"A design-led downtown hotel in the Gaslamp Quarter with a rooftop pool and nightlife-facing atmosphere. Travel Gay currently includes it as an LGBTQ+-welcoming San Diego option.","vibe":"fashion-forward Gaslamp stay with a lively rooftop","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; rooftop, pool, dining and events follow current schedules.","link":"https://www.hyatt.com/andaz/en-US/sanas-andaz-san-diego","location":"600 F Street, San Diego, CA 92101, United States","lat":32.713788,"lng":-117.158796,"arrival":"Rooftop events and Gaslamp weekends can make valet and lobby periods busy; room check-in remains separate.","best_for":"Downtown dining, nightlife and events, with Hillcrest reached by a short ride.","audience":"Couples, groups, design travellers and LGBTQ+ guests in an adult-leaning mixed crowd.","dress":"Fashionable casual works; programmed rooftop events may publish a specific code.","inclusion":"Current Travel Gay coverage identifies Andaz as an LGBTQ+-welcoming San Diego hotel.","basis":"Current Travel Gay San Diego listing plus official Hyatt information.","hotel_class":"Luxury lifestyle hotel","coordinate_source":"Mapbox exact-address hotel result checked against Hyatt's official address.","source_urls":["https://www.travelgay.com/gay-san-diego-hotels","https://www.hyatt.com/andaz/en-US/sanas-andaz-san-diego"]},
 {"name":"Margaritaville Hotel San Diego Gaslamp Quarter","city":"san_diego","description":"A colourful Gaslamp Quarter hotel with rooftop pool and a playful resort-style identity downtown. Travel Gay currently lists it as an LGBTQ+-welcoming San Diego stay.","vibe":"bright urban resort energy with a social rooftop pool","tags_csv":"social,relax,mixed","hours":"Hotel reception operates 24 hours; rooftop, pool, restaurant and bar schedules vary.","link":"https://www.margaritavilleresorts.com/margaritaville-hotel-san-diego","location":"435 6th Avenue, San Diego, CA 92101, United States","lat":32.70978,"lng":-117.158946,"arrival":"Gaslamp events and baseball dates can pressure valet and rooftop capacity; book key experiences separately.","best_for":"A playful downtown stay near Petco Park, dining and nightlife.","audience":"Couples, groups, leisure travellers and LGBTQ+ guests in a broad upbeat hotel crowd.","dress":"Resort-casual character; rooftop and nightlife programming may set event rules.","inclusion":"Current specialist LGBTQ+ travel coverage documents the hotel as a welcoming option.","basis":"Current Travel Gay San Diego listing plus official property information.","hotel_class":"Upscale lifestyle hotel","coordinate_source":"Mapbox exact-address hotel result checked against the official address.","source_urls":["https://www.travelgay.com/gay-san-diego-hotels","https://www.margaritavilleresorts.com/margaritaville-hotel-san-diego"]},
 {"name":"Hotel Indigo San Diego Gaslamp Quarter","city":"san_diego","description":"A pet-friendly boutique hotel in the Gaslamp Quarter with rooftop bar and views toward Petco Park. Its current Travel Gay listing supplies a documented LGBTQ+-welcoming signal.","vibe":"relaxed Gaslamp boutique style with rooftop city views","tags_csv":"social,cozy,mixed","hours":"Hotel reception operates 24 hours; rooftop bar, restaurant and fitness schedules should be checked directly.","link":"https://www.ihg.com/hotelindigo/hotels/us/en/san-diego/sanis/hoteldetail","location":"509 9th Avenue, San Diego, CA 92101, United States","lat":32.710702,"lng":-117.156187,"arrival":"Baseball and convention dates can affect valet and rooftop access; pet and accessibility needs should be shared early.","best_for":"Gaslamp and East Village access in a smaller lifestyle hotel than the major waterfront resorts.","audience":"Couples, solo travellers, pet travellers and LGBTQ+ guests in a mixed boutique setting.","dress":"No hotel-wide code; smart-casual suits the rooftop bar.","inclusion":"Travel Gay's current San Diego guide includes the hotel as an LGBTQ+-welcoming choice.","basis":"Current Travel Gay San Diego listing plus official IHG information.","hotel_class":"Boutique Hotel Indigo","coordinate_source":"Mapbox exact-address result checked against IHG's official address.","source_urls":["https://www.travelgay.com/gay-san-diego-hotels","https://www.ihg.com/hotelindigo/hotels/us/en/san-diego/sanis/hoteldetail"]},

 {"name":"W Seattle","city":"seattle","description":"A design-conscious downtown hotel near the central library and light rail, with a lively lobby and contemporary rooms. Travel Gay currently includes it as an LGBTQ+-welcoming Seattle choice.","vibe":"bold downtown design with a music-led social lobby","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; restaurant, bar, fitness and events follow current schedules.","link":"https://www.marriott.com/en-us/hotels/seawh-w-seattle/overview/","location":"1112 4th Avenue, Seattle, WA 98101, United States","lat":47.60743,"lng":-122.333661,"arrival":"Downtown events can make valet and lobby periods busier; reserve dining and special programming separately.","best_for":"A polished downtown base with light-rail access to Capitol Hill's queer scene.","audience":"Couples, business travellers, music and design guests, and LGBTQ+ visitors in a mixed upscale crowd.","dress":"Contemporary city style fits the lobby and bar; no hotel-wide code is published.","inclusion":"Current Travel Gay Seattle coverage documents the property as an LGBTQ+-welcoming hotel.","basis":"Current Travel Gay Seattle listing plus official Marriott information.","hotel_class":"Luxury W lifestyle hotel","coordinate_source":"Mapbox exact-address hotel result checked against Marriott's official address.","source_urls":["https://www.travelgay.com/gay-seattle-hotels","https://www.marriott.com/en-us/hotels/seawh-w-seattle/overview/"]},
 {"name":"Warwick Seattle","city":"seattle","description":"A central Belltown hotel with balconies, pool and easy access to downtown attractions. Travel Gay currently lists it as a welcoming Seattle option for LGBTQ+ travellers.","vibe":"comfortable Belltown city stay with balcony views","tags_csv":"relax,mixed,social","hours":"Hotel reception operates 24 hours; pool, fitness and restaurant schedules should be checked directly.","link":"https://www.warwickhotels.com/warwick-seattle","location":"401 Lenora Street, Seattle, WA 98121, United States","lat":47.613782,"lng":-122.340685,"arrival":"Standard full-service check-in; Belltown events can affect valet and street access.","best_for":"Walking to Pike Place, Belltown and Seattle Center, with Capitol Hill a short ride away.","audience":"Couples, families, business guests and LGBTQ+ visitors in a broad city-hotel mix.","dress":"No hotel-wide dress code; smart-casual suits dining.","inclusion":"Current specialist LGBTQ+ travel coverage includes Warwick as a welcoming Seattle hotel.","basis":"Current Travel Gay Seattle listing plus official Warwick information.","hotel_class":"Upscale downtown hotel","coordinate_source":"Mapbox exact-address result checked against Warwick's official address.","source_urls":["https://www.travelgay.com/gay-seattle-hotels","https://www.warwickhotels.com/warwick-seattle"]},
 {"name":"MarQueen Hotel","city":"seattle","description":"A historic boutique hotel in Queen Anne, close to Seattle Center and Climate Pledge Arena. Travel Gay currently includes it among Seattle's LGBTQ+-welcoming hotel choices.","vibe":"historic Queen Anne character with neighbourhood warmth","tags_csv":"cozy,cultural,mixed","hours":"Hotel reception operates 24 hours; spa, restaurant and guest services use current schedules.","link":"https://www.marqueen.com/","location":"600 Queen Anne Avenue N, Seattle, WA 98109, United States","lat":47.625015,"lng":-122.356348,"arrival":"The historic building has distinctive layouts; discuss stairs, accessibility and parking before arrival.","best_for":"Seattle Center events and a residential neighbourhood feel rather than direct Capitol Hill nightlife.","audience":"Couples, arts and event travellers, solo guests and LGBTQ+ visitors in a mixed boutique crowd.","dress":"No hotel-wide code; everyday Seattle clothing is appropriate.","inclusion":"Travel Gay's current Seattle guide supplies the LGBTQ+-welcoming evidence for the property.","basis":"Current Travel Gay Seattle listing plus official hotel information.","hotel_class":"Historic boutique hotel","coordinate_source":"Mapbox exact-address building result checked against the official address.","source_urls":["https://www.travelgay.com/gay-seattle-hotels","https://www.marqueen.com/"]},

 {"name":"The Dupont Circle Hotel","city":"washington_dc","description":"A luxury hotel directly on Dupont Circle, near one of Washington's historic LGBTQ+ neighbourhoods and nightlife corridors. Travel Gay currently marks it Approved for LGBTQ+ guests.","vibe":"cosmopolitan Dupont luxury at the heart of queer Washington","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; restaurant, bar and guest services use current schedules.","link":"https://www.doylecollection.com/hotels/the-dupont-circle-hotel","location":"1500 New Hampshire Avenue NW, Washington, DC 20036, United States","lat":38.910604,"lng":-77.042993,"arrival":"Dupont traffic and event dates can pressure valet and dining; normal 24-hour hotel arrival otherwise applies.","best_for":"Immediate Dupont access, museums, dining and a walkable connection to LGBTQ+ Washington history.","audience":"LGBTQ+ couples, international travellers, business guests and luxury visitors in a broad hotel crowd.","dress":"Smart-casual suits the restaurant and bar; no identity-based hotel code is published.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and a welcoming service standard.","basis":"Current Travel Gay Approved listing plus official hotel information.","hotel_class":"Luxury Dupont Circle hotel","coordinate_source":"Mapbox exact-address hotel result checked against the official property address.","source_urls":["https://www.travelgay.com/gay-washington-hotels","https://www.doylecollection.com/hotels/the-dupont-circle-hotel"]},
 {"name":"The Darcy Hotel","city":"washington_dc","description":"A boutique hotel between Dupont Circle and Logan Circle with an explicit first-party LGBTQ+ friendly page. The hotel presents inclusivity as part of its own identity rather than relying only on a directory listing.","vibe":"warm independent style between Dupont and Logan circles","tags_csv":"luxury,cozy,mixed","hours":"Hotel reception operates 24 hours; restaurant, fitness and guest experiences follow current schedules.","link":"https://www.thedarcyhotel.com/","location":"1515 Rhode Island Avenue NW, Washington, DC 20005, United States","lat":38.907906,"lng":-77.035543,"arrival":"Straightforward boutique check-in; reserve dining and communicate accessibility needs before arrival.","best_for":"A central stay between two key neighbourhoods with easy access to queer nightlife and city sights.","audience":"LGBTQ+ travellers, couples, families and business guests in a welcoming mixed environment.","dress":"No hotel dress code; smart-casual works for dining and city evenings.","inclusion":"The Darcy publishes a dedicated LGBTQ+ friendly hotel page and explicitly welcomes queer guests.","basis":"First-party LGBTQ+ friendly hotel statement.","hotel_class":"Upscale independent boutique hotel","coordinate_source":"Mapbox exact-address result checked against the official hotel address.","source_urls":["https://www.thedarcyhotel.com/about/lgbt-friendly-hotel","https://www.thedarcyhotel.com/"]},
 {"name":"Kimpton Banneker Hotel","city":"washington_dc","description":"A design-led Kimpton near Dupont and Logan circles with a dedicated Pride page and documented Trevor Project partnership. This gives the hotel a concrete first-party LGBTQ+ inclusion record.","vibe":"modern queer-friendly boutique stay with civic Washington polish","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; rooftop, restaurant, social hour and fitness follow current schedules.","link":"https://www.thebanneker.com/","location":"1315 16th Street NW, Washington, DC 20036, United States","lat":38.908272,"lng":-77.036087,"arrival":"Rooftop and event capacity are separate from room check-in; reserve peak evenings when they matter.","best_for":"Dupont, Logan Circle and downtown access in a hotel with explicit LGBTQ+ commitments.","audience":"LGBTQ+ couples, solo travellers, pet travellers, business guests and allies.","dress":"Expressive city clothing is welcome; rooftop and restaurant are generally smart-casual.","inclusion":"The hotel's own Pride page calls it gay-friendly and documents support for The Trevor Project.","basis":"First-party LGBTQ+ positioning and documented community partnership.","hotel_class":"Upscale boutique Kimpton hotel","coordinate_source":"Mapbox exact-address result checked against the official hotel address.","source_urls":["https://www.thebanneker.com/washington-dc-boutique-hotel/pride/","https://www.thebanneker.com/"]}
]
$hotels$) h(
    name text, city text, description text, vibe text, tags_csv text,
    hours text, link text, location text, lat double precision, lng double precision,
    arrival text, best_for text, audience text, dress text, inclusion text,
    basis text, hotel_class text, coordinate_source text, source_urls jsonb
  )
), source_hotels as (
  select
    h.*,
    jsonb_build_object(
      'queue_wait', h.arrival,
      'best_nights', h.best_for,
      'crowd_mix', h.audience,
      'dress_code', h.dress,
      'staff_inclusivity', h.inclusion,
      'inclusion_basis', h.basis,
      'hotel_class', h.hotel_class,
      'coordinate_source', h.coordinate_source,
      'source_urls', h.source_urls,
      'research_status', 'researched_sources_and_exact_property_location',
      'updated_at', '2026-08-23T00:00:00Z'
    ) as intel
  from raw_hotels h
), updated as (
  update public.places p
  set type = 'hotel',
      description = h.description,
      vibe = h.vibe,
      vibe_tags = string_to_array(h.tags_csv, ','),
      hours = h.hours,
      link = h.link,
      location = h.location,
      lat = h.lat,
      lng = h.lng,
      venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || h.intel,
      seo_indexable = true,
      seo_quality_status = 'approved',
      updated_at = timezone('utc', now())
  from source_hotels h
  where lower(trim(p.city)) = h.city
    and lower(trim(p.name)) = lower(trim(h.name))
  returning p.id
)
insert into public.places (
  name, city, type, description, vibe, vibe_tags, hours, link, location,
  lat, lng, venue_intel, seo_indexable, seo_quality_status, updated_at
)
select
  h.name, h.city, 'hotel', h.description, h.vibe,
  string_to_array(h.tags_csv, ','), h.hours, h.link, h.location,
  h.lat, h.lng, h.intel, true, 'approved', timezone('utc', now())
from source_hotels h
where not exists (
  select 1 from public.places p
  where lower(trim(p.city)) = h.city
    and lower(trim(p.name)) = lower(trim(h.name))
);

commit;

-- Expected: 3 complete rows in every destination.
select
  city,
  count(*) filter (
    where type = 'hotel'
      and venue_intel->>'updated_at' = '2026-08-23T00:00:00Z'
  ) as batch_hotels,
  count(*) filter (
    where type = 'hotel'
      and venue_intel->>'updated_at' = '2026-08-23T00:00:00Z'
      and coalesce(venue_intel->>'queue_wait', '') <> ''
      and coalesce(venue_intel->>'best_nights', '') <> ''
      and coalesce(venue_intel->>'crowd_mix', '') <> ''
      and coalesce(venue_intel->>'dress_code', '') <> ''
      and coalesce(venue_intel->>'staff_inclusivity', '') <> ''
      and jsonb_array_length(coalesce(venue_intel->'source_urls', '[]'::jsonb)) >= 2
      and lat between -90 and 90
      and lng between -180 and 180
      and coalesce(location, '') <> ''
      and coalesce(link, '') <> ''
  ) as complete_rows
from public.places
where lower(trim(city)) in (
  'cancun','chicago','dallas','denver','fireisland','las_vegas','new_orleans',
  'orlando','palm_springs','philadelphia','san_diego','seattle','washington_dc'
)
group by city
order by city;

select
  name, city, location,
  round(lat::numeric, 6) as lat,
  round(lng::numeric, 6) as lng,
  venue_intel->>'inclusion_basis' as inclusion_basis
from public.places
where type = 'hotel'
  and venue_intel->>'updated_at' = '2026-08-23T00:00:00Z'
order by city, name;
