-- Queer Atlas: Windhoek city package
-- Editorially checked 2026-08-15. Idempotent; no null coordinates.

begin;

with src as (
select * from jsonb_to_recordset($windhoek_places$
[
 {"name":"Piccolo Cafe & Lounge","city":"windhoek","type":"restaurant","description":"A lively Italian-leaning cafe and late lounge inside Maerua Mall, and one of the few Windhoek businesses with a public, independently documented LGBTQI+ safe-space commitment. Equal Namibia and Drag Night Namibia inaugurated it into the Verified Safe-Space network in 2024. Come for an easy meal, cocktails or Tuesday trivia rather than expecting a dedicated gay bar; the room stays mixed and its value is that queerness does not need a special event to be welcome.","vibe":"bright mall-side ally lounge where trivia, cocktails and queer ease can share a table","hours":"Monday-Saturday from about 08:00 until late; Tuesday trivia is commonly advertised from 18:30 or 19:00. Sunday closing and late service should be confirmed directly.","link":"https://www.facebook.com/537394433062383","location":"Shop 13, Maerua Mall, Jan Jonker Road and Centaurus Street, Windhoek, Namibia","lat":-22.58412,"lng":17.09315},
 {"name":"The Village Windhoek","city":"windhoek","type":"hotel","description":"A landscaped Eros compound combining boutique suites, workspaces, restaurants, courtyards and a weekly Sunday market. Equal Namibia has identified The Village as part of its Verified Safe-Space network, while current guests describe the complex as both calm and socially alive. It is not queer-exclusive, but it offers something Windhoek badly needs: an attractive daytime place where a coffee, market browse, short stay or first meeting does not require a nightlife plan.","vibe":"green urban village with a verified welcome, design-minded stays and soft Sunday energy","hours":"The complex operates daily by tenant; the official Sunday Market runs 09:00-15:00. Suites and private events use separate booking access.","link":"https://www.villagewhk.com/","location":"18 Liliencron Street, Eros, Windhoek, Namibia","lat":-22.5531816,"lng":17.0878429},
 {"name":"The Brewers Market","city":"windhoek","type":"bar","description":"The old Warehouse Theatre complex is now a large industrial brewpub and live-event space with several rooms, a broad local crowd and a history that still matters to queer Windhoek. A rainbow crossing was painted outside during Namibia Pride, and the complex has hosted Pride Pop-Up, Kings of Namibia and 2026's House of Rainbows. On an ordinary night it is a mixed city bar, not a permanent gay venue; on the right organiser's date, it becomes one of the capital's most visible queer rooms.","vibe":"lofty old-brewery rooms where live music, local nights and Pride-scale pop-ups can take over","hours":"Current listings show daily service from late morning until late, with the busiest programme Friday and Saturday; private events alter room access, so verify the live listing.","link":"https://www.facebook.com/The-Brewers-Market-103031907902601","location":"Old Breweries Building, 48 Tal Street, Windhoek Central, Namibia","lat":-22.5726817,"lng":17.0838927},
 {"name":"Le Roof at FNCC","city":"windhoek","type":"bar","description":"The open-air performance room at the Franco-Namibian Cultural Centre is one of Windhoek's most useful programme-led queer addresses. Drag Night Namibia brought Motown glamour here in March 2026, the Pride Kiki Ball filled it with ballroom in June, and FNCC followed with an LGBTQIA+ film series in July. Outside those dates it belongs to a wider arts centre, so check the title on the calendar rather than assuming every evening carries the same crowd.","vibe":"open-air cultural stage where drag, ballroom, film and conversation become publicly queer","hours":"Event-led. FNCC office hours are Monday-Thursday 08:00-17:00 and Friday 08:00-13:00; Le Roof doors and closing follow each ticketed programme.","link":"https://www.fncc.org.na/events","location":"Franco-Namibian Cultural Centre, 118 Robert Mugabe Avenue, Windhoek, Namibia","lat":-22.5607471,"lng":17.0863230}
]
$windhoek_places$) p(name text,city text,type text,description text,vibe text,hours text,link text,location text,lat double precision,lng double precision)
), upd as (
 update public.places p set type=s.type,description=s.description,vibe=s.vibe,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)) returning p.id
)
insert into public.places(name,city,type,description,vibe,vibe_tags,hours,link,location,lat,lng,seo_indexable,seo_quality_status,updated_at)
select name,city,type,description,vibe,array[]::text[],hours,link,location,lat,lng,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.places p where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)));

with src as (
select * from jsonb_to_recordset($windhoek_events$
[
 {"name":"Drag Night Namibia: Drag Me to Motown 2026","city":"windhoek","description":"Drag Night Namibia opened its 2026 stage season at Le Roof with sequins, Motown classics, fashion and a cast selected through Positive Vibes' Just Like You campaign. The 7 March show was designed as both entertainment and an explicitly inclusive platform for local performers, with tickets listed at N$150 in advance and N$160 at the door.","link":"https://weshareevents.com/event/drag-night-namibia-2/","date":"2026-03-07","start_date":"2026-03-07","end_date":"2026-03-07","location":"Le Roof, Franco-Namibian Cultural Centre, 118 Robert Mugabe Avenue, Windhoek, Namibia","lat":-22.5607471,"lng":17.0863230,"vibe":"retro drag glamour with a real local-community purpose"},
 {"name":"Pride Kiki Ball 2026","city":"windhoek","description":"Windhoek's Pride Month began with a true ballroom night at Le Roof on 6 June. Open categories included corporate realness, face, European and All-American runway, body and Vogue Femme; performers and allies shared the floor while local fashion, beauty and restaurant sponsors backed prizes. Advance entry was N$150 and the door price N$180.","link":"https://www.namibian.com.na/kiki-ball-kicks-of-lgbtqi-pride-month/","date":"2026-06-06","start_date":"2026-06-06","end_date":"2026-06-06","location":"Le Roof, Franco-Namibian Cultural Centre, 118 Robert Mugabe Avenue, Windhoek, Namibia","lat":-22.5607471,"lng":17.0863230,"vibe":"Namibian ballroom, community judging and unapologetic Pride expression"},
 {"name":"House of Rainbows 2026","city":"windhoek","description":"Pride Pop-Up, Kings of Namibia and Fruity Connects closed Windhoek's Pride Month with ten hours of games, glam, music, performance, conversation and community visibility on 27 June. The event occupied the old Warehouse Theatre rooms at Brewers Market from 13:00 to 23:00, with N$50 presale and N$100 door tickets.","link":"https://weshareevents.com/event/house-of-rainbows-2026/","date":"2026-06-27","start_date":"2026-06-27","end_date":"2026-06-27","location":"The Brewers Market, Old Breweries Building, 48 Tal Street, Windhoek, Namibia","lat":-22.5726817,"lng":17.0838927,"vibe":"all-day queer joy moving from games and connection into performance and music"},
 {"name":"Les Rendez-vous Cinema: LGBTQIA+ Film Series 2026","city":"windhoek","description":"FNCC's July cinema series brought three contemporary French films about identity, desire, emotion and transformation to Windhoek across 1, 8 and 22 July. The spaced-out Wednesday format offered a quieter cultural route into Pride-season conversation after June's drag and ballroom stages.","link":"https://www.fncc.org.na/events","date":"2026-07-01","start_date":"2026-07-01","end_date":"2026-07-22","location":"Franco-Namibian Cultural Centre, 118 Robert Mugabe Avenue, Windhoek, Namibia","lat":-22.5607471,"lng":17.0863230,"vibe":"thoughtful queer cinema and conversation in an established cultural centre"}
]
$windhoek_events$) e(name text,city text,description text,link text,date date,start_date date,end_date date,location text,lat double precision,lng double precision,vibe text)
), upd as (
 update public.events e set description=s.description,link=s.link,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)) returning e.id
)
insert into public.events(name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.events e where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)));

with src as (
select * from jsonb_to_recordset($windhoek_services$
[
 {"name":"Out-Right Namibia","city":"windhoek","type":"wellness","provider_name":"Out-Right Namibia","contact":"+264 81 649 2719; info@outrightnam.com","booking_link":"https://outrightnam.com/contact-us/","description":"Namibia's long-running LGBTQI+ human-rights organisation combines advocacy with practical support. Its current programme includes SRHR and HIV services, psychosocial counselling, crisis intervention, legal literacy and community mobilisation. Contact before travelling so the team can route a health, safety, counselling or rights issue correctly rather than assuming every service is a walk-in.","hours":"Weekday contact by phone or email; programme and clinic access should be arranged directly before arrival.","link":"https://outrightnam.com/","location":"7 Best Street, Windhoek West, Windhoek, Namibia","lat":-22.5626596,"lng":17.0657063,"price_tier":"$","vibe":"queer-led rights, health and crisis support with national reach","source":"Out-Right Namibia official website and current contact page; checked 2026-08-15"},
 {"name":"Positive Vibes Trust Namibia","city":"windhoek","type":"wellness","provider_name":"Positive Vibes Trust","contact":"+264 61 245556; info@positivevibes.org","booking_link":"https://www.positivevibes.org/contacts/","description":"A Namibian-registered organisation working at the intersection of queer rights, HIV, sexual and reproductive health, community power and structural change. Positive Vibes supports LGBTQ+ people, sex workers, people living with HIV, women-led groups and other marginalised communities across a much wider regional network. This is an organisation and programme hub, not a general medical clinic; begin with a clear email or call.","hours":"Weekday organisational contact; project, training and community access are arranged through the relevant team.","link":"https://www.positivevibes.org/","location":"49 Pasteur Street, Windhoek West, Windhoek, Namibia","lat":-22.5591358,"lng":17.0679899,"price_tier":"$","vibe":"community-rooted queer rights and health work built for long-term change","source":"Positive Vibes and IPPF Africa official profiles and current contact information; checked 2026-08-15"},
 {"name":"Sister Namibia","city":"windhoek","type":"other","provider_name":"Sister Namibia","contact":"media@sisternamibia.org","booking_link":"https://sisternamibia.org/contact/","description":"A feminist media and advocacy organisation amplifying plural voices across Namibia, including queer and gender-nonconforming perspectives. Sister Namibia co-shaped Windhoek's 2026 Pride Month, maintains a practical directory of mental-health and counselling routes, and uses publishing, public art and civic education to make belonging visible. It is best approached for programme, media or referral information rather than emergency counselling.","hours":"Contact by email before visiting; public events and campaigns publish their own access times.","link":"https://sisternamibia.org/","location":"163 Nelson Mandela Avenue, Eros, Windhoek, Namibia","lat":-22.55136,"lng":17.0891676,"price_tier":"$","vibe":"warm feminist storytelling, public visibility and practical referral knowledge","source":"Sister Namibia official contact, resources and 2026 Pride collaboration; checked 2026-08-15"},
 {"name":"Legal Assistance Centre Namibia","city":"windhoek","type":"other","provider_name":"Legal Assistance Centre","contact":"+264 61 223356; info@lac.org.na","booking_link":"https://www.lac.org.na/index.php/contact/","description":"Namibia's public-interest law centre provides free basic advice and takes litigation with wider community impact. Its LGBTQI+ work explains decriminalisation, family and immigration law, violence and discrimination in unusually clear language. The centre does not operate like a private lawyer for every personal dispute, so call or attend advice hours for triage and expect staff to assess whether the issue fits its mandate.","hours":"Basic advice Monday-Friday 08:00-11:30 and 14:00-16:00; Friday closes at 15:00, according to the official site.","link":"https://www.lac.org.na/index.php/projects/gender-research-advocacy-grap/lgbti/","location":"4 Marien Ngouabi Street, Windhoek, Namibia","lat":-22.5576607,"lng":17.0873437,"price_tier":"$","vibe":"plain-language rights guidance and strategic legal support without a fee","source":"Legal Assistance Centre official LGBTI, about and contact pages; checked 2026-08-15"},
 {"name":"Equal Namibia","city":"windhoek","type":"other","provider_name":"Namibia Equal Rights Movement","contact":"+264 81 7173938; namibiaequalrightsmovement@gmail.com","booking_link":"https://www.instagram.com/equalnamibia/","description":"A youth-led grassroots movement challenging state-sanctioned homophobia and intersectional discrimination. Equal Namibia coordinates across civil society, helps drive Namibia Pride Week and created the Verified Safe-Space network that publicly identifies queer- and ally-owned businesses such as Piccolo and The Village. Contact through its current social channel for organising and community information; this is not a staffed drop-in centre with guaranteed daily reception.","hours":"Movement-led and appointment-based; use the current social channel or email before visiting.","link":"https://www.instagram.com/equalnamibia/","location":"Erf 194, TransNamib Goods Shed area, Hosea Kutako Drive, Windhoek, Namibia","lat":-22.55553,"lng":17.08026,"price_tier":"$","vibe":"young grassroots organising turning equality into visible local action","source":"CIVIC +264 profile, 2025 Legal Literacy Handbook and local safe-space reporting; checked 2026-08-15"}
]
$windhoek_services$) s(name text,city text,type text,provider_name text,contact text,booking_link text,description text,hours text,link text,location text,lat double precision,lng double precision,price_tier text,vibe text,source text)
), upd as (
 update public.services x set type=s.type,provider_name=s.provider_name,contact=s.contact,booking_link=s.booking_link,description=s.description,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,price_tier=s.price_tier,vibe=s.vibe,source=s.source,"lastChecked"='2026-08-15'::date,verified=true,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)) returning x.id
)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified,seo_indexable,seo_quality_status,updated_at)
select name,city,type,provider_name,contact,booking_link,description,hours,link,array[]::text[],location,lat,lng,price_tier,vibe,array[]::text[],source,'2026-08-15'::date,true,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.services x where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)));

commit;

select 'places' category,count(*) total from public.places where lower(trim(city))='windhoek'
union all select 'events',count(*) from public.events where lower(trim(city))='windhoek'
union all select 'services',count(*) from public.services where lower(trim(city))='windhoek'
order by category;
