-- Queer Atlas: four researched LGBTQ-welcoming hotels per new city.
-- Split, Nantes, Strasbourg, Merida (Yucatan), San Sebastian. Idempotent.

begin;

alter table if exists public.places
  add column if not exists venue_intel jsonb not null default '{}'::jsonb;

with raw_hotels as (
 select * from jsonb_to_recordset($qa_hotels$
[
 {"name":"Atrium Hotel Split","aliases":"Atrium Hotel Split|Atrium Hotel","city":"split","description":"A full-service five-star hotel in Split's business district with an indoor pool, wellness, restaurants and year-round operation. Its position about one kilometre from the historic centre suits travellers wanting larger facilities rather than palace-lane intimacy.","vibe":"large polished city hotel balancing spa facilities, business scale and old-town access","tags":"luxury,relax,mixed","hours":"Reception operates 24 hours; pool, wellness, restaurants and casino maintain separate schedules.","link":"https://www.safirhoteli.hr/en/atrium-hotel-split/","location":"Ulica Domovinskog rata 49A, 21000 Split, Croatia","lat":43.518868,"lng":16.447682,"arrival":"The shopping and business district can be busy at road peaks; reserve garage access and an adapted room directly before arrival.","best":"Best for guests prioritising indoor wellness, parking and full hotel infrastructure over immediate waterfront nightlife.","crowd":"Queer couples and solo visitors mix with conferences, casino guests, tour groups and mainstream luxury travellers.","dress":"City casual works by day; restaurants and casino areas lean smart-casual, with separate pool and wellness attire.","inclusion":"Hotels.com currently includes Atrium in its LGBTQIA-welcoming Split collection; no queer ownership is claimed.","basis":"Current inclusion-labelled hotel catalogue paired with Split Tourist Board and active first-party property information.","class":"Five-star full-service city hotel","coords":"Mapbox exact-address result for Domovinskog rata 49A, checked 2026-08-27.","sources":["https://www.hotels.com/en/de1634348-th21/lgbtq-welcoming-hotels-split-croatia/","https://visitsplit.com/hr/accommodation/12","https://www.safirhoteli.hr/en/atrium-hotel-split/"]},
 {"name":"Radisson Blu Resort & Spa Split","aliases":"Radisson Blu Resort & Spa Split|Radisson Blu Resort Split","city":"split","description":"A large seafront resort at Trstenik with beach access, indoor and outdoor pools, spa, restaurants and broad room categories. It trades old-town immediacy for resort space and a direct Adriatic rhythm.","vibe":"contemporary seafront resort with broad wellness, beach and social facilities","tags":"luxury,relax,social","hours":"Reception operates 24 hours; beach, pools, spa, restaurants and bars follow seasonal schedules.","link":"https://www.radissonhotels.com/en-us/hotels/radisson-blu-resort-split-spa","location":"Put Trstenika 19, 21000 Split, Croatia","lat":43.502922,"lng":16.470196,"arrival":"Resort and event peaks can crowd the driveway and lifts; confirm parking, beach access and mobility routes before travel.","best":"Best for couples wanting sea views, pool and spa time with taxis or buses into the Pride and old-town circuit.","crowd":"LGBTQ+ leisure guests share a large mixed resort with couples, families, conferences and international groups.","dress":"Resort casual fits by day; restaurants become smart-casual and wet areas require the property's stated swimwear rules.","inclusion":"The property is listed in the current Hotels.com LGBTQIA-welcoming collection for Split.","basis":"Current LGBTQIA-welcoming catalogue evidence plus Radisson's live official address, access and service record.","class":"Five-star seafront resort and spa","coords":"Mapbox exact-address result for Put Trstenika 19, checked 2026-08-27.","sources":["https://www.hotels.com/en/de1634348-th21/lgbtq-welcoming-hotels-split-croatia/","https://www.radissonhotels.com/en-us/hotels/radisson-blu-resort-split-spa"]},
 {"name":"Hotel Luxe Split","aliases":"Hotel Luxe Split|Hotel Luxe","city":"split","description":"A colourful boutique hotel near the ferry port, railway station and Diocletian's Palace, with breakfast, compact wellness and contemporary rooms. Its practical transport position suits short queer city stays and island connections.","vibe":"bright boutique base joining ferry convenience, contemporary design and compact wellness","tags":"cultural,cozy,relax","hours":"Reception operates daily; breakfast, sauna, gym, parking and massage use current hotel schedules.","link":"https://hotelluxesplit.com/","location":"Ulica kralja Zvonimira 6, 21000 Split, Croatia","lat":43.506485,"lng":16.443751,"arrival":"Port and ferry traffic can complicate the final approach; confirm parking and luggage access before entering the centre.","best":"Best for travellers arriving by ferry, bus or rail who want the palace and central Pride locations within a short walk.","crowd":"Queer couples and independent travellers mix with island-hoppers, cruise visitors and design-oriented city-break guests.","dress":"Everyday coastal city wear fits the informal boutique setting; wellness areas maintain their own clothing rules.","inclusion":"Current specialist queer-travel coverage recommends Hotel Luxe to gay visitors, supported by an active official hotel record.","basis":"Specialist LGBTQ travel recommendation combined with the hotel's direct address, operation and facility information.","class":"Four-star contemporary boutique hotel","coords":"Mapbox exact-address result for Kralja Zvonimira 6, checked 2026-08-27.","sources":["https://www.theglobetrotterguys.com/gay-split-croatia-travel/","https://hotelluxesplit.com/index.php/en/contact"]},
 {"name":"Cornaro Hotel","aliases":"Cornaro Hotel|Cornaro Hotel Split","city":"split","description":"A central five-star hotel beside the old-town walls with 24-hour operation, rooftop bar, wellness, restaurant and more than 150 rooms following its 2025-26 reconstruction. It gives direct walking access to Pride assembly and cultural venues.","vibe":"central contemporary luxury with rooftop views, wellness and immediate palace access","tags":"luxury,cultural,social","hours":"Open 24/7 year-round; rooftop, restaurant, wellness and parking follow current schedules and reservations.","link":"https://www.cornarohotel.com/","location":"Sinjska ulica 6, 21000 Split, Croatia","lat":43.510334,"lng":16.439384,"arrival":"The historic-centre edge and reconstruction-era logistics make garage, drop-off and room location worth confirming directly.","best":"Best for first-time visitors wanting a polished full-service stay within minutes of central Pride and old-town activity.","crowd":"LGBTQ+ couples, luxury leisure travellers, small groups and conference guests share a large central mainstream hotel.","dress":"Polished resort-city clothing fits the rooftop and restaurant; there is no published queer-specific appearance gate.","inclusion":"Cornaro appears in current LGBTQIA-welcoming Split accommodation listings; the classification does not imply queer ownership.","basis":"Current inclusion-labelled catalogue plus active official hotel, reconstruction and exact-address information.","class":"Five-star central lifestyle hotel","coords":"Mapbox exact-address result for Sinjska ulica 6, checked 2026-08-27.","sources":["https://www.hotels.com/en/de1634348-th21/lgbtq-welcoming-hotels-split-croatia/","https://www.cornarohotel.com/"]},

 {"name":"SŌZŌ Hotel","aliases":"SŌZŌ Hotel|SOZO Hotel|Sōzō Hôtel","city":"nantes","description":"A 24-room boutique hotel built inside a converted nineteenth-century chapel opposite the Jardin des Plantes, retaining stone, stained glass and a dramatic high nave. It offers a distinctive calm alternative near the station.","vibe":"architectural chapel hotel combining stained-glass drama, boutique scale and spa calm","tags":"cultural,luxury,cozy","hours":"Reception operates daily; breakfast, hammam, sauna and treatments follow reservation and service schedules.","link":"https://www.sozohotel.fr/","location":"16 Rue Frédéric Cailliaud, 44000 Nantes, France","lat":47.219878,"lng":-1.541239,"arrival":"The protected chapel layout creates varied room geometry; request the correct accessible room and parking instructions before arrival.","best":"Best for couples seeking memorable architecture, station convenience and a quiet retreat from the later central bar circuit.","crowd":"Queer couples and design travellers mix with garden visitors, rail arrivals and special-occasion guests.","dress":"Relaxed boutique-hotel clothing fits; spa and treatment spaces have their own practical rules.","inclusion":"GayOut currently classifies SŌZŌ as LGBTQ+ friendly, while the hotel supplies current first-party operation and access details.","basis":"Current specialist LGBTQ+ hotel listing matched to the official hotel's address, scale and facility record.","class":"Four-star chapel boutique hotel","coords":"Mapbox exact-address result for Rue Frédéric Cailliaud 16, checked 2026-08-27.","sources":["https://www.gayout.com/fr/europe/france/nantes/hotels","https://www.sozohotel.fr/fr/contact-sozo.html"]},
 {"name":"Seven Urban Suites Nantes Centre","aliases":"Seven Urban Suites Nantes Centre|7 Urban Suites Nantes|Seven Urban Suites","city":"nantes","description":"A four-star hotel and aparthotel on Île de Nantes with rooms, longer-stay suites, bar, spa and a calm contemporary design. It is useful for guests needing more space near the convention district.","vibe":"contemporary aparthotel calm with longer-stay flexibility, spa and island access","tags":"relax,cozy,mixed","hours":"Reception operates daily; spa, breakfast, bar and check-in services follow current published schedules.","link":"https://www.7urbansuites.fr/","location":"10 Rue Konrad Adenauer, 44200 Nantes, France","lat":47.207814,"lng":-1.539544,"arrival":"Convention dates can pressure parking and reception; reserve spa, parking and an accessible suite independently of the room note.","best":"Best for longer stays, work trips and couples wanting suite space with quick transport into central queer nightlife.","crowd":"LGBTQ+ guests mix with conference travellers, families, business visitors and longer-stay city users.","dress":"Everyday city and work clothing fit; spa access uses separate attire and reservation rules.","inclusion":"Misterb&b's current community guide rates Seven Urban Suites as a highly recommended LGBTQ+-welcoming Nantes property.","basis":"Current gay-community hotel recommendation paired with direct first-party address, suite and wellness information.","class":"Four-star hotel and aparthotel","coords":"Mapbox exact-address result for Rue Konrad Adenauer 10, checked 2026-08-27.","sources":["https://www.misterbandb.com/gay-hotels/nantes","https://www.7urbansuites.fr/"]},
 {"name":"ibis Styles Nantes Centre Place Graslin","aliases":"ibis Styles Nantes Centre Place Graslin|Ibis Styles Nantes Graslin","city":"nantes","description":"A renovated 38-room design hotel themed around Nantes's Petit Beurre biscuit, set in the walkable Graslin district near theatres and Passage Pommeraye. It offers a playful central base without resort-scale facilities.","vibe":"playful compact design hotel rooted in Nantes culture and central walking access","tags":"cultural,cozy,mixed","hours":"Reception operates daily; breakfast and check-in follow current Accor schedules.","link":"https://all.accor.com/hotel/8464/index.en.shtml","location":"5 Rue du Chapeau Rouge, 44000 Nantes, France","lat":47.214968,"lng":-1.560332,"arrival":"The centre has restricted access and no private hotel parking or bicycle room; plan the nearby public garage before arrival.","best":"Best for visitors wanting Graslin, Commerce and the queer evening circuit on foot at a moderate chain-hotel scale.","crowd":"LGBTQ+ city-break visitors mix with families, theatre audiences, business guests and Accor travellers.","dress":"Informal city clothing suits the colourful economy-design concept; there is no published restrictive code.","inclusion":"Misterb&b's current Nantes hotel guide identifies this property as LGBTQ+-welcoming with community recommendation data.","basis":"Current gay-community recommendation plus Accor's live property, accessibility and exact GPS record.","class":"Three-star compact design hotel","coords":"Official Accor GPS 47.214968,-1.560332, checked 2026-08-27.","sources":["https://www.misterbandb.com/gay-hotels/nantes","https://all.accor.com/hotel/8464/index.en.shtml"]},
 {"name":"The Originals City Hôtel du Grand Monarque Nantes Gare","aliases":"The Originals City Hôtel du Grand Monarque Nantes Gare|Hotel du Grand Monarque Nantes|Grand Monarque Nantes","city":"nantes","description":"A straightforward two-star hotel near the cathedral, Jardin des Plantes and railway station, with a small scale and breakfast service. It provides a value-led alternative to Nantes's design hotels.","vibe":"simple welcoming station-side hotel focused on value, human service and cultural access","tags":"cozy,cultural,mixed","hours":"Reception and check-in follow the hotel's current schedule; published check-in begins at 15:00.","link":"https://www.theoriginalshotels.com/en/hotels/du-grand-monarque-nantes-train-station","location":"36 Rue Maréchal Joffre, 44000 Nantes, France","lat":47.221563,"lng":-1.547681,"arrival":"The compact hotel has fewer facilities than a full-service property; confirm late arrival, stairs and room access directly.","best":"Best for budget-conscious rail travellers prioritising the cathedral, gardens and a walk into central social life.","crowd":"Queer solo travellers and couples mix with rail users, cultural visitors and short-stay value guests.","dress":"Casual travel clothing fits the unpretentious breakfast-and-room format; no formal code is published.","inclusion":"Misterb&b currently names Grand Monarque as Nantes's most-booked LGBTQ+-friendly community choice.","basis":"Current gay-community booking recommendation plus The Originals' official active hotel and address record.","class":"Two-star independent-style city hotel","coords":"Mapbox exact-address result for Rue Maréchal Joffre 36, checked 2026-08-27.","sources":["https://www.misterbandb.com/gay-hotels/nantes","https://www.theoriginalshotels.com/en/hotels/du-grand-monarque-nantes-train-station"]},

 {"name":"BOMA easy living hotel","aliases":"BOMA easy living hotel|BOMA Hotel|Boma Hotel Strasbourg","city":"strasbourg","description":"A 103-room four-star lifestyle hotel on Rue du 22 Novembre with colourful interiors, restaurant, cocktail bar, fitness and central access between the station and Petite France. Its specialist approval makes the queer-welcome claim unusually direct.","vibe":"colourful central lifestyle hotel with cocktails, local energy and polished easy-living design","tags":"social,cultural,luxury","hours":"Reception operates 24 hours; restaurant, bar, fitness and room service maintain separate schedules.","link":"https://www.boma-hotel.com/en/?lang=en","location":"7 Rue du 22 Novembre, 67000 Strasbourg, France","lat":48.582837,"lng":7.741149,"arrival":"Pedestrian-centre and tram conditions affect driving; confirm the recommended garage and accessible arrival route.","best":"Best for guests wanting a direct specialist-approved stay between central sights, La Station and queer evening venues.","crowd":"LGBTQ+ couples and solo visitors mix with design travellers, business guests and local bar or restaurant customers.","dress":"Colourful city casual fits the lifestyle concept; the restaurant and cocktail bar lean polished without a restrictive code.","inclusion":"TravelGay actively approves BOMA and identifies LGBTQ-friendly management, accepted community guests and a welcoming experience.","basis":"Current specialist approval paired with the official hotel and Strasbourg destination accommodation records.","class":"Four-star lifestyle hotel","coords":"Mapbox exact-address result for Rue du 22 Novembre 7, checked 2026-08-27.","sources":["https://www.travelgay.com/gay-strasbourg-hotels","https://www.boma-hotel.com/en/?lang=en"]},
 {"name":"Hôtel Rohan Strasbourg","aliases":"Hôtel Rohan Strasbourg|Hotel Rohan Strasbourg|Hotel Rohan","city":"strasbourg","description":"A four-star hotel immediately beside the cathedral in the pedestrian old city, with individually styled rooms, lounge and direct access to Strasbourg's central cultural network. It is smaller and more historic in feel than the large chain hotels.","vibe":"cathedral-side boutique comfort with historic-centre intimacy and immediate walking access","tags":"cultural,cozy,luxury","hours":"Reception operates daily; breakfast, lounge and arrival services follow current hotel schedules.","link":"https://www.hotel-rohan.com/","location":"17-19 Rue du Maroquin, 67000 Strasbourg, France","lat":48.580887,"lng":7.750457,"arrival":"The pedestrian old city and Crit'Air rules require tram, approved vehicle or the hotel's current access instructions.","best":"Best for couples prioritising cathedral atmosphere and short walks to La Station and Canapé Queer.","crowd":"Queer leisure guests mix with heritage travellers, couples and international cathedral visitors.","dress":"Relaxed smart-casual fits the boutique public rooms; no identity-specific code is published.","inclusion":"TravelGay currently lists Hôtel Rohan as approved with LGBTQ-friendly management and accepted community guests.","basis":"Current specialist approval plus direct official address, transport and active hotel information.","class":"Four-star historic-centre boutique hotel","coords":"Mapbox exact-address result for Rue du Maroquin 17, checked 2026-08-27.","sources":["https://www.travelgay.com/gay-strasbourg-hotels","https://www.hotel-rohan.com/fr/acceder-a-lhotel/"]},
 {"name":"Hôtel Cour du Corbeau Strasbourg – MGallery","aliases":"Hôtel Cour du Corbeau Strasbourg – MGallery|Cour du Corbeau Strasbourg|Hotel Cour du Corbeau","city":"strasbourg","description":"A high-end MGallery hotel in a restored Renaissance inn dating to 1580, organised around a timbered courtyard near the cathedral. Its architecture creates a romantic, heritage-heavy stay rather than a social party hotel.","vibe":"Renaissance courtyard luxury with intimate heritage detail and river-edge calm","tags":"luxury,cultural,cozy","hours":"Reception operates daily; breakfast, bar, valet and guest services use current hotel schedules.","link":"https://www.cour-corbeau.com/en/","location":"6-8 Rue des Couples, 67000 Strasbourg, France","lat":48.579174,"lng":7.752387,"arrival":"The hotel has no private garage and uses valet to a nearby public facility; current quay works can alter vehicle routing.","best":"Best for couples seeking architectural romance close to Canapé Queer without choosing a nightlife-led property.","crowd":"LGBTQ+ couples and special-occasion guests mix with luxury heritage travellers and international visitors.","dress":"Polished city clothing suits the historic lounge and courtyard; ordinary guest access has no published restrictive code.","inclusion":"GayOut's current Strasbourg guide classifies Cour du Corbeau as LGBTQ+-welcoming with a fresh 2026 status.","basis":"Current specialist LGBTQ+ listing matched to MGallery's active first-party address and arrival information.","class":"Five-star Renaissance heritage hotel","coords":"Mapbox exact-address result for Rue des Couples 6, checked 2026-08-27.","sources":["https://www.gayout.com/europe/france/strasbourg/hotels","https://www.cour-corbeau.com/en/location/"]},
 {"name":"Maison Rouge Strasbourg Hotel & Spa","aliases":"Maison Rouge Strasbourg Hotel & Spa|Maison Rouge Strasbourg|Maison Rouge Hotel Spa Autograph Collection","city":"strasbourg","description":"A 131-room five-star Autograph Collection hotel near Place Kléber with 1920s Art Deco references, restaurant and a reservable spa. Its pedestrian heart-of-city location works for a polished cultural weekend.","vibe":"Art Deco city luxury combining central pedestrian access, gastronomy and reservable spa calm","tags":"luxury,cultural,relax","hours":"Reception operates daily; spa access requires advance booking and is restricted to guests aged 16 and over.","link":"https://www.maison-rouge.com/en/","location":"4 Rue des Francs-Bourgeois, 67000 Strasbourg, France","lat":48.582120,"lng":7.746016,"arrival":"The pedestrian low-emission centre requires planned parking or tram access; Christmas-market restrictions change the nearest garage.","best":"Best for couples wanting spa time, Place Kléber and an easy walk across the complete central queer network.","crowd":"LGBTQ+ couples and luxury visitors mix with Marriott guests, spa users and international cultural travellers.","dress":"Smart-casual clothing suits the Art Deco public rooms; spa and treatment areas maintain separate rules.","inclusion":"Hotels.com includes Maison Rouge in its current LGBTQIA-welcoming Strasbourg collection.","basis":"Current inclusion-labelled catalogue evidence paired with the hotel's official active address, access and spa details.","class":"Five-star Art Deco luxury hotel and spa","coords":"Mapbox exact-address result for Rue des Francs-Bourgeois 4, checked 2026-08-27.","sources":["https://fr.hotels.com/de1745048-th21/hotel-lgbtq-strasbourg-et-environs-france/","https://www.maison-rouge.com/acces-contacts/"]},

 {"name":"ibis Mérida","aliases":"ibis Mérida|Ibis Merida|ibis Merida","city":"merida","description":"A practical Accor hotel near Paseo de Montejo and the international convention centre with accessible rooms, restaurant and an economy-city format. Yucatán's tourism authority specifically identifies ibis hotels as inclusion and diversity partners.","vibe":"straightforward inclusive city hotel with Paseo access, accessibility and predictable service","tags":"mixed,service,cozy","hours":"Reception operates 24 hours; restaurant, breakfast and other services follow current Accor schedules.","link":"https://all.accor.com/hotel/6928/index.en.shtml","location":"Calle 58A 495, Colonia Centro, 97000 Mérida, Yucatán, Mexico","lat":20.988889,"lng":-89.617973,"arrival":"The convention area can be busy during events; reserve one of the adapted rooms directly and confirm parking arrangements.","best":"Best for value-conscious travellers wanting a documented inclusive chain partner near Paseo de Montejo.","crowd":"LGBTQ+ guests mix with convention delegates, business travellers, families and domestic city visitors.","dress":"Casual city clothing fits the economy hotel; there is no published appearance code.","inclusion":"Yucatán's official LGBTQ tourism page identifies ibis hotels as active inclusion and diversity allies; Hotels.com also labels this property LGBTQ+ friendly.","basis":"Official destination inclusion statement reinforced by current first-party hotel and property-level welcome records.","class":"Three-star inclusive economy hotel","coords":"Official Accor GPS 20.988889,-89.617973, checked 2026-08-27.","sources":["https://yucatan.travel/turismo-lgbtq/","https://all.accor.com/hotel/6928/index.en.shtml","https://www.hotels.com/en/ho326752/ibis-merida-merida-mexico/"]},
 {"name":"Ochenta y Dos Bed & Breakfast & Spa","aliases":"Ochenta y Dos Bed & Breakfast & Spa|Ochenta y Dos|Ochenta y Dos B&B","city":"merida","description":"A four-suite, adults-only and LGBTQ+-owned bed-and-breakfast with breakfast, pool, steam room and spa features near the Santiago district. Its host-led scale offers direct community identity rather than corporate inclusion branding.","vibe":"intimate queer-owned adults-only home with courtyard pool, spa and personal hosting","tags":"cozy,relax,social","hours":"Arrival is arranged directly and reception is not open 24 hours; confirm check-in before travel.","link":"https://meridabnb.com/","location":"Calle 82 #467C, Centro, 97000 Mérida, Yucatán, Mexico","lat":20.978945,"lng":-89.635438,"arrival":"The private small-property format requires advance arrival coordination; the official listing warns it is not suitable for limited mobility.","best":"Best for adults seeking a genuinely queer-owned stay, host contact and quiet pool time rather than chain anonymity.","crowd":"Queer couples and solo adults, especially gay travellers, share a very small guesthouse with the resident hosts and rescue dogs.","dress":"Relaxed home and pool clothing fits; respect shared-space, rooftop smoking and adults-only house rules.","inclusion":"GayCities identifies Ochenta y Dos as LGBTQ+-owned, while its official site emphasises a safe adult home and names the resident hosts.","basis":"Direct queer-ownership specialist evidence combined with current first-party operation, address and access limitations.","class":"Queer-owned adults-only boutique bed-and-breakfast","coords":"Mapbox exact-address result for Calle 82 #467C, checked 2026-08-27.","sources":["https://merida.gaycities.com/hotels","https://meridabnb.com/"]},
 {"name":"Casa Lecanda Boutique Hotel","aliases":"Casa Lecanda Boutique Hotel|Casa Lecanda","city":"merida","description":"An adults-only luxury boutique hotel in a restored Centro residence with seven rooms, gardens, patios and pool. Its quiet scale suits couples who prefer privacy and local architecture over a large social resort.","vibe":"serene adults-only colonial boutique retreat with gardens, patios and highly personal service","tags":"luxury,cozy,relax","hours":"Reception and arrival follow direct booking arrangements; availability is limited by the seven-room scale.","link":"https://www.casalecanda.com/en/","location":"Calle 47 #471 between 54 and 56, Centro, 97000 Mérida, Yucatán, Mexico","lat":20.974940,"lng":-89.617640,"arrival":"The restored-house layout and limited inventory make mobility needs, airport transfer and arrival time important to confirm personally.","best":"Best for queer couples seeking discretion, architectural calm and walking access to Centro and Paseo de Montejo.","crowd":"LGBTQ+ couples mix with adult luxury travellers, honeymooners and design-focused guests in a quiet seven-room setting.","dress":"Relaxed polished resort clothing fits the patios and pool; there is no published identity-based appearance rule.","inclusion":"GayCities currently lists Casa Lecanda as mixed gay/straight and gay-friendly, without claiming queer ownership.","basis":"Current specialist community listing paired with direct official adults-only, address and room-scale information.","class":"Adults-only luxury colonial boutique hotel","coords":"Published OpenStreetMap/GeoNames position 20.97494,-89.61764 checked against the official address.","sources":["https://merida.gaycities.com/hotels","https://www.casalecanda.com/contacto","https://mapcarta.com/32801664"]},
 {"name":"Rosas & Xocolate Boutique Hotel and Spa","aliases":"Rosas & Xocolate Boutique Hotel and Spa|Rosas y Xocolate|Rosas & Xocolate","city":"merida","description":"A seventeen-room boutique hotel occupying two restored pink French-style mansions on Paseo de Montejo, with restaurant, spa and private outdoor Jacuzzis. It combines high-design romance with a highly visible central address.","vibe":"romantic pink-mansion design hotel with private Jacuzzis, spa and destination dining","tags":"luxury,cultural,relax","hours":"Reception operates daily; restaurant, spa, events and treatments require current schedules or reservations.","link":"https://www.rosasandxocolate.com/","location":"Paseo de Montejo 480, Centro, 97000 Mérida, Yucatán, Mexico","lat":20.978910,"lng":-89.618590,"arrival":"Paseo traffic and a historic-mansion layout make drop-off, parking and accessible-room confirmation important.","best":"Best for couples wanting expressive design, private outdoor bathing and immediate Paseo de Montejo access.","crowd":"Queer couples, romantic leisure guests, design travellers, restaurant diners and event guests share the property.","dress":"Stylish resort and smart-casual clothing suits the restaurant and public mansion rooms; pool and spa rules apply separately.","inclusion":"GayCities lists Rosas & Xocolate as a mixed gay/straight welcoming hotel in Mérida.","basis":"Current specialist community listing combined with active official hotel, address, room and hospitality records.","class":"Luxury design boutique hotel and spa","coords":"Published OpenStreetMap position 20.97891,-89.61859 matches the official Paseo de Montejo 480 address.","sources":["https://merida.gaycities.com/hotels","https://www.rosasandxocolate.com/","https://mapcarta.com/N6037892585"]},

 {"name":"Axel Hotel San Sebastián","aliases":"Axel Hotel San Sebastián|Axel Hotel San Sebastian|Axel San Sebastian","city":"san_sebastian","description":"A 100-room adults-only Axel designed specifically around LGBTQIA+ hospitality, with rooftop pool, spa, gym and explicit respect-and-safety house principles. It is the city's clearest community-focused hotel rather than merely a friendly mainstream stay.","vibe":"confident LGBTQIA-focused adults-only hotel with rooftop, wellness and expressive social energy","tags":"social,luxury,relax","hours":"Reception operates 24 hours; rooftop 10:00-20:00, gym 24 hours and spa services follow current schedules.","link":"https://www.axelhotels.com/en/axel-hotel-san-sebastian/hotel","location":"Amara Kalea 26, 20006 Donostia / San Sebastián, Spain","lat":43.313883,"lng":-1.984812,"arrival":"On-site parking is limited; reserve it or use the Easo agreement, and book the included spa slot before arrival.","best":"Best for adults wanting the city's strongest explicit LGBTQIA identity, social rooftop and wellness close to Centro.","crowd":"LGBTQIA+ adults form the intended core alongside open-minded non-LGBTQ guests, couples and wellness users.","dress":"Expressive personal style is welcomed; pool and wellness have practical attire while respect and consent are stated house rules.","inclusion":"Axel calls itself the first hotel chain for the LGBTQIA community, and the Basque Government describes this property as designed especially for LGBTIQ guests.","basis":"First-party community mission and house rules reinforced by the official Basque accommodation registry.","class":"Four-star LGBTQIA-focused adults-only hotel","coords":"Mapbox exact-address result for Amara 26, checked 2026-08-27.","sources":["https://www.axelhotels.com/en/axel-hotel-san-sebastian/hotel","https://www.euskadi.eus/gobierno-vasco/-/es/alojamientos/axel-san-sebastian/"]},
 {"name":"Intelier Villa Katalina","aliases":"Intelier Villa Katalina|Hotel Intelier Villa Katalina|Villa Katalina Hotel","city":"san_sebastian","description":"A three-star boutique hotel beside Buen Pastor Cathedral with compact contemporary rooms and locally focused breakfast, less than ten minutes from La Concha. It is a convenient urban stay rather than a destination resort.","vibe":"bright cathedral-side boutique hotel focused on walkability, local breakfast and compact comfort","tags":"cultural,cozy,mixed","hours":"Reception operates daily; breakfast and arrival follow current Intelier schedules.","link":"https://www.intelier.com/en/hotel-intelier-villa-katalina-san-sebastian/","location":"Hondarribia Kalea 42, 20006 Donostia / San Sebastián, Spain","lat":43.316653,"lng":-1.980742,"arrival":"Room shapes include compact and attic formats; select the exact room and confirm lift or luggage requirements before booking.","best":"Best for queer travellers prioritising La Concha, cathedral and central walking over hotel nightlife.","crowd":"LGBTQ+ couples and solo visitors mix with food travellers, beach visitors and short-stay city guests.","dress":"Casual coastal city clothing suits the small property; no restrictive appearance policy is published.","inclusion":"Hotels.com currently includes Intelier Villa Katalina in its LGBTQIA-welcoming San Sebastián selection.","basis":"Current inclusion-labelled catalogue evidence paired with Intelier's direct address, room and service record.","class":"Three-star central boutique hotel","coords":"Mapbox exact-address result for Hondarribia 42, checked 2026-08-27.","sources":["https://www.hotels.com/es/de1651660-th21/lgbtq-hoteles-san-sebastian-espana/","https://www.intelier.com/en/hotel-intelier-villa-katalina-san-sebastian/location/"]},
 {"name":"Intelier Victoria","aliases":"Intelier Victoria|Hotel Intelier Victoria|Villa Victoria San Sebastian","city":"san_sebastian","description":"A small modern hotel near La Concha with terrace, breakfast café and contemporary rooms on San Bartolomé. Its calmer scale works for visitors who want beach and centre access without a party-led lobby.","vibe":"small contemporary La Concha base with terrace calm and highly walkable city access","tags":"cozy,relax,mixed","hours":"Reception and breakfast operate daily according to current Intelier schedules.","link":"https://www.intelier.com/hotel-intelier-victoria-san-sebastian/","location":"San Bartolomé Kalea 13, 20007 Donostia / San Sebastián, Spain","lat":43.315525,"lng":-1.985157,"arrival":"The compact centre property has limited public facilities; confirm luggage, late arrival and the selected room layout directly.","best":"Best for couples and solo travellers wanting a quiet room within minutes of La Concha and Centro.","crowd":"LGBTQ+ beach and food travellers mix with couples, independent visitors and short-break guests.","dress":"Relaxed coastal city clothes fit the terrace and breakfast room; no formal code is published.","inclusion":"Hotels.com's current San Sebastián collection labels Intelier Victoria LGBTQIA-welcoming.","basis":"Current inclusion-labelled catalogue entry matched to Intelier's active official address and facility record.","class":"Two-star modern boutique city hotel","coords":"Mapbox exact-address result for San Bartolomé 13, checked 2026-08-27.","sources":["https://da.hotels.com/de1651660-th21/lgbtq-venligt-hoteller-san-sebastian-spanien/","https://www.intelier.com/hotel-intelier-victoria-san-sebastian/"]},
 {"name":"Hotel Antik San Sebastián","aliases":"Hotel Antik San Sebastián|Hotel Antik San Sebastian|Antik San Sebastian","city":"san_sebastian","description":"A modern four-star hotel in the Antiguo area with larger-room practicality and road access west of the centre. It suits drivers and visitors who value a quieter residential base over immediate Parte Vieja nightlife.","vibe":"quiet contemporary Antiguo hotel with practical road access and residential-city rhythm","tags":"relax,mixed,cozy","hours":"Reception operates daily; breakfast, parking and check-in follow current hotel schedules.","link":"https://hotelantiksansebastian.com/en/","location":"Zarautz Kalea 120, 20018 Donostia / San Sebastián, Spain","lat":43.302881,"lng":-2.003827,"arrival":"The location is outside the central walking core; confirm parking and use city buses or taxis for late evening movement.","best":"Best for travellers arriving by car, needing quieter rooms or combining Donostia with wider Basque road trips.","crowd":"LGBTQ+ guests mix with families, road travellers, business visitors and residential-district city guests.","dress":"Everyday city clothing fits the practical hotel; no appearance restrictions are published.","inclusion":"Hotels.com's current LGBTQIA-welcoming San Sebastián guide identifies Hotel Antik as an inclusive option.","basis":"Current inclusion-labelled hotel catalogue paired with the property's official active business and exact-address record.","class":"Four-star residential-district city hotel","coords":"Mapbox exact-address result for Zarautz 120, checked 2026-08-27.","sources":["https://www.hotels.com/de1651660-th21/lgbtq-welcoming-hotels-san-sebastian-spain/","https://hotelantiksansebastian.com/en/legal-advice"]}
]
$qa_hotels$) h(name text,aliases text,city text,description text,vibe text,tags text,hours text,link text,location text,lat double precision,lng double precision,arrival text,best text,crowd text,dress text,inclusion text,basis text,class text,coords text,sources jsonb)
), hotels as (
 select h.*,string_to_array(h.tags,',')::text[] approved_tags,
  jsonb_build_object(
   'queue_wait',arrival,'best_nights',best,'crowd_mix',crowd,'dress_code',dress,
   'staff_inclusivity',inclusion,'inclusion_basis',basis,'hotel_class',class,
   'coordinate_source',coords,'source_urls',sources,
   'research_status','current_lgbtq_source_plus_active_official_hotel_source',
   'updated_at','2026-08-27T00:00:00Z'
  ) intel
 from raw_hotels h
), updated as (
 update public.places p set
  name=h.name,type='hotel',description=h.description,vibe=h.vibe,vibe_tags=h.approved_tags,
  hours=h.hours,link=h.link,location=h.location,lat=h.lat,lng=h.lng,
  venue_intel=coalesce(p.venue_intel,'{}'::jsonb)||h.intel,
  seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from hotels h
 where lower(trim(p.city))=h.city and lower(trim(p.name)) in (
  select lower(trim(alias_name)) from unnest(string_to_array(h.aliases,'|')) alias_name
 ) returning p.id
)
insert into public.places(name,city,type,description,vibe,vibe_tags,hours,link,location,lat,lng,venue_intel,seo_indexable,seo_quality_status,updated_at)
select h.name,h.city,'hotel',h.description,h.vibe,h.approved_tags,h.hours,h.link,h.location,h.lat,h.lng,h.intel,true,'approved',timezone('utc',now())
from hotels h where not exists (
 select 1 from public.places p where lower(trim(p.city))=h.city and lower(trim(p.name)) in (
  select lower(trim(alias_name)) from unnest(string_to_array(h.aliases,'|')) alias_name
 )
);

select public.qa_refresh_city_seo_status(slug)
from (values('split'),('nantes'),('strasbourg'),('merida'),('san_sebastian')) v(slug);

commit;

select lower(trim(city)) city,count(*) filter(where type='hotel') hotel_count,
 count(*) filter(where type='hotel')>=4 target_met
from public.places
where lower(trim(city)) in('split','nantes','strasbourg','merida','san_sebastian')
group by lower(trim(city)) order by lower(trim(city));

select lower(trim(city)) city,count(*) batch_rows,
 count(*) filter(where lat between -90 and 90 and lng between -180 and 180
  and char_length(coalesce(venue_intel->>'queue_wait',''))>=24
  and char_length(coalesce(venue_intel->>'best_nights',''))>=24
  and char_length(coalesce(venue_intel->>'crowd_mix',''))>=24
  and char_length(coalesce(venue_intel->>'dress_code',''))>=24
  and char_length(coalesce(venue_intel->>'staff_inclusivity',''))>=24
  and jsonb_array_length(coalesce(venue_intel->'source_urls','[]'::jsonb))>=2) complete_rows
from public.places
where type='hotel' and venue_intel->>'updated_at'='2026-08-27T00:00:00Z'
 and lower(trim(city)) in('split','nantes','strasbourg','merida','san_sebastian')
group by lower(trim(city)) order by lower(trim(city));
