-- Queer Atlas: Asia hotel batch 1
-- Siem Reap, Shanghai, Hong Kong, New Delhi, Bali, Jakarta, Kyoto, Tokyo,
-- Kuala Lumpur, Manila, Seoul, Singapore, Phuket and Ho Chi Minh City.
-- Three researched LGBTQ+-focused or LGBTQ+-welcoming hotels per destination.
-- Editorial and source check: 2026-08-23.
--
-- No ratings or review totals are manufactured. Inclusion is based on either
-- a first-party LGBTQ+ statement/operation or a current specialist LGBTQ+
-- travel listing. Coordinates identify the hotel property, never a city centre.
-- Safe to run repeatedly; existing rows are matched by city + hotel name.

begin;

alter table if exists public.places
  add column if not exists venue_intel jsonb not null default '{}'::jsonb;

with raw_hotels as (
  select * from jsonb_to_recordset($hotels$
[
 {"name":"MEN's Resort & Spa","city":"siem_reap","description":"An explicitly gay, male-only boutique resort in Siem Reap with ten rooms, saltwater pool, gym and included access to its men's sauna and spa. This is a genuine queer specialist stay rather than a general hotel inferred to be friendly.","vibe":"intimate gay men's resort with pool and sauna social life","tags_csv":"men_only,relax,social","hours":"Hotel accommodation with sauna and spa facilities; confirm reception, check-in and current facility hours directly.","link":"https://www.mens-resort.com/","location":"Wat Bo Street, Wat Polanka area, Siem Reap 171201, Cambodia","lat":13.3627557,"lng":103.8659704,"arrival":"Small-resort arrival is best coordinated in advance, especially for airport transfers or late check-in.","best":"Gay men wanting a self-contained queer stay with pool, gym and sauna access close to central Siem Reap.","audience":"Male-only hotel guests and gay men using the associated wellness facilities; check current visitor rules.","dress":"Resort casual; pool, sauna and spa areas have their own practical clothing and conduct rules.","inclusion":"The property describes itself as a gay hotel and operates specifically for men.","basis":"First-party gay hotel positioning plus current Travel Gay gay-owned/gay-managed listing.","class":"Gay men's boutique resort and spa","coord":"OpenStreetMap hotel-property point checked against the published Wat Bo/Wat Polanka address.","sources":["https://www.mens-resort.com/","https://www.travelgay.com/gay-siem-reap-hotels"]},
 {"name":"Rambutan Hotel & Resort Siem Reap","city":"siem_reap","description":"A gay-owned and gay-managed pair of boutique properties around saltwater pools near Wat Damnak and the Old Market. Rambutan combines a strongly queer guest mix with a broader welcoming social-enterprise model.","vibe":"gay-owned Khmer-style oasis near the Old Market","tags_csv":"social,relax,mixed","hours":"Hotel reception and accommodation operate daily; confirm restaurant, massage, pool and airport-transfer schedules directly.","link":"https://rambutansiemreap.com/","location":"Rambutan Lane, Phum Wat Damnak, Kum Sala Komreuk, Krom 10, Siem Reap 17259, Cambodia","lat":13.35137939,"lng":103.85488892,"arrival":"The hotel sits in a pedestrian lane; share transfer and luggage plans before arrival.","best":"Queer travellers wanting a gay-owned central base with Old Market access and a relaxed pool environment.","audience":"A high proportion of gay guests alongside LGBTQ+ friends, couples and other respectful adult travellers.","dress":"Relaxed tropical clothing works; pool and restaurant spaces use ordinary resort etiquette.","inclusion":"Travel Gay identifies Rambutan as gay-owned and managed, and the current booking record confirms the live property.","basis":"Current specialist gay-owned listing plus official property and booking records.","class":"Gay-owned boutique hotel and resort","coord":"Current booking-engine GeoCoordinates checked against the official Rambutan Lane address.","sources":["https://rambutansiemreap.com/contact-us/","https://www.travelgay.com/gay-siem-reap-hotels"]},
 {"name":"Hotel Be Angkor","city":"siem_reap","description":"A tiny art-led hotel on The Passage beside Siem Reap's Old Market. Current LGBTQ+ specialist coverage identifies it as gay-friendly, making it a compact alternative to the city's larger pool resorts.","vibe":"artistic micro-hotel in the middle of Old Market life","tags_csv":"cozy,cultural,mixed","hours":"Small hotel accommodation; confirm live reception, check-in and luggage arrangements before arrival.","link":"https://www.travelgay.com/siem-reap-gay-guesthouses","location":"The Passage, Old Market Area, Siem Reap 171000, Cambodia","lat":13.3543032,"lng":103.854615,"arrival":"With only a few rooms, arrival instructions and late check-in should be confirmed directly.","best":"Travellers prioritising the Old Market, walkability and local art over full resort facilities.","audience":"LGBTQ+ couples, solo visitors and general culture-led guests in a very small mixed hotel.","dress":"No hotel dress code; everyday tropical city clothing is appropriate.","inclusion":"Current Travel Gay coverage describes Hotel Be Angkor as gay-friendly.","basis":"Current LGBTQ+ specialist guesthouse listing and verified live property location.","class":"Small art boutique hotel","coord":"OpenStreetMap hotel-property point checked against The Passage location.","sources":["https://www.travelgay.com/siem-reap-gay-guesthouses","https://www.travelgay.com/gay-siem-reap-hotels"]},

 {"name":"The Langham Shanghai Xintiandi","city":"shanghai","description":"A five-star hotel beside Xintiandi with spa, pool and high-service dining. Travel Gay currently includes it among Shanghai's LGBTQ+-welcoming luxury hotels, with strong access to the former French Concession.","vibe":"refined Xintiandi luxury with polished city energy","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; spa, pool, restaurants and bars use current schedules.","link":"https://www.langhamhotels.com/en/the-langham/shanghai/","location":"99 Madang Road, Huangpu District, Shanghai 200021, China","lat":31.2237257,"lng":121.4698926,"arrival":"Concierge-led arrival; reserve spa and destination dining separately, especially on holidays.","best":"Xintiandi, central sightseeing and discreet access toward Shanghai's changing queer social scene.","audience":"International couples, business travellers, luxury guests and LGBTQ+ visitors in a mixed hotel.","dress":"Smart-casual suits dining and bars; spa and pool areas have practical rules.","inclusion":"Current Travel Gay luxury coverage documents the property as welcoming to LGBTQ+ travellers.","basis":"Current Travel Gay Shanghai luxury listing plus official hotel information.","class":"5-star luxury hotel","coord":"OpenStreetMap hotel-building point checked against the official 99 Madang Road address.","sources":["https://www.travelgay.com/gay-shanghai-luxury-hotels","https://www.langhamhotels.com/en/the-langham/shanghai/discover/our-location/"]},
 {"name":"Park Hyatt Shanghai","city":"shanghai","description":"A high-rise luxury hotel inside the Shanghai World Financial Center in Lujiazui, with skyline rooms, pool and spa. Travel Gay currently includes it as an LGBTQ+-welcoming Shanghai luxury choice.","vibe":"serene sky-high luxury above Pudong's financial district","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; pool, spa, restaurants and lounges follow current schedules.","link":"https://www.hyatt.com/park-hyatt/en-US/shaph-park-hyatt-shanghai","location":"100 Century Avenue, Pudong New Area, Shanghai 200120, China","lat":31.2365768,"lng":121.5030406,"arrival":"The hotel occupies upper floors of a major tower; follow its dedicated arrival and lift directions.","best":"Skyline views, Lujiazui business and a quiet luxury retreat rather than immediate nightlife frontage.","audience":"LGBTQ+ couples, international business guests and luxury travellers in a broad mixed environment.","dress":"Smart-casual is suitable for lounges and restaurants; wellness spaces have separate rules.","inclusion":"Current LGBTQ+ specialist travel coverage lists the hotel as a welcoming luxury option.","basis":"Current Travel Gay Shanghai luxury listing plus official Hyatt property information.","class":"5-star high-rise luxury hotel","coord":"Shanghai World Financial Center building coordinate checked against the official 100 Century Avenue address.","sources":["https://www.travelgay.com/gay-shanghai-luxury-hotels","https://www.hyatt.com/park-hyatt/en-US/shaph-park-hyatt-shanghai"]},
 {"name":"Hotel Indigo Shanghai on the Bund","city":"shanghai","description":"A design-focused hotel on the south Bund with river views, rooftop dining and a contemporary local-art identity. It appears in Travel Gay's current Shanghai hotel selection for LGBTQ+ travellers.","vibe":"colourful Bund design stay with rooftop river views","tags_csv":"luxury,cultural,mixed","hours":"Hotel reception operates 24 hours; rooftop, restaurants, pool and gym follow current schedules.","link":"https://www.ihg.com/hotelindigo/hotels/us/en/shanghai/shgnb/hoteldetail","location":"585 Zhongshan East 2nd Road, Huangpu District, Shanghai 200010, China","lat":31.2281122,"lng":121.4956739,"arrival":"Bund traffic can slow vehicle arrival; rooftop dining should be reserved separately.","best":"Design travellers wanting Bund views and central cultural access with a quieter hotel base.","audience":"Couples, business visitors, design travellers and LGBTQ+ guests in a mixed boutique setting.","dress":"Creative city clothing works; rooftop dining is generally smart-casual.","inclusion":"Current Travel Gay coverage includes the property among Shanghai's welcoming hotel choices.","basis":"Current specialist LGBTQ+ travel listing plus official IHG information.","class":"Upscale design boutique hotel","coord":"OpenStreetMap hotel-building point checked against the official 585 Zhongshan South Road address.","sources":["https://www.travelgay.com/gay-shanghai-luxury-hotels","https://www.ihg.com/hotelindigo/hotels/us/en/shanghai/shgnb/hoteldetail"]},

 {"name":"Eaton HK","city":"hong_kong","description":"A culture-led Jordan hotel whose programming and public identity actively engage LGBTQ+ art, community and counterculture. The Terrible Baby venue, food hall and community spaces make this more than a generic friendly stay.","vibe":"queer-positive cultural hub with energetic Kowloon social spaces","tags_csv":"cultural,social,mixed","hours":"Hotel reception operates 24 hours; music, culture, dining, pool and event programmes use separate schedules.","link":"https://www.eatonworkshop.com/en-us/hong-kong/","location":"380 Nathan Road, Jordan, Kowloon, Hong Kong","lat":22.3080618,"lng":114.1718264,"arrival":"Public events can make the ground floors busy; hotel check-in remains separate from programme access.","best":"Queer culture, local food and Jordan access in a socially engaged hotel environment.","audience":"LGBTQ+ creatives, couples, artists, local event audiences and general international guests.","dress":"Expressive city style is welcome; programmed events publish any specific access rules.","inclusion":"Eaton's own cultural platform regularly centres LGBTQ+ creators and community programming.","basis":"First-party queer cultural programming plus current specialist LGBTQ+ hotel coverage.","class":"Culture-led lifestyle hotel","coord":"OpenStreetMap hotel-building point checked against the official 380 Nathan Road address.","sources":["https://www.eatonworkshop.com/en-us/hong-kong/","https://www.travelgay.com/gay-hong-kong-hotels"]},
 {"name":"W Hong Kong","city":"hong_kong","description":"A high-energy luxury hotel above Kowloon Station with rooftop pool, spa and direct Elements mall access. Travel Gay currently lists it as a gay-popular, LGBTQ+-welcoming Hong Kong choice.","vibe":"bold sky-high Kowloon luxury with a social rooftop","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; rooftop pool, spa, bar and restaurants follow current schedules.","link":"https://www.marriott.com/en-us/hotels/hkgwh-w-hong-kong/overview/","location":"1 Austin Road West, West Kowloon, Hong Kong","lat":22.3046362,"lng":114.1605933,"arrival":"Kowloon Station simplifies airport arrival; rooftop and event access are managed separately.","best":"Airport Express convenience, shopping and a polished social hotel with rapid cross-harbour links.","audience":"LGBTQ+ couples, fashion and nightlife travellers, business guests and a broad luxury crowd.","dress":"Fashionable casual fits the hotel; programmed events may set a specific code.","inclusion":"Current Travel Gay coverage identifies W Hong Kong as popular with gay guests and LGBTQ+-welcoming.","basis":"Current specialist LGBTQ+ travel listing plus official Marriott information.","class":"5-star W lifestyle hotel","coord":"OpenStreetMap hotel-property point checked against the official 1 Austin Road West address.","sources":["https://www.travelgay.com/gay-hong-kong-hotels","https://www.marriott.com/en-us/hotels/hkgwh-w-hong-kong/overview/"]},
 {"name":"Hotel ICON","city":"hong_kong","description":"An independent teaching and design hotel in Tsim Sha Tsui East with harbour views, pool and strong hospitality facilities. Travel Gay currently marks it Approved for LGBTQ+ customers.","vibe":"independent harbour-view design with serious service polish","tags_csv":"luxury,cultural,mixed","hours":"Hotel reception operates 24 hours; pool, spa, restaurants and shuttle services follow current schedules.","link":"https://www.hotel-icon.com/","location":"17 Science Museum Road, Tsim Sha Tsui East, Kowloon, Hong Kong","lat":22.3008025,"lng":114.1796535,"arrival":"Normal full-service arrival; reserve harbour-view dining and spa treatments separately.","best":"Tsim Sha Tsui culture and harbour access in a distinctive independent property.","audience":"Couples, design travellers, business guests and LGBTQ+ visitors in a mixed upscale crowd.","dress":"Smart-casual suits restaurants; pool and spa have practical rules.","inclusion":"The current Travel Gay Approved record documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official Hotel ICON information.","class":"5-star independent design hotel","coord":"OpenStreetMap hotel-building point checked against the official 17 Science Museum Road address.","sources":["https://www.travelgay.com/gay-hong-kong-hotels","https://www.hotel-icon.com/about-icon"]},

 {"name":"The LaLiT New Delhi","city":"new_delhi","description":"A central luxury hotel whose Kitty Su nightclub has a documented history of hosting and supporting Delhi's LGBTQ+ community. The hotel's own inclusion work gives it a stronger basis than directory proximity alone.","vibe":"central luxury with a concrete queer nightlife and advocacy link","tags_csv":"luxury,social,cultural","hours":"Hotel reception operates 24 hours; Kitty Su, spa, pool, restaurants and events use separate live schedules.","link":"https://www.thelalit.com/the-lalit-delhi/","location":"Barakhamba Avenue, Connaught Place, New Delhi 110001, India","lat":28.6314643,"lng":77.2271911,"arrival":"Hotel and nightclub entry are separate; confirm Kitty Su's current event, ID and door policy before travelling.","best":"Queer travellers wanting a central full-service hotel with a real link to Delhi's LGBTQ+ event history.","audience":"LGBTQ+ guests, business travellers, couples and a broad international luxury audience.","dress":"Hotel areas are smart-casual; Kitty Su events may publish a nightlife dress and ID policy.","inclusion":"The LaLiT and Kitty Su have publicly supported LGBTQ+ events, performers and employment inclusion.","basis":"First-party LGBTQ+ nightlife/community work plus current Travel Gay hotel coverage.","class":"5-star luxury hotel with nightclub","coord":"OpenStreetMap hotel-property point checked against the official Barakhamba Avenue address.","sources":["https://www.thelalit.com/the-lalit-delhi/location/","https://www.travelgay.com/new-delhi-hotels"]},
 {"name":"The Lodhi","city":"new_delhi","description":"A high-service luxury hotel on Lodhi Road with large rooms, spa, pool and destination dining. Travel Gay currently marks it Approved as a welcoming option for LGBTQ+ New Delhi travellers.","vibe":"quiet architectural luxury with strong wellness focus","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; spa, pool, restaurants and club facilities use current schedules.","link":"https://www.thelodhi.com/","location":"Lodhi Road, New Delhi 110003, India","lat":28.5915262,"lng":77.238125,"arrival":"Concierge-led arrival; reserve spa and dining separately and communicate accessibility needs early.","best":"A private, wellness-led luxury stay with central heritage access rather than nightlife at the door.","audience":"LGBTQ+ couples, international leisure travellers and business guests in a mixed luxury environment.","dress":"Smart-casual suits restaurants and public areas; wellness facilities use practical attire rules.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and a welcoming service standard.","basis":"Current Travel Gay Approved listing plus official Lodhi information.","class":"5-star luxury hotel","coord":"OpenStreetMap hotel-property point checked against the official Lodhi Road address.","sources":["https://www.travelgay.com/new-delhi-hotels","https://www.thelodhi.com/contact-us/"]},
 {"name":"The Oberoi New Delhi","city":"new_delhi","description":"A landmark luxury hotel beside Delhi Golf Club and Humayun's Tomb, with spa, pool and multiple restaurants. Its current Travel Gay Approved listing supplies the LGBTQ+-welcoming evidence.","vibe":"landmark Delhi luxury with calm, formal service","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; restaurants, spa and pool follow current schedules.","link":"https://www.oberoihotels.com/hotels-in-delhi/","location":"Dr Zakir Hussain Marg, New Delhi 110003, India","lat":28.5965326,"lng":77.239815,"arrival":"High-service hotel arrival; restaurant and wellness reservations should be made separately.","best":"Heritage sightseeing, quiet luxury and high-touch service away from denser nightlife areas.","audience":"LGBTQ+ couples, diplomats, business guests and international luxury travellers in a mixed hotel.","dress":"Smart-casual to formal clothing suits dining and lounges; pool and spa have separate rules.","inclusion":"Current Travel Gay Approved status documents acceptance of LGBTQ+ guests.","basis":"Current Travel Gay Approved listing plus official Oberoi property information.","class":"5-star luxury hotel","coord":"OpenStreetMap hotel-building point checked against the official Dr Zakir Hussain Marg address.","sources":["https://www.travelgay.com/new-delhi-hotels","https://www.oberoihotels.com/hotels-in-delhi/contact-us/"]},

 {"name":"Balinea Villa & Spa","city":"bali","description":"An eight-room gay resort in Kerobokan with private terraces, pool, jacuzzi and massage services. Its explicit gay-resort identity makes it the specialist queer stay in the Bali batch.","vibe":"small rainbow-bright gay villa resort with relaxed pool life","tags_csv":"social,relax,mixed","hours":"Boutique resort accommodation; confirm reception, massage, pool and visitor schedules directly.","link":"https://www.travelgay.com/gay-bali-hotels","location":"Jalan Merta Agung No. 11, Kerobokan Kelod, Badung, Bali 80361, Indonesia","lat":-8.671259,"lng":115.167229,"arrival":"Small-property arrival and airport transfers should be coordinated in advance.","best":"Queer travellers wanting an explicitly gay, intimate pool stay near Seminyak without a large-resort atmosphere.","audience":"Predominantly gay and LGBTQ+ adult guests with an explicitly welcoming resort identity.","dress":"Relaxed tropical resort wear; pool and shared-villa etiquette applies.","inclusion":"Current Travel Gay coverage explicitly describes Balinea as a gay resort.","basis":"Current specialist gay-resort listing plus verified address and hotel coordinates.","class":"Small gay villa resort and spa","coord":"Published hotel coordinates checked against Jalan Merta Agung No. 11.","sources":["https://www.travelgay.com/gay-bali-hotels","https://www.travelgay.com/bali_gay_resorts"]},
 {"name":"W Bali Seminyak","city":"bali","description":"A major beachfront luxury resort in Seminyak with expansive pools, spa, restaurants and a socially active calendar. Travel Gay currently includes it among Bali's LGBTQ+-welcoming luxury hotels.","vibe":"high-energy beachfront luxury with sunset social life","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; beach, pools, spa, bars and restaurants follow current schedules.","link":"https://www.marriott.com/en-us/hotels/dpswh-w-bali-seminyak/overview/","location":"Jalan Petitenget, Kerobokan, Seminyak, Bali 80361, Indonesia","lat":-8.6771681,"lng":115.1497352,"arrival":"Large-resort arrival is straightforward; reserve spa, dining and special events separately.","best":"Beachfront luxury, sunset energy and access to Seminyak's queer-popular visitor zone.","audience":"LGBTQ+ couples and groups, international resort travellers and a broad fashionable crowd.","dress":"Resort casual by day; bars and programmed events may lean fashionable.","inclusion":"Current Travel Gay luxury coverage presents W Bali as an LGBTQ+-welcoming resort.","basis":"Current specialist LGBTQ+ travel listing plus official Marriott information.","class":"5-star beachfront lifestyle resort","coord":"OpenStreetMap resort-property point checked against the official Petitenget address.","sources":["https://www.travelgay.com/gay-bali-luxury-hotels","https://www.marriott.com/en-us/hotels/dpswh-w-bali-seminyak/overview/"]},
 {"name":"THE HAVEN Bali Seminyak","city":"bali","description":"A large contemporary hotel on Jalan Raya Seminyak with pools, spa and practical access to Double Six Beach and Seminyak nightlife. Travel Gay currently marks it Approved for LGBTQ+ customers.","vibe":"easy urban-resort base between Seminyak beach and nightlife","tags_csv":"relax,social,mixed","hours":"Hotel reception operates 24 hours; pools, spa, dining and beach services use current schedules.","link":"https://thehavenbali.com/","location":"Jalan Raya Seminyak No. 500, Seminyak, Bali 80361, Indonesia","lat":-8.6965546,"lng":115.1682018,"arrival":"Standard resort check-in; Seminyak traffic makes advance transfer planning useful.","best":"Travellers balancing beach time, shopping and access toward Seminyak's LGBTQ+ nightlife.","audience":"Couples, families, groups and LGBTQ+ guests across a broad resort audience.","dress":"Tropical resort casual; pools, spa and dining areas apply their own practical guidance.","inclusion":"The current Travel Gay Approved record documents LGBTQ+ acceptance and a welcoming standard.","basis":"Current Travel Gay Approved listing plus official property information.","class":"Contemporary Seminyak resort hotel","coord":"OpenStreetMap hotel-property point checked against the official No. 500 address.","sources":["https://www.travelgay.com/gay-bali-hotels","https://thehavenbali.com/"]},

 {"name":"Hotel Indonesia Kempinski Jakarta","city":"jakarta","description":"A landmark luxury hotel at Bundaran HI with direct Grand Indonesia access, rooftop pool, spa and major dining venues. Travel Gay currently includes it in Jakarta's LGBTQ+-welcoming hotel selection.","vibe":"landmark Thamrin luxury at the centre of modern Jakarta","tags_csv":"luxury,massive,mixed","hours":"Hotel reception operates 24 hours; restaurants, spa, pool and mall access follow separate schedules.","link":"https://www.kempinski.com/en/hotel-indonesia","location":"Jalan M.H. Thamrin No. 1, Jakarta 10310, Indonesia","lat":-6.1952483,"lng":106.821907,"arrival":"Traffic and major events around Bundaran HI can slow arrival; reserve dining and spa separately.","best":"Central Jakarta shopping, business and high-service comfort with discreet city logistics.","audience":"LGBTQ+ couples, business travellers, families and international luxury guests in a mixed setting.","dress":"Smart-casual suits public areas and dining; wellness facilities have practical rules.","inclusion":"Current Travel Gay coverage includes the hotel as a welcoming Jakarta option.","basis":"Current specialist LGBTQ+ travel listing plus official Kempinski information.","class":"5-star landmark luxury hotel","coord":"OpenStreetMap hotel-property point checked against the official Thamrin No. 1 address.","sources":["https://www.travelgay.com/gay-jakarta-hotels","https://www.kempinski.com/en/hotel-indonesia"]},
 {"name":"Pullman Jakarta Indonesia","city":"jakarta","description":"A five-star Thamrin hotel opposite the landmark roundabout with restaurants, spa, pool and direct business-district access. It appears in Travel Gay's current Jakarta hotel recommendations.","vibe":"cosmopolitan Thamrin hub with energetic business-city rhythm","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; restaurants, bar, pool, spa and events follow current schedules.","link":"https://www.pullmanjakartaindonesia.com/","location":"Jalan M.H. Thamrin Kav. 59, Jakarta Pusat 10350, Indonesia","lat":-6.1932917,"lng":106.823796,"arrival":"Jakarta traffic is the main variable; plan airport and cross-city transfers with extra time.","best":"A central, transport-connected stay for shopping and business rather than visible dedicated queer nightlife.","audience":"LGBTQ+ guests, business travellers, couples and groups in a broad international city hotel.","dress":"Smart-casual works throughout; restaurants and events may set specific guidance.","inclusion":"Current LGBTQ+ specialist travel coverage lists Pullman among Jakarta's welcoming hotels.","basis":"Current Travel Gay Jakarta listing plus official Accor property and GPS records.","class":"5-star city hotel","coord":"Official Pullman GPS coordinates for the property.","sources":["https://www.travelgay.com/gay-jakarta-hotels","https://www.pullmanjakartaindonesia.com/"]},
 {"name":"Gran Melia Jakarta","city":"jakarta","description":"A resort-like luxury hotel in Kuningan with pool, spa, gardens and several restaurants. Travel Gay currently marks it Approved for LGBTQ+ customers in Jakarta.","vibe":"garden-framed urban luxury with calm resort facilities","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; pool, spa, restaurants and event spaces follow current schedules.","link":"https://www.melia.com/en/hotels/indonesia/jakarta/gran-melia-jakarta","location":"Jalan H.R. Rasuna Said Kav. X-0, Kuningan, Jakarta 12950, Indonesia","lat":-6.2350823,"lng":106.830278,"arrival":"Allow significant transfer time in peak Jakarta traffic; dining and spa need separate reservations.","best":"A quieter high-service Kuningan base with pool and gardens for business or leisure stays.","audience":"Couples, families, business groups and LGBTQ+ travellers in a broad luxury environment.","dress":"Smart-casual suits restaurants; pool and spa use practical clothing rules.","inclusion":"Travel Gay's current Approved standard documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official Meliá information.","class":"5-star luxury hotel","coord":"OpenStreetMap hotel-property point checked against the official Rasuna Said address.","sources":["https://www.travelgay.com/gay-jakarta-hotels","https://www.melia.com/en/hotels/indonesia/jakarta/gran-melia-jakarta"]},

 {"name":"Hotel Granvia Kyoto","city":"kyoto","description":"A major hotel integrated with Kyoto Station and historically notable for hosting Japan's first hotel-based same-sex wedding ceremony. This provides unusually concrete LGBTQ+ relevance alongside excellent rail access.","vibe":"station-integrated city luxury with genuine queer wedding history","tags_csv":"luxury,cultural,mixed","hours":"Hotel reception operates 24 hours; pool, fitness, restaurants and wedding facilities use separate schedules.","link":"https://www.granvia-kyoto.co.jp/en/","location":"901 Higashi Shiokoji-cho, Shimogyo-ku, Kyoto 600-8216, Japan","lat":34.9858426,"lng":135.7598191,"arrival":"Station integration simplifies rail arrival; follow hotel signs inside the Kyoto Station complex.","best":"Rail-based Kyoto exploration and travellers who value a documented same-sex wedding milestone.","audience":"LGBTQ+ couples, international tourists, rail travellers and business guests in a large mixed hotel.","dress":"Everyday city clothing works; restaurants and ceremonies may be smart-casual or formal.","inclusion":"Travel Gay documents Granvia Kyoto as the first Japanese hotel to host a gay wedding ceremony.","basis":"Documented same-sex wedding history plus current Travel Gay Approved listing.","class":"Upscale station hotel","coord":"OpenStreetMap hotel-building point checked against the official Kyoto Station address.","sources":["https://www.travelgay.com/gay-kyoto-hotels","https://www.granvia-kyoto.co.jp/en/"]},
 {"name":"Kyoto Tokyu Hotel","city":"kyoto","description":"A polished city hotel near Nishi Honganji with restaurants, courtyard and fitness facilities. Travel Gay currently identifies it as one of Kyoto's gay-friendly hotels.","vibe":"calm contemporary Kyoto stay around a refined courtyard","tags_csv":"cultural,relax,mixed","hours":"Hotel reception operates 24 hours; shuttle, restaurants and fitness facilities use current schedules.","link":"https://www.tokyuhotels.co.jp/en/kyoto-h/","location":"580 Kakimoto-cho, Shimogyo-ku, Kyoto 600-8519, Japan","lat":34.9951413,"lng":135.7516852,"arrival":"Use the hotel's current station shuttle or plan a taxi; communicate accessibility needs before arrival.","best":"Culture-led sightseeing with a quieter base than the immediate Kyoto Station complex.","audience":"LGBTQ+ couples, tour groups, families and international visitors in a mixed hotel setting.","dress":"No hotel-wide code; smart-casual is useful for dining.","inclusion":"Current Travel Gay coverage identifies Kyoto Tokyu as gay-friendly.","basis":"Current specialist LGBTQ+ hotel listing plus official Tokyu information.","class":"Upscale city hotel","coord":"OpenStreetMap hotel-building point checked against the official Kakimoto-cho address.","sources":["https://www.travelgay.com/gay-kyoto-hotels","https://www.tokyuhotels.co.jp/en/kyoto-h/"]},
 {"name":"Hotel Gracery Kyoto Sanjo","city":"kyoto","description":"A modern hotel on the Sanjo shopping arcade near Kawaramachi, Nishiki Market and Kyoto's small queer bar scene. Travel Gay currently marks it Approved for LGBTQ+ guests.","vibe":"central arcade convenience with modern compact comfort","tags_csv":"cultural,cozy,mixed","hours":"Hotel reception operates 24 hours; restaurant and guest services follow current schedules.","link":"https://kyoto-sanjo.gracery.com/","location":"420 Sakuranocho, Nakagyo-ku, Kyoto 604-8035, Japan","lat":35.0075211,"lng":135.767323,"arrival":"Pedestrian arcade access can differ from vehicle drop-off; confirm the best luggage route before arrival.","best":"Walking access to central shopping, food and Kyoto's intimate night-time venues.","audience":"Solo visitors, couples, shoppers and LGBTQ+ guests in a broad compact-city-hotel crowd.","dress":"No dress code; everyday Kyoto city clothing is suitable.","inclusion":"Current Travel Gay Approved status documents LGBTQ+ acceptance and a welcoming standard.","basis":"Current Travel Gay Approved listing plus official hotel information.","class":"Modern mid-range city hotel","coord":"OpenStreetMap hotel-building point checked against the official Sakuranocho address.","sources":["https://www.travelgay.com/gay-kyoto-hotels","https://kyoto-sanjo.gracery.com/"]},

 {"name":"JR Kyushu Hotel Blossom Shinjuku","city":"tokyo","description":"A polished hotel minutes from Shinjuku Station, with direct transport convenience and practical access to Ni-chome. Travel Gay currently recommends it for LGBTQ+ Tokyo visitors.","vibe":"calm Japanese design at the edge of high-energy Shinjuku","tags_csv":"cultural,relax,mixed","hours":"Reception operates 24 hours; restaurant, massage and guest services follow current schedules.","link":"https://www.jrk-hotels.co.jp/en/Shinjuku/","location":"2-6-2 Yoyogi, Shibuya-ku, Tokyo 151-0053, Japan","lat":35.68761,"lng":139.69839,"arrival":"Shinjuku Station is complex; use the South Exit and the hotel's published walking directions.","best":"Rail convenience and a comfortable base within walking distance or a short ride of Ni-chome.","audience":"LGBTQ+ couples, solo travellers, rail tourists and business guests in a mixed hotel.","dress":"No dress code; individual Ni-chome venues set their own audience and entry rules.","inclusion":"Current Travel Gay coverage recommends the property to gay and LGBTQ+ Tokyo travellers.","basis":"Current specialist LGBTQ+ hotel listing plus official JR hotel information.","class":"Upscale station-area hotel","coord":"OpenStreetMap hotel point and Tokyo tourist information coordinates checked against 2-6-2 Yoyogi.","sources":["https://www.travelgay.com/gay-tokyo-hotels","https://www.jrk-hotels.co.jp/en/Shinjuku/access/"]},
 {"name":"Shinjuku Granbell Hotel","city":"tokyo","description":"A design hotel in Kabukicho within walking distance of Shinjuku Ni-chome, with rooftop bar and compact contemporary rooms. Travel Gay currently includes it as a practical gay-friendly Tokyo base.","vibe":"urban design energy between Kabukicho and Ni-chome","tags_csv":"social,cultural,mixed","hours":"Hotel reception operates 24 hours; rooftop bar, restaurant and café use separate schedules.","link":"https://www.granbellhotel.jp/en/shinjuku/","location":"2-14-5 Kabukicho, Shinjuku-ku, Tokyo 160-0021, Japan","lat":35.6965754,"lng":139.7056852,"arrival":"Kabukicho streets are busy at night; use the official route and reserve rooftop seating separately.","best":"Visitors prioritising Shinjuku nightlife and walkability to Ni-chome.","audience":"LGBTQ+ travellers, couples, groups and design-conscious city visitors in a mixed crowd.","dress":"Casual city clothing works; individual bars and clubs set their own entry expectations.","inclusion":"Current Travel Gay coverage lists the hotel as welcoming and well placed for the gay scene.","basis":"Current specialist LGBTQ+ travel listing plus official property information.","class":"Design lifestyle hotel","coord":"OpenStreetMap hotel-property point checked against the official Kabukicho address.","sources":["https://www.travelgay.com/gay-tokyo-hotels","https://www.granbellhotel.jp/en/shinjuku/"]},
 {"name":"Hotel New Otani Tokyo The Main","city":"tokyo","description":"A large luxury hotel around a historic Japanese garden with extensive dining, pools and wellness facilities. Travel Gay currently marks it Approved and notes quick access to Shinjuku's queer nightlife.","vibe":"garden-centred Tokyo grandeur with full resort-scale facilities","tags_csv":"luxury,relax,massive","hours":"Hotel reception operates 24 hours; pools, garden, restaurants, spa and shops use separate schedules.","link":"https://www.newotani.co.jp/en/tokyo/","location":"4-1 Kioi-cho, Chiyoda-ku, Tokyo 102-8578, Japan","lat":35.6809135,"lng":139.7339748,"arrival":"The complex is large; confirm the correct tower and entrance before arrival.","best":"A full-service luxury retreat with central rail access rather than direct Ni-chome frontage.","audience":"LGBTQ+ couples, families, business groups and international luxury travellers in a mixed hotel.","dress":"Smart-casual suits many restaurants; pools and formal dining may have specific rules.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official New Otani information.","class":"Large luxury garden hotel","coord":"OpenStreetMap The Main building point checked against the official Kioi-cho complex address.","sources":["https://www.travelgay.com/gay-tokyo-hotels","https://www.newotani.co.jp/en/tokyo/"]},

 {"name":"WOLO Kuala Lumpur","city":"kuala_lumpur","description":"A design-conscious hotel at the Bukit Bintang crossing, surrounded by shopping, dining and mixed nightlife. Travel Gay currently includes WOLO among Kuala Lumpur's gay-friendly hotel recommendations.","vibe":"bold compact design in the middle of Bukit Bintang","tags_csv":"social,cultural,mixed","hours":"Hotel reception operates 24 hours; café, bar and guest services follow current schedules.","link":"https://wolohotel.com.my/","location":"165 Jalan Bukit Bintang, Kuala Lumpur 55100, Malaysia","lat":3.1470748,"lng":101.7114291,"arrival":"Bukit Bintang traffic is dense; rail or planned drop-off can simplify arrival.","best":"Shopping, mixed nightlife and central access while keeping queer activity discreet in Malaysia's legal context.","audience":"LGBTQ+ visitors, couples, shoppers and international city guests in a broad mixed hotel.","dress":"Contemporary city casual; external venues set their own policies.","inclusion":"Current Travel Gay coverage lists WOLO as a welcoming Kuala Lumpur choice.","basis":"Current specialist LGBTQ+ hotel listing plus official property information.","class":"Design boutique city hotel","coord":"OpenStreetMap hotel-property point checked against the official Bukit Bintang address.","sources":["https://www.travelgay.com/kuala-lumpur-hotels","https://wolohotel.com.my/"]},
 {"name":"PARKROYAL COLLECTION Kuala Lumpur","city":"kuala_lumpur","description":"A biophilic luxury hotel in Bukit Bintang with pool, spa, restaurants and extensive greenery. Travel Gay currently includes the property among Kuala Lumpur's LGBTQ+-welcoming hotel choices.","vibe":"lush biophilic luxury above Bukit Bintang's city pulse","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; pool, spa, restaurants and collection club use current schedules.","link":"https://www.panpacific.com/en/hotels-and-resorts/pr-collection-kuala-lumpur.html","location":"Jalan Sultan Ismail, Bukit Bintang, Kuala Lumpur 50250, Malaysia","lat":3.1443335,"lng":101.7121987,"arrival":"Central traffic can delay vehicles; reserve spa and dining separately.","best":"High-service wellness and shopping access in a discreet, broad-audience hotel.","audience":"Couples, families, business guests and LGBTQ+ travellers in an international mixed setting.","dress":"Smart-casual suits restaurants; pool and spa have practical requirements.","inclusion":"Current LGBTQ+ specialist travel coverage includes the hotel as a welcoming option.","basis":"Current Travel Gay Kuala Lumpur listing plus official Pan Pacific information.","class":"5-star biophilic luxury hotel","coord":"OpenStreetMap hotel-building point checked against the official Jalan Sultan Ismail address.","sources":["https://www.travelgay.com/kuala-lumpur-hotels","https://www.panpacific.com/en/hotels-and-resorts/pr-collection-kuala-lumpur.html"]},
 {"name":"Traders Hotel Kuala Lumpur","city":"kuala_lumpur","description":"A high-rise hotel facing KLCC Park and the Petronas Towers, known for skyline rooms and SkyBar. Travel Gay currently lists it for LGBTQ+ Kuala Lumpur travellers.","vibe":"iconic KLCC skyline stay with polished rooftop energy","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; SkyBar, pool, restaurants and club lounge follow current schedules.","link":"https://www.shangri-la.com/kualalumpur/traders/","location":"Kuala Lumpur City Centre, Kuala Lumpur 50088, Malaysia","lat":3.1541033,"lng":101.7150455,"arrival":"KLCC events can increase traffic and SkyBar demand; reserve public venues separately.","best":"Petronas views, KLCC access and a polished mixed-nightlife base.","audience":"LGBTQ+ couples, business travellers and international leisure guests in a broad hotel crowd.","dress":"Smart-casual suits SkyBar and dining; pool rules are separate.","inclusion":"Current Travel Gay coverage includes Traders among Kuala Lumpur's welcoming hotels.","basis":"Current specialist LGBTQ+ travel listing plus official Shangri-La information.","class":"5-star KLCC business and leisure hotel","coord":"OpenStreetMap hotel-property point checked against the official KLCC address.","sources":["https://www.travelgay.com/kuala-lumpur-hotels","https://www.shangri-la.com/kualalumpur/traders/"]},

 {"name":"Sheraton Manila Bay","city":"manila","description":"A full-service hotel in Malate with pool, dining and access to Manila's historic entertainment district. Travel Gay currently marks it Approved for LGBTQ+ customers.","vibe":"classic Malate city hotel with lively central access","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; pool, restaurants, lounge and fitness use current schedules.","link":"https://www.marriott.com/en-us/hotels/mnlsb-sheraton-manila-bay/overview/","location":"M. Adriatico Street corner General Malvar Street, Malate, Manila 1004, Philippines","lat":14.5727383,"lng":120.9843562,"arrival":"Metro Manila traffic is unpredictable; allow generous transfer time and reserve dining separately.","best":"Malate, historic Manila and a central full-service hotel base.","audience":"LGBTQ+ travellers, couples, families and business guests in a broad international setting.","dress":"Smart-casual suits dining; pool and fitness areas have practical rules.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official Marriott information.","class":"5-star full-service hotel","coord":"OpenStreetMap hotel-property point checked against the official Adriatico/Malvar address.","sources":["https://www.travelgay.com/gay-manila-hotels","https://www.marriott.com/en-us/hotels/mnlsb-sheraton-manila-bay/overview/"]},
 {"name":"New World Makati Hotel","city":"manila","description":"A luxury hotel beside Greenbelt in Makati with pool, spa and multiple restaurants. Travel Gay currently marks it Approved and highlights its practical position for LGBTQ+ Metro Manila visitors.","vibe":"polished Greenbelt luxury at the centre of Makati","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; pool, spa, restaurants and club lounge use current schedules.","link":"https://manila.newworldhotels.com/","location":"Esperanza Street corner Makati Avenue, Ayala Center, Makati 1228, Metro Manila, Philippines","lat":14.5511597,"lng":121.0216878,"arrival":"Makati traffic and mall events can slow arrival; reserve spa and dining separately.","best":"Greenbelt shopping, Makati dining and a high-service base for a geographically dispersed queer scene.","audience":"LGBTQ+ couples, business travellers, families and international luxury guests in a mixed hotel.","dress":"Smart-casual suits public spaces and restaurants; pool rules are separate.","inclusion":"The current Travel Gay Approved listing documents LGBTQ+ acceptance and a welcoming standard.","basis":"Current Travel Gay Approved listing plus official hotel information.","class":"5-star luxury city hotel","coord":"OpenStreetMap hotel-building point checked against the official Esperanza Street address.","sources":["https://www.travelgay.com/gay-manila-hotels","https://manila.newworldhotels.com/"]},
 {"name":"Dusit Thani Manila","city":"manila","description":"A long-established luxury hotel in Ayala Center with Thai-influenced hospitality, pool, spa and several restaurants. Travel Gay currently includes it among LGBTQ+-welcoming Manila hotels.","vibe":"warm Thai-style luxury with central Makati convenience","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; spa, pool, restaurants and events use current schedules.","link":"https://www.dusit.com/dusitthani-manila/","location":"Ayala Center, Makati 1223, Metro Manila, Philippines","lat":14.5484702,"lng":121.026157,"arrival":"Allow for Makati traffic; restaurant and spa bookings are separate from hotel arrival.","best":"Ayala shopping and a full-service Makati stay with easy ride-based city access.","audience":"Couples, families, business groups and LGBTQ+ travellers in a broad luxury crowd.","dress":"Smart-casual suits dining and lobby spaces; wellness areas have practical rules.","inclusion":"Current LGBTQ+ specialist travel coverage includes Dusit Thani as a welcoming Manila option.","basis":"Current Travel Gay Manila listing plus official Dusit information.","class":"5-star luxury hotel","coord":"OpenStreetMap hotel-property point checked against the official Ayala Center location.","sources":["https://www.travelgay.com/gay-manila-hotels","https://www.dusit.com/dusitthani-manila/"]},

 {"name":"Imperial Palace Boutique Hotel Itaewon","city":"seoul","description":"A colourful boutique hotel directly in Itaewon, within walking distance of Homo Hill and the district's queer nightlife. Travel Gay currently marks it Approved and names it a top affordable Seoul choice.","vibe":"playful Itaewon design beside Seoul's international queer scene","tags_csv":"social,cultural,mixed","hours":"Hotel reception operates 24 hours; restaurant, gym and guest services follow current schedules.","link":"https://www.ipboutiquehotel.com/","location":"221 Itaewon-ro, Yongsan-gu, Seoul 04349, South Korea","lat":37.5352908,"lng":126.9982368,"arrival":"Itaewon weekends are busy; public transport and a planned luggage route simplify arrival.","best":"Walking access to Homo Hill and Itaewon's queer-friendly bars and clubs.","audience":"LGBTQ+ travellers, international visitors, couples and nightlife groups in a mixed boutique hotel.","dress":"No hotel code; individual Seoul nightlife doors can be audience-specific.","inclusion":"Travel Gay's current Approved record and Itaewon hotel guide document a welcoming LGBTQ+ standard.","basis":"Current Travel Gay Approved listing plus exact queer-district location.","class":"Boutique lifestyle hotel","coord":"OpenStreetMap hotel-property point checked against the official 221 Itaewon-ro address.","sources":["https://www.travelgay.com/gay-seoul-hotels","https://www.ipboutiquehotel.com/"]},
 {"name":"Hamilton Hotel Seoul","city":"seoul","description":"A landmark hotel directly above Itaewon Station and at the entrance to the neighbourhood's queer nightlife lanes. Travel Gay currently marks it Approved for LGBTQ+ customers.","vibe":"central Itaewon landmark with nightlife at the doorstep","tags_csv":"social,massive,mixed","hours":"Hotel reception operates 24 hours; pool, sauna, restaurants and retail spaces use separate schedules.","link":"https://www.hamilton.co.kr/","location":"179 Itaewon-ro, Yongsan-gu, Seoul 04350, South Korea","lat":37.5347459,"lng":126.993629,"arrival":"Weekend street crowds can be intense; Itaewon Station is usually the simplest arrival route.","best":"Maximum proximity to Itaewon nightlife and public transport.","audience":"LGBTQ+ visitors, international tourists, groups and local weekend guests in a broad mixed hotel.","dress":"Hotel areas are casual; clubs and small queer bars may enforce specific audience or door rules.","inclusion":"Current Travel Gay Approved status documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus direct Itaewon queer-scene location.","class":"Large central Itaewon hotel","coord":"OpenStreetMap hotel-building point checked against the official 179 Itaewon-ro address.","sources":["https://www.travelgay.com/gay-seoul-hotels","https://www.hamilton.co.kr/"]},
 {"name":"Mondrian Seoul Itaewon","city":"seoul","description":"A design-led luxury hotel in Yongsan with pool, spa, bars and easy access to Itaewon. Travel Gay currently marks it Approved for LGBTQ+ guests.","vibe":"fashion-forward Seoul luxury with bold social spaces","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; pool, spa, bars, restaurants and events use current schedules.","link":"https://mondrianhotels.com/seoul-itaewon/","location":"23 Jangmun-ro, Yongsan-gu, Seoul 04392, South Korea","lat":37.5285592,"lng":126.9931256,"arrival":"Hotel events can make the lobby lively; reserve bars, dining and wellness separately.","best":"A polished lifestyle stay near Itaewon with more resort facilities than the district's smaller hotels.","audience":"LGBTQ+ couples, fashion crowds, business guests and international travellers in a mixed setting.","dress":"Fashionable city clothing fits the public spaces; events may publish specific guidance.","inclusion":"Travel Gay's current Approved record documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official Mondrian information.","class":"5-star lifestyle hotel","coord":"OpenStreetMap hotel-property point checked against the official 23 Jangmun-ro address.","sources":["https://www.travelgay.com/gay-seoul-hotels","https://mondrianhotels.com/seoul-itaewon/"]},

 {"name":"Hotel 1929","city":"singapore","description":"A compact heritage boutique hotel on Keong Saik Road, steps from Chinatown and Neil Road's LGBTQ+ venues. Travel Gay currently marks it Approved for LGBTQ+ guests.","vibe":"compact heritage character beside Chinatown's queer circuit","tags_csv":"cozy,cultural,social","hours":"Hotel reception operates daily; confirm current late-arrival and guest-service arrangements directly.","link":"https://hotel1929.com.sg/","location":"50 Keong Saik Road, Singapore 089154","lat":1.2807922,"lng":103.8418123,"arrival":"Rooms and lobby are compact; confirm luggage storage and late arrival before travel.","best":"Walking access to Chinatown dining, Neil Road bars and central transit.","audience":"LGBTQ+ couples, solo visitors and value-conscious city travellers in a small mixed hotel.","dress":"No hotel dress code; nightlife venues nearby set their own policies.","inclusion":"Current Travel Gay Approved status documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official property information.","class":"Heritage boutique hotel","coord":"OpenStreetMap hotel-building point checked against the official 50 Keong Saik Road address.","sources":["https://www.travelgay.com/gay-singapore-hotels","https://hotel1929.com.sg/"]},
 {"name":"PARKROYAL COLLECTION Pickering","city":"singapore","description":"A landmark biophilic hotel beside Chinatown with elevated gardens, infinity pool and spa. Travel Gay currently marks it Approved and its location gives easy access to Neil Road's LGBTQ+ venues.","vibe":"lush architectural luxury above central Singapore","tags_csv":"luxury,relax,cultural","hours":"Hotel reception operates 24 hours; pool, spa, restaurants and collection club use current schedules.","link":"https://www.panpacific.com/en/hotels-and-resorts/pr-collection-pickering.html","location":"3 Upper Pickering Street, Singapore 058289","lat":1.2856566,"lng":103.8462571,"arrival":"Concierge-led arrival; reserve spa and dining separately during peak travel periods.","best":"Design, wellness and walking access to Chinatown and Singapore's compact queer nightlife.","audience":"LGBTQ+ couples, architecture travellers, business guests and luxury visitors in a mixed hotel.","dress":"Smart-casual suits dining; pool and spa have practical attire rules.","inclusion":"The current Travel Gay Approved listing documents LGBTQ+ acceptance and a welcoming standard.","basis":"Current Travel Gay Approved listing plus official Pan Pacific information.","class":"5-star biophilic luxury hotel","coord":"OpenStreetMap hotel-building point checked against the official 3 Upper Pickering Street address.","sources":["https://www.travelgay.com/gay-singapore-hotels","https://www.panpacific.com/en/hotels-and-resorts/pr-collection-pickering.html"]},
 {"name":"JEN Singapore Orchardgateway","city":"singapore","description":"A contemporary hotel directly above Somerset MRT with rooftop infinity pool and immediate Orchard Road access. Travel Gay currently marks it Approved for LGBTQ+ customers.","vibe":"bright Orchard convenience with a panoramic rooftop pool","tags_csv":"social,relax,mixed","hours":"Hotel reception operates 24 hours; rooftop pool, gym, restaurant and bar follow current schedules.","link":"https://www.jen-eats.com/orchardgateway/","location":"277 Orchard Road, Singapore 238858","lat":1.3007018,"lng":103.8388997,"arrival":"Direct MRT and mall integration make arrival simple; follow hotel lift signage from Orchardgateway.","best":"Shopping, transit and rooftop leisure with Chinatown's queer bars a short ride away.","audience":"Couples, families, shoppers and LGBTQ+ guests in a broad contemporary hotel.","dress":"Relaxed city clothing works; rooftop pool and dining have practical guidance.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official hotel information.","class":"Upscale Orchard Road hotel","coord":"OpenStreetMap hotel-building point checked against the official 277 Orchard Road address.","sources":["https://www.travelgay.com/gay-singapore-hotels","https://www.shangri-la.com/en/hotels/jen/singapore/orchardgateway/"]},

 {"name":"CC's Hideaway","city":"phuket","description":"A hillside boutique resort above Kata and Karon whose current Travel Gay Approved listing documents LGBTQ+ welcome. Yoga, pool and shuttle access create a quieter alternative to Patong.","vibe":"inclusive tropical hillside retreat with wellness energy","tags_csv":"relax,cozy,mixed","hours":"Hotel reception operates daily; shuttles, yoga, pool, restaurant and activities use current schedules.","link":"https://www.ccshideaway.com/","location":"36 Patak Road Soi 10, Karon, Phuket 83100, Thailand","lat":7.8298374,"lng":98.304652,"arrival":"The steep hillside makes the resort shuttle or arranged transfer preferable with luggage.","best":"LGBTQ+ travellers seeking wellness and quieter beach access rather than nightlife at the door.","audience":"Queer couples, solo wellness travellers and a broad international resort crowd.","dress":"Tropical resort and yoga clothing; activities use practical attire guidance.","inclusion":"Travel Gay's current Approved record documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official resort information.","class":"Boutique hillside wellness resort","coord":"OpenStreetMap resort-property point checked against the official Patak Soi 10 address.","sources":["https://www.travelgay.com/gay-phuket-hotels","https://www.ccshideaway.com/"]},
 {"name":"La Flora Resort Patong","city":"phuket","description":"A beachfront Patong resort within walking distance of Paradise Complex, with two pools, spa and sunset-facing restaurant. Travel Gay identifies it as a highly gay-popular five-star Phuket stay.","vibe":"beachfront Patong luxury close to the queer night scene","tags_csv":"luxury,social,mixed","hours":"Hotel reception operates 24 hours; pools, spa, restaurant and beach services follow current schedules.","link":"https://www.laflorapatong.com/","location":"39 Thawewong Road, Patong, Phuket 83150, Thailand","lat":7.8955578,"lng":98.2954925,"arrival":"Central Patong traffic can be dense; arrange airport transfer and reserve spa or sunset dining separately.","best":"Combining direct beach access with easy walking to Paradise Complex gay bars.","audience":"LGBTQ+ couples and groups, beach travellers and international resort guests in a mixed setting.","dress":"Beachwear by day; restaurants and nightlife venues may request smarter clothing.","inclusion":"Current Travel Gay coverage identifies La Flora as gay-popular and welcoming.","basis":"Current specialist LGBTQ+ hotel coverage plus official resort information.","class":"5-star beachfront resort","coord":"OpenStreetMap hotel-property point checked against the official Thawewong Road address.","sources":["https://www.travelgay.com/phuket-luxury-hotels","https://www.laflorapatong.com/"]},
 {"name":"The KEE Resort & Spa","city":"phuket","description":"A contemporary Patong resort immediately beside Paradise Complex and close to the beach, with rooftop bar, pool and spa. Travel Gay currently recommends it strongly for gay Phuket visitors.","vibe":"colourful Patong resort with queer nightlife next door","tags_csv":"social,relax,mixed","hours":"Hotel reception operates 24 hours; rooftop, pool, spa and restaurants use current schedules.","link":"https://www.thekeeresort.com/","location":"152/1 Thawewong Road, Patong, Phuket 83150, Thailand","lat":7.8950255,"lng":98.2974329,"arrival":"Paradise Complex and Bangla-area traffic peak at night; plan vehicle arrival earlier when possible.","best":"Travellers who want the shortest walk to Patong's gay bars while retaining full resort facilities.","audience":"LGBTQ+ couples, groups, nightlife travellers and a broad international Patong crowd.","dress":"Resort casual; rooftop and individual nightlife venues may have separate rules.","inclusion":"Current Travel Gay coverage places The KEE among Patong's key gay-friendly hotel choices.","basis":"Current specialist LGBTQ+ hotel listing plus official resort information.","class":"Upscale central Patong resort","coord":"OpenStreetMap hotel-property point checked against the official 152/1 Thawewong Road address.","sources":["https://www.travelgay.com/gay-patong-hotels","https://www.thekeeresort.com/"]},

 {"name":"Liberty Central Saigon Citypoint","city":"ho_chi_minh","description":"A modern District 1 hotel with rooftop pool, sky bar, spa and in-house cinema near Nguyen Hue and Ben Thanh. Travel Gay currently marks it Approved for LGBTQ+ guests.","vibe":"central Saigon polish with rooftop city energy","tags_csv":"social,luxury,mixed","hours":"Hotel reception operates 24 hours; rooftop, cinema, spa, pool and restaurants use current schedules.","link":"https://www.libertycentralsaigoncitypoint.com/en/","location":"59-61 Pasteur Street, District 1, Ho Chi Minh City, Vietnam","lat":10.7747464,"lng":106.7006434,"arrival":"District 1 traffic can slow drop-off; reserve rooftop and spa access separately.","best":"First-time city access, central attractions and a lively rooftop within walking distance of queer-friendly events.","audience":"LGBTQ+ couples, business travellers and international city visitors in a broad mixed hotel.","dress":"Smart-casual suits the sky bar; pool and spa have practical rules.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official hotel information.","class":"4-star central city hotel","coord":"OpenStreetMap hotel-building point checked against the official 59-61 Pasteur address.","sources":["https://www.travelgay.com/gay-Ho-Chi-Minh-Hotels","https://www.libertycentralsaigoncitypoint.com/en/"]},
 {"name":"Silverland Yen Hotel","city":"ho_chi_minh","description":"A 64-room District 1 hotel near Ben Thanh Market with rooftop pool, sauna and compact boutique atmosphere. Travel Gay currently marks it Approved for LGBTQ+ customers.","vibe":"compact Ben Thanh boutique stay with rooftop relaxation","tags_csv":"cozy,relax,mixed","hours":"Hotel reception operates 24 hours; rooftop pool, sauna, restaurant and afternoon service follow current schedules.","link":"https://silverlandhotels.com/silverland-yen-hotel/","location":"73-75 Thu Khoa Huan Street, Ben Thanh Ward, District 1, Ho Chi Minh City, Vietnam","lat":10.774313,"lng":106.6961892,"arrival":"A compact central hotel; confirm vehicle drop-off and reserve any limited rooftop services early.","best":"Ben Thanh sightseeing and a quieter boutique base within central District 1.","audience":"LGBTQ+ couples, solo travellers and general international visitors in a mixed small hotel.","dress":"No hotel-wide code; pool and sauna use practical clothing rules.","inclusion":"Current Travel Gay Approved status documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official Silverland information.","class":"Boutique District 1 hotel","coord":"OpenStreetMap hotel-property point checked against the official Thu Khoa Huan location.","sources":["https://www.travelgay.com/gay-Ho-Chi-Minh-Hotels","https://silverlandhotels.com/silverland-yen-hotel/"]},
 {"name":"Hotel Nikko Saigon","city":"ho_chi_minh","description":"A spacious Japanese-style luxury hotel on Nguyen Van Cu with pool, spa and extensive dining. Travel Gay currently marks it Approved and recommends it to LGBTQ+ Ho Chi Minh City visitors.","vibe":"calm Japanese-influenced luxury beyond the busiest tourist blocks","tags_csv":"luxury,relax,mixed","hours":"Hotel reception operates 24 hours; pool, spa, restaurants and club lounge use current schedules.","link":"https://hotelnikko-saigon.com.vn/","location":"235 Nguyen Van Cu Street, District 1, Ho Chi Minh City, Vietnam","lat":10.764275,"lng":106.6829603,"arrival":"The hotel is slightly west of the densest central sights; plan rides and reserve dining or spa separately.","best":"Large rooms, wellness and a quieter high-service base with short rides to District 1 nightlife.","audience":"LGBTQ+ couples, families, business guests and international luxury travellers in a mixed hotel.","dress":"Smart-casual suits dining and lounges; pool and spa have separate practical rules.","inclusion":"Travel Gay's current Approved programme documents LGBTQ+ acceptance and welcoming service.","basis":"Current Travel Gay Approved listing plus official hotel information.","class":"5-star luxury hotel","coord":"OpenStreetMap hotel-building point checked against the official 235 Nguyen Van Cu address.","sources":["https://www.travelgay.com/gay-Ho-Chi-Minh-Hotels","https://hotelnikko-saigon.com.vn/"]}
]
$hotels$) h(
  name text, city text, description text, vibe text, tags_csv text, hours text,
  link text, location text, lat double precision, lng double precision,
  arrival text, best text, audience text, dress text, inclusion text, basis text,
  class text, coord text, sources jsonb
  )
), source_hotels as (
  select h.*,
    jsonb_build_object(
      'queue_wait', h.arrival,
      'best_nights', h.best,
      'crowd_mix', h.audience,
      'dress_code', h.dress,
      'staff_inclusivity', h.inclusion,
      'inclusion_basis', h.basis,
      'hotel_class', h.class,
      'coordinate_source', h.coord,
      'source_urls', h.sources,
      'research_status', 'researched_sources_and_exact_property_location',
      'updated_at', '2026-08-23T00:00:00Z'
    ) as intel
  from raw_hotels h
), updated as (
  update public.places p
  set type = 'hotel',
      description = h.description,
      vibe = h.vibe,
      vibe_tags = string_to_array(h.tags_csv, ','),
      hours = h.hours,
      link = h.link,
      location = h.location,
      lat = h.lat,
      lng = h.lng,
      venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || h.intel,
      seo_indexable = true,
      seo_quality_status = 'approved',
      updated_at = timezone('utc', now())
  from source_hotels h
  where lower(trim(p.city)) = h.city
    and lower(trim(p.name)) = lower(trim(h.name))
  returning p.id
)
insert into public.places (
  name, city, type, description, vibe, vibe_tags, hours, link, location,
  lat, lng, venue_intel, seo_indexable, seo_quality_status, updated_at
)
select h.name, h.city, 'hotel', h.description, h.vibe,
  string_to_array(h.tags_csv, ','), h.hours, h.link, h.location,
  h.lat, h.lng, h.intel, true, 'approved', timezone('utc', now())
from source_hotels h
where not exists (
  select 1 from public.places p
  where lower(trim(p.city)) = h.city
    and lower(trim(p.name)) = lower(trim(h.name))
);

commit;

-- Expected: exactly 3 complete batch rows per destination.
select city,
  count(*) filter (
    where type = 'hotel'
      and venue_intel->>'updated_at' = '2026-08-23T00:00:00Z'
  ) as batch_hotels,
  count(*) filter (
    where type = 'hotel'
      and venue_intel->>'updated_at' = '2026-08-23T00:00:00Z'
      and coalesce(venue_intel->>'queue_wait', '') <> ''
      and coalesce(venue_intel->>'best_nights', '') <> ''
      and coalesce(venue_intel->>'crowd_mix', '') <> ''
      and coalesce(venue_intel->>'dress_code', '') <> ''
      and coalesce(venue_intel->>'staff_inclusivity', '') <> ''
      and jsonb_array_length(coalesce(venue_intel->'source_urls', '[]'::jsonb)) >= 2
      and lat between -90 and 90 and lng between -180 and 180
      and coalesce(location, '') <> '' and coalesce(link, '') <> ''
  ) as complete_rows
from public.places
where lower(trim(city)) in (
  'siem_reap','shanghai','hong_kong','new_delhi','bali','jakarta','kyoto',
  'tokyo','kuala_lumpur','manila','seoul','singapore','phuket','ho_chi_minh'
)
group by city
order by city;

select name, city, location,
  round(lat::numeric, 6) as lat,
  round(lng::numeric, 6) as lng,
  venue_intel->>'inclusion_basis' as inclusion_basis
from public.places
where type = 'hotel'
  and venue_intel->>'updated_at' = '2026-08-23T00:00:00Z'
order by city, name;
