-- Queer Atlas: Cairo venue, event and service intelligence
-- Run after city-cairo-curated-v1.sql. Idempotent and apostrophe-safe.

begin;

with researched as (
 select * from jsonb_to_recordset($cairo_place_intel$
[
 {"name":"Cairo Jazz Club","patch":{"queue_wait":"This is more reservation check than spontaneous queue. Names are checked against the booking, hard ID is required and capacity or door selection can still stop entry. Reach the door before the headline set; the final half-hour before a popular act is where the pavement bunches.","best_nights":"Follow the artist. A live Egyptian band produces a different room from an electronic or nostalgia night, and Thursday or Friday is not automatically better than a strong midweek booking. Reserve as soon as the programme you want appears.","crowd_mix":"Young and mid-career Cairenes, musicians, creative-industry regulars, affluent local groups, expatriates and informed visitors. The room is predominantly local and mixed, not a tourist bar or a public queer gathering.","dress_code":"The venue explicitly refuses slippers and sportswear. Clean city-night clothing, closed shoes and a composed group presentation are the practical baseline; experimental style can work, but it does not override the reservation, age or mixed-group rules.","staff_inclusivity":"The published code prohibits harassment and discriminatory behaviour, which is meaningful. At the same time, reviews repeatedly describe a selective or abrupt door and the couples-or-mixed-groups policy can create friction. There is no public LGBTQ+ inclusion promise, so discretion remains necessary.","review_signal":"More than a thousand current reviews converge on excellent live energy, strong programming and an intimate stage, with recurring criticism of smoke, crowding, high prices and door or service attitude. The right artist can make the night; a casual unreserved arrival is the weak version.","identity_note":"Established mixed live-music club with no public gay-venue claim and a formal, capacity-controlled door.","source_urls":["https://www.cairojazzclub.com/","https://cairojazzclub.com/about-cjc/cjc-stage-1-1/","https://wanderlog.com/place/details/106346/cairo-jazz-club"],"research_status":"official_rules_plus_current_review_consensus","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"ROOM Art Space & Cafe Garden City","patch":{"queue_wait":"Ordinary cafe hours are low-pressure, but ticketed music, comedy and karaoke can compress everyone into the same small basement. Buy or reserve through the event listing and arrive 20 to 30 minutes before doors if you want a comfortable table or sightline.","best_nights":"The best night is a programme you actually care about. Karaoke creates the easiest participatory social mood; a seated concert or film offers a quieter entry. ROOM changes personality so completely that generic weekend advice is almost useless.","crowd_mix":"Cairo students, musicians, performers, young professionals, artists and small groups of international residents or travellers. The audience is creative and mostly local, but not automatically queer because the programme feels alternative.","dress_code":"Casual, expressive clothes fit naturally. Comfortable shoes and a light layer help because a busy basement can run warm while the street or ride home feels different. No standing dress code was found.","staff_inclusivity":"The breadth of performers and participatory formats suggests an open cultural room, yet no current LGBTQ+ policy or safer-space protocol is published. Treat warm creative energy as a positive signal, not proof that public affection or personal disclosure is risk-free.","review_signal":"Visitors repeatedly value the intimate performances, atmosphere and sense of discovery; smaller-room crowding, smoke or service pacing appear in mixed comments. Programme quality—not polished hospitality—is why people return.","identity_note":"Mixed independent arts cafe that can feel socially open without being a declared queer venue.","source_urls":["https://www.roomart.space/","https://www.roomart.space/events","https://www.facebook.com/ROOMArtSpaceGardenCity/"],"research_status":"official_calendar_plus_current_local_listing_consensus","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Zawya Cinema","patch":{"queue_wait":"A normal weekday screening is straightforward. Festival premieres, one-off restorations and filmmaker conversations can sell out or form a real box-office line, so buy through the current programme and arrive 20 to 30 minutes early when the title is scarce.","best_nights":"Choose by film rather than weekday. Arab independent premieres, retrospectives and festival programmes bring the most engaged room; a quieter afternoon screening is better when you want cultural depth without a social spotlight.","crowd_mix":"Egyptian cinephiles, students, filmmakers, critics, Downtown regulars and international residents. Review volume suggests a strongly local institution rather than a tourist attraction, even when subtitled films broaden the room.","dress_code":"Everyday cinema clothes. Nothing about the venue calls for club styling, and low-key presentation is the more context-aware choice in Downtown Cairo.","staff_inclusivity":"Reviews often call the team friendly and the programming independent-minded. That supports a respectful cultural experience, but Zawya publishes no general LGBTQ+ safety guarantee; assess each film and discussion on its own terms.","review_signal":"A roughly 4.5 rating across thousands of reviews is unusually strong. Audiences praise the arthouse selection, affordable access, projection and character; the recurring compromise is an older auditorium and seats that some find uncomfortable.","identity_note":"Independent arthouse cinema with adventurous programming, not a permanently queer-labelled space.","source_urls":["https://zawyacinema.com/","https://wanderlog.com/place/details/4327237/cin%C3%A9ma-zawya"],"research_status":"official_programme_plus_large_current_review_consensus","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Townhouse Gallery","patch":{"queue_wait":"Daytime visits rarely queue. Opening nights, talks and performances can fill the narrow approach and small rooms, but the harder part for first-timers is finding the entrance. Save the pin, check the current address and allow ten extra minutes.","best_nights":"An exhibition opening or announced talk gives the gallery its strongest social pulse. For time with the work and staff, choose a weekday afternoon; Townhouse is cultural daytime infrastructure, not a late-night substitute.","crowd_mix":"Cairo artists, curators, students, writers, Downtown cultural workers and visitors following the contemporary scene. Locals shape the room, while international arts networks add a smaller transient layer.","dress_code":"Comfortable, city-casual and heat-aware. Openings can become stylish, but there is no door code and practical shoes suit the surrounding lanes better than a formal look.","staff_inclusivity":"Reviewers regularly describe helpful, engaged staff and a welcoming small-scale atmosphere. The institution's experimental history is encouraging, but no current venue-wide LGBTQ+ policy was found, so the atlas does not convert artistic openness into a safety guarantee.","review_signal":"Current reviews sit around 4.5 from several hundred visitors, praising the hidden discovery, exhibitions, library and human welcome. Confusing access, changing programme information and the modest physical space are the consistent caveats.","identity_note":"Independent contemporary-art institution with a mixed public and no permanent queer-space designation.","source_urls":["http://thetownhousegallery.com/","https://www.cuipcairo.org/ar/directory/townhouse-gallery","https://wanderlog.com/place/details/1714683/galerie-townhouse"],"research_status":"institutional_directory_plus_current_review_consensus_with_address_caveat","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Harry's Pub","patch":{"queue_wait":"Hotel security is the predictable pause; the pub itself is usually table-led rather than a street queue. A live-band night or match can fill the compact room, so reserve through the hotel or arrive near opening if a seat matters.","best_nights":"Choose the published live-band evening for energy, or an early weekday for a quiet drink. Harry's is useful because it is predictable, not because one universal party night transforms it into a queer scene.","crowd_mix":"Cairenes meeting after work, Marriott guests, expatriates, business travellers and small groups seeking a familiar pub format. Visitors are more visible here than at an independent Downtown venue, but locals are not absent.","dress_code":"The hotel lists casual dress. Smart-casual clothing keeps arrival simple through the lobby; avoid reading the relaxed pub format as permission for conspicuous public affection.","staff_inclusivity":"International-hotel service standards and staffed security can make logistics feel orderly. Neither the pub nor the hotel publishes a Cairo-specific LGBTQ+ welcome, so professional hospitality should not be mistaken for legal or social protection.","review_signal":"Review summaries generally praise the intimate room, cleanliness, music and friendly service. Price complaints and occasional service inconsistencies recur, reflecting a hotel bar whose convenience carries a premium.","identity_note":"Mixed hotel pub with predictable infrastructure, not a gay bar or certified queer-safe venue.","source_urls":["https://www.marriott.com/en-us/hotels/caieg-cairo-marriott-hotel/dining/","https://restaurantguru.com/Harrys-pub-Cairo-2"],"research_status":"official_hotel_listing_plus_current_review_consensus","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Pub 28 Zamalek","patch":{"queue_wait":"There is no formal club queue, but the small room can run out of tables late on Thursday and Friday. Arrive before the dinner-to-drinks crossover or call ahead with a group; waiting outside adds little to the experience.","best_nights":"Early evening is the best first visit because conversation, food and the old-pub character are still legible. Later weekend hours become louder and smokier. Pick another venue if what you want is dancing or an explicitly queer crowd.","crowd_mix":"Long-time Zamalek regulars, Egyptian professionals, expatriates, couples, friend groups and travellers following guidebook recommendations. The atmosphere is mixed and locally rooted rather than an international gay-tour stop.","dress_code":"Relaxed smart-casual works. The room is old-school rather than fashion-policed, but understated presentation is sensible and likely to feel more natural than full clubwear.","staff_inclusivity":"Many reviews value familiar, personable service; others describe uneven treatment or abruptness. No public LGBTQ+ policy was found, and directory mentions cannot substitute for one. Keep the visit socially discreet and judge the current room.","review_signal":"Around 1,500 review entries average near 4.0. Loyal guests praise the cosy institution, food and conversation; smoke, pricing, crowded tables and inconsistent service are the repeated negatives.","identity_note":"Historic mixed Zamalek pub sometimes mentioned in gay travel lists but not credibly established as a gay venue.","source_urls":["https://www.facebook.com/Pub28Zamalek","https://wanderlog.com/place/details/1496117","https://www.tripadvisor.com/Restaurant_Review-g294201-d789403-Reviews-Pub_28-Cairo_Cairo_Governorate.html"],"research_status":"current_review_consensus_plus_directory_claim_checked_and_qualified","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Cairo Marriott Hotel & Omar Khayyam Casino","patch":{"queue_wait":"Reception and vehicle security can slow at peak check-in or major functions, but this is managed arrival rather than a nightlife line. Confirm visitor rules and airport transfer details before landing, especially if another person may join you.","best_nights":"Use the property as a base, not a queer-night destination. Garden or dining hours are pleasant for a low-pressure first evening; the value is returning to a staffed Zamalek address after a separately planned cultural night.","crowd_mix":"Egyptian wedding and dining guests, regional business travellers, international tour groups, diplomats and independent visitors. The palace complex is more visitor-heavy than most Cairo nightlife while still functioning as a local social venue.","dress_code":"Travel-smart clothing works around reception and gardens; individual restaurants or the casino may expect a neater look. Conservative presentation outside private rooms remains the context-aware choice.","staff_inclusivity":"A major international chain offers formal service channels and management escalation, but no property-specific LGBTQ+ certification was found. Egypt's legal and social context still applies inside and around the hotel, including to dating-app meetings.","review_signal":"Large review samples praise the historic palace, Nile-adjacent location, grounds and staff. Common negatives include dated rooms, noise, busy public areas and value that varies sharply by room category.","identity_note":"International mixed hotel chosen for infrastructure and location, not a public promise of queer safety.","source_urls":["https://www.marriott.com/en-us/hotels/caieg-cairo-marriott-hotel/overview/","https://roomcard.com/hotel/cairo-marriott-hotel/25437312","https://www.booking.com/hotel/eg/cairo-marriott-casino.html"],"research_status":"official_property_details_plus_large_cross_platform_review_consensus","updated_at":"2026-08-15T00:00:00Z"}}
]
$cairo_place_intel$) r(name text,patch jsonb)
)
update public.places p set venue_intel=coalesce(p.venue_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(p.city))='cairo' and lower(trim(p.name))=lower(trim(r.name));

with researched as (
 select * from jsonb_to_recordset($cairo_event_intel$
[
 {"name":"Cairo International Festival for Experimental Theatre 2026","patch":{"entry_wait":"Access differs by theatre, workshop and performance. Ticket collection plus venue security can bunch close to curtain, so confirm the exact stage and reach it about 45 minutes early rather than navigating from the festival's general headquarters at showtime.","best_arrival":"Forty-five minutes before a performance; earlier for registration-based workshops. Cairo traffic can turn a short map distance into the main delay.","crowd_mix":"Egyptian theatre makers and students, Arab and international companies, critics, cultural workers and public audiences interested in experimental form.","dress_code":"Creative-casual is natural, but the useful rule is comfortable clothing and shoes for a multi-venue day. Individual ceremonies may be smarter than ordinary performances.","host_inclusivity":"The festival's international and experimental mandate creates space for varied artistic expression, but it is not an LGBTQ+ festival and no queer-specific welfare policy was found. Inclusion must be judged at work and venue level.","source_urls":["https://cifet.org/","https://english.ahram.org.eg/NewsContentP/5/556169/Arts--Culture/-Cairo-Int%3Bl-Festival-for-Experimental-Theatre--ca.aspx"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Starlight Festival Egypt 2026","patch":{"entry_wait":"Expect ticket and ID checks, transport staging and full festival security rather than a casual club door. Use only the organiser's official pass and shuttle information, travel with people you trust and arrive before the main-night rush.","best_arrival":"Follow the official transfer slot for the Pyramids nights. The practical best arrival is early enough to clear security in daylight or early evening and understand the return point before the crowd peaks.","crowd_mix":"Egyptian electronic-music fans, regional travellers, international festival visitors, DJs and production crews. The destination format increases the tourist share without making the environment legally or socially separate from Egypt.","dress_code":"Festival-ready shoes, sun and dust protection, a layer for late hours and clothing that remains workable outside the gates. Expressive styling does not remove the need for discretion in transit and public areas.","host_inclusivity":"No explicit LGBTQ+ inclusion or safer-space policy was found on the published festival site. Treat it as a large mixed event in a high-risk national context, not as a protected queer bubble.","source_urls":["https://starlight-festival.org/","https://travel.state.gov/en/international-travel/travel-advisories/destination.egy.html","https://www.gov.uk/foreign-travel-advice/egypt/safety-and-security"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Cairo International Film Festival 2026","patch":{"entry_wait":"Premieres, gala screenings and accreditation desks create the longest waits; ordinary public screenings are easier but still use ticket and venue security. Arrive 45 minutes early at the exact cinema and never assume Opera House headquarters means every film screens there.","best_arrival":"Forty-five minutes before public screenings and earlier for accreditation or a red-carpet event. Build traffic time separately from entry time.","crowd_mix":"Egyptian film audiences, Arab and international filmmakers, critics, students, industry delegates, media and invited guests, with the balance changing between public and gala sessions.","dress_code":"Smart-casual suits normal screenings; premieres and ceremonies can be formal. The festival does not require every audience member to perform red-carpet glamour.","host_inclusivity":"The festival promotes international cultural exchange, but the 2026 programme is not yet complete and no blanket LGBTQ+ safety claim should be made. Evaluate individual films and discussions once the official schedule appears.","source_urls":["https://ciff.org.eg/en/media/news/ciff-announces-the-opening-of-submissions-for-its-47th-edition","https://ciff.org.eg/"],"updated_at":"2026-08-15T00:00:00Z"}}
]
$cairo_event_intel$) r(name text,patch jsonb)
)
update public.events e set event_intel=coalesce(e.event_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(e.city))='cairo' and lower(trim(e.name))=lower(trim(r.name));

with researched as (
 select * from jsonb_to_recordset($cairo_service_intel$
[
 {"name":"Bedayaa Organization","patch":{"booking_lead_time":"Start by email or the official contact channel and allow the team to choose a safe response method. Legal emergencies, health support, counselling and refugee work use different routes; do not travel to an assumed office.","best_time":"Weekday daytime is the clearest first contact. Put urgency and service need in the subject line without describing intimate details that are unnecessary for triage.","client_mix":"LGBTQI+ people in Egypt and Sudan, including people needing legal help, sexual-health or HIV support, psychosocial care and queer refugees navigating protection systems.","preparation":"Use a private device and account where possible, remove identifying previews from a locked screen and ask before sending IDs, chat logs or medical records. Agree the communication and meeting method first.","provider_inclusivity":"Bedayaa is queer-led and explicitly built around sexual orientation, gender identity and expression. Its legal, health and refugee programmes make inclusion a direct service mandate rather than an inferred reputation.","source_urls":["https://bedayaa.org/","https://bedayaa.org/programs/legal-aid-program/","https://bedayaa.org/programs/health-program/","https://bedayaa.org/programs/the-queer-refugee-empowerment-program/"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Cairo 52 Legal Research Institute","patch":{"booking_lead_time":"Email the pro-bono legal-aid address as early as safely possible. Mark an arrest, summons or imminent hearing as urgent; ordinary rights questions may need more response time.","best_time":"Contact during Egyptian weekday hours, but do not wait for business hours if detention or immediate legal danger is involved. A trusted person can also make first contact when the affected person cannot.","client_mix":"LGBTQ+ Egyptians and others facing morality, debauchery, cybercrime or identity-related prosecution, plus lawyers, researchers and advocates working on the same legal environment.","preparation":"Write a short timeline and preserve relevant notices or messages securely. Do not forward explicit images, full dating-app histories or unnecessary identity documents in the first email; ask counsel what evidence is needed.","provider_inclusivity":"The institute's legal aid and research are explicitly focused on LGBTQ+ rights in Egypt. The service understands the interaction between online evidence, police practice and morality-law prosecutions.","source_urls":["https://cairo52.com/contact/","https://cairo52.com/","https://cairo52.com/wp-content/uploads/2023/11/Your-Kind-Is-Not-Welcome-Here-ENG.pdf"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"St Andrew's Refugee Services","patch":{"booking_lead_time":"Check eligibility and current intake by phone before visiting. Legal, psychosocial, education and community programmes have different appointment paths, and high demand can make same-day service unrealistic.","best_time":"Sunday to Thursday during the published 09:00-17:00 partner hours, preferably early enough for triage. Confirm holiday closures and the exact department first.","client_mix":"Refugees and asylum seekers from many nationalities and backgrounds in Greater Cairo, including people needing protection, legal, psychosocial, education or community support.","preparation":"Bring UNHCR or case documents only when requested, keep copies separate from originals and explain any language or accessibility need. Queer refugees can ask for a confidential referral without disclosing details at a public reception desk.","provider_inclusivity":"StARS is refugee-centred rather than LGBTQ+-specialist. Its broad legal and psychosocial remit can provide an entry point, while Bedayaa's queer-refugee programme is the more identity-specific route when safe and appropriate.","source_urls":["https://www.stars-egypt.org/","https://help.unhcr.org/egypt/en/partners/st-andrews-refugee-services-stars/","https://bedayaa.org/programs/the-queer-refugee-empowerment-program/"],"updated_at":"2026-08-15T00:00:00Z"}}
]
$cairo_service_intel$) r(name text,patch jsonb)
)
update public.services s set service_intel=coalesce(s.service_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(s.city))='cairo' and lower(trim(s.name))=lower(trim(r.name));

commit;

select 'places_with_complete_intel' check_name,count(*) result from public.places where lower(trim(city))='cairo' and coalesce(venue_intel->>'queue_wait','')<>'' and coalesce(venue_intel->>'best_nights','')<>'' and coalesce(venue_intel->>'crowd_mix','')<>'' and coalesce(venue_intel->>'dress_code','')<>'' and coalesce(venue_intel->>'staff_inclusivity','')<>''
union all select 'events_with_complete_intel',count(*) from public.events where lower(trim(city))='cairo' and coalesce(event_intel->>'entry_wait','')<>'' and coalesce(event_intel->>'host_inclusivity','')<>''
union all select 'services_with_complete_intel',count(*) from public.services where lower(trim(city))='cairo' and coalesce(service_intel->>'booking_lead_time','')<>'' and coalesce(service_intel->>'provider_inclusivity','')<>''
order by check_name;
