-- Queer Atlas: Turin curated city package
-- Researched and checked 2026-08-14. Idempotent, constraint-safe and apostrophe-safe.

begin;

with src as (
 select * from jsonb_to_recordset($turin_places$
[
 {"name":"Nora Book & Coffee","city":"turin","type":"cafe","description":"A transfeminist bookshop-cafe where Turin's queer life is visible in daylight: roughly five thousand titles, small-press shelves, reading groups, presentations and a plant-filled room for coffee or bicerin. Recent visitors repeatedly describe it as safe, relaxed and genuinely local. A smaller number flag worn facilities or dairy cross-contamination, so ask clearly about allergies rather than assuming the vegan-friendly menu means a separate preparation area.","vibe":"warm transfeminist bookshop-cafe with serious shelves and neighbourly conversation","hours":"Current listings show Tuesday-Friday from 08:00 and daytime-to-evening service; weekend and Monday hours vary. Check the current social page before a special journey.","link":"https://compravicino.comune.torino.it/epic/nora-book-coffee/","location":"Via delle Orfane 24/D, 10122 Torino, Italy","lat":45.0758638,"lng":7.6796470},
 {"name":"CasArcobaleno and Barcolbaleno","city":"turin","type":"cafe","description":"Turin's LGBTQIA+ community house gathers associations, listening desks, workshops, games and public events around a central hall and the small Barcolbaleno. It is a place to meet the city's organised community rather than consume a rainbow-branded night. Services are freely accessible, while bar activity can require a current ARCI or Arcigay card; check the calendar because a quiet advice session and a packed social evening use the same address very differently.","vibe":"community living room joining mutual aid, associations and low-pressure social nights","hours":"Service and event led. The bar opens for listed activities and may require ARCI or Arcigay membership; consult the current calendar.","link":"https://casarcobaleno.it/gli-spazi/","location":"Via Bernardino Lanino 3/A, 10152 Torino, Italy","lat":45.0785170,"lng":7.6831092},
 {"name":"Centralino Club","city":"turin","type":"club","description":"A long-running central nightclub used for queer Friday formats, Pride parties and multi-room dancing. The useful truth is mixed: loyal guests praise energetic music, security and memorable nights, while a substantial review trail reports expensive drinks, unclear entry decisions and alleged poor treatment of tourists or non-Italians. Pick a named queer event, confirm its door rules and keep another plan rather than treating the address as a guaranteed welcome every weekend.","vibe":"historic multi-room queer club energy with a sharply debated door","hours":"Current listings show Friday openings around 23:00, with Saturday or special dates programmed separately; verify the exact event and ticket terms.","link":"https://www.torinopride.it/facebook-event/torino-pride-official-party/","location":"Via delle Rosine 16, 10123 Torino, Italy","lat":45.0657206,"lng":7.6918181},
 {"name":"Nasty Club","city":"turin","type":"club","description":"A two-room club inside Parco del Valentino, now home to Bananamia's long-running Friday LGBTQ+ party. Pop, reggaeton and hits share the building with a courtyard and chill area, creating more of a broad party than an intimate gay bar. The queer programme is current, but so is a serious operational caveat: police reported 841 people against an authorised 550 during a May 2026 inspection. Buy for a named night, watch crowd density and leave if movement or exits feel compromised.","vibe":"big Friday pop party with courtyard breathing space and an important crowding caveat","hours":"Friday and Saturday nights commonly run about 23:00-04:30; Bananamia is Friday. Confirm the current promoter listing and admission policy.","link":"https://xceed.me/en/torino/venue/nasty-club","location":"Corso Massimo d'Azeglio 3, 10125 Torino, Italy","lat":45.0578692,"lng":7.6873680},
 {"name":"011 Sauna Club","city":"turin","type":"sauna","description":"An 800-square-metre men-only membership club in a converted factory, combining Finnish and Turkish heat, bars, cabins, cinema and a large labyrinth. Friday becomes naked-with-mask after 20:00; Saturday is fully naked. Fresh reviews range from exceptionally warm hosting and well-kept spaces to complaints about cleanliness, broken facilities, abrupt staff and tourist treatment. The scale is real, but verify what is operating and ask for the full entry price before paying.","vibe":"large men-only sauna that turns into a dress-coded cruise club on weekend nights","hours":"Monday 14:00-20:30; Tuesday-Thursday and Sunday 14:00-22:00; Friday 14:00-02:00; Saturday 14:00-04:00. ARCO membership required.","link":"https://www.011saunaclub.it/","location":"Via Messina 5/D, 10153 Torino, Italy","lat":45.0758611,"lng":7.6934661},
 {"name":"Garage Club Torino","city":"turin","type":"sauna","description":"A smaller men-only membership sauna and cruise club near Porta Nuova, with steam, dry heat, whirlpool, cabins, cinema and labyrinth-style play space. Its personality is less theatrical than 011: regulars often value the relaxed owner-led welcome and unforced atmosphere. Other visitors describe maintenance, smoke, temperature or opening-time problems, including a recent arrival turned away while the club was listed open. The official 2026 schedule is the best starting point, but a same-day check is wise.","vibe":"compact local men's sauna where timing and working facilities matter more than spectacle","hours":"Official 2026 schedule: daily from 15:00; Monday to 20:30, Tuesday-Thursday to 23:30, Friday to 03:00. Weekend details and themed formats should be confirmed.","link":"https://www.garageclub.it/","location":"Corso Stati Uniti 35, 10129 Torino, Italy","lat":45.0636503,"lng":7.6672070},
 {"name":"La Boulandrola","city":"turin","type":"cafe","description":"A small San Salvario cafe, kitchen and pantry whose queer signal is lived through politics, familiar symbols and an openly engaged team rather than nightclub branding. Reviews describe a calm, personal room, friendly service, good coffee, local products and useful vegan choices; a few find individual dishes uneven. Come for breakfast, lunch or merenda sinoira and conversation, not for a late scene or a guaranteed event.","vibe":"politically engaged neighbourhood cafe with vegan choices and an easy queer welcome","hours":"Monday 08:30-20:00; Tuesday-Friday 07:30-20:00; Saturday 08:30-20:00; Sunday closed. Recheck holiday hours.","link":"https://www.arteaporte.com/host/la-boulandrola/","location":"Via Madama Cristina 45, 10125 Torino, Italy","lat":45.0549007,"lng":7.6810538},
 {"name":"Bunker","city":"turin","type":"club","description":"A post-industrial culture site in Barriera di Milano used for music, talks, installations and large public programmes such as Equi.Voci. It is not a permanent gay club, which is precisely why the event name matters: on an inclusion-led date it offers space and production scale beyond Turin's small dedicated venues; on another night the audience may be entirely mixed. Check access, transport and registration for the exact programme.","vibe":"raw industrial culture ground that becomes queer through carefully chosen public programming","hours":"Open for announced events only; individual programmes publish their own door, registration and closing times.","link":"https://eventi.comune.torino.it/calendario/equi-voci-all-freaks-free/","location":"Via Niccolò Paganini 0/200, 10154 Torino, Italy","lat":45.0870728,"lng":7.7045345}
]
$turin_places$) p(name text,city text,type text,description text,vibe text,hours text,link text,location text,lat double precision,lng double precision)
), upd as (
 update public.places p set type=s.type,description=s.description,vibe=s.vibe,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)) returning p.id
)
insert into public.places(name,city,type,description,vibe,vibe_tags,hours,link,location,lat,lng,seo_indexable,seo_quality_status,updated_at)
select name,city,type,description,vibe,array[]::text[],hours,link,location,lat,lng,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.places p where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)));

with src as (
 select * from jsonb_to_recordset($turin_events$
[
 {"name":"Lovers Film Festival 2026","city":"turin","description":"The 41st edition brought more than fifty LGBTQI+ films from twenty-one countries to Cinema Massimo from 16 to 21 April. Founded from Ottavio Mai and Giovanni Minerba's challenge to stereotyped queer cinema, Lovers is now Europe's longest-running LGBTQI+ film festival and one of the clearest reasons Turin's cultural authority exceeds its nightlife scale.","link":"https://www.loversff.com/","date":"2026-04-16","start_date":"2026-04-16","end_date":"2026-04-21","location":"Cinema Massimo, Via Giuseppe Verdi 18, 10124 Torino, Italy","lat":45.0682681,"lng":7.6925087,"vibe":"international queer cinema with deep local memory and serious public conversation"},
 {"name":"Equi.Voci - All Freaks Free 2026","city":"turin","description":"A free registered day at Bunker on 9 May joined talks, workshops, games and film with evening performance and DJs. Its four axes—gender equality, LGBTQ+ rights, multiculturality and accessibility—made inclusion the actual programme. The 2026 edition addressed queer youth minority stress and mental wellbeing rather than reducing the topic to party aesthetics.","link":"https://eventi.comune.torino.it/calendario/equi-voci-all-freaks-free/","date":"2026-05-09","start_date":"2026-05-09","end_date":"2026-05-09","location":"Bunker, Via Niccolò Paganini 0/200, 10154 Torino, Italy","lat":45.0870728,"lng":7.7045345,"vibe":"free youth-facing inclusion festival moving from workshops into performance and DJs"},
 {"name":"Torino Pride 2026","city":"turin","description":"Turin marked twenty years since its first city Pride with the Venti di lotte march on 6 June. The procession left Parco del Valentino at 15:30 for Piazza Vittorio Veneto. Quiet spaces, a seated access bus, LIS interpretation, water, medical support and free rapid HIV and syphilis testing made the practical access plan unusually substantial.","link":"https://www.torinopride.it/pride/pride-2026/","date":"2026-06-06","start_date":"2026-06-06","end_date":"2026-06-06","location":"Parco del Valentino to Piazza Vittorio Veneto, Torino, Italy","lat":45.0523928,"lng":7.6849361,"vibe":"twentieth-anniversary march where protest, public care and city-scale celebration met"},
 {"name":"Torino Pride Official Party 2026","city":"turin","description":"The community fundraiser continued at Centralino from 20:30 after the march, with food, several rooms and a quiet zone. Entry was €10 before 22:00 and €15 later with one drink, no presale or guest list, and proceeds supported Torino Pride. Companion pricing, earplugs and accessibility information distinguished it from a generic branded club afterparty.","link":"https://www.torinopride.it/facebook-event/torino-pride-official-party/","date":"2026-06-06","start_date":"2026-06-06","end_date":"2026-06-07","location":"Centralino Club, Via delle Rosine 16, 10123 Torino, Italy","lat":45.0657206,"lng":7.6918181,"vibe":"community-funded Pride release across club rooms with a calmer access option"},
 {"name":"Bananamia Fridays - August 2026","city":"turin","description":"Turin's LGBTQ+ Friday institution, running since 1991, now takes over Nasty Club with pop, reggaeton, hits and two-room energy. This listing covers the remaining August Fridays rather than pretending the party is tied to one permanent era or address. Check the promoter immediately before travel, especially because door formats and seasonal pauses can change.","link":"https://t.me/banana_mia","date":"2026-08-21","start_date":"2026-08-21","end_date":"2026-08-28","location":"Nasty Club, Corso Massimo d'Azeglio 3, 10125 Torino, Italy","lat":45.0578692,"lng":7.6873680,"vibe":"long-running Friday LGBTQ+ pop ritual with a broad, youthful city crowd"},
 {"name":"Supermedium - Festival delle Colline Torinesi 2026","city":"turin","description":"Núria Guiu Sagarra's Italian premiere places eight female or non-binary performers in a ritual contemporary-dance work where bodies channel inherited gestures and multiple identities. It plays Teatro Astra on 17 October at 21:00 and 18 October at 17:00, giving the autumn queer-cultural calendar a formally ambitious alternative to club programming.","link":"https://www.fondazionetpe.it/festival/supermedium/","date":"2026-10-17","start_date":"2026-10-17","end_date":"2026-10-18","location":"Teatro Astra, Via Rosolino Pilo 6, 10143 Torino, Italy","lat":45.0772509,"lng":7.6503956,"vibe":"ritual contemporary dance where gender-expansive bodies become a living archive"},
 {"name":"EuroPride Torino 2027","city":"turin","description":"EuroPride returns to Italy in Turin from 18 to 26 June 2027, culminating in the march and closing programme on Saturday 26 June. The official programme is still developing, so this is a planning anchor rather than a fabricated schedule. Expect a citywide rights, culture and community week built on Turin's unusually long activist history.","link":"https://www.europride2027.eu/en/","date":"2027-06-18","start_date":"2027-06-18","end_date":"2027-06-26","location":"Citywide programme and final march in Torino, Italy","lat":45.0651446,"lng":7.6948871,"vibe":"major European Pride week rooted in Turin's activist, civic and cultural infrastructure"}
]
$turin_events$) e(name text,city text,description text,link text,date date,start_date date,end_date date,location text,lat double precision,lng double precision,vibe text)
), upd as (
 update public.events e set description=s.description,link=s.link,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)) returning e.id
)
insert into public.events(name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.events e where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)));

with src as (
 select * from jsonb_to_recordset($turin_services$
[
 {"name":"Maurice GLBTQ","city":"turin","type":"other","provider_name":"Maurice GLBTQ APS","contact":"segreteria@mauriceglbtq.org","booking_link":"https://www.mauriceglbtq.org/","description":"A queer community organisation founded in 1985, combining peer groups, anti-discrimination support, migrant and refugee work, trans and non-binary connection and a specialist library of more than six thousand volumes. Maurice is useful both when something has gone wrong and when someone simply needs community. Match the request to the correct desk instead of arriving expecting every volunteer or professional at once.","hours":"Library Monday-Friday 15:30-18:30; study space generally 15:00-19:00 except Tuesday. Groups and specialist desks follow their own calendar.","link":"https://www.mauriceglbtq.org/","location":"Via Stampatori 10, 10122 Torino, Italy","lat":45.0723708,"lng":7.6782132,"price_tier":"$","vibe":"historic community care joining peer knowledge, books, rights and practical solidarity","source":"Maurice GLBTQ official site and City of Turin LGBTQIA+ directory; checked 2026-08-14"},
 {"name":"Pronto Arcigay Torino","city":"turin","type":"other","provider_name":"Arcigay Torino Ottavio Mai","contact":"accoglienza@arcigaytorino.it; +39 011 765 0051","booking_link":"https://www.arcigaytorino.it/servizi/sportello-accoglienza/","description":"A trained volunteer listening and welcome desk for questions about orientation, gender identity, family or workplace acceptance and the local LGBTQIA+ network. It also supports people seeking asylum after sexual-orientation or gender-identity persecution. This is an orientation doorway, not an emergency line or a replacement for specialist legal or clinical care.","hours":"Friday 16:30-19:30 by email appointment only.","link":"https://www.arcigaytorino.it/servizi/sportello-accoglienza/","location":"CasArcobaleno, Via Bernardino Lanino 3/A, 10152 Torino, Italy","lat":45.0785170,"lng":7.6831092,"price_tier":"$","vibe":"confidential first conversation connecting people to community and specialist pathways","source":"Arcigay Torino official service page; checked 2026-08-14"},
 {"name":"SanArcobaleno","city":"turin","type":"wellness","provider_name":"Arcigay Torino and partner health professionals","contact":"Check the current CasArcobaleno and Arcigay calendar","booking_link":"https://www.arcigaytorino.it/","description":"A recurring community sexual-health service offering free, anonymous rapid HIV and syphilis testing with medical consultation and referral around other STIs. Its placement inside CasArcobaleno lowers the threshold for people who avoid a hospital route. Sessions are periodic rather than daily, so use the published date and never delay urgent post-exposure care while waiting for the next community evening.","hours":"Periodic listed sessions, often monthly; registration and final access time follow the current announcement.","link":"https://www.arcigaytorino.it/","location":"CasArcobaleno, Via Bernardino Lanino 3/A, 10152 Torino, Italy","lat":45.0785170,"lng":7.6831092,"price_tier":"$","vibe":"low-threshold anonymous testing inside a familiar queer community space","source":"Arcigay Torino and Torino Pride official service information; checked 2026-08-14"},
 {"name":"TO Housing","city":"turin","type":"other","provider_name":"Associazione Quore APS","contact":"tohousing@quore.org","booking_link":"https://www.quore.org/to-housing-accoglienza-lgbtqi/","description":"A protected LGBTQI+ housing and reintegration programme with capacity for up to twenty-four guests across five apartments. It is designed for people facing severe vulnerability, including youth expelled by family, migrants and refugees, isolated elders and trans people. The listed Quore office handles contact; residential addresses remain private. Admission follows case assessment and available capacity, not tourist-style direct booking.","hours":"Case-led contact by email; meetings are arranged after initial assessment. Protected residences are not public drop-in locations.","link":"https://www.quore.org/to-housing-accoglienza-lgbtqi/","location":"Associazione Quore operational office, Via Sant'Agostino 12, 10121 Torino, Italy","lat":45.0744069,"lng":7.6798711,"price_tier":"$","vibe":"confidential housing stability and social reintegration for LGBTQI+ people in serious need","source":"Associazione Quore official TO Housing and contact pages; checked 2026-08-14"},
 {"name":"CIDIGeM Torino","city":"turin","type":"wellness","provider_name":"AOU Città della Salute e della Scienza di Torino","contact":"cidigem@cittadellasalute.to.it","booking_link":"https://www.torinogiovani.it/luoghi/cidigem-centro-interdipartimentale-disforia-di-genere-molinette","description":"Piedmont's public multidisciplinary reference centre for people with gender incongruence, with coordination across psychological, endocrine and other specialist care and collaboration for minors through Regina Margherita. Initial contact is email only. Community accounts value access to public assessment and endocrinology but repeatedly describe long waits, cancelled appointments and difficult communication, so Maurice or another peer service can help with navigation while the clinical route proceeds.","hours":"Initial access only by email; there is no telephone desk. Appointment times are assigned by the clinical service.","link":"https://www.torinogiovani.it/luoghi/cidigem-centro-interdipartimentale-disforia-di-genere-molinette","location":"Ospedale San Giovanni Antica Sede, Via Cavour 31, 4th floor, 10123 Torino, Italy","lat":45.0635579,"lng":7.6878954,"price_tier":"$","vibe":"public specialist gender care with an important role and documented access friction","source":"Torino Giovani current municipal listing and AOU Città della Salute; community access reports checked 2026-08-14"}
]
$turin_services$) s(name text,city text,type text,provider_name text,contact text,booking_link text,description text,hours text,link text,location text,lat double precision,lng double precision,price_tier text,vibe text,source text)
), upd as (
 update public.services x set type=s.type,provider_name=s.provider_name,contact=s.contact,booking_link=s.booking_link,description=s.description,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,price_tier=s.price_tier,vibe=s.vibe,source=s.source,"lastChecked"='2026-08-14'::date,verified=true,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)) returning x.id
)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified,seo_indexable,seo_quality_status,updated_at)
select name,city,type,provider_name,contact,booking_link,description,hours,link,array[]::text[],location,lat,lng,price_tier,vibe,array[]::text[],source,'2026-08-14'::date,true,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.services x where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)));

commit;

select 'places' check_name,count(*) result from public.places where lower(trim(city))='turin'
union all select 'events',count(*) from public.events where lower(trim(city))='turin'
union all select 'services',count(*) from public.services where lower(trim(city))='turin'
union all select 'missing_coordinates',count(*) from (
 select lat,lng from public.places where lower(trim(city))='turin'
 union all select lat,lng from public.events where lower(trim(city))='turin'
 union all select lat,lng from public.services where lower(trim(city))='turin'
) q where lat is null or lng is null
order by check_name;
