-- Queer Atlas: Saugatuck, Salt Lake City, Halifax, Minneapolis and Cardiff.
-- Researched 2026-08-27 from first-party operators, Pride/community organisations,
-- destination-marketing bodies and public-health providers. Idempotent.

begin;

alter table if exists public.places add column if not exists venue_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.services add column if not exists service_intel jsonb not null default '{}'::jsonb;

do $qa_require_qari$
declare k text;
begin
  foreach k in array array['country:united-states','country:canada','country:united-kingdom'] loop
    if not exists(select 1 from public.qa_qari_profiles where destination_key=k and scope_type='country' and is_published=true) then
      raise exception 'Published QARI profile % is required before this city batch can run.', k;
    end if;
  end loop;
end;
$qa_require_qari$;

with src as (
 select * from jsonb_to_recordset($qa_cities$
[
 {"slug":"saugatuck","name":"Saugatuck","title":"Queer Saugatuck","country":"United States","country_code":"US","latitude":42.6550,"longitude":-86.2016,"timezone":"America/Detroit","vibe":"lakeside, multigenerational and resort-social","local_mood":"Saugatuck and neighbouring Douglas form one shared queer destination: beach days, arts businesses, LGBTQ-owned lodging and the large Dunes entertainment resort are connected by a small-town summer rhythm.","queer_status":"Dedicated resorts and year-round queer-owned businesses give the area unusual visibility for its size, while access and opening patterns remain strongly seasonal.","crowd_profile":"Midwest weekenders, gay men, lesbian couples, trans and non-binary visitors, artists, campers, older regulars and mixed families overlap without forming one single nightlife crowd.","introduction":"Read Saugatuck together with Douglas and nearby Fennville. The Dunes is both accommodation and the main nightlife complex, Campit provides an LGBTQ outdoor-resort community, Uncommon Coffee supplies a queer-founded daytime room, and Oval Beach is the classic queer-popular public beach. CommUNITY Pride and a dense network of LGBTQ-owned lodging make the destination deeper than its tiny population suggests.","guide_items":[{"title":"About","text":"The Art Coast is a two-town queer resort ecosystem rather than a conventional gay district. Dedicated resorts, galleries, hospitality businesses and Pride organising share the load."},{"title":"Districts","text":"Downtown Saugatuck holds cafés, shopping and the riverfront; Douglas contains The Dunes and several stays; Campit sits south near Fennville and requires a car."},{"title":"Safety","text":"The resort area is openly welcoming, but beach, boating and alcohol safety matter. Confirm seasonal transport and never treat a public beach as a private cruising venue."},{"title":"Nightlife","text":"The Dunes programme drives late nights; Campit is registered-guest community space. Check current calendars because weekdays and shoulder season differ sharply from summer weekends."},{"title":"Cost","text":"Summer weekends and festivals raise room rates. Parking, beach admission and ride availability should be planned before relying on a compact-looking map."}],"guide_sources":[{"label":"Saugatuck tourism LGBTQ guide","url":"https://saugatuck.com/why-the-art-coast-is-a-must-visit-destination-for-the-lgbtq-traveler/"},{"label":"The Dunes Resort","url":"https://dunesresort.com/"},{"label":"Community Pride MI","url":"https://www.communitypridemi.org/"}],"safety_context":"Saugatuck-Douglas has unusually visible queer infrastructure, but it is seasonal and geographically spread. Confirm venue dates, arrange a sober ride between towns and respect campground membership and public-beach rules.","qari_key":"country:united-states"},
 {"slug":"salt_lake_city","name":"Salt Lake City","title":"Queer Salt Lake City","country":"United States","country_code":"US","latitude":40.7608,"longitude":-111.8910,"timezone":"America/Denver","vibe":"mountain-framed, resilient and unexpectedly visible","local_mood":"Salt Lake City's queer life balances long-running bars, newer drag-led clubs, community infrastructure and a visible Harvey Milk Boulevard within Utah's more conservative statewide context.","queer_status":"A concentrated group of dedicated venues and multiple Pride organisations creates real urban visibility; state politics and liquor rules still shape the visitor experience.","crowd_profile":"Local gay men, lesbians, trans and non-binary people, former-LDS residents, students, drag audiences, leather communities, allies and outdoor travellers mix across distinct venues.","introduction":"Salt Lake City has a real permanent circuit rather than occasional queer nights alone. Try-Angles and Sun Trapp provide veteran bar culture, MILK+ and Why Kiki lead drag and dance programming, and Metro Music Hall hosts larger queer productions. Utah Pride Center adds year-round resources, while SLC Pride and Utah Pride programmes reflect a community with more than one organising voice.","guide_items":[{"title":"About","text":"The city is more progressive and queer-visible than Utah stereotypes imply, but local warmth should not be confused with uniform statewide politics."},{"title":"Districts","text":"Harvey Milk Boulevard around 900 South links Try-Angles and MILK+; Sun Trapp and Metro sit west of downtown, while Why Kiki is central."},{"title":"Safety","text":"Bring physical ID because Utah bars check everyone. Track late-night transport, altitude and dehydration, and consult current local guidance for policy changes."},{"title":"Nightlife","text":"Start with a neighbourhood bar, then move to MILK+, Why Kiki or a Metro programme. Theme nights materially change audience, dress and cover."},{"title":"Cost","text":"Covers and special events vary; downtown hotels can spike around conventions and ski weekends, although TRAX makes much of the circuit reachable."}],"guide_sources":[{"label":"Visit Salt Lake LGBTQ guide","url":"https://www.visitsaltlake.com/articles/post/out-in-salt-lake-city-an-lgbtq-guide-to-utahs-unexpectedly-cool-capital/"},{"label":"Visit Salt Lake bars","url":"https://www.visitsaltlake.com/blog/stories/post/salt-lakes-lgbtq-bars/"},{"label":"Utah Pride Center","url":"https://utahpridecenter.org/"}],"safety_context":"Salt Lake has durable queer venues and support organisations alongside a changeable political environment. Carry ID, verify event rules and distinguish city-level inclusion from statewide conditions.","qari_key":"country:united-states"},
 {"slug":"halifax","name":"Halifax","title":"Queer Halifax","country":"Canada","country_code":"CA","latitude":44.6488,"longitude":-63.5752,"timezone":"America/Halifax","vibe":"maritime, community-led and newly resurgent","local_mood":"Halifax's queer scene combines established community businesses with a new generation of bars after several venue closures; calendars and grassroots networks matter as much as a fixed district.","queer_status":"Stardust, Rumours and BACKLOT restore permanent nightlife capacity, while prideHealth, The Youth Project and queer-run daytime businesses provide deeper regional infrastructure.","crowd_profile":"Two-spirit and LGBTQIA+ locals, university students, military and maritime communities, drag audiences, queer youth, older organisers and Atlantic Canadian visitors meet across different spaces.","introduction":"Halifax is in a period of queer-venue renewal. Stardust offers food, cocktails and performance, Rumours runs a larger queer-owned dance and show programme, and BACKLOT adds an intimate Gottingen Street room. Glitter Bean and Venus Envy remain important daytime anchors. Indulge is deliberately excluded because it closed; current operator evidence is favoured over inherited directory lists.","guide_items":[{"title":"About","text":"Atlantic Canada's largest city supports both nightlife and regional service infrastructure, but venue turnover makes current first-party checks essential."},{"title":"Districts","text":"Barrington and Lower Water hold Stardust, Rumours and Venus Envy; Gottingen has BACKLOT; Glitter Bean sits by the universities on Spring Garden Road."},{"title":"Safety","text":"Downtown is walkable, with ordinary waterfront weather, late-night and consent awareness. Respect Indigenous two-spirit terminology and community-specific programmes."},{"title":"Nightlife","text":"Each current room has a different scale: dinner and shows at Stardust, larger club energy at Rumours, and intimate event-led nights at BACKLOT."},{"title":"Cost","text":"Festival and summer dates lift hotel prices. Some Pride events are ticketed, and late-night rides should be budgeted when weather turns."}],"guide_sources":[{"label":"Discover Halifax 2SLGBTQIA+ resources","url":"https://discoverhalifaxns.com/plan/lgbthalifaxresources/"},{"label":"Halifax Pride","url":"https://www.halifaxpride.com/"},{"label":"prideHealth","url":"https://www.nshealth.ca/pridehealth"}],"safety_context":"Halifax has strong community organisations but a recently changing venue map. Verify doors and calendars on the day, use weather-aware transport and treat youth and clinical services as protected support spaces.","qari_key":"country:canada"},
 {"slug":"minneapolis","name":"Minneapolis","title":"Queer Minneapolis","country":"United States","country_code":"US","latitude":44.9778,"longitude":-93.2650,"timezone":"America/Chicago","vibe":"historic, expansive and community-inventive","local_mood":"Minneapolis sustains one of the Midwest's broadest queer venue mixes, from veteran downtown institutions and neighbourhood bars to women's sports, theatre, leather and youth infrastructure.","queer_status":"Multiple permanent venues, a major free Pride festival and specialised library, clinic and youth services create substantial local infrastructure despite wider state and national policy volatility.","crowd_profile":"Gay men, lesbians, trans and non-binary people, sports fans, leather communities, drag and theatre audiences, queer youth, BIPOC communities and allies find different entry points.","introduction":"Minneapolis should not be reduced to one Hennepin Avenue bar crawl. The Saloon and Gay 90s carry downtown scale; 19 Bar preserves neighbourhood history; LUSH and Roxy's connect food with performance; EAGLE MPLS serves bar, brunch and leather-adjacent communities; Jetset adds a smaller dance room; and A Bar of Their Own centres women's sports. Quatrefoil, Family Tree and QUEERSPACE make the guide useful beyond nightlife.","guide_items":[{"title":"About","text":"The scene is large enough to specialise by audience and format. That diversity is more informative than labelling every stop simply gay-friendly."},{"title":"Districts","text":"Downtown and Loring Park hold the densest cluster; Northeast contains LUSH and Jetset; Seward has A Bar of Their Own; services extend south."},{"title":"Safety","text":"Winter weather and long distances matter. Use normal late-night transport care, verify 18+/21+ rules and respect youth and clinical privacy."},{"title":"Nightlife","text":"Programme first: drag, leather, karaoke, theatre, sports and DJs draw different crowds. Check official calendars rather than assuming every night is interchangeable."},{"title":"Cost","text":"Twin Cities Pride is free, while covers, shows and rides vary. Central hotels peak during Pride, sports and convention weekends."}],"guide_sources":[{"label":"Meet Minneapolis LGBTQ bars","url":"https://www.minneapolis.org/lgbtq-community/bars-clubs/"},{"label":"Twin Cities Pride","url":"https://tcpride.org/"},{"label":"Meet Minneapolis LGBTQ businesses","url":"https://www.minneapolis.org/lgbtq-community/businesses/"}],"safety_context":"Minneapolis offers extensive queer infrastructure but a geographically spread scene and severe seasonal weather. Confirm access ages, use reliable late transport and check current state and national guidance.","qari_key":"country:united-states"},
 {"slug":"cardiff","name":"Cardiff","title":"Queer Cardiff","country":"United Kingdom","country_code":"GB","latitude":51.4816,"longitude":-3.1791,"timezone":"Europe/London","vibe":"compact, cabaret-forward and proudly Welsh","local_mood":"Cardiff's central queer circuit is unusually walkable, linking historic pubs, drag bars, late clubs and a world-class LGBTQ film festival within a few streets.","queer_status":"A durable cluster around St Mary Street and Churchill Way, Pride Cymru, Iris Prize and youth services gives Wales' capital strong public visibility.","crowd_profile":"Welsh LGBTQ+ locals, students, drag audiences, gay men, lesbians, trans and non-binary people, film communities, rugby visitors and allies overlap across clearly different rooms.","introduction":"Cardiff combines heritage and reinvention. The Golden Cross remains the historic pub and cabaret anchor; Mary's leads St Mary Street singalong energy; Pulse and The Kings sustain the Churchill Way club circuit; Eclipse now occupies the former Eagle basement under a new identity; and Dock Feeder offers a broader welcoming bar. The Queer Emporium is not inserted as permanent because its announced August 2026 closure makes the record unstable. Iris Prize provides the strongest confirmed future event.","guide_items":[{"title":"About","text":"The capital's queer core is compact and publicly visible, with Welsh-language identity and major annual events adding depth beyond nightlife."},{"title":"Districts","text":"St Mary Street and Churchill Way form the main walkable circuit; Charles Street holds Eclipse. Film and Pride venues spread only slightly farther."},{"title":"Safety","text":"The centre is busy on event and rugby nights. Use ordinary late-night awareness, confirm basement accessibility and follow each venue's consent rules."},{"title":"Nightlife","text":"Golden Cross is the historic opener; Mary's is cabaret-led; Pulse, Kings and Eclipse run later. Programming determines the best audience fit."},{"title":"Cost","text":"Many bars have free early access but clubs and shows vary. Rugby, Pride and graduation weekends can sharply raise room prices."}],"guide_sources":[{"label":"Visit Cardiff LGBTQ guide","url":"https://www.visitcardiff.com/2025/09/cardiff-friendly-city-lgbtq/"},{"label":"Visit Wales LGBTQ places","url":"https://www.visitwales.com/inspire-me/city-breaks/guide-some-best-lgbt-places-cardiff"},{"label":"Iris Prize","url":"https://irisprize.org/"}],"safety_context":"Cardiff's queer venues are central and established, but operator changes can outpace old directories. Verify current names and hours, plan around major-event crowds and check step-free access for basement rooms.","qari_key":"country:united-kingdom"}
]
$qa_cities$) c(slug text,name text,title text,country text,country_code text,latitude double precision,longitude double precision,timezone text,vibe text,local_mood text,queer_status text,crowd_profile text,introduction text,guide_items jsonb,guide_sources jsonb,safety_context text,qari_key text)
)
insert into public.qa_cities(slug,name,title,country,country_code,latitude,longitude,map_confirmed,timezone,vibe,local_mood,queer_status,crowd_profile,introduction,guide_items,guide_sources,guide_checked_at,safety_context,qari_destination_key,qari_score,qari_summary,qari_confidence,status,updated_at)
select c.slug,c.name,c.title,c.country,c.country_code,c.latitude,c.longitude,true,c.timezone,c.vibe,c.local_mood,c.queer_status,c.crowd_profile,c.introduction,c.guide_items,c.guide_sources,date '2026-08-27',c.safety_context,q.destination_key,q.qari_score,q.summary,q.confidence,'published',timezone('utc',now())
from src c cross join lateral(select destination_key,qari_score,summary,confidence from public.qa_qari_profiles where destination_key=c.qari_key and scope_type='country' and is_published=true order by reviewed_at desc nulls last limit 1) q
on conflict(slug) do update set name=excluded.name,title=excluded.title,country=excluded.country,country_code=excluded.country_code,latitude=excluded.latitude,longitude=excluded.longitude,map_confirmed=true,timezone=excluded.timezone,vibe=excluded.vibe,local_mood=excluded.local_mood,queer_status=excluded.queer_status,crowd_profile=excluded.crowd_profile,introduction=excluded.introduction,guide_items=excluded.guide_items,guide_sources=excluded.guide_sources,guide_checked_at=excluded.guide_checked_at,safety_context=excluded.safety_context,qari_destination_key=excluded.qari_destination_key,qari_score=excluded.qari_score,qari_summary=excluded.qari_summary,qari_confidence=excluded.qari_confidence,status='published',updated_at=excluded.updated_at;

with raw_places as (
 select * from jsonb_to_recordset($qa_places$
[
 {"name":"Campit Outdoor Resort","city":"saugatuck","type":"other","description":"A seasonal LGBTQ outdoor resort and campground near Fennville with cabins, RV and tent sites, pool, clubhouse and programmed community weekends. Registration and guest rules make it a destination community rather than a casual public bar.","hours":"Seasonal; registered-guest access and event times vary by current calendar.","link":"https://www.campitresort.com/","location":"6635 118th Avenue, Fennville, MI 49408, USA","lat":42.549650,"lng":-86.191750,"vibe":"social LGBTQ campground balancing pool days, themed weekends and wooded downtime","q":"Holiday weekends create check-in and pool peaks; complete registration before driving to the gate.","best":"Choose a themed weekend matching the desired crowd, or quieter weekdays for a slower campground stay.","crowd":"LGBTQ adults, couples, solo campers, RV travellers and friend groups; event audiences vary by programme.","dress":"Camp casual and swimwear fit common areas; themed parties publish separate expectations.","staff":"The operator explicitly positions Campit as an LGBTQ resort and publishes conduct and guest procedures.","sources":["https://www.campitresort.com/","https://saugatuck.com/business/campit-outdoor-resort/"]},
 {"name":"Uncommon Coffee Roasters","city":"saugatuck","type":"cafe","description":"A queer-founded, minority-owned downtown coffeehouse and roastery that describes itself as a safe space and employs queer people and allies. It is the strongest verified daytime queer anchor in central Saugatuck.","hours":"Sunday-Thursday 07:00-18:00; Friday-Saturday 07:00-19:00.","link":"https://www.uncommoncoffeeroasters.com/pages/uncommon-coffee-roasters","location":"127 Hoffman Street, Saugatuck, MI 49453, USA","lat":42.656365,"lng":-86.204755,"vibe":"welcoming queer-founded coffee room with local regulars and summer visitor energy","q":"Morning and summer-weekend lines can form; counter service normally moves faster outside breakfast peaks.","best":"Weekday mornings suit local atmosphere; afternoons work for a calm queer-friendly break between shops.","crowd":"Queer locals and staff, artists, remote workers, families and resort visitors share the room.","dress":"Come-as-you-are café clothing; beach and cycling attire are routine.","staff":"The business explicitly documents queer founding, minority ownership and a safe-space employment culture.","sources":["https://www.uncommoncoffeeroasters.com/pages/uncommon-coffee-roasters"]},
 {"name":"Oval Beach","city":"saugatuck","type":"other","description":"Saugatuck's public Lake Michigan beach, long identified by official destination guides as especially popular with LGBTQ visitors. It is not a private queer venue: city rules, lifeguard status and public-family expectations apply.","hours":"Seasonal gate generally 08:00-22:00; verify current city access, parking and lifeguard information.","link":"https://www.saugatuckcity.com/oval-beach.html","location":"690 Perryman Street, Saugatuck, MI 49453, USA","lat":42.662400,"lng":-86.216030,"vibe":"wide Lake Michigan beach with a visible queer following and mixed public crowd","q":"Sunny summer weekends fill parking and the chain ferry approach; arrive early or use authorised transport.","best":"Late morning through sunset in warm weather, with wind and water conditions checked first.","crowd":"LGBTQ visitors, couples, families, swimmers and general beachgoers; no section is private.","dress":"Ordinary public-beach swimwear; comply with bans on alcohol, smoking and dogs.","staff":"City management is general-public; queer relevance comes from sustained destination-guide evidence, not special beach governance.","sources":["https://www.saugatuckcity.com/oval-beach.html","https://saugatuck.com/why-the-art-coast-is-a-must-visit-destination-for-the-lgbtq-traveler/"]},

 {"name":"Club Try-Angles","city":"salt_lake_city","type":"bar","description":"A long-running 21+ gay neighbourhood bar with patio, pool, darts, karaoke, low-cost pours and changing leather, underwear and community theme nights.","hours":"Monday-Friday from 16:00; Saturday from 18:00; Sunday from 14:00; verify closing and event times.","link":"https://clubtryangles.com/","location":"251 West 900 South, Salt Lake City, UT 84101, USA","lat":40.749552,"lng":-111.898562,"vibe":"unpretentious gay dive-bar warmth that becomes louder on theme nights","q":"ID is checked for every entrant; Pride and theme nights can create a compact door line.","best":"Early evening for conversation, Thursday karaoke or published theme nights for a fuller crowd.","crowd":"Gay men anchor the room alongside broader LGBTQ regulars, leather guests and allies.","dress":"Casual bar wear ordinarily; underwear and leather events publish opt-in themes, never assumptions.","staff":"A dedicated gay bar with long local history and current official/community-tourism confirmation.","sources":["https://clubtryangles.com/","https://www.visitsaltlake.com/articles/post/out-in-salt-lake-city-an-lgbtq-guide-to-utahs-unexpectedly-cool-capital/"]},
 {"name":"The Sun Trapp","city":"salt_lake_city","type":"bar","description":"Salt Lake City's oldest operating LGBTQ+ bar, known for a large patio, mason-jar drinks, dancing and a broad community crowd west of downtown.","hours":"Tuesday-Sunday 11:00-01:00; closed Monday; confirm holiday changes.","link":"https://www.suntrappslc.com/","location":"102 South 600 West, Salt Lake City, UT 84101, USA","lat":40.766941,"lng":-111.908572,"vibe":"veteran LGBTQ patio bar shifting from daytime socialising to late dancing","q":"Universal ID checks apply; weekend dance hours and Pride dates produce the longest wait.","best":"Patio afternoons for conversation, then Friday or Saturday late evening for dancing.","crowd":"A multigenerational LGBTQ crowd, downtown visitors and allies; the patio broadens the mix.","dress":"Relaxed bar clothing; weather layers matter on the patio.","staff":"The venue explicitly identifies as LGBTQ and is independently confirmed by Visit Salt Lake.","sources":["https://www.suntrappslc.com/","https://www.visitsaltlake.com/plan-your-visit/trip-ideas-itineraries/lgbtq-friendly/"]},
 {"name":"MILK+","city":"salt_lake_city","type":"club","description":"An LGBTQ nightclub and food-led social venue on Harvey Milk Boulevard with drag, karaoke, game nights, DJs, patio service and a deliberately broad queer audience.","hours":"Thursday-Sunday 18:00-02:00; individual programmes may start earlier.","link":"https://milkslc.com/","location":"49 East 900 South, Salt Lake City, UT 84111, USA","lat":40.750021,"lng":-111.889481,"vibe":"polished queer club energy combining dinner, drag, games and late dancing","q":"Ticketed drag and weekend club nights can queue; valid physical ID is essential.","best":"Arrive for the named show if performance matters, or later for the dance-floor peak.","crowd":"Queer adults across genders, drag audiences, younger clubgoers and allies.","dress":"Expressive nightlife looks are welcome; specific parties may announce themes.","staff":"The operator explicitly describes MILK+ as an LGBTQ venue built for community and entertainment.","sources":["https://milkslc.com/","https://www.visitsaltlake.com/articles/post/out-in-salt-lake-city-an-lgbtq-guide-to-utahs-unexpectedly-cool-capital/"]},
 {"name":"Why Kiki","city":"salt_lake_city","type":"bar","description":"A queer-owned and staffed inclusive cocktail, drag and dance bar with frequent shows, Sunday brunch and a downstairs silent disco.","hours":"Programme-led, generally Thursday-Sunday; consult the official calendar for doors and closing.","link":"https://www.whykikibar.com/","location":"69 West 100 South, Salt Lake City, UT 84101, USA","lat":40.767003,"lng":-111.893457,"vibe":"playful drag-forward downtown bar moving from cocktails to full dance energy","q":"Brunch and headline drag reservations fill; club entry later uses Utah ID checks.","best":"Book the exact drag or brunch programme, or arrive before the late-night dance surge.","crowd":"Queer locals, drag fans, birthday groups, younger dancers and supportive allies.","dress":"Colourful self-expression works; ordinary smart-casual is equally accepted.","staff":"The venue states it is run and staffed by LGBTQ people while welcoming everyone.","sources":["https://www.whykikibar.com/","https://www.visitsaltlake.com/articles/post/out-in-salt-lake-city-an-lgbtq-guide-to-utahs-unexpectedly-cool-capital/"]},
 {"name":"Metro Music Hall","city":"salt_lake_city","type":"club","description":"A live-music and event hall repeatedly hosting major drag, queer touring shows and local LGBTQ productions. It is an ally venue with queer programming, not a dedicated gay bar every night.","hours":"Event-led; doors and age rules are published per show.","link":"https://metromusichall.com/","location":"615 West 100 South, Salt Lake City, UT 84104, USA","lat":40.766930,"lng":-111.909011,"vibe":"larger-format concert room where queer touring acts and drag nights take over the calendar","q":"Ticketed shows create a security and ID line; sold-out events require earlier arrival.","best":"Attend only for a verified queer programme and follow its published door time.","crowd":"Concert audiences vary; queer events draw drag fans, LGBTQ locals and allies.","dress":"Show-specific self-expression; practical standing-room footwear helps.","staff":"Visit Salt Lake identifies Metro as an ally venue with frequent drag and queer events; not queer-exclusive.","sources":["https://metromusichall.com/","https://www.visitsaltlake.com/blog/stories/post/salt-lakes-lgbtq-bars/"]},
 {"name":"Under the Umbrella Bookstore","city":"salt_lake_city","type":"gay_store","description":"A queer little bookstore carrying LGBTQ+ books, gifts and community programming in the city's Granary District. Its curated shelves provide a sober, all-ages daytime complement to the bar circuit.","hours":"Schedule varies; verify current shop and event hours on the official site before travel.","link":"https://www.undertheumbrellabookstore.com/","location":"511 West 200 South, Suite 120, Salt Lake City, UT 84101, USA","lat":40.764659,"lng":-111.905941,"vibe":"community-minded queer bookstore centring representation, conversation and sober connection","q":"Ordinary shopping has no queue; launches and author events can require early arrival or registration.","best":"Browse during daytime hours or choose a named event that matches the desired age and topic.","crowd":"Queer readers across ages, authors, families, students and supportive allies.","dress":"Everyday retail clothing; respect the privacy of community-event participants.","staff":"The shop explicitly identifies as queer and curates LGBTQ+ authors and content as its core mission.","sources":["https://www.undertheumbrellabookstore.com/","https://www.undertheumbrellabookstore.com/uploads/b/bf6a03c0-ad29-11eb-af2f-916932a4f5c3/Under%20the%20Umbrella_Publicity%20Kit_2025.pdf"]},

 {"name":"Stardust Bar + Kitchen","city":"halifax","type":"bar","description":"A downtown queer bar and kitchen combining cocktails, dinner, drag, cabaret and community events in an intimate Barrington Street room.","hours":"Wednesday-Thursday 15:00-00:00; Friday 15:00-02:00; Saturday 11:00-02:00; Sunday 11:00-00:00.","link":"https://www.stardustbar.ca/","location":"1688 Barrington Street, Halifax, NS B3J 2A2, Canada","lat":44.647117,"lng":-63.574167,"vibe":"warm queer supper-club atmosphere with polished drinks and close-up performance","q":"Brunches, drag and cabaret seatings benefit from reservations; late bar entry varies by capacity.","best":"Book the named performance or visit early for food before the room becomes show-led.","crowd":"Queer adults across genders, drag and theatre audiences, couples and allies.","dress":"Come-as-you-are through expressive cabaret looks; seated dining remains casual.","staff":"The operator explicitly presents Stardust as a queer bar and community gathering space.","sources":["https://www.stardustbar.ca/"]},
 {"name":"Rumours HFX","city":"halifax","type":"club","description":"A queer-owned Lower Water Street bar and nightclub with drag, DJs, karaoke, themed parties, food and a larger dance-floor format.","hours":"Open seven days with programme-specific hours; check the official calendar before travel.","link":"https://www.rumourshfx.com/","location":"1668 Lower Water Street, Halifax, NS B3J 1S4, Canada","lat":44.647209,"lng":-63.571387,"vibe":"high-energy queer-owned club mixing drag spectacle, dancing and community nights","q":"Headline shows and weekend dancing create the main queue; tickets do not remove ID checks.","best":"Match arrival to the show or theme; earlier evening suits food, later hours suit dancing.","crowd":"A broad 2SLGBTQIA+ crowd, students, drag fans, visitors and allies.","dress":"Expressive party wear is common; themed events publish optional prompts.","staff":"Rumours explicitly identifies as queer-owned and builds its programme around queer community.","sources":["https://www.rumourshfx.com/"]},
 {"name":"BACKLOT HFX","city":"halifax","type":"bar","description":"A small queer Gottingen Street bar opened in 2026 with drag, DJs, karaoke and community-led events. Its newness means the live social calendar is more reliable than inherited opening-hour directories.","hours":"Event-led; verify current doors and age rules on the operator's social channel.","link":"https://www.instagram.com/backlothfx/","location":"2103 Gottingen Street, Halifax, NS B3K 3B2, Canada","lat":44.651905,"lng":-63.583008,"vibe":"intimate new queer bar with grassroots performance and neighbourhood energy","q":"The small room reaches capacity quickly for launches and drag; arrive near published doors.","best":"Choose a named event rather than assuming identical nightly operation.","crowd":"Queer locals, performers, students, North End regulars and friends.","dress":"Casual and expressive; programme themes may shift the room.","staff":"Local queer press documents BACKLOT as a dedicated queer venue opened in March 2026.","sources":["https://wayves.ca/backlot-hfx-2026-03","https://www.instagram.com/backlothfx/"]},
 {"name":"Glitter Bean Café","city":"halifax","type":"cafe","description":"A queer-centric, unionised worker-owned cooperative café near the universities, functioning as an affirming daytime room as well as a coffee shop.","hours":"Monday-Friday 07:30-18:00; Saturday 10:00-17:00; Sunday 11:00-16:00.","link":"https://www.glitterbeancafe.com/contact","location":"5896 Spring Garden Road, Halifax, NS B3H 0A6, Canada","lat":44.640758,"lng":-63.584784,"vibe":"queer-centric cooperative café with student, activist and neighbourhood warmth","q":"Lunch and campus peaks can fill seats; counter ordering remains straightforward.","best":"Weekday mid-morning or afternoon for the strongest community-café feel.","crowd":"Queer and trans locals, students, workers, activists and general café customers.","dress":"Everyday café clothing; no appearance gate.","staff":"Discover Halifax identifies it as 2SLGBTQIA+ run, and the cooperative documents worker ownership.","sources":["https://www.glitterbeancafe.com/contact","https://discoverhalifaxns.com/plan/lgbthalifaxresources/lgbt-allied-businesses/"]},
 {"name":"Venus Envy Halifax","city":"halifax","type":"gay_store","description":"A queer- and trans-owned bookstore and sex shop providing inclusive products, books, education and a sensory-friendly Sunday shopping window.","hours":"Monday-Thursday 11:00-19:00; Friday-Saturday 11:00-20:00; Sunday 11:00-18:00; sensory-friendly Sunday 16:00-18:00.","link":"https://venusenvy.ca/pages/halifax-store","location":"1727 Barrington Street, Halifax, NS B3J 2A4, Canada","lat":44.647758,"lng":-63.574190,"vibe":"sex-positive queer bookstore and shop combining practical access with community education","q":"Ordinary retail entry; workshops or launches may have separate registration and capacity.","best":"Use the quieter Sunday sensory window if reduced music, scent and conversation helps.","crowd":"Queer and trans shoppers, readers, educators, couples and curious adults.","dress":"Ordinary retail attire; privacy and consent around other shoppers matter.","staff":"The business explicitly identifies as queer- and trans-owned and publishes affirming access information.","sources":["https://venusenvy.ca/pages/halifax-store"]},

 {"name":"The Saloon","city":"minneapolis","type":"club","description":"A downtown LGBTQ institution since 1977 with multiple bars, dance floor, patio, drag, karaoke, DJs and a major Pride block party.","hours":"Sunday-Thursday 12:00-02:00; Friday-Saturday 12:00-03:00; verify event exceptions.","link":"https://www.saloonmn.com/","location":"830 Hennepin Avenue, Minneapolis, MN 55403, USA","lat":44.976809,"lng":-93.277088,"vibe":"large veteran gay club moving between daytime bar familiarity and packed dance nights","q":"Weekend, Pride and headline-event security lines can be long; bring valid ID.","best":"Early evening for the bar, later Friday or Saturday for dancing, exact calendar for drag.","crowd":"Gay men anchor a broad LGBTQ and ally audience across ages.","dress":"Casual by day and expressive clubwear at night; themed events vary.","staff":"The venue explicitly describes itself as a cornerstone of Minneapolis gay life and remains current in official tourism.","sources":["https://www.saloonmn.com/","https://www.minneapolis.org/lgbtq-community/businesses/"]},
 {"name":"LUSH Lounge & Theater","city":"minneapolis","type":"club","description":"An LGBTQ+ lounge, restaurant and theatre in Northeast Minneapolis with drag, cabaret, brunch, live performance and late social nights.","hours":"Programme-led; restaurant, lounge and theatre doors vary by show.","link":"https://lushmpls.com/","location":"990 Central Avenue NE, Minneapolis, MN 55413, USA","lat":44.995526,"lng":-93.247607,"vibe":"polished queer dinner-and-show room where theatre and nightlife overlap","q":"Ticketed theatre and brunch reservations determine seating; lounge entry remains capacity-dependent.","best":"Book the exact performance and arrive for dinner if a full evening is desired.","crowd":"Queer adults across genders, drag and theatre audiences, brunch groups and allies.","dress":"Smart-casual through celebratory show looks; no single required style.","staff":"LUSH explicitly operates as an LGBTQ+ venue and is current in city tourism guidance.","sources":["https://lushmpls.com/","https://www.minneapolis.org/lgbtq-community/bars-clubs/"]},
 {"name":"A Bar of Their Own","city":"minneapolis","type":"bar","description":"An LGBTQ-owned, family-friendly sports bar dedicated to showing women's sports, with food, vegan and gluten-free options and an explicitly inclusive audience.","hours":"Match and service hours vary; check the official schedule before a specific game.","link":"https://www.abaroftheirown.com/","location":"2207 East Franklin Avenue, Minneapolis, MN 55404, USA","lat":44.962590,"lng":-93.240509,"vibe":"joyful women’s-sports bar centring queer ownership, shared games and all-ages community","q":"Major finals and local-team games fill tables; reservations or early arrival are prudent.","best":"Choose the official screen schedule for the sport and audience you want.","crowd":"LGBTQ sports fans, women and non-binary supporters, families, teams and allies.","dress":"Team gear and casual clothing dominate; no nightlife dress expectation.","staff":"The venue is LGBTQ-owned and explicitly designed as an inclusive home for women's sports.","sources":["https://www.abaroftheirown.com/","https://www.minneapolis.org/lgbtq-community/bars-clubs/"]},
 {"name":"Gay 90's","city":"minneapolis","type":"club","description":"A large multi-room downtown gay nightclub known for La Femme drag, dancing, karaoke, food on selected days and some published 18+ programmes.","hours":"Event-led late-night operation; confirm food, 18+ and room schedules directly.","link":"https://gay90s.com/","location":"408 Hennepin Avenue, Minneapolis, MN 55401, USA","lat":44.980506,"lng":-93.271994,"vibe":"big-room classic gay-club spectacle with drag, dancing and younger-access nights","q":"Security and ID lines grow on weekends; 18+ access applies only to specifically published programmes.","best":"Attend for La Femme or a named party and arrive before the midnight surge.","crowd":"Gay men, broader LGBTQ dancers, drag audiences, younger 18+ guests on eligible nights and allies.","dress":"Club casual to expressive performance looks; event-specific restrictions control entry.","staff":"A long-running gay nightclub continuously documented by the venue and official city tourism.","sources":["https://gay90s.com/","https://www.minneapolis.org/lgbtq-community/bars-clubs/"]},
 {"name":"19 Bar","city":"minneapolis","type":"bar","description":"Minneapolis's historic cash-only gay neighbourhood bar, reopened after fire restoration, with pool, darts, jukebox, patio, karaoke and affordable drinks.","hours":"Monday-Friday 15:00-02:00; Saturday-Sunday 13:00-02:00.","link":"https://www.facebook.com/19BarMinneapolis/","location":"19 West 15th Street, Minneapolis, MN 55403, USA","lat":44.967492,"lng":-93.278811,"vibe":"low-key historic gay bar favouring conversation, pool and neighbourhood regulars","q":"Usually easier than dance clubs; cash-only service and small peak-night capacity deserve preparation.","best":"Early evening for regular-bar atmosphere, karaoke or weekend patio hours for more energy.","crowd":"Multigenerational gay regulars, broader queer locals, pool players and visitors.","dress":"Unfussy casual clothing.","staff":"Official Minneapolis tourism confirms current operation after the fire and its historic gay identity.","sources":["https://www.minneapolis.org/lgbtq-community/bars-clubs/","https://www.minneapolis.org/things-to-do/music-nightlife/food-entertainment/"]},
 {"name":"Roxy's Cabaret","city":"minneapolis","type":"club","description":"A Nicollet Mall queer cabaret venue with drag, brunch, karaoke, games, classic-film events and an upstairs food-and-rooftop component.","hours":"Programme-led; brunch, cabaret and rooftop service use separate schedules.","link":"https://roxyscabaret.com/","location":"1333 Nicollet Mall, Minneapolis, MN 55403, USA","lat":44.970095,"lng":-93.277548,"vibe":"drag-forward cabaret complex mixing seated shows, food and rooftop socialising","q":"Reserved shows and brunches need advance booking; walk-in bar space depends on the event.","best":"Choose a named drag or cabaret programme and arrive before seating begins.","crowd":"Queer adults, drag fans, brunch groups, theatre audiences and allies.","dress":"Smart-casual through celebratory drag-night fashion.","staff":"The operator centres queer cabaret, and official tourism keeps it in the current LGBTQ venue list.","sources":["https://roxyscabaret.com/","https://www.minneapolis.org/lgbtq-community/bars-clubs/"]},
 {"name":"EAGLE MPLS","city":"minneapolis","type":"bar","description":"A gay bar and grill in East Town with brunch, patio, DJs, show-tune Sundays and leather-community lineage without limiting the everyday audience to one subculture.","hours":"Monday-Thursday 15:00-00:00; Friday 15:00-02:00; Saturday 11:00-02:00; Sunday 10:00-00:00.","link":"https://www.eaglempls.com/","location":"515 Washington Avenue South, Minneapolis, MN 55415, USA","lat":44.978374,"lng":-93.260845,"vibe":"friendly gay bar and grill linking patio brunch, leather history and dance nights","q":"Brunch, Show Tunes Sunday and Pride create peaks; ordinary afternoons are more relaxed.","best":"Sunday for brunch and show tunes, warm evenings for the patio, calendar nights for DJs.","crowd":"Gay men, leather communities, neighbourhood diners, dog owners on the patio and wider LGBTQ guests.","dress":"Casual bar wear; leather is welcome but not required.","staff":"The venue identifies as a gay bar and is current in city tourism and LGBTQ business guides.","sources":["https://www.eaglempls.com/","https://www.minneapolis.org/lgbtq-community/bars-clubs/"]},
 {"name":"Jetset Underground","city":"minneapolis","type":"club","description":"A revived Northeast lounge and dance club geared toward the gay community, with DJs, strong cocktails and a smaller, more polished room than the downtown mega-clubs.","hours":"Thursday 17:00-22:00; Friday 17:00-02:00; Saturday 18:00-02:00.","link":"https://www.instagram.com/jetsetunderground/","location":"205 East Hennepin Avenue, Minneapolis, MN 55414, USA","lat":44.987809,"lng":-93.257687,"vibe":"compact gay-oriented lounge with club classics and a polished late-week dance floor","q":"Friday and Saturday capacity is limited; arrive before the main DJ peak.","best":"Later Friday or Saturday for dancing, Thursday for a quieter lounge visit.","crowd":"Gay men, queer dancers, cocktail groups and allies.","dress":"Neat nightlife casual and expressive club looks both fit.","staff":"Meet Minneapolis describes the revived venue as geared toward the gay community.","sources":["https://www.minneapolis.org/lgbtq-community/bars-clubs/","https://www.instagram.com/jetsetunderground/"]},
 {"name":"The Smitten Kitten","city":"minneapolis","type":"gay_store","description":"A trans- and queer-owned, liberation-focused sex shop offering body-safe products, gender-affirming items, education and community mutual-aid activity in Uptown.","hours":"Tuesday-Friday 13:00-20:00; Saturday 11:00-20:00; Sunday 11:00-17:00; closed Monday.","link":"https://smittenkittenonline.com/","location":"3010 Lyndale Avenue South, Minneapolis, MN 55408, USA","lat":44.947928,"lng":-93.288505,"vibe":"sex-positive queer retail grounded in education, bodily autonomy and mutual aid","q":"Ordinary retail access is simple; workshops and benefit events can use separate tickets or capacity.","best":"Weekday afternoon for questions and lower traffic; check the event calendar for community programming.","crowd":"Queer and trans shoppers, couples, educators, kink communities and wider sex-positive customers.","dress":"Everyday retail clothing; consent and other shoppers' privacy are central etiquette.","staff":"The operator explicitly states trans and queer ownership and a liberation-focused, shame-free mission.","sources":["https://smittenkittenonline.com/","https://www.minneapolis.org/lgbtq-community/businesses/"]},
 {"name":"Rainbow Road","city":"minneapolis","type":"gay_store","description":"A long-running downtown LGBTQ+ retail shop specialising in underwear, swimwear, Pride goods, gifts, books and adult products near Loring Park.","hours":"Retail hours vary by day; the official site currently publishes daytime opening and should be checked before travel.","link":"https://rainbowrd.com/","location":"109 West Grant Street, Minneapolis, MN 55403, USA","lat":44.969626,"lng":-93.279930,"vibe":"bright gay retail stop for Pride gear, fashion and practical nightlife shopping","q":"Normal shop entry has no meaningful queue; Pride weekend can make the compact store busier.","best":"Daytime before Loring Park or a night out, especially when sizing help matters.","crowd":"Gay men, broader LGBTQ+ shoppers, Pride visitors, gift buyers and allies.","dress":"Ordinary retail clothing; changing and product questions should be handled respectfully.","staff":"The business's current assortment and specialist queer listings establish a sustained LGBTQ+ retail identity.","sources":["https://rainbowrd.com/","https://minneapolis.gaycities.com/shops?general=lgbtq-owned"]},

 {"name":"The Golden Cross","city":"cardiff","type":"bar","description":"Cardiff's historic LGBTQ+ pub and cabaret venue, operating since the nineteenth century and now known for nightly drag, karaoke and a mixed multigenerational community.","hours":"Monday-Wednesday 12:00-23:00; Thursday 12:00-00:00; Friday-Saturday 12:00-02:00; Sunday 12:00-00:00.","link":"https://www.cardiffgoldencross.com/","location":"283 Hayes Bridge Road, Cardiff CF10 1GH, United Kingdom","lat":51.478110,"lng":-3.171250,"vibe":"historic queer pub warmth with intimate cabaret and late singalong energy","q":"Weekend cabaret fills the small room; early pub hours are usually straightforward.","best":"Early evening for pub history, later for the advertised drag or karaoke host.","crowd":"LGBTQ locals across ages, drag fans, regulars, visitors and allies.","dress":"Come-as-you-are pub clothing through expressive cabaret looks.","staff":"The venue explicitly identifies as Cardiff's oldest LGBTQ+ venue and publishes a current programme.","sources":["https://www.cardiffgoldencross.com/","https://www.visitcardiff.com/2025/09/cardiff-friendly-city-lgbtq/"]},
 {"name":"Mary's Cardiff","city":"cardiff","type":"bar","description":"A St Mary Street LGBTQIA+ cabaret bar known for resident drag, karaoke, cocktails and a lively seven-night central-city rhythm.","hours":"Open seven nights; verify the current daily and performance times.","link":"https://maryscardiff.uk/","location":"89 St Mary Street, Cardiff CF10 1DW, United Kingdom","lat":51.478260,"lng":-3.178330,"vibe":"friendly high-energy gay cabaret bar with singalongs and central-nightlife footfall","q":"Friday, Saturday and headline drag create the main door pressure; arrive before performances.","best":"Select a resident-host night or arrive early enough to settle before karaoke.","crowd":"Broad LGBTQ+ crowd, drag audiences, students, visitors and allies.","dress":"Everyday going-out clothes through flamboyant cabaret looks.","staff":"The bar explicitly centres LGBTQIA+ community and is current in official Cardiff and Wales guides.","sources":["https://maryscardiff.uk/","https://www.visitwales.com/inspire-me/city-breaks/guide-some-best-lgbt-places-cardiff"]},
 {"name":"Pulse Cardiff","city":"cardiff","type":"club","description":"A late LGBTQ+ nightclub on Churchill Way with DJs, drag, karaoke and multi-level dance energy extending well beyond pub closing time.","hours":"Wednesday 20:00-04:00; Friday 20:00-05:00; Saturday 19:00-05:00; verify special events.","link":"https://www.instagram.com/pulsecardiff/","location":"3 Churchill Way, Cardiff CF10 2HD, United Kingdom","lat":51.482210,"lng":-3.172660,"vibe":"big late-night LGBTQ club energy built around drag, pop and weekend dancing","q":"Weekend security lines peak after nearby bars close; bring physical ID and plan the trip home.","best":"Arrive for the named drag feature or before midnight to reduce the queue.","crowd":"Young and mixed LGBTQ clubgoers, drag fans, students, visitors and allies.","dress":"Clubwear and expressive looks; published event rules govern.","staff":"Pulse remains a dedicated LGBTQ venue in current official destination guidance.","sources":["https://www.instagram.com/pulsecardiff/","https://www.visitcardiff.com/2025/09/cardiff-friendly-city-lgbtq/"]},
 {"name":"The Kings","city":"cardiff","type":"bar","description":"A proud LGBTQ+ safe-space bar on Churchill Way with drag bingo, karaoke, DJs and late opening across most of the week.","hours":"Monday-Wednesday 20:00-02:00; Thursday-Saturday 20:00-03:00; closed Sunday.","link":"https://www.canalquarter.uk/thekings","location":"10 Churchill Way, Cardiff CF10 2DX, United Kingdom","lat":51.481750,"lng":-3.173180,"vibe":"welcoming drag-led queer bar bridging weekday games and weekend dancing","q":"Drag bingo and weekend nights can fill; arrive near opening for seats.","best":"Follow the host calendar for bingo or karaoke, then stay later for DJs.","crowd":"LGBTQ adults, trans and non-binary guests, students, drag regulars and allies.","dress":"Come-as-you-are with optional party expression.","staff":"The operator explicitly calls The Kings an LGBTQ+ safe space and publishes conduct expectations.","sources":["https://www.canalquarter.uk/thekings","https://www.visitcardiff.com/2025/09/cardiff-friendly-city-lgbtq/"]},
 {"name":"Eclipse Cardiff","city":"cardiff","type":"club","description":"The current queer basement club at the former Eagle address, operating under the Eclipse name with drag and themed dance nights. The retired Eagle identity is intentionally not retained as an active venue.","hours":"Monday-Wednesday 18:00-01:00; Thursday 18:00-02:00; Friday 18:00-03:00; Saturday 18:00-04:00; Sunday 18:00-01:00.","link":"https://www.instagram.com/eclipsecardiff/","location":"Basement, 39 Charles Street, Cardiff CF10 2GB, United Kingdom","lat":51.480850,"lng":-3.173200,"vibe":"late queer basement club with drag, techno and themed party programming","q":"Basement capacity and event security can create a street-level wait; accessibility should be confirmed before travel.","best":"Choose a specific party and arrive before the later club surge.","crowd":"Queer clubgoers, gay men, drag and electronic-music audiences, students and allies.","dress":"Nightlife and themed looks; event-specific rules apply.","staff":"Current destination and CAMRA records confirm Eclipse as the active successor identity; it is not presented as the closed Eagle.","sources":["https://camra.org.uk/pubs/eclipse-cardiff-133037","https://www.visitcardiff.com/2025/09/cardiff-friendly-city-lgbtq/"]},
 {"name":"The Dock Feeder","city":"cardiff","type":"bar","description":"A welcoming Canal Quarter bar beside the Churchill Way queer cluster, hosting drag and inclusive social events without claiming to be exclusively LGBTQ every night.","hours":"Daily bar service; consult the operator for current doors and event times.","link":"https://www.canalquarter.uk/","location":"18-20 Churchill Way, Cardiff CF10 2DY, United Kingdom","lat":51.481420,"lng":-3.172830,"vibe":"broad city-centre bar with a visible queer welcome and drag-event crossover","q":"Major city events and advertised drag can fill tables; ordinary sessions are less pressured.","best":"Use it as an early social stop or attend a verified queer programme.","crowd":"Mixed local crowd with LGBTQ groups, drag audiences, students and visitors.","dress":"General city-bar casual.","staff":"Visit Cardiff explicitly includes the Dock Feeder among venues welcoming LGBTQ people; no exclusive identity is implied.","sources":["https://www.visitcardiff.com/2025/09/cardiff-friendly-city-lgbtq/","https://www.canalquarter.uk/"]}
]
$qa_places$) p(name text,city text,type text,description text,hours text,link text,location text,lat double precision,lng double precision,vibe text,q text,best text,crowd text,dress text,staff text,sources jsonb)
), places as (
 select p.*,
   case
     when p.type='gay_store' then 'gallery'
     when p.type='other' and p.name='Campit Outdoor Resort' then 'club'
     when p.type='other' and p.name='Oval Beach' then 'cruising_area'
     else p.type
   end as schema_type,
   jsonb_build_object('queue_wait',q,'best_nights',best,'crowd_mix',crowd,'dress_code',dress,'staff_inclusivity',staff,'source_urls',sources,'research_status','current_operator_and_community_source','source_entity_type',p.type,'updated_at','2026-08-27T00:00:00Z') intel
 from raw_places p
), upd as (
 update public.places t set type=p.schema_type,description=p.description,hours=p.hours,link=p.link,location=p.location,lat=p.lat,lng=p.lng,vibe=p.vibe,vibe_tags=array[]::text[],venue_intel=p.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from places p where lower(trim(t.city))=p.city and lower(trim(t.name))=lower(trim(p.name)) returning t.id
)
insert into public.places(name,city,type,description,hours,link,location,lat,lng,vibe,vibe_tags,venue_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,schema_type,description,hours,link,location,lat,lng,vibe,array[]::text[],intel,true,'approved',timezone('utc',now()) from places p where not exists(select 1 from public.places t where lower(trim(t.city))=p.city and lower(trim(t.name))=lower(trim(p.name)));

with raw_events as (
 select * from jsonb_to_recordset($qa_events$
[
 {"name":"Saugatuck-Douglas CommUNITY Pride Week 2027","city":"saugatuck","description":"The next announced CommUNITY Pride week spans Saugatuck and Douglas with public celebration, education, outdoor activities and community fundraising. The organiser has confirmed the dates; the detailed programme should be checked after release.","link":"https://www.communitypridemi.org/pride-week-2026.html","date":"2027-06-02","start_date":"2027-06-02T09:00:00-04:00","end_date":"2027-06-06T22:00:00-04:00","location":"Multiple venues across Saugatuck and Douglas, Michigan","lat":42.650900,"lng":-86.204000,"vibe":"small-town Pride week joining lakeshore leisure, public visibility and local fundraising","q":"Individual activities use different registration, parking and capacity rules; there is no single festival gate.","best":"Wait for the detailed 2027 programme, then reserve limited cruises, runs or talks before travelling.","crowd":"LGBTQ residents and visitors, families, businesses, artists, outdoor participants and allies.","dress":"Activity- and weather-specific; Pride expression is welcome across mixed public settings.","host":"Community Pride MI explicitly organises for LGBTQIA+ inclusion and local affirming organisations.","sources":["https://www.communitypridemi.org/pride-week-2026.html"]},
 {"name":"SLC Pride 2026","city":"salt_lake_city","description":"An intersectional two-day Pride festival at 400 North and 400 West organised around queer, BIPOC, trans, disabled and undocumented community connection. The verified 2026 edition is retained as the latest official benchmark until new dates publish.","link":"https://www.slc-pride.org/","date":"2026-06-27","start_date":"2026-06-27T12:00:00-06:00","end_date":"2026-06-28T19:00:00-06:00","location":"Intersection of 400 North and 400 West, Salt Lake City, Utah","lat":40.773800,"lng":-111.902600,"vibe":"grassroots intersectional Pride centring community overlap and public celebration","q":"Festival entry, security and nearby parking peak after opening; use transit and published access guidance.","best":"Arrive near opening for resources and lower heat, then return for chosen stage programmes.","crowd":"Queer and BIPOC communities, trans and disabled attendees, families, organisers and allies.","dress":"Pride expression with sun, altitude, hydration and mobility needs prioritised.","host":"The organiser explicitly centres overlapping marginalised queer identities and community access.","sources":["https://www.slc-pride.org/"]},
 {"name":"Halifax Pride Festival 2026","city":"halifax","description":"The latest completed Halifax Pride ran for eleven days with a July 18 parade and a calendar of community, cultural and ticketed activities. The official archive remains the source until Canada Pride 2027 details are published.","link":"https://www.halifaxpride.com/","date":"2026-07-16","start_date":"2026-07-16T10:00:00-03:00","end_date":"2026-07-26T23:00:00-03:00","location":"Multiple venues across Halifax, Nova Scotia","lat":44.648800,"lng":-63.575200,"vibe":"regional 2SLGBTQIA+ festival combining parade scale, community access and paid performance","q":"The parade and headline events create transport and security pressure; ticketed events state their own entry rules.","best":"Use the online calendar released near the festival and arrive early for parade positioning.","crowd":"2SLGBTQIA+ Atlantic Canadians, two-spirit participants, families, performers, visitors and allies.","dress":"Weather-ready Pride clothing; each indoor venue may add bag or age rules.","host":"Halifax Pride reviews sponsors for inclusion commitments and aims to keep programming free or low-cost.","sources":["https://www.halifaxpride.com/","https://www.halifaxpride.com/faq"]},
 {"name":"Twin Cities Pride Festival 2026","city":"minneapolis","description":"The latest completed free Twin Cities Pride Festival filled Loring Park with three stages, more than 650 vendors and extensive LGBTQIA2S+ and BIPOC resources, preceded by Youth Night.","link":"https://tcpride.org/2026-vendor-info/","date":"2026-06-27","start_date":"2026-06-27T10:00:00-05:00","end_date":"2026-06-28T18:00:00-05:00","location":"Loring Park, Minneapolis, Minnesota","lat":44.968300,"lng":-93.282700,"vibe":"major free community festival joining entertainment, resources, youth and regional visibility","q":"Entry is free but transport, screening and popular stages create queues; use official transit and accessibility plans.","best":"Morning gives easier resource browsing; map stages and cooling breaks before the afternoon peak.","crowd":"LGBTQIA2S+ people across ages, BIPOC organisations, youth, families, performers and allies.","dress":"Pride expression with sun, rain, hydration and park footwear considered.","host":"Twin Cities Pride explicitly exists to empower LGBTQIA2S+ people and maintains a free festival model.","sources":["https://tcpride.org/2026-vendor-info/","https://tcpride.org/"]},
 {"name":"Iris Prize LGBTQ+ Film Festival 2026","city":"cardiff","description":"Iris celebrates its twentieth edition with seven days of LGBTQ+ films, filmmakers, talks, industry sessions and parties at Cineworld Cardiff, Chapter and partner venues, plus a UK online programme.","link":"https://irisprize.org/","date":"2026-10-12","start_date":"2026-10-12T17:00:00+01:00","end_date":"2026-10-18T23:00:00+01:00","location":"Cineworld Cardiff, Chapter and partner venues, Cardiff, Wales","lat":51.478900,"lng":-3.173700,"vibe":"international queer cinema festival combining screenings, industry access and Cardiff nightlife","q":"Pass collection, premieres and parties can queue; book screenings and access services before arrival.","best":"Plan by thematic day and reserve high-demand screenings; 16 October centres Best British work.","crowd":"LGBTQ filmmakers and audiences, industry delegates, students, international guests and local community.","dress":"Cinema casual by day; opening, awards and parties lean celebratory smart-casual.","host":"Iris is an LGBTQ+ film organisation with captioned and BSL-interpreted accessible screenings in the 2026 programme.","sources":["https://irisprize.org/","https://irisprize.org/news/cineworld-cardiff-to-host-the-20th-anniversary-edition-of-iris-prize/"]}
]
$qa_events$) e(name text,city text,description text,link text,date text,start_date timestamptz,end_date timestamptz,location text,lat double precision,lng double precision,vibe text,q text,best text,crowd text,dress text,host text,sources jsonb)
), events as (
 select e.*,jsonb_build_object('entry_wait',q,'best_arrival',best,'crowd_mix',crowd,'dress_code',dress,'host_inclusivity',host,'source_urls',sources,'research_status','official_organiser_dates','updated_at','2026-08-27T00:00:00Z') intel from raw_events e
), upd as (
 update public.events t set description=e.description,link=e.link,date=e.date,start_date=e.start_date,end_date=e.end_date,location=e.location,lat=e.lat,lng=e.lng,vibe=e.vibe,vibe_tags=array[]::text[],event_intel=e.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from events e where lower(trim(t.city))=e.city and lower(trim(t.name))=lower(trim(e.name)) returning t.id
)
insert into public.events(name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,event_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],intel,true,'approved',timezone('utc',now()) from events e where not exists(select 1 from public.events t where lower(trim(t.city))=e.city and lower(trim(t.name))=lower(trim(e.name)));

with raw_services as (
 select * from jsonb_to_recordset($qa_services$
[
 {"name":"Community Pride MI","city":"saugatuck","type":"other","provider":"Community Pride MI","contact":"PO Box 437, Douglas, MI 49406; use official contact form","booking":"https://www.communitypridemi.org/","description":"The local nonprofit organising Pride Week, grants, education and connection across Saugatuck-Douglas. It is an organiser and referral route, not a daily walk-in centre.","hours":"Online year-round; in-person access follows each published programme.","link":"https://www.communitypridemi.org/","location":"Saugatuck-Douglas service area, Michigan","lat":42.643300,"lng":-86.200900,"vibe":"local Pride organising, grants and connection for a small lakeshore community","lead":"Contact before volunteering, partnership or grant work; ordinary programme details are online.","best":"Reach out well before Pride Week and specify the town, activity and access question.","crowd":"LGBTQIA+ residents, visitors, businesses, nonprofits, families and volunteers.","prep":"State whether the need concerns events, grants, accessibility, media or community referral.","incl":"The organisation explicitly exists to foster LGBTQIA+ inclusion across Saugatuck and Douglas.","sources":["https://www.communitypridemi.org/"]},
 {"name":"Utah Pride Center","city":"salt_lake_city","type":"other","provider":"Utah Pride Center","contact":"801-539-8800","booking":"https://utahpridecenter.org/about/plan-your-visit","description":"Utah's central LGBTQ+ resource organisation provides social groups, youth and adult programming, health navigation, events and referrals from a downtown office.","hours":"Monday-Friday 16:00-20:00 for published public access; verify programme schedules.","link":"https://utahpridecenter.org/","location":"68 South Main Street, 9th Floor, Salt Lake City, UT 84101, USA","lat":40.767590,"lng":-111.891579,"vibe":"statewide LGBTQ+ resource hub connecting community groups, navigation and affirming programmes","lead":"Groups and services differ; contact before visiting for a specific appointment or age programme.","best":"Weekday contact before 20:00, with the exact service or referral need stated.","crowd":"LGBTQ+ youth and adults, families, trans communities, volunteers and service partners.","prep":"Confirm eligibility, privacy, floor access, accessibility and whether registration is required.","incl":"The centre is a dedicated LGBTQ+ nonprofit with identity-specific programmes and navigation.","sources":["https://utahpridecenter.org/about/plan-your-visit"]},
 {"name":"prideHealth","city":"halifax","type":"wellness","provider":"Nova Scotia Health","contact":"902-487-0470","booking":"https://www.nshealth.ca/pridehealth","description":"A Nova Scotia Health navigation service helping 2SLGBTQIA+ people reach affirming primary, sexual, gender and mental-health care. Contact first because navigation is not equivalent to a general walk-in clinic.","hours":"Navigation and appointment-led; verify current telephone and programme availability.","link":"https://www.nshealth.ca/pridehealth","location":"Nova Scotia Health, Halifax service area","lat":44.637916,"lng":-63.580048,"vibe":"affirming public-health navigation reducing barriers across Nova Scotia services","lead":"Call before an in-person visit; navigation may redirect to the appropriate clinic or regional provider.","best":"Weekday contact with enough time for referral or appointment matching.","crowd":"Two-spirit and LGBTQIA+ patients across ages, families and health-care providers.","prep":"Describe the health need and preferred language or identity considerations without sharing more than necessary.","incl":"The programme is explicitly dedicated to safe and accessible care for 2SLGBTQIA+ communities.","sources":["https://www.nshealth.ca/pridehealth"]},
 {"name":"The Youth Project","city":"halifax","type":"other","provider":"The Youth Project","contact":"Use official phone, email and referral channels","booking":"https://youthproject.ns.ca/","description":"A Nova Scotia nonprofit providing support, education, groups and resources for youth under 25 around sexual orientation and gender identity, with a Halifax community base.","hours":"Programme and appointment-led; contact before arriving at the office.","link":"https://youthproject.ns.ca/","location":"2281 Brunswick Street, Halifax, NS B3K 2Y9, Canada","lat":44.654536,"lng":-63.583595,"vibe":"protected youth-centred support, peer connection and education across Nova Scotia","lead":"Contact in advance because age groups, consent, registration and locations vary by programme.","best":"Use a private weekday contact method and ask for the relevant youth, parent or educator route.","crowd":"2SLGBTQIA+ youth under 25, families, schools, volunteers and educators.","prep":"Confirm age band, privacy, transport, accessibility and whether a guardian is involved.","incl":"The organisation explicitly centres youth around sexual orientation and gender identity.","sources":["https://youthproject.ns.ca/"]},
 {"name":"Quatrefoil Library","city":"minneapolis","type":"other","provider":"Quatrefoil Library","contact":"info@qlibrary.org","booking":"https://qlibrary.org/about-us/contact-us/","description":"A member-supported LGBTQ+ lending library, archive and community space with books, periodicals, media, exhibitions and events in south Minneapolis.","hours":"Volunteer and event-led; verify current open hours before travel.","link":"https://qlibrary.org/","location":"1220 East Lake Street, Minneapolis, MN 55407, USA","lat":44.948602,"lng":-93.256772,"vibe":"quiet multigenerational LGBTQ+ archive, lending room and cultural meeting place","lead":"Ordinary browsing follows open hours; research, donation and event requests benefit from advance contact.","best":"Visit during staffed hours and allow time to browse specialist collections.","crowd":"LGBTQ+ readers, researchers, elders, students, community groups and volunteers.","prep":"Bring membership or research questions and respect archive handling and visitor privacy.","incl":"The library's collection and mission explicitly preserve and serve LGBTQ+ communities.","sources":["https://qlibrary.org/about-us/contact-us/"]},
 {"name":"Family Tree Clinic","city":"minneapolis","type":"wellness","provider":"Family Tree Clinic","contact":"612-473-0800","booking":"https://www.familytreeclinic.org/","description":"A community clinic providing affirming sexual, reproductive, primary and gender-affirming health care, education and interpretation with transparent sliding-fee and appointment pathways.","hours":"Clinic hours vary by service; call or use the official appointment route.","link":"https://www.familytreeclinic.org/","location":"1919 Nicollet Avenue, Minneapolis, MN 55403, USA","lat":44.963117,"lng":-93.277542,"vibe":"community-based affirming clinical care with strong trans and sexual-health competence","lead":"Book ahead for most care and describe urgency so triage can identify the right route.","best":"Call on a weekday with insurance, cost, interpreter and accessibility questions ready.","crowd":"LGBTQ+ patients, trans and gender-diverse people, families and wider community clients.","prep":"Bring requested documents and medication information; ask about privacy, labs and follow-up.","incl":"The clinic explicitly provides gender-affirming and LGBTQ-competent care with barrier-reduction policies.","sources":["https://www.familytreeclinic.org/"]},
 {"name":"QUEERSPACE Youth Center","city":"minneapolis","type":"other","provider":"QUEERSPACE collective","contact":"Use the official youth-centre interest and contact forms","booking":"https://www.queerspacecollective.org/youth-programs/youth-center","description":"A free drop-in youth centre with identity-affirming activities, meals, mentoring and separate programme days for LGBTQ+ teens and young adults.","hours":"Ages 13-17 Tuesday and Thursday; ages 18-24 Wednesday; verify current session times.","link":"https://www.queerspacecollective.org/youth-programs/youth-center","location":"702 West Franklin Avenue; accessible entrance 1936 Lyndale Avenue South, Minneapolis, MN 55405, USA","lat":44.962701,"lng":-93.288185,"vibe":"free protected queer-youth drop-in space built around mentorship and belonging","lead":"Review the correct age-day and any first-visit form before attending.","best":"Attend only the published age-specific session and arrive with safe transport arranged.","crowd":"LGBTQ+ youth ages 13-24, mentors, programme staff and invited community partners.","prep":"Confirm age eligibility, confidentiality, accessibility entrance, food needs and pickup plans.","incl":"QUEERSPACE is explicitly designed by and for LGBTQ+ youth and provides affirming mentorship.","sources":["https://www.queerspacecollective.org/youth-programs/youth-center"]},
 {"name":"Cardiff Youth LGBTQ+ Group","city":"cardiff","type":"other","provider":"Cardiff Youth Service","contact":"Use the official youth-service referral contact","booking":"https://www.cardiffyouthservices.wales/lgbtq-2/","description":"A council youth group providing a confidential, supportive weekly space for LGBTQ+ young people at Eastmoors Youth Centre, with youth-worker activities and peer connection.","hours":"Wednesday 18:15-20:30; confirm term and holiday changes.","link":"https://www.cardiffyouthservices.wales/lgbtq-2/","location":"Eastmoors Youth Centre, Sanquhar Street, Cardiff CF24 2AD, United Kingdom","lat":51.480488,"lng":-3.157312,"vibe":"confidential council-run LGBTQ+ youth group focused on safety and peer connection","lead":"Contact before a first visit to confirm age eligibility, consent and current session operation.","best":"Use a private contact method before Wednesday and arrange safe transport home.","crowd":"LGBTQ+ young people and trained youth workers; not a visitor attraction.","prep":"Confirm age band, confidentiality, accessibility, guardian rules and what happens on arrival.","incl":"The council service explicitly provides a safe and confidential LGBTQ+ youth environment.","sources":["https://www.cardiffyouthservices.wales/lgbtq-2/"]},
 {"name":"Pride Cymru Community Information","city":"cardiff","type":"other","provider":"Pride Cymru","contact":"Use official contact and volunteer routes","booking":"https://pridecymru.com/","description":"Wales-wide LGBTQ+ charity and Cardiff festival organiser providing community events, campaigning, volunteering and official Pride access information rather than a daily drop-in centre.","hours":"Online year-round; physical access follows published events and appointments.","link":"https://pridecymru.com/","location":"Cardiff, Wales, United Kingdom","lat":51.481600,"lng":-3.179100,"vibe":"national Welsh LGBTQ+ organising connecting festival visibility, community programmes and equality work","lead":"Contact early for volunteering, access, stalls, media or partnership; festival deadlines close months ahead.","best":"Use current official channels before attending any physical event or relying on an old office address.","crowd":"LGBTQ+ people across Wales, community groups, volunteers, families, performers and allies.","prep":"State whether the request concerns access, welfare, volunteering, parade or community referral.","incl":"Pride Cymru is an LGBTQ+ charity and publishes quiet-hour, welfare and access provisions.","sources":["https://pridecymru.com/","https://pridecymru.com/events/"]}
]
$qa_services$) s(name text,city text,type text,provider text,contact text,booking text,description text,hours text,link text,location text,lat double precision,lng double precision,vibe text,lead text,best text,crowd text,prep text,incl text,sources jsonb)
), services as (
 select s.*,jsonb_build_object('booking_lead_time',lead,'best_time',best,'client_mix',crowd,'preparation',prep,'provider_inclusivity',incl,'source_urls',sources,'research_status','current_first_party_service_source','updated_at','2026-08-27T00:00:00Z') intel from raw_services s
), upd as (
 update public.services t set type=s.type,provider_name=s.provider,contact=s.contact,booking_link=s.booking,description=s.description,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,vibe_tags=array[]::text[],source='Official provider pages; checked 2026-08-27',"lastChecked"=date '2026-08-27',verified=true,service_intel=s.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from services s where lower(trim(t.city))=s.city and lower(trim(t.name))=lower(trim(s.name)) returning t.id
)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,location,lat,lng,vibe,vibe_tags,source,"lastChecked",verified,service_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,type,provider,contact,booking,description,hours,link,location,lat,lng,vibe,array[]::text[],'Official provider pages; checked 2026-08-27',date '2026-08-27',true,intel,true,'approved',timezone('utc',now()) from services s where not exists(select 1 from public.services t where lower(trim(t.city))=s.city and lower(trim(t.name))=lower(trim(s.name)));

select public.qa_refresh_city_seo_status(slug)
from (values('saugatuck'),('salt_lake_city'),('halifax'),('minneapolis'),('cardiff')) v(slug)
where to_regprocedure('public.qa_refresh_city_seo_status(text)') is not null;

commit;

select c.slug,c.name,c.verified_place_count,c.seo_indexable,c.seo_requirements
from public.qa_cities c
where c.slug in('saugatuck','salt_lake_city','halifax','minneapolis','cardiff')
order by c.slug;

select lower(trim(city)) city,type,count(*) records
from (
 select city,'place'::text type from public.places
 union all select city,'event' from public.events
 union all select city,'service' from public.services
) x
where lower(trim(city)) in('saugatuck','salt_lake_city','halifax','minneapolis','cardiff')
group by lower(trim(city)),type order by city,type;
