-- Queer Atlas: Bristol curated city package
-- Researched and checked 2026-08-14. Idempotent, constraint-safe and apostrophe-safe.

begin;

with src as (
 select * from jsonb_to_recordset($bristol_places$
[
 {"name":"Queenshilling","city":"bristol","type":"club","description":"Bristol's longest-running dedicated LGBTQ+ nightclub is the Frogmore Street option for karaoke, pop, drag guests and a recognisably queer dance floor. Its own door policy rejects racism, homophobia and harassment, while recent local discussion still treats it as the gayer alternative to nearby OMG. The room can also draw straight groups and community posts raise drink-safety concerns, so keep ordinary club precautions in place. Accessibility is limited by the absence of an officially accessible toilet; contact the venue before relying on assistance.","vibe":"old-school LGBTQ+ pop club where karaoke warmth turns into a late weekend dance floor","hours":"Monday karaoke 21:00-02:00; Thursday 21:00-02:00; Friday-Saturday 22:00-04:00. Check special-event and holiday changes.","link":"https://queenshilling.com/weeklylineup.html","location":"9 Frogmore Street, Bristol BS1 5NA, United Kingdom","lat":51.4537021,"lng":-2.6009819},
 {"name":"OMG Bristol Club","city":"bristol","type":"club","description":"A large, late Frog Lane club built around commercial pop, house, student offers and drag-era spectacle. It can deliver a loud youthful night, but the evidence is genuinely divided: some guests praise friendly bar staff and security, while a substantial review trail describes a straight-dominated crowd, expensive or unclear promotions and uncomfortable queer experiences. Treat a named LGBTQ+ event as stronger evidence than the logo, read the ticket terms and keep Queenshilling or Old Market as a backup.","vibe":"high-volume student-facing pop club with queer branding and a sharply mixed community reputation","hours":"Current official listings programme Wednesday, Friday and Saturday from about 22:00, commonly until 04:00-05:00. Confirm the exact night before travel.","link":"https://www.omgclubs.com/venues/omg-bristol-club","location":"1-2 Frog Lane, Bristol BS1 5UX, United Kingdom","lat":51.4530689,"lng":-2.6018030},
 {"name":"OMG Bristol Bar","city":"bristol","type":"bar","description":"The smaller Frogmore Street sister bar works as a jukebox-led pre-club room, with cabaret and student promotions changing the energy by night. It is easier to enter and talk in than the main OMG club, though recent accounts still flag inconsistent door or service experiences across the brand. Come for one drink and the live atmosphere, then decide whether the room feels right rather than assuming the connected club is the automatic next step.","vibe":"bright jukebox pre-bar mixing cabaret regulars, students and weekend club groups","hours":"Official contact information lists daily opening from 20:00, usually to 02:00 and to 03:00 Thursday and Sunday; event pages can publish different seasonal hours, so verify same day.","link":"https://www.omgclubs.com/venues/omg-bristol-bar","location":"3 Frogmore Street, Bristol BS1 5UX, United Kingdom","lat":51.4535628,"lng":-2.6010933},
 {"name":"Bristol Bear Bar","city":"bristol","type":"bar","description":"A compact purpose-built bear bar at the edge of Old Market, promoted as the UK's only bespoke venue of its kind. The room is primarily shaped by gay and bi men, bears, cubs and admirers, but its attitude-free identity and strong current review score make it approachable beyond that core. Thursday and Sunday favour conversation; Friday and Saturday turn livelier without pretending to be a giant circuit club.","vibe":"small, sociable bear bar where regulars and visitors can actually hear one another","hours":"Monday closed; Tuesday-Thursday 19:00-23:30; Friday-Saturday 19:00-02:00; Sunday currently listed from late afternoon to 23:00. Verify Sunday opening time.","link":"https://www.oldmarketquarter.co.uk/bristolbearbar/","location":"2 West Street, Bristol BS2 0BH, United Kingdom","lat":51.4563887,"lng":-2.5796161},
 {"name":"The Phoenix","city":"bristol","type":"bar","description":"A relaxed pub behind Cabot Circus with a terrace, local beer, food and a mixed neighbourhood crowd. Its queer value is programme-led rather than exclusive: the long-running Don't Tell Your Mother indie-pop night gives the first Saturday a clear LGBTQ+ pulse, while ordinary afternoons remain family, dog and pub friendly. It is useful for people who want local texture without a nightclub door.","vibe":"unfussy queer-friendly pub whose monthly indie-pop night adds sparkle to a broad local base","hours":"Monday-Tuesday 16:00-23:00; Wednesday-Friday 12:00-23:00; Saturday 12:00-late; Sunday 12:00-22:00. Event licensing can extend selected nights.","link":"https://www.oldmarketquarter.co.uk/thephoenix/","location":"1 Wellington Buildings, Champion Square, Bristol BS2 9DB, United Kingdom","lat":51.4584992,"lng":-2.5831312},
 {"name":"Old Castle Green","city":"bristol","type":"bar","description":"A colourful independent pub and garden at Old Market's eastern edge, known for drag, cabaret, quizzes and openly trans-friendly community events. Locals repeatedly recommend it when someone wants a queer room that feels less like a branded club, but the audience and noise level change completely with the listing. Check the actual host: a QPOC social, non-binary meetup and ordinary pub evening are three different uses of the same building.","vibe":"community-minded pub where drag, grassroots socials and a generous garden share the week","hours":"Open across the week with event-led late finishes; published hours vary between the venue and directories. Check the current programme before a dedicated journey.","link":"https://oldcastlegreen.com/","location":"46 Gloucester Lane, Bristol BS2 0DP, United Kingdom","lat":51.4570572,"lng":-2.5787383},
 {"name":"Old Market Tavern","city":"bristol","type":"bar","description":"A traditional queer-friendly pub with a conservatory and garden, sitting closer to pints and conversation than polished nightlife. Pride quizzes and Old Market history give it community relevance, and many guests value the cheaper, quieter rhythm. Current reviews are not uniformly warm: alongside praise for atmosphere and value are specific complaints about abrupt or aggressive service. Read the room early and move on easily if the welcome is off.","vibe":"traditional Old Market local with queer history, garden space and a deliberately unflashy pace","hours":"Current listings generally show daily service from midday, with later Friday-Saturday closing. Independent sources disagree, so verify directly on the day.","link":"https://www.oldmarketquarter.co.uk/oldmarkettavern/","location":"29-30 Old Market Street, Bristol BS2 0HB, United Kingdom","lat":51.4562234,"lng":-2.5821450},
 {"name":"The Old Market Assembly","city":"bristol","type":"restaurant","description":"A restaurant, bar and performance building whose in-house Wardrobe Theatre makes queer culture part of the weekly programme rather than an annual add-on. Seasonal plates and pizza work for an early meeting; cabaret, theatre, storytelling and Pride shows take the building later. It is not an exclusively LGBTQ+ venue, so book the named production if the queer audience matters more than dinner.","vibe":"handsome all-day assembly room where food, theatre and queer performance overlap naturally","hours":"Monday-Wednesday 16:00-22:30; Thursday 16:00-23:00; Friday 16:00-late; Saturday 12:00-late; Sunday 11:30-22:00. Kitchen hours are shorter.","link":"https://www.oldmarketassembly.co.uk/","location":"25 West Street, Bristol BS2 0DF, United Kingdom","lat":51.4568748,"lng":-2.5790776},
 {"name":"To The Moon","city":"bristol","type":"bar","description":"A tucked-away Old Market cocktail and local-beer bar built from reclaimed furniture, with free DJs most Fridays and Saturdays and a firm zero-discrimination commitment. Reviews consistently favour the cosy room, thoughtful drinks and welcoming staff. The trade-off is physical access: the main entrance is level, but toilets are not accessible and Room 2 has steps; the team can sometimes arrange an external toilet solution when contacted ahead.","vibe":"cosy independent cocktail bar with free weekend DJs and an easy, mixed queer welcome","hours":"Wednesday-Thursday 17:00-23:00; Friday-Saturday 17:00-00:00; Sunday 15:00-22:00; Monday-Tuesday closed.","link":"https://tothemoon.cc/","location":"27-29 Midland Road, Bristol BS2 0JT, United Kingdom","lat":51.4558728,"lng":-2.5791282},
 {"name":"Filthy XIII","city":"bristol","type":"bar","description":"A compact Cheltenham Road cocktail bar that explicitly describes itself as a safe place for the queer community. Drinks and hospitality, not rainbow spectacle, are the draw: current reviews repeatedly single out knowledgeable staff and unusually good cocktails. Every guest needs a seat, so weekends can be fully booked; a card-backed reservation carries a £15-per-person late-cancellation or no-show charge and is released after fifteen minutes.","vibe":"serious but playful cocktails in a small seated room with an explicit queer-safe ethos","hours":"Tuesday-Sunday 17:00-00:00; Monday closed. Reserve for Friday or Saturday if the stop matters.","link":"https://filthyxiii.com/reservations/","location":"208 Cheltenham Road, Bristol BS6 5QU, United Kingdom","lat":51.4693439,"lng":-2.5931073},
 {"name":"Bristol Community Sauna","city":"bristol","type":"sauna","description":"A not-for-profit, nonsexual community sauna with two Finnish rooms, cold plunges and regular queer and trans-only sessions alongside its all-community schedule. The consent code is unusually concrete: ask pronouns, respect silence and boundaries, keep phones outside and wear swimwear below the waist; top-half swimwear is optional for every gender. One sauna, the plunges and an accessible toilet have step-free access. Sessions often sell out, so this is a booked wellbeing experience rather than a spontaneous gay cruising venue.","vibe":"consent-led community heat with dedicated queer sessions, cold plunges and zero cruise pretence","hours":"Book a listed 75-minute session online; queer, trans-only, low-capacity and silent formats vary by week. Do not arrive without a booking.","link":"https://bristolcommunitysauna.org/","location":"St Anne's House, St Anne's Road, Brislington, Bristol BS4 4AB, United Kingdom","lat":51.4526023,"lng":-2.5476684}
]
$bristol_places$) p(name text,city text,type text,description text,vibe text,hours text,link text,location text,lat double precision,lng double precision)
), upd as (
 update public.places p set type=s.type,description=s.description,vibe=s.vibe,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)) returning p.id
)
insert into public.places(name,city,type,description,vibe,vibe_tags,hours,link,location,lat,lng,seo_indexable,seo_quality_status,updated_at)
select name,city,type,description,vibe,array[]::text[],hours,link,location,lat,lng,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.places p where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)));

with src as (
 select * from jsonb_to_recordset($bristol_events$
[
 {"name":"Trans Pride Bristol March 2026","city":"bristol","description":"Trans Pride Bristol gathered at the Cenotaph for speeches before an 11:15 march toward its Community Day. The adapted route kept the procession closer to Trinity Centre and published bus, rail and access contact information in advance. It was a focused trans, non-binary, gender-nonconforming and intersex rights action rather than a satellite branding exercise.","link":"https://www.transpridebristol.org.uk/events/trans-pride-bristol-march-26","date":"2026-03-28","start_date":"2026-03-28","end_date":"2026-03-28","location":"The Cenotaph, Colston Avenue, Bristol BS1 4UA, United Kingdom","lat":51.4549808,"lng":-2.5964324,"vibe":"trans-led city-centre protest moving deliberately toward community care"},
 {"name":"Trans Pride Bristol Community Day 2026","city":"bristol","description":"The post-march heart of Trans Pride moved into Trinity Centre for community stalls, workshops and a daytime space where connection mattered more than performance polish. Its proximity to the end of the revised march route reduced the transfer burden. The programme was built specifically around trans and gender-diverse people, with accessibility questions invited directly before the event.","link":"https://www.transpridebristol.org.uk/events","date":"2026-03-28","start_date":"2026-03-28","end_date":"2026-03-28","location":"Trinity Centre, Trinity Road, Bristol BS2 0NW, United Kingdom","lat":51.4583460,"lng":-2.5760420,"vibe":"daylight trans community hub joining practical resources, workshops and easy social contact"},
 {"name":"Trans Pride Bristol After Party Gig 2026","city":"bristol","description":"A queer and trans band bill took Trans Pride into the railway arches at Loco Klub, with KODACHROME and Princess Boyfriend mixing indie, rock, post-punk and theatrical energy. The venue's manifesto explicitly names itself a queer safer space and rejects homophobia, transphobia, racism and other discrimination. It was a compact live-music bridge before later afterparty programming, not an all-night generic club listing.","link":"https://www.transpridebristol.org.uk/events/trans-pride-bristol-after-party-gig","date":"2026-03-28","start_date":"2026-03-28","end_date":"2026-03-28","location":"Loco Klub, Clock Tower Yard, Bristol BS1 6QH, United Kingdom","lat":51.4493020,"lng":-2.5805150,"vibe":"young trans-led live music inside atmospheric railway arches"},
 {"name":"Bristol Pride Festival 2026","city":"bristol","description":"Bristol Pride's two-week 2026 programme spread more than forty-five events across cinema, theatre, sport, history, community workshops, nightlife and family formats from 27 June to 12 July. That breadth is the point: the festival makes the whole city legible beyond one outdoor finale. Individual events use their own tickets and access rules, so build a route from the official programme rather than treating the date range as one continuous venue.","link":"https://bristolpride.co.uk/news/2026-aftperty-and-fortnight-events/","date":"2026-06-27","start_date":"2026-06-27","end_date":"2026-07-12","location":"Multiple verified venues across Bristol, United Kingdom","lat":51.4545000,"lng":-2.5879000,"vibe":"fortnight-long queer city takeover spanning protest, film, sport, theatre and nightlife"},
 {"name":"Bristol Pride Parade March 2026","city":"bristol","description":"The free public march gathered by St Peter's Church in Castle Park at 10:30 and departed at 11:00 for a roughly two-mile, hour-long walking route to the Harbourside. Bristol Pride explicitly framed it as protest as well as celebration. Individuals and friendship groups needed no registration, while large organisations did; accessible toilets and priority boarding for the onward shuttle were mapped separately.","link":"https://bristolpride.co.uk/parade/","date":"2026-07-11","start_date":"2026-07-11","end_date":"2026-07-11","location":"Castle Park to Bristol Harbourside, Bristol BS1 3XE, United Kingdom","lat":51.4556700,"lng":-2.5906400,"vibe":"large free walking protest with the city centre visibly claimed by community"},
 {"name":"Bristol Pride Day 2026","city":"bristol","description":"One of the UK's largest Pride festivals returned to The Downs with Sister Sledge, Jason Donovan, Chloe Qisha, Black Box and Trinity The Tuck among more than 250 performers. Multiple music, cabaret, circus and dance stages sat beside youth, family, community and sensory-calm areas. Tickets funded the charity and included Bristol-zone bus travel; under-16s required an adult.","link":"https://bristolpride.co.uk/events/pride-day/","date":"2026-07-11","start_date":"2026-07-11","end_date":"2026-07-11","location":"Durdham Downs near Saville Road, Bristol BS9 1JA, United Kingdom","lat":51.4762460,"lng":-2.6223570,"vibe":"full-scale outdoor Pride festival balancing disco spectacle with community and calm space"},
 {"name":"Bristol Pride Official Afterparty 2026","city":"bristol","description":"Jodie Harsh headlined a three-room O2 Academy takeover with Jayde Adams, DTYM, Disco Wonderland, Mutual Vibes, dancers and aerial performers. Advance entry was £13 including booking fee, while Day+Night wristbands added a dedicated lane and partner-club access. It was an 18+ fundraiser for Bristol Pride, giving the big post-festival crowd a defined official route rather than an improvised bar crawl.","link":"https://bristolpride.co.uk/events/the-official-afterparty/","date":"2026-07-11","start_date":"2026-07-11","end_date":"2026-07-12","location":"O2 Academy Bristol, Frogmore Street, Bristol BS1 5NA, United Kingdom","lat":51.4545955,"lng":-2.6003964,"vibe":"high-energy three-room Pride finale with community fundraising under the production gloss"},
 {"name":"The Queer History of Magic, Myth and Legends","city":"bristol","description":"Historian Sacha Coward connects vampires, mermaids, fairies and other magical figures to changing ideas of gender and sexuality, followed by audience questions. The 18+ Bristol talk begins at 19:30 on 2 September, with doors at 19:00 and tickets originally listed from £11.50. Published ticket information warns that wheelchair access is limited, so confirm the current arrangement before booking.","link":"https://www.ents24.com/bristol-events/hen-and-chicken/the-queer-history-of-magic-myth-and-legends/7504677","date":"2026-09-02","start_date":"2026-09-02","end_date":"2026-09-02","location":"Hen and Chicken, 210 North Street, Bristol BS3 1JF, United Kingdom","lat":51.4406500,"lng":-2.5998600,"vibe":"smart, playful queer public history delivered through monsters, myth and audience questions"},
 {"name":"PrideCAF 2026","city":"bristol","description":"A not-for-profit day festival dedicated to independent LGBTQIA+ comic artists, writers, illustrators and zine makers, running at Sparks Bristol on 19 September. The format privileges direct discovery and conversation with creators over celebrity convention scale. Published 2026 access information lists level entry and a service lift fallback for the first-floor event.","link":"https://pridecaf.co.uk/","date":"2026-09-19","start_date":"2026-09-19","end_date":"2026-09-19","location":"Sparks Bristol, 78 Broadmead, Bristol BS1 3DS, United Kingdom","lat":51.4578347,"lng":-2.5908692,"vibe":"warm independent queer comics fair where creators, readers and zine culture meet directly"},
 {"name":"PAPAYA Film Night: Family Album","city":"bristol","description":"A tender documentary built from archives, photographs and the voices of women who shaped Argentina's trans-rights movement, followed by a post-show Q&A. The Wardrobe Theatre screens it on 13 October at 19:30 for £10 as part of the biennial Anglo-Latinx PAPAYA Fest. The combination of lived testimony and conversation gives the evening more editorial depth than a generic Pride-season film slot.","link":"https://thewardrobetheatre.com/papayafest/","date":"2026-10-13","start_date":"2026-10-13","end_date":"2026-10-13","location":"The Wardrobe Theatre, 25 West Street, Bristol BS2 0DF, United Kingdom","lat":51.4568748,"lng":-2.5790776,"vibe":"intimate trans-history documentary night followed by live reflection"},
 {"name":"SPUNK at PAPAYA Fest 2026","city":"bristol","description":"A dark comedy spanning sixty years of queer history through gay saunas as places of sex, confession, worship, survival and unexpected care. The makers of Jeezus! bring it to the Wardrobe Theatre on 17 October at 19:30, with tickets listed at £14. Adult themes are integral to the history rather than used as decorative shock.","link":"https://thewardrobetheatre.com/papayafest/","date":"2026-10-17","start_date":"2026-10-17","end_date":"2026-10-17","location":"The Wardrobe Theatre, 25 West Street, Bristol BS2 0DF, United Kingdom","lat":51.4568748,"lng":-2.5790776,"vibe":"darkly funny queer theatre using the sauna as a sixty-year social archive"}
]
$bristol_events$) e(name text,city text,description text,link text,date date,start_date date,end_date date,location text,lat double precision,lng double precision,vibe text)
), upd as (
 update public.events e set description=s.description,link=s.link,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)) returning e.id
)
insert into public.events(name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.events e where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)));

with src as (
 select * from jsonb_to_recordset($bristol_services$
[
 {"name":"OTR Freedom","city":"bristol","type":"other","provider_name":"Off the Record Bristol","contact":"freedom@otrbristol.org.uk; BHCDS freephone 0800 171 2272","booking_link":"https://www.otrbristol.org.uk/what-we-do/freedom/","description":"A free LGBTQIA+ youth programme for ages 11-25, with separate age groups, optional creative and social activity, parent and carer support, one-to-one help and a specialist hate-crime caseworker. Young people do not need a settled label to join. Group locations are deliberately private and supplied after signup, so the public OTR office below is a contact point rather than permission to attend an undisclosed session.","hours":"Groups meet on weekday evenings after signup; age-specific and parent sessions use their own schedule. Email Freedom for the correct route.","link":"https://www.otrbristol.org.uk/what-we-do/freedom/","location":"Public contact: Off the Record, 8-10 West Street, Bristol BS2 0BH; group venues shared privately after signup","lat":51.4564657,"lng":-2.5794647,"price_tier":"$","vibe":"joyful queer youth connection backed by specialist support and careful privacy","source":"OTR Freedom official service page and 2024-25 impact report; checked 2026-08-14"},
 {"name":"Yuno at Central Health Clinic","city":"bristol","type":"wellness","provider_name":"Yuno Sexual Health","contact":"0117 342 6900","booking_link":"https://yunosexualhealth.co.uk/find-a-clinic-or-pharmacy","description":"Bristol's central all-ages sexual-health clinic provides booked NHS care, while Yuno also lists a monthly peer-run LGBTQ+ testing drop-in at Prism. The service explicitly promises dignity to trans, non-binary and intersex patients. It is the correct route for testing, contraception, STI care and PEP guidance; a possible recent HIV exposure should never wait for the next community drop-in when clinic or A&E assessment is available.","hours":"Appointments: Monday-Tuesday 08:45-16:30; Wednesday 10:45-18:00; Thursday-Saturday 08:45-12:00. LGBTQ+ Prism drop-in: second Thursday monthly 17:00-19:30.","link":"https://yunosexualhealth.co.uk/find-a-clinic-or-pharmacy","location":"Central Health Clinic, Tower Hill, Bristol BS2 0JD, United Kingdom","lat":51.4545414,"lng":-2.5853365,"price_tier":"$","vibe":"confidential NHS sexual health with an explicit trans-inclusive promise and queer peer-testing option","source":"Yuno official clinic directory and current LGBTQ+ testing schedule; checked 2026-08-14"},
 {"name":"Brigstowe","city":"bristol","type":"wellness","provider_name":"Brigstowe","contact":"0117 955 5038; info@brigstowe.org","booking_link":"https://www.brigstowe.org/","description":"A Bristol HIV charity combining advice, advocacy, peer mentoring, groups and practical help around health, benefits, housing and stigma. Its Ground Floor Easton office is accessible, but support is relationship-led rather than a casual drop-in attraction. Contact the team to match a need to the right worker, particularly when immigration, asylum, poverty or another long-term condition intersects with HIV.","hours":"Office and appointments follow weekday service hours; contact the team before visiting so the appropriate worker is available.","link":"https://www.brigstowe.org/","location":"The Old Co-op Business Centre, Ground Floor, 40-42 Chelsea Road, Bristol BS5 6AF, United Kingdom","lat":51.4634743,"lng":-2.5629212,"price_tier":"$","vibe":"practical HIV support grounded in peer knowledge, dignity and long-term advocacy","source":"Brigstowe official service, peer support and current address pages; checked 2026-08-14"},
 {"name":"SARI and Bristol Hate Crime and Discrimination Services","city":"bristol","type":"other","provider_name":"Stand Against Racism and Inequality","contact":"0117 942 0060; BHCDS freephone 0800 171 2272","booking_link":"https://saricharity.org.uk/","description":"SARI leads Bristol's multi-agency hate-crime and discrimination service, supporting incidents linked to sexual orientation, transgender identity and other protected or perceived identities. Help can include listening, safety planning, advocacy and navigating justice or community systems. Support does not depend on choosing a police report, and intersectional cases are central rather than treated as an exception.","hours":"Contact by phone or online referral during service hours; this is not an emergency line. Call 999 when there is immediate danger.","link":"https://saricharity.org.uk/what-can-you-do/","location":"15 Portland Square, Bristol BS2 8SJ, United Kingdom","lat":51.4608252,"lng":-2.5845930,"price_tier":"$","vibe":"confidential anti-hate advocacy that understands overlapping identities and lets the person control next steps","source":"SARI official guidance, impact reporting and Bristol Hate Crime and Discrimination Services; checked 2026-08-14"},
 {"name":"Queer Space Bristol","city":"bristol","type":"other","provider_name":"Queer Space Bristol","contact":"Use the current event or access contact on the official site","booking_link":"https://queerspacebristol.com/","description":"A mobile programme of LGBTQIA+-led creative arts and wellbeing sessions, from making and movement to reflection and community markets. It has no permanent venue by design: partner buildings, outdoor spaces and online rooms change while the queer-led ethos remains. Workshops use pay-what-you-decide pricing and the organisation says current physical partner venues have lifts, changing facilities and gender-neutral toilets; still check the individual listing.","hours":"Event-led. Each workshop publishes its own date, venue, booking and access details; there is no permanent public drop-in room.","link":"https://queerspacebristol.com/","location":"Rotating verified partner venues across Bristol; consult the individual booking page","lat":51.4545000,"lng":-2.5879000,"price_tier":"$","vibe":"gentle queer-led creativity where connection matters more than skill or scene confidence","source":"Queer Space Bristol official mission, programme, pricing and access information; checked 2026-08-14"},
 {"name":"Bristol QPOC Socials","city":"bristol","type":"other","provider_name":"Bristol QPOC Socials","contact":"Use the current event contact on the official site","booking_link":"https://www.bristolqpoc.co.uk/","description":"A community programme specifically for queer people of colour, with a first-Wednesday monthly social, a QPOC 30+ gathering on the third Sunday and additional events. Participant testimony repeatedly describes finding shared experience and safety that Bristol's often white mainstream queer spaces did not provide. Locations can rotate, so preserve that boundary and use the organiser's live calendar instead of relying on an old venue pin.","hours":"Main social first Wednesday monthly; QPOC 30+ third Sunday monthly; additional dates vary. Check the live event listing for time and location.","link":"https://www.bristolqpoc.co.uk/","location":"Rotating Bristol venues disclosed in current event listings","lat":51.4545000,"lng":-2.5879000,"price_tier":"$","vibe":"peer-led QPOC belonging built around recurring low-pressure connection","source":"Bristol QPOC Socials official programme and participant testimony; checked 2026-08-14"}
]
$bristol_services$) s(name text,city text,type text,provider_name text,contact text,booking_link text,description text,hours text,link text,location text,lat double precision,lng double precision,price_tier text,vibe text,source text)
), upd as (
 update public.services x set type=s.type,provider_name=s.provider_name,contact=s.contact,booking_link=s.booking_link,description=s.description,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,price_tier=s.price_tier,vibe=s.vibe,source=s.source,"lastChecked"='2026-08-14'::date,verified=true,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)) returning x.id
)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified,seo_indexable,seo_quality_status,updated_at)
select name,city,type,provider_name,contact,booking_link,description,hours,link,array[]::text[],location,lat,lng,price_tier,vibe,array[]::text[],source,'2026-08-14'::date,true,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.services x where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)));

commit;

select 'places' check_name,count(*) result from public.places where lower(trim(city))='bristol'
union all select 'events',count(*) from public.events where lower(trim(city))='bristol'
union all select 'services',count(*) from public.services where lower(trim(city))='bristol'
union all select 'missing_coordinates',count(*) from (
 select lat,lng from public.places where lower(trim(city))='bristol'
 union all select lat,lng from public.events where lower(trim(city))='bristol'
 union all select lat,lng from public.services where lower(trim(city))='bristol'
) q where lat is null or lng is null
order by check_name;
