-- Queer Atlas: Thessaloniki place, event and service intelligence
-- Researched 2026-08-13 from official pages, current programmes and review consensus.
-- Run after city-thessaloniki-curated-v1.sql. Idempotent.

begin;
alter table if exists public.places add column if not exists venue_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.services add column if not exists service_intel jsonb not null default '{}'::jsonb;

with researched(name,patch) as (values
('Enola Bar Club',jsonb_build_object(
 'queue_wait','An ordinary night rarely carries a famous velvet-rope queue, but the second-floor entrance and compact room bottleneck once weekend arrivals land. Before 00:30 entry is usually easier; Friday and Saturday around drag moments can mean a short wait and little standing room. No reservation is needed unless you bring a large group.',
 'best_nights','Wednesday is the characterful choice for Greek music and more local flavour. Friday and Saturday are the full dance-and-drag nights and become strongest after midnight. Enola opens nightly, so Sunday to Thursday suits travellers who want an actual conversation before the room accelerates.',
 'crowd_mix','Queer Thessaloniki regulars and students lead, with gay men highly visible but lesbians, trans people, mixed friends and visitors explicitly welcomed. Pride and Balkan travel weekends shift the room outward; ordinary midweek nights feel much more local. It is a scene anchor, not a tourist production.',
 'dress_code','There is explicitly no dress code: comfy clothes, denim, trainers, a shirt or full glam all work. Dress for heat, stairs and dancing rather than approval. A themed event may invite a look without turning it into a permanent rule; bring valid identification and keep luggage out of the club flow.',
 'staff_inclusivity','The venue states that it welcomes the whole LGBTQ+ community, and fresh reports praise hands-on care when a guest was injured as well as help finding transport. Some community comments describe the room as more cis-gay-male in practice and reviews mention occasional pricing or service friction, so the evidence is warm but not uncritical.',
 'review_signal','Travel aggregates sit around the mid-three-star range while written reviews are more informative: strong music, late energy and helpful management recur, alongside smoking, price consistency and crowding complaints. Seventeen years of operation and its direct role in Pride history matter more than a single blended score.',
 'source_urls',to_jsonb(array['https://enola.gr/','https://wanderlog.com/place/details/6857847/enola-bar-club','https://www.travelgay.com/venue/enola']::text[]),'research_status','official_plus_current_review_consensus','updated_at','2026-08-13T00:00:00Z')),
('XPOSE Club',jsonb_build_object(
 'queue_wait','The club wakes late: turning up around midnight is normally smoother than arriving with the 01:00 wave. It can fill on Saturday and during a promoted drag set, but current reports describe a normal club entrance rather than prolonged face control. Check the live post because it may only operate on weekend nights.',
 'best_nights','Saturday is the clearest peak for a full floor and drag; Friday is the alternative when you want space without losing the late energy. Arrive around 00:30-01:00 rather than expecting an early bar. The current promoter schedule is more reliable than directories that still claim six-night opening.',
 'crowd_mix','A younger LGBTQ+ mix with gay men, women, trans and non-binary guests, queer friend groups and some visitors. Reviews explicitly note women feeling at home, and Pride sponsorship widens the room. It reads more broadly queer than a men-only club, though the exact event still tilts the audience.',
 'dress_code','Everyday clubwear works: tees, denim, dresses, trainers, makeup and louder looks all appear. No current formal code or appearance gate is published. Wear something that handles six hours of dancing, keep valuables close and bring valid ID; expressive does not mean compulsory.',
 'staff_inclusivity','Recent reviews repeatedly praise the welcome, bartending and help recovering a lost phone. One neurodivergent visitor described a rude DJ interaction and asked the venue to take inclusion seriously. That mixed record supports a generally caring room with an individual service caveat rather than a flawless claim.',
 'review_signal','Current Google-derived aggregates show roughly 4.5/5 from about 160 reviews. Praise concentrates on drag, clean facilities, music, drinks and friendly staff; scattered criticism concerns a DJ interaction, changing drink quality or whether the bright room feels more bar than club. Saturday after 01:00 best matches the reputation.',
 'source_urls',to_jsonb(array['https://www.instagram.com/xpose.skg/','https://wanderlog.com/place/details/10363751/expose','https://www.xpose.gr/contact/']::text[]),'research_status','current_review_consensus_with_schedule_conflict_resolved','updated_at','2026-08-13T00:00:00Z')),
('PLAY Thessaloniki',jsonb_build_object(
 'queue_wait','Reception normally means a brief membership or entry check rather than a nightclub queue. The material risk is travelling there and being refused new membership: more than one visitor reports inconsistent explanations. Message first, especially if you are new to the city, and do not treat a directory listing as guaranteed admission.',
 'best_nights','Friday and Saturday later in the evening offer the best chance of enough company; a weekday can be very quiet. One detailed visitor saw roughly fifteen men build over several hours, showing that patience matters. Choose this for the multi-floor adult layout, not for a guaranteed packed crowd.',
 'crowd_mix','Adult gay and bisexual men form the core, with locals and visiting men across roughly thirty to sixty in the written accounts. Age and attendance change by hour. It is not an all-gender queer venue, and no honest source supports a fixed locals-versus-tourists ratio.',
 'dress_code','Street clothes are fine at reception; the adult areas then follow house, hygiene and consent rules rather than fashion. Bring valid ID and ask about membership, lockers, re-entry and phone policy. Fetish equipment is an option, not blanket consent, and privacy must be protected everywhere in the club.',
 'staff_inclusivity','Some visitors describe a kind receptionist, clean rooms and a discreet first visit. Others, including a Black traveller, report repeated refusal under an unclear membership explanation. That unresolved pattern is material: the guide should neither erase it nor declare discrimination proven without the venue response.',
 'review_signal','The travel audience score is around 3.3 from nearly two hundred votes, while a smaller Google-derived set is about 4.1. Praise centres on the three-level design and cleanliness; criticism centres on quiet periods, value and entry handling. The fairest advice is to confirm access and choose a late weekend window.',
 'source_urls',to_jsonb(array['https://www.travelgay.com/venue/play','https://wanderlog.com/place/details/10364312/play']::text[]),'research_status','review_consensus_with_material_entry_caveat','updated_at','2026-08-13T00:00:00Z')),
('Splash Sauna Thessaloniki',jsonb_build_object(
 'queue_wait','There is normally no queue beyond reception. Crowd level is the real wait: early weekday sessions can be sparse, while staff and visitors point to weekends as busier. Give the facilities enough time and confirm the current Tantalou address, because older Splash and AquaSplash locations remain in search results.',
 'best_nights','Friday or Saturday evening provides the strongest likelihood of company and runs later. A weekday afternoon suits steam and quiet but may not deliver much social energy. This 2026 iteration is still developing its routine, so same-day confirmation is smarter than repeating an old theme calendar.',
 'crowd_mix','Adult gay and bisexual men across ages, with Thessaloniki regulars and international visitors sharing the compact space. Fresh comments describe a mixed clientele rather than one body or age lane. Weekend balance is broader; a quiet weekday can reduce the room to only a handful of guests.',
 'dress_code','Use the locker and follow towel, footwear, hygiene, smoking and phone rules. Flip-flops are sensible on wet floors, and consent applies separately to every interaction. The dark areas have low ceilings in places according to one recent guest, so move slowly until you understand the layout.',
 'staff_inclusivity','May and June 2026 reviews repeatedly call the owners and reception kind, smiling and helpful, including visitors from outside Greece. One sharply negative report criticises smoke, chlorine and behaviour inside rather than the welcome. Staff signal is unusually positive, but guest conduct and facility comfort still vary.',
 'review_signal','A current listing shows about 4.1/5 from 90 Google reviews, with a concentrated wave of positive feedback after the renewed opening. Cleanliness and staff lead the praise; cool showers, a mild jacuzzi, smoke and quiet periods recur as caveats. Treat the fresh rating as promising rather than decades-established.',
 'source_urls',to_jsonb(array['https://www.gayout.com/europe/greece/thessaloniki/saunas/splash-sauna-1003','https://www.travelgay.com/destination/gay-greece/gay-thessaloniki/']::text[]),'research_status','fresh_2026_review_consensus_current_location_prioritised','updated_at','2026-08-13T00:00:00Z')),
('Iliotropio Cafe',jsonb_build_object(
 'queue_wait','There is no door queue; finding a good Navarinou table is the issue. After-class and evening hours can fill the small, cosy room, while morning coffee is easy. Groups planning board games should arrive before the square becomes busy rather than occupying one table at the peak without ordering.',
 'best_nights','This works best by day or early evening, especially when you want a soft queer-friendly meeting before nightlife. Any weekday carries student energy; weekend afternoons are longer and more social. It is not a programme-dependent gay bar, so the pleasure comes from the regular crowd rather than a headline event.',
 'crowd_mix','Students, alternative locals, queer women and mixed LGBTQ+ friends are highly visible, joined by Navarinou regulars and a modest traveller stream. Community recommendations repeatedly name it for lesbian or queer-friendly coffee. The cafe remains mixed and should never be described as exclusively queer.',
 'dress_code','Whatever you wore to class, work or a city walk fits: trainers, vintage layers, practical clothes and expressive hair all feel normal. There is no face control. Bring a layer for square seating and enough time to linger; relaxed participation matters more than turning up dressed for a queer photo-op.',
 'staff_inclusivity','Most reviews describe swift, helpful service and a welcoming young atmosphere. A minority report harsh handling when part of a teenage group could not afford to order, which is relevant to claims of accessibility. The community signal is strong, but hospitality experiences are not uniformly gentle.',
 'review_signal','Google-derived listings show roughly 4.4/5 from more than 1,100 reviews, while a small Tripadvisor set is higher. Value, snacks, games and atmosphere lead the praise; isolated complaints focus on staff tone and minimum-order pressure. Its repeated local queer recommendation is stronger evidence than branding.',
 'source_urls',to_jsonb(array['https://wanderlog.com/place/details/3264810/iliotropio-cafe','https://www.reddit.com/r/thessaloniki/comments/16ryo8f/']::text[]),'research_status','large_review_consensus_plus_local_queer_recommendations','updated_at','2026-08-13T00:00:00Z')),
('Ypsilon',jsonb_build_object(
 'queue_wait','Daytime is usually normal cafe seating, though laptops compete for sockets. A Pride screening, concert or major late event can fill the heritage rooms and needs the organiser ticket or an early arrival. Do not queue for a random night expecting queer programming that belongs to another date.',
 'best_nights','Choose Ypsilon by programme. It hosted queer poetry and animation during Pride 2026; those dates carry a clearer community signal than an ordinary Friday. Morning and afternoon suit coffee or work, while late events turn the same building into a denser cultural bar.',
 'crowd_mix','Design and culture workers, students, laptop regulars, food-and-coffee visitors and international travellers form the daily mix. Queer audiences become central when Pride or an independent promoter takes over. The crowd is city-first and culturally mixed rather than a stable LGBTQ-only clientele.',
 'dress_code','Creative-casual is natural but not enforced: denim, simple work clothes, vintage pieces and night-out looks coexist. Wear layers because the courtyards and rooms shift temperature, and check access for the exact performance. The building''s polish does not translate into a velvet-rope dress policy.',
 'staff_inclusivity','Fresh 2026 reviews praise welcoming staff, reliable workspace help and thoughtful coffee service. Pride''s repeated use and local queer recommendations support the inclusion signal, but the host venue and event organiser can be different teams. Direct access or conduct concerns to both when relevant.',
 'review_signal','Cross-platform review volume exceeds four thousand, with Google around 4.4 and Tripadvisor closer to 3.8. Architecture, atmosphere, coffee and flexible uses lead praise; service and value vary more in the smaller travel set. The event calendar, not a blended score, determines its queer usefulness.',
 'source_urls',to_jsonb(array['https://thessalonikipride.com/program-of-the-festival/?lang=en','https://restaurantguru.com/YPSILON-Thessaloniki','https://www.tripadvisor.com/Restaurant_Review-g189473-d12861531-Reviews-Ypsilon-Thessaloniki_Thessaloniki_Region_Central_Macedonia.html']::text[]),'research_status','programme_verified_mixed_cultural_venue','updated_at','2026-08-13T00:00:00Z')),
('Rediviva Cucina Povera',jsonb_build_object(
 'queue_wait','The small Ano Poli room and courtyard can fill at dinner, so reserve rather than climbing the hill on hope. Lunch and an early weekday table are easier. Tuesday closure matters, and the old-city route takes longer than its map distance suggests.',
 'best_nights','Friday or Saturday suits a slow dinner before descending to the centre; Sunday lunch shows the neighbourhood at its gentlest. Go for seasonal food and the cooperative atmosphere, not a queer event. It is an excellent date or mixed-friend stop precisely because it is not performing nightlife.',
 'crowd_mix','Ano Poli locals, couples, families, food-focused travellers, vegetarians and queer mixed groups share the tables. Visitor reports call it local rather than tourist-trap territory. LGBTQ+ comfort comes through repeated community recommendation, not a claim that every diner or worker is queer.',
 'dress_code','Casual dinner clothes and shoes suitable for steep old-city streets are right. There is no fashion threshold. The courtyard can cool after dark, so bring a layer; accessibility is the more important practical question, as current listings flag physical barriers.',
 'staff_inclusivity','Most large-platform feedback praises attentive, lovely staff and an unforced neighbourhood welcome. A recent negative review drew a mocking public management response, which is a genuine hospitality caveat even though it was not identity-related. Expect personality, but do not romanticise every interaction.',
 'review_signal','Google-derived listings are around 4.5/5 from more than 1,100 reviews; Tripadvisor sits near 4.0 from about 120. Seasonal dishes, setting and value dominate praise, while a smaller set questions pricing or consistency. The cooperative identity and locals-first atmosphere remain its clearest strengths.',
 'source_urls',to_jsonb(array['https://www.rediviva.gr/who-we-are-2/','https://wanderlog.com/place/details/1165364/rediviva-cucina-povera','https://www.tripadvisor.co.uk/Restaurant_Review-g189473-d10247553-Reviews-Rediviva_Cucina_Povera-Thessaloniki_Thessaloniki_Region_Central_Macedonia.html']::text[]),'research_status','official_cooperative_identity_plus_large_review_consensus','updated_at','2026-08-13T00:00:00Z')),
('ONOMA Hotel',jsonb_build_object(
 'queue_wait','Check-in is a normal hotel flow; Pride rooftop events may require registration and separate access. Ask about pool and roof admission before inviting local friends, because guest amenities and public events are not interchangeable. Railway-area traffic can slow arrival more than reception does.',
 'best_nights','Stay here when Pride programming, the western centre or a playful social hotel matters. The rooftop is strongest in season and hosted Pride literature in 2026. For quiet sleep, request the appropriate room rather than assuming every design-led space is insulated from station-side city noise.',
 'crowd_mix','City-break couples, business travellers, younger design-hotel guests, Pride visitors and occasional event audiences mix. It is mainstream accommodation with documented Pride partnership, not an exclusively queer hotel. Festival weeks make LGBTQ+ guests more visible without changing the property''s general audience.',
 'dress_code','Reception is casual; smart-casual works on the roof, and swimwear belongs only in designated pool areas. Bring the booking ID and payment method rather than a scene look. Pride events may encourage colour, but hotel access rules remain separate from the programme aesthetic.',
 'staff_inclusivity','Hosting Pride events and appearing among the festival''s hospitality partners provide meaningful institutional evidence. That is stronger than an unverified rainbow-friendly label, though it cannot guarantee every interaction. Ask in advance about names, room sharing or accessibility if those details affect safety and comfort.',
 'review_signal','The evidence here rests on official Pride partnership, direct contact information and the property''s active programme rather than an imported score. Travellers should still read current room reviews for noise, location and amenity access; queer welcome and hotel performance are related but different questions.',
 'source_urls',to_jsonb(array['https://onomahotel.com/contact/','https://thessalonikipride.com/program-of-the-festival/?lang=en','https://thessalonikipride.com/?lang=en']::text[]),'research_status','official_pride_partner_and_programme_host','updated_at','2026-08-13T00:00:00Z'))
)
update public.places p set venue_intel=coalesce(p.venue_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(p.city))='thessaloniki' and lower(trim(p.name))=lower(trim(r.name));

with researched(name,patch) as (values
('Thessaloniki Pride 2026',jsonb_build_object('entry_wait','The week-long programme used different venues and registration rules. For the parade there was no ticket queue, but White Tower Square compressed before the 18:30 departure.','best_arrival','For the final Saturday, arriving around 17:30 gave time for speeches before the 18:30 march; individual workshops needed their own registration.','crowd_mix','LGBTQ+ locals, youth groups, families, allies, Balkan visitors and international Pride travellers shared the route.','dress_code','No code: weather-ready shoes, sun protection, water and expressive Pride clothes all worked.','host_inclusivity','The programme explicitly addressed gender diversity and mixed public celebration with education and advocacy.','source_urls',to_jsonb(array['https://thessalonikipride.com/program-of-the-festival/?lang=en','https://thessaloniki.travel/event/14th-thessaloniki-pride/']::text[]),'updated_at','2026-08-13T00:00:00Z')),
('Self-Organised Thessaloniki Pride 2026',jsonb_build_object('entry_wait','Open public gathering without ticketing; the relevant wait was assembly before movement.','best_arrival','The call set 17:00 at the Venizelos statue before the 19:00 colourful march.','crowd_mix','Grassroots queer organisers, anti-authoritarian and solidarity networks, younger locals and allies led.','dress_code','No imposed look; practical march shoes, water and personally expressive clothing fitted the sponsor-free format.','host_inclusivity','Open assembly and refusal of commercial control are central, though participants should read the political framing before joining.','source_urls',to_jsonb(array['https://www.thestival.gr/eidiseis/koinonia/thessaloniki-simera-i-polychromi-porei-2/']::text[]),'updated_at','2026-08-13T00:00:00Z')),
('Love Unbound: Five Films For Freedom 2026',jsonb_build_object('entry_wait','Admission was free, so capacity rather than ticket collection was the pressure point in the intimate Beetroot House.','best_arrival','Arrive before the selected screening or workshop; the two-day programme was designed for staying through discussion, not dropping in at the final minute.','crowd_mix','Queer film audiences, students, artists, activists, cultural partners and allies mixed in a compact room.','dress_code','No dress code; comfortable seated-event clothes and a layer for March were sufficient.','host_inclusivity','The programme centred LGBTQIA+ and gender-equality stories through British Council, BFI Flare and local partners.','source_urls',to_jsonb(array['https://www.britishcouncil.gr/en/events/love-unbound-five-films-for-freedom','https://www.britishcouncil.gr/sites/default/files/love-unbound-2026-programme-en.pdf']::text[]),'updated_at','2026-08-13T00:00:00Z')),
('SmaDragdus at Thessaloniki Fringe 2026',jsonb_build_object('entry_wait','This is ticketed cabaret in a small independent venue; capacity and seating matter more than club door pressure.','best_arrival','Book the 8 or 9 October 22:00 performance and arrive at least twenty minutes early for check-in and orientation.','crowd_mix','Fringe audiences, queer and drag communities, local performers and international arts visitors should form the room.','dress_code','No formal code; expressive evening clothes are welcome, but dress for a seated or close-standing performance.','host_inclusivity','The festival formally promotes diversity and the host is an independent contemporary-performance space; exact access needs should still be raised before booking.','source_urls',to_jsonb(array['https://thessfringe.com/','https://thessfringe.com/venues/transcendance/']::text[]),'updated_at','2026-08-13T00:00:00Z'))
)
update public.events e set event_intel=coalesce(e.event_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(e.city))='thessaloniki' and lower(trim(e.name))=lower(trim(r.name));

with researched(name,patch) as (values
('Thess Checkpoint',jsonb_build_object('booking_lead_time','Use the live booking route or call before travelling, because current official materials conflict on the Egnatia street number.','best_time','Choose an appointment that respects the window period of the test; disclose the exposure date so staff can guide timing.','client_mix','LGBTQ+ people and anyone seeking low-stigma rapid testing and counselling; not limited to gay men.','preparation','Bring only what booking instructions request and ask about anonymity, STI coverage and confirmatory care before testing.','provider_inclusivity','Checkpoint is community-based and created by Positive Voice to reduce stigma and connect reactive results to care.','source_urls',to_jsonb(array['https://mycheckpoint.gr/','https://eody.gov.gr/wp-content/uploads/2020/07/domes-eksetasis_HIV_22-01-2024.pdf']::text[]),'updated_at','2026-08-13T00:00:00Z')),
('PRAKSIS Thessaloniki Polyclinic',jsonb_build_object('booking_lead_time','Call before attending; testing sessions and broader clinic work may use different time slots.','best_time','A weekday daytime contact gives the best chance of being routed correctly. Recent exposure should be stated immediately.','client_mix','People seeking anonymous rapid testing and those facing wider social exclusion; it is not an LGBTQ-only service.','preparation','Ask what identification, if any, is required and whether the requested test is available that day.','provider_inclusivity','Its public-health listing confirms free anonymous testing, while the broader inclusion signal comes from PRAKSIS social-health work.','source_urls',to_jsonb(array['https://praksis.gr/','https://eody.gov.gr/wp-content/uploads/2020/07/domes-eksetasis_HIV_22-01-2024.pdf']::text[]),'updated_at','2026-08-13T00:00:00Z')),
('11528 By Your Side',jsonb_build_object('booking_lead_time','No travel appointment is needed; check live line hours and call when you have privacy.','best_time','Choose a quiet private window and use emergency services instead if there is immediate danger.','client_mix','LGBTQ+ people, questioning callers, families, educators and professionals across Greece.','preparation','Note the main concern, safe contact conditions and what kind of referral or listening you want.','provider_inclusivity','The service is explicitly designed around sexual orientation and gender identity with specialist support rather than generic crisis scripting.','source_urls',to_jsonb(array['https://11528.gr/']::text[]),'updated_at','2026-08-13T00:00:00Z')),
('Thessaloniki Pride Community Organisation',jsonb_build_object('booking_lead_time','Contact ahead for volunteering, collaboration or access; there is no reliable daily walk-in desk.','best_time','Begin months before Pride for team roles, or use the named contact on a current year-round programme.','client_mix','LGBTQI+ residents, youth, volunteers, civil-society partners, educators and regional networks.','preparation','State the purpose, date, language, access needs and whether you represent yourself or an organisation.','provider_inclusivity','The organisation combines visibility with education, advocacy, youth participation and solidarity beyond one annual march.','source_urls',to_jsonb(array['https://thessalonikipride.com/epikinonia/','https://youth.europa.eu/volunteering/organisation/58357_en']::text[]),'updated_at','2026-08-13T00:00:00Z'))
)
update public.services s set service_intel=coalesce(s.service_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(s.city))='thessaloniki' and lower(trim(s.name))=lower(trim(r.name));

commit;

select 'places_with_complete_intel' check_name,count(*) result from public.places where lower(trim(city))='thessaloniki' and coalesce(venue_intel->>'queue_wait','')<>'' and coalesce(venue_intel->>'best_nights','')<>'' and coalesce(venue_intel->>'crowd_mix','')<>'' and coalesce(venue_intel->>'dress_code','')<>'' and coalesce(venue_intel->>'staff_inclusivity','')<>''
union all select 'events_with_complete_intel',count(*) from public.events where lower(trim(city))='thessaloniki' and coalesce(event_intel->>'entry_wait','')<>'' and coalesce(event_intel->>'host_inclusivity','')<>''
union all select 'services_with_complete_intel',count(*) from public.services where lower(trim(city))='thessaloniki' and coalesce(service_intel->>'booking_lead_time','')<>'' and coalesce(service_intel->>'provider_inclusivity','')<>''
order by check_name;
