-- Queer Atlas: Bordeaux curated city package
-- Researched and checked 2026-08-14. Idempotent, constraint-safe and apostrophe-safe.

begin;

with src as (
 select * from jsonb_to_recordset($bordeaux_places$
[
 {"name":"Philippe Bar Queer","city":"bordeaux","type":"bar","description":"A young, explicitly queer Saint-Paul bar where the promise of a safe room is backed by drag, karaoke, open stages and a real dance floor. Current reviewers praise the warm service, strong cocktails and easy mix of identities, though one visitor found a quiet late arrival less welcoming. Go when the programme is active rather than expecting a full club every afternoon.","vibe":"bright all-community queer bar with pop, electro and a neighbourly dance floor","hours":"Public listings show daily afternoon-to-02:00 operation and happy hour 18:00-20:00; confirm the live social schedule before travelling.","link":"https://www.instagram.com/philippe_bar_queer/","location":"31 Rue Bouquière, 33000 Bordeaux, France","lat":44.8365070,"lng":-0.5702439},
 {"name":"Coco Loko","city":"bordeaux","type":"bar","description":"Bordeaux's established seven-night gay and lesbian party bar runs on games, DJs, drag guests and two contrasting rooms: pop upstairs and electronic music below. The central address and free entry make it an easy first stop, but reports of serious weekend crowding are credible. Arrive for the social hour if you want conversation; arrive later if you want the sing-along version.","vibe":"camp, high-energy city-centre party bar with drag and two musical moods","hours":"Daily 18:00-02:00 according to Bordeaux Tourism; event timings vary.","link":"https://www.facebook.com/CocoLokoBar","location":"3 Rue Duffour-Dubergier, 33000 Bordeaux, France","lat":44.8371374,"lng":-0.5762411},
 {"name":"Le Plumeau","city":"bordeaux","type":"bar","description":"A Chartrons queer bar built around drag-pop, DJ sets and the kind of warm, slightly chaotic room where spectators often end up dancing. Local coverage describes an audience wider than one letter of the acronym and a real Pride commitment. It is a late-week destination, not a quiet daytime cafe, and the energy depends on the announced artists.","vibe":"joyful Chartrons drag-pop room with local performers and full-volume nostalgia","hours":"Thursday-Sunday from 21:00; closing and special tea-dance hours follow the current event listing.","link":"https://www.instagram.com/leplumeaubar/","location":"3 Rue Premeynard, 33300 Bordeaux, France","lat":44.8590587,"lng":-0.5753644},
 {"name":"Buster Bar","city":"bordeaux","type":"cruise_club","description":"A compact men-focused bar and cruise venue with a lively ground floor and a more intimate upper room. Bordeaux Tourism emphasises the owners' nightly hosting, while specialist guides flag theme and dress-code nights that can change who the evening is for. Treat it as an adult gay venue, not a general queer cocktail bar, and check the current code before arrival.","vibe":"small, sociable gay men's bar with an adult upstairs edge","hours":"Nightly around 22:00-02:00 according to Bordeaux Tourism; theme nights and access rules can alter the schedule.","link":"https://www.facebook.com/BusterBarOfficial","location":"34 Rue de Cursol, 33000 Bordeaux, France","lat":44.8347960,"lng":-0.5774528},
 {"name":"Ultra Klubs","city":"bordeaux","type":"club","description":"The city's large late-night LGBTQ+ club has room for roughly 500, a stage, VIP area and recurring drag or themed bookings. Fresh reviews split in useful ways: many praise the mixed crowd and responsive door team, while others criticise drinks, DJ transitions or cleanliness. Choose a named party, arrive after midnight and expect a proper club rather than an intimate community bar.","vibe":"big-room queer clubbing with drag, pop spectacle and a mixed after-midnight crowd","hours":"Current listings commonly show Friday-Saturday from around midnight to 07:00, with selected Thursday or Sunday events; verify the weekly programme.","link":"https://www.facebook.com/UltraKlubs/","location":"22 Place André Meunier dit Mureine, 33800 Bordeaux, France","lat":44.8294496,"lng":-0.5632632},
 {"name":"Crunch Sauna","city":"bordeaux","type":"sauna","description":"A compact men-only sauna whose recent reputation rests more on care than scale. Visitors repeatedly mention a warm owner, clean changing areas and a surprisingly complete two-level layout with hammam, dry sauna, jacuzzi, bar and cruise basement. Not every review agrees on client behaviour or maintenance, so consent and ordinary bathhouse awareness still matter.","vibe":"friendly local men's sauna with a compact spa level and darker basement","hours":"Monday-Thursday 12:00-01:00; Friday 12:00-02:00; Saturday 13:00-02:00; Sunday 13:00-01:00. Confirm themed sessions.","link":"https://sauna-crunch.com/","location":"62 Cours Anatole France, 33000 Bordeaux, France","lat":44.8341941,"lng":-0.5845344},
 {"name":"Traxx Bordeaux","city":"bordeaux","type":"cruise_club","description":"A city-centre men-only cruise club spread across multiple rooms and play zones. Current reviewers like the friendly reception, cleanliness and range of equipment, but also warn that a weekday afternoon can be almost empty and entry can feel expensive for a quiet session. The theme calendar changes the dress and social temperature more than the address does.","vibe":"direct, theme-led men's cruise club where timing decides the room","hours":"Current listings show Tuesday-Sunday sessions with later Wednesday-Saturday night openings; verify the official social calendar because published hours conflict.","link":"https://www.facebook.com/traxxbordeaux/","location":"38 bis Rue Arnaud Miqueu, 33000 Bordeaux, France","lat":44.8389660,"lng":-0.5732261},
 {"name":"Sauna Le Saint","city":"bordeaux","type":"sauna","description":"Le Saint is the alternative to the all-male bathhouse model: an adult sauna that explicitly welcomes solo men, couples, women, trans and cross-dressing guests. The equipment is modest—sauna, hammam, video room, backroom and themed cabins—but the clearest rule is useful: everything permitted remains optional. Audience balance varies sharply, so read the day's format before choosing it.","vibe":"small mixed-adult sauna centred on consent, curiosity and audience-specific sessions","hours":"Daily 13:00-19:00 according to the official site; confirm audience and event rules before visiting.","link":"https://sauna-le-saint.fr/","location":"39 Rue Saint-Joseph, 33000 Bordeaux, France","lat":44.8531766,"lng":-0.5725635},
 {"name":"Bien Public","city":"bordeaux","type":"restaurant","description":"A large right-bank culture house where the queer signal comes from programming rather than a permanent gay-bar label. It hosts concerts, markets, exhibitions, Pride afters and major LGBTQ+ editions such as VendrediXXL. The riverfront scale can hold a crowd that the small central bars cannot, while an ordinary Sunday still works as lunch rather than nightlife.","vibe":"industrial riverfront culture house that becomes a major queer stage on programmed nights","hours":"Wednesday-Thursday 17:00-01:00; Friday 17:00-02:00; Saturday 16:00-02:00; Sunday 11:30-18:00; Monday-Tuesday closed.","link":"https://www.bienpublic-bordeaux.com/","location":"68 Quai Deschamps, 33100 Bordeaux, France","lat":44.8349431,"lng":-0.5520232},
 {"name":"JOST Bordeaux and Lieu Chéri","city":"bordeaux","type":"hotel","description":"A station-side hotel with a separate 300-square-metre cabaret room, Lieu Chéri, used for drag, performance and changing queer nightlife programmes. Two community safety reports on Vibes are positive, but the hotel is mainstream and the public calendar can be empty between productions. Book it for transport convenience and event potential, not on the promise of a nightly queer show.","vibe":"playful station hotel with a cabaret room and rotating queer-facing programme","hours":"Hotel reception operates daily; Lieu Chéri opens only for listed public or private events.","link":"https://www.jost-hotel-bordeaux.com/lieu-cheri/","location":"5-7 Promenade des Cheminots, 33800 Bordeaux, France","lat":44.8205697,"lng":-0.5597402}
]
$bordeaux_places$) p(name text,city text,type text,description text,vibe text,hours text,link text,location text,lat double precision,lng double precision)
), upd as (
 update public.places p set type=s.type,description=s.description,vibe=s.vibe,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)) returning p.id
)
insert into public.places(name,city,type,description,vibe,vibe_tags,hours,link,location,lat,lng,seo_indexable,seo_quality_status,updated_at)
select name,city,type,description,vibe,array[]::text[],hours,link,location,lat,lng,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.places p where lower(trim(p.city))=s.city and lower(trim(p.name))=lower(trim(s.name)));

with src as (
 select * from jsonb_to_recordset($bordeaux_events$
[
 {"name":"Mois des Fiertés Bordeaux 2026","city":"bordeaux","description":"The city's sixth Pride Month linked more than forty cultural, political and community moments from 17 May to 30 June. It is useful as an archive of how Bordeaux actually celebrates: libraries, courtyards, concerts, legal debate, drag, dance and HIV history, not only one commercial weekend.","link":"https://www.bordeaux-metropole.fr/agenda/14994330_mois-des-fiertes-2026-6eme-edition","date":"2026-05-17","start_date":"2026-05-17","end_date":"2026-06-30","location":"Venues across Bordeaux, France","lat":44.8378000,"lng":-0.5792000,"vibe":"citywide queer culture, public memory and community-led celebration"},
 {"name":"Bordeaux Pride March 2026","city":"bordeaux","description":"Bordeaux marked thirty years of Pride with a free public march from Place des Quinconces to the Right Bank on 30 May. Speeches ran from 13:00 with French Sign Language interpretation, the procession moved at 14:00 and the official AfterPride followed at Parc des Sports Saint-Michel.","link":"https://www.bordeaux-metropole.fr/agenda/43347290_the-gay-pride-in-bordeaux","date":"2026-05-30","start_date":"2026-05-30","end_date":"2026-05-30","location":"Place des Quinconces to the Right Bank, Bordeaux, France","lat":44.8456932,"lng":-0.5755545,"vibe":"historic public march balancing celebration, protest and local memory"},
 {"name":"AfterPride Bordeaux 2026","city":"bordeaux","description":"The official march finish became a free river-edge celebration from 17:30 at Parc des Sports Saint-Michel. This was the broad outdoor after rather than a private club party, allowing marchers, associations and friends to stay together before smaller late-night events split across the city.","link":"https://www.bordeaux-metropole.fr/agenda/14994330_mois-des-fiertes-2026-6eme-edition","date":"2026-05-30","start_date":"2026-05-30","end_date":"2026-05-30","location":"Parc des Sports Saint-Michel, Quai de la Monnaie, 33800 Bordeaux, France","lat":44.8338906,"lng":-0.5627077,"vibe":"free outdoor Pride finish with community, music and riverside release"},
 {"name":"Festival Cinémarges 2026","city":"bordeaux","description":"The 21st Cinémarges festival used film, archives, performance and discussion to connect lesbian, gay, trans and feminist resistance with forty years of local HIV history. Its 1-8 April edition crossed Utopia, libraries, universities, art institutions and queer bars rather than hiding inside one cinema.","link":"https://festival.cinemarges.fr/grille-2026","date":"2026-04-01","start_date":"2026-04-01","end_date":"2026-04-08","location":"Cinema Utopia and partner venues across Bordeaux, France","lat":44.8386670,"lng":-0.5708400,"vibe":"politically alive queer cinema moving between institutions and nightlife"},
 {"name":"VendrediXXL Bordeaux 2026","city":"bordeaux","description":"VendrediX takes over Bien Public for a thirteen-hour LGBTQIA+ edition on 18 September, beginning at 17:30 and running to 06:00. Cabaret opens the night, pop and hyperpop take one floor, harder electronic music moves downstairs and an adult Bestial Zone makes the late section explicitly sex-positive.","link":"https://vendredix.fr/event/vendredixxl-22/","date":"2026-09-18","start_date":"2026-09-18","end_date":"2026-09-19","location":"Bien Public, 68 Quai Deschamps, 33100 Bordeaux, France","lat":44.8349431,"lng":-0.5520232,"vibe":"large-scale queer cabaret, hyperpop and adult after-dark freedom"},
 {"name":"Journées du matrimoine et du queer heritage 2026","city":"bordeaux","description":"La Maison des Femmes opens its feminist and queer memory on 19 and 20 September through Isabelle Sentis's exhibition tracing women's houses from San Francisco to Bordeaux. QueerCode, Le Girofard, GiroArchives and La Boîte sous le lit connect the display to living local archive work. Admission is free.","link":"https://journeesdupatrimoine.culture.gouv.fr/w/377623/evenement/19042153/journees-du-matrimoine-patrimoine-et-du-queer-heritage-a-la-maison-des-femmes-de-bordeaux","date":"2026-09-19","start_date":"2026-09-19","end_date":"2026-09-20","location":"Maison des Femmes de Bordeaux, entrance 11 Place du Palais, 33000 Bordeaux, France","lat":44.8379529,"lng":-0.5695156,"vibe":"free feminist and queer heritage told through a living community archive"},
 {"name":"Bal Queer #8","city":"bordeaux","description":"La Bordelle and Salle des Fêtes Bordeaux Grand-Parc return with the eighth Queer Ball on 28 November from 19:00 to 23:30. This is one of the city's strongest collective-led alternatives to permanent gay-club culture: performance, dancing and queer self-fashioning in a large civic hall.","link":"https://www.helloasso.com/associations/la-salle-des-fetes-bordeaux-grand-parc/evenements/bal-queer-8","date":"2026-11-28","start_date":"2026-11-28","end_date":"2026-11-28","location":"Salle des Fêtes Bordeaux Grand-Parc, 39 Cours de Luze, 33300 Bordeaux, France","lat":44.8569011,"lng":-0.5792629,"vibe":"community-made queer ball culture with room for spectacle and participation"},
 {"name":"Drag Me to Rock 2026","city":"bordeaux","description":"Bordeaux Rock, Médusyne and La Bordelle brought drag, live rock and electronic music together at Deus Ex Machina on 27 June. The free event made the Mois des Fiertés finale feel less like generic pop Pride and more like the city's feminist, alternative music network taking the stage.","link":"https://www.bordeaux-metropole.fr/agenda/14994330_mois-des-fiertes-2026-6eme-edition","date":"2026-06-27","start_date":"2026-06-27","end_date":"2026-06-28","location":"Deus Ex Machina, Hangar 16, Quai des Chartrons, 33300 Bordeaux, France","lat":44.8581400,"lng":-0.5646500,"vibe":"free queer rock, drag and electronics with a feminist independent spine"}
]
$bordeaux_events$) e(name text,city text,description text,link text,date date,start_date date,end_date date,location text,lat double precision,lng double precision,vibe text)
), upd as (
 update public.events e set description=s.description,link=s.link,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)) returning e.id
)
insert into public.events(name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.events e where lower(trim(e.city))=s.city and lower(trim(e.name))=lower(trim(s.name)));

with src as (
 select * from jsonb_to_recordset($bordeaux_services$
[
 {"name":"Le Girofard","city":"bordeaux","type":"other","provider_name":"Le Girofard - Centre LGBTQIAP+ de Bordeaux","contact":"09 54 19 65 04; girofard@gmail.com","booking_link":"https://www.le-girofard.org/","description":"Bordeaux's LGBTQIAP+ centre combines community welcome with practical support: violence response, legal and psychological orientation, asylum help, sexual health and chemsex work, trans health, parenthood, senior connection, archives and social groups. Check the specific permanence rather than assuming every specialist is present whenever the centre is open.","hours":"Programme and appointment based; consult the current agenda or contact the centre before travelling.","link":"https://www.le-girofard.org/","location":"21 Rue du Loup, 33000 Bordeaux, France","lat":44.8380357,"lng":-0.5726379,"price_tier":"$","vibe":"community front door joining care, organising, memory and everyday queer company","source":"Le Girofard official site and Gironde service directory; checked 2026-08-14"},
 {"name":"CeGIDD Bordeaux","city":"bordeaux","type":"wellness","provider_name":"Département de la Gironde","contact":"05 57 22 46 66; PrEP 05 57 22 46 60","booking_link":"https://www.doctolib.fr/centre-de-sante/bordeaux/conseil-departemental-de-gironde","description":"Free HIV, STI and hepatitis testing with anonymous access available, plus results, PrEP consultations, sexology and a Tuesday chemsex listening service with ENIPSE. Most testing windows are walk-in, while Tuesday afternoon and PrEP require appointments. Tell staff about exposure timing so they can choose the right tests and follow-up.","hours":"Walk-in testing Monday, Wednesday and Friday 09:00-14:00 and Thursday 14:00-18:00; Tuesday 13:45-18:30 by appointment. Secretariat weekdays 08:30-17:00.","link":"https://www.gironde.fr/lieu/centre-gratuit-dinformation-de-depistage-et-de-diagnostic-cegidd","location":"Maison du Département de la Promotion de la Santé, 2 Rue du Moulin Rouge, 33200 Bordeaux, France","lat":44.8417312,"lng":-0.6026941,"price_tier":"$","vibe":"confidential public sexual-health care with practical PrEP and chemsex pathways","source":"Gironde official CeGIDD page and Sida Info Service directory; checked 2026-08-14"},
 {"name":"ANCRES","city":"bordeaux","type":"other","provider_name":"ANCRES - Adelphes Non-Cisgenres","contact":"contact.ancres@gmail.com","booking_link":"https://ancresassociation.org/","description":"A trans-led association for trans, non-binary and questioning people, built around peer support rather than clinical gatekeeping. It offers administrative help, experience-sharing sessions, individual appointments, auto-injection workshops and injection kits, with most activity hosted at Le Girofard.","hours":"Permanence and workshop based; use the current official agenda for dates and registration.","link":"https://ancresassociation.org/","location":"Activities mainly at Le Girofard, 21 Rue du Loup, 33000 Bordeaux, France","lat":44.8380357,"lng":-0.5726379,"price_tier":"$","vibe":"trans-led mutual aid that turns paperwork, health knowledge and isolation into shared practice","source":"ANCRES official service and agenda pages; checked 2026-08-14"},
 {"name":"Maison des Femmes de Bordeaux","city":"bordeaux","type":"other","provider_name":"La Maison des Femmes de Bordeaux","contact":"05 56 51 30 95; maison.des.femmes@orange.fr","booking_link":"https://maisondesfemmes.net/nos-accueils/accueil-ecoute-orientation/","description":"A feminist social welcome for all women facing isolation, access-to-rights, work, health or administrative problems. Support is anonymous, free and confidential, with both individual orientation and collective activity. Its queer partnerships include Girofard, QueerCode and local archive work, but it is a women's service rather than a general LGBTQ centre.","hours":"Monday-Wednesday and Friday 14:00-18:00; closed Thursday. Available with or without appointment.","link":"https://maisondesfemmes.net/","location":"27 Cours d'Alsace et Lorraine, entrance at 11 Place du Palais, 33000 Bordeaux, France","lat":44.8379529,"lng":-0.5695156,"price_tier":"$","vibe":"confidential feminist listening with a practical route back to rights and connection","source":"Maison des Femmes official social-welcome page and French Ministry of Culture 2026 programme; checked 2026-08-14"},
 {"name":"Bordeaux Ville Sans Sida Prevention Kits","city":"bordeaux","type":"wellness","provider_name":"Bordeaux Ville Sans Sida","contact":"Order through the secure official form","booking_link":"https://bordeaux-ville-sans-sida.fr/test-prevention/","description":"A free prevention kit combines a self-administered HIV test, internal and external condoms and sexual-health information. Bordeaux residents can request discreet home delivery or arrange collection from the Rue du Loup office. A self-test cannot replace urgent post-exposure care; possible exposure within 48 hours needs emergency medical advice.","hours":"Online order at any time; collection is arranged by email rather than treated as a public walk-in.","link":"https://bordeaux-ville-sans-sida.fr/test-prevention/","location":"Collection by appointment at 21 Rue du Loup, 33000 Bordeaux, France","lat":44.8380357,"lng":-0.5726379,"price_tier":"$","vibe":"discreet, no-cost HIV self-testing linked to the city's wider prevention network","source":"Bordeaux Ville Sans Sida official prevention-kit page; checked 2026-08-14"}
]
$bordeaux_services$) s(name text,city text,type text,provider_name text,contact text,booking_link text,description text,hours text,link text,location text,lat double precision,lng double precision,price_tier text,vibe text,source text)
), upd as (
 update public.services x set type=s.type,provider_name=s.provider_name,contact=s.contact,booking_link=s.booking_link,description=s.description,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,price_tier=s.price_tier,vibe=s.vibe,source=s.source,"lastChecked"='2026-08-14'::date,verified=true,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now())
 from src s where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)) returning x.id
)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified,seo_indexable,seo_quality_status,updated_at)
select name,city,type,provider_name,contact,booking_link,description,hours,link,array[]::text[],location,lat,lng,price_tier,vibe,array[]::text[],source,'2026-08-14'::date,true,true,'approved',timezone('utc',now()) from src s
where not exists(select 1 from public.services x where lower(trim(x.city))=s.city and lower(trim(x.name))=lower(trim(s.name)));

commit;

select 'places' category,count(*) total from public.places where lower(trim(city))='bordeaux'
union all select 'events',count(*) from public.events where lower(trim(city))='bordeaux'
union all select 'services',count(*) from public.services where lower(trim(city))='bordeaux'
order by category;
