-- Queer Atlas: Almaty, Kazakhstan city package
-- Verified 2026-09-13. Safe to run multiple times.
-- Protected community addresses remain confidential. Closed Amirovka, Chernika and PlayBoy records are excluded.
begin;

with new_places (name,city,type,description,vibe,hours,link,location,lat,lng) as (values
    ('bULt', 'almaty', 'club', 'A raw experimental rave and arts space whose own manifesto aims to be safe for every form of life. bULt is one of Almaty''s strongest mixed late-night signals for queer travelers who follow sound, community and boundary-pushing bookings rather than rainbow branding.', 'community-driven experimental rave room with an art-school pulse', 'Event-led; doors and finish times vary. Check the current programme before travel.', 'https://www.instagram.com/bult____/', '83 Gagarin Avenue, Almaty 050000, Kazakhstan', 43.2368, 76.8937),
    ('Kumäno', 'almaty', 'bar', 'An intimate bar with serious cocktails, a house lager and selectors who can turn a late dinner into a tight, friendly dance floor. The crowd is mixed and creative; its value is the unforced social chemistry rather than a claim to be a dedicated queer venue.', 'tiny cocktail den where dinner drifts into left-field dancing', 'Evening-led; verify the current weekly schedule and DJ programme.', 'https://www.instagram.com/kumano.bar/', '124 Nazarbayev Avenue, Almaty 050000, Kazakhstan', 43.2512, 76.9451),
    ('Sky Bar & Lounge', 'almaty', 'bar', 'The Ritz-Carlton''s elevated lounge trades underground energy for city lights, polished drinks and an international hotel crowd. It is a useful low-friction date or first-night option, but remains a mainstream luxury bar rather than an LGBTQ+ venue.', 'high-altitude hotel cocktails above the Nurly Tau skyline', 'Hotel bar schedule varies; reserve and confirm the current service hours.', 'https://www.ritzcarlton.com/en/hotels/alarz-the-ritz-carlton-almaty/dining/', 'Esentai Tower, 77/7 Al-Farabi Avenue, Almaty 050040, Kazakhstan', 43.2189, 76.9284),
    ('Almaty Museum of Arts', 'almaty', 'cafe', 'A major private museum for modern and contemporary art that gives an Almaty itinerary cultural weight beyond nightlife. Use the exhibition calendar for the city''s most ambitious visual conversations; the museum is included as a mixed cultural anchor, not a queer institution.', 'new contemporary-art landmark with a sharp Central Asian lens', 'Tue-Sun 11:00-21:00; closed Monday; last admission 20:00. Holiday hours may vary.', 'https://www.almaty.art/contact', '28 Al-Farabi Avenue, Almaty, Kazakhstan', 43.2221, 76.9289),
    ('The Dostyk Hotel', 'almaty', 'hotel', 'A protected architectural landmark in the historic centre with a 15-metre pool, hammam, sauna and a genuinely useful position for theatres, cafés and Abay metro. Its 24-hour bar makes late arrivals easier without pretending the property has a queer programme.', 'heritage five-star calm beside theatres, consulates and Abay metro', 'Hotel open daily; Bastau Bar operates 24 hours according to the hotel.', 'https://dostyk.kz/en/about', '36 Kurmangazy Street, Almaty 050021, Kazakhstan', 43.2447, 76.9542),
    ('Hotel Kazakhstan', 'almaty', 'hotel', 'Almaty''s unmistakable 26-storey landmark gives a stay local architectural drama and fast access to Dostyk Avenue, Kok Tobe and the Palace of the Republic. Choose it for character and location, while confirming any accessibility or privacy requirement directly.', 'Soviet-modernist icon with mountain-facing city character', 'Hotel and reception operate daily; booking office hours differ.', 'https://kazakhstanhotel.kz/en/', '52/2 Dostyk Avenue, Almaty 050010, Kazakhstan', 43.2449, 76.9588),
    ('Rixos Almaty', 'almaty', 'hotel', 'A polished central hotel with 235 rooms, a pool and full spa, set between the café grid and Almaty''s wider business district. It works as a contained, service-heavy base when privacy and recovery matter more than being inside the late-night circuit.', 'grand five-star calm with a spa behind the central avenues', 'Hotel open daily; check-in 15:00 and check-out 12:00.', 'https://www.rixos.com/hotel-resort/rixos-almaty', '506/99 Seifullin Avenue, Almaty 050012, Kazakhstan', 43.2501, 76.9282),
    ('The Ritz-Carlton, Almaty', 'almaty', 'hotel', 'High floors, mountain views and direct access to Esentai Mall make this the city''s most cinematic international hotel base. The appeal is controlled service and a private retreat above the city, not a verified property-specific LGBTQ+ programme.', 'skyline luxury with Tian Shan views above Esentai', 'Hotel open daily; confirm current check-in, spa and dining reservations.', 'https://www.ritzcarlton.com/en/hotels/alarz-the-ritz-carlton-almaty/overview/', 'Esentai Tower, 77/7 Al-Farabi Avenue, Almaty 050040, Kazakhstan', 43.2189, 76.9284)
), updated as (
 update public.places p set type=n.type,description=n.description,vibe=n.vibe,hours=n.hours,link=n.link,location=n.location,lat=n.lat,lng=n.lng from new_places n where lower(trim(p.city))=n.city and lower(trim(p.name))=lower(trim(n.name)) returning p.id
)
insert into public.places(name,city,type,description,vibe,hours,link,location,lat,lng)
select n.* from new_places n where not exists(select 1 from public.places p where lower(trim(p.city))=n.city and lower(trim(p.name))=lower(trim(n.name)));

with venue_intel(name,intel) as (values
 ('bULt',jsonb_build_object('queue_wait','bULt opens around individual rave and art programmes, commonly with late doors and event-specific admission. Check the latest post, age rule and ticket method before travelling to Gagarin Avenue.','best_nights','A named experimental, techno or guest-DJ booking is the reason to go; an unprogrammed night is not a reliable visit. The room usually develops after midnight rather than at cocktail hour.','crowd_mix','Almaty electronic regulars, artists, students, visiting selectors and a visible but discreet queer contingent share a mixed dance floor.','dress_code','Functional rave clothing and shoes built for dancing fit the industrial mood. Avoid photographing people without clear consent; discretion is part of the room''s safety culture.','staff_inclusivity','The operator describes bULt as a community-driven arts environment aiming to be safe for all forms of life. That is a meaningful venue statement, though no detailed public safeguarding or accessibility protocol was found.','source_urls',jsonb_build_array('https://www.instagram.com/bult____/','https://t.me/bULtAlmaty','https://ra.co/events/1908272'),'research_status','current_operator_and_editorial_sources','updated_at','2026-09-13T00:00:00Z')),
 ('Kumäno',jsonb_build_object('queue_wait','Kumäno is compact, so a strong DJ night can run out of comfortable standing room faster than a conventional club. Begin with food or cocktails before the late crowd closes in.','best_nights','Follow the selector rather than the weekday: slow disco, house and visiting-DJ collaborations produce different rooms. Earlier hours favour conversation; later sets turn the bar into a dance pocket.','crowd_mix','Cocktail people, food-industry friends, young creatives, local nightlife regulars and queer guests mix without a dedicated LGBTQ+ identity.','dress_code','Smart casual, vintage and creative everyday looks all work in the intimate room. There is no verified formal fashion gate.','staff_inclusivity','Current nightlife reporting supports a friendly mixed atmosphere, but the venue publishes no LGBTQ+ policy or detailed incident process. Treat the welcome as social evidence rather than a formal guarantee.','source_urls',jsonb_build_array('https://www.instagram.com/kumano.bar/','https://openkitchen.eda.yandex/article/places/guides/where-to-dance-7-bars-with-great-music'),'research_status','current_operator_and_editorial_sources','updated_at','2026-09-13T00:00:00Z')),
 ('Sky Bar & Lounge',jsonb_build_object('queue_wait','Reserve a table for sunset, weekends or a date where the view matters; hotel security and elevator access replace the street-club queue.','best_nights','Clear evenings deliver the skyline and mountain silhouette. This is a composed first drink or date, not the city''s underground late-night peak.','crowd_mix','Hotel guests, business travelers, affluent locals, couples and international visitors form a polished mixed room.','dress_code','Smart casual suits the luxury-hotel setting; avoid sportswear and confirm any evening-specific table terms.','staff_inclusivity','Marriott publishes global inclusion commitments, but no Almaty-property LGBTQ+ training or safeguarding policy was located. Request privacy, name handling and access needs directly.','source_urls',jsonb_build_array('https://www.ritzcarlton.com/en/hotels/alarz-the-ritz-carlton-almaty/dining/'),'research_status','current_operator_source','updated_at','2026-09-13T00:00:00Z')),
 ('Almaty Museum of Arts',jsonb_build_object('queue_wait','Timed talks, openings and headline exhibitions can concentrate arrivals; ordinary gallery visits should follow the museum''s current ticket and entry guidance.','best_nights','Choose an opening, artist talk or public programme for social energy; a daytime visit gives the architecture and collection more room.','crowd_mix','Artists, design audiences, students, cultural travelers and Almaty''s contemporary creative community.','dress_code','Everyday museum clothing; expressive style fits, but the visit is about art rather than a door scene.','staff_inclusivity','The museum is a mixed cultural institution and makes no verified LGBTQ-specific promise. Its public programme is relevant cultural infrastructure, not evidence of a queer safe-space policy.','source_urls',jsonb_build_array('https://www.almaty.art/'),'research_status','current_operator_source','updated_at','2026-09-13T00:00:00Z')),
 ('The Dostyk Hotel',jsonb_build_object('queue_wait','Reception is the main arrival point; reserve rooms and spa treatments ahead, while the 24-hour Bastau Bar removes timing pressure after a late flight.','best_nights','Use the hotel for a quiet central reset, theatre-adjacent dinner or late private drink rather than programmed queer nightlife.','crowd_mix','Business guests, diplomatic visitors, heritage-minded tourists and local restaurant or spa guests.','dress_code','Polished everyday hotel clothing; spa and restaurant areas have their own conventional expectations.','staff_inclusivity','The property documents its facilities and central consular location but publishes no LGBTQ+ training statement. Confirm room setup, guest access and name handling privately before arrival.','source_urls',jsonb_build_array('https://dostyk.kz/en/about'),'research_status','current_operator_source','updated_at','2026-09-13T00:00:00Z')),
 ('Hotel Kazakhstan',jsonb_build_object('queue_wait','The 24-hour reception handles a large landmark property; booking directly reduces ambiguity around room type, visitors and mountain-view requests.','best_nights','Stay for the architecture and location, then use verified events elsewhere. The hotel itself is not a standing queer social venue.','crowd_mix','Tour groups, domestic travelers, business guests and architecture-curious international visitors.','dress_code','Standard city-hotel clothing; individual restaurants may expect smart casual dress.','staff_inclusivity','No property-specific LGBTQ+ or detailed accessibility policy was found. Its value is a central, staffed base; confirm sensitive requests directly and avoid assuming brand-level protections.','source_urls',jsonb_build_array('https://kazakhstanhotel.kz/en/contacts'),'research_status','current_operator_source','updated_at','2026-09-13T00:00:00Z')),
 ('Rixos Almaty',jsonb_build_object('queue_wait','A large hotel reception absorbs normal arrivals, but rooms, spa access and restaurant tables should be booked separately during conferences and holidays.','best_nights','Choose it for spa recovery or a contained luxury evening after the city; there is no verified recurring LGBTQ+ programme.','crowd_mix','International and Kazakh business travelers, tour guests, conference groups and luxury city-break visitors.','dress_code','Smart casual in public areas, with standard pool and spa attire in wellness spaces.','staff_inclusivity','The official listing documents wheelchair access, pool and hotel services. Accor has corporate inclusion commitments, but no Almaty-specific LGBTQ+ training claim was found; confirm personal requirements with reception.','source_urls',jsonb_build_array('https://www.rixos.com/hotel-resort/rixos-almaty'),'research_status','current_operator_source','updated_at','2026-09-13T00:00:00Z')),
 ('The Ritz-Carlton, Almaty',jsonb_build_object('queue_wait','Advance room and spa reservations matter more than a queue; Esentai security and the high-rise arrival sequence add a controlled layer between street and lobby.','best_nights','A clear-sky stay maximizes Tian Shan views, while an early evening reservation works for skyline dining before a separately verified event.','crowd_mix','Luxury leisure guests, executives, international visitors and affluent local diners in a discreet, service-led environment.','dress_code','Refined smart casual fits the lobby and dining rooms; confirm spa and restaurant requirements independently.','staff_inclusivity','Marriott''s global policies provide a corporate baseline, but no public Almaty-property LGBTQ+ protocol was found. Directly confirm privacy, companion access, names and any mobility requirement.','source_urls',jsonb_build_array('https://www.ritzcarlton.com/en/hotels/alarz-the-ritz-carlton-almaty/overview/'),'research_status','current_operator_source','updated_at','2026-09-13T00:00:00Z'))
)
update public.places p set venue_intel=v.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from venue_intel v where lower(trim(p.city))='almaty' and lower(trim(p.name))=lower(trim(v.name));

with new_services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified) as (values
 ('Safe Space Almaty','almaty','other','Safe Space Almaty','Contact through the official Telegram channel; the physical address is released only after community screening.','https://t.me/safe_space_ala_center','A screened community centre for LGBTQ+ people and allies offering gatherings, workshops, film discussions and peer connection. Its address is intentionally withheld for participant safety.','Programme-led; register through the current channel before attending.','https://t.me/safe_space_ala_center',array[]::text[],'Confidential location, Almaty, Kazakhstan',43.2389,76.8897,'$','screened LGBTQ+ community centre with protected access',array['service','social','cultural']::text[],'Safe Space Almaty official Telegram channel','2026-09-13'::date,true),
 ('Feminita Kazakhstan','almaty','other','Feminita','Use the official website or social channels; do not visit an assumed office address.','https://feminita.kz/','A feminist initiative led by queer women that documents rights conditions, supports community advocacy and publishes current information under intense legal pressure.','Online and campaign availability varies; contact before arranging any meeting.','https://feminita.kz/',array[]::text[],'Contact-led service, Almaty, Kazakhstan',43.2389,76.8897,'$','queer feminist rights work and community advocacy',array['service','cultural','social']::text[],'Feminita official website','2026-09-13'::date,true),
 ('Kok.team','almaty','other','Kok.team','Use the publication contact channels.','https://www.kok.team/','Kazakhstan-focused LGBTQ+ media and community information with reporting on rights, health, local initiatives and support routes. It is a digital resource, not a walk-in venue.','Online publication.','https://www.kok.team/',array[]::text[],'Online service, Almaty, Kazakhstan',43.2389,76.8897,'$','Kazakh and Russian-language LGBTQ+ information',array['service','cultural']::text[],'Kok.team publication','2026-09-13'::date,true),
 ('Almaty City AIDS Center','almaty','other','Almaty City Center for HIV Prevention','Confirm testing hours and confidentiality procedures through the official centre.','https://www.gcaids.kz/en/','The municipal HIV prevention centre provides the city''s formal testing and treatment pathway. Ask directly about anonymous or confidential options and current documentation requirements before arrival.','Clinic hours vary by service; verify before visiting.','https://www.gcaids.kz/en/',array[]::text[],'Almaty, Kazakhstan',43.2389,76.8897,'$','official HIV testing, prevention and treatment pathway',array['service','relax']::text[],'Almaty City AIDS Center official website','2026-09-13'::date,true)
), updated as (
 update public.services s set type=n.type,provider_name=n.provider_name,contact=n.contact,booking_link=n.booking_link,description=n.description,hours=n.hours,link=n.link,image_urls=n.image_urls,location=n.location,lat=n.lat,lng=n.lng,price_tier=n.price_tier,vibe=n.vibe,vibe_tags=n.vibe_tags,source=n.source,"lastChecked"=n."lastChecked",verified=n.verified from new_services n where lower(trim(s.city))=n.city and lower(trim(s.name))=lower(trim(n.name)) returning s.id
)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified) select n.* from new_services n where not exists(select 1 from public.services s where lower(trim(s.city))=n.city and lower(trim(s.name))=lower(trim(n.name)));

insert into public.qa_country_rights_profiles(country,legal_level,rights_level,safety_level,same_sex_relations_status,union_status,legal_gender_recognition_status,anti_discrimination_status,what_this_means,confidence,source_legal_url,source_rights_url,source_safety_url,source_checked_at,needs_manual_review) values
('Kazakhstan','risk','risk','risk','legal','no_protection','restricted','limited_or_none','Consensual same-sex relations are legal, but same-sex relationships receive no recognition and Kazakhstan has no explicit national LGBTQ+ anti-discrimination protection. Public and online expression faces additional risk under the 2026 censorship law; Almaty community spaces often rely on discretion and screening.','high','https://www.equaldex.com/region/kazakhstan','https://outrightinternational.org/our-work/europe-and-central-asia/kazakhstan','https://www.hrw.org/world-report/2026/country-chapters/kazakhstan','2026-09-13'::date,false)
on conflict(country) do update set legal_level=excluded.legal_level,rights_level=excluded.rights_level,safety_level=excluded.safety_level,same_sex_relations_status=excluded.same_sex_relations_status,union_status=excluded.union_status,legal_gender_recognition_status=excluded.legal_gender_recognition_status,anti_discrimination_status=excluded.anti_discrimination_status,what_this_means=excluded.what_this_means,confidence=excluded.confidence,source_legal_url=excluded.source_legal_url,source_rights_url=excluded.source_rights_url,source_safety_url=excluded.source_safety_url,source_checked_at=excluded.source_checked_at,needs_manual_review=excluded.needs_manual_review;
insert into public.qa_qari_profiles(destination_key,scope_type,country,city_key,legal_risk,social_risk,digital_risk,risk_floor,confidence,summary,methodology_version,reviewed_by,reviewed_at,is_published) values
('country:kazakhstan','country','Kazakhstan',null,65,88,85,0,'high','Same-sex relations are legal, but absent relationship and anti-discrimination protections combine with extremely low reported acceptance and a 2026 censorship law carrying fines or detention. Public, organizational and digital visibility require substantial care.','1.0','Queer Atlas editorial review','2026-09-13'::date,true)
on conflict(destination_key) do update set legal_risk=excluded.legal_risk,social_risk=excluded.social_risk,digital_risk=excluded.digital_risk,risk_floor=excluded.risk_floor,confidence=excluded.confidence,summary=excluded.summary,methodology_version=excluded.methodology_version,reviewed_by=excluded.reviewed_by,reviewed_at=excluded.reviewed_at,is_published=excluded.is_published;

delete from public.qa_qari_sources where destination_key='country:kazakhstan';
insert into public.qa_qari_sources(destination_key,axis,source_type,label,url,supports_claim,published_at,checked_at) values
('country:kazakhstan','legal','legal_database','Equaldex · Kazakhstan','https://www.equaldex.com/region/kazakhstan','Documents legal same-sex relations, banned marriage, restricted gender recognition and absent explicit protections.',null,'2026-09-13'::date),
('country:kazakhstan','social','legal_database','Equaldex · Kazakhstan public opinion','https://www.equaldex.com/region/kazakhstan','Reports 6% describing their area as a good place for gay and lesbian people in the 2024 Gallup measure.',null,'2026-09-13'::date),
('country:kazakhstan','digital','ngo_report','Human Rights Watch · World Report 2026','https://www.hrw.org/world-report/2026/country-chapters/kazakhstan','Documents the censorship law and penalties affecting LGBTQ+ expression.','2026-01-01'::date,'2026-09-13'::date),
('country:kazakhstan','digital','ngo_report','Outright International · Kazakhstan','https://outrightinternational.org/our-work/europe-and-central-asia/kazakhstan','Documents the enacted propaganda ban and pressure on LGBTQ+ activists.','2026-03-12'::date,'2026-09-13'::date);

commit;



