-- Queer Atlas: Windhoek venue, event and service intelligence
-- Run after city-windhoek-curated-v1.sql. Idempotent and apostrophe-safe.

begin;

with researched as (
 select * from jsonb_to_recordset($windhoek_place_intel$
[
 {"name":"Piccolo Cafe & Lounge","patch":{"queue_wait":"Ordinary breakfast and lunch service is normally a walk-in. Tuesday trivia, a Drag Night collaboration or a busy late meal can fill tables, so a group should call ahead rather than treating the mall location as unlimited capacity.","best_nights":"Tuesday is the easiest social entry because the recurring trivia night gives strangers something to do together. For a quieter first meeting, choose daytime or early evening; Piccolo is an everyday ally venue, not a dance floor that only becomes useful after midnight.","crowd_mix":"Mall diners, friends, date-night couples, trivia teams, hospitality regulars, queer locals and allies overlap. The room is mixed rather than tourist-led, and its LGBTQI+ value comes from an explicit welcome instead of an exclusively queer clientele.","dress_code":"Windhoek casual works: jeans, trainers, a clean shirt or an easy dinner look. Drag and safe-space launches naturally bring more colour, but there is no standing scene code. Carry a light layer for the later ride home.","staff_inclusivity":"Equal Namibia and Drag Night Namibia formally inaugurated Piccolo into the Verified Safe-Space network, and the co-owner publicly stated that the venue is open to everyone. That is stronger evidence than a generic friendly label; any current access concern should still be raised directly with management.","review_signal":"Current directories place Piccolo around 4.3 from more than fifty reviews, while local recommendations repeatedly mention it as a safe social option. The useful consensus is relaxed food-and-drinks energy, not luxury service or a purpose-built gay club.","identity_note":"Verified LGBTQI+ ally cafe and lounge with a mixed public, not a dedicated queer bar.","source_urls":["https://www.namibian.com.na/piccolo-declared-lgbtqi-safe-space/","https://www.whatsonnamibia.com/events/venue/piccolo-cafe-and-lounge","https://www.africabizinfo.com/NA/piccolo-caf%C3%A9-lounge-081-645-1884","https://www.reddit.com/r/Namibia/comments/1rinzmj/hi_does_anyone_know_any_safe_spaces_for_lgbtq/"],"research_status":"source_synthesised_current","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"The Village Windhoek","patch":{"queue_wait":"There is no general door queue. The free Sunday market is the main pressure point: parking, brunch tables and popular stalls tighten from late morning. Suite check-in, private events and restaurant bookings each have their own flow.","best_nights":"Sunday 09:00-15:00 is the clearest community moment, with stalls, food and live music. A weekday stay or courtyard meeting is calmer. Choose The Village for daylight connection and a soft social landing, not for a guaranteed queer night.","crowd_mix":"Local families, entrepreneurs, market vendors, remote workers, restaurant guests and international suite residents share the courtyards. Queer people and allies are part of that broad public rather than a separate house crowd.","dress_code":"Relaxed, sun-ready clothes suit the garden and market; add a hat, water and comfortable shoes for browsing. Dinner and private-event looks can be smarter, but the complex does not publish a general dress code.","staff_inclusivity":"Equal Namibia has listed The Village in its Verified Safe-Space network, while the venue's own community language centres kindness, respect and an open welcome. The recognition applies to the complex's public ethos; individual tenant experiences can still differ.","review_signal":"Recent review summaries are unusually consistent about the landscaped calm, attractive suites, Sunday atmosphere and useful mix of restaurants. The Village scores around 4.5 across hundreds of map reviews; overnight guests especially praise space and staff, with a smaller accommodation sample than the public venue.","identity_note":"Mixed-use hospitality and community compound with verified LGBTQI+ ally status, not a queer-only hotel.","source_urls":["https://www.namibian.com.na/piccolo-declared-lgbtqi-safe-space/","https://www.villagewhk.com/community","https://www.villagewhk.com/","https://wanderlog.com/place/details/8268236/the-village","https://www.booking.com/hotel/na/the-village-suites-windhoek.en-gb.html"],"research_status":"source_synthesised_current","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"The Brewers Market","patch":{"queue_wait":"An ordinary bar visit is usually straightforward; ticket scanning and security can create a real line when a large concert or Pride production occupies the old theatre rooms. Buy through the named organiser and arrive before the published start if the stage matters.","best_nights":"For queer community, the best night is whichever Pride Pop-Up, Kings of Namibia or allied producer has actually announced. Friday and Saturday are livelier for the mixed bar crowd, but a generic weekend should never be advertised as a substitute for a queer programme.","crowd_mix":"Young Windhoek locals, live-music audiences, beer drinkers, creatives and visitors dominate ordinary service. A Pride takeover changes the balance toward LGBTQI+ community, performers, organisers and allies, sometimes with regional guests.","dress_code":"Everyday nightlife clothes and practical shoes suit the industrial building. Pride productions invite colour and self-expression; a themed event may add its own prompt. The large rooms can shift temperature, so a light layer is useful.","staff_inclusivity":"The building has repeatedly made room for queer organisers and sits beside a Pride-created rainbow crossing, but no current venue-wide LGBTQI+ policy was found. Judge inclusion through the named host and current event welfare information rather than the historical Warehouse reputation alone.","review_signal":"Recent local nightlife discussions still place Brewers among Windhoek favourites, praising its live programme and old-brewery atmosphere. Published hours conflict and the complex is large enough to feel empty without an event, making calendar choice more important than aggregate ratings.","identity_note":"Mixed brewpub and event complex with significant queer event history; not a permanent gay bar.","source_urls":["https://weshareevents.com/event/house-of-rainbows-2026/","https://www.namibian.com.na/pride-pop-up-returns-with-continental-collaboration/","https://www.petitfute.co.uk/v53560-windhoek/c1169-s-amuser-sortir/c182-bar-cafe/1583862-the-brewers-market.html","https://www.reddit.com/r/Namibia/comments/1kjc11b/how_is_nightlife_in_windhoek/"],"research_status":"source_synthesised_current","updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Le Roof at FNCC","patch":{"queue_wait":"The room follows the event, not daily bar traffic. Drag and Pride nights use a ticket check and can bunch close to showtime; cinema sessions are calmer. Arrive 30 minutes early when sightline or seating matters.","best_nights":"Choose a named Drag Night Namibia, Pride Week or LGBTQIA+ cinema listing. The 2026 Pride Kiki Ball and Motown show demonstrate the room at full queer energy; an unrelated FNCC booking will have a completely different audience.","crowd_mix":"Artists, students, cultural workers, diplomats and general Windhoek audiences use FNCC across the year. Queer programmes bring LGBTQI+ locals, drag and ballroom performers, allies and Pride collaborators into the same open-air room.","dress_code":"No permanent code. Film nights are casual; drag and ballroom programmes reward expressive looks without requiring guests to compete. Outdoor evening air can cool quickly, so build the outfit around a layer you can keep.","staff_inclusivity":"FNCC programmed a three-film LGBTQIA+ series in 2026 and repeatedly hosted Drag Night Namibia and Pride work. That is concrete institutional evidence, although accessibility, age limits and welfare arrangements still need to be checked per event.","review_signal":"The strongest signal is programme history rather than a separate Le Roof review score. Local reporting describes the terrace coming alive for drag and ballroom, while FNCC's official calendar confirms repeated queer cultural programming.","identity_note":"Event-led open-air room inside a broader cultural centre, queer when the published programme is queer.","source_urls":["https://www.fncc.org.na/events","https://www.namibian.com.na/kiki-ball-kicks-of-lgbtqi-pride-month/","https://www.namibiansun.com/art-and-entertainment/drag-night-namibia-brings-motown-glam-to-the-stage-nmh006459-1-7146","https://www.museums.com.na/museums/windhoek/franco-namibian-cultural-centre-fncc"],"research_status":"source_synthesised_current","updated_at":"2026-08-15T00:00:00Z"}}
]
$windhoek_place_intel$) r(name text,patch jsonb)
)
update public.places p set venue_intel=coalesce(p.venue_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(p.city))='windhoek' and lower(trim(p.name))=lower(trim(r.name));

with researched as (
 select * from jsonb_to_recordset($windhoek_event_intel$
[
 {"name":"Drag Night Namibia: Drag Me to Motown 2026","patch":{"entry_wait":"Advance and door tickets were both published; the practical delay was concentrated near the 19:00 start. Arriving around 18:30 gave time for ticket check and a useful position without missing the opening look.","best_arrival":"Thirty minutes before the show. The production was performance-led rather than an all-night club, so arriving after the first number meant losing part of the actual event.","crowd_mix":"Local drag audiences, LGBTQI+ community, Positive Vibes campaign performers, fashion and music creatives, and allies.","dress_code":"Retro glamour, sequins and Motown references suited the theme, but guests were not required to arrive in costume. A warm evening layer remained practical for Le Roof.","host_inclusivity":"Drag Night Namibia is a queer and trans performance platform; the 2026 cast also connected to Positive Vibes' empowerment campaign, making inclusion part of the production rather than surface branding.","source_urls":["https://weshareevents.com/event/drag-night-namibia-2/","https://www.namibiansun.com/art-and-entertainment/drag-night-namibia-brings-motown-glam-to-the-stage-nmh006459-1-7146","https://www.culturalagendanamibia.com/theaterperformance-art"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Pride Kiki Ball 2026","patch":{"entry_wait":"Tickets were N$150 in advance and N$180 at the door. Competitors needed more preparation time than spectators, while the public benefited from arriving before the 19:00 opening and category briefings.","best_arrival":"Around 18:30 for spectators; competitors needed the organiser's own call time with hair, makeup and category looks already prepared.","crowd_mix":"Lesbian, gay, bisexual, trans, queer and intersex locals, drag and ballroom performers, designers, judges, community partners and allies shared the floor.","dress_code":"The theme was Show Us Your Pride. Spectators could dress expressively; entrants followed category language such as corporate realness, face, runway, body and Vogue Femme rather than a generic club code.","host_inclusivity":"All categories were explicitly open to everyone. Drag Night Namibia used ballroom as storytelling and community-building, with local queer judges and broad Pride collaboration.","source_urls":["https://www.namibian.com.na/kiki-ball-kicks-of-lgbtqi-pride-month/","https://www.glartent.com/NA/Windhoek/107247418084392/Drag-Night-Namibia"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"House of Rainbows 2026","patch":{"entry_wait":"Presale was N$50 and door entry N$100. The ten-hour format spread arrivals, but evening performances were the natural pressure point; buying first and reaching the old theatre before the headline programme reduced friction.","best_arrival":"Early afternoon for games, stalls and conversation; early evening for music and performance. The event was designed as a full arc, not only a late party.","crowd_mix":"Queer community, allies, Pride Pop-Up regulars, Kings of Namibia audiences, performers, creatives and people looking for low-pressure connection before the night intensified.","dress_code":"The organiser invited guests to dress to impress, but the day-long programme rewarded comfort, practical shoes and a layer as much as glamour.","host_inclusivity":"Pride Pop-Up, Kings of Namibia and Fruity Connects explicitly framed the event around queer joy, visibility, creativity and a safe community space.","source_urls":["https://weshareevents.com/event/house-of-rainbows-2026/","https://www.namibian.com.na/kiki-ball-kicks-of-lgbtqi-pride-month/"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Les Rendez-vous Cinema: LGBTQIA+ Film Series 2026","patch":{"entry_wait":"Cinema entry was lower-pressure than the Pride performance nights, but each film used its own event listing. Arriving 20 to 30 minutes early allowed time for seating and any introduction.","best_arrival":"Before the advertised 18:00 screening on 1, 8 or 22 July; the value lay in the complete film and discussion context rather than dropping into a late party.","crowd_mix":"Queer viewers, film audiences, students, Francophone cultural followers, artists and allies interested in identity and contemporary cinema.","dress_code":"Casual cultural-centre clothing with an evening layer. There was no performance or scene code.","host_inclusivity":"FNCC curated the series explicitly around LGBTQIA+ lives, desire, becoming and return, giving queer stories a repeated institutional slot rather than a one-night rainbow label.","source_urls":["https://www.fncc.org.na/events","https://weshareevents.com/events/"],"updated_at":"2026-08-15T00:00:00Z"}}
]
$windhoek_event_intel$) r(name text,patch jsonb)
)
update public.events e set event_intel=coalesce(e.event_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(e.city))='windhoek' and lower(trim(e.name))=lower(trim(r.name));

with researched as (
 select * from jsonb_to_recordset($windhoek_service_intel$
[
 {"name":"Out-Right Namibia","patch":{"booking_lead_time":"Call or email before travelling. Counselling, crisis response, health work and legal-literacy support use different staff and may not share a public walk-in schedule.","best_time":"Weekday daytime is the safest first contact. State whether the need concerns immediate safety, psychosocial support, HIV or SRHR, legal information or community connection so the message reaches the right programme.","client_mix":"LGBTQI+ Namibians across identities and regions, people seeking health or psychosocial support, activists, families and community partners.","preparation":"Share only the details needed for triage, ask how confidentiality is handled and confirm the exact meeting point before arrival. For urgent danger, use emergency services rather than waiting on email.","provider_inclusivity":"The organisation is LGBTQI+ mandated and combines rights work with direct psychosocial, crisis and health programmes; inclusion is its operating purpose, not an inferred reputation.","source_urls":["https://outrightnam.com/","https://outrightnam.com/contact-us/","https://rightsinexile.org/sexual-orientation-and-gender-identity-country-list/namibia-lgbtqi-resources/"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Positive Vibes Trust Namibia","patch":{"booking_lead_time":"Begin with the Namibia office by email or telephone. Much of the work is programme-, partner- or movement-based rather than immediate individual booking.","best_time":"Weekday office hours, with a concise description of whether the request concerns queer rights, SRHR, HIV, community organising, training or partnership.","client_mix":"LGBTQ+ communities, sex workers, people living with HIV, women-led groups, adolescent girls and young women, and regional civil-society partners.","preparation":"Do not arrive expecting a general clinic. Ask which service is active, who qualifies, whether referral is required and whether the conversation can be confidential or remote.","provider_inclusivity":"Positive Vibes is a Namibian-registered queer-rights organisation whose published work explicitly addresses marginalisation, health and structural change across several key populations.","source_urls":["https://www.positivevibes.org/","https://www.positivevibes.org/contacts/","https://africa.ippf.org/about-us/member-associations/positive-vibes-trust"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Sister Namibia","patch":{"booking_lead_time":"Email before visiting. Editorial, campaign, referral and event requests do not use one public appointment system.","best_time":"Weekday contact works best; say whether you need media information, a counselling referral, feminist or queer resources, or details of a current public programme.","client_mix":"Women in their diversity, queer and gender-nonconforming people, writers, activists, artists, researchers and people looking for trusted support routes.","preparation":"For mental-health or violence support, use the current provider directory and confirm the receiving service directly. Sister Namibia is a valuable navigator, not an emergency clinic.","provider_inclusivity":"Its queer-feminist publishing, LGBTQIA+ legal-literacy work, Pride collaboration and public-art programming provide direct evidence of an intersectional approach.","source_urls":["https://sisternamibia.org/","https://sisternamibia.org/contact/","https://sisternamibia.org/resources-and-services/","https://sisternamibia.org/2024/11/the-namibian-house-building-inclusive-spaces-for-lgbtqia-persons/"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Legal Assistance Centre Namibia","patch":{"booking_lead_time":"Basic advice is available in published weekday windows, but litigation is accepted only when the matter has wider public-interest impact. Call first if travel, privacy or urgency matters.","best_time":"Morning advice hours offer the longest window. Bring an LGBTQI+ family, immigration, violence or discrimination question in a short timeline so a paralegal can triage it clearly.","client_mix":"Namibians from all backgrounds, including LGBTQI+ people facing rights questions, people unable to afford private advice and organisations working on law reform.","preparation":"Bring copies, not irreplaceable originals, of relevant notices, IDs, dates and messages. Ask what can be advised for free and whether a private practitioner or government legal aid is the correct next route.","provider_inclusivity":"The centre publishes plain-language LGBTQI+ legal guidance and has documented family, immigration, decriminalisation and discrimination issues. Its mandate is public-interest law, which is a scope limit rather than an inclusion gap.","source_urls":["https://www.lac.org.na/index.php/about-us/","https://www.lac.org.na/index.php/contact/","https://www.lac.org.na/index.php/projects/gender-research-advocacy-grap/lgbti/"],"updated_at":"2026-08-15T00:00:00Z"}},
 {"name":"Equal Namibia","patch":{"booking_lead_time":"Use the live social account or email and allow for movement-led response times. Campaign organising and Pride coordination are not the same as a staffed support desk.","best_time":"Contact ahead of Pride programmes, safe-space questions or civic campaigns. For immediate counselling, health or legal needs, use Out-Right Namibia or the Legal Assistance Centre directly.","client_mix":"Young LGBTQI+ Namibians, grassroots organisers, allies, civil-society partners, queer-owned businesses and Pride collaborators.","preparation":"Be specific about the city, the request and whether you need organising information, a verified venue signal or a referral. Do not publish private meeting details without consent.","provider_inclusivity":"The movement is queer-led, intersectional and responsible for concrete local infrastructure including Namibia Pride Week coordination and the Verified Safe-Space network.","source_urls":["https://www.civic264.org.na/social-movements/namibia-equal-rights-movement-equal-namibia","https://www.instagram.com/equalnamibia/","https://www.namibian.com.na/piccolo-declared-lgbtqi-safe-space/","https://www.lac.org.na/projects/grap/Pdf/LGBT%20Paralegal%20Handbook%20%282025%29.pdf"],"updated_at":"2026-08-15T00:00:00Z"}}
]
$windhoek_service_intel$) r(name text,patch jsonb)
)
update public.services s set service_intel=coalesce(s.service_intel,'{}'::jsonb)||r.patch,updated_at=timezone('utc',now()) from researched r
where lower(trim(s.city))='windhoek' and lower(trim(s.name))=lower(trim(r.name));

commit;

select 'places_with_complete_intel' check_name,count(*) result from public.places where lower(trim(city))='windhoek' and coalesce(venue_intel->>'queue_wait','')<>'' and coalesce(venue_intel->>'best_nights','')<>'' and coalesce(venue_intel->>'crowd_mix','')<>'' and coalesce(venue_intel->>'dress_code','')<>'' and coalesce(venue_intel->>'staff_inclusivity','')<>''
union all select 'events_with_complete_intel',count(*) from public.events where lower(trim(city))='windhoek' and coalesce(event_intel->>'entry_wait','')<>'' and coalesce(event_intel->>'host_inclusivity','')<>''
union all select 'services_with_complete_intel',count(*) from public.services where lower(trim(city))='windhoek' and coalesce(service_intel->>'booking_lead_time','')<>'' and coalesce(service_intel->>'provider_inclusivity','')<>''
order by check_name;
