-- Queer Atlas: Kathmandu, Nepal city package. Verified 2026-09-14; idempotent.
begin;

with s(name,type,description,vibe,hours,link,location,lat,lng,intel) as (values
('PINK Tiffany','bar','Nepal''s first openly LGBTQI+-friendly restaurant and bar is both a landmark and a real night out. Founded by trans activist Meghna Lama, PINK Tiffany moves from food and conversation into music, live performance and close-quarters dancing without losing the feeling that half the room already knows each other.','trans-founded queer café that turns into Thamel''s intimate rainbow living room','Restaurant and evening bar hours vary; current listings show regular operation, with the liveliest atmosphere after 21:00. Confirm the same-day schedule.','https://www.facebook.com/pinktiffanynepal/','P886+F24, Chaksibari Marg, Thamel, Kathmandu 44600, Nepal',27.7162,85.3118,'{"queue_wait":"The room is intimate rather than gate-kept; weekend performances can fill tables and compress the dance area after 21:30. Arrive earlier for dinner if sitting matters.","best_nights":"A current live-music or drag announcement gives the fullest experience. Earlier hours favour food and conversation; Friday and Saturday usually carry more late energy.","crowd_mix":"Trans and queer Nepali regulars, gay men, activists, local friends and curious international travellers share a close social room.","dress_code":"Relaxed Thamel nightlife clothes and expressive looks both fit. Ask before photographing performers or guests, especially local people.","staff_inclusivity":"Founder Meghna Lama opened PINK Tiffany after experiencing discrimination elsewhere, and the venue publicly identifies as LGBTQI+-friendly. That trans-led history is direct inclusion evidence; no detailed accessibility policy is published.","source_urls":["https://kathmandupost.com/valley/2019/02/28/welcome-to-pink-tiffany-kathmandus-first-openly-lgbtiq-friendly-restaurant-and-bar","https://www.gayout.com/asia-aus/nepal/kathmandu/bars","https://wanderlog.com/place/details/10399309/pink-tiffany"],"research_status":"editorial_review_consensus","updated_at":"2026-08-29T00:00:00Z"}'::jsonb),
('Fire Club','club','A mainstream Kathmandu club with one night that changes the room completely: Friday''s long-running gay party. Come after PINK Tiffany for the scale-up—commercial pop, a packed floor and the rare Kathmandu moment when the local queer scene occupies a full-size nightclub rather than a discreet corner.','big Thamel dance floor whose Friday party pulls the city''s loudest queer crowd','Evening to late night; Friday is the recurring queer-focused night. Verify the current programme before arrival.','https://fireclub.com.np/','Chaksibari Marg, Thamel, Kathmandu 44600, Nepal',27.716,85.3116,'{"queue_wait":"Friday concentrates the queer crowd and can produce the week''s longest door check after 23:00. It is a full-scale mainstream club, so carry identification and expect normal security.","best_nights":"Friday is the recurring gay night and the only reason for the queer classification. On other nights, expect Fire Club''s regular mixed Thamel programme.","crowd_mix":"Friday draws gay and bisexual Nepali men, broader queer friend groups, local clubbers and international visitors; other nights are mainstream and mixed.","dress_code":"Standard clubwear works. Bring photo identification, avoid beachwear and check the current event post for any theme or door condition.","staff_inclusivity":"The club has hosted a long-running Friday gay party, which supports event-specific inclusion. It is not a dedicated queer venue and publishes no LGBTQ+ safeguarding policy, so assess the current promoter and night separately.","source_urls":["https://fireclub.com.np/contact-us","https://www.gayout.com/asia-aus/nepal/kathmandu/bars","https://nomadicboys.com/kathmandu-gay-guide/"],"research_status":"editorial_review_consensus","updated_at":"2026-08-29T00:00:00Z"}'::jsonb),
('Aloft Kathmandu Thamel','hotel','A modern five-star base above Chhaya Devi Complex, with a rooftop pool, 24-hour fitness room and W XYZ social bar. The location earns its place: Kathmandu''s two most dependable queer nightlife stops sit within the same Thamel grid, so the last journey home can be short and staffed.','rooftop-pool polish planted directly inside Thamel''s beautiful chaos','Hotel open daily; check-in 15:00 and check-out 12:00; minimum check-in age 18.','https://www.marriott.com/en-us/hotels/ktmal-aloft-kathmandu-thamel/overview/','Chhaya Devi Complex, Amrit Marg, Thamel, Kathmandu 44600, Nepal',27.7167,85.3128,'{"queue_wait":"Official check-in begins at 15:00 and checkout is noon. Mobile Key and a staffed front desk can streamline arrival; reserve airport transport because valley traffic changes quickly.","best_nights":"Its Thamel position is strongest on Friday, when both PINK Tiffany and Fire Club are active nearby. The rooftop and W XYZ Bar work as an easy pre-night meeting point.","crowd_mix":"International leisure guests, younger business travellers, mall visitors and social-bar regulars use a polished, highly central property.","dress_code":"Contemporary casual fits the lobby and W XYZ Bar; pool, spa and fitness areas follow standard hotel attire.","staff_inclusivity":"Marriott publishes staffed reception, accessible parking, elevators and service-animal access for this property. No Kathmandu-specific LGBTQ+ training statement was found; confirm names, room setup and visitor access directly.","source_urls":["https://www.marriott.com/en-us/hotels/ktmal-aloft-kathmandu-thamel/overview/"],"research_status":"editorial_review_consensus","updated_at":"2026-08-29T00:00:00Z"}'::jsonb),
('Kathmandu Marriott Hotel','hotel','Six restaurants, a full spa and an outdoor pool make this the decompression option after Kathmandu''s dust, traffic and late nights. Naxal places it outside the tight Thamel circuit but closer to a polished international rhythm, useful for couples who want a staffed retreat and do not mind booking a ride to the bars.','full-service Naxal retreat with a pool, spa and breathing room beyond Thamel','Hotel open daily; check-in 15:00 and check-out 12:00; minimum check-in age 18.','https://www.marriott.com/en-us/hotels/ktmmc-kathmandu-marriott-hotel/overview/','Manakamana Marg, Naxal, Kathmandu 44600, Nepal',27.7145,85.3256,'{"queue_wait":"Check-in starts at 15:00 and checkout is noon. Conferences and group arrivals can load the lobby; direct booking helps settle room, companion and airport-transfer details in advance.","best_nights":"Choose the Marriott for pool or spa recovery and a contained dinner after sightseeing. A direct ride is needed for Thamel''s queer nightlife rather than relying on a casual walk.","crowd_mix":"Business and diplomatic guests, tour groups, upscale leisure travellers and local diners move through a large full-service hotel.","dress_code":"Polished casual fits public areas and restaurants; the spa, pool and 24-hour fitness centre have conventional attire.","staff_inclusivity":"The property documents accessible routes to its pool, spa, gym and public areas. Marriott provides a corporate inclusion baseline, but no property-specific queer protocol is public; confirm privacy and name handling before arrival.","source_urls":["https://www.marriott.com/en-us/hotels/ktmmc-kathmandu-marriott-hotel/overview/"],"research_status":"editorial_review_consensus","updated_at":"2026-08-29T00:00:00Z"}'::jsonb),
('Hyatt Centric Soalteemode Kathmandu','hotel','A 153-room lifestyle hotel that gives Kathmandu''s brick, carved wood and courtyard language a contemporary frame. Its Tahachal setting works for Durbar Square days and poolside recovery; nightlife needs a planned ride, but the trade is space, mountain views and a quieter landing than central Thamel.','Newari-inspired resort calm with mountain views on the heritage-city side','Hotel open daily; check-in and checkout times should be confirmed on the current reservation.','https://www.hyatt.com/hyatt-centric/en-US/ktmzk-hyatt-centric-soalteemode-kathmandu/','PO Box 8801, Tahachal, Kathmandu 44600, Nepal',27.7009,85.2927,'{"queue_wait":"The quieter Tahachal arrival avoids Thamel''s densest pedestrian traffic, though group check-ins can still collect at reception. Confirm the property''s current check-in time with the reservation.","best_nights":"Use the hotel for heritage-district days, mountain-view mornings and pool recovery. Nightlife requires a deliberate ride to Chaksibari Marg.","crowd_mix":"International leisure travellers, heritage-focused guests, tour groups and local restaurant visitors favour the resort-style setting.","dress_code":"Smart casual suits the contemporary public rooms; standard swim and fitness attire applies in leisure facilities.","staff_inclusivity":"Hyatt publishes detailed accessible routes, tactile signage, mobility-room dimensions and service-animal access here. No local LGBTQ+ training claim is public, so ask reception about couple, privacy and visitor needs.","source_urls":["https://www.hyatt.com/hyatt-centric/en-US/ktmzk-hyatt-centric-soalteemode-kathmandu/","https://www.hyatt.com/hyatt-centric/en-US/ktmzk-hyatt-centric-soalteemode-kathmandu/hotel-info"],"research_status":"editorial_review_consensus","updated_at":"2026-08-29T00:00:00Z"}'::jsonb)
), upd as (
 update public.places p set type=s.type,description=s.description,vibe=s.vibe,hours=s.hours,link=s.link,location=s.location,lat=s.lat,lng=s.lng,venue_intel=s.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from s where lower(trim(p.city))='kathmandu' and lower(trim(p.name))=lower(s.name) returning p.id)
insert into public.places(name,city,type,description,vibe,hours,link,location,lat,lng,venue_intel,seo_indexable,seo_quality_status)
select name,'kathmandu',type,description,vibe,hours,link,location,lat,lng,intel,true,'approved' from s where not exists(select 1 from public.places p where lower(trim(p.city))='kathmandu' and lower(trim(p.name))=lower(s.name));

with s(name,type,provider_name,contact,booking_link,description,hours,link,location,vibe,tags,source) as (values
 ('Blue Diamond Society','other','Blue Diamond Society Nepal','info@bds.org.np · +977 1 4526652','https://bds.org.np/','Nepal’s pioneering LGBTQI+ organisation combines legal advocacy, community support, HIV prevention and referrals. Contact the Dhumbarahi office before visiting.','Office and programme-led; arrange contact before arrival.','https://bds.org.np/','Dhumbarahi, Kathmandu, Nepal','national LGBTQI+ rights, health and community anchor',array['service','social','cultural']::text[],'Blue Diamond Society and Social Welfare Council listings'),
 ('Mitini Nepal','other','Mitini Nepal','mitini.nepal@gmail.com · +977 1 4957590 · +977 9843948535','https://mitininepal.org.np/mitini-nepal-kathmandu/','A pioneering lesbian, bisexual and trans-led organisation working on rights, dignity, economic opportunity, research and support for women with LBT identities.','Office and programme-led; contact before visiting.','https://mitininepal.org.np/mitini-nepal-kathmandu/','Bhatbhateni, Kathmandu, Nepal','LBT-led rights, support and movement-building space',array['service','social','cultural']::text[],'Mitini Nepal official contact page'),
 ('Queer Youth Group','other','Queer Youth Group Nepal','communications.qyg@gmail.com · +977 9851350665','https://www.queeryouthgroup.org.np/en','A youth-led organisation producing legal resources, research, movement work and Nepal Pride Parade with an intentionally broad PoMSOGIESC framework.','Programme-led; contact before visiting.','https://www.queeryouthgroup.org.np/en','Yala Dhwakha, Patandhoka, Lalitpur-20, Nepal','youth-led queer advocacy, knowledge and Pride organising',array['service','social','cultural']::text[],'Queer Youth Group official website')
), upd as (update public.services x set type=s.type,provider_name=s.provider_name,contact=s.contact,booking_link=s.booking_link,description=s.description,hours=s.hours,link=s.link,location=s.location,vibe=s.vibe,vibe_tags=s.tags,source=s.source,"lastChecked"='2026-09-14'::date,verified=true from s where lower(trim(x.city))='kathmandu' and lower(trim(x.name))=lower(trim(s.name)) returning x.id)
insert into public.services(name,city,type,provider_name,contact,booking_link,description,hours,link,image_urls,location,lat,lng,price_tier,vibe,vibe_tags,source,"lastChecked",verified)
select name,'kathmandu',type,provider_name,contact,booking_link,description,hours,link,array[]::text[],location,27.7172,85.3240,'$',vibe,tags,source,'2026-09-14'::date,true from s where not exists(select 1 from public.services x where lower(trim(x.city))='kathmandu' and lower(trim(x.name))=lower(trim(s.name)));

insert into public.qa_country_rights_profiles(country,legal_level,rights_level,safety_level,same_sex_relations_status,union_status,legal_gender_recognition_status,anti_discrimination_status,what_this_means,confidence,source_legal_url,source_rights_url,source_safety_url,source_checked_at,needs_manual_review) values
('Nepal','good','good','mixed','legal','marriage','available','partial_coverage','Same-sex relations are legal, constitutional equality protection and gender recognition are established, and the Supreme Court ordered equal marriage rights in June 2026. Implementation remains uneven, with gaps in employment, housing and hate-crime law and documented discrimination in everyday services.','high','https://www.equaldex.com/region/nepal','https://www.hrw.org/news/2024/07/31/nepal-supreme-court-recognizes-trans-woman-woman','https://mitininepal.org.np/mitini-nepal-kathmandu/','2026-09-14'::date,false)
on conflict(country) do update set legal_level=excluded.legal_level,rights_level=excluded.rights_level,safety_level=excluded.safety_level,same_sex_relations_status=excluded.same_sex_relations_status,union_status=excluded.union_status,legal_gender_recognition_status=excluded.legal_gender_recognition_status,anti_discrimination_status=excluded.anti_discrimination_status,what_this_means=excluded.what_this_means,confidence=excluded.confidence,source_legal_url=excluded.source_legal_url,source_rights_url=excluded.source_rights_url,source_safety_url=excluded.source_safety_url,source_checked_at=excluded.source_checked_at,needs_manual_review=excluded.needs_manual_review;

insert into public.qa_qari_profiles(destination_key,scope_type,country,city_key,legal_risk,social_risk,digital_risk,risk_floor,confidence,summary,methodology_version,reviewed_by,reviewed_at,is_published) values
('country:nepal','country','Nepal',null,26,32,20,0,'high','Nepal combines legal same-sex relations, constitutional protection, gender recognition and a 2026 marriage-equality order with unusually positive opinion data. Sector-level protection and consistent implementation still lag behind the constitutional framework.','1.0','Queer Atlas editorial review','2026-09-14'::date,true)
on conflict(destination_key) do update set legal_risk=excluded.legal_risk,social_risk=excluded.social_risk,digital_risk=excluded.digital_risk,risk_floor=excluded.risk_floor,confidence=excluded.confidence,summary=excluded.summary,methodology_version=excluded.methodology_version,reviewed_by=excluded.reviewed_by,reviewed_at=excluded.reviewed_at,is_published=excluded.is_published;

delete from public.qa_qari_sources where destination_key='country:nepal';
insert into public.qa_qari_sources(destination_key,axis,source_type,label,url,supports_claim,published_at,checked_at) values
('country:nepal','legal','legal_database','Equaldex · Nepal','https://www.equaldex.com/region/nepal','Documents legal relations, the 2026 marriage-equality order, gender recognition and constitutional protection.',null,'2026-09-14'::date),
('country:nepal','social','legal_database','Equaldex · Nepal public opinion','https://www.equaldex.com/region/nepal','Reports 82% describing their area as a good place for gay and lesbian people in 2024.',null,'2026-09-14'::date),
('country:nepal','digital','ngo_report','Human Rights Watch · Legal gender recognition','https://www.hrw.org/news/2024/07/31/nepal-supreme-court-recognizes-trans-woman-woman','Documents a rights-affirming Supreme Court ruling and persistent administrative barriers.','2024-07-31'::date,'2026-09-14'::date),
('country:nepal','social','ngo_report','Mitini Nepal · LBT community support','https://mitininepal.org.np/mitini-nepal-kathmandu/','Documents active LBT-led rights and support infrastructure in Nepal.',null,'2026-09-14'::date);

commit;

