-- Queer Atlas: verified queer and queer-friendly electronic events, Batch 6.
-- Countries: Estonia, Latvia, Lithuania and Hungary. Researched 2026-08-29.
-- Unpublished venue or timing details remain explicit instead of being inferred.
-- Source data contains no vibe_tags; UPDATE and INSERT force ARRAY[]::text[].

begin;

alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists ticket_url text;

with src as (
  select * from jsonb_to_recordset($qa_baltic_hungary_batch6_events$
[
{"name":"Is This What You Wanted? – Tallinn Fringe 2026","aliases":["IS THIS WHAT YOU WANTED?","happeningfish Tallinn Fringe 2026"],"city":"tallinn","date":"2026-09-04","start_date":"2026-09-04","end_date":"2026-09-05","description":"Trans comedian happeningfish performs two English-language Tallinn Fringe shows combining filthy stand-up, emotional labour, queer politics and laughter as activism.","link":"https://fringe.ee/tickets/is-this-what-you-wanted-190048/","ticket_url":"https://fringe.ee/tickets/is-this-what-you-wanted-190048/","location":"Heldeke!, Telliskivi 62, 10412 Tallinn, Estonia","lat":59.4394,"lng":24.7286,"vibe":"smart trans stand-up balancing vulnerable storytelling, queer politics and gloriously dirty jokes","intel":{"entry_wait":"Two one-hour performances are listed for 4 and 5 September; choose the correct date when booking and arrive before the 21:00 start.","best_arrival":"Reach Heldeke! around 20:30 for ticket check and seating because the intimate performance room has limited capacity.","crowd_mix":"Queer and trans audiences, English-speaking locals, Fringe visitors, comedy followers and international cultural travellers attend.","dress_code":"No appearance requirement applies; comfortable theatre or bar clothing is appropriate for the compact underground room.","host_inclusivity":"The trans performer's work explicitly examines queer politics, transgender experience, activism, allyship and survival through comedy.","source_urls":["https://fringe.ee/tickets/is-this-what-you-wanted-190048/"],"research_status":"official_festival_dates_times_venue_age_language_and_queer_content_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Queer-Only Cuddle Party Tallinn – September 2026","aliases":["4th Queer Cuddle Party Tallinn","kväär kaisupidu 13 September 2026"],"city":"tallinn","date":"2026-09-13","start_date":"2026-09-13","end_date":"2026-09-13","description":"A facilitated LGBTQIA+-only afternoon creates a non-sexual space for platonic touch, boundary practice, grounding and low-pressure queer and trans connection.","link":"https://www.transformationembodied.com/et/uritused/queer-only-cuddle-party-4/","ticket_url":"https://fienta.com/index.php/s/queer-cuddle-party","location":"Kultus Club, Kopli, Tallinn, Estonia; exact address emailed to ticket holders","lat":59.4520,"lng":24.7010,"vibe":"gentle consent-led queer gathering designed for clear boundaries and nervous-system ease","intel":{"entry_wait":"Capacity is deliberately limited and each ticket holds one place; book in advance and meet the published 15:45 gathering time.","best_arrival":"Arrive at the privately supplied address by 15:45 so the group can begin consent guidance together at 16:00.","crowd_mix":"Queer and trans adults, neurodivergent participants, people exploring identity and guests seeking non-sexual connection are centred.","dress_code":"Wear comfortable layered clothing that can adapt as the room warms; a soothing object or plush toy is welcome.","host_inclusivity":"The event is restricted to LGBTQIA+ participants and uses explicit consent, optional participation and clear boundary-setting practices.","source_urls":["https://www.transformationembodied.com/et/uritused/queer-only-cuddle-party-4/","https://fienta.com/index.php/s/queer-cuddle-party"],"research_status":"organiser_and_ticketing_date_hours_audience_consent_access_and_private_address_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Triangle – Queer Tallinn History Walk","aliases":["Guided Tour Triangle Tallinn Fringe 2026","Triangle LGBT History Walk Tallinn"],"city":"tallinn","date":"2026-09-13","start_date":"2026-09-13","end_date":"2026-09-13","description":"Airi Triisberg leads an English-language walk through the late-Soviet triangle where Tallinn's gay, punk, bohemian and dissident histories crossed.","link":"https://fringe.ee/piletid/guided-tour-triangle-in-english-194594/","ticket_url":"https://fringe.ee/piletid/guided-tour-triangle-in-english-194594/","location":"Meeting point: Vabaduse väljak 10, 10146 Tallinn, Estonia","lat":59.4339,"lng":24.7440,"vibe":"street-level queer memory walk connecting nightlife, dissent and Tallinn's hidden subcultures","intel":{"entry_wait":"Advance Fringe booking is recommended; the two-hour English tour begins at 17:00 and proceeds even in rainy weather.","best_arrival":"Meet at Vabaduse väljak 10 around 16:45 so the group can depart together and hear the route introduction.","crowd_mix":"LGBTQ+ residents, cultural travellers, historians, punk and literary audiences and English-speaking Fringe visitors join.","dress_code":"No dress code applies; use weatherproof layers and comfortable shoes for stairs, slopes and two hours outdoors.","host_inclusivity":"The tour narrates gay and LGBT+ history alongside punk, literary and dissident life rather than treating queer memory as an afterthought.","source_urls":["https://fringe.ee/piletid/guided-tour-triangle-in-english-194594/"],"research_status":"official_festival_date_time_language_meeting_point_route_and_lgbt_history_verified","updated_at":"2026-08-29T00:00:00Z"}},

{"name":"Amber Muse x Elli Acula","aliases":["Amber Muse Elli Acula Riga 2026"],"city":"riga","date":"2026-09-11","start_date":"2026-09-11","end_date":"2026-09-12","description":"Amber Muse brings Elli Acula's raw Berlin techno to Laska V21 with Riga duo Queer On Acid and an explicit anti-homophobia, anti-sexism and anti-racism policy.","link":"https://ra.co/events/2450684","ticket_url":"https://ra.co/events/2450684","location":"Laska V21, Vagonu iela 21, Riga LV-1009, Latvia","lat":56.9461,"lng":24.1430,"vibe":"queer-connected Baltic techno night pairing Berlin intensity with a clear conduct line","intel":{"entry_wait":"Presale tiers range from ten to twenty-five euros; bring valid 18+ identification and expect face control at the venue.","best_arrival":"Arrive close to the 22:00 opening for smoother entry and the full progression before the headline peak.","crowd_mix":"Riga techno regulars, Queer On Acid followers, LGBTQ+ dancers, Berlin-scene fans and respectful electronic visitors attend.","dress_code":"No mandatory look is published; practical expressive clubwear and reliable dancing shoes fit the overnight programme.","host_inclusivity":"The organiser explicitly prohibits homophobia, sexism and racism, while queer Riga artists are represented in the lineup.","source_urls":["https://ra.co/events/2450684","https://ra.co/dj/queeronacid"],"research_status":"organiser_date_hours_venue_age_ticketing_lineup_and_anti_discrimination_policy_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Bisexuality Visibility Day Riga 2026","aliases":["Biseksualitātes redzamības diena 2026","Bi Visibility Day Riga 2026"],"city":"riga","date":"2026-09-23","start_date":"2026-09-23","end_date":"2026-09-23","description":"Latvian B+ organisation NEONS marks Bisexuality Visibility Day with community-led programming focused on bisexual, pansexual and multisexual visibility and wellbeing.","link":"https://neons.lv/events/list/?tribe-bar-date=2026-02-26","ticket_url":"https://neons.lv/events/list/?tribe-bar-date=2026-02-26","location":"Final venue and programme to be announced by NEONS, Riga, Latvia","lat":56.9496,"lng":24.1052,"vibe":"B+-centred visibility day creating space for recognition, learning and community connection","intel":{"entry_wait":"The official calendar confirms the date but not the final format or venue; check NEONS channels before attending and register if requested.","best_arrival":"Use the organiser's final programme rather than the calendar placeholder hours, which do not yet describe the actual session.","crowd_mix":"Bisexual, pansexual, omnisexual and other B+ people are centred alongside wider LGBT+ community members and supportive guests.","dress_code":"No requirement has been announced; comfortable community-event clothing and visible bi or pan colours are natural choices.","host_inclusivity":"NEONS specifically advocates for the visibility, wellbeing and inclusion of B+ people within Latvian society and LGBT+ life.","source_urls":["https://neons.lv/","https://neons.lv/events/list/?tribe-bar-date=2026-02-26"],"research_status":"official_organisation_and_date_verified_final_format_time_and_venue_pending","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"NEONS October Community Meeting 2026","aliases":["NEONA Oktobra kopienas ikmēneša tikšanās"],"city":"riga","date":"2026-10-17","start_date":"2026-10-17","end_date":"2026-10-17","description":"NEONS holds its October monthly meeting for B+ and wider LGBT+ community connection, informal conversation and mutual visibility in Riga.","link":"https://neons.lv/events/category/neona-pasakumi/","ticket_url":"https://neons.lv/events/category/neona-pasakumi/","location":"Final meeting location to be announced by NEONS, Riga, Latvia","lat":56.9496,"lng":24.1052,"vibe":"small community-led B+ meetup offering a lower-pressure alternative to nightlife","intel":{"entry_wait":"The organiser confirms the day while detailed hours, location and any registration remain pending; recheck the listing before travel.","best_arrival":"Follow the final NEONS post because the all-day calendar display is a placeholder rather than a verified meeting window.","crowd_mix":"B+ people, LGBT+ community members, regular NEONS participants, newcomers and supportive local peers are welcomed.","dress_code":"No dress expectation is announced; relaxed everyday clothing suits the informal community format.","host_inclusivity":"NEONS welcomes everyone who wants to advance B+ and wider LGBT+ visibility, wellbeing and inclusion in Latvia.","source_urls":["https://neons.lv/","https://neons.lv/events/category/neona-pasakumi/"],"research_status":"official_organisation_event_title_and_date_verified_time_and_location_pending","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"NEONS November Community Meeting 2026","aliases":["NEONA Novembra kopienas ikmēneša tikšanās"],"city":"riga","date":"2026-11-21","start_date":"2026-11-21","end_date":"2026-11-21","description":"NEONS continues its monthly B+ and LGBT+ community series in November with an informal Riga gathering built around belonging and peer connection.","link":"https://neons.lv/events/category/neona-pasakumi/","ticket_url":"https://neons.lv/events/category/neona-pasakumi/","location":"Final meeting location to be announced by NEONS, Riga, Latvia","lat":56.9496,"lng":24.1052,"vibe":"welcoming late-autumn B+ community meetup focused on conversation and belonging","intel":{"entry_wait":"The calendar confirms 21 November but final participation details have not been published; check NEONS for registration and venue updates.","best_arrival":"Ignore the generic calendar time until NEONS releases the actual meeting window and arrival instructions.","crowd_mix":"Bisexual, pansexual and other multisexual people meet wider LGBT+ peers, friends and community-minded newcomers.","dress_code":"No code applies; comfortable casual clothing fits a peer-led indoor community gathering.","host_inclusivity":"The host's stated mission centres B+ visibility and wellbeing while welcoming people who support broader LGBT+ inclusion.","source_urls":["https://neons.lv/","https://neons.lv/events/category/neona-pasakumi/"],"research_status":"official_organisation_event_title_and_date_verified_time_and_location_pending","updated_at":"2026-08-29T00:00:00Z"}},

{"name":"Kreivės – Vilnius Queer Festival 2026","aliases":["13th Vilnius Queer Festival Kreives","Kreivės 13"],"city":"vilnius","date":"2026-09-04","start_date":"2026-09-04","end_date":"2026-09-09","description":"Kreivės returns for six Vilnius days of queer film, performance, readings, exhibitions, archival practice, conversation and community meeting.","link":"https://festivaliskreives.lt/en/programme/","ticket_url":"https://festivaliskreives.lt/en/programme/","location":"SODAS 2123, Meno avilys and multiple cultural venues, Vilnius, Lithuania","lat":54.6872,"lng":25.2797,"vibe":"Lithuania's annual queer culture forum connecting cinema, archives, art and social change","intel":{"entry_wait":"Many programme items are free, while tours and the symposium require registration; reserve limited sessions from the official programme.","best_arrival":"Build each day from the venue-specific schedule and allow transfers between SODAS 2123, Meno avilys and partner spaces.","crowd_mix":"Lithuanian LGBTQ+ communities, filmmakers, artists, archivists, activists, students and international cultural visitors attend.","dress_code":"No festival-wide code applies; comfortable cultural-event clothing works, with expressive styling welcome at performances and parties.","host_inclusivity":"Kreivės is explicitly a queer cultural and social initiative creating space for meeting, self-expression and change since 2014.","source_urls":["https://festivaliskreives.lt/festivalis/","https://festivaliskreives.lt/en/programme/"],"research_status":"official_edition_dates_cities_programme_venues_and_queer_mission_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Unseen, Unheard – Queer Vilnius Installation","aliases":["Nematyta negirdėta 2026","Unseen Unheard Kreives 2026"],"city":"vilnius","date":"2026-09-05","start_date":"2026-09-05","end_date":"2026-09-09","description":"Kristijonas Dirsė's spatial audiovisual installation maps personal testimony onto scanned Vilnius locations to explore queer visibility, memory and urban erasure.","link":"https://festivaliskreives.lt/en/renginys/unseen-unheard/","ticket_url":"https://festivaliskreives.lt/en/renginys/unseen-unheard/","location":"Meno avilys, A. Goštauto g. 2, Vilnius, Lithuania","lat":54.6898,"lng":25.2705,"vibe":"immersive queer memory work turning city locations and testimony into spatial sound","intel":{"entry_wait":"The launch begins at 17:30 on 5 September; subsequent viewing runs daily from 16:00–19:00 through 9 September.","best_arrival":"Attend the launch for context from the creators or arrive early within later three-hour windows to experience the work without rushing.","crowd_mix":"Queer Vilnius residents, installation-art audiences, researchers, activists, students and festival visitors share the work.","dress_code":"No dress requirement applies; quiet, comfortable gallery clothing suits an attentive audiovisual experience.","host_inclusivity":"The project was developed with LGBTQ+ researchers, activists and artists and directly centres nine queer community testimonies.","source_urls":["https://festivaliskreives.lt/en/renginys/unseen-unheard/"],"research_status":"official_festival_dates_daily_hours_venue_method_and_community_collaboration_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Circus Techno: Magic Vilnius","aliases":["Circus Techno event Vilnius 2026","Circus Techno Magic at Briusly"],"city":"vilnius","date":"2026-09-18","start_date":"2026-09-18","end_date":"2026-09-19","description":"Circus Techno transforms three rooms into a 21+ house and techno spectacle with performances, workshops, self-expression and an on-site consent team.","link":"https://ra.co/events/2512497","ticket_url":"https://ra.co/events/2512497","location":"Briusly, former Opium Club, Islandijos g. 4, Vilnius 01401, Lithuania","lat":54.6864,"lng":25.2793,"vibe":"extravagant consent-aware techno circus combining spectacle, play and self-expression","intel":{"entry_wait":"Tickets are limited and non-refundable; bring valid 21+ identification and expect the venue to enforce its published entry conditions.","best_arrival":"Reach the venue near the 23:00 opening to explore all three spaces and hear the consent framework before peak hours.","crowd_mix":"Queer-friendly club visitors, couples, circus performers, techno and house dancers and expressive Vilnius night crowds attend.","dress_code":"Circus, extravagance and self-expression are recommended; an intentional theatrical look helps guests become part of the show.","host_inclusivity":"The organiser calls the night a safe space and provides a consent team plus discreet security throughout the event.","source_urls":["https://ra.co/events/2512497"],"research_status":"organiser_date_hours_venue_age_capacity_dress_and_consent_team_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"DRAMATICA XXIII – Let's Drag New Season","aliases":["Dramatica 23 Vilnius","Let's Drag the New Season 2026"],"city":"vilnius","date":"2026-09-25","start_date":"2026-09-25","end_date":"2026-09-26","description":"Lithuania's international drag series opens a new season at Soho with Vanessa Van Cartier, Sederginne and a one-night European cast performing in English.","link":"https://www.sohoclub.lt/dramatica/","ticket_url":"https://www.sohoclub.lt/dramatica/","location":"Soho Club, Švitrigailos g. 7, Vilnius 03110, Lithuania","lat":54.6751,"lng":25.2681,"vibe":"one-night international drag fantasy combining pageant polish, camp and queer club energy","intel":{"entry_wait":"Purchase the specific DRAMATICA chapter ticket in advance and arrive before the 19:30 show listing rather than only for the later club night.","best_arrival":"Reach Soho around 19:00 for entry and positioning because every chapter has a unique cast and limited audience.","crowd_mix":"Vilnius LGBTQ+ regulars, drag devotees, international visitors, English-speaking audiences and Soho club guests attend.","dress_code":"No mandatory look is stated; glamour, camp, pageant references and polished queer nightlife styling fit naturally.","host_inclusivity":"DRAMATICA is Lithuania's international drag series and Soho identifies itself as Vilnius's longstanding queer club and safe open space.","source_urls":["https://www.sohoclub.lt/dramatica/","https://www.sohoclub.lt/events/"],"research_status":"official_host_date_venue_cast_language_series_identity_and_queer_space_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Too Gay to Go Home – Soho Vilnius","aliases":["Too Gay to Go Home 12 September 2026"],"city":"vilnius","date":"2026-09-12","start_date":"2026-09-12","end_date":"2026-09-13","description":"Soho's September calendar makes staying out the point with a named queer Saturday running from 22:00–07:00 at Lithuania's longest-standing LGBTQ+ club.","link":"https://www.sohoclub.lt/events/","ticket_url":"https://www.sohoclub.lt/events/","location":"Soho Club, Švitrigailos g. 7, Vilnius 03110, Lithuania","lat":54.6751,"lng":25.2681,"vibe":"late queer pop-club Saturday built around release, familiarity and a dependable community floor","intel":{"entry_wait":"Check Soho's event post for the current cover or SMS promotion, carry adult identification and arrive before the deepest Saturday queue.","best_arrival":"Arrive between 22:00 and midnight for easier entry and the complete overnight build through the 07:00 close.","crowd_mix":"Vilnius LGBTQ+ locals, younger queer dancers, visiting gay travellers, friends and established Soho regulars share the floor.","dress_code":"No event-specific requirement is published; confident pop-club styling and comfortable dance shoes work well.","host_inclusivity":"Soho has welcomed Lithuania's LGBTQ+ community since 2007 and describes itself as a safe, open place to connect and be yourself.","source_urls":["https://www.sohoclub.lt/events/","https://vnb.lt/en/dainykla/soho-club/"],"research_status":"official_club_calendar_date_hours_venue_and_lgbtq_space_identity_verified","updated_at":"2026-08-29T00:00:00Z"}},

{"name":"House of Garçons – September 2026","aliases":["Garçons Budapest 5 September 2026","House of Garcons Akvarium September 2026"],"city":"budapest","date":"2026-09-05","start_date":"2026-09-05","end_date":"2026-09-06","description":"House of Garçons brings its major monthly gay party to Akvárium with house, pop remixes and a large central Budapest dance floor from 23:00–05:00.","link":"https://www.garconsbudapest.com/","ticket_url":"https://www.patroc.com/gay/budapest/d/garcons-party.html","location":"Akvárium Klub, Erzsébet tér 12, 1051 Budapest, Hungary","lat":47.4976,"lng":19.0537,"vibe":"large polished gay monthly mixing house drive, pop familiarity and central-city spectacle","intel":{"entry_wait":"Published admission ranges from 3000–4000 HUF; use the organiser link for current sales and bring valid adult identification.","best_arrival":"Reach Akvárium before midnight for smoother entry and cloakroom access ahead of the central late-night peak.","crowd_mix":"Gay men are centred alongside broader LGBTQ+ clubbers, local regulars, international visitors and house-pop dancers.","dress_code":"No mandatory code is published; polished fitted clubwear and expressive fashion suit the production and central venue.","host_inclusivity":"Garçons describes itself as East Central Europe's largest gay monthly party and programmes specifically for that community.","source_urls":["https://www.garconsbudapest.com/","https://www.patroc.com/gay/budapest/d/garcons-party.html"],"research_status":"official_party_identity_plus_current_exact_date_hours_venue_music_and_price_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Labrisz Autumn Picnic 2026","aliases":["Őszi Labrisz piknik 2026","Labrisz September Picnic Budapest"],"city":"budapest","date":"2026-09-06","start_date":"2026-09-06","end_date":"2026-09-06","description":"Labrisz welcomes LBTQ+ women to an informal autumn picnic on Margaret Island for conversation, games, friendship and lower-pressure community connection.","link":"https://labrisz.hu/aktualis-esemenyek/","ticket_url":"https://labrisz.hu/aktualis-esemenyek/","location":"Margaret Island meadow north of the former Holdudvar, Budapest, Hungary","lat":47.5240,"lng":19.0476,"vibe":"easy outdoor LBTQ+ gathering built for conversation, games and meeting new people","intel":{"entry_wait":"No ticket requirement is published; locate the group by its rainbow or Labrisz flag near the meadow from 15:00.","best_arrival":"Take bus 26 to Parkmozi and arrive shortly before 15:00 so you can find the group before the picnic spreads out.","crowd_mix":"Lesbian, bisexual, trans and queer women, Labrisz members, partners, friends and newcomers are the intended community.","dress_code":"No code applies; bring comfortable outdoor layers, a picnic blanket and anything you would like to eat, drink or play.","host_inclusivity":"Labrisz states that its programmes are open to LBTQ+ women and organises specifically to strengthen their visibility and community.","source_urls":["https://labrisz.hu/aktualis-esemenyek/"],"research_status":"official_organiser_date_time_coordinates_directions_activity_and_audience_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Hello – Queer Pop Party September 2026","aliases":["Hello Queer Pop Party 12 September 2026","Hello Party Toldi September 2026"],"city":"budapest","date":"2026-09-12","start_date":"2026-09-12","end_date":"2026-09-13","description":"HELLO fills Toldi with pop divas, colourful queer rebellion and DJ Gango for an 18+ Saturday party running from 23:00–05:00.","link":"https://ra.co/events/2516559","ticket_url":"https://ra.co/events/2516559","location":"Toldi Klub, Bajcsy-Zsilinszky út 36-38, 1054 Budapest, Hungary","lat":47.5041,"lng":19.0550,"vibe":"bright queer pop rush celebrating divas, colour, style and collective release","intel":{"entry_wait":"Carry valid 18+ identification and check the organiser's current ticket post; the venue reserves the right to refuse entry.","best_arrival":"Arrive near the 23:00 opening for a smoother door and time to settle before the pop floor reaches its late peak.","crowd_mix":"Budapest queer communities, pop lovers, style-focused clubbers, friends and international LGBTQ+ visitors attend.","dress_code":"No mandatory look is listed; colourful, pumped-up, diva-inspired or personally expressive styling matches the invitation.","host_inclusivity":"HELLO explicitly names itself a queer pop party and addresses queens, rebels, dreamers and style icons as its community.","source_urls":["https://ra.co/events/2516559"],"research_status":"organiser_date_hours_venue_age_music_and_explicit_queer_identity_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Pikk Dáma Game Night – September 2026","aliases":["Pikk Dáma játékest 20 September 2026","Labrisz Game Night September 2026"],"city":"budapest","date":"2026-09-20","start_date":"2026-09-20","end_date":"2026-09-20","description":"Labrisz's monthly card and board-game evening offers LBTQ+ women a free, donation-supported space to play, bring friends and meet new faces.","link":"https://labrisz.hu/aktualis-esemenyek/","ticket_url":"https://labrisz.hu/aktualis-esemenyek/","location":"Szabad Új Hely, Víg utca 30, 1084 Budapest, Hungary","lat":47.4922,"lng":19.0720,"vibe":"low-pressure LBTQ+ social night where games make new community connection easier","intel":{"entry_wait":"Entry is free and donations support future programmes; no advance ticket is stated, but check Labrisz for any capacity update.","best_arrival":"Reach Szabad Új Hely shortly before 17:00 to join game selection and introductions before tables become established.","crowd_mix":"Lesbian, bisexual, trans and queer women, partners, friends, regular players and first-time Labrisz visitors are welcomed.","dress_code":"No requirement applies; relaxed everyday clothing suits a three-hour seated social and game session.","host_inclusivity":"Labrisz explicitly opens its programmes to LBTQ+ women and uses recurring community formats to reduce isolation and strengthen belonging.","source_urls":["https://labrisz.hu/aktualis-esemenyek/"],"research_status":"official_organiser_date_hours_venue_price_activity_and_audience_verified","updated_at":"2026-08-29T00:00:00Z"}}
]
$qa_baltic_hungary_batch6_events$) e(
  name text, aliases jsonb, city text, date date, start_date date, end_date date,
  description text, link text, ticket_url text, location text,
  lat double precision, lng double precision, vibe text, intel jsonb
  )
), matched as (
  select s.*, existing.id as existing_id
  from src s
  left join lateral (
    select candidate.id
    from public.events candidate
    where lower(trim(candidate.city)) = lower(trim(s.city))
      and (
        lower(regexp_replace(trim(candidate.name), '[^a-z0-9]+', '', 'gi')) = lower(regexp_replace(trim(s.name), '[^a-z0-9]+', '', 'gi'))
        or exists (
          select 1 from jsonb_array_elements_text(coalesce(s.aliases, '[]'::jsonb)) alias_name
          where lower(regexp_replace(trim(candidate.name), '[^a-z0-9]+', '', 'gi')) = lower(regexp_replace(trim(alias_name), '[^a-z0-9]+', '', 'gi'))
        )
        or (
          candidate.start_date = s.start_date and nullif(trim(candidate.link), '') is not null
          and lower(trim(candidate.link)) in (lower(trim(s.link)), lower(trim(coalesce(s.ticket_url, s.link))))
        )
      )
    order by case when lower(trim(candidate.name)) = lower(trim(s.name)) then 0 else 1 end,
      candidate.updated_at desc nulls last
    limit 1
  ) existing on true
), updated as (
  update public.events target
  set name=m.name, description=m.description, link=m.link, ticket_url=m.ticket_url,
      date=m.date, start_date=m.start_date, end_date=m.end_date, location=m.location,
      lat=m.lat, lng=m.lng, vibe=m.vibe, vibe_tags=array[]::text[], event_intel=m.intel,
      seo_indexable=true, seo_quality_status='approved', updated_at=timezone('utc', now())
  from matched m where target.id=m.existing_id returning target.id
)
insert into public.events(
  name, city, description, link, ticket_url, date, start_date, end_date,
  location, lat, lng, vibe, vibe_tags, event_intel,
  seo_indexable, seo_quality_status, updated_at
)
select name, city, description, link, ticket_url, date, start_date, end_date,
  location, lat, lng, vibe, array[]::text[], intel,
  true, 'approved', timezone('utc', now())
from matched where existing_id is null;

do $qa_no_baltic_hungary_batch6_duplicates$
begin
  if exists (
    select 1 from public.events
    where start_date >= date '2026-08-29' and event_intel->>'updated_at'='2026-08-29T00:00:00Z'
    group by lower(trim(city)), lower(regexp_replace(trim(name), '[^a-z0-9]+', '', 'gi')), start_date
    having count(*) > 1
  ) then
    raise exception 'Baltic and Hungary Batch 6 duplicate detected; transaction rolled back.';
  end if;
end;
$qa_no_baltic_hungary_batch6_duplicates$;

commit;
