-- Queer Atlas: verified France, Spain and Italy events, batch 5.
-- No Portugal record is inserted: no future queer-led event had a sufficiently verified date and venue at research time.

begin;
alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists ticket_url text;

with src as (
 select * from jsonb_to_recordset($qa_fspti_batch5$
[
{"name":"Spectrum Waves: Pride Edition","aliases":["Spectrum Waves Pride edition 2026"],"city":"paris","date":"2026-10-03","start_date":"2026-10-03","end_date":"2026-10-04","description":"Spectrum Waves makes DOCK B a temporary queer planet: two rooms, no announced bill, no cameras and a crowd of night creatures trusted to transform rather than just consume the party.","link":"https://ra.co/events/2529570","ticket_url":"https://ra.co/events/2529570","location":"DOCK B, 1 Place de la Pointe, 93500 Pantin, France","lat":48.8979,"lng":2.4045,"vibe":"queer Pride rave with mystery lineup, two rooms and a no-camera transformation ritual","intel":{"hours":"23:00 Saturday 3 October–06:00 Sunday 4 October 2026.","entry_wait":"Sold out with no door tickets; use only official resale or notification channels rather than travelling without a valid ticket.","best_arrival":"Be at the opening for the whole mystery arc and a calmer awareness check.","crowd_mix":"Queers and self-described night creatures aged 21+ are the intended community, not a broad mainstream Pride crowd.","dress_code":"Drag queens, kings and night creatures may enter free; transformative, expressive styling fits the event's premise.","host_inclusivity":"Spectrum Waves explicitly rejects LGBTQ-phobia, racism, sexism, misogyny and hate; prevention and risk-reduction staff are on site.","lineup":"Intentionally unannounced.","age_limit":"21+.","source_urls":["https://ra.co/events/2529570"],"research_status":"ticketing_listing_sold_out_and_house_policy_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"Opening T7 × ORIGINS","aliases":["T7 x Origins JAZZY Toxic Machinery Angel Karel"],"city":"paris","date":"2026-10-03","start_date":"2026-10-03","end_date":"2026-10-04","description":"ORIGINS opens T7 with raw, hypnotic industrial techno and a floor that treats leather, chains and drag as a language of freedom — not just a look for the flyer.","link":"https://ra.co/events/2534447","ticket_url":"https://ra.co/events/2534447","location":"T7 Paris, Place des Insurgés de Varsovie, 75015 Paris, France","lat":48.8310,"lng":2.3654,"vibe":"industrial techno with dark sensuality and women- and marginalised-identity-centred dance-floor care","intel":{"hours":"23:00 Saturday 3 October–06:00 Sunday 4 October 2026.","entry_wait":"€29 tickets and an 18+ door are listed; arrive before the central peak to make entry straightforward.","best_arrival":"Come for 23:00 doors to hear the full build from opening sets into the hypnotic late stretch.","crowd_mix":"Women and marginalised identities are explicitly centred alongside techno dancers who understand a respectful safe-floor culture.","dress_code":"Leather, chains and drag inspire the look; dark, sensual self-expression is invited rather than a strict uniform.","host_inclusivity":"ORIGINS is a committed inclusive project built around free expression of bodies and identities, with safety and care stated as central.","lineup":"JAZZY, TOXIC MACHINERY, Angel Karel, GO$PEL and Nightowl.","age_limit":"18+.","source_urls":["https://ra.co/events/2534447"],"research_status":"ticketing_listing_and_inclusion_statement_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"KRANK: Underground / Techno / Sex Positive","aliases":["KRANK Barcelona October 2026"],"city":"barcelona","date":"2026-10-02","start_date":"2026-10-02","end_date":"2026-10-03","description":"KRANK skips the nightclub theatre for a steamier proposition: underground techno, one focused floor and generous play areas for kinksters who refuse to choose between a proper set and a properly liberated room.","link":"https://ra.co/events/2523725","ticket_url":"https://ra.co/events/2523725","location":"Sauvage Swinger Club, Avenida de Madrid 136, 08028 Barcelona, Spain","lat":41.3810,"lng":2.1358,"vibe":"sex-positive underground techno with serious sound, large play areas and fetish-door precision","intel":{"hours":"23:59 Friday 2 October–06:00 Saturday 3 October 2026; last entry is strictly 02:00.","entry_wait":"€25–35 RA tickets are listed, but the dress code is enforced and non-compliant guests are refused without refund.","best_arrival":"Reach the club before midnight for a calm wardrobe change and to avoid the hard 02:00 cutoff.","crowd_mix":"Kink-positive techno dancers; a very limited allocation for single heterosexual men is handled directly by the organiser.","dress_code":"Latex, harnesses, fishnet, leather, rubber, metal, lace and lingerie work; regular shirts, jeans, tees and ordinary underwear do not.","host_inclusivity":"The policy protects a kink-specific, consent-aware room by making the door format explicit rather than pretending it is a generic techno party.","lineup":"stndrd and Vanina Buniak.","age_limit":"18+.","source_urls":["https://ra.co/events/2523725"],"research_status":"ticketing_listing_door_policy_and_timing_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"L❋ΞX Brunch & Karaoke","aliases":["LEX Brunch and Karaoke Milan 2026"],"city":"milan","date":"2026-10-11","start_date":"2026-10-11","end_date":"2026-10-11","description":"L❋ΞX trades the late-club template for a daytime queer family table: brunch, karaoke, DJ Gimbo and Ambrosya on the mic for Milan's lesbian and queer community to be loud before sunset.","link":"https://www.laex.it/","ticket_url":"https://www.laex.it/","location":"NYX Club Milano, Milan, Italy","lat":45.4642,"lng":9.1900,"vibe":"lesbian- and queer-centred daytime brunch, karaoke and chosen-family celebration","intel":{"hours":"11:00–16:30 Sunday 11 October 2026.","entry_wait":"Brunch entry is €25 and post-brunch entry €15, both including one drink; use the organiser's current ticket link.","best_arrival":"Come for 11:00 if you want the shared-table rhythm, not only the later karaoke surge.","crowd_mix":"Lesbians, queer women and the wider LGBTQ+ community are centred in a deliberately family-like safe space.","dress_code":"Just be you.","host_inclusivity":"L❋ΞX describes itself as Milan's largest party for lesbians and queer women and explicitly operates as an LGBTQ+ safe space.","lineup":"DJ Gimbo; Ambrosya on mic.","age_limit":"Confirm in the live ticket flow.","source_urls":["https://www.laex.it/"],"research_status":"official_organiser_calendar_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"Kinky Roma Play Party","aliases":["Kinky Roma October 2026"],"city":"rome","date":"2026-10-10","start_date":"2026-10-10","end_date":"2026-10-11","description":"Kinky Roma brings its play-party chapter to Skyline Club: bodies, beats and freedom in a queer nightlife venue whose programme treats dress code and personal expression as part of the night’s shared language.","link":"https://skylineclubroma.it/?lang=en","ticket_url":"https://skylineclubroma.it/?lang=en","location":"Skyline Club Roma, San Giovanni, Rome, Italy","lat":41.8859,"lng":12.5131,"vibe":"Rome queer kink-community party with dress-code-led freedom and late-night club intimacy","intel":{"hours":"23:00 Saturday 10 October 2026; confirm closing time and exact dress direction on the organiser's live event detail.","entry_wait":"This is a special season event; use the club's current ticket or RSVP route and do not assume standard weekly entry rules apply.","best_arrival":"Arrive near 23:00 to understand the event-specific door format before the room fills.","crowd_mix":"Rome's LGBTQ+ nightlife and kink-community guests looking for a themed, expression-led party rather than a generic disco.","dress_code":"Dress code applies; the exact edition rule is supplied on the live event detail and should be checked before travelling.","host_inclusivity":"Skyline frames its programme around nightlife, music, community and freedom of expression in an LGBTQ+ venue.","lineup":"Programme details published by Skyline Club Roma.","age_limit":"Confirm with organiser.","source_urls":["https://skylineclubroma.it/?lang=en"],"research_status":"official_club_season_calendar_verified_event_details_pending","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"Subject Sue + Las Eras Live","aliases":["Subject Sue Las Eras Bologna 2026"],"city":"bologna","date":"2026-11-27","start_date":"2026-11-27","end_date":"2026-11-27","description":"Subject Sue and Las Eras give Bologna's TANK a live electronic night shaped by queer club culture and half-forgotten 1930s–60s archives — intimate, unsettling and euphoric in the same breath.","link":"https://ra.co/events/2516508","ticket_url":"https://ra.co/events/2516508","location":"TANK, Via Emilio Zago 14, Bologna, Italy","lat":44.5150,"lng":11.3545,"vibe":"live electronic performance with queer club-memory, archival tension and intimate nocturnal atmosphere","intel":{"hours":"Doors at 21:00 Friday 27 November 2026; check the current DICE listing for full running order and finish time.","entry_wait":"Advance tickets are sold through DICE; ARCI membership is required for entry, so confirm membership before purchase or travel.","best_arrival":"Be there at 21:00 for both live performances and a softer entry into the event's conceptual world.","crowd_mix":"Queer-culture listeners, experimental live-music audiences and Bologna underground regulars seeking something more intimate than a standard DJ night.","dress_code":"No formal code is published; thoughtful, comfortable night-out clothing suits an audience focused on live performance.","host_inclusivity":"The project explicitly draws from queer club culture and turns historical queer archives into a contemporary shared space.","lineup":"Las Eras live; Subject Sue live.","age_limit":"Confirm with venue and ticketing.","source_urls":["https://ra.co/events/2516508"],"research_status":"ticketing_listing_and_venue_membership_requirement_verified","updated_at":"2026-09-26T00:00:00Z"}}
]
$qa_fspti_batch5$) e(name text,aliases jsonb,city text,date date,start_date date,end_date date,description text,link text,ticket_url text,location text,lat double precision,lng double precision,vibe text,intel jsonb)
), matched as (
 select s.*,x.id existing_id from src s left join lateral(select e.id from public.events e where lower(trim(e.city))=lower(trim(s.city)) and (lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(s.name),'[^a-z0-9]+','','gi')) or exists(select 1 from jsonb_array_elements_text(s.aliases) a where lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(a),'[^a-z0-9]+','','gi'))) or (e.start_date=s.start_date and lower(nullif(trim(e.link),'')) in(lower(s.link),lower(s.ticket_url)))) limit 1)x on true
), updated as (
 update public.events e set name=s.name,description=s.description,link=s.link,ticket_url=s.ticket_url,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,vibe_tags=array[]::text[],event_intel=s.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from matched s where e.id=s.existing_id returning e.id
)
insert into public.events(name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,event_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],intel,true,'approved',timezone('utc',now()) from matched where existing_id is null;

do $qa_fspti_batch5_guard$
begin
 if exists(select 1 from public.events where event_intel->>'updated_at'='2026-09-26T00:00:00Z' and (coalesce(trim(description),'')='' or coalesce(trim(location),'')='' or jsonb_array_length(coalesce(event_intel->'source_urls','[]'::jsonb))=0)) then raise exception 'France Spain Portugal Italy batch missing editorial data'; end if;
end;
$qa_fspti_batch5_guard$;
commit;
