-- Queer Atlas: verified Japan, Philippines, South Korea and Thailand events, batch 11.

begin;
alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists ticket_url text;

with src as (
 select * from jsonb_to_recordset($qa_batch11$
[
{"name":"experiment","aliases":["experiment Fetish Techno Tokyo October 2026","experiment B.A.R.K. White Space Lab"],"city":"tokyo","date":"2026-10-16","start_date":"2026-10-16","end_date":"2026-10-16","description":"experiment distils Shibuya into a dark, precise collision of fetish aesthetics and relentless techno: body, sound and desire given enough room to become their own language.","link":"https://experiment-re-cords.jp/en/next-event/","ticket_url":"https://experiment-re-cords.jp/en/next-event/","location":"White Space Lab, Shibuya, Tokyo, Japan","lat":35.6595,"lng":139.6989,"vibe":"inclusive Shibuya fetish-techno laboratory with black-clad precision and body-forward sound","intel":{"hours":"19:00–23:30 Friday 16 October 2026; changing access is available 18:30–19:00.","entry_wait":"Guest-list registration gives ¥500 off; register in advance and expect entry to be refused if the strongly encouraged dress code is ignored.","best_arrival":"Use the early changing window if you need it, then be in by 19:00 for a cleaner entry and the complete short-form techno arc.","crowd_mix":"Fetish-techno regulars, queer-friendly Shibuya clubbers, fashion-minded dancers and people who prefer intent over generic nightlife.","dress_code":"Fetish styling is strongly encouraged; all black is the safe default. No re-entry, lockers or cloakroom are available.","host_inclusivity":"experiment calls itself raw, underground and inclusive, and asks guests to report inappropriate behaviour to crew immediately.","lineup":"B.A.R.K., Hexe, Znthiia, Ai and Louis Kordexe; Yousuke Fuyama is also listed in the live RA programme.","age_limit":"Confirm with organiser before attending.","source_urls":["https://experiment-re-cords.jp/en/next-event/","https://experiment-re-cords.jp/en/home/"],"research_status":"official_date_hours_host_policy_dress_code_and_venue_area_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"Casket of Horrors: Kabukicho in Space","aliases":["Haus von Schwarz Casket of Horrors Tokyo 2026","Kabukicho in Space 666th anniversary"],"city":"tokyo","date":"2026-10-17","start_date":"2026-10-17","end_date":"2026-10-17","description":"Haus von Schwarz throws its Casket of Horrors into orbit: Tokyo alternative drag, burlesque and queer art for anyone who prefers their Halloween ridiculous, theatrical and a little extraterrestrial.","link":"https://kabukichoinspace.peatix.com/","ticket_url":"https://kabukichoinspace.peatix.com/","location":"Shinjuku Heist, Horizon Building B2F, 2-25-6 Kabukicho, Shinjuku, Tokyo, Japan","lat":35.6967,"lng":139.7047,"vibe":"alternative queer cabaret from outer space: dark drag, burlesque and Tokyo underground theatre","intel":{"hours":"19:00–22:00 Saturday 17 October 2026.","entry_wait":"Advance tickets are ¥4,000 and door tickets ¥5,000, plus a ¥700 drink ticket at entry; secure advance access for the smaller performance format.","best_arrival":"Arrive for 19:00 so the space-themed drag narrative lands as a whole rather than as isolated late acts.","crowd_mix":"Alternative drag followers, burlesque fans, local queer creatives, costume-minded visitors and audiences that value performance over a conventional club set.","dress_code":"No mandatory look is stated; dark theatrical or space-age styling fits the 666th-anniversary concept without being required.","host_inclusivity":"Haus von Schwarz’s programme is built around Tokyo’s alternative and queer art community, foregrounding emerging performers alongside established local acts.","lineup":"Alternative drag, burlesque, live musicians and special guest/debut performances; the final artist roster is released by the house.","age_limit":"Confirm with ticketing before attending.","source_urls":["https://www.timeout.com/tokyo/lgbtq/haus-von-schwarz-presents-casket-of-horrors-kabukicho-in-space","https://kabukichoinspace.peatix.com/"],"research_status":"published_date_hours_full_address_ticket_prices_and_queer_programme_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"Intensity Manila: Anime City — Day 1","aliases":["Intensity Manila Anime City BSK Raveclub 2026","Intensity Anime City dark circuit Manila"],"city":"manila","date":"2026-10-02","start_date":"2026-10-02","end_date":"2026-10-03","description":"Intensity Manila opens Anime City on its darker setting: hard circuit pressure, tech house, techno and cosplay imagination turned loose in a Mandaluyong rave-room.","link":"https://whereto.party/events/intensity-manila-anime-city/mandaluyong-city","ticket_url":"https://whereto.party/events/intensity-manila-anime-city/mandaluyong-city","location":"BSK Raveclub, Sheridan, Greenfield District, Mandaluyong City 1550, Metro Manila, Philippines","lat":14.5778,"lng":121.0562,"vibe":"dark-circuit Manila opener with techno, tech house and anime cosplay energy","intel":{"hours":"Friday 2 October 2026; confirm door and closing times in the active ticket channel.","entry_wait":"This is the first half of a two-night circuit weekend; buy through the named event channel and allow for costume/security checks.","best_arrival":"Arrive close to doors to catch the darker techno/tech-house identity before the floor reaches peak rave density.","crowd_mix":"Manila circuit dancers, anime and cosplay fans, electronic-music regulars and guests joining the two-night Intensity community.","dress_code":"Cosplay is encouraged across Anime City. Pick a look that can handle heat and continuous movement in a dark-circuit room.","host_inclusivity":"Intensity Manila is an established gay circuit brand whose weekend is framed around diversity, dance and shared self-expression.","lineup":"Day 1 is billed as techno, tech house and dark circuit; final artist schedule is released via Intensity Manila.","age_limit":"Confirm through ticketing before attending.","source_urls":["https://whereto.party/events/intensity-manila-anime-city/mandaluyong-city","https://www.gaytravel4u.com/event/intensity-manila-circuit-event/"],"research_status":"event_listing_date_full_address_two_night_format_and_music_theme_verified_final_hours_pending","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"Intensity Manila: Anime City — Day 2","aliases":["Intensity Manila Anime City Stratosphere 2026","Intensity Anime City circuit Makati"],"city":"manila","date":"2026-10-03","start_date":"2026-10-03","end_date":"2026-10-04","description":"Anime City turns full colour for Intensity Manila’s second night: big-room circuit, house, bodies in cosplay and a Makati finale built to be louder than its own storyline.","link":"https://whereto.party/events/intensity-manila-anime-city/makati-city","ticket_url":"https://whereto.party/events/intensity-manila-anime-city/makati-city","location":"Stratosphere Events Place, 4/F Century Mall, Kalayaan Avenue corner Salamanca Street, Makati City 1209, Metro Manila, Philippines","lat":14.5657,"lng":121.0302,"vibe":"full-colour Makati circuit finale with house, big-room lift and anime-cosplay release","intel":{"hours":"Saturday 3 October 2026; confirm door and closing times in the active ticket channel.","entry_wait":"The venue sits on Century Mall’s fourth floor; secure the event ticket ahead and build in time for mall/venue entry before the second-night rush.","best_arrival":"Come early enough to see the cosplay field before the big-room programme pulls the crowd toward the main floor.","crowd_mix":"Circuit-party regulars, local and visiting LGBTQ+ dancers, house fans and anime-cosplay guests continuing from the Mandaluyong opener.","dress_code":"Come as a favourite anime character or use imaginative cosplay—Anime City explicitly encourages both.","host_inclusivity":"Intensity Manila’s circuit programme is presented as an LGBTQ+ community celebration focused on diversity, high-energy dance culture and self-expression.","lineup":"Day 2 is billed as house, big room and circuit; final artist schedule is released via Intensity Manila.","age_limit":"Confirm through ticketing before attending.","source_urls":["https://whereto.party/events/intensity-manila-anime-city/makati-city","https://www.ticketmax.ph/venues/stratosphere-events-place/"],"research_status":"event_listing_date_full_address_two_night_format_and_music_theme_verified_final_hours_pending","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"Lazberry","aliases":["Lazberry FLINTA Seoul October 2026","Lazberry at Nyapi Melting 99"],"city":"seoul","date":"2026-10-01","start_date":"2026-10-01","end_date":"2026-10-02","description":"Lazberry makes Nyapi a Seoul FLINTA* living room with real sub-bass: Melting 99’s cold digital swing, local selectors and a floor built for care without killing the edge.","link":"https://ra.co/events/2545012","ticket_url":"https://ra.co/events/2545012","location":"Nyapi, 187 Itaewon-ro, Yongsan-gu, Seoul, South Korea","lat":37.5343,"lng":126.9945,"vibe":"FLINTA*-centred Itaewon electronic night with house, tech-house and a care-first underground floor","intel":{"hours":"22:00 Thursday 1 October–04:00 Friday 2 October 2026.","entry_wait":"Entry is listed at ₩15,000; buy or confirm through the live organiser/RA channel and bring photo ID for the 18+ check.","best_arrival":"Arrive for 22:00 to settle into Nyapi before the compact floor reaches its fuller late-night energy.","crowd_mix":"Women, lesbians, intersex, non-binary, trans and agender dancers, alongside people who actively respect the FLINTA*-centred space.","dress_code":"No fixed look is published; functional clubwear and self-expression are a better fit than treating the room as a costume obligation.","host_inclusivity":"Lazberry explicitly centres FLINTA* identities and its mutual-care culture, while Nyapi presents itself as a genre-open home for freedom and community.","lineup":"Melting 99, Kugel, Soyo, Uni and YAREE.","age_limit":"18+.","source_urls":["https://ra.co/events/2545012"],"research_status":"ra_date_hours_full_address_lineup_price_age_and_flinta_policy_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"RGB Golden Week: Unleash × Shadow × Bearism","aliases":["RGB Pride Party Golden Week Bangkok 2026","Unleash Shadow Bearism Hook Up BKK"],"city":"bangkok","date":"2026-10-02","start_date":"2026-10-02","end_date":"2026-10-03","description":"RGB makes Bangkok Golden Week sweat on purpose: a Pride circuit party with an underwear zone, a full dance floor and no interest in shrinking desire down to polite small talk.","link":"https://megatix.in.th/events/rgb-golden-week-unleash-x-shadow-x-bearism","ticket_url":"https://megatix.in.th/events/rgb-golden-week-unleash-x-shadow-x-bearism","location":"Hook Up BKK, 37/5 2nd Floor, Surawong Road, Suriyawong, Bang Rak, Bangkok 10500, Thailand","lat":13.7283,"lng":100.5332,"vibe":"Bangkok Pride circuit heat: underwear-zone confidence, late dance-floor release and Golden Week spectacle","intel":{"hours":"22:00 Friday 2 October–05:00 Saturday 3 October 2026.","entry_wait":"Ticket tiers run from early-bird through door sale; use Megatix before travelling and expect the semi-underwear theme to make pre-entry preparation worthwhile.","best_arrival":"Come for 22:00 to use both the underwear and dance zones before the late-night circuit crowd fills the room.","crowd_mix":"Bangkok Pride-party regulars, bear and circuit communities, friends seeking a sexy queer dance floor and visitors who respect the event’s body-positive setting.","dress_code":"Semi-underwear is the stated dress code. Build a look that feels bold while remaining comfortable and respectful in a crowded club.","host_inclusivity":"The event is produced by RGB Pride Party and explicitly framed as a Pride experience with distinct body-positive social and dance spaces.","lineup":"Unleash × Shadow × Bearism collaborative Pride programme; confirm DJ and performance roster through the live ticket page.","age_limit":"20+.","source_urls":["https://megatix.in.th/events/rgb-golden-week-unleash-x-shadow-x-bearism"],"research_status":"official_ticketing_date_hours_full_address_age_dress_code_and_pride_format_verified","updated_at":"2026-09-26T00:00:00Z"}},
{"name":"GEGEN × HORNBKK","aliases":["GEGEN X HORNBKK Bangkok October 2026","Gegen Horn Bangkok techno 2026"],"city":"bangkok","date":"2026-10-24","start_date":"2026-10-24","end_date":"2026-10-25","description":"GEGEN and HORNBKK bring Berlin-born queer fetish gravity to Silom: hard-breathing techno, performance bodies and an XXL play area for a Bangkok night that refuses to stay on the safe side of the room.","link":"https://ra.co/events/2502998","ticket_url":"https://ra.co/events/2502998","location":"Horn, 4th Floor, 71–73 Silom 4 Alley, Suriya Wong, Bang Rak, Bangkok 10500, Thailand","lat":13.7302,"lng":100.5324,"vibe":"queer-fetish techno in Silom: Berlin pressure, performance bodies and a purpose-built play space","intel":{"hours":"22:00 Saturday 24 October–03:00 Sunday 25 October 2026.","entry_wait":"Presale is limited and door tickets are listed only with dress code; buy early and read the current event guidance before heading to Horn.","best_arrival":"Reach the club around 22:00 for easier entry and time to understand the venue’s sound, performance and play-space boundaries.","crowd_mix":"Bangkok queer nightlife, fetish and leather communities, GEGEN travellers, techno devotees and guests who opt in to an erotic performance setting.","dress_code":"A door ticket requires dress code. Fetish styling is appropriate; choose gear you can safely wear and dance in while following venue consent rules.","host_inclusivity":"GEGEN is a queer-fetish party framework, and the Horn collaboration explicitly couples techno, performance and play spaces rather than treating sexuality as decoration.","lineup":"Sound: 5.5MM, Cristian Marras and Mar/us. Bodies: Aisin, Beer and Snooker.","age_limit":"Confirm with promoter and ticketing before attending.","source_urls":["https://ra.co/events/2502998"],"research_status":"ra_date_hours_full_address_lineup_genre_and_dress_code_requirement_verified","updated_at":"2026-09-26T00:00:00Z"}}
]
$qa_batch11$) e(name text,aliases jsonb,city text,date date,start_date date,end_date date,description text,link text,ticket_url text,location text,lat double precision,lng double precision,vibe text,intel jsonb)
), matched as (
 select s.*,x.id existing_id from src s left join lateral(select e.id from public.events e where lower(trim(e.city))=lower(trim(s.city)) and (lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(s.name),'[^a-z0-9]+','','gi')) or exists(select 1 from jsonb_array_elements_text(s.aliases) a where lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(a),'[^a-z0-9]+','','gi'))) or (e.start_date=s.start_date and lower(nullif(trim(e.link),'')) in(lower(s.link),lower(s.ticket_url)))) limit 1)x on true
), updated as (
 update public.events e set name=s.name,description=s.description,link=s.link,ticket_url=s.ticket_url,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,vibe_tags=array[]::text[],event_intel=s.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from matched s where e.id=s.existing_id returning e.id
)
insert into public.events(name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,event_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],intel,true,'approved',timezone('utc',now()) from matched where existing_id is null;

do $qa_batch11_guard$
begin
 if exists(select 1 from public.events where event_intel->>'updated_at'='2026-09-26T00:00:00Z' and (coalesce(trim(description),'')='' or coalesce(trim(location),'')='' or jsonb_array_length(coalesce(event_intel->'source_urls','[]'::jsonb))=0)) then raise exception 'Japan Philippines South Korea Thailand batch missing editorial data'; end if;
end;
$qa_batch11_guard$;
commit;
