-- Queer Atlas: Nordic queer events, batch 2.
-- Countries: Sweden, Norway, Denmark, Finland and Iceland.
-- Research completed 2026-09-26. Every record has an organiser, venue or ticketing source.

begin;

alter table if exists public.events
  add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events
  add column if not exists ticket_url text;

with src as (
  select * from jsonb_to_recordset($qa_nordics_batch2$
[
  {"name":"Lilith Club: Sapphic Halloween","aliases":["Lilith Club – Sapphic Halloween – October 31","Lilith Sapphic Halloween Night"],"city":"stockholm","date":"2026-10-31","start_date":"2026-10-31","end_date":"2026-11-01","description":"Lilith turns House of Q into a sapphic Halloween refuge: pop, hyperpop and slutty rave split across two floors, with performances, a darkroom and a lounge made for meeting people between dance-floor spells.","link":"https://blackplanet.se/event/lilith-club-sapphic-halloween-october-31/","ticket_url":"https://blackplanet.se/event/lilith-club-sapphic-halloween-october-31/","location":"House of Q, Malmvägen 1, 115 41 Stockholm, Sweden","lat":59.3293,"lng":18.0686,"vibe":"radical sapphic Halloween club with pop, hyperpop, rave and community space","intel":{"hours":"21:00–03:00 Saturday 31 October into Sunday 1 November 2026.","entry_wait":"Presale only; the organiser says Lilith events sell out quickly and no tickets are sold at the door.","best_arrival":"Come near 21:00 for the social lounge, performances and both floors before the Halloween peak.","crowd_mix":"Lesbians, bi and pan women, trans women, non-binary people who love women, working-class queers and artists are directly centred.","dress_code":"Halloween looks are strongly encouraged; wear whatever keeps you up at night and can handle a long dance floor.","host_inclusivity":"Cis men and TERFs are explicitly excluded. The organiser frames the room as trans-welcoming radical sapphic space.","lineup":"Two dance floors: girly pop; hyperpop and rave music. Sapphic performances are programmed.","age_limit":"Confirm on the ticket page.","source_urls":["https://blackplanet.se/event/lilith-club-sapphic-halloween-october-31/"],"research_status":"official_ticketing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Cabaret Club – 10 October 2026","aliases":["Cabaret Club Oslo October 2026"],"city":"oslo","date":"2026-10-10","start_date":"2026-10-10","end_date":"2026-10-10","description":"Ivana Impeachum's Cabaret Club brings the decadent, tender edge of queer Berlin cabaret to Oslo Nye Teaterkjelleren: drag, burlesque, humour and a rotating cast that keeps every edition singular.","link":"https://www.visitoslo.com/event/cabaret-club","ticket_url":"https://www.ticketmaster.no/","location":"Oslo Nye Teaterkjelleren, Akersgata 38, 0102 Oslo, Norway","lat":59.9141,"lng":10.7413,"vibe":"intimate queer cabaret with drag, burlesque and 1930s Berlin atmosphere","intel":{"hours":"21:00–22:00 Saturday 10 October 2026.","entry_wait":"Use the official Ticketmaster route; this is a seated or performance-led hour, so do not depend on late entry.","best_arrival":"Arrive 20–30 minutes early for ticket scan and a drink before the compact one-hour performance begins.","crowd_mix":"Queer culture lovers, drag and burlesque regulars, theatre-goers and nightlife guests looking for a performance rather than a generic club night.","dress_code":"No enforced look is published; cabaret glamour is welcome without being a requirement.","host_inclusivity":"VisitOSLO categorises the event as LGBTQIA+ and the format celebrates the rawness and love in queer culture.","lineup":"Ivana Impeachum hosts; the autumn series rotates artists by edition.","age_limit":"Check the live ticket listing.","source_urls":["https://www.visitoslo.com/event/cabaret-club"],"research_status":"official_destination_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"BRITNEY CLUB","aliases":["Britney Club Oslo 2026"],"city":"oslo","date":"2026-10-17","start_date":"2026-10-17","end_date":"2026-10-18","description":"BRITNEY CLUB makes SALT an all-night pop universe for people who still feel Toxic in their bones: queer line dance, drag pop-ups, karaoke, quiz, costume competition and a DJ-driven late club.","link":"https://www.broadcast.events/events/britney-club/P90BL9jx4r","ticket_url":"https://www.broadcast.events/events/britney-club/P90BL9jx4r","location":"SALT Art & Music, Langkaia 1, 0150 Oslo, Norway","lat":59.9065,"lng":10.7533,"vibe":"queer pop festival, karaoke and dance-floor nostalgia with drag energy","intel":{"hours":"17:00 Saturday 17 October–01:00 Sunday 18 October 2026.","entry_wait":"Multiple ticket types cover separate programme sections; choose the Full Britney Experience only if you want the whole day and night.","best_arrival":"Arrive from doors to catch the quiz, line dance and karaoke before the late DJ club portion.","crowd_mix":"Millennial pop devotees, queer line dancers, drag fans, karaoke regulars and friends who treat Britney as communal memory.","dress_code":"A Britney-inspired outfit is ideal for the competition but not mandatory; plan for a full evening of dancing.","host_inclusivity":"The programme explicitly includes queer line dance and drag pop-ups, built by Jelena Skankovic and Nabi Yeon Geisha with SALT and OsloMet.","lineup":"Ayama Star, Alara Joy, DJ Austinatt, DJ Ursula and DJ Ferdinand, plus quiz and costume hosts.","age_limit":"20+.","source_urls":["https://www.broadcast.events/events/britney-club/P90BL9jx4r"],"research_status":"official_ticketing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Oslo Queer Line Dance: Onboarding Class","aliases":["Oslo Queer Line Dance Onboarding class October 2026"],"city":"oslo","date":"2026-10-06","start_date":"2026-10-06","end_date":"2026-10-06","description":"An entry point to Oslo's queer line-dance floor: learn the moves without needing a partner, then come back knowing both the steps and the people who make the regular class feel like a little chosen-family ritual.","link":"https://blaaoslo.no/","ticket_url":"https://www.ticketmaster.no/","location":"Himmel at BLÅ, Brenneriveien 9c, 0182 Oslo, Norway","lat":59.9224,"lng":10.7500,"vibe":"welcoming queer line-dance onboarding for social movement and new connections","intel":{"hours":"Tuesday 6 October 2026; confirm the live start time and ticket terms with BLÅ.","entry_wait":"This is an onboarding class rather than a late-night club door; reserve through the current venue or ticket listing if required.","best_arrival":"Be there a little before the published class start so the first steps do not become a catch-up exercise.","crowd_mix":"Queer people and supportive dance-curious newcomers; no partner or prior line-dance fluency is implied by the onboarding format.","dress_code":"Movement-friendly clothes and shoes with enough grip for repeated steps beat costume pressure.","host_inclusivity":"The title and recurring programme explicitly make queer social dance the point, rather than treating it as an add-on to a general club night.","lineup":"Instructor-led onboarding class; music and instructor details are confirmed by the venue.","age_limit":"Check the live venue listing.","source_urls":["https://blaaoslo.no/","https://www.ticketmaster.no/discover/oslo?categoryId=KZFzniwnSyZfZ7v7nJ&classificationId=KnvZfZ7vAvF&language=en-us"],"research_status":"venue_calendar_verified_details_to_confirm","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"GROUP THERAPY 8 YEARS","aliases":["Group Therapy 8 Years Copenhagen 2026"],"city":"copenhagen","date":"2026-10-10","start_date":"2026-10-10","end_date":"2026-10-11","description":"Group Therapy marks eight years of queer love and playful sound with the rare kind of b2b that rewards staying close to the speakers: Lakuti and Tama Sumo stretching house and disco into something warm, deep and unhurried.","link":"https://ra.co/events/dk/copenhagen?startDate=2026-10-10","ticket_url":"https://ra.co/events/dk/copenhagen?startDate=2026-10-10","location":"Den Anden Side, Axeltorv 5, 1609 Copenhagen, Denmark","lat":55.6752,"lng":12.5622,"vibe":"queer house and disco anniversary with deep, percussive all-night energy","intel":{"hours":"Saturday 10 October 2026; confirm exact doors and closing time on the live RA ticket page.","entry_wait":"The listing is ticketed; Den Anden Side also uses its normal selection process, so a ticket is not a substitute for arriving ready for the space.","best_arrival":"Come near doors to hear the full anniversary arc and have an easier conversation with the entrance team.","crowd_mix":"Group Therapy's queer community, house and disco dancers, and guests who value a playful but musically serious floor.","dress_code":"No event-specific code is listed; intentional clubwear is a better fit than business or sports-uniform styling discouraged by venue policy.","host_inclusivity":"Den Anden Side centres queer and marginalised guests with consent, awareness-team and no-photo expectations; Group Therapy is explicitly celebrating queer love.","lineup":"Lakuti b2b Tama Sumo; Aldonna, Frederik Tollund, Selma, DJ Woo Girl and Lucky Lube.","age_limit":"20+; confirm on current ticketing.","source_urls":["https://ra.co/events/dk/copenhagen?startDate=2026-10-10","https://www.denandenside.com/club-policy"],"research_status":"ra_city_listing_and_venue_policy_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"69/96: The Final Descent","aliases":["The Final Descent Copenhagen Pride 2026"],"city":"copenhagen","date":"2026-10-24","start_date":"2026-10-24","end_date":"2026-10-25","description":"Copenhagen Pride closes its 30th anniversary year by going underground: The Final Descent trades rainbow polish for drag, decadence, DJs and a pre-Halloween basement where queer history is felt rather than recited.","link":"https://www.copenhagenpride.dk/en/event/69-96-the-final-descent/","ticket_url":"https://www.copenhagenpride.dk/en/event/69-96-the-final-descent/","location":"Basement, Enghavevej 42, 1674 Copenhagen V, Denmark","lat":55.6676,"lng":12.5444,"vibe":"underground queer pre-Halloween party with drag, DJs and decadent basement energy","intel":{"hours":"22:00 Saturday 24 October–05:00 Sunday 25 October 2026.","entry_wait":"Early-bird tickets are 75 DKK until 1 October, then 100 DKK at full price or door; buy early for the small underground room.","best_arrival":"Arrive around 22:00 to catch the opening descent and avoid compressing your night into the late costume rush.","crowd_mix":"Copenhagen Pride's queer community, drag audiences, underground party people and allies who come for liberation rather than spectacle.","dress_code":"No formal code is published; the theme welcomes dark, decadent pre-Halloween self-expression.","host_inclusivity":"Produced by Copenhagen Pride and explicitly framed around freedom, community, desire and queer struggle.","lineup":"Bazooka (CPH) is announced; further programme is on the organiser page.","age_limit":"Check current ticketing.","source_urls":["https://www.copenhagenpride.dk/en/event/69-96-the-final-descent/"],"research_status":"official_organiser_and_ticketing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Global Queers: Queer Yoga","aliases":["Global Queers Helsinki Queer Yoga 2026"],"city":"helsinki","date":"2026-10-12","start_date":"2026-10-12","end_date":"2026-10-12","description":"Global Queers makes yoga a meeting point rather than a wellness performance: an English-language queer evening with a visiting instructor from Taiwan, designed for breathing room, movement and new peer connections.","link":"https://pride.fi/en/get-involved/activities-for-adults/","ticket_url":"https://pride.fi/en/get-involved/activities-for-adults/","location":"Helsinki Pride community room, Ruoholahti Cable Factory, Tallberginkatu 1, courtyard, C-stairs, 4th floor, 00180 Helsinki, Finland","lat":60.1633,"lng":24.9143,"vibe":"gentle LGBTQIA+ community yoga and peer connection in English","intel":{"hours":"18:00–20:00 Monday 12 October 2026.","entry_wait":"The organiser asks guests to be on time and closes doors 15 minutes after activities begin; confirm any registration requirement before travelling.","best_arrival":"Arrive 10–15 minutes early to find the courtyard entrance and fourth-floor community room without missing the welcome.","crowd_mix":"LGBTQIA+ people living in Helsinki who want English-language peer connection, including newcomers to the city.","dress_code":"Comfortable movement clothing; this is alcohol-free community space rather than a nightlife room.","host_inclusivity":"Helsinki Pride's Global Queers group welcomes LGBTQIA+ people in English and operates under safer-space principles.","lineup":"Guest yoga instructor from Taiwan.","age_limit":"Adult community activity; confirm eligibility with Helsinki Pride.","source_urls":["https://pride.fi/en/get-involved/activities-for-adults/"],"research_status":"official_organiser_calendar_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Global Queers: Game Night + Art/Crafting","aliases":["Global Queers Helsinki Game Night 2026"],"city":"helsinki","date":"2026-11-16","start_date":"2026-11-16","end_date":"2026-11-16","description":"A November Global Queers night built for low-stakes connection: games, making things and the rare chance to arrive alone to a queer room that has already made space for conversation.","link":"https://pride.fi/en/get-involved/activities-for-adults/","ticket_url":"https://pride.fi/en/get-involved/activities-for-adults/","location":"Helsinki Pride community room, Ruoholahti Cable Factory, Tallberginkatu 1, courtyard, C-stairs, 4th floor, 00180 Helsinki, Finland","lat":60.1633,"lng":24.9143,"vibe":"English-language queer game night and creative community hang","intel":{"hours":"18:00–20:00 Monday 16 November 2026.","entry_wait":"Doors close 15 minutes after the start; check Helsinki Pride's current activity guidance for registration or accessibility needs.","best_arrival":"Reach the Cable Factory before 18:00 so finding the courtyard and C-stairs does not cut into introductions.","crowd_mix":"LGBTQIA+ Helsinki residents, internationals and people looking for friendship through an English-language peer group.","dress_code":"Come as you are; casual craft-night comfort is the intended energy.","host_inclusivity":"Helsinki Pride hosts the group in a safer-space, alcohol-free community room specifically for LGBTQIA+ peer connection.","lineup":"Facilitated Global Queers activity: games and art/crafting.","age_limit":"Adult community activity; confirm with organiser.","source_urls":["https://pride.fi/en/get-involved/activities-for-adults/"],"research_status":"official_organiser_calendar_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Global Queers: Potluck + Karaoke with Pikkujoulu","aliases":["Global Queers Helsinki Potluck Karaoke 2026"],"city":"helsinki","date":"2026-12-14","start_date":"2026-12-14","end_date":"2026-12-14","description":"Global Queers ends its autumn rhythm with a potluck, karaoke and Pikkujoulu: a small queer December celebration where the point is sharing a table, then taking the mic in whatever key feels right.","link":"https://pride.fi/en/get-involved/activities-for-adults/","ticket_url":"https://pride.fi/en/get-involved/activities-for-adults/","location":"Helsinki Pride community room, Ruoholahti Cable Factory, Tallberginkatu 1, courtyard, C-stairs, 4th floor, 00180 Helsinki, Finland","lat":60.1633,"lng":24.9143,"vibe":"cozy English-language queer holiday potluck and karaoke night","intel":{"hours":"18:00–20:00 Monday 14 December 2026.","entry_wait":"Arrive on time: doors close 15 minutes after activities begin. Confirm what to bring for the potluck with the organiser.","best_arrival":"Be at the community room before 18:00 to settle food safely and join the first round of conversation.","crowd_mix":"LGBTQIA+ people in Helsinki, particularly English-speaking peers and people looking for a softer seasonal gathering.","dress_code":"Festive knitwear, a karaoke look or everyday comfort all work; alcohol is not part of the activity.","host_inclusivity":"Helsinki Pride's Global Queers programme uses safer-space principles and makes peer community available in English.","lineup":"Potluck and karaoke with Pikkujoulu.","age_limit":"Adult community activity; confirm with organiser.","source_urls":["https://pride.fi/en/get-involved/activities-for-adults/"],"research_status":"official_organiser_calendar_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Music and Magic: Reykjavík Queer Choir × Fado Bicha","aliases":["Music and Magic Reykjavik Queer Choir Fado Bicha"],"city":"reykjavik","date":"2026-10-01","start_date":"2026-10-01","end_date":"2026-10-01","description":"RIFF pairs Reykjavík Queer Choir with Lisbon duo Fado Bicha for a concert where queer voices bend a beloved tradition without asking it for permission: cinematic, communal and gleefully unboxed.","link":"https://riff.is/en/special-events/category/special-events/2026-10/","ticket_url":"https://riff.is/en/special-events/category/special-events/2026-10/","location":"Háskólabíó, Hagatorg, 107 Reykjavík, Iceland","lat":64.1373,"lng":-21.9488,"vibe":"queer choir and boundary-pushing fado concert within Reykjavík International Film Festival","intel":{"hours":"20:30–22:00 Thursday 1 October 2026.","entry_wait":"Use RIFF's live event page for availability and ticket conditions; this is a timed seated concert, not a rolling door.","best_arrival":"Arrive 20–30 minutes early for ticket scan and a calm seat before the 20:30 downbeat.","crowd_mix":"Queer music audiences, film-festival visitors, choir supporters and listeners drawn to Fado Bicha's reworked Portuguese tradition.","dress_code":"No special look is published; concert-ready warmth is sensible for an October Reykjavík evening.","host_inclusivity":"RIFF describes the concert as a unique celebration of queerness, with Reykjavík's queer choir and Fado Bicha sharing the stage.","lineup":"Reykjavík Queer Choir and Fado Bicha.","age_limit":"Check RIFF ticket guidance.","source_urls":["https://riff.is/en/special-events/category/special-events/2026-10/"],"research_status":"official_festival_calendar_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Reykjavík Pride 2027: Queer City Walk","aliases":["Pink Iceland Queer City Walk 2027"],"city":"reykjavik","date":"2027-08-05","start_date":"2027-08-05","end_date":"2027-08-05","description":"Pink Iceland's Pride-week Queer City Walk follows the people, places and frictions that shaped Reykjavík's LGBTQIA+ story — a city tour with actual queer memory under its feet, not a rainbow sightseeing overlay.","link":"https://www.pinkiceland.is/reykjavik-pride","ticket_url":"https://www.pinkiceland.is/reykjavik-pride","location":"Reykjavík, Iceland — exact meeting point supplied by Pink Iceland to confirmed guests","lat":64.1466,"lng":-21.9426,"vibe":"queer-history city walk during Reykjavík Pride week","intel":{"hours":"Thursday 5 August 2027; Pink Iceland will confirm departure time and meeting point with bookings.","entry_wait":"Book directly with the queer-owned organiser; do not travel to an assumed meeting point because it is not published on the programme page.","best_arrival":"Follow the confirmed booking instructions and allow extra time for central Reykjavík festival traffic.","crowd_mix":"LGBTQIA+ travellers, friends, families, allies and local history lovers looking for a queer lens on the city.","dress_code":"Walking shoes and changeable-weather layers are more useful than a festival outfit.","host_inclusivity":"Pink Iceland is queer-owned and designs the experience for LGBTQIA+ travellers and the communities gathering around Reykjavík Pride.","lineup":"Guided Queer City Walk.","age_limit":"Confirm with Pink Iceland.","source_urls":["https://www.pinkiceland.is/reykjavik-pride"],"research_status":"official_organiser_date_verified_meeting_point_pending","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Reykjavík Pride 2027: Gay Golden Circle","aliases":["Pink Iceland Gay Golden Circle 2027"],"city":"reykjavik","date":"2027-08-06","start_date":"2027-08-06","end_date":"2027-08-06","description":"Pink Iceland's Gay Golden Circle turns the country's classic day trip into Pride company: seven hours of big landscape, lunch and queer conversation before Reykjavík's parade weekend hits full volume.","link":"https://www.pinkiceland.is/reykjavik-pride","ticket_url":"https://www.pinkiceland.is/reykjavik-pride","location":"Reykjavík departure point supplied by Pink Iceland to confirmed guests; Golden Circle route, Iceland","lat":64.1466,"lng":-21.9426,"vibe":"full-day queer Golden Circle excursion during Reykjavík Pride","intel":{"hours":"Friday 6 August 2027; advertised as a full-day trip of approximately seven hours, with lunch included.","entry_wait":"Reserve directly with Pink Iceland. The exact Reykjavík pickup point and itinerary come with booking, so do not infer them from a map.","best_arrival":"Follow the confirmed pickup time exactly; this is a timed coach excursion rather than a drop-in Pride event.","crowd_mix":"LGBTQIA+ travellers, their friends, families and allies sharing a Pride-week nature trip in queer company.","dress_code":"Icelandic weather layers and walking-ready footwear are essential; bring gear for outdoor stops.","host_inclusivity":"Pink Iceland is queer-owned, and the trip is explicitly built around a welcoming Pride atmosphere for LGBTQIA+ guests.","lineup":"Guided Gay Golden Circle tour with lunch; detailed route is supplied by organiser.","age_limit":"Confirm with Pink Iceland.","source_urls":["https://www.pinkiceland.is/reykjavik-pride"],"research_status":"official_organiser_date_verified_pickup_pending","updated_at":"2026-09-26T00:00:00Z"}}
]
$qa_nordics_batch2$) e(name text, aliases jsonb, city text, date date, start_date date, end_date date, description text, link text, ticket_url text, location text, lat double precision, lng double precision, vibe text, intel jsonb)
), matched as (
  select s.*, candidate.id as existing_id
  from src s
  left join lateral (
    select e.id
    from public.events e
    where lower(trim(e.city)) = lower(trim(s.city))
      and (
        lower(regexp_replace(trim(e.name), '[^a-z0-9]+', '', 'gi')) = lower(regexp_replace(trim(s.name), '[^a-z0-9]+', '', 'gi'))
        or exists (select 1 from jsonb_array_elements_text(s.aliases) a where lower(regexp_replace(trim(e.name), '[^a-z0-9]+', '', 'gi')) = lower(regexp_replace(trim(a), '[^a-z0-9]+', '', 'gi')))
        or (e.start_date = s.start_date and lower(nullif(trim(e.link), '')) in (lower(s.link), lower(s.ticket_url)))
      )
    order by e.updated_at desc nulls last
    limit 1
  ) candidate on true
), updated as (
  update public.events e
  set name=s.name, description=s.description, link=s.link, ticket_url=s.ticket_url,
      date=s.date, start_date=s.start_date, end_date=s.end_date, location=s.location,
      lat=s.lat, lng=s.lng, vibe=s.vibe, vibe_tags=array[]::text[], event_intel=s.intel,
      seo_indexable=true, seo_quality_status='approved', updated_at=timezone('utc', now())
  from matched s where e.id=s.existing_id returning e.id
)
insert into public.events(name, city, description, link, ticket_url, date, start_date, end_date, location, lat, lng, vibe, vibe_tags, event_intel, seo_indexable, seo_quality_status, updated_at)
select name, city, description, link, ticket_url, date, start_date, end_date, location, lat, lng, vibe, array[]::text[], intel, true, 'approved', timezone('utc', now())
from matched where existing_id is null;

do $qa_nordics_batch2_guard$
begin
  if exists (
    select 1 from public.events
    where event_intel->>'updated_at' = '2026-09-26T00:00:00Z'
      and (coalesce(trim(description),'') = '' or coalesce(trim(location),'') = '' or jsonb_array_length(coalesce(event_intel->'source_urls','[]'::jsonb)) = 0)
  ) then
    raise exception 'Nordic batch 2 event missing required editorial data';
  end if;
end;
$qa_nordics_batch2_guard$;

commit;
