-- Queer Atlas: verified queer and queer-friendly electronic events, Batch 2.
-- Countries: Portugal, United Kingdom, Spain and France. Researched 2026-08-29.
--
-- Queer-led events are labelled as such. Broader electronic events are included
-- only when the organiser publishes meaningful consent, safer-space or explicit
-- anti-discrimination rules. No inferred annual dates are imported.
--
-- VIBE-TAG SAFETY: source data has no vibe_tags property. Both UPDATE and INSERT
-- write ARRAY[]::text[] directly, so this migration cannot introduce any value
-- rejected by qa_events_vibe_tags_allowed.

begin;

alter table if exists public.events
  add column if not exists event_intel jsonb not null default '{}'::jsonb;

alter table if exists public.events
  add column if not exists ticket_url text;

with src as (
  select * from jsonb_to_recordset($qa_western_europe_batch2_events$
[
{"name":"Porto Pride 2026","aliases":["Porto Pride Festival 2026"],"city":"porto","date":"2026-09-11","start_date":"2026-09-11","end_date":"2026-09-13","description":"Porto Pride's official three-day programme combines an equality summit, a free public festival, PINK Club afterparty, drag brunch and Pride boat experience.","link":"https://portopride.com/en/","ticket_url":"https://portopride.com/en/","location":"Largo Amor de Perdição and multiple venues, Porto, Portugal","lat":41.1457,"lng":-8.6167,"vibe":"three-day community Pride moving from policy and public culture into queer nightlife","intel":{"entry_wait":"The outdoor festival is free, while the summit, afterparty, brunch and boat use separate capacities or booking routes on the official programme.","best_arrival":"Use each programme item's stated doors; reach Largo Amor de Perdição early on Saturday and allow transfer time to PINK Club afterward.","crowd_mix":"Porto's LGBTQIA+ communities, organisations, artists, families, visitors and allies meet across civic, daytime and nightlife formats.","dress_code":"No festival-wide code applies; practical Pride clothing suits the outdoor programme and expressive clubwear fits the official afterparty.","host_inclusivity":"Porto Pride is the official queer organiser and European Pride Organisers Association member, with equality and community visibility central.","source_urls":["https://portopride.com/en/"],"research_status":"official_full_programme_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Queer Porto 12","aliases":["Queer Porto 2026","12th Queer Porto"],"city":"porto","date":"2026-11-03","start_date":"2026-11-03","end_date":"2026-11-07","description":"The twelfth Queer Porto presents LGBTQIA+ cinema and community programming at Batalha, Casa Comum, Passos Manuel and Bar of Soap from 3–7 November.","link":"https://www.queerporto.pt/en/2026-editions/queer-porto/venues-and-tickets","ticket_url":"https://www.queerporto.pt/en/2026-editions/queer-porto/venues-and-tickets","location":"Batalha Centro de Cinema and multiple venues, Porto, Portugal","lat":41.1463,"lng":-8.6069,"vibe":"intimate citywide queer cinema festival with screenings, conversation and social space","intel":{"entry_wait":"Batalha sessions use five-euro tickets with concessions; Casa Comum and Bar of Soap are free, while Passos Manuel sells from one hour before.","best_arrival":"Reach each venue before its published screening time, especially Passos Manuel where same-day sales begin only one hour before the session.","crowd_mix":"Queer film audiences, filmmakers, students, activists, international visitors and Porto cultural communities share the five-day programme.","dress_code":"Everyday cinema clothing is appropriate; opening, closing and social sessions may invite a polished look but publish no mandatory code.","host_inclusivity":"The festival explicitly centres LGBTQIA+ cinema and publishes a code of conduct covering welcome, accessibility, inclusion and removal for violations.","source_urls":["https://queerlisboa.pt/en","https://www.queerporto.pt/en/2026-editions/queer-porto/venues-and-tickets","https://www.queerlisboa.pt/en/festivals/code-of-conduct-and-regulations"],"research_status":"official_dates_venues_and_policy_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Alienação – Desterro #39","aliases":["Alienacao Desterro 39"],"city":"lisbon","date":"2026-09-19","start_date":"2026-09-19","end_date":"2026-09-20","description":"Alienação returns to Desterro from 22:00–04:30 with techno and trance from beanslut, Phasos and João Melgueira; the lineup links Lisbon underground sound with sapphic party culture.","link":"https://ra.co/events/2518975","ticket_url":"https://ra.co/events/2518975","location":"Desterro, Calçada do Desterro 7, 1150-125 Lisbon, Portugal","lat":38.7208,"lng":-9.1356,"vibe":"small underground techno and trance night with a queer-scene creative connection","intel":{"entry_wait":"The listing specifies door sales rather than advance tickets, so arrive early with identification and do not depend on late remaining capacity.","best_arrival":"Arrive near the 22:00 opening for the calmest entry and the full progression through the three advertised artist sets.","crowd_mix":"Lisbon underground dancers and queer-club followers meet around a lineup including beanslut, co-founder of a local sapphic party.","dress_code":"No formal dress code is published; compact, expressive and dance-ready clothing fits Desterro's intimate underground setting.","host_inclusivity":"This is queer-adjacent rather than queer-exclusive; its strongest community signal is the sapphic-party authorship represented in the lineup.","source_urls":["https://ra.co/events/2518975"],"research_status":"ticketing_and_artist_context_verified_queer_adjacent","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Lisbon Bear Pride 2027","aliases":["Lisbon Bear Pride XXIII","LBP 2027"],"city":"lisbon","date":"2027-05-24","start_date":"2027-05-24","end_date":"2027-05-30","description":"Lisbon Bear Pride's official 2027 edition runs 24–30 May with seven days of bear-community social events, parties and city experiences across Lisbon.","link":"https://www.lisbonbearpride.com/","ticket_url":"https://www.lisbonbearpride.com/","location":"Multiple venues, Lisbon, Portugal","lat":38.7223,"lng":-9.1393,"vibe":"week-long international bear gathering combining sociable daytime plans and nightlife","intel":{"entry_wait":"The week uses an organiser pass and event-specific instructions; book accommodation and the official package early rather than relying on door access.","best_arrival":"Plan around the final daily programme and arrive in Lisbon before the opening activity to collect any pass or participant information calmly.","crowd_mix":"Local and visiting bears, cubs, admirers and friends form an adult gay-community gathering with a strong international component.","dress_code":"Most social events are casual, while individual parties may suggest themed looks; follow the organiser's final programme for each venue.","host_inclusivity":"The event explicitly centres the bear community and its admirers; guests should review each adult nightlife format before booking.","source_urls":["https://www.lisbonbearpride.com/"],"research_status":"official_2027_dates_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"TRADES","aliases":["TRADES at M.O.T"],"city":"london","date":"2026-09-11","start_date":"2026-09-11","end_date":"2026-09-12","description":"TRADES brings a Black queer global-club programme to M.O.T from 23:00–06:00, moving through afro-electronica, ghetto-tech and percussive dance music.","link":"https://ra.co/events/2509295","ticket_url":"https://ra.co/events/2509295","location":"M.O.T, Orion Business Centre, Surrey Canal Road, London SE14 5RT, United Kingdom","lat":51.4787,"lng":-0.0515,"vibe":"Black queer global-club pressure with fast percussion and community-first energy","intel":{"entry_wait":"The listing carries low-cost advance tiers and warns that the night may sell out; buy before travel and bring valid 18+ identification.","best_arrival":"Arrive during the first hour to clear the compact venue entrance and experience the complete arc before the room reaches peak density.","crowd_mix":"Black queer Londoners and global-club dancers are centred, alongside respectful guests drawn to afro-electronic and percussive sounds.","dress_code":"No mandatory outfit is stated; expressive, sweat-ready queer clubwear suits the music and the intimate industrial room.","host_inclusivity":"The promoter explicitly frames TRADES as a Black queer club space rather than a generic electronic night.","source_urls":["https://ra.co/events/2509295"],"research_status":"organiser_ticketing_verified_queer_centred","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Club Boots Vol. II","aliases":["Club Boots Volume 2"],"city":"london","date":"2026-09-11","start_date":"2026-09-11","end_date":"2026-09-12","description":"Club Boots returns to The Glove That Fits from 22:00–04:00 for a compact queer underground night spanning house, techno and leftfield club music.","link":"https://ra.co/events/2501720","ticket_url":"https://ra.co/events/2501720","location":"The Glove That Fits, 179 Morning Lane, London E9 6JY, United Kingdom","lat":51.5465,"lng":-0.0521,"vibe":"close-quarters queer underground club night moving between house and techno","intel":{"entry_wait":"The 18+ basement has limited capacity, making advance purchase and an early arrival safer than relying on a late door allocation.","best_arrival":"Reach Morning Lane close to 22:00 for the easiest entry and time to settle before the small dance floor becomes busiest.","crowd_mix":"Queer east-London clubbers, underground electronic listeners, artists and friends gather in a deliberately intimate setting.","dress_code":"No mandatory code is published; a personal, dance-ready queer club look is more useful than elaborate clothing in the compact room.","host_inclusivity":"The event is explicitly presented as queer underground nightlife, with community and music taking priority over large-club spectacle.","source_urls":["https://ra.co/events/2501720"],"research_status":"organiser_ticketing_verified_queer_centred","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Satiate","aliases":["Satiate at radial"],"city":"london","date":"2026-09-13","start_date":"2026-09-13","end_date":"2026-09-13","description":"Satiate stages a ten-hour, music-first queer day party at radial from 13:00–23:00, with house and techno and proceeds supporting gender-affirming care and LGBTQI causes.","link":"https://ra.co/events/2515817","ticket_url":"https://ra.co/events/2515817","location":"radial, London, United Kingdom","lat":51.5074,"lng":-0.1278,"vibe":"long-form queer house and techno day party with a mutual-aid purpose","intel":{"entry_wait":"Accessible ticket tiers run from five to twenty pounds; advance booking supports the fundraiser and avoids depending on remaining day-of capacity.","best_arrival":"Come early in the afternoon for a calmer entrance and the intended ten-hour musical journey rather than treating it as a late club arrival.","crowd_mix":"Queer dancers, allies, DJs and community supporters gather around music, affordability and fundraising for gender-affirming and LGBTQI causes.","dress_code":"There is no published costume rule; comfortable daytime-to-night dancewear is the practical choice for a ten-hour programme.","host_inclusivity":"The organiser explicitly describes a music-first queer party and directs nonprofit proceeds toward gender-affirming care and LGBTQI charities.","source_urls":["https://ra.co/events/2515817"],"research_status":"organiser_ticketing_and_fundraising_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"SERVE Day Edition","aliases":["SERVE at Algha's Plantroom"],"city":"london","date":"2026-09-19","start_date":"2026-09-19","end_date":"2026-09-19","description":"SERVE hosts a ten-hour day-to-night session at Algha's Plantroom from 13:00–23:00, foregrounding queer artists and a music-first community atmosphere.","link":"https://ra.co/events/2415540","ticket_url":"https://ra.co/events/2415540","location":"Algha's Plantroom, London, United Kingdom","lat":51.5074,"lng":-0.1278,"vibe":"daylight queer club gathering built for long sets, connection and collective release","intel":{"entry_wait":"Use the official advance ticket route and check the organiser update before travel because the specialist venue has finite capacity.","best_arrival":"Arrive in the opening portion for orientation and the complete musical build; this is designed as a day-long session, not only a late peak.","crowd_mix":"Queer artists, London dancers, creative communities and respectful electronic-music listeners share an intentionally social floor.","dress_code":"No mandatory code is advertised; expressive but comfortable clothing works best for an extended daytime and evening dance.","host_inclusivity":"The programme explicitly foregrounds queer artists and community, distinguishing it from a merely queer-friendly general club listing.","source_urls":["https://ra.co/events/2415540"],"research_status":"organiser_ticketing_verified_queer_centred","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"HOMOSTASH 12th Anniversary","aliases":["Homostash 12 Years"],"city":"london","date":"2026-09-26","start_date":"2026-09-26","end_date":"2026-09-27","description":"HOMOSTASH celebrates twelve years at Colours Hoxton from 21:30–03:30 with house, disco and techno in its moustache-loving, gender-inclusive queer community.","link":"https://ra.co/events/2507336","ticket_url":"https://ra.co/events/2507336","location":"Colours Hoxton, 2–4 Hoxton Square, London N1 6NU, United Kingdom","lat":51.5274,"lng":-0.0814,"vibe":"playful inclusive queer anniversary party crossing disco, house and techno","intel":{"entry_wait":"Advance prices rise by tier from nine to twenty pounds; book early and bring valid identification for the venue's 18+ entry.","best_arrival":"Arrive near 21:30 for the anniversary opening and easier access before Hoxton's Saturday-night queues build.","crowd_mix":"LGBTQ+ Londoners, moustache enthusiasts, visitors and allies of all genders form a playful, deliberately inclusive audience.","dress_code":"A moustache is the party's signature playful motif but not a published barrier; colourful, expressive clubwear is welcome.","host_inclusivity":"HOMOSTASH explicitly presents itself as an open queer party for everyone, with identity, play and community at its centre.","source_urls":["https://ra.co/events/2507336"],"research_status":"organiser_ticketing_verified_queer_centred","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"London Trans+ Pride Fundraver","aliases":["London Trans Pride Fundraver"],"city":"london","date":"2026-09-06","start_date":"2026-09-06","end_date":"2026-09-06","description":"London Trans+ Pride's official fundraver takes over Hackney Bridge from 16:00–22:00 with INFERNO, Queer House Party, Filth and Bumpah across techno, ambient and club sounds.","link":"https://ra.co/events/2506233","ticket_url":"https://ra.co/events/2506233","location":"Hackney Bridge, Units 1–28 Echo Building, London E15 2SJ, United Kingdom","lat":51.5447,"lng":-0.0208,"vibe":"trans-led fundraiser joining queer collectives for an energetic Sunday rave","intel":{"entry_wait":"Buy through the official listing so the fundraiser receives support; bring valid identification and allow time for the multi-space venue check.","best_arrival":"Arrive near 16:00 to hear the full collective programme and enjoy the outdoor-to-evening transition before the main crowd peaks.","crowd_mix":"Trans+ people are centred, alongside queer communities, collective regulars, supporters and respectful allies attending the fundraiser.","dress_code":"No mandatory dress code is published; expressive, weather-aware dancewear works for the daytime start and evening finish.","host_inclusivity":"The event directly funds London Trans+ Pride and is programmed by established queer and trans-led nightlife collectives.","source_urls":["https://ra.co/events/2506233","https://londontranspride.org/"],"research_status":"organiser_and_ticketing_verified_trans_centred","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"The Coast Is Queer 2026","aliases":["Coast Is Queer 2026","Brighton Queer Literature Festival 2026"],"city":"brighton","date":"2026-10-15","start_date":"2026-10-15","end_date":"2026-10-18","description":"The Coast Is Queer returns to Brighton from 15–18 October as a dedicated LGBTQ+ literature festival of readings, conversations, workshops and community exchange.","link":"https://coastisqueer.com/","ticket_url":"https://coastisqueer.com/","location":"Brighton cultural venues, Brighton, United Kingdom","lat":50.8225,"lng":-0.1372,"vibe":"thoughtful queer literature weekend joining writers, readers and community voices","intel":{"entry_wait":"Individual talks and workshops may have separate capacities, so reserve priority sessions once the official programme and ticket links are released.","best_arrival":"Build a session-by-session route from the final timetable and reach each venue before its stated seating or workshop check-in time.","crowd_mix":"LGBTQ+ writers, readers, publishers, students, activists, Brighton residents and visitors create an intergenerational cultural audience.","dress_code":"There is no dress code; comfortable everyday clothing suits talks, readings and movement between festival venues.","host_inclusivity":"The festival is explicitly dedicated to queer literature and positions LGBTQ+ authorship, stories and discussion at its core.","source_urls":["https://coastisqueer.com/"],"research_status":"official_2026_dates_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Trans Pride Brighton 2027","aliases":["Trans Pride Brighton & Hove 2027"],"city":"brighton","date":"2027-07-17","start_date":"2027-07-17","end_date":"2027-07-17","description":"Trans Pride Brighton & Hove has officially announced its 2027 community Pride day for 17 July, continuing its trans-led programme of visibility, solidarity and celebration.","link":"https://transpridebrighton.org/","ticket_url":"https://transpridebrighton.org/","location":"Brighton and Hove, United Kingdom","lat":50.8225,"lng":-0.1372,"vibe":"grassroots trans-led Pride day combining protest, community care and celebration","intel":{"entry_wait":"The central Pride programme is community-focused; monitor official updates for any separately ticketed indoor or afterparty elements.","best_arrival":"Use the final march and venue information when published and reach the announced assembly point well before the stated departure time.","crowd_mix":"Trans, non-binary and intersex people are centred, with friends, families, community groups and allies joining in solidarity.","dress_code":"There is no mandatory code; expressive Pride clothing, comfortable footwear and weather protection are the useful choices.","host_inclusivity":"The event is trans-led and explicitly created around trans community visibility, safety, solidarity and public celebration.","source_urls":["https://transpridebrighton.org/"],"research_status":"official_2027_date_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Climax Clique","aliases":["Climax Clique at Lakota"],"city":"bristol","date":"2026-09-06","start_date":"2026-09-06","end_date":"2026-09-06","description":"Climax Clique returns to Lakota from 15:00–22:00 with a FLINTA-forward club programme, furnished playroom, decompression spaces and DJs from the inclusive Embody crew.","link":"https://ra.co/events/2511406","ticket_url":"https://ra.co/events/2511406","location":"Lakota, 6 Upper York Street, Bristol BS2 8QN, United Kingdom","lat":51.4623,"lng":-2.5907,"vibe":"FLINTA-forward sensual Sunday club with dance, play and deliberate aftercare","intel":{"entry_wait":"This is a members event and each member may bring two guests; complete membership and ticket arrangements before arriving at the 18+ door.","best_arrival":"Arrive near 15:00 for a gentle orientation through the lounge, playroom and softness suite before the dance programme intensifies.","crowd_mix":"FLINTA guests are foregrounded, with members and invited friends seeking expression away from the cis-male gaze.","dress_code":"No single outfit is prescribed; sensual or expressive clothing is welcome, but personal comfort and consent boundaries come first.","host_inclusivity":"The event centres FLINTA guests and explicitly describes joyful, inclusive, connected dance floors with grounding and aftercare space.","source_urls":["https://ra.co/events/2511406"],"research_status":"organiser_ticketing_and_access_model_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Canton Pride 2026","aliases":["Canton Pride Cardiff 2026"],"city":"cardiff","date":"2026-09-04","start_date":"2026-09-04","end_date":"2026-09-06","description":"Community-run Canton Pride fills west Cardiff with three days of LGBTQ+ music, film, art, wellbeing and club programming, with most events free or pay what you can.","link":"https://www.cantonpride.org/","ticket_url":"https://www.cantonpride.org/","location":"Chapter, St John's Church, The Corp and multiple Canton venues, Cardiff, United Kingdom","lat":51.4845,"lng":-3.2028,"vibe":"grassroots neighbourhood Pride combining Welsh queer culture, wellbeing and nightlife","intel":{"entry_wait":"Most programme items are free or pay what you can, but venue capacities differ; reserve any bookable sessions and arrive early for popular performances.","best_arrival":"Use the organiser's daily venue schedule; Friday evening begins at St John's Church before the launch party at The Corp.","crowd_mix":"Cardiff LGBTQ+ residents, Welsh artists, families, young people, wellbeing groups, local neighbours and allies share the weekend.","dress_code":"No festival-wide code applies; weather-ready casual Pride clothing works by day and expressive looks suit the club programme.","host_inclusivity":"Canton Pride is community-run, explicitly LGBTQ+ and designed around affordable access, local culture and a welcoming neighbourhood atmosphere.","source_urls":["https://www.cantonpride.org/","https://www.chapter.cymru/whats-on/tom-rasmussen"],"research_status":"official_full_programme_and_venue_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"DRIP","aliases":["DRIP Glasgow September 2026"],"city":"glasgow","date":"2026-09-04","start_date":"2026-09-04","end_date":"2026-09-05","description":"DRIP brings high-energy techno, Chicago house and global queer club sounds to The Berkeley Suite from 23:00–04:00, with Ariel Zetina, CUZINO, NWANNEKA and 3MR.","link":"https://ra.co/events/2476714","ticket_url":"https://ra.co/events/2476714","location":"The Berkeley Suite, 237 North Street, Glasgow G3 7DL, United Kingdom","lat":55.8650,"lng":-4.2740,"vibe":"BIPOC- and trans-prioritising queer club night with strict privacy and consent","intel":{"entry_wait":"A ticket does not guarantee entry because the team protects the room's safety; bring ID, expect bag checks and contact them for limited community tickets.","best_arrival":"Arrive near 23:00 for the door process and chill-area orientation before the compact basement reaches its busiest point.","crowd_mix":"Queer Glasgow is centred with priority care for BIPOC and trans guests, alongside respectful dancers who understand the safer-space rules.","dress_code":"No compulsory look is published; expressive clubwear is welcome, while behaviour, consent and respect matter at the door.","host_inclusivity":"DRIP publishes zero tolerance for harassment, mandatory consent, pronoun awareness, no-camera privacy and priority community tickets.","source_urls":["https://ra.co/events/2476714"],"research_status":"organiser_ticketing_and_safer_space_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Scottish Queer International Film Festival 2026","aliases":["SQIFF 2026"],"city":"glasgow","date":"2026-10-19","start_date":"2026-10-19","end_date":"2026-10-24","description":"SQIFF returns to Glasgow from 19–24 October with international queer cinema, accessible screenings, discussion and community programming.","link":"https://www.sqiff.org/","ticket_url":"https://www.sqiff.org/","location":"Glasgow cinemas and cultural venues, Glasgow, United Kingdom","lat":55.8642,"lng":-4.2518,"vibe":"accessible international queer film festival with conversation and community focus","intel":{"entry_wait":"Book individual screenings and access requirements through the final programme, as capacities and ticket models vary between partner venues.","best_arrival":"Reach each named venue before its advertised access and seating time, allowing for travel between screenings across Glasgow.","crowd_mix":"Queer filmmakers, cinema audiences, activists, disabled community members, students and international visitors share the festival.","dress_code":"There is no dress code; comfortable cinema clothing and practical layers are appropriate for moving between autumn venues.","host_inclusivity":"SQIFF explicitly centres queer film and is known for detailed access information, inclusive screening formats and community participation.","source_urls":["https://www.sqiff.org/"],"research_status":"official_2026_dates_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"EAT ME: The Wedding","aliases":["EAT ME The Wedding"],"city":"liverpool","date":"2026-09-25","start_date":"2026-09-25","end_date":"2026-09-26","description":"Award-winning queer drag cabaret and disco party EAT ME stages its chaotic wedding edition at District from 19:30–01:00.","link":"https://ra.co/events/2509250","ticket_url":"https://ra.co/events/2509250","location":"District, 61 Jordan Street, Liverpool L1 0BW, United Kingdom","lat":53.3952,"lng":-2.9806,"vibe":"theatrical queer wedding cabaret turning into an irreverent late disco","intel":{"entry_wait":"Use the advance listing for this finite-capacity cabaret and club event, then arrive before the 19:30 performance start for ticket checks.","best_arrival":"Be inside before showtime to experience the complete narrative cabaret before the room shifts into its queer disco phase.","crowd_mix":"Liverpool's queer cabaret audience, drag fans, performers' communities and playful nightlife guests make up the room.","dress_code":"Wedding-guest glamour, bridal satire and fancy clothing fit the theme, though the listing does not state a compulsory audience costume.","host_inclusivity":"EAT ME is explicitly a queer drag cabaret and disco party with queer performance, humour and community authorship at its centre.","source_urls":["https://ra.co/events/2509250"],"research_status":"organiser_listing_verified_queer_centred","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Outburst Queer Arts Festival 2026","aliases":["Outburst 2026","Outburst 20th Anniversary"],"city":"belfast","date":"2026-11-12","start_date":"2026-11-12","end_date":"2026-11-21","description":"Belfast's Outburst marks its twentieth anniversary with a city programme of queer performance, visual art, film, ideas and international exchange from 12–21 November.","link":"https://www.outburstarts.com/","ticket_url":"https://www.outburstarts.com/","location":"Ulster University and multiple venues, Belfast, United Kingdom","lat":54.6037,"lng":-5.9286,"vibe":"international queer arts festival mixing performance, film, ideas and Belfast community","intel":{"entry_wait":"Individual shows, talks and installations have different ticket and capacity rules; reserve headline performances after the full programme launches.","best_arrival":"Build a venue-by-venue itinerary from the organiser schedule and reach Ulster University or each partner space before its stated start.","crowd_mix":"Queer artists, Belfast communities, students, cultural workers, international guests and allies meet across artistic disciplines.","dress_code":"There is no festival-wide code; everyday arts-venue clothing works, with more expressive looks natural for evening performances.","host_inclusivity":"Outburst is explicitly a queer arts organisation and festival, centring LGBTQ+ creativity, critical conversation and international exchange.","source_urls":["https://www.outburstarts.com/","https://www.ulster.ac.uk/ulsterpresents/whats-on/2026-27/outburst-queer-arts-festival"],"research_status":"organiser_and_university_dates_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"KINYXX Mansion Fetish Edition","aliases":["KINYXX pres: Mansion Fetish Edition"],"city":"barcelona","date":"2026-09-05","start_date":"2026-09-05","end_date":"2026-09-06","description":"KINYXX takes over Atlantic Club from midnight–06:00 for a queer house and techno night with performances, a mandatory fetish dress code and explicit consent rules.","link":"https://ra.co/events/2500683","ticket_url":"https://ra.co/events/2500683","location":"Atlantic Club, Avinguda del Tibidabo 56, 08035 Barcelona, Spain","lat":41.4157,"lng":2.1316,"vibe":"immersive queer fetish mansion party balancing house, techno and radical expression","intel":{"entry_wait":"Advance booking is strongly advised for the promoted 18+ event; bring identification and expect the mandatory fetish look to be checked at the door.","best_arrival":"Arrive close to midnight for a calmer entry and time to understand the mansion layout, performance areas and consent expectations.","crowd_mix":"Barcelona's queer, fetish and electronic communities mix with performers and open-minded visitors inside an explicitly inclusive party.","dress_code":"Fetish wear is mandatory: the organiser lists black, latex, harnesses, leather, PVC, lingerie, mesh, drag, gothic and fantasy looks among options.","host_inclusivity":"KINYXX publishes equality across age, body, faith, race and gender, zero tolerance for phobias and clear permission-before-touching rules.","source_urls":["https://ra.co/events/2500683"],"research_status":"organiser_ticketing_dress_and_consent_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Ne/Re/A + Carol Nyx","aliases":["Ne Re A and Carol Nyx"],"city":"barcelona","date":"2026-09-09","start_date":"2026-09-09","end_date":"2026-09-10","description":"Brooklyn-based techno artist and queer MERGE resident Ne/Re/A plays Barcelona's Moog Club from midnight to 05:00 with Carol Nyx.","link":"https://ra.co/events/2504052","ticket_url":"https://ra.co/events/2504052","location":"Moog Club, Arc del Teatre 3, 08001 Barcelona, Spain","lat":41.3776,"lng":2.1744,"vibe":"focused midweek techno session led by an artist rooted in queer club culture","intel":{"entry_wait":"Advance RA tickets are available for the compact club; bring valid identification and arrive before midnight rather than relying on late capacity.","best_arrival":"Arrive during the opening window to hear the full set progression and avoid the tightest queue around the midnight start.","crowd_mix":"Barcelona techno regulars, queer-club followers and visitors drawn to Ne/Re/A's MERGE and international underground background attend.","dress_code":"No formal code is published; practical, compact clubwear suits Moog's small and energetic dance floor.","host_inclusivity":"This is queer-adjacent rather than queer-exclusive, led by an artist with a long residency at Brooklyn queer party MERGE.","source_urls":["https://ra.co/events/2504052"],"research_status":"ticketing_and_artist_context_verified_queer_adjacent","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Animalia x Fiesta x Fiesta","aliases":["Animalia x FxF"],"city":"madrid","date":"2026-09-05","start_date":"2026-09-05","end_date":"2026-09-06","description":"Fiesta x Fiesta and Naarm collective Animalia open Madrid's season with an extended secret-location session of minimal techno, dub, bass and psychedelia.","link":"https://ra.co/events/2509090","ticket_url":"https://ra.co/events/2509090","location":"Secret LFO.exp location disclosed to ticket holders, Madrid, Spain","lat":40.4168,"lng":-3.7038,"vibe":"extended queer-rooted underground session spanning techno, dub and bass","intel":{"entry_wait":"Venue details are emailed to ticket holders, so buy in advance, monitor the booking email and do not travel without the final location instructions.","best_arrival":"Follow the disclosed door time and route exactly; arrive near midnight to reduce navigation uncertainty and hear the full extended programme.","crowd_mix":"Fiesta x Fiesta's queer Madrid community meets Animalia followers and underground techno, dub and bass listeners.","dress_code":"No mandatory look is listed; intentional, comfortable club clothing suits the long secret-location session.","host_inclusivity":"Fiesta x Fiesta is a queer-rooted Madrid platform; the collaboration is community-led even though the listing is music-forward.","source_urls":["https://ra.co/events/2509090"],"research_status":"organiser_ticketing_verified_queer_rooted","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"KINYXX Madrid – Fetish Edition","aliases":["KINYXX Madrid Fetish Edition"],"city":"madrid","date":"2026-10-02","start_date":"2026-10-02","end_date":"2026-10-03","description":"KINYXX returns to Strong The Club from 23:00–06:00 with house and techno inside its queer fetish community space built around identity, expression and consent.","link":"https://ra.co/events/2511263","ticket_url":"https://ra.co/events/2511263","location":"Strong The Club, Calle de Trujillos 7, 28013 Madrid, Spain","lat":40.4183,"lng":-3.7064,"vibe":"queer fetish house and techno night combining freedom, performance and community","intel":{"entry_wait":"Purchase through the official listing, bring valid 18+ identification and expect the promoter to enforce its fetish-focused house rules at entry.","best_arrival":"Arrive near 23:00 for a calmer door, time to read the room and the complete progression from house into techno.","crowd_mix":"Queer and fetish communities, performers, house and techno dancers and open-minded visitors form the explicitly inclusive floor.","dress_code":"Treat the advertised fetish edition seriously and choose intentional fetish, dark, harness, latex, leather, mesh or similarly expressive attire.","host_inclusivity":"KINYXX describes the dance floor as a queer refuge based on diversity, authenticity, consent and freedom from phobia or judgement.","source_urls":["https://ra.co/events/2511263"],"research_status":"organiser_ticketing_and_house_rules_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Festival des Fiertés 2026","aliases":["Paris LGBTQIA+ Pride Cultures Festival 2026"],"city":"paris","date":"2026-11-06","start_date":"2026-11-06","end_date":"2026-11-22","description":"Paris's sixth Festival des Fiertés presents more than fifty free or bookable LGBTQIA+ exhibitions, readings, screenings and parties across the 11th–14th arrondissements.","link":"https://www.paris.fr/evenements/5e-edition-du-festival-des-fiertes-le-festival-des-cultures-et-identites-lgbtqia-89984","ticket_url":"https://www.paris.fr/evenements/5e-edition-du-festival-des-fiertes-le-festival-des-cultures-et-identites-lgbtqia-89984","location":"11th, 12th, 13th and 14th arrondissements, Paris, France","lat":48.8422,"lng":2.3496,"vibe":"large civic queer-culture programme spanning learning, art, film and nightlife","intel":{"entry_wait":"Most events are free but some require registration and individual venues have limited capacities; reserve priority sessions through their programme pages.","best_arrival":"Plan by arrondissement and venue rather than by festival day, allowing Paris travel time and arriving before each published session.","crowd_mix":"Paris LGBTQIA+ communities, neighbourhood residents, artists, activists, families, students and allies meet across more than fifty events.","dress_code":"No festival-wide code applies; everyday cultural-venue clothing works, with expressive evening looks fitting party and performance formats.","host_inclusivity":"The City of Paris and district partners explicitly centre LGBTQIA+ cultures, identities, rights history and anti-discrimination education.","source_urls":["https://www.paris.fr/evenements/5e-edition-du-festival-des-fiertes-le-festival-des-cultures-et-identites-lgbtqia-89984"],"research_status":"official_city_dates_and_scope_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"RAW XXS #15 – Secret Warehouse","aliases":["RAW XXS 15"],"city":"paris","date":"2026-10-03","start_date":"2026-10-03","end_date":"2026-10-04","description":"RAW stages an intimate secret-warehouse techno session near Paris from 23:00–07:00 with an unannounced lineup, no-phone floor and published inclusion and consent rules.","link":"https://ra.co/events/2494619","ticket_url":"https://ra.co/events/2494619","location":"Secret warehouse disclosed to ticket holders, Paris, France","lat":48.8566,"lng":2.3522,"vibe":"intimate secret-lineup techno with no-phone immersion and explicit safer-space rules","intel":{"entry_wait":"Capacity is deliberately limited and the address is secret; buy in advance, monitor ticket communication and bring identification for the 21+ door.","best_arrival":"Follow the final route and arrive near 23:00 to navigate the warehouse entry before the floor fills and the secret programme unfolds.","crowd_mix":"Dedicated techno listeners and open-minded queer-friendly dancers attend; this is inclusive electronic nightlife rather than a queer-exclusive party.","dress_code":"No costume is required; intentional black or underground clubwear fits, with phones kept away from the dance floor.","host_inclusivity":"RAW publishes respect, care, inclusion, consent and immediate exclusion for discriminatory, violent or disrespectful behaviour.","source_urls":["https://ra.co/events/2494619"],"research_status":"organiser_ticketing_and_inclusion_policy_verified_queer_friendly","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"NOGENDER Games – Angel Karel All Night Long","aliases":["NOGENDER ANGEL KAREL ANL","NOGENDER Games Lyon"],"city":"lyon","date":"2026-09-18","start_date":"2026-09-18","end_date":"2026-09-19","description":"NOGENDER returns to a secret Lyon location for an all-night Angel Karel industrial-techno set, performances, darkrooms and gender-free self-expression.","link":"https://ra.co/events/2499769","ticket_url":"https://ra.co/events/2499769","location":"Secret location disclosed to ticket holders, Lyon, France","lat":45.7640,"lng":4.8357,"vibe":"gender-free industrial techno refuge with performance, darkrooms and radical expression","intel":{"entry_wait":"Buy the listed advance ticket, await the secret location and bring valid 18+ identification; the organiser operates a values-led door.","best_arrival":"Follow the disclosed directions and arrive early enough for the entry conversation, venue orientation and complete all-night musical arc.","crowd_mix":"All genders, sexualities and origins are welcomed, with queer ravers, NOGENDER regulars, performers and industrial-techno listeners central.","dress_code":"Black is the published minimum and experimentation is encouraged; build an intentional dark, fetish or imaginative look rather than casual streetwear.","host_inclusivity":"NOGENDER explicitly welcomes all identities and foregrounds consent, listening, respect and intolerance of discriminatory behaviour.","source_urls":["https://ra.co/events/2499769"],"research_status":"organiser_ticketing_dress_and_consent_verified","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"disc·o·patio: The Unfolding Session","aliases":["Disco Patio The Unfolding Session"],"city":"lyon","date":"2026-09-26","start_date":"2026-09-26","end_date":"2026-09-27","description":"disc·o·patio returns to a two-level secret warehouse near Gorge de Loup from 18:00–06:00 for trance, techno, immersive staging and collective care.","link":"https://ra.co/events/2498336","ticket_url":"https://ra.co/events/2498336","location":"Secret warehouse near Gorge de Loup, Lyon, France","lat":45.7660,"lng":4.8056,"vibe":"immersive twelve-hour techno and trance gathering built around care and shared energy","intel":{"entry_wait":"Purchase before travel and monitor organiser messages for the secret address; allow time to reach the site by TCL and complete entry checks.","best_arrival":"Arrive during the early evening to explore both floors and the outdoor decompression area before the overnight section becomes busiest.","crowd_mix":"Lyon underground techno and trance dancers, visual-art audiences and queer-friendly guests meet in a community-oriented warehouse format.","dress_code":"No formal code is listed; layered, movement-ready clothing works across the raw indoor levels and the outdoor resting area.","host_inclusivity":"The organiser explicitly states that the team remains attentive so each person feels free, safe and respected on a care-led floor.","source_urls":["https://ra.co/events/2498336"],"research_status":"organiser_ticketing_and_care_policy_verified_queer_friendly","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Unité.22 – Yenkov Residency with TWIENA","aliases":["Yenkov Residency TWIENA Etienne Nogues"],"city":"marseille","date":"2026-09-12","start_date":"2026-09-12","end_date":"2026-09-13","description":"Yenkov hosts TWIENA and Etienne Nogues at Unité.22 from midnight–05:30 for playful techno, trance and acid-shaped club music with queer-scene lineage.","link":"https://ra.co/events/2522909","ticket_url":"https://ra.co/events/2522909","location":"Unité.22, 22 rue Jobin, 13003 Marseille, France","lat":43.3105,"lng":5.3914,"vibe":"playful high-energy techno and trance led by queer-club-connected artists","intel":{"entry_wait":"There is explicitly no box office at the venue, so only travel with a valid advance ticket and identification; entry remains reserved by the club.","best_arrival":"Reach rue Jobin before midnight to clear the door and hear Yenkov's opening before TWIENA and the closing set.","crowd_mix":"Marseille underground dancers, queer-club followers and listeners drawn to TWIENA's RAUM residency and Yenkov's local collective attend.","dress_code":"No mandatory code is published; expressive, lightweight clubwear fits the fast, physical techno and trance programme.","host_inclusivity":"This is queer-adjacent rather than queer-exclusive, with credible queer-club lineage through TWIENA's former RAUM residency.","source_urls":["https://ra.co/events/2522909"],"research_status":"ticketing_artist_and_venue_rules_verified_queer_adjacent","updated_at":"2026-08-29T00:00:00Z"}},
{"name":"Utopia Festival – Tome VI","aliases":["Utopia Festival 2026 Marseille"],"city":"marseille","date":"2026-09-25","start_date":"2026-09-25","end_date":"2026-09-27","description":"Utopia Festival fills Friche Belle de Mai for two nights of techno, house, bass and ambient from 21:30–06:00, joining emerging and international artists.","link":"https://ra.co/events/2329789","ticket_url":"https://ra.co/events/2329789","location":"Friche Belle de Mai, 41 rue Jobin, 13003 Marseille, France","lat":43.3104,"lng":5.3902,"vibe":"large multi-style electronic weekend with an intense but unifying dance-floor ethos","intel":{"entry_wait":"Day and weekend tickets range by tier; buy in advance and allow time for security and orientation inside the large multi-space Friche site.","best_arrival":"Check each night's running order and arrive before the first priority act, because overlapping rooms make late spontaneous navigation difficult.","crowd_mix":"Marseille electronic regulars, visiting festival audiences, younger club communities and queer-friendly dancers mix across multiple styles.","dress_code":"No formal code is published; practical festival clubwear, comfortable footwear and hearing protection suit two long nights.","host_inclusivity":"This is queer-friendly rather than queer-centred; its published framing emphasises collective, bright and unifying electronic culture.","source_urls":["https://ra.co/events/2329789"],"research_status":"organiser_ticketing_verified_queer_friendly","updated_at":"2026-08-29T00:00:00Z"}}
]
$qa_western_europe_batch2_events$) e(
    name text, aliases jsonb, city text, date date, start_date date, end_date date,
    description text, link text, ticket_url text, location text,
    lat double precision, lng double precision, vibe text, intel jsonb
  )
), matched as (
  select s.*, existing.id as existing_id
  from src s
  left join lateral (
    select candidate.id
    from public.events candidate
    where lower(trim(candidate.city)) = lower(trim(s.city))
      and (
        lower(regexp_replace(trim(candidate.name), '[^a-z0-9]+', '', 'gi')) =
          lower(regexp_replace(trim(s.name), '[^a-z0-9]+', '', 'gi'))
        or exists (
          select 1 from jsonb_array_elements_text(coalesce(s.aliases, '[]'::jsonb)) alias_name
          where lower(regexp_replace(trim(candidate.name), '[^a-z0-9]+', '', 'gi')) =
            lower(regexp_replace(trim(alias_name), '[^a-z0-9]+', '', 'gi'))
        )
        or (
          candidate.start_date = s.start_date
          and nullif(trim(candidate.link), '') is not null
          and lower(trim(candidate.link)) in (
            lower(trim(s.link)), lower(trim(coalesce(s.ticket_url, s.link)))
          )
        )
      )
    order by
      case when lower(trim(candidate.name)) = lower(trim(s.name)) then 0 else 1 end,
      candidate.updated_at desc nulls last
    limit 1
  ) existing on true
), updated as (
  update public.events target
  set name = m.name,
      description = m.description,
      link = m.link,
      ticket_url = m.ticket_url,
      date = m.date,
      start_date = m.start_date,
      end_date = m.end_date,
      location = m.location,
      lat = m.lat,
      lng = m.lng,
      vibe = m.vibe,
      vibe_tags = array[]::text[],
      event_intel = m.intel,
      seo_indexable = true,
      seo_quality_status = 'approved',
      updated_at = timezone('utc', now())
  from matched m
  where target.id = m.existing_id
  returning target.id
)
insert into public.events(
  name, city, description, link, ticket_url, date, start_date, end_date,
  location, lat, lng, vibe, vibe_tags, event_intel,
  seo_indexable, seo_quality_status, updated_at
)
select
  name, city, description, link, ticket_url, date, start_date, end_date,
  location, lat, lng, vibe, array[]::text[], intel,
  true, 'approved', timezone('utc', now())
from matched
where existing_id is null;

-- Fail closed if this batch produces a duplicate canonical event.
do $qa_no_western_europe_batch2_duplicates$
begin
  if exists (
    select 1
    from public.events
    where start_date >= date '2026-08-29'
      and event_intel->>'updated_at' = '2026-08-29T00:00:00Z'
    group by lower(trim(city)),
      lower(regexp_replace(trim(name), '[^a-z0-9]+', '', 'gi')),
      start_date
    having count(*) > 1
  ) then
    raise exception 'Western Europe Batch 2 duplicate detected; transaction rolled back.';
  end if;
end;
$qa_no_western_europe_batch2_duplicates$;

commit;
