-- Queer Atlas: verified queer events in Singapore, Costa Rica and Uruguay, batch 14.

begin;
alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists ticket_url text;

with src as (
  select * from jsonb_to_recordset($qa_batch14$
[
  {"name":"HAIR RAISER Halloween ft. Gottmik","aliases":["HAIR RAISER Halloween","HAIR RAISER Halloween ft. GOTTMIK (Drag Race) by FOMOHOMO & POOF DOOF","FOMOHOMO HAIR RAISER 2026"],"city":"singapore","date":"2026-10-24","start_date":"2026-10-24","end_date":"2026-10-25","description":"FOMOHOMO and POOF DOOF turn MDLR into a queer Halloween fever dream: Gottmik’s painted provocation, Jimi the Kween’s Australian club charge and Singapore drag in a late set that refuses to play background music.","link":"https://www.eventbrite.sg/e/hair-raiser-halloween-ft-gottmik-drag-race-by-fomohomo-poof-doof-tickets-2002153595300","ticket_url":"https://www.eventbrite.sg/e/hair-raiser-halloween-ft-gottmik-drag-race-by-fomohomo-poof-doof-tickets-2002153595300","location":"MDLR, 62 Cecil Street, Singapore 049710","lat":1.2828,"lng":103.8491,"vibe":"Singapore queer Halloween with Drag Race voltage, guest-DJ momentum and a transformed industrial room","intel":{"hours":"22:00 Saturday 24 October–03:30 Sunday 25 October 2026.","entry_wait":"This is an advance-ticketed FOMOHOMO and POOF DOOF date with a high-profile international guest; buy ahead instead of treating the door as dependable.","best_arrival":"Be there at 22:00 for the opening shape of the room and more breathing space before the headline drag-and-DJ crowd settles in.","crowd_mix":"Singapore LGBTQ+ nightlife regulars, regional queer travellers, Drag Race fans, local drag supporters and late-night dance-floor people.","dress_code":"No compulsory code is published; Halloween drag glamour, creature looks and practical dancing layers all make sense.","host_inclusivity":"FOMOHOMO is a Singapore queer-event producer; the listing centres drag performers and LGBTQ+ nightlife rather than a generic Halloween club booking.","lineup":"Gottmik (RuPaul's Drag Race S13 and All Stars 9), Jimi the Kween, local drag performers and DJs; full lineup pending.","age_limit":"21+.","source_urls":["https://www.eventbrite.sg/e/hair-raiser-halloween-ft-gottmik-drag-race-by-fomohomo-poof-doof-tickets-2002153595300","https://www.gaytravel4u.com/event/fomohomo-singapore-presents/"],"research_status":"ticketing_date_hours_full_address_age_and_headline_cast_verified;_full_local_lineup_pending","updated_at":"2026-09-28T00:00:00Z"}},
  {"name":"BABE: Halloween!","aliases":["BABE Halloween Costa Rica 2026","BABE: Halloween Edificio Steinvorth"],"city":"san_jose","date":"2026-10-31","start_date":"2026-10-31","end_date":"2026-11-01","description":"BABE takes over both halves of Edificio Steinvorth for Halloween: drag on the bill, two rooms in play and enough midnight shape-shifting to make the historic building feel less like architecture than an alibi.","link":"https://starticket.cr/en/e/babe-halloween/9948","ticket_url":"https://starticket.cr/en/e/babe-halloween/9948","location":"Edificio Steinvorth, Calle 1 and Avenida 0–1, San José, Costa Rica","lat":9.9341,"lng":-84.0780,"vibe":"San José queer Halloween takeover with drag shows, two rooms and a six-hour after-dark arc","intel":{"hours":"22:00 Saturday 31 October–06:00 Sunday 1 November 2026.","entry_wait":"The official ticket page has limited paid tiers; purchase before travelling and use the ticketing channel for current access details.","best_arrival":"Arrive near 22:00 to see both Music Hall and Steinroom before the drag-show crowd and late dance floor pull into their own orbits.","crowd_mix":"BABE's expressive, music-led community; drag-show audiences, costume crews and queer nightlife friends across San José.","dress_code":"Costumes are strongly on-theme but not listed as mandatory; choose something expressive that can survive a six-hour two-room night.","host_inclusivity":"BABE describes itself as a collective celebration of free expression and music, and its 2026 programme includes an official Pride after-party; this Halloween edition publishes drag shows as part of the format.","lineup":"Drag shows across Music Hall and Steinroom; individual performer roster is not published on the active ticket page.","age_limit":"Confirm the venue's current entry rule with the organiser before attending.","source_urls":["https://starticket.cr/en/e/babe-halloween/9948","https://starticket.cr/en/o/1949/babe-party","https://www.gamcultural.com/cr/p/edificiosteinvorth"],"research_status":"official_ticketing_date_hours_venue_format_and_address_verified;_performer_roster_pending","updated_at":"2026-09-28T00:00:00Z"}},
  {"name":"After Marcha — viajerosdisco","aliases":["After Marcha Montevideo 2026","After Marcha Viajeros Disco Pub"],"city":"montevideo","date":"2026-10-02","start_date":"2026-10-02","end_date":"2026-10-02","description":"After Marcha brings the march’s loose, bright momentum inside Viajeros: a post-demonstration queer reset where the point is not polish, but keeping the collective spark alive long after the route ends.","link":"https://www.gayout.com/south-america/uruguay/montevideo/events/after-marcha-2026-10-02","ticket_url":"https://www.gayout.com/south-america/uruguay/montevideo/events/after-marcha-2026-10-02","location":"Viajeros Disco Pub, Soriano 1340, 11100 Montevideo, Uruguay","lat":-34.9076,"lng":-56.1871,"vibe":"post-march Montevideo queer night in a two-level gay club with drag-stage history and late energy","intel":{"hours":"Friday 2 October 2026; exact door and closing times have not been published.","entry_wait":"Check viajerosdisco's current social channel before leaving: the event listing confirms the date and venue but not the door time or ticket procedure.","best_arrival":"Use the organiser's same-day update, then arrive early enough to orient yourself before the post-march crowd turns the room into its late-night mode.","crowd_mix":"March participants, local LGBTQ+ regulars, friends of the movement and travellers looking for a community-led rather than generic club night.","dress_code":"No dress code is published; march looks, badges and whatever feels celebratory and comfortable are the natural reading of the night.","host_inclusivity":"Viajeros is identified as a mixed LGBTQ+ gay club with drag shows, theme nights and a trans-friendly profile; the event is explicitly listed as an LGBTQ+ post-march gathering.","lineup":"Not announced.","age_limit":"Confirm current entry requirements with viajerosdisco.","source_urls":["https://www.gayout.com/south-america/uruguay/montevideo/events/after-marcha-2026-10-02","https://montevideo.gaycities.com/bars/312017-viajeros-disco","https://www.descubrimontevideo.uy/noche"],"research_status":"event_date_lgbtq_format_full_address_and_venue_context_verified;_hours_lineup_and_ticketing_pending","updated_at":"2026-09-28T00:00:00Z"}},
  {"name":"MO.VI.DA Fest","aliases":["MO.VI.DA Montevideo 2026","MO.VI.DA Fest Auditorio Nelly Goitiño"],"city":"montevideo","date":"2026-10-17","start_date":"2026-10-17","end_date":"2026-10-17","description":"MO.VI.DA gives Montevideo’s queer scene the proscenium it deserves: drag queens, transformistas, dancers, singers and a DJ taking a formal theatre somewhere much more alive — with part of the box office feeding back to Colectivo Trans Uruguay.","link":"https://sodre.gub.uy/espectaculos/mo-vi/","ticket_url":"https://sodre.gub.uy/espectaculos/mo-vi/","location":"Auditorio Nelly Goitiño, Sala Héctor Tosar, Avenida 18 de Julio 930, 11100 Montevideo, Uruguay","lat":-34.9053,"lng":-56.1871,"vibe":"queer Montevideo variety show: drag, performance, dance and DJ energy inside an intimate theatre","intel":{"hours":"19:00 Saturday 17 October 2026; closing time is not published.","entry_wait":"Use the official SODRE event page to confirm ticket release and seat availability; this is a theatre format, so do not assume a late walk-up is available.","best_arrival":"Arrive 20–30 minutes before 19:00 to settle into Sala Héctor Tosar and catch the programme from its theatrical opening.","crowd_mix":"Montevideo queer artists and supporters, drag and performance audiences, allies and people who want nightlife culture with an actual stage at its centre.","dress_code":"No requirement is published; expressive theatre-night dressing fits, but the room does not demand club armour.","host_inclusivity":"MO.VI.DA was created to showcase Montevideo's queer artists and visibly supports Colectivo Trans Uruguay through its proceeds — community purpose is built into the event, not added as decoration.","lineup":"Drag queens, transformistas, dancers, singers, actors, performances and DJ Paola Dalto; individual artist billing is published by the organisers as it is finalised.","age_limit":"Confirm with the official venue or ticket channel before attending.","source_urls":["https://sodre.gub.uy/espectaculos/mo-vi/","https://qlist.app/events/Montevideo/MOVIDA-Fest/42514/es"],"research_status":"official_date_start_time_full_address_queer_programme_and_charity_context_verified;_closing_time_and_final_artist_roster_pending","updated_at":"2026-09-28T00:00:00Z"}}
]
$qa_batch14$) e(name text,aliases jsonb,city text,date date,start_date date,end_date date,description text,link text,ticket_url text,location text,lat double precision,lng double precision,vibe text,intel jsonb)
), matched as (
  select s.*, x.id existing_id
  from src s
  left join lateral (
    select e.id from public.events e
    where lower(trim(e.city)) = lower(trim(s.city))
      and (
        lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi')) = lower(regexp_replace(trim(s.name),'[^a-z0-9]+','','gi'))
        or exists (select 1 from jsonb_array_elements_text(s.aliases) a where lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi')) = lower(regexp_replace(trim(a),'[^a-z0-9]+','','gi')))
        or (e.start_date = s.start_date and lower(nullif(trim(e.link),'')) in (lower(s.link), lower(s.ticket_url)))
      )
    limit 1
  ) x on true
), updated as (
  update public.events e
  set name=s.name, description=s.description, link=s.link, ticket_url=s.ticket_url, date=s.date, start_date=s.start_date, end_date=s.end_date, location=s.location, lat=s.lat, lng=s.lng, vibe=s.vibe, vibe_tags=array[]::text[], event_intel=s.intel, seo_indexable=true, seo_quality_status='approved', updated_at=timezone('utc', now())
  from matched s where e.id=s.existing_id
  returning e.id
)
insert into public.events(name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,event_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],intel,true,'approved',timezone('utc', now())
from matched where existing_id is null;

do $qa_batch14_guard$
begin
  if exists (
    select 1 from public.events
    where event_intel->>'updated_at'='2026-09-28T00:00:00Z'
      and (coalesce(trim(description),'')='' or coalesce(trim(location),'')='' or jsonb_array_length(coalesce(event_intel->'source_urls','[]'::jsonb))=0)
  ) then
    raise exception 'Singapore Costa Rica Uruguay batch missing editorial data';
  end if;
end;
$qa_batch14_guard$;
commit;
