-- Queer Atlas: verified Slovenia and Lithuania events, batch 12.

begin;
alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists ticket_url text;

with src as (
 select * from jsonb_to_recordset($qa_batch12$
[
{"name":"Odyssey","aliases":["Odyssey Ljubljana Klub K4 2026","Odyssey London collective Slovenia 2026"],"city":"ljubljana","date":"2026-10-16","start_date":"2026-10-16","end_date":"2026-10-17","description":"Odyssey lands in Ljubljana with London’s queer underground in its luggage: gothic glamour, EBM voltage, Italo sweat and a night built to make Klub K4 feel more like a fantasy than a venue.","link":"https://www.eventim.si/en/artist/odyssey/","ticket_url":"https://www.eventim.si/en/artist/odyssey/","location":"Klub K4, Kersnikova ulica 6, 1000 Ljubljana, Slovenia","lat":46.0575,"lng":14.5053,"vibe":"London queer underground meets Ljubljana: Italo disco, EBM, performance and refined gothic glamour","intel":{"hours":"23:00 Friday 16 October 2026; confirm closing time via the active Eventim ticket flow.","entry_wait":"Tickets start at €20 plus booking fee. Buy early for Odyssey’s first Slovenian edition rather than relying on a late walk-up.","best_arrival":"Arrive for 23:00 to catch the hosts and DJs before the club reaches its darker, denser EBM peak.","crowd_mix":"Ljubljana queer nightlife, fashion-forward electronic-music dancers, London Odyssey followers and guests drawn to performance-led club culture.","dress_code":"No compulsory code is published; club-ready gothic, Italo or expressive styling belongs naturally in the event’s queer fantasy world.","host_inclusivity":"Odyssey is presented as a London collective operating at the intersection of music, performance, fashion and queer culture, not merely as a generic electronic booking.","lineup":"Djedjotronic, Metallic Lover, Claudia Kane and Brother of Set.","age_limit":"Confirm with ticketing before attending.","source_urls":["https://www.eventim.si/en/artist/odyssey/"],"research_status":"official_ticketing_date_start_time_full_address_lineup_and_queer_collective_context_verified","updated_at":"2026-09-28T00:00:00Z"}},
{"name":"Queendom: Grand Drag Show — Devil’s Ball","aliases":["Queendom Devil's Ball Vilnius 2026","Queendom Grand Drag Show Lukiškių kalėjimas 2.0"],"city":"vilnius","date":"2026-10-31","start_date":"2026-10-31","end_date":"2026-10-31","description":"Queendom turns Lukiškės Prison 2.0 into a Halloween drag court: theatrical looks, high-camp menace and a one-night Devil’s Ball where the old cellblock gets a much better afterlife.","link":"https://www.bilietai.lt/en/tickets/XFYJQ2T4W4/queendom-grand-drag-show-lukiskiu-kalejimas-2-0","ticket_url":"https://www.bilietai.lt/en/tickets/XFYJQ2T4W4/queendom-grand-drag-show-lukiskiu-kalejimas-2-0","location":"Lukiškių kalėjimas 2.0, Lukiškių skersgatvis 6, 01108 Vilnius, Lithuania","lat":54.6898,"lng":25.2683,"vibe":"Vilnius Halloween drag court inside a former prison: grand looks, devilish theatre and queer camp release","intel":{"hours":"21:00–23:00 Saturday 31 October 2026.","entry_wait":"Use the official Bilietai ticket route and arrive with room for venue-entry procedures; ticket service charges may apply.","best_arrival":"Come before 21:00 to take in the transformed prison setting and settle before the staged drag programme begins.","crowd_mix":"Vilnius drag fans, queer Halloween crews, camp-performance audiences and guests drawn to the former prison’s dramatic setting.","dress_code":"No mandatory code is published, but Halloween’s Devil’s Ball framing rewards theatrical, spooky or glam styling.","host_inclusivity":"Queendom is explicitly billed as a grand drag show, placing queer performance—not generic nightlife—at the centre of the event.","lineup":"Grand drag-show programme; performer roster is released through the official ticketing channel.","age_limit":"Confirm with organiser before attending.","source_urls":["https://www.bilietai.lt/en/tickets/XFYJQ2T4W4/queendom-grand-drag-show-lukiskiu-kalejimas-2-0"],"research_status":"official_ticketing_date_hours_full_address_and_queer_drag_format_verified","updated_at":"2026-09-28T00:00:00Z"}}
]
$qa_batch12$) e(name text,aliases jsonb,city text,date date,start_date date,end_date date,description text,link text,ticket_url text,location text,lat double precision,lng double precision,vibe text,intel jsonb)
), matched as (
 select s.*,x.id existing_id from src s left join lateral(select e.id from public.events e where lower(trim(e.city))=lower(trim(s.city)) and (lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(s.name),'[^a-z0-9]+','','gi')) or exists(select 1 from jsonb_array_elements_text(s.aliases) a where lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(a),'[^a-z0-9]+','','gi'))) or (e.start_date=s.start_date and lower(nullif(trim(e.link),'')) in(lower(s.link),lower(s.ticket_url)))) limit 1)x on true
), updated as (
 update public.events e set name=s.name,description=s.description,link=s.link,ticket_url=s.ticket_url,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,vibe_tags=array[]::text[],event_intel=s.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from matched s where e.id=s.existing_id returning e.id
)
insert into public.events(name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,event_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],intel,true,'approved',timezone('utc',now()) from matched where existing_id is null;

do $qa_batch12_guard$
begin
 if exists(select 1 from public.events where event_intel->>'updated_at'='2026-09-28T00:00:00Z' and (coalesce(trim(description),'')='' or coalesce(trim(location),'')='' or jsonb_array_length(coalesce(event_intel->'source_urls','[]'::jsonb))=0)) then raise exception 'Slovenia Lithuania batch missing editorial data'; end if;
end;
$qa_batch12_guard$;
commit;
