-- Queer Atlas: verified Taiwan and India events, batch 13.
-- Kolkata and Badlapur are not currently city pages, so their events are stored in global_events.

begin;
alter table if exists public.events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.events add column if not exists ticket_url text;
alter table if exists public.global_events add column if not exists event_intel jsonb not null default '{}'::jsonb;
alter table if exists public.global_events add column if not exists ticket_url text;

with src as (
 select * from jsonb_to_recordset($qa_taiwan_events$
[
{"name":"CandyLand: Taipei Pride Techno","aliases":["CandyLand Taipei Pride 2026 Friday","CandyLand 30 October 2026 Red Space"],"city":"taipei","date":"2026-10-30","start_date":"2026-10-30","end_date":"2026-10-31","description":"CandyLand starts Taipei Pride weekend in the blur it deserves: hard-focus techno, soft-focus bodies and a consent-first floor where the only required reality is the kick drum.","link":"https://www.klook.com/zh-TW/activity/187645-candyland-x-backdoor/","ticket_url":"https://www.klook.com/zh-TW/activity/187645-candyland-x-backdoor/","location":"RED SPACE, B1, Fuxing North Road 15, Zhongshan District, Taipei, Taiwan","lat":25.0470,"lng":121.5444,"vibe":"Taipei Pride techno night with hazy bodies, sharp kicks and a consent-first queer floor","intel":{"hours":"23:00 Friday 30 October–05:00 Saturday 31 October 2026.","entry_wait":"Advance tiers run to 29 October; buy ahead for Pride weekend and arrive before midnight for a calmer entry.","best_arrival":"Come at 23:00 for the complete techno arc and room to orient yourself before the floor thickens.","crowd_mix":"Taipei LGBTQ+ dancers, Pride-week visitors, techno regulars and people looking for a deliberate alternative to generic circuit programming.","dress_code":"Optional; wear what feels good, with visually expressive looks encouraged.","host_inclusivity":"CandyLand and BackDoor state zero tolerance for harassment, racism, homophobia, sexism and bullying; consent is a stated rule.","lineup":"Terry x Fififlat B2B, Jamie Q and Pelatto.","age_limit":"Confirm with ticketing before attending.","source_urls":["https://www.klook.com/zh-TW/activity/187645-candyland-x-backdoor/"],"research_status":"ticketing_date_hours_full_address_lineup_and_consent_policy_verified","updated_at":"2026-09-28T00:00:00Z"}},
{"name":"CandyLand × BackDoor: Taipei Pride Techno & Circuit House","aliases":["CandyLand BackDoor Taipei Pride 2026 Saturday","BackDoor 31 October 2026 Red Space"],"city":"taipei","date":"2026-10-31","start_date":"2026-10-31","end_date":"2026-11-01","description":"CandyLand and BackDoor double the voltage for Taipei Pride: one night, two queer dance-floor instincts—dark techno pressure and circuit-house lift—with no need to pick a side.","link":"https://www.klook.com/zh-TW/activity/187645-candyland-x-backdoor/","ticket_url":"https://www.klook.com/zh-TW/activity/187645-candyland-x-backdoor/","location":"RED SPACE, B1, Fuxing North Road 15, Zhongshan District, Taipei, Taiwan","lat":25.0470,"lng":121.5444,"vibe":"two-mode Taipei Pride pressure: dark techno downstairs in spirit, circuit-house euphoria on top","intel":{"hours":"23:00 Saturday 31 October–05:00 Sunday 1 November 2026.","entry_wait":"Pride Saturday has separate advance and door pricing; pre-purchase rather than treating the door as reliable.","best_arrival":"Arrive at 23:00 to move through both musical modes before each crowd claims its peak-hour territory.","crowd_mix":"Taipei LGBTQ+ clubbers, circuit-house fans, techno dancers, Pride visitors and go-go-performance audiences.","dress_code":"Optional but expressive styling is encouraged; make the outfit breathable enough for a five-hour two-sound sprint.","host_inclusivity":"The co-hosts publish a consent-led, discrimination-free policy and state that offending guests may be removed.","lineup":"CandyLand: TBD, Pelatto, J6. BackDoor: Keefe, Isaac x K9999 B2B, PAT+ x Mango B2B.","age_limit":"Confirm with ticketing before attending.","source_urls":["https://www.klook.com/zh-TW/activity/187645-candyland-x-backdoor/"],"research_status":"ticketing_date_hours_full_address_lineup_and_consent_policy_verified","updated_at":"2026-09-28T00:00:00Z"}},
{"name":"X-Formosa: BLACK ARENA","aliases":["Formosa Pride Black Arena 2026","X-Formosa 30 October 2026"],"city":"taipei","date":"2026-10-30","start_date":"2026-10-30","end_date":"2026-10-31","description":"BLACK ARENA opens X-Formosa at full nocturnal scale: a black-clad gay music-festival main room that turns Taipei Pride weekend into a global after-dark meeting point.","link":"https://formosapride.com/en/2026/","ticket_url":"https://formosapride.com/en/2026/","location":"New Taipei City Exhibition Hall, next to Zepp New Taipei, New Taipei City, Taiwan","lat":25.0604,"lng":121.4568,"vibe":"black-clad global gay festival opener with circuit force, live show spectacle and Taiwan Pride gravity","intel":{"hours":"22:00 Friday 30 October–04:00 Saturday 31 October 2026.","entry_wait":"Single-night and multi-night passes are active; door sales pause at capacity, so buy ahead and carry required ID.","best_arrival":"Use 22:00 doors for the opening live show and lower security pressure before the festival reaches full density.","crowd_mix":"International gay travellers, Taiwan Pride participants, circuit fans and local LGBTQ+ nightlife communities.","dress_code":"Black.","host_inclusivity":"X-Formosa is explicitly a gay rainbow music festival staged alongside Taiwan Pride, with safety procedures and trained onsite staff.","lineup":"Live: ABUS. DJs: Stone Formosa, Danny Verde and Junyo.","age_limit":"18+; passport or valid ID required.","source_urls":["https://formosapride.com/en/2026/"],"research_status":"official_date_hours_venue_lineup_dress_code_age_and_ticketing_verified","updated_at":"2026-09-28T00:00:00Z"}},
{"name":"X-Formosa: WHITE EDEN","aliases":["Formosa Pride White Eden 2026","X-Formosa 31 October 2026"],"city":"taipei","date":"2026-10-31","start_date":"2026-10-31","end_date":"2026-11-01","description":"WHITE EDEN is X-Formosa’s Pride-Saturday release: white looks, international circuit rhythm and a post-parade floor engineered for people who have no interest in going home early.","link":"https://formosapride.com/en/2026/","ticket_url":"https://formosapride.com/en/2026/","location":"New Taipei City Exhibition Hall, next to Zepp New Taipei, New Taipei City, Taiwan","lat":25.0604,"lng":121.4568,"vibe":"white-clad Taiwan Pride Saturday: global circuit momentum after the parade","intel":{"hours":"21:30 Saturday 31 October–04:30 Sunday 1 November 2026.","entry_wait":"Door sales depend on capacity; purchase the White Eden pass in advance and plan for heightened post-parade demand.","best_arrival":"Arrive for 21:30 to reset from the parade and get inside before the international Pride surge.","crowd_mix":"Taiwan Pride marchers, global circuit travellers, local LGBTQ+ communities and performance-focused partygoers.","dress_code":"White.","host_inclusivity":"The event is part of X-Formosa’s LGBTQ+ Pride-week programme and publishes clear safety, security and ID procedures.","lineup":"Live: C.Holly and Afro Kombat 7. DJs: Arno Formosa, Danny Verde and Anne Louise.","age_limit":"18+; passport or valid ID required.","source_urls":["https://formosapride.com/en/2026/"],"research_status":"official_date_hours_venue_lineup_dress_code_age_and_ticketing_verified","updated_at":"2026-09-28T00:00:00Z"}},
{"name":"X-Formosa: WOOF Tea Dance","aliases":["Formosa Pride WOOF 2026","X-Formosa WOOF 1 November 2026"],"city":"taipei","date":"2026-11-01","start_date":"2026-11-01","end_date":"2026-11-01","description":"WOOF gives X-Formosa daylight teeth: a green-and-camo bear tea dance with big queer warmth, Brazilian disco drama and the kind of Sunday that refuses to be a comedown.","link":"https://formosapride.com/en/2026/","ticket_url":"https://formosapride.com/en/2026/","location":"New Taipei City Exhibition Hall, next to Zepp New Taipei, New Taipei City, Taiwan","lat":25.0604,"lng":121.4568,"vibe":"bear-centred Taipei Pride tea dance with daylight bravado, green/camo looks and generous Sunday release","intel":{"hours":"16:00–21:00 Sunday 1 November 2026.","entry_wait":"Single WOOF passes and door tickets are capacity-controlled; arrive early for an easier daytime check-in.","best_arrival":"Enter at 16:00 for the whole afternoon programme rather than only the final dance-floor rush.","crowd_mix":"Bear community, LGBTQ+ Pride visitors, local festival regulars and friends looking for an outdoor-feeling daytime queer social.","dress_code":"Green or camouflage.","host_inclusivity":"WOOF is one part of X-Formosa’s explicit LGBTQ+ festival programme, with 18+ ID checks and managed safety procedures.","lineup":"DJs Neil Formosa and Las Bibas From Vizcaya; shows by Notshybear and Chidash.","age_limit":"18+; passport or valid ID required.","source_urls":["https://formosapride.com/en/2026/"],"research_status":"official_date_hours_venue_lineup_dress_code_age_and_ticketing_verified","updated_at":"2026-09-28T00:00:00Z"}},
{"name":"X-Formosa: PINK","aliases":["Formosa Pride Pink 2026","X-Formosa Pink 1 November 2026"],"city":"taipei","date":"2026-11-01","start_date":"2026-11-01","end_date":"2026-11-02","description":"PINK is X-Formosa’s final neon exhale: a pink-coded Sunday-night circuit close with live vocal, Spanish club energy and no obligation to make Monday sensible.","link":"https://formosapride.com/en/2026/","ticket_url":"https://formosapride.com/en/2026/","location":"New Taipei City Exhibition Hall, next to Zepp New Taipei, New Taipei City, Taiwan","lat":25.0604,"lng":121.4568,"vibe":"pink-coded Taiwan Pride finale with circuit lift, live vocal and one last high-gloss release","intel":{"hours":"23:00 Sunday 1 November–04:00 Monday 2 November 2026.","entry_wait":"Door access is capacity-dependent; secure the PINK ticket early, especially if joining after WOOF.","best_arrival":"Come for 23:00 to catch the vocal and DJ programme before the festival’s final late-night compression.","crowd_mix":"International gay travellers, Taiwan LGBTQ+ scene, circuit-party dancers and guests continuing from the tea dance.","dress_code":"Pink.","host_inclusivity":"PINK is part of the official X-Formosa LGBTQ+ rainbow festival and follows its published safety and ID policies.","lineup":"Live vocal: Ann Bai. DJs: Kai Formosa and Suri.","age_limit":"18+; passport or valid ID required.","source_urls":["https://formosapride.com/en/2026/"],"research_status":"official_date_hours_venue_lineup_dress_code_age_and_ticketing_verified","updated_at":"2026-09-28T00:00:00Z"}}
]
$qa_taiwan_events$) e(name text,aliases jsonb,city text,date date,start_date date,end_date date,description text,link text,ticket_url text,location text,lat double precision,lng double precision,vibe text,intel jsonb)
), matched as (
 select s.*,x.id existing_id from src s left join lateral(select e.id from public.events e where lower(trim(e.city))=lower(trim(s.city)) and (lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(s.name),'[^a-z0-9]+','','gi')) or exists(select 1 from jsonb_array_elements_text(s.aliases) a where lower(regexp_replace(trim(e.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(a),'[^a-z0-9]+','','gi'))) or (e.start_date=s.start_date and lower(nullif(trim(e.link),'')) in(lower(s.link),lower(s.ticket_url)))) limit 1)x on true
), updated as (update public.events e set name=s.name,description=s.description,link=s.link,ticket_url=s.ticket_url,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,lat=s.lat,lng=s.lng,vibe=s.vibe,vibe_tags=array[]::text[],event_intel=s.intel,seo_indexable=true,seo_quality_status='approved',updated_at=timezone('utc',now()) from matched s where e.id=s.existing_id returning e.id)
insert into public.events(name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,vibe_tags,event_intel,seo_indexable,seo_quality_status,updated_at)
select name,city,description,link,ticket_url,date,start_date,end_date,location,lat,lng,vibe,array[]::text[],intel,true,'approved',timezone('utc',now()) from matched where existing_id is null;

with src as (
 select * from jsonb_to_recordset($qa_india_global_events$
[
{"name":"Pre-Navratri LGBTQ+ Resort Party","aliases":["Page G Pre-Navratri 2026","Mumbai LGBTQ Garba Pool Party 2026"],"date":"2026-10-03","start_date":"2026-10-03","end_date":"2026-10-04","description":"Page G takes queer Navratri out of the city and up the hill: pool light, Garba, Bollywood, a full overnight reset and a resort floor big enough to make the traditional and the unruly share a rhythm.","link":"https://therainbowrepublic.com/mumbai-party-events/pre-navratri-party/","ticket_url":"https://therainbowrepublic.com/mumbai-party-events/pre-navratri-party/","location":"Bhoj Resort, Kondeshwar Road, near Bhoj Dam, Bhoj Village, Badlapur East, Maharashtra 421503, India","vibe":"overnight Indian LGBTQ+ resort escape with Garba, Bollywood, pool-party release and hillside air","intel":{"hours":"19:00 Saturday 3 October–10:00 Sunday 4 October 2026.","entry_wait":"RSVP ahead to support new-venue planning; ticket price is listed at ₹950 and guests should follow resort and pool rules.","best_arrival":"Arrive close to 19:00 to settle into the resort before dinner, Garba and the all-night DJ sequence.","crowd_mix":"LGBTQ+ guests travelling in from across India, Garba newcomers, Bollywood dancers, pool-party groups and queer social regulars.","dress_code":"Pool clothes are for the pool only; pack a second comfortable outfit for Garba and the overnight dance programme.","host_inclusivity":"The organiser describes the party as an LGBTQ+ gathering and requires respectful, well-behaved participation; unauthorised photography of other guests is forbidden.","lineup":"Garba, Bollywood DJ and pool-party programming; individual DJ names are not published.","age_limit":"Confirm with organiser before attending.","source_urls":["https://therainbowrepublic.com/mumbai-party-events/pre-navratri-party/"],"research_status":"event_directory_date_hours_full_address_lgbtq_format_and_house_rules_verified","updated_at":"2026-09-28T00:00:00Z"}},
{"name":"The Navami Party 2026","aliases":["Kitty Su Navami Party Kolkata 2026","The Navami Party Kitty Su 2026"],"date":"2026-10-20","start_date":"2026-10-20","end_date":"2026-10-21","description":"Kitty Su brings Navami to Kolkata with bass, lights and queer nerve: a festival-night club ritual from India’s loudest LGBTQ+ nightlife institution, tuned for a full-throttle electronic release.","link":"https://www.kittysu.com/event/TheNavamiParty2026","ticket_url":"https://www.kittysu.com/event/TheNavamiParty2026","location":"Kitty Su, Dalhousie Square 1–3, Old Court House Street, Ward 1, Kolkata, West Bengal, India","vibe":"Kolkata queer club ritual with Navami energy, house/techno pulse and India-wide Kitty Su community","intel":{"hours":"20–21 October 2026; exact door and closing times are subject to the organiser’s live schedule.","entry_wait":"Official tickets are ₹1,350–3,500. Use Kitty Su’s own purchase channel because venue and schedule can change without prior notice.","best_arrival":"Confirm final doors before travel, then arrive in the opening window to avoid missing the still-to-be-announced headline programme.","crowd_mix":"Kitty Su regulars, Kolkata LGBTQ+ dancers, queer DJs and allies who value a visibly queer nightlife home.","dress_code":"No fixed code is published; bold, dance-ready styling fits Kitty Su’s queer-forward club identity.","host_inclusivity":"Kitty Su describes itself as India’s queerest nightlife brand and says queerness and DEI are central to its programming.","lineup":"To be announced by Kitty Su.","age_limit":"Confirm through official ticketing before attending.","source_urls":["https://www.kittysu.com/event/TheNavamiParty2026","https://kittysu.com/"],"research_status":"official_date_city_location_ticket_range_and_queer_host_identity_verified_schedule_pending","updated_at":"2026-09-28T00:00:00Z"}}
]
$qa_india_global_events$) e(name text,aliases jsonb,date date,start_date date,end_date date,description text,link text,ticket_url text,location text,vibe text,intel jsonb)
), matched as (select s.*,x.id existing_id from src s left join lateral(select g.id from public.global_events g where lower(regexp_replace(trim(g.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(s.name),'[^a-z0-9]+','','gi')) or exists(select 1 from jsonb_array_elements_text(s.aliases) a where lower(regexp_replace(trim(g.name),'[^a-z0-9]+','','gi'))=lower(regexp_replace(trim(a),'[^a-z0-9]+','','gi'))) or (g.start_date=s.start_date and lower(nullif(trim(g.link),'')) in(lower(s.link),lower(s.ticket_url))) limit 1)x on true), updated as (update public.global_events g set name=s.name,description=s.description,link=s.link,ticket_url=s.ticket_url,date=s.date,start_date=s.start_date,end_date=s.end_date,location=s.location,vibe=s.vibe,vibe_tags=array[]::text[],event_intel=s.intel,source='Queer Atlas editorial verification',last_checked='2026-09-28',event_status='scheduled' from matched s where g.id=s.existing_id returning g.id)
insert into public.global_events(name,date,start_date,end_date,location,vibe,vibe_tags,description,link,ticket_url,event_intel,source,last_checked,event_status)
select name,date,start_date,end_date,location,vibe,array[]::text[],description,link,ticket_url,intel,'Queer Atlas editorial verification','2026-09-28','scheduled' from matched where existing_id is null;

do $qa_batch13_guard$
begin
 if exists(select 1 from public.events where event_intel->>'updated_at'='2026-09-28T00:00:00Z' and (coalesce(trim(description),'')='' or coalesce(trim(location),'')='' or jsonb_array_length(coalesce(event_intel->'source_urls','[]'::jsonb))=0)) then raise exception 'Taiwan batch missing editorial data'; end if;
 if exists(select 1 from public.global_events where event_intel->>'updated_at'='2026-09-28T00:00:00Z' and (coalesce(trim(description),'')='' or coalesce(trim(location),'')='' or jsonb_array_length(coalesce(event_intel->'source_urls','[]'::jsonb))=0)) then raise exception 'India batch missing editorial data'; end if;
end;
$qa_batch13_guard$;
commit;
