-- Queer Atlas: verified U.S. queer dance, Pride and culture events.
-- Researched 2026-09-26 from organiser, official ticketing or Resident Advisor.
-- Addresses marked TBA are intentionally not guessed.

begin;

alter table if exists public.events
  add column if not exists event_intel jsonb not null default '{}'::jsonb;

alter table if exists public.events
  add column if not exists ticket_url text;

with src as (
  select * from jsonb_to_recordset($qa_usa_queer_events$
[
  {"name":"SOLVENT","aliases":["SOLVENT at ErF Studios October 2026"],"city":"new_york","date":"2026-10-01","start_date":"2026-10-01","end_date":"2026-10-01","description":"SOLVENT turns ErF Studios into a queer-run vinyl pressure chamber: Cyclo Bonette, Very J, Estro and Amy L'Nitrate move from acid bite to a long, lubricated house-and-rave release. It is not a generic open-invite club night; allies enter at the host's discretion and the room's anti-harassment boundary is part of the format.","link":"https://ra.co/events/2530584","ticket_url":"https://ra.co/events/2530584","location":"ErF Studios, 1 Ingraham Street, Brooklyn, NY 11206, United States","lat":40.70854,"lng":-73.93856,"vibe":"queer vinyl acid and house with a deliberately intimate late-night finish","intel":{"hours":"21:00–04:00 on Thursday 1 October 2026.","entry_wait":"Advance tickets were listed at $15; capacity and queer-community door discretion make a walk-up assumption unwise.","best_arrival":"Arrive close to 21:00 for the full vinyl arc and to settle before the three-hour closing B2B.","crowd_mix":"Queer dancers and music heads are the intended room; allies are welcome only when they respect the host's boundaries.","dress_code":"No formal look is published. Choose dance-ready clothes rather than treating the event as a costume or spectator space.","host_inclusivity":"The organiser explicitly prohibits racism, homophobia, transphobia, unwanted touching and staring, and directs guests to staff for support.","lineup":"Cyclo Bonette, Very J, Estro b2b Amy L'Nitrate.","age_limit":"21+.","source_urls":["https://ra.co/events/2530584"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"The Melt: Equinox","aliases":["The Melt Equinox 2026"],"city":"washington_dc","date":"2026-10-03","start_date":"2026-10-03","end_date":"2026-10-03","description":"The Melt's Equinox edition gives Washington a compact Black- and queer-DJ-led autumn reset: ghetto-tech swing, club pressure and a low-cost night built to keep local dancers in the room rather than outside the price point.","link":"https://ra.co/events/2536181","ticket_url":"https://ra.co/events/2536181","location":"Sinners and Saints, 2309 18th Street NW, Washington, DC 20009, United States","lat":38.92063,"lng":-77.04205,"vibe":"Black queer ghetto-tech and club rhythms in an intimate Adams Morgan room","intel":{"hours":"22:00–03:00 on Saturday 3 October 2026.","entry_wait":"$10 advance or at the door, with a notaflof option stated by the organiser; carry valid ID for the 21+ door.","best_arrival":"Come soon after 22:00 if you want the warm-up sets and an easier bar order before the room peaks.","crowd_mix":"Rising Black and queer DJs lead a local dance crowd, with a Baltimore guest in the bill.","dress_code":"No formal code is published; club-ready layers suit the compact late-night room.","host_inclusivity":"The event explicitly centres Black and queer DJs; its accessibility promise is financial as well as cultural through notaflof.","lineup":"swvmpting, Juno Hill, ¡ceL!, belizenotbrazil b2b sage blue.","age_limit":"21+.","source_urls":["https://ra.co/events/2536181"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Technosexual Order's Read the Room for Pride w/ Jeffrey Sfire","aliases":["Technosexual Order Read the Room for Pride","Read the Room for Pride with Jeffrey Sfire"],"city":"atlanta","date":"2026-10-09","start_date":"2026-10-09","end_date":"2026-10-10","description":"Technosexual Order's Atlanta Pride-weekend warm-up keeps the scale intimate and the selectors sharp: local queer DJs share a room with Detroit's Jeffrey Sfire for a house-and-techno session that reads more like a trusted invitation than a corporate Pride add-on.","link":"https://ra.co/events/2529223","ticket_url":"https://ra.co/events/2529223","location":"Read the Room, 691 John Wesley Dobbs Avenue NE, Unit P, Atlanta, GA 30312, United States","lat":33.75618,"lng":-84.36474,"vibe":"intimate queer Pride-weekend house and techno with Detroit depth","intel":{"hours":"19:00–03:00 on Friday 9 October 2026.","entry_wait":"Limited $30 tickets were listed and the organiser flags sell-out risk; buy ahead and bring ID.","best_arrival":"Use the early 19:00 opening for a calmer entry and the whole local-to-guest-DJ progression.","crowd_mix":"Atlanta queer DJs, their communities and visiting dance-music listeners are the clear centre of gravity.","dress_code":"No prescribed code is published; expressive Pride-night-out clothing is appropriate without assuming a fetish threshold.","host_inclusivity":"The promoter frames the bill around Atlanta's queer DJ community rather than treating queer identity as venue decoration.","lineup":"Jeffrey Sfire, Mike Bradley, Brian Rojas, Phox, berth.","age_limit":"21+.","source_urls":["https://ra.co/events/2529223"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Hybrid Identity: sapphic autumn","aliases":["Hybrid Identity sapphic autumn 2026"],"city":"new_york","date":"2026-10-09","start_date":"2026-10-09","end_date":"2026-10-10","description":"Hybrid Identity imagines sapphic communion as an all-night sound system: Scotia, Antenes, Emsho, ron like hell, threehz and Constructible take techno and electro somewhere intimate, unruly and deliberately phone-light. The address stays protected until ticket holders receive it.","link":"https://ra.co/events/2533778","ticket_url":"https://ra.co/events/2533778","location":"Brooklyn, NY, United States — exact address sent to ticket holders before 18:00","lat":40.67818,"lng":-73.94416,"vibe":"sapphic queer techno and electro with an all-night warehouse sensibility","intel":{"hours":"23:00–10:00 overnight, Friday 9 to Saturday 10 October 2026.","entry_wait":"$40 tickets; the exact location is sent to ticket holders before 18:00 on the event day, so do not travel to an invented pin.","best_arrival":"Arrive near 23:00: this protects the host's confidential-address flow and gives space before the long overnight build.","crowd_mix":"Sapphic community is the event's mood and subject, while the organisers welcome everyone willing to uphold collective care.","dress_code":"Looks are invited rather than mandated; contribute an intentional mood without assuming a costume or kink requirement.","host_inclusivity":"Hybrid Identity names consent, staff support, phone-free dancing and harassment prevention as operating rules.","lineup":"Scotia, Antenes, ron like hell b2b threehz, Emsho, Constructible.","age_limit":"21+.","source_urls":["https://ra.co/events/2533778"],"research_status":"ticketing_listing_verified_confidential_address","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Porkroll: Ourfest with Derrick Carter","aliases":["Porkroll Ourfest 2026","Porkroll with Derrick Carter"],"city":"philadelphia","date":"2026-10-09","start_date":"2026-10-09","end_date":"2026-10-10","description":"Porkroll opens OURfest weekend with Derrick Carter's elastic Chicago-house command, then lets Tommy C, Redevil and Chris Urban stretch the night through disco, soul, house and queer-positive room craft. It is joyous rather than heritage-museum house: dress up or down, but show up for the floor.","link":"https://ra.co/events/2525429","ticket_url":"https://ra.co/events/2525429","location":"broad hall., 699 North Broad Street, Philadelphia, PA 19123, United States","lat":39.96489,"lng":-75.15803,"vibe":"queer-positive house, disco and dance-floor generosity for OURfest opening night","intel":{"hours":"21:00–02:00 on Friday 9 October 2026.","entry_wait":"$20–$40 advance tickets were listed; prices rise with tiers, so buying earlier matters more than arriving at the last minute.","best_arrival":"Be there at 21:00 to catch the foundation-room sets before Derrick Carter's headline peak.","crowd_mix":"Philadelphia queer dancers, OURfest visitors, Chicago-house devotees and DC's Tommy C community share the room.","dress_code":"No dress threshold: the organiser explicitly says dress up or down. Coat check is available.","host_inclusivity":"Porkroll describes its purpose as queer positivity and community care, not merely a gay-branded booking.","lineup":"Derrick Carter, Tommy Cornelis, Redevil, Chris Urban.","age_limit":"21+.","source_urls":["https://ra.co/events/2525429"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"TOSSD at telos.haus – October 2026","aliases":["TOSSD October 2026"],"city":"new_york","date":"2026-10-11","start_date":"2026-10-11","end_date":"2026-10-11","description":"TOSSD starts after sunrise and refuses the usual afters autopilot: a twelve-hour queer DIY day party at telos.haus with a young underground lineup, subBASS sound and enough time for Brooklyn's dancers to make the day their own.","link":"https://ra.co/events/2537121","ticket_url":"https://ra.co/events/2537121","location":"telos.haus, 303 Ten Eyck Street, Brooklyn, NY 11206, United States","lat":40.70861,"lng":-73.93953,"vibe":"queer DIY after-hours-to-daylight dance marathon with bass-system focus","intel":{"hours":"06:00–20:00 on Sunday 11 October 2026.","entry_wait":"$40 cash or Venmo at the door was listed; arrive early because this is a single-day, capacity-bound DIY event.","best_arrival":"Aim for the 06:00 opening if you want the intended after-hours-to-daylight transition rather than only the late-day crowd.","crowd_mix":"Up-and-coming queer underground DJs and a queer DIY dance floor are the event's stated core.","dress_code":"No published uniform; daylight-to-evening layers and comfortable dancing shoes are more useful than nightclub polish.","host_inclusivity":"The organisers ask guests to respect staff, artists and each other, positioning care as part of the DIY infrastructure.","lineup":"Kiss Kiss, Simisola, DJ DEADNAME b2b MORENXXX, Scotia, Blu:sh, Giovannii.","age_limit":"21+.","source_urls":["https://ra.co/events/2537121"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"OUTFEST AFTERS with Jeffrey Sfire","aliases":["OURfest Afters with Jeffrey Sfire 2026"],"city":"philadelphia","date":"2026-10-11","start_date":"2026-10-11","end_date":"2026-10-12","description":"FVTVRE FAV and DIVA WORSHIP take the OURfest afters to The Dolphin with Jeffrey Sfire, G I N A and Doll.Redacted: Italo tension, high-NRG lift and acid edges for people who want the queer festival day to turn into a properly sweaty Sunday night.","link":"https://ra.co/events/2538288","ticket_url":"https://www.etix.com/","location":"The Dolphin, 1539 South Broad Street, Philadelphia, PA 19147, United States","lat":39.92950,"lng":-75.16918,"vibe":"OURfest afterparty with Italo, high-NRG, acid and queer dance-floor history","intel":{"hours":"21:00–02:00 Sunday 11 October into Monday 12 October 2026.","entry_wait":"$15–$20 tickets were listed; obtain the current ticket from the event's linked seller rather than relying on a walk-up.","best_arrival":"Arrive at doors for the support DJs and a smoother entry before the post-festival crowd consolidates.","crowd_mix":"OURfest attendees, queer nightlife regulars and fans of Sfire's Italo-to-house lineage are the natural audience.","dress_code":"No formal code is published; use a dance-ready look that can survive a Sunday-night afterparty.","host_inclusivity":"The hosts are queer nightlife collectives presenting an official OURfest-afters context, not a generic DJ night.","lineup":"Jeffrey Sfire, G I N A, Doll.Redacted; hosted by The Moon Baby.","age_limit":"21+.","source_urls":["https://ra.co/events/2538288","https://www.etix.com/"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Melt at Val's Lesbian Bar","aliases":["Melt Philadelphia October 2026","Melt Queer Dance Philly"],"city":"philadelphia","date":"2026-10-17","start_date":"2026-10-17","end_date":"2026-10-18","description":"Melt brings Queer Dance Philly's sapphic and trans-forward club language to Val's: funky house, glitchy electronics and physical rhythms with enough warmth to be sensual without turning anyone into a performance.","link":"https://ra.co/events/2535173","ticket_url":"https://ra.co/events/2535173","location":"Val's Lesbian Bar, 605 South 3rd Street, Philadelphia, PA 19147, United States","lat":39.94054,"lng":-75.14534,"vibe":"sapphic and trans-forward house, electronica and close-quarters club energy","intel":{"hours":"21:00–01:30 Saturday 17 October into Sunday 18 October 2026.","entry_wait":"21+ event; confirm the current ticket or door arrangement through Queer Dance Philly because the listing's price field is not a reliable admission promise.","best_arrival":"Reach Val's near 21:00 for a softer opening room before its intimate capacity becomes the point.","crowd_mix":"Sapphic and trans dancers are explicitly centred, alongside friends who understand the room's consent-led social intention.","dress_code":"Courage and costumes are encouraged, never required; come expressive but able to dance in a small bar.","host_inclusivity":"Queer Dance Philly defines this edition as sapphic and trans-forward, making its audience commitment specific rather than generic.","lineup":"diy.ffs, America Loves Me, Callaia.","age_limit":"21+.","source_urls":["https://ra.co/events/2535173","https://queerdancephilly.com/"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"The Carry Nation at Flash","aliases":["The Carry Nation Washington DC 2026"],"city":"washington_dc","date":"2026-10-23","start_date":"2026-10-23","end_date":"2026-10-24","description":"The Carry Nation land at Flash with their deep knowledge of queer New York's dance-floor lineage intact: Nita Aviance and Will Automagic bring long-form house instincts, joined by Fish House Funk, Lemz and Keenan Orr across two rooms.","link":"https://ra.co/events/2515830","ticket_url":"https://ra.co/events/2515830","location":"Flash, 645 Florida Avenue NW, Washington, DC 20001, United States","lat":38.90702,"lng":-77.02009,"vibe":"queer underground house with extended-set craft and a two-room Flash layout","intel":{"hours":"22:00–04:00 Friday 23 October into Saturday 24 October 2026.","entry_wait":"Advance tickets were listed at $10–$25; Flash may sell door tickets only while capacity permits.","best_arrival":"Arrive for the 22:00 doors to move between club level and Green Room before the headline room reaches peak density.","crowd_mix":"Queer house dancers, House of Aviance followers, Flash regulars and visiting NYC dance-music heads converge.","dress_code":"Flash has no event-specific look published; avoid overpacking because large bags and coats are checked under its current policy.","host_inclusivity":"The artists' work is rooted in queer nightlife, while Flash publishes staff escalation and a no-harassment safe-space policy.","lineup":"The Carry Nation, Fish House Funk, Lemz, Keenan Orr.","age_limit":"21+.","source_urls":["https://ra.co/events/2515830"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"SEQUENCE X","aliases":["SEQUENCE X Year 10 Anniversary Reunion","SEQUENCE X 2026"],"city":"washington_dc","date":"2026-10-24","start_date":"2026-10-24","end_date":"2026-10-25","description":"SEQUENCE's tenth-anniversary reunion is a renegade-techno love letter to DC: Perc headlines the hard room while a second room bends toward electro, jazz and psychedelia. The public listing is unusually clear about zero tolerance for harassment; the warehouse address stays with confirmed guests.","link":"https://ra.co/events/2515525","ticket_url":"https://ra.co/events/2515525","location":"Washington, DC, United States — exact location emailed to ticket holders or RSVPs on event day","lat":38.90719,"lng":-77.03687,"vibe":"all-night renegade techno with industrial force, queer underground links and two-room contrast","intel":{"hours":"22:00–06:00 Saturday 24 October into Sunday 25 October 2026.","entry_wait":"$15–$50 listed; valid government ID is required and the exact address is released only to ticket holders or RSVPs.","best_arrival":"Come at 22:00 and follow the event-day address instructions exactly; late arrival risks missing the controlled location release and the full eight-hour arc.","crowd_mix":"Techno lifers, DC underground dancers and queer community organisers and artists share a night designed for serious participation rather than spectator culture.","dress_code":"No published costume rule; hard-techno comfort, ear protection and an all-night transit plan are more useful than a fashion assumption.","host_inclusivity":"The listing explicitly bans sexism, racism, homophobia, transphobia, unsolicited touching and leering, with immediate enforcement stated.","lineup":"Perc, Juana, Ron Jackson, Damon Bradley, has.san, JADE CAO, Scotia, Jaguar Mindset, DJ Dubu, Chelle.","age_limit":"21+.","source_urls":["https://ra.co/events/2515525"],"research_status":"ticketing_listing_verified_confidential_address","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"BOOFOWEEN","aliases":["BOOF Halloween 2026","BOOFOWEEN 2026"],"city":"san_francisco","date":"2026-10-31","start_date":"2026-10-31","end_date":"2026-11-01","description":"BOOFOWEEN gives Halloween a queer warehouse pulse rather than a bar-crawl cliché: Only Fire, DJ SEXSTASY, QUEENIE and ANDYLAND take 888 Garage into a techno-forward world of dark rooms, design and dance-floor-first immersion.","link":"https://ra.co/events/2484351","ticket_url":"https://ra.co/events/2484351","location":"888 Garage, 888 Marin Street, San Francisco, CA 94124, United States","lat":37.74890,"lng":-122.40334,"vibe":"queer-led Halloween techno warehouse rave with dark-room intensity and visual world-building","intel":{"hours":"22:30–03:00 Saturday 31 October into Sunday 1 November 2026.","entry_wait":"Advance RA tickets are available; this is a 21+ Halloween warehouse event, so expect capacity pressure rather than a casual bar walk-in.","best_arrival":"Use the 22:30 opening for easier entry and time with the production before the costume-night rush.","crowd_mix":"BOOF's queer underground community, techno dancers and Halloween night owls form the room; the brand's focus is world-building, not mainstream spectacle.","dress_code":"No mandatory costume has been published, but intentional Halloween looks suit the production; retain comfortable footwear for a warehouse floor.","host_inclusivity":"BOOF explicitly identifies as a queer-led underground brand and frames its events around a cohesive, intentional dance floor.","lineup":"Only Fire, DJ SEXSTASY, QUEENIE, ANDYLAND.","age_limit":"21+.","source_urls":["https://ra.co/events/2484351"],"research_status":"ticketing_listing_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"MERGE x The Great Beyond Weekender","aliases":["MERGE x THE GREAT BEYOND Weekender 2027","MERGE Great Beyond 2027"],"city":"new_york","date":"2027-01-27","start_date":"2027-01-27","end_date":"2027-01-31","description":"MERGE and The Great Beyond turn five winter days into a Brooklyn queer-techno weekender: early programming gives way to two East Williamsburg warehouse nights where self-expression, immersion and a carefully held collective body matter as much as the eventual lineup.","link":"https://ra.co/events/2502909","ticket_url":"https://ra.co/events/2502909","location":"Brooklyn, NY, United States — programme venues and East Williamsburg warehouse address to be announced by organiser","lat":40.70812,"lng":-73.94198,"vibe":"five-day queer techno weekender built around warehouse immersion and collective release","intel":{"hours":"Wednesday 27 January through Sunday 31 January 2027; final daily times and locations are pending.","entry_wait":"Tickets and the full lineup are staged for later release. Do not infer a warehouse address or individual-day admission from an older MERGE event.","best_arrival":"Build the trip once the organiser publishes the day-by-day schedule; Friday and Saturday are named as the principal warehouse nights.","crowd_mix":"MERGE's Brooklyn queer-techno community joins The Great Beyond's participants around dance, self-expression and sound-system immersion.","dress_code":"No formal rule is published; expression is central, but treat final venue rules and weather as decisive.","host_inclusivity":"MERGE explicitly defines itself as a queer techno party and states zero tolerance for physical, verbal and sexual harassment or discriminatory behaviour.","lineup":"To be announced by organiser.","age_limit":"21+.","source_urls":["https://ra.co/events/2502909"],"research_status":"official_ticketing_dates_verified_programme_pending","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Jersey Pride LGBTQ+ Pride Festival 2027","aliases":["Jersey Pride 2027","New Jersey Pride Festival 2027"],"city":"asbury_park","date":"2027-06-06","start_date":"2027-06-06","end_date":"2027-06-06","description":"Jersey Pride's 35th statewide celebration brings parade, boardwalk rally and six hours of live performance to Asbury Park: a genuinely public Pride day with community organisations, resources and an Atlantic-facing stage rather than a single-ticket nightlife product.","link":"https://jerseypride.org/","ticket_url":"https://jerseypride.org/","location":"Asbury Park Boardwalk and downtown parade route, Asbury Park, NJ 07712, United States","lat":40.22039,"lng":-74.01208,"vibe":"large, family-friendly statewide Pride with parade, advocacy and oceanfront live music","intel":{"hours":"12:00–19:00 Sunday 6 June 2027; parade begins at 12:00.","entry_wait":"The organiser describes a free, rain-or-shine public festival. Parade-route access, parking and boardwalk arrival are the practical constraints, not a club queue.","best_arrival":"Arrive before noon for the parade start and allow extra time for shore traffic; use the final organiser map for the rally stage and service points.","crowd_mix":"LGBTQ+ New Jersey communities, families, local organisations, performers, visitors and allies share a statewide public celebration.","dress_code":"Sun protection, comfortable shoes and weather-ready Pride expression are more useful than a formal look.","host_inclusivity":"Jersey Pride is explicitly a statewide LGBTQ+ event with community-resource distribution alongside entertainment.","lineup":"2027 rally performers to be announced.","age_limit":"All ages.","source_urls":["https://jerseypride.org/"],"research_status":"official_date_and_format_verified","updated_at":"2026-09-26T00:00:00Z"}},
  {"name":"Capital Pride Celebration 2027","aliases":["Capital Pride Parade and Festival 2027","Capital Pride DC 2027"],"city":"washington_dc","date":"2027-06-12","start_date":"2027-06-12","end_date":"2027-06-13","description":"Capital Pride's 2027 Celebration pairs Washington's June 12 parade with its June 13 festival: a two-day civic gathering where advocacy, visibility and a broad regional LGBTQ+ community take the foreground before any afterparty does.","link":"https://www.capitalpride.org/celebration-registration/","ticket_url":"https://www.capitalpride.org/celebration-registration/","location":"Washington, DC, United States — official parade route and festival grounds to be confirmed by Capital Pride","lat":38.90719,"lng":-77.03687,"vibe":"two-day national-capital Pride combining civic visibility, parade energy and a public community festival","intel":{"hours":"Parade Saturday 12 June and festival Sunday 13 June 2027; final operating hours and sites are pending.","entry_wait":"2027 participation registration is open, but public attendee access, route controls and festival-site entry guidance require the organiser's final map.","best_arrival":"Choose parade or festival deliberately and travel from the confirmed route or grounds, not a generic city-centre pin.","crowd_mix":"LGBTQ+ residents, regional visitors, community groups, advocates, businesses, performers, families and allies attend the capital region's largest Pride celebration.","dress_code":"Public Pride comfort applies: weather layers, walking shoes and water; expressive clothing is welcome without a formal requirement.","host_inclusivity":"Capital Pride Alliance explicitly frames the weekend around community visibility and the many voices within the LGBTQ+ region.","lineup":"2027 performers and detailed programme to be announced.","age_limit":"All ages for public Pride programming.","source_urls":["https://www.capitalpride.org/celebration-registration/"],"research_status":"official_dates_verified_venue_pending","updated_at":"2026-09-26T00:00:00Z"}}
]
$qa_usa_queer_events$) e(
  name text, aliases jsonb, city text, date date, start_date date, end_date date,
  description text, link text, ticket_url text, location text, lat double precision,
  lng double precision, vibe text, intel jsonb
)
), matched as (
  select s.*, existing.id as existing_id
  from src s
  left join lateral (
    select e.id
    from public.events e
    where lower(trim(e.city)) = lower(trim(s.city))
      and (
        lower(regexp_replace(trim(e.name), '[^a-z0-9]+', '', 'gi')) = lower(regexp_replace(trim(s.name), '[^a-z0-9]+', '', 'gi'))
        or exists (select 1 from jsonb_array_elements_text(coalesce(s.aliases, '[]'::jsonb)) a where lower(regexp_replace(trim(e.name), '[^a-z0-9]+', '', 'gi')) = lower(regexp_replace(trim(a), '[^a-z0-9]+', '', 'gi')))
        or (e.start_date = s.start_date and lower(nullif(trim(e.link), '')) in (lower(trim(s.link)), lower(trim(s.ticket_url))))
      )
    order by e.updated_at desc nulls last
    limit 1
  ) existing on true
), upserted as (
  update public.events e set name=s.name, description=s.description, link=s.link, ticket_url=s.ticket_url, date=s.date, start_date=s.start_date, end_date=s.end_date, location=s.location, lat=s.lat, lng=s.lng, vibe=s.vibe, vibe_tags=array[]::text[], event_intel=s.intel, seo_indexable=true, seo_quality_status='approved', updated_at=timezone('utc', now())
  from matched s where e.id=s.existing_id returning e.id
)
insert into public.events (name, city, description, link, ticket_url, date, start_date, end_date, location, lat, lng, vibe, vibe_tags, event_intel, seo_indexable, seo_quality_status, updated_at)
select name, city, description, link, ticket_url, date, start_date, end_date, location, lat, lng, vibe, array[]::text[], intel, true, 'approved', timezone('utc', now())
from matched where existing_id is null;

do $qa_event_safety$
begin
  if exists (
    select 1 from public.events
    where event_intel->>'updated_at' = '2026-09-26T00:00:00Z'
      and (coalesce(trim(description), '') = '' or coalesce(trim(location), '') = '' or jsonb_array_length(coalesce(event_intel->'source_urls', '[]'::jsonb)) = 0)
  ) then raise exception 'Imported event is missing editorial copy, location or source provenance'; end if;
  if exists (
    select 1 from public.events
    where event_intel->>'updated_at' = '2026-09-26T00:00:00Z'
    group by lower(trim(city)), lower(regexp_replace(trim(name), '[^a-z0-9]+', '', 'gi')), start_date
    having count(*) > 1
  ) then raise exception 'Duplicate imported event detected'; end if;
end;
$qa_event_safety$;

commit;
