-- Queer Atlas venue intelligence: global review-led editorial pass, batch 46.
-- Nine Brussels records checked against current official pages, local reporting, event listings and guest reviews on 2026-08-06.
-- Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (205::bigint, jsonb_build_object(
      'queue_wait', 'This is an all-day café, not a velvet-rope night out. Breakfast and weekday coffee are easy; the broad terrace and lunch tables become the squeeze when Brussels gets sun, and Friday-Saturday drinks run later. Order at the bar when service is busy. The real address is Rue du Marché au Charbon 91.',
      'best_nights', 'Come late morning for specialty coffee and breakfast, or let a bright afternoon stretch into natural wine and cocktails on the terrace. Friday and Saturday work as queer pre-drinks, but the reopened café feels most distinctive when food, daylight and neighbourhood gossip overlap.',
      'crowd_mix', 'Queer locals, artists and design-minded friends share the room with city workers, brunch regulars and Grand-Place visitors. It feels visibly LGBTQ+ without becoming a single-gender bar. The balance leans local by day and more international as the terrace fills toward the weekend.',
      'dress_code', 'There is no dress code: coffee-run layers, office clothes, vintage finds and a full going-out look can land at neighbouring tables. Dress for the terrace and Brussels weather rather than a door test. The vegetarian and vegan menu also makes this an easy mixed-group meeting point before anyone commits to the night.',
      'staff_inclusivity', 'Recent guests describe the reopened team as kind, quick and genuinely welcoming, especially with mixed groups. The café is queer-led in mood rather than guarded at the threshold. Toilet upkeep appears in older feedback, but hospitality and food quality dominate the current consensus.',
      'venue_classification', 'active_reopened_queer_led_all_day_cafe_restaurant_and_terrace_in_brussels_gay_street_with_specialty_coffee_vegetarian_food_natural_wine_cocktails_and_mixed_local_visitor_crowd',
      'identity_note', 'Le Fontainas reopened under a new creative team in 2025 after a closure. Its current official address is Rue du Marché au Charbon 91, 1000 Brussels; the stored Rue des Ursulines 4 address is incorrect.',
      'source_urls', to_jsonb(array['https://www.lefontainas.be/','https://lefooding.com/en/restaurants/le-fontainas-2','https://wanderlog.com/place/details/2658631/caf%C3%A9-le-fontainas','https://www.corner.inc/place/pNUEZ8rnhoiN','https://brussels.gaycities.com/restaurants/303291-le-fontainas?type=cafe']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','all_day_cafe_no_club_queue_with_sun_and_weekend_terrace_pressure_bar_ordering_late_weekend_hours_and_correct_current_address','source_urls',to_jsonb(array['https://www.lefontainas.be/','https://lefooding.com/en/restaurants/le-fontainas-2','https://wanderlog.com/place/details/2658631/caf%C3%A9-le-fontainas']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','specialty_coffee_breakfast_daylight_terrace_natural_wine_cocktail_and_friday_saturday_queer_predrink_variation','source_urls',to_jsonb(array['https://www.lefontainas.be/','https://lefooding.com/en/restaurants/le-fontainas-2','https://www.corner.inc/place/pNUEZ8rnhoiN']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','queer_local_artist_designer_worker_brunch_regular_and_grand_place_visitor_mix_with_day_local_and_weekend_international_shift','source_urls',to_jsonb(array['https://lefooding.com/en/restaurants/le-fontainas-2','https://wanderlog.com/place/details/2658631/caf%C3%A9-le-fontainas','https://brussels.gaycities.com/restaurants/303291-le-fontainas?type=cafe']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_code_day_office_vintage_nightlife_and_weather_led_terrace_style_with_mixed_group_food_access','source_urls',to_jsonb(array['https://www.lefontainas.be/','https://www.corner.inc/place/pNUEZ8rnhoiN']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','current_kind_quick_helpful_and_mixed_group_welcome_consensus_balanced_against_older_toilet_upkeep_notes','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2658631/caf%C3%A9-le-fontainas','https://www.corner.inc/place/pNUEZ8rnhoiN']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (207::bigint, jsonb_build_object(
      'queue_wait', 'Big-name Friday and Saturday bills can sell out and stack a serious Marolles queue. Buy early, but a presale still does not guarantee admission; security keeps final say. Door tickets may remain when online sales close, and early arrival gives the best chance. Entry is 18+ and searches are possible.',
      'best_nights', 'Follow the DJ, not the weekday. Long, properly programmed techno nights define the club; harder bookings draw the fiercest room, while queer or Pride editions change the social temperature. The main floor now has a rebuilt system, so arrive before peak crush if sound and space matter equally.',
      'crowd_mix', 'Brussels techno loyalists meet international ravers, artist fans and newer clubbers who know the headline more than the room. It is strongly queer-friendly and hosts queer dates, but an ordinary weekend is music-led rather than an LGBTQ+ party. Sold-out crowds can become pushy despite excellent programming.',
      'dress_code', 'The code favours muted, functional, darker clubwear and closed dance-safe shoes. Suits, high heels, sandals, flip-flops and glowing accessories can be refused; toplessness is welcome for every gender. Phone cameras are stickered and filming inside is forbidden, though official photographers may work.',
      'staff_inclusivity', 'Recent guests praise friendly staff, clean free toilets, lockers and a well-run room. Trained awareness and hospitality teams, a calm safe zone and a reporting contact cover discrimination or non-consent. That structure matters, while crowding and rough dancers remain the repeated weak point.',
      'venue_classification', 'active_landmark_marolles_techno_club_since_1994_with_international_lineups_rebuilt_main_sound_system_no_phone_dancefloor_functional_dress_policy_awareness_team_and_queer_specific_events',
      'identity_note', 'Fuse is currently at Rue Blaes/Blaesstraat 208, 1000 Brussels. The stored Rue des Tanneurs 127 address is outdated and should be corrected before map directions are trusted.',
      'source_urls', to_jsonb(array['https://www.fuse.be/','https://www.fuse.be/faq','https://www.fuse.be/news/room-01-new-sound-system','https://www.fuse.be/news/official-statement','https://wanderlog.com/place/details/1357077/fuse','https://ket.brussels/2026/04/30/fuse-is-turning-pride-into-a-full-throttle-queer-night/','https://www.reddit.com/r/Techno/comments/1m9o638']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','headline_weekend_sellout_queue_advance_ticket_without_guarantee_possible_door_allocation_early_arrival_age_18_and_search_policy','source_urls',to_jsonb(array['https://www.fuse.be/faq','https://wanderlog.com/place/details/1357077/fuse']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','dj_led_long_techno_harder_booking_queer_pride_special_and_rebuilt_main_sound_system_with_peak_space_tradeoff','source_urls',to_jsonb(array['https://www.fuse.be/','https://www.fuse.be/news/room-01-new-sound-system','https://ket.brussels/2026/04/30/fuse-is-turning-pride-into-a-full-throttle-queer-night/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_techno_loyalist_international_raver_artist_fan_newcomer_and_queer_event_mix_with_headliner_and_overcrowding_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1357077/fuse','https://www.reddit.com/r/Techno/comments/1m9o638','https://ket.brussels/2026/04/30/fuse-is-turning-pride-into-a-full-throttle-queer-night/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','official_muted_functional_dark_closed_shoe_code_with_formal_high_heel_open_shoe_lightwear_exclusions_all_gender_toplessness_and_no_phone_rule','source_urls',to_jsonb(array['https://www.fuse.be/faq']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','recent_staff_facility_and_operation_praise_with_trained_awareness_hospitality_safe_zone_reporting_channel_and_crowding_pressure','source_urls',to_jsonb(array['https://www.fuse.be/news/official-statement','https://wanderlog.com/place/details/1357077/fuse']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (203::bigint, jsonb_build_object(
      'queue_wait', 'The current incarnation is a tiny café-bar, not the cruise club described in this listing. Weekdays are usually an easy walk-in; the few seats, summer terrace and Pride or themed evenings can fill fast. Go before the late-evening rush if you want a proper conversation. The real address is Rue du Marché au Charbon 5.',
      'best_nights', 'Early evening is ideal for a Homo Colada, Belgian beer and a chat before moving along the gay street. Weekends bring more colour, while drag, art, fetish socials and watch parties make selected dates the real draw. In warm weather the little terrace changes it from a cosy winter den into a neighbourhood lookout.',
      'crowd_mix', 'Queer regulars, gay men, mixed LGBTQ+ friends and international visitors settle in together, with bartenders often bridging the languages and introductions. It is intimate enough that tourists do not feel anonymous and locals still set the tone. This is a social drinking bar first, not a men-only cruising crowd.',
      'dress_code', 'Dress as you would for a small queer café: casual layers, a date-night look or fetish accents all work. There is no fashion door. Space is the practical constraint, so bulky coats are less useful than personality. Save a glance for the playful art and famously decorated bathroom.',
      'staff_inclusivity', 'Hospitality is the clearest review pattern: solo visitors, couples and English-speaking tourists call the owners and bartenders warm, funny and attentive. Guests relax quickly and return on consecutive nights. The small scale makes the team part of the atmosphere rather than distant service staff.',
      'venue_classification', 'active_small_queer_cafe_bar_by_spit_it_out_at_new_gay_street_address_with_cocktails_beer_terrace_art_drag_watch_and_fetish_socials_mixed_local_international_crowd_and_exceptional_host_consensus',
      'identity_note', 'The current Homo Erectus by Spit It Out is a café-bar at Rue du Marché au Charbon 5, 1000 Brussels. The stored Rue Henri Maus 2 address and cruise-club classification do not describe the current venue.',
      'source_urls', to_jsonb(array['https://www.instagram.com/homoerectus.bxl/','https://wanderlog.com/place/details/4177643/lhomoerectus-by-spit-it-out','https://whereis.gay/homoerectus-bar','https://localguide.brussels/en/spot/lhomo-erectus/','https://qlist.app/venues/Bruxelles/The-Homo-Erectus-Bar/NGNzbTUzbXFLYzArK2hERzllNzI0QQ/fr']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_small_cafe_bar_not_cruise_club_with_weekday_walkin_weekend_pride_theme_capacity_early_conversation_and_correct_address','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4177643/lhomoerectus-by-spit-it-out','https://whereis.gay/homoerectus-bar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','early_cocktail_beer_predrink_weekend_drag_art_fetish_watch_party_and_summer_terrace_variation','source_urls',to_jsonb(array['https://whereis.gay/homoerectus-bar','https://localguide.brussels/en/spot/lhomo-erectus/','https://qlist.app/venues/Bruxelles/The-Homo-Erectus-Bar/NGNzbTUzbXFLYzArK2hERzllNzI0QQ/fr']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','queer_regular_gay_man_mixed_lgbtq_friend_and_international_visitor_social_bar_mix_distinct_from_men_only_cruising','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4177643/lhomoerectus-by-spit-it-out','https://whereis.gay/homoerectus-bar','https://localguide.brussels/en/spot/lhomo-erectus/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_reported_fashion_door_casual_date_and_expressive_fetish_style_with_small_room_coat_constraint_and_playful_decor','source_urls',to_jsonb(array['https://whereis.gay/homoerectus-bar','https://qlist.app/venues/Bruxelles/The-Homo-Erectus-Bar/NGNzbTUzbXFLYzArK2hERzllNzI0QQ/fr']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_named_owner_bartender_warm_fun_attentive_solo_couple_and_english_speaking_tourist_hospitality_consensus','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4177643/lhomoerectus-by-spit-it-out','https://whereis.gay/homoerectus-bar']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (202::bigint, jsonb_build_object(
      'queue_wait', 'The wood-panelled room is genuinely small. Weekday afternoons are calm enough to claim a stool and talk; Friday, Saturday and Pride can fill it shoulder to shoulder, with spillover standing outside. There is rarely a club-style line, but capacity is the limit. The correct doorway is Petite Rue au Beurre 2A.',
      'best_nights', 'Come after work for coffee, advocaat or Belgian beer and stay while the oldies-to-pop soundtrack lifts. Friday and Saturday become louder and more communal; Eurovision and Pride turn history into a party. Quiet weekday daylight is better if you want the staff and old interior to tell their stories.',
      'crowd_mix', 'Mature gay men and bears remain the heart, joined by younger admirers, loyal locals, mixed-age LGBTQ+ friends and Grand-Place tourists. Recent reports show a broader welcome than the old stereotype. Weekdays lean neighbourhood; celebratory weekends bring city and visitors into one narrow room.',
      'dress_code', 'There is no style test at this classic Belgian tavern. Knitwear, checked shirts, tourist layers and a sharper Friday look all fit the stained glass and dark wood. Comfort matters because stools and passage space are tight. Arrive as yourself, order well and respect the regulars.',
      'staff_inclusivity', 'Current reviews under the newer team are strikingly warm: guests praise fast service, English-friendly conversation and hosts who turn a quick beer into an evening. Older reports describe abrupt treatment, especially toward women, but largely predate this team. Recent feedback still notes toilets needing care.',
      'venue_classification', 'active_historic_oldest_brussels_gay_tavern_at_petite_rue_au_beurre_with_preserved_wood_interior_belgian_beer_coffee_mature_bear_core_mixed_age_visitors_weekend_pop_and_current_warm_host_consensus',
      'identity_note', 'La Réserve is at Petite Rue au Beurre/Korte Boterstraat 2A, 1000 Brussels. The stored Rue de l’Évêque 21 address is incorrect. Current local tourism information names Sebastian and Benji as the hosts.',
      'source_urls', to_jsonb(array['https://www.visit.brussels/en/visitors/venue-details.La-Reserve.266669','https://www.la-reserve.brussels/','https://wanderlog.com/place/details/4639772/la-r%C3%A9serve','https://whereis.gay/listing/la-reserve/','https://www.travelgay.com/venue/la-reserve','https://brussels.gaycities.com/bars/303261-la-reserve','https://ket.brussels/2025/11/20/timeless-charm-at-la-reserve-brussels-oldest-gay-bar-welcomes-all/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_room_weekday_calm_weekend_pride_capacity_without_typical_club_line_outside_spillover_and_correct_doorway','source_urls',to_jsonb(array['https://www.visit.brussels/en/visitors/venue-details.La-Reserve.266669','https://wanderlog.com/place/details/4639772/la-r%C3%A9serve','https://whereis.gay/listing/la-reserve/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','afterwork_coffee_advocaat_belgian_beer_weekend_pop_eurovision_pride_and_quiet_history_conversation_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4639772/la-r%C3%A9serve','https://whereis.gay/listing/la-reserve/','https://www.travelgay.com/venue/la-reserve']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mature_gay_bear_core_younger_admirer_local_mixed_age_lgbtq_friend_and_grand_place_tourist_mix_with_time_shift','source_urls',to_jsonb(array['https://www.visit.brussels/en/visitors/venue-details.La-Reserve.266669','https://whereis.gay/listing/la-reserve/','https://www.travelgay.com/venue/la-reserve']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_style_test_classic_tavern_casual_checked_tourist_and_friday_looks_with_tight_room_comfort_and_regular_respect','source_urls',to_jsonb(array['https://ket.brussels/2025/11/20/timeless-charm-at-la-reserve-brussels-oldest-gay-bar-welcomes-all/','https://whereis.gay/listing/la-reserve/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_fast_english_friendly_owner_host_praise_balanced_against_older_previous_management_women_hostility_and_current_toilet_care_note','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4639772/la-r%C3%A9serve','https://whereis.gay/listing/la-reserve/','https://www.travelgay.com/venue/la-reserve']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (210::bigint, jsonb_build_object(
      'queue_wait', 'Sunday is the dependable queer night, when FLASH takes over YOU from 22:00. Entry is free before midnight with a €10 membership card; admission later costs €10. It becomes extremely packed, with toilet and cloakroom lines inside, so early entry buys comfort too. The venue is at Rue Duquesnoy 18.',
      'best_nights', 'Sunday is the reason to go: two rooms, pop and club tracks, visiting dancers or DJs and a late finish after central Brussels slows down. Arrive before midnight for a lighter, social opening; come later for maximum heat. Friday-Saturday listings are separate and not automatically the same queer party.',
      'crowd_mix', 'Mostly young gay and LGBTQ+ clubbers, local regulars and weekend visitors fill the floor, with women and allies admitted. It is mixed, but not especially lesbian-centred. Guests say expanded VIP zones squeeze general admission and weaken the communal feeling, so usable dance space feels small.',
      'dress_code', 'No clear fashion code is published for Sunday: contemporary clubwear, trainers and expressive queer looks are the practical norm. Bring cash for facilities, keep valuables close and expect weekly photographers. If privacy matters, ask where cameras work; this is not a phone-free or anonymous room.',
      'staff_inclusivity', 'Music, drag energy and visible queer freedom still win loyal praise. Recent reviews also allege aggressive security, weak conflict handling, language exclusion, paid toilets and VIP-first treatment; other guests felt welcomed. Go with friends and raise problems early rather than assuming a flawless safe-space response.',
      'venue_classification', 'active_weekly_sunday_flash_lgbtq_party_inside_you_night_club_at_duquesnoy_with_two_rooms_young_gay_queer_crowd_early_member_entry_late_capacity_pressure_photography_and_material_security_service_concerns',
      'identity_note', 'The recurring current identity is FLASH Club at YOU Night Club, 18 Rue Duquesnoy, 1000 Brussels. The stored Rue des Pierres 48 address is wrong, and the listing should present Sunday FLASH rather than imply one uniform all-week queer club.',
      'source_urls', to_jsonb(array['https://flashclub.be/en','https://wanderlog.com/place/details/5036016/flash-club','https://www.gayout.com/europe/belgium/brussels/bars/flash-club-1611','https://no.travelgay.com/venue/flash-tea-dance-you-night-club','https://www.thegayagenda.fyi/brussels/businesses/you-night-club/','https://fr.restaurantguru.com/FLASH-CLUB-Brussels']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','sunday_2200_flash_free_before_midnight_with_paid_membership_then_paid_entry_extreme_capacity_internal_facility_lines_and_correct_address','source_urls',to_jsonb(array['https://flashclub.be/en','https://wanderlog.com/place/details/5036016/flash-club','https://www.gayout.com/europe/belgium/brussels/bars/flash-club-1611']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','sunday_only_queer_anchor_two_room_pop_club_guest_dancer_dj_early_social_late_peak_and_non_equivalent_weekend_programming','source_urls',to_jsonb(array['https://flashclub.be/en','https://no.travelgay.com/venue/flash-tea-dance-you-night-club']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mostly_young_gay_lgbtq_local_visitor_woman_ally_mix_not_lesbian_centred_with_vip_partition_and_usable_capacity_concerns','source_urls',to_jsonb(array['https://www.gayout.com/europe/belgium/brussels/bars/flash-club-1611','https://no.travelgay.com/venue/flash-tea-dance-you-night-club','https://wanderlog.com/place/details/5036016/flash-club']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_sunday_fashion_code_with_contemporary_club_trainer_expression_cash_facility_valuables_and_weekly_photographer_privacy_context','source_urls',to_jsonb(array['https://flashclub.be/en','https://www.gayout.com/europe/belgium/brussels/bars/flash-club-1611']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','queer_music_drag_and_expression_praise_balanced_against_repeated_current_security_conflict_language_paid_toilet_vip_and_safe_space_failure_allegations','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5036016/flash-club','https://www.gayout.com/europe/belgium/brussels/bars/flash-club-1611','https://www.thegayagenda.fyi/brussels/businesses/you-night-club/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (209::bigint, jsonb_build_object(
      'queue_wait', 'Do not queue at Boulevard Anspach 73 for Machito. That address is a protected sandwich shop, and no current venue, official channel, calendar or credible review trail matches this listing. Remove the pin before it sends queer visitors to an unrelated daytime business.',
      'best_nights', 'There is no verified programme because no Brussels nightlife venue called Machito can be tied to this address. For a real queer evening, use nearby Rue du Marché au Charbon listings with live calendars. Inventing a Friday or Saturday here would turn a database error into travel advice.',
      'crowd_mix', 'No local, tourist or LGBTQ+ crowd can honestly be described for this record. Evidence at the address belongs to a historic sandwich counter, not a queer bar. Any Machito rating should be quarantined until its origin is known, not merged with reviews for the real business in the building.',
      'dress_code', 'There is no Machito door and no dress policy. The address is tied to a casual daytime food counter, but that does not make it a substitute venue. Hide this page, preserve the audit trail and restore it only if a verifiable operator supplies a distinct name, address and current programme.',
      'staff_inclusivity', 'No Machito team can be evaluated because the entity cannot be verified. Reviews of another business at the address must not become queer-safety evidence. Editorial restraint protects users here: suppress the record now and create a fresh place only if independent identity evidence appears.',
      'venue_classification', 'invalid_unverified_brussels_nightlife_record_named_machito_at_address_belonging_to_protected_au_suisse_sandwich_business_with_no_operator_calendar_reviews_or_distinct_queer_venue_identity',
      'record_status', 'non_venue_unverified_identity_hide_from_search_maps_sitemap_city_counts_recommendations_and_venue_intelligence_scoring',
      'identity_note', 'No credible current evidence connects a Brussels venue called Machito to Boulevard Anspach 73. The protected premises at 73-75 are documented as Au Suisse, a historic sandwich business.',
      'source_urls', to_jsonb(array['https://monument.heritage.brussels/fr/buildings/30712','https://www.brusselslife.be/fr/au-suisse','https://www.brusselstimes.com/39018/10-places-to-go-out-in-the-pedestrian-zone','https://unilocal.fr/belgique/bruxelles/au-suisse']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_machito_door_at_stored_address_which_is_documented_as_unrelated_protected_sandwich_business_and_requires_pin_removal','source_urls',to_jsonb(array['https://monument.heritage.brussels/fr/buildings/30712','https://www.brusselslife.be/fr/au-suisse','https://www.brusselstimes.com/39018/10-places-to-go-out-in-the-pedestrian-zone']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','no_verified_operator_calendar_or_night_programme_and_no_basis_for_weekend_recommendation','source_urls',to_jsonb(array['https://monument.heritage.brussels/fr/buildings/30712','https://www.brusselslife.be/fr/au-suisse']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','no_entity_specific_local_tourist_or_lgbtq_crowd_and_strict_separation_from_unrelated_address_business_reviews','source_urls',to_jsonb(array['https://www.brusselslife.be/fr/au-suisse','https://unilocal.fr/belgique/bruxelles/au-suisse']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_verified_venue_door_or_policy_with_unrelated_casual_daytime_business_not_a_substitute_identity','source_urls',to_jsonb(array['https://www.brusselslife.be/fr/au-suisse','https://unilocal.fr/belgique/bruxelles/au-suisse']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_machito_team_or_valid_review_consensus_and_other_business_staff_feedback_must_not_be_reused','source_urls',to_jsonb(array['https://monument.heritage.brussels/fr/buildings/30712','https://www.brusselslife.be/fr/au-suisse']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (204::bigint, jsonb_build_object(
      'queue_wait', 'There is no current nightclub queue: Spirito ended public club operations on 30 April 2026 and held a closing sale in May. Its old selective church line is history. Ignore the stored Rue de l’Escalier address and unofficial tickets; the former club stood at Rue de Stassart 18 in Ixelles.',
      'best_nights', 'The weekend ritual beneath stained glass has finished. Historically, commercial dance, electro, hip-hop and polished Saturday production made the church the spectacle. The owners spoke of reinvention, but no public club programme is confirmed, so there is no honest “best night” now.',
      'crowd_mix', 'In its club years, Spirito drew young polished locals, international guests, private-table groups and visitors curious about the church interior. Reviews called the crowd posh or showy; it was LGBTQ+-friendly rather than queer-centred. That mix is history after the April 2026 closure.',
      'dress_code', 'The former door leaned chic and selective: smart shirts and shoes were safer for men, while trainers, T-shirts and casual looks met inconsistent treatment. Those reports describe the old club only. There is no valid current dress code, and stale booking pages do not prove admission has resumed.',
      'staff_inclusivity', 'Past guests split between polished, helpful service and complaints about arbitrary dress rules, price and discriminatory selection. Wheelchair access was advertised for the ground floor and basement. With the club closed, that does not establish a current team; any successor needs a fresh review.',
      'venue_classification', 'closed_30_april_2026_former_luxury_nightclub_in_deconsecrated_ixelles_church_with_historic_commercial_electro_weekends_selective_chic_door_mixed_staff_reports_and_no_confirmed_successor_club',
      'record_status', 'closed_former_nightclub_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring_until_verified_successor_opens',
      'identity_note', 'Spirito ceased nightclub operations on 30 April 2026. Its real former address was Rue de Stassart 18, 1050 Ixelles; the stored Rue de l’Escalier 38 address is incorrect. The official site currently has no scheduled events.',
      'source_urls', to_jsonb(array['https://www.bruzz.be/actua/cultuurnieuws/brusselse-nachtclub-spirito-sluit-de-deuren-april-2026-2025-04-18','https://www.brusselstimes.com/belgium/1540755/brussels-spirito-nightclub-to-close-after-16-years-of-operation','https://www.brusselstimes.com/belgium/2058507/after-dark-brussels-might-be-sacrificed-due-to-a-game-of-compromise/','https://www.spiritobrussels.com/fr/','https://www.visit.brussels/nl/bezoekers/venue-details.Spirito-Brussels.263044','https://selfcity.be/discotheek/brussel/spirito/','https://app.wanderlog.com/place/details/1820392/le-spirito']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','confirmed_no_current_queue_after_30_april_2026_club_closure_and_may_sale_with_correct_former_stassart_address','source_urls',to_jsonb(array['https://www.bruzz.be/actua/cultuurnieuws/brusselse-nachtclub-spirito-sluit-de-deuren-april-2026-2025-04-18','https://www.brusselstimes.com/belgium/1540755/brussels-spirito-nightclub-to-close-after-16-years-of-operation','https://www.spiritobrussels.com/fr/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_weekend_commercial_electro_hiphop_church_spectacle_but_no_confirmed_successor_or_current_public_programme','source_urls',to_jsonb(array['https://www.bruzz.be/actua/cultuurnieuws/brusselse-nachtclub-spirito-sluit-de-deuren-april-2026-2025-04-18','https://www.spiritobrussels.com/fr/','https://selfcity.be/discotheek/brussel/spirito/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_young_polished_local_international_private_table_and_architecture_visitor_mix_lgbtq_friendly_not_queer_centred_and_not_current','source_urls',to_jsonb(array['https://selfcity.be/discotheek/brussel/spirito/','https://app.wanderlog.com/place/details/1820392/le-spirito']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_selective_chic_male_shirt_shoe_and_inconsistent_trainer_casual_enforcement_with_no_valid_current_policy','source_urls',to_jsonb(array['https://selfcity.be/discotheek/brussel/spirito/','https://app.wanderlog.com/place/details/1820392/le-spirito']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','historic_professional_helpful_praise_balanced_against_arbitrary_dress_price_and_discrimination_complaints_plus_advertised_access_not_current_team','source_urls',to_jsonb(array['https://selfcity.be/discotheek/brussel/spirito/','https://app.wanderlog.com/place/details/1820392/le-spirito','https://www.visit.brussels/nl/bezoekers/venue-details.Spirito-Brussels.263044']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (206::bigint, jsonb_build_object(
      'queue_wait', 'Friday and Saturday are busy by 23:00 and can reach shoulder-to-shoulder capacity around midnight. Earlier weekdays are easier; Sunday starts at 15:00 and builds around its dress theme. Entry varies by event, so check the calendar rather than assuming free admission. The current door is Rue du Marché au Charbon 114.',
      'best_nights', 'Friday-Saturday bring the fullest bar, darkroom and late-night social energy. Thursday often turns naked; Sunday afternoon rotates naked or underwear themes and feels easier for first contact. Monday-Wednesday suit conversation, but destination visitors should choose the exact fetish or techno date.',
      'crowd_mix', 'This men-focused gay cruise bar draws bears, leather men, admirers and curious visitors from roughly their twenties to sixties. Locals and tourists mix freely, and the front bar can be more social than the dark area. It is not an all-gender queer club; each body or fetish theme shapes the room.',
      'dress_code', 'Ordinary nights suit jeans, a T-shirt, sportswear or leather; heat and limited space punish fussy layers. Naked and underwear dates mean exactly that, with a clothes check and confidence doing more than fashion. Bring essentials, read the event wording and never treat a sexual dress theme as consent.',
      'staff_inclusivity', 'Many visitors describe a playful team and attitude-free crowd, especially on Sunday. Others report denied tap water, abrupt service, poor ventilation, uneven cleanliness and weak responses to unwanted touching. Condoms and lube should be easy to find; if not, ask before entering the dark area.',
      'venue_classification', 'active_men_focused_gay_cruise_and_fetish_bar_at_new_charcoal_market_address_with_front_social_bar_darkroom_weekend_capacity_naked_underwear_events_bear_leather_age_mix_and_material_facility_service_variation',
      'identity_note', 'Stammbar is currently at Rue du Marché au Charbon/Kolenmarkt 114, 1000 Brussels. The stored Rue des Pierres 29 address is obsolete. Official hours run evenings Monday-Saturday plus Sunday afternoon.',
      'source_urls', to_jsonb(array['https://stammbarbxl.com/','https://stammbarbxl.com/contact/','https://stammbarbxl.com/category/events/','https://stammbarbxl.com/naked-underwear-61/','https://stammbarbxl.com/naked-night-6/','https://www.travelgay.com/venue/stammbar','https://wanderlog.com/place/details/2447764/stammbar','https://brussels.gaycities.com/bars/305872-stammbar','https://ket.brussels/2023/03/17/stammbar/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','friday_saturday_2300_midnight_capacity_weekday_ease_sunday_afternoon_theme_event_specific_entry_and_correct_current_address','source_urls',to_jsonb(array['https://stammbarbxl.com/contact/','https://www.travelgay.com/venue/stammbar','https://wanderlog.com/place/details/2447764/stammbar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekend_full_bar_darkroom_thursday_naked_sunday_afternoon_naked_underwear_and_quieter_weekday_social_variation','source_urls',to_jsonb(array['https://stammbarbxl.com/category/events/','https://stammbarbxl.com/naked-underwear-61/','https://stammbarbxl.com/naked-night-6/','https://www.travelgay.com/venue/stammbar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','men_focused_gay_bear_leather_admirer_local_tourist_and_roughly_twenty_to_sixty_mix_with_social_front_and_cruise_back','source_urls',to_jsonb(array['https://www.travelgay.com/venue/stammbar','https://brussels.gaycities.com/bars/305872-stammbar','https://ket.brussels/2023/03/17/stammbar/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','ordinary_jean_tshirt_sports_leather_and_heat_practicality_with_exact_naked_underwear_theme_clothes_check_essentials_and_consent_boundary','source_urls',to_jsonb(array['https://stammbarbxl.com/naked-underwear-61/','https://stammbarbxl.com/naked-night-6/','https://www.travelgay.com/venue/stammbar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','many_playful_welcoming_sunday_team_and_attitude_free_crowd_reports_balanced_against_water_service_ventilation_cleanliness_and_touching_response_concerns','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2447764/stammbar','https://www.travelgay.com/venue/stammbar','https://brussels.gaycities.com/bars/305872-stammbar']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (208::bigint, jsonb_build_object(
      'queue_wait', 'An early drink is usually simple; ticketed drag guests and Friday-Saturday parties can pack the bar. Headline doors often open an hour before showtime and some dates cost around €10, with a free party later. Book when offered and arrive for the host, not halfway through. The address is Plattesteen 18/20.',
      'best_nights', 'Let the calendar choose: Drag Race viewings feel communal, Friday drag brings full performance energy, blind tests turn pop knowledge into chaos, and queer tango slows the room enough to meet people. Friday-Saturday run latest, but a free midweek culture night can feel more Brussels than generic dancing.',
      'crowd_mix', 'Young LGBTQIA+ locals, drag regulars, gender-diverse friends, queer women, newcomers and respectful allies make a broad mix. International visitors are common and many events work in French and English. The format matters: a viewing party, tango class and midnight DJ floor are socially different rooms.',
      'dress_code', 'There is no fashion gate. Everyday clothes, sequins, drag, gender-expansive looks and dance-ready shoes belong. The real code is behavioural: the charter rejects homophobia, transphobia, racism, fatphobia, ableism and slut-shaming. For shows, keep sightlines clear and bring cash if artists invite tips.',
      'staff_inclusivity', 'Most guests describe a cosy, super-queer room, friendly service and freedom across identities. A clear anti-discrimination charter supports removing harmful behaviour. Some reviews allege weak theft or safety handling and discourteous service, so the written promise still depends on consistent action when packed.',
      'venue_classification', 'active_central_broad_lgbtqia_event_bar_at_plattesteen_with_drag_viewings_pop_games_queer_tango_workshops_late_weekends_gender_diverse_local_international_crowd_formal_anti_discrimination_charter_and_mixed_incident_handling_reports',
      'identity_note', 'The Agenda is currently at Plattesteen 18/20, 1000 Brussels. The stored Rue des Brasseurs 5 address is incorrect. Its official programme and opening hours are current through August 2026.',
      'source_urls', to_jsonb(array['https://theagendabxl.be/','https://theagendabxl.be/events/','https://theagendabxl.be/charter/','https://theagendabxl.be/about-us/','https://theagendabxl.be/events/drag-show-kerri/','https://theagendabxl.be/events/tango-practice/','https://theagendabxl.be/events/just-the-tip/','https://www.thegayagenda.fyi/brussels/businesses/the-agenda/','https://restaurantguru.com/The-Agenda-Brussels','https://ket.brussels/2026/02/24/cut-cut-funding-party-drag-community-and-a-brand-new-chest-at-the-agenda/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','ordinary_early_walkin_ticketed_drag_and_weekend_capacity_typical_predoor_paid_show_later_free_party_advance_booking_and_correct_address','source_urls',to_jsonb(array['https://theagendabxl.be/','https://theagendabxl.be/events/drag-show-kerri/','https://theagendabxl.be/events/just-the-tip/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','calendar_led_drag_race_viewing_friday_drag_blindtest_queer_tango_workshop_and_late_weekend_versus_midweek_culture_variation','source_urls',to_jsonb(array['https://theagendabxl.be/','https://theagendabxl.be/events/','https://theagendabxl.be/events/tango-practice/','https://theagendabxl.be/events/just-the-tip/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_lgbtqia_drag_gender_diverse_queer_woman_newcomer_ally_and_international_french_english_mix_changing_by_format','source_urls',to_jsonb(array['https://theagendabxl.be/','https://theagendabxl.be/about-us/','https://www.thegayagenda.fyi/brussels/businesses/the-agenda/','https://ket.brussels/2026/02/24/cut-cut-funding-party-drag-community-and-a-brand-new-chest-at-the-agenda/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_fashion_gate_with_everyday_sequin_drag_gender_expression_and_dance_style_under_explicit_broad_anti_discrimination_behaviour_charter','source_urls',to_jsonb(array['https://theagendabxl.be/charter/','https://theagendabxl.be/about-us/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','majority_cosy_queer_friendly_cross_identity_service_praise_and_formal_exclusion_policy_balanced_against_theft_safety_and_courtesy_handling_complaints','source_urls',to_jsonb(array['https://theagendabxl.be/charter/','https://www.thegayagenda.fyi/brussels/businesses/the-agenda/','https://restaurantguru.com/The-Agenda-Brussels']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (204,209);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (205,207,203,202,210,209,204,206,208)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 9 then raise exception 'Expected 9 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
