-- Queer Atlas venue intelligence: global review-led editorial pass, batch 47.
-- Eight Antwerp, Bangkok, Belgrade, Berlin and Brussels records checked on 2026-08-07.
-- Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (2042::bigint, jsonb_build_object(
      'queue_wait','Big bookings can produce a proper line at the station-side entrance, while smaller Friday dates move quickly. Presale is the calmer route; arrive before midnight for more room and fewer payment-app bottlenecks. Lockers are QR-based, so have a charged phone ready.',
      'best_nights','Choose by the promoter and sound rather than assuming every weekend is identical. Techno nights make best use of the high ceiling, weighty bass and restrained lighting; selected upstairs openings add a second room. Friday is often the easier first visit, while major Saturdays run hotter and fuller.',
      'crowd_mix','Young Antwerp ravers, serious sound-system listeners and visitors from nearby Dutch and Belgian cities dominate. The room is multicultural and explicitly open to every background, but it is an electronic club rather than a dedicated queer venue. Headliners bring more tourists and a less settled floor.',
      'dress_code','There is no fashion-uniform policy: trainers, loose rave layers and dark practical clubwear all fit. Prioritise shoes you can dance in and something light for the warm main room. The door focuses on sobriety, conduct and respect, not gender expression or whether an outfit is expensive.',
      'staff_inclusivity','The published policy rejects homophobia, transphobia, sexism, racism and harassment, with trained stewards, security and bar staff named as contact points. Reviews often praise the sound and efficient service, but also flag crowding, heat, the cashless wallet system and occasional bar-charge disputes.',
      'venue_classification','active_antwerp_electronic_cultural_space_by_central_station_with_high_ceiling_main_room_strong_sound_qr_lockers_cashless_wallet_multicultural_safe_space_policy_and_promoter_led_programming',
      'identity_note','Ampere is active at Simonsstraat 21, 2018 Antwerp. It paused its former nightclub format in late 2023 but continues as a cultural and event space with current electronic programming.',
      'source_urls',to_jsonb(array['https://ampere-antwerp.com/','https://ampere-antwerp.com/about/','https://restaurantguru.com/Ampere-Antwerp','https://www.reddit.com/r/Antwerpen/comments/1jfd96p/amp%C3%A8re_club/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','booking_scaled_station_entrance_queue_presale_early_arrival_qr_locker_and_cashless_phone_friction','source_urls',to_jsonb(array['https://ampere-antwerp.com/about/','https://restaurantguru.com/Ampere-Antwerp']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','promoter_and_lineup_led_techno_high_ceiling_sound_lighting_upstairs_variation_and_friday_saturday_pressure','source_urls',to_jsonb(array['https://ampere-antwerp.com/','https://www.reddit.com/r/Antwerpen/comments/1jfd96p/amp%C3%A8re_club/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','young_local_regional_raver_and_sound_listener_mix_with_multicultural_policy_but_no_dedicated_queer_identity','source_urls',to_jsonb(array['https://ampere-antwerp.com/about/','https://www.reddit.com/r/Antwerpen/comments/1jfd96p/amp%C3%A8re_club/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_published_fashion_code_practical_ravewear_and_dance_shoes_with_conduct_sobriety_and_respect_door_focus','source_urls',to_jsonb(array['https://ampere-antwerp.com/about/','https://www.dresscodefinder.com/antwerpen/ampere']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','explicit_trained_safe_space_response_and_anti_discrimination_policy_balanced_against_heat_crowding_payment_and_bar_disputes','source_urls',to_jsonb(array['https://ampere-antwerp.com/about/','https://restaurantguru.com/Ampere-Antwerp','https://www.reddit.com/r/Antwerpen/comments/1jfd96p/amp%C3%A8re_club/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (2041::bigint, jsonb_build_object(
      'queue_wait','This basement is small enough that busy hard-techno and Pride dates can sell through. Presale is the only stated guarantee of capacity, not unconditional admission; intoxication or disrespect can still end the night at the door. Friday and Saturday open from 23:00, so earlier entry is smoother.',
      'best_nights','Follow the bill: harder techno turns the low bunker into a full-pressure room, while house and queer Pride collaborations loosen the mood. Saturday usually carries the longest peak; Friday can feel more focused. Summer outdoor editions are separate events, with the club used for the afterparty.',
      'crowd_mix','The core is young Antwerp techno and hard-bounce ravers, joined by regional visitors and a visible queer crowd on Pride-led dates. Recent regulars describe a younger, trend-driven audience than the club once had. It is broadly welcoming, but an ordinary weekend is music-first rather than LGBTQ+-centred.',
      'dress_code','All styles are officially welcome and comfort is the rule; topless dancing is explicitly allowed. Wear breathable layers and solid shoes for the tight cellar. Cameras regularly work inside, so expressive or skin-forward looks may be photographed; contact the venue first if that changes what feels comfortable.',
      'staff_inclusivity','The club says everyone is welcome, offers accessibility help and can refuse guests for disrespect rather than style. Reviews praise friendly people, lighting and ventilation, but toilet quality, drink prices and unwanted behaviour have drawn criticism. Treat the written welcome as a standard staff must actively uphold.',
      'venue_classification','active_small_antwerp_rijnkaai_basement_electronic_club_with_friday_saturday_programming_hard_techno_house_pride_collaborations_open_style_policy_toplessness_lockers_and_mixed_review_consensus',
      'identity_note','Club Vaag is active at Rijnkaai 4, 2000 Antwerp, with a current 2026 calendar and explicit entry, accessibility and dress guidance.',
      'source_urls',to_jsonb(array['https://www.clubvaag.be/','https://www.clubvaag.be/contact','https://selfcity.be/discotheek/antwerpen/club-vaag/','https://www.vaagoutdoor.be/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','small_capacity_presale_guarantee_conditional_on_respect_and_sobriety_with_friday_saturday_2300_early_entry_advantage','source_urls',to_jsonb(array['https://www.clubvaag.be/contact','https://selfcity.be/discotheek/antwerpen/club-vaag/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','bill_specific_hard_techno_house_pride_saturday_peak_friday_focus_and_separate_outdoor_afterparty_variation','source_urls',to_jsonb(array['https://www.clubvaag.be/','https://www.vaagoutdoor.be/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','young_local_regional_hard_techno_trend_crowd_with_pride_date_queer_shift_and_non_dedicated_weekends','source_urls',to_jsonb(array['https://selfcity.be/discotheek/antwerpen/club-vaag/','https://www.clubvaag.be/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','official_all_styles_comfort_toplessness_policy_with_small_hot_cellar_practicality_and_regular_photography_notice','source_urls',to_jsonb(array['https://www.clubvaag.be/contact']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','official_everyone_welcome_access_support_and_conduct_door_policy_balanced_against_facility_price_and_harassment_concerns','source_urls',to_jsonb(array['https://www.clubvaag.be/contact','https://selfcity.be/discotheek/antwerpen/club-vaag/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (2050::bigint, jsonb_build_object(
      'queue_wait','Do not plan a queue around this pin. The underground club operation has closed, moved more than once and now lacks a verifiable current door or official 2026 calendar. Old listings point variously to Thonglor, Phra Sumen Road and Pathum Thani, so a ride based on this record may end at the wrong building.',
      'best_nights','There is no defensible current best night. In its active years, the draw was the specific live, indie, psytrance, metal or electronic bill rather than a fixed weekend formula. Archived memories describe strong late events, but they cannot be converted into present-tense advice without a new operator announcement.',
      'crowd_mix','Historically, Bangkok musicians, underground electronic listeners, indie fans, expats and travellers mixed across genre-led nights. It was alternative and queer-friendly by scene overlap, not a dedicated LGBTQ+ club. No current crowd can be claimed after the club closure and repeated address changes.',
      'dress_code','The former rooms favoured unfussy band and club clothing rather than a fashion door: trainers, black tees and breathable layers suited the raw spaces. That history is not a current admission policy. Ignore third-party pages advertising a 2026 dress code until a verified operator publishes a location and programme.',
      'staff_inclusivity','Past guests remembered friendly crowds, ambitious bookings and a rare home for non-mainstream music. Those reviews belong to former incarnations and cannot verify a present team, accessibility or queer-safety response. Suppressing the stale record is more inclusive than sending visitors to an uncertain address.',
      'venue_classification','closed_or_unverified_former_bangkok_multi_genre_underground_live_and_electronic_venue_with_multiple_historic_addresses_no_confirmed_current_operator_door_or_2026_programme',
      'record_status','closed_or_unverified_former_venue_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring',
      'identity_note','De Commune/DECOMMUNE has operated from several Bangkok-area addresses. Available current evidence reports the club closed and no official 2026 programme establishes a successor at the stored identity.',
      'source_urls',to_jsonb(array['https://wanderlog.com/place/details/1699107','https://www.reddit.com/r/Bangkok/comments/191etz5','https://www.reddit.com/r/Bangkok/comments/1iasl9y','https://intravel.net/bangkok/nightlife/decommune']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','no_verified_current_door_after_closure_moves_and_conflicting_thonglor_phra_sumen_pathum_thani_addresses','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1699107','https://www.reddit.com/r/Bangkok/comments/1iasl9y','https://intravel.net/bangkok/nightlife/decommune']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','historic_bill_led_live_indie_psytrance_metal_and_electronic_programme_without_current_best_night_basis','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1699107','https://www.tripniceday.com/en/place/decommune']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','historic_local_musician_underground_listener_expat_traveller_mix_not_dedicated_lgbtq_and_not_current','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1699107','https://www.reddit.com/r/ThailandTourism/comments/11e4i7b']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','historic_unfussy_genre_led_clothing_only_with_no_verified_current_door_or_2026_policy','source_urls',to_jsonb(array['https://www.tripniceday.com/en/place/decommune','https://wanderlog.com/place/details/1699107']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','positive_historic_scene_memory_but_no_current_team_accessibility_or_safety_response_evidence','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1699107','https://www.reddit.com/r/Bangkok/comments/191etz5']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (2011::bigint, jsonb_build_object(
      'queue_wait','The riverboat does not reward arriving too early: the floor often wakes after midnight and can peak deep into the morning. Popular international bills may create a short gangway line, but entry is generally less theatrical than Berlin. Take a taxi or rideshare; the approach on foot is awkward at night.',
      'best_nights','Pick the DJ, then stay for sunrise over the Sava. House, techno, disco and left-field electronic nights each pull a different floor, and the open water makes warm-season dawns the signature experience. Arrive around 01:00 for momentum; before midnight can feel like the boat is still breathing in.',
      'crowd_mix','Belgrade underground regulars, artists, students and regional ravers mix with travellers who came for the city''s floating-club legend. The crowd is relaxed, mixed-gender and queer-friendly rather than explicitly LGBTQ+. International names increase the tourist share without erasing the local social core.',
      'dress_code','There is no polished splav dress code here. Worn trainers, tees, denim and functional dance layers suit the weathered boat better than heels or formal shirts. Dress for wind at the river edge and heat below deck. Knowing the night''s music and arriving composed matter more than a curated black uniform.',
      'staff_inclusivity','Guests repeatedly praise the unpretentious crowd, intimate scale and freedom of the dance floor. The recurring caution is practical: check each bar charge and bill before tapping or handing over cash. Queer visitors are common and the atmosphere is permissive, but no detailed public awareness policy was found.',
      'venue_classification','active_belgrade_sava_river_floating_underground_electronic_club_with_late_start_sunrise_signature_local_artist_student_traveller_mix_relaxed_door_and_recurring_bar_bill_caution',
      'identity_note','Klub 20/44 is an active floating club on the Sava riverbank in Belgrade. It is not a Bangkok lesbian bar or a Berlin venue; the numeric name refers to the boat club.',
      'source_urls',to_jsonb(array['https://www.instagram.com/klub20.44/','https://www.tripadvisor.com/Attraction_Review-g294472-d8762718-Reviews-Club_20_44-Belgrade.html','https://balkaninsight.com/wp-content/uploads/2017/01/belgradeinsightissueno221.pdf','https://en.wikipedia.org/wiki/No_Sleep_Festival']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','late_waking_boat_popular_bill_gangway_variation_easy_door_and_awkward_night_approach_transport_advice','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g294472-d8762718-Reviews-Club_20_44-Belgrade.html','https://balkaninsight.com/wp-content/uploads/2017/01/belgradeinsightissueno221.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','dj_led_house_techno_disco_leftfield_programming_with_post_midnight_momentum_and_sava_sunrise_signature','source_urls',to_jsonb(array['https://www.instagram.com/klub20.44/','https://www.tripadvisor.com/Attraction_Review-g294472-d8762718-Reviews-Club_20_44-Belgrade.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','belgrade_underground_artist_student_regional_raver_and_traveller_mix_queer_friendly_not_dedicated','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g294472-d8762718-Reviews-Club_20_44-Belgrade.html','https://en.wikipedia.org/wiki/No_Sleep_Festival']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','unpolished_boat_casual_dancewear_with_river_wind_and_below_deck_heat_practicality','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g294472-d8762718-Reviews-Club_20_44-Belgrade.html','https://balkaninsight.com/wp-content/uploads/2017/01/belgradeinsightissueno221.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','unpretentious_intimate_permissive_consensus_with_recurring_bar_overcharge_warning_and_no_published_awareness_policy','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g294472-d8762718-Reviews-Club_20_44-Belgrade.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (2000::bigint, jsonb_build_object(
      'queue_wait','This former slaughterhouse starts late. Before 01:00 the vast concrete rooms can feel empty; a strong international techno bill may build a line and full pressure after 02:00. Advance tickets help with sold-out risk, not behaviour checks. Use a rideshare and bring cash for the cloakroom.',
      'best_nights','The programme is everything: uncompromising techno uses the main hall at its most physical, while experimental concerts, theatre and queer editions can completely redraw the building. Friday and Saturday are not interchangeable. For the classic experience, choose a heavyweight electronic bill and stay past 03:00.',
      'crowd_mix','Belgrade ravers, artists, students and all-age local regulars share the rooms with international techno travellers. The club is notably LGBTQ+-friendly and gender-mixed without being exclusively queer. Bigger promoters bring a harder, more visitor-heavy crowd; live programmes feel more rooted in the city.',
      'dress_code','No standard fashion code is reported. Black layers, streetwear, boots or trainers all work in the raw industrial shell; dress light because the hall gets hot. Some themed parties publish their own look, so read the event page. Phones should stay away: the club is treated as a no-photo dance space.',
      'staff_inclusivity','Foreign and queer guests often describe easy entry, a liberated atmosphere and capable event management. The rough edges are real: toilets, standing water, heat and occasional bar friction recur in reviews. Inclusivity on the floor is strong; facilities and response quality vary with the night and crowd size.',
      'venue_classification','active_belgrade_former_slaughterhouse_underground_techno_live_art_and_theatre_complex_with_late_peak_multiple_rooms_no_photo_norm_lgbtq_friendly_local_international_mix_and_rough_facility_consensus',
      'identity_note','Drugstore is active at Bulevar despota Stefana 115, Belgrade. It is the Serbian underground club, not Berlin''s self-managed youth centre of the same name.',
      'source_urls',to_jsonb(array['https://www.instagram.com/clubdrugstore/','https://wanderlog.com/place/details/2323844/drugstore-belgrade','https://www.tripadvisor.com/Attraction_Review-g294472-d7218553-Reviews-Drugstore_Club_Beograd-Belgrade.html','https://restaurantguru.com/Drugstore-Belgrade','https://maps.apple.com/place?place-id=IC920943FAFD859AC']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','late_post_0100_build_international_bill_queue_advance_ticket_and_cash_cloakroom_rideshare_practicality','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2323844/drugstore-belgrade','https://www.tripadvisor.com/Attraction_Review-g294472-d7218553-Reviews-Drugstore_Club_Beograd-Belgrade.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','programme_specific_techno_experimental_concert_theatre_and_queer_variation_with_classic_post_0300_electronic_peak','source_urls',to_jsonb(array['https://www.instagram.com/clubdrugstore/','https://wanderlog.com/place/details/2323844/drugstore-belgrade']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','local_raver_artist_student_all_age_regular_international_techno_and_lgbtq_friendly_gender_mixed_crowd','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2323844/drugstore-belgrade','https://www.tripadvisor.com/Attraction_Review-g294472-d7218553-Reviews-Drugstore_Club_Beograd-Belgrade.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_standard_code_industrial_practical_clothing_event_specific_theme_and_no_photo_norm','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2323844/drugstore-belgrade','https://www.reddit.com/r/serbia/comments/f0bhta']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','foreign_queer_welcome_and_management_praise_balanced_against_toilet_heat_cleanliness_and_service_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2323844/drugstore-belgrade','https://restaurantguru.com/Drugstore-Belgrade']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1992::bigint, jsonb_build_object(
      'queue_wait','The garden-house entrance can swing from twenty minutes to more than an hour on celebrated Saturdays and costume-led nights. A ticket is not a promise of admission. Small groups, a calm queue and knowing the party help; Friday or an earlier arrival usually costs less time than the main Saturday crush.',
      'best_nights','Renate is strongest when its maze of rooms, garden and theatrical corners matter as much as one DJ. Regular house and techno weekends feel playful rather than severe; the elaborate sex-positive costume party is a separate world with a strict theme. Check the bill, because room count and mood change dramatically.',
      'crowd_mix','Berlin locals, international club tourists, queer dancers, artists and playful straight allies mingle through the old-house labyrinth. It is more colourful than the city''s stern techno stereotype. Costume-led dates become more explicitly queer and sex-positive; standard nights stay broad and music-led.',
      'dress_code','Ordinary nights reward personal, unconventional style and reject corporate formality more than colour; all-black is not required. For the costume party, effort is mandatory and no costume can mean no entry. Read the exact event brief rather than copying a generic Berlin uniform.',
      'staff_inclusivity','House rules centre consent and reject racism, homophobia, transphobia and hate speech; themed nights add an awareness team and play areas. Many guests love the free, eccentric atmosphere, while door reviews include abrupt refusals and language frustration. A ticket still leaves discretion at entry.',
      'venue_classification','active_friedrichshain_house_and_garden_electronic_club_with_multiroom_labyrinth_playful_mixed_queer_crowd_personal_style_door_policy_strict_costume_events_consent_rules_and_awareness_support',
      'identity_note','Renate remains active at Alt-Stralau 70, Berlin. The current public name is Renate, formerly Salon zur Wilden Renate; themed House of Lunacy dates have materially stricter clothing rules than ordinary club nights.',
      'source_urls',to_jsonb(array['https://www.renate.cc/','https://www.tripadvisor.com/Attraction_Review-g187323-d4923937-Reviews-Wilde_Renate-Berlin.html','https://www.reddit.com/r/Techno/comments/1b45t35','https://www.reddit.com/r/berlinsocialclub/comments/1pecpie/dresscode_for_renate/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','party_scaled_twenty_minute_to_hour_plus_ticket_not_guarantee_small_calm_group_and_early_friday_advantage','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g187323-d4923937-Reviews-Wilde_Renate-Berlin.html','https://www.renate.cc/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','multiroom_house_garden_theatre_value_with_regular_house_techno_and_distinct_strict_costume_sex_positive_event','source_urls',to_jsonb(array['https://www.renate.cc/','https://www.reddit.com/r/Techno/comments/1b45t35']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','berlin_local_international_tourist_queer_artist_and_ally_mix_with_more_explicit_costume_event_shift','source_urls',to_jsonb(array['https://www.renate.cc/','https://www.tripadvisor.com/Attraction_Review-g187323-d4923937-Reviews-Wilde_Renate-Berlin.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','ordinary_personal_unconventional_non_corporate_style_without_black_requirement_and_mandatory_event_specific_costume_effort','source_urls',to_jsonb(array['https://www.renate.cc/','https://www.reddit.com/r/Techno/comments/1b45t35','https://www.reddit.com/r/berlinsocialclub/comments/1pecpie/dresscode_for_renate/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','consent_anti_hate_rules_awareness_team_and_play_area_support_balanced_against_abrupt_selective_door_reports','source_urls',to_jsonb(array['https://www.renate.cc/','https://www.tripadvisor.com/Attraction_Review-g187323-d4923937-Reviews-Wilde_Renate-Berlin.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1993::bigint, jsonb_build_object(
      'queue_wait','This record combines two separate doors. The large vault complex can range from almost no line before midnight to a queue stretching toward the station for famous artists; its smaller neighbour runs its own admission and often a different ticket. Never assume one queue or purchase covers both.',
      'best_nights','Treat the calendar as two venues: the vault is for monumental industrial techno across its basement and upper hall, while the compact turbine-room neighbour favours adventurous bass, house, art and queer collectives. A combined “best night” would erase the programming choice that actually matters.',
      'crowd_mix','The larger institution draws young international techno pilgrims alongside Berlin regulars; the intimate room next door attracts more scene-specific locals, artists and queer communities when their collectives host. They share an operator connection and address complex, not one stable crowd.',
      'dress_code','Neither requires luxury. The vault door favours sober, music-aware guests in practical dancewear; the smaller room is officially described as casual and varies with its promoter. Tickets can still be refused. Read the named event and venue, not a merged listing or a one-size black-clothing myth.',
      'staff_inclusivity','Both programmes include diverse and queer-led nights, yet reviews of their separate doors vary from welcoming to opaque rejection. A single staff score would be misleading because entrance teams, scale and promoters differ. Replace this page with two records so safety and accessibility evidence stays attributable.',
      'venue_classification','invalid_composite_record_merging_distinct_adjacent_berlin_venues_tresor_and_ohm_with_separate_programmes_tickets_doors_capacity_crowds_and_review_consensus',
      'record_status','composite_duplicate_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring_then_replace_with_two_distinct_records',
      'identity_note','Tresor and OHM are distinct venues at the Köpenicker Strasse 70 complex. They have separate calendars and entry contexts; this combined record should not be treated as one venue.',
      'source_urls',to_jsonb(array['https://tresorberlin.com/','https://tresorberlin.com/club/tickets/','https://ohmberlin.com/','https://www.berlin.de/en/clubs/8871792-4469452-ohm.en.html','https://www.tripadvisor.com/Attraction_Review-g187323-d195031-Reviews-Tresor-Berlin.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','two_separate_doors_ticket_contexts_and_large_venue_artist_scaled_queue_versus_small_room_independent_admission','source_urls',to_jsonb(array['https://tresorberlin.com/club/tickets/','https://ohmberlin.com/','https://www.tripadvisor.com/Attraction_Review-g187323-d195031-Reviews-Tresor-Berlin.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','distinct_large_industrial_techno_and_small_adventurous_bass_house_art_queer_calendars_without_valid_combined_recommendation','source_urls',to_jsonb(array['https://tresorberlin.com/','https://ohmberlin.com/','https://www.berlin.de/en/clubs/8871792-4469452-ohm.en.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','large_international_techno_pilgrim_mix_versus_small_scene_specific_local_artist_and_queer_collective_audiences','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g187323-d195031-Reviews-Tresor-Berlin.html','https://ohmberlin.com/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','separate_music_aware_practical_and_casual_promoter_led_policies_with_no_valid_merged_code','source_urls',to_jsonb(array['https://tresorberlin.com/wp-content/uploads/2022/12/hausordnung-tresor2022.pdf','https://www.berlin.de/en/clubs/8871792-4469452-ohm.en.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','diverse_programming_but_nontransferable_door_staff_promoter_safety_and_accessibility_evidence_requires_two_records','source_urls',to_jsonb(array['https://tresorberlin.com/','https://ohmberlin.com/','https://www.tripadvisor.com/Attraction_Review-g187323-d195031-Reviews-Tresor-Berlin.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (2040::bigint, jsonb_build_object(
      'queue_wait','Presale and door buyers join the same line, and every group gets a short house-rules conversation. Busy Friday and Saturday bills can back up beneath Central Station; arrive near the 23:00 opening and keep groups under six to eight. Stay quiet outside and leave drinks behind before joining.',
      'best_nights','Let the curators decide. The concrete main room shines on deep techno and experimental electronic bills; concerts, installations and multidisciplinary programmes can make an earlier date more rewarding than a generic Saturday. Queer collectives shift the room most clearly, so read the full lineup and host.',
      'crowd_mix','Brussels electronic regulars, art-school and creative crowds, queer ravers, EU-city internationals and weekend visitors meet under the Horta Gallery. No single community owns the room. Major techno names raise the tourist ratio; local collectives and hybrid art nights feel more rooted and socially varied.',
      'dress_code','No fixed colour or fashion code is published. Functional dancewear, expressive queer looks and trainers all work if the person wearing them understands the night and house rules. Large groups, intoxication or disrespect matter more than labels. Phone cameras are covered, so dress for the room rather than documentation.',
      'staff_inclusivity','The ethos explicitly rejects racism, sexism, homophobia, shaming, violence and intrusive behaviour, with equality explained at entry. Many guests praise sound, staff and focus created by the camera ban; others report brusque briefing or unexplained refusal. Refused presale tickets are eligible for refund.',
      'venue_classification','active_brussels_central_station_horta_gallery_multidisciplinary_electronic_art_and_concert_space_with_house_rules_conversation_same_ticket_queue_camera_cover_inclusive_ethos_and_selective_door',
      'identity_note','C12 is active at Rue du Marché aux Herbes 116, 1000 Brussels, beneath Central Station in the Horta Gallery. Its official FAQ documents current queue, ticket, group and inclusion policies.',
      'source_urls',to_jsonb(array['https://c12space.com/','https://c12space.com/practical/','https://wanderlog.com/place/details/2298804','https://www.brusselstimes.com/belgium/377290/brussels-nightclub-c12-bans-smartphone-cameras/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','same_presale_door_queue_house_rule_conversation_busy_weekend_early_2300_group_size_silence_and_no_drink_guidance','source_urls',to_jsonb(array['https://c12space.com/practical/','https://www.brusselstimes.com/belgium/377290/brussels-nightclub-c12-bans-smartphone-cameras/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','curator_lineup_led_techno_experimental_concert_installation_multidisciplinary_and_queer_collective_variation','source_urls',to_jsonb(array['https://c12space.com/','https://c12space.com/practical/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','brussels_electronic_art_creative_queer_international_and_visitor_mix_with_headliner_and_local_collective_shift','source_urls',to_jsonb(array['https://c12space.com/','https://wanderlog.com/place/details/2298804']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_fixed_fashion_code_functional_expressive_style_with_music_house_rule_awareness_group_sobriety_and_camera_cover','source_urls',to_jsonb(array['https://c12space.com/practical/','https://www.brusselstimes.com/belgium/377290/brussels-nightclub-c12-bans-smartphone-cameras/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','explicit_equal_anti_discrimination_anti_intrusion_ethos_positive_sound_staff_and_camera_focus_balanced_against_door_communication_complaints','source_urls',to_jsonb(array['https://c12space.com/practical/','https://wanderlog.com/place/details/2298804']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (2050,1993);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (2042,2041,2050,2011,2000,1992,1993,2040)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
