-- Queer Atlas venue intelligence: global review-led editorial pass, batch 53.
-- Four Busan and four Cape Town records checked against current official pages,
-- local/editorial coverage and guest-review consensus on 2026-08-07.
-- Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1771::bigint, jsonb_build_object(
      'queue_wait', 'This is a vast daytime cafe, not a nightlife door. Weekday mornings leave the most room to read; weekends and exhibition afternoons bring families, design crowds and a longer order line. Even when the counter is busy, the old factory floor offers far more breathing space than a typical Busan cafe.',
      'best_nights', 'Treat it as a long daytime date: start with hand-drip coffee and pastry, then drift into the used-book store, galleries, bamboo path and garden. A weekday gives the architecture room to breathe; a weekend works when a current exhibition matters more than quiet. It is not a queer event venue.',
      'crowd_mix', 'Local coffee regulars, couples, families, art students and domestic visitors make up most of the room, with international travellers drawn by the factory conversion. The atmosphere is mixed and design-led rather than explicitly LGBTQ+. Locals dominate, especially outside holiday weekends.',
      'dress_code', 'There is no dress code. Clean everyday layers, study clothes and camera-ready weekend outfits all fit beneath the steel frame. Wear shoes comfortable enough for the bookstore, galleries and garden; the pleasure here is wandering, not dressing for approval.',
      'staff_inclusivity', 'Reviews consistently praise the spacious, calm setting and careful coffee, without identifying an LGBTQ-specific hospitality policy. Queer visitors should read it as a polished mainstream cultural stop where mixed groups blend in easily, not as a community safe-space with trained queer staff.',
      'venue_classification', 'active_large_specialty_coffee_and_bakery_branch_inside_f1963_adaptive_reuse_cultural_complex_with_bookstore_galleries_gardens_local_daytime_crowd_and_mainstream_mixed_welcome',
      'identity_note', 'Terarosa Suyeong is the Terarosa branch inside F1963 at 20 Gurak-ro 123beon-gil. It is a mainstream cafe in a former wire factory, not an LGBTQ-specific venue.',
      'source_urls', to_jsonb(array['https://terarosa.com/','https://www.f1963.org/','https://www.visitbusan.net/index.busan?lang_cd=en&menuCd=DOM_000000301001001000&uc_seq=372','https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=225385','https://wanderlog.com/place/details/2412970','https://hongdiarytravel.com/terarosa-f1963-busan-specialty-coffee/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','large_walkin_cafe_with_weekday_space_and_weekend_exhibition_counter_pressure_not_a_nightlife_queue','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2412970','https://hongdiarytravel.com/terarosa-f1963-busan-specialty-coffee/','https://www.hapskorea.com/busan-bites-mangmi-dongs-terarosa-2/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','daytime_coffee_pastry_bookstore_gallery_bamboo_and_garden_visit_with_weekday_quiet_or_event_led_weekend','source_urls',to_jsonb(array['https://www.visitbusan.net/index.busan?lang_cd=en&menuCd=DOM_000000301001001000&uc_seq=372','https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=225385','https://hongdiarytravel.com/terarosa-f1963-busan-specialty-coffee/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mainstream_local_coffee_couple_family_art_student_domestic_and_international_architecture_visitor_mix_not_lgbtq_specific','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2412970','https://www.visitbusan.net/index.busan?lang_cd=en&menuCd=DOM_000000301001001000&uc_seq=372','https://www.hapskorea.com/busan-bites-mangmi-dongs-terarosa-2/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_door_policy_everyday_study_and_weekend_style_with_walking_comfort_for_multi_space_complex','source_urls',to_jsonb(array['https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=225385','https://www.visitbusan.net/index.busan?lang_cd=en&menuCd=DOM_000000301001001000&uc_seq=372']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','positive_space_and_coffee_consensus_without_verified_lgbtq_policy_so_mainstream_mixed_welcome_not_community_safe_space_claim','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2412970','https://hongdiarytravel.com/terarosa-f1963-busan-specialty-coffee/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    )),
    (1763::bigint, jsonb_build_object(
      'queue_wait', 'The ritual is the entrance, not a rope line: go through Casa Busano, use the phone by the coffee counter and wait for the bookcase door to open. Most reviews describe only a handful of guests, though Haeundae weekends can make the best balcony seats scarce. There is no evidence of a selective queer door.',
      'best_nights', 'Go after dinner for one properly made signature cocktail, a cigar or a slow balcony conversation above Gunam-ro. Friday and Saturday have more Haeundae movement; a quieter weeknight makes the hidden-door theatre and attentive bartending feel most convincing. This is a cocktail stop, not a dance destination.',
      'crowd_mix', 'Couples, cocktail enthusiasts, hotel guests and curious Haeundae visitors form a polished international-mainstream mix. Reviews do not establish an LGBTQ core, local queer programme or community ownership. It can work for a queer date, but should not be sold as one of Busan''s gay bars.',
      'dress_code', 'Smart-casual fits the dark, styled room, yet reviewers say the secret entrance is more theatrical than exclusionary. Resort clothes, a neat date look or an understated evening outfit all work. The practical rule is to arrive composed enough for a premium cocktail bar, not to imitate a prohibition costume.',
      'staff_inclusivity', 'Recent couples repeatedly describe respectful, personal service, careful drinks and warm extras near closing. That supports a broadly welcoming mixed bar, but there is no published queer policy or meaningful LGBTQ review sample. Judge it on hospitality, not an unverified community label.',
      'venue_classification', 'active_hidden_speakeasy_style_mainstream_cocktail_and_cigar_bar_above_casa_busano_in_haeundae_with_phone_and_bookcase_entry_balcony_signature_drinks_couple_visitor_crowd_and_no_verified_lgbtq_identity',
      'identity_note', 'The current TBR The Back Room is at 17-1 Gunam-ro above/inside Casa Busano, not inside Tap and Tapas. It is a mixed speakeasy-style cocktail bar; no reliable source verifies it as an LGBTQ venue.',
      'source_urls', to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g297884-d12986888-Reviews-TBR_THE_BACK_ROOM-Busan.html','https://wanderlog.com/place/details/4945816','https://creatrip.com/en/spot/14323','https://www.trip.com/restaurant/south-korea/busan/detail/tbr-the-back-room-62012617/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','phone_and_bookcase_access_with_generally_low_guest_count_and_weekend_balcony_seat_pressure_without_selective_door_evidence','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g297884-d12986888-Reviews-TBR_THE_BACK_ROOM-Busan.html','https://wanderlog.com/place/details/4945816','https://creatrip.com/en/spot/14323']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','post_dinner_signature_cocktail_cigar_balcony_visit_with_weekend_energy_and_weeknight_service_focus_not_dancing','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g297884-d12986888-Reviews-TBR_THE_BACK_ROOM-Busan.html','https://wanderlog.com/place/details/4945816']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mainstream_couple_cocktail_hotel_and_international_haeundae_visitor_mix_with_no_verified_lgbtq_core','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g297884-d12986888-Reviews-TBR_THE_BACK_ROOM-Busan.html','https://wanderlog.com/place/details/4945816','https://www.trip.com/restaurant/south-korea/busan/detail/tbr-the-back-room-62012617/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','review_inferred_smart_casual_premium_cocktail_room_without_published_or_reported_selective_policy','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g297884-d12986888-Reviews-TBR_THE_BACK_ROOM-Busan.html','https://wanderlog.com/place/details/4945816']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_recent_respectful_personal_attentive_service_consensus_but_no_published_queer_policy_or_lgbtq_review_sample','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g297884-d12986888-Reviews-TBR_THE_BACK_ROOM-Busan.html','https://wanderlog.com/place/details/4945816']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    )),
    (1769::bigint, jsonb_build_object(
      'queue_wait', 'Doors open late and the room matters most after midnight. Thursday is the lighter entry; Friday and Saturday drag bills and monthly themes can compress the small club quickly. There is little evidence of a formal velvet-rope queue, but arriving near 23:00 gives you space before the show and a better view.',
      'best_nights', 'Choose Friday or Saturday for committed lip-sync drag, bigger sound and the full local queer-club release. Thursday is better for meeting the bartenders and reading the room without the weekend crush. Monthly themes change the music and dress energy, so the current programme matters more than a fixed weekly promise.',
      'crowd_mix', 'Busan LGBTQ+ regulars, drag supporters, younger gay clubbers and international visitors share the floor. The reviews are notably multilingual and call the space foreigner-friendly, but locals give it its pulse. It is broader than a men-only bar, though not enough evidence supports a precise lesbian-to-gay split.',
      'dress_code', 'No formal code is published. Dance-ready black, streetwear, a playful queer look or full drag energy all make sense; the stage rewards expression more than polish. Wear shoes for a compact, loud floor and bring cash for drinks or performer support rather than treating applause as the whole tip.',
      'staff_inclusivity', 'The clearest pattern is affection for the bartenders, performers and unusually warm queer-room feeling. Guests describe powerful sound, generous hosting and drag delivered with real commitment. Evidence is enthusiastic but still small, so keep the praise specific rather than pretending there is a vast review sample.',
      'venue_classification', 'active_late_week_drag_bar_and_lgbtq_nightclub_in_beomil_with_friday_saturday_drag_monthly_themes_compact_dancefloor_local_queer_core_foreigner_friendly_reports_and_strong_bartender_performer_praise',
      'identity_note', 'TightHall is an active drag bar and LGBTQ nightclub at 28 Jaseonggongwon-ro in Busan''s Beomil nightlife cluster. Current listings show Thursday through Saturday late opening, with drag concentrated on weekends.',
      'source_urls', to_jsonb(array['https://www.instagram.com/tighthall/','https://www.travelgay.com/venue/tighthall','https://wanderlog.com/place/details/6325068','https://qlist.app/venues/South-Korea/TightHall/YytSekRuQUhpUXRwWXIybzNoZjJRQQ','https://qlist.app/cities/South-Korea/Busan/23']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','late_2300_opening_with_lighter_thursday_and_compact_friday_saturday_drag_theme_capacity_without_formal_rope_evidence','source_urls',to_jsonb(array['https://www.travelgay.com/venue/tighthall','https://wanderlog.com/place/details/6325068','https://qlist.app/cities/South-Korea/Busan/23']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_lipsync_drag_and_full_sound_with_quieter_thursday_and_monthly_theme_variation','source_urls',to_jsonb(array['https://www.instagram.com/tighthall/','https://www.travelgay.com/venue/tighthall','https://wanderlog.com/place/details/6325068']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_lgbtq_drag_supporter_younger_gay_clubber_and_multilingual_international_visitor_mix_without_supported_gender_ratio','source_urls',to_jsonb(array['https://www.travelgay.com/venue/tighthall','https://qlist.app/venues/South-Korea/TightHall/YytSekRuQUhpUXRwWXIybzNoZjJRQQ','https://wanderlog.com/place/details/6325068']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_code_with_dance_ready_streetwear_black_expressive_and_drag_style_supported_by_event_identity','source_urls',to_jsonb(array['https://www.instagram.com/tighthall/','https://www.travelgay.com/venue/tighthall']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','small_but_strong_bartender_performer_warmth_powerful_sound_and_committed_drag_consensus','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6325068','https://qlist.app/venues/South-Korea/TightHall/YytSekRuQUhpUXRwWXIybzNoZjJRQQ']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    )),
    (1766::bigint, jsonb_build_object(
      'queue_wait', 'At 20:00 or 21:00 you may have the bar and owner almost to yourself; reviews say it usually fills around 22:00–23:00. There is no club queue or status door. Walk in for a seat and conversation, then use the host''s tips if you want a busier dance floor elsewhere in Beomil.',
      'best_nights', 'Start here any evening for a serious classic cocktail and local orientation. Friday brings the strongest mix of football, regulars and visitors, while a weekday rewards solo travellers who actually want to talk. TOOL works best as the intelligent first drink, not the final all-out club.',
      'crowd_mix', 'Gay local regulars form the base, joined by Korean and international visitors who often arrive alone. English and some Japanese support make the room unusually easy for newcomers. The mood is male-leaning and intimate rather than a broad all-gender queer party, with locals and travellers mixing at the bar.',
      'dress_code', 'No dress code: jeans, clean casual layers and travel clothes are fine. The polish comes from the drinks, not the door. Sit close enough to watch the bartender work, and save your high-impact club look for wherever the night goes next.',
      'staff_inclusivity', 'Hospitality is the venue''s signature. Reviews repeatedly describe fluent English, attentive cocktail-making and an owner who writes down useful nightlife recommendations instead of letting visitors drift. That personal welcome is especially valuable in a small scene where language can otherwise feel like a wall.',
      'venue_classification', 'active_small_gay_owned_beomil_cocktail_bar_since_2014_with_quiet_early_hours_later_regular_build_classic_strong_drinks_football_interest_local_and_international_male_leaning_mix_and_exceptional_multilingual_host_consensus',
      'identity_note', 'TOOL is an active gay cocktail bar near Beomil Station, associated with address forms 14 Beomil-gil and 660-83 Beomil-dong. Current specialist listings show nightly opening from 20:00.',
      'source_urls', to_jsonb(array['https://www.travelgay.com/venue/tool','https://qlist.app/venues/Busan/TOOL/anNOK25JQmVzZ1lMQ1pzOTJhUC9EUQ','https://gayandasia.com/en/v/tool','https://www.tripadvisor.ca/Restaurant_Review-g297884-d32626809-Reviews-Tool-Busan.html','https://stg.travelgay.com/busan-gay-bars']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_status_queue_with_quiet_2000_2100_and_review_reported_2200_2300_fill_suited_to_first_drink','source_urls',to_jsonb(array['https://www.travelgay.com/venue/tool','https://www.tripadvisor.ca/Restaurant_Review-g297884-d32626809-Reviews-Tool-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','nightly_first_drink_classic_cocktail_local_orientation_with_friday_regular_visitor_and_football_energy','source_urls',to_jsonb(array['https://www.travelgay.com/venue/tool','https://www.tripadvisor.ca/Restaurant_Review-g297884-d32626809-Reviews-Tool-Busan.html','https://stg.travelgay.com/busan-gay-bars']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','male_leaning_gay_local_regular_korean_solo_and_international_visitor_mix_supported_by_multilingual_service','source_urls',to_jsonb(array['https://www.travelgay.com/venue/tool','https://qlist.app/venues/Busan/TOOL/anNOK25JQmVzZ1lMQ1pzOTJhUC9EUQ','https://gayandasia.com/en/v/tool']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_reported_code_with_casual_travel_and_neighbourhood_bar_style_while_drink_craft_supplies_polish','source_urls',to_jsonb(array['https://www.travelgay.com/venue/tool','https://qlist.app/venues/Busan/TOOL/anNOK25JQmVzZ1lMQ1pzOTJhUC9EUQ']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','repeated_attentive_fluent_english_helpful_owner_cocktail_and_local_recommendation_hospitality_consensus','source_urls',to_jsonb(array['https://www.travelgay.com/venue/tool','https://qlist.app/venues/Busan/TOOL/anNOK25JQmVzZ1lMQ1pzOTJhUC9EUQ','https://www.tripadvisor.ca/Restaurant_Review-g297884-d32626809-Reviews-Tool-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    )),
    (666::bigint, jsonb_build_object(
      'queue_wait', 'There is no current Cape Town queue. The chain closed in August 2024 after liquidation pressure, and the Green Point drag-dinner room is gone. Do not trust stale booking widgets or a 2026 event page carrying the old name; the former 40 Somerset Road venue should not receive reservations or directions.',
      'best_nights', 'The old formula peaked on drag-show and bingo evenings, when burgers, camp hosts and cabaret mattered more than a conventional dinner. That history is worth remembering, but it is not a current recommendation. Choose an active Cape Town drag calendar rather than planning around a resurrected listing.',
      'crowd_mix', 'Historically, queer diners mixed with birthday groups, bachelorettes, tourists and drag loyalists in a deliberately all-welcome room. The audience could feel more celebration-led than community-intimate. No present crowd exists after closure, so old ratings must remain clearly historical.',
      'dress_code', 'The former venue rewarded colour, sparkle and a willingness to join the joke, but never required costume. That is archival guidance only. There is no current Beefcakes door or valid dress policy in Cape Town, and any page implying otherwise risks sending dressed-up guests to a closed business.',
      'staff_inclusivity', 'Past praise centred on quick-witted drag hosts and playful service; criticism covered uneven food, ignored tables and pressure around paid extras. Closure reporting also documents financial strain. None of that proves a current team, so the record must stay hidden rather than borrow hospitality from its legacy.',
      'venue_classification', 'closed_august_2024_former_cape_town_queer_drag_dinner_cabaret_burger_bar_at_40_somerset_road_with_historic_mixed_celebration_crowd_camp_hosts_uneven_food_service_reviews_and_no_verified_reopening',
      'record_status', 'closed_former_drag_restaurant_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring',
      'identity_note', 'Beefcakes Cape Town closed with the wider South African chain in August 2024. Current closed-place reports and 2026 local discussion confirm no reopening at 40 Somerset Road; stale event and booking pages are not evidence of active trade.',
      'source_urls', to_jsonb(array['https://www.mambaonline.com/2024/08/19/end-of-an-era-beefcakes-shuts-down/','https://capetown.gaycities.com/restaurants/309325-beefcakes','https://restaurantguru.com/Beefcakes-Cape-Town','https://www.reddit.com/r/capetown/comments/1qeb3z7/drag_shows/','https://www.eatout.co.za/venue/beefcakesgreenpoint/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','confirmed_no_current_queue_after_august_2024_chain_closure_and_warning_against_stale_booking_or_event_pages','source_urls',to_jsonb(array['https://www.mambaonline.com/2024/08/19/end-of-an-era-beefcakes-shuts-down/','https://capetown.gaycities.com/restaurants/309325-beefcakes','https://restaurantguru.com/Beefcakes-Cape-Town']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_drag_and_bingo_peak_only_with_no_current_programme_or_honest_visit_recommendation','source_urls',to_jsonb(array['https://www.mambaonline.com/2024/08/19/end-of-an-era-beefcakes-shuts-down/','https://www.eatout.co.za/venue/beefcakesgreenpoint/','https://www.reddit.com/r/capetown/comments/1qeb3z7/drag_shows/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_queer_diner_birthday_bachelorette_tourist_and_drag_fan_mix_only_with_no_current_crowd','source_urls',to_jsonb(array['https://www.mambaonline.com/2024/08/19/end-of-an-era-beefcakes-shuts-down/','https://capetown.gaycities.com/restaurants/309325-beefcakes','https://www.eatout.co.za/venue/beefcakesgreenpoint/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_colour_and_camp_without_required_costume_but_no_current_door_or_valid_policy','source_urls',to_jsonb(array['https://capetown.gaycities.com/restaurants/309325-beefcakes','https://www.eatout.co.za/venue/beefcakesgreenpoint/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','historic_drag_host_and_playful_service_praise_balanced_against_uneven_table_food_and_paid_extra_reports_with_no_current_team','source_urls',to_jsonb(array['https://www.eatout.co.za/venue/beefcakesgreenpoint/','https://restaurantguru.com/Beefcakes-Cape-Town','https://www.mambaonline.com/2024/08/19/end-of-an-era-beefcakes-shuts-down/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    )),
    (1316::bigint, jsonb_build_object(
      'queue_wait', 'The balcony bar is usually an easy daytime walk-in; student deals, live bands, salsa and Pride afterparties can create a busier Long Street door later. It is not known for a hard queer selection policy. Arrive before the headline set if you want a balcony rail rather than a squeeze near the bar.',
      'best_nights', 'Follow the event post: one night can mean salsa, another an alternative band, DJ set, student games or a Pride afterparty. Early hours suit pizza and people-watching over Long Street; after midnight the same room turns louder and looser. The programme, not Friday alone, decides whether it lands.',
      'crowd_mix', 'Students, Long Street regulars, live-music fans, tourists and queer-friendly party groups share the venue. Pride dates visibly increase the LGBTQ+ presence, but an ordinary night is broadly mixed rather than a gay club. The balcony draws visitors; themed events bring more Cape Town locals.',
      'dress_code', 'Casual city-night clothes are the norm: trainers, denim, band shirts and an easy party look. Salsa or Pride editions invite more effort, but no standing fashion code is published. Keep valuables close on Long Street and dress for a room that moves between pizza tables, balcony drinks and dancing.',
      'staff_inclusivity', 'Current guides present the venue as LGBTQ-friendly and active across varied communities, but the independent review sample is thin. One published diner review is positive; that is not enough for sweeping safety claims. Treat the event host and crowd on the night as more informative than the label alone.',
      'venue_classification', 'active_mixed_long_street_balcony_cafe_bar_and_event_club_in_former_sgt_pepper_space_with_pizza_live_bands_djs_salsa_student_nights_pride_afterparties_casual_door_and_event_led_queer_presence',
      'identity_note', 'Club Tai Pan operates at 194 Long Street in the former SGT Pepper space. The stored sgtpepperct.com link represents the previous venue identity and should be replaced by the current Club Tai Pan social channel.',
      'source_urls', to_jsonb(array['https://www.instagram.com/club_tai_pan/','https://www.capetownmagazine.com/clubs/your-long-street-guide/52_22_22013','https://www.topreviews.co.za/best-gay-clubs-cape-town/','https://www.tripadvisor.co.uk/Restaurant_Review-g312659-d26766181-Reviews-Club_Tai_Pan-Cape_Town_Central_Western_Cape.html','https://www.tripadvisor.in/Attraction_Review-g312659-d26737553-Reviews-Club_Tai_Pan-Cape_Town_Central_Western_Cape.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','daytime_walkin_with_event_led_student_live_salsa_and_pride_pressure_without_hard_queer_selection_evidence','source_urls',to_jsonb(array['https://www.capetownmagazine.com/clubs/your-long-street-guide/52_22_22013','https://www.topreviews.co.za/best-gay-clubs-cape-town/','https://www.instagram.com/club_tai_pan/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','event_led_salsa_alternative_band_dj_student_game_and_pride_afterparty_variation_from_early_food_to_late_dancing','source_urls',to_jsonb(array['https://www.capetownmagazine.com/clubs/your-long-street-guide/52_22_22013','https://www.topreviews.co.za/best-gay-clubs-cape-town/','https://www.instagram.com/club_tai_pan/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_student_long_street_regular_live_music_tourist_and_queer_friendly_group_crowd_with_pride_specific_lgbtq_lift','source_urls',to_jsonb(array['https://www.capetownmagazine.com/clubs/your-long-street-guide/52_22_22013','https://www.topreviews.co.za/best-gay-clubs-cape-town/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_standing_code_with_casual_trainer_denim_band_and_event_specific_salsa_pride_style','source_urls',to_jsonb(array['https://www.capetownmagazine.com/clubs/your-long-street-guide/52_22_22013','https://www.topreviews.co.za/best-gay-clubs-cape-town/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','lgbtq_friendly_editorial_classification_and_broad_event_programme_but_thin_independent_review_sample_requires_cautious_claim','source_urls',to_jsonb(array['https://www.topreviews.co.za/best-gay-clubs-cape-town/','https://www.tripadvisor.co.uk/Restaurant_Review-g312659-d26766181-Reviews-Club_Tai_Pan-Cape_Town_Central_Western_Cape.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    )),
    (667::bigint, jsonb_build_object(
      'queue_wait', 'The new Cobern Street bar is quiet early and can feel almost private on a weekday or Sunday. Friday-Saturday events build after 21:00; recent listings offer free entry before then and a modest cover later. It is a cosy dance room, not a giant club, so arriving early matters more than winning a selective door.',
      'best_nights', 'Friday and Saturday bring DJs and the most reliable dancing; karaoke, live music and Pride dates add character beyond a playlist. Happy hour is useful for meeting people before the floor wakes up. Sunday is consistently described as very quiet, better for a drink than a destination night.',
      'crowd_mix', 'Gay men remain the visible core, joined by broader LGBTQ+ regulars, visitors and friends. The relocated room feels local and conversational before the weekend dance crowd arrives. It is less tourist-slick than old De Waterkant mythology suggests, with the energy changing sharply by hour and event.',
      'dress_code', 'Ordinary nights are relaxed: fitted casualwear, trainers and a going-out shirt work. Ticketed themes can be strict—its New Year''s event required full disco glamour and refused low effort—so read the actual listing. Never assume one costume brief is the permanent policy.',
      'staff_inclusivity', 'Recent guests split hard: some praise a welcoming manager, strong air-conditioning, quick service and a safe-feeling room; others allege arbitrary pricing, automatic tips and poor incident response. Check the amount before tapping, keep the receipt and raise discrepancies immediately.',
      'venue_classification', 'active_relocated_gay_and_lgbtq_bar_club_at_cobern_street_with_small_dancefloor_weekend_djs_karaoke_live_music_pride_events_early_quiet_local_social_energy_theme_specific_dress_and_material_billing_service_dispute_reports',
      'identity_note', 'Crew Bar is active at 10–12 Cobern Street, De Waterkant, not its former 30 Napier Street address. A May 2026 event and March 2026 reviews confirm current trade; older closed markers refer to the previous listing/location.',
      'source_urls', to_jsonb(array['https://infogaytion.com/south-africa/cape-town/events/sanctuary-at-crew-bar-cape-town','https://wanderlog.com/place/details/9264147/crew-bar','https://www.gayout.com/africa/south-africa/cape-town/bars/crew-bar-139','https://qlist.app/venues/Cape-Town/Crew-Bar/TWsyMy9jajdkY1JPa2NGeFRHWlBlZw','https://www.howler.co.za/events/the-nye-great-gatsby-gala-e7a4','https://capetowndata.com/en/products/blogpost/813/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','new_cobern_room_quiet_early_and_sunday_with_post_2100_weekend_event_build_free_early_then_modest_cover','source_urls',to_jsonb(array['https://infogaytion.com/south-africa/cape-town/events/sanctuary-at-crew-bar-cape-town','https://wanderlog.com/place/details/9264147/crew-bar','https://www.gayout.com/africa/south-africa/cape-town/bars/crew-bar-139']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_dj_dancing_plus_karaoke_live_music_and_pride_programming_with_consistently_quiet_sunday','source_urls',to_jsonb(array['https://infogaytion.com/south-africa/cape-town/events/sanctuary-at-crew-bar-cape-town','https://wanderlog.com/place/details/9264147/crew-bar','https://capetowndata.com/en/products/blogpost/813/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_male_core_broader_lgbtq_regular_visitor_and_friend_mix_with_local_early_conversation_and_weekend_dance_shift','source_urls',to_jsonb(array['https://qlist.app/venues/Cape-Town/Crew-Bar/TWsyMy9jajdkY1JPa2NGeFRHWlBlZw','https://wanderlog.com/place/details/9264147/crew-bar','https://www.gayout.com/africa/south-africa/cape-town/bars/crew-bar-139']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','relaxed_ordinary_night_style_with_strict_event_specific_nye_disco_glamour_code_not_generalized','source_urls',to_jsonb(array['https://www.howler.co.za/events/the-nye-great-gatsby-gala-e7a4','https://wanderlog.com/place/details/9264147/crew-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','current_manager_service_aircon_and_safe_room_praise_balanced_against_billing_tip_pricing_and_incident_response_complaints','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9264147/crew-bar','https://www.gayout.com/africa/south-africa/cape-town/bars/crew-bar-139','https://www.tripadvisor.com/Attraction_Review-g312659-d10435046-Reviews-Crew_Bar-Cape_Town_Central_Western_Cape.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    )),
    (1303::bigint, jsonb_build_object(
      'queue_wait', 'There is no nightlife queue: this is a seven-room heritage guesthouse with booked check-in. Send arrival details in advance because reception is handled through the wider guesthouse operation, and the check-in point can differ from the front door. Peak summer and Pride weeks are an availability problem, not a line.',
      'best_nights', 'Stay here when walking home through De Waterkant matters more than a resort scene. A warm evening in the courtyard or by the small pool suits a reset before dinner; mornings are quiet and continental. Pride season places the queer district outside your door, while ordinary weeks feel residential and discreet.',
      'crowd_mix', 'International couples, solo city-break guests and LGBTQ+ travellers choose it for the historic gay village and central access. It is not men-only and current booking feedback is broadly mixed-demographic. Tourists dominate inside; local queer life appears in the surrounding bars, cafes and streets.',
      'dress_code', 'No code beyond guesthouse common-space manners. Pool layers, linen, sightseeing clothes and a sharper dinner look all move easily through the compact house. Pack for steep Cape Town streets and changeable weather; heritage charm also means rooms and bathroom layouts vary, so read your room category.',
      'staff_inclusivity', 'Verified guests repeatedly call the team friendly, available and generous with local tips, with especially strong scores for staff, cleanliness and location. Specialist approval supports LGBTQ+ welcome. A few guests find breakfast basic or room layouts intimate, but warmth and feeling at home dominate.',
      'venue_classification', 'active_small_cape_georgian_heritage_guesthouse_at_35_loader_street_operated_by_cape_finest_with_pool_courtyard_central_gay_village_access_international_mixed_guests_verified_high_staff_location_and_cleanliness_scores',
      'identity_note', 'The current Cape Finest – De Waterkant House is at 35 Loader Street, not the stored 137 Waterkant Street. The official house site and current booking platforms agree on Loader Street and Cape Finest operation.',
      'source_urls', to_jsonb(array['https://www.dewaterkanthouse.co.za/','https://www.capefinest.co.za/','https://www.booking.com/reviews/za/hotel/dewaterkanthouse-cape-town1.html','https://www.booking.com/hotel/za/dewaterkanthouse-cape-town1.en-gb.html','https://www.expedia.com/Cape-Town-Hotels-De-Waterkant-House.h101986973.Hotel-Information','https://www.travelgay.com/hotels/de-waterkant-house-cape-town']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','booked_seven_room_guesthouse_with_advance_arrival_coordination_and_separate_checkin_point_not_nightlife_queue','source_urls',to_jsonb(array['https://www.dewaterkanthouse.co.za/','https://www.booking.com/hotel/za/dewaterkanthouse-cape-town1.en-gb.html','https://www.expedia.com/Cape-Town-Hotels-De-Waterkant-House.h101986973.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','gay_village_walkability_courtyard_pool_evening_and_quiet_morning_stay_with_pride_season_location_value','source_urls',to_jsonb(array['https://www.dewaterkanthouse.co.za/','https://www.travelgay.com/hotels/de-waterkant-house-cape-town','https://www.booking.com/reviews/za/hotel/dewaterkanthouse-cape-town1.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','international_couple_solo_city_break_and_lgbtq_traveller_mix_not_men_only_with_tourist_inside_local_queer_district_outside','source_urls',to_jsonb(array['https://www.booking.com/reviews/za/hotel/dewaterkanthouse-cape-town1.html','https://www.travelgay.com/hotels/de-waterkant-house-cape-town','https://www.expedia.com/Cape-Town-Hotels-De-Waterkant-House.h101986973.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_code_with_pool_sightseeing_and_dinner_style_plus_heritage_room_layout_variation','source_urls',to_jsonb(array['https://www.dewaterkanthouse.co.za/','https://www.booking.com/hotel/za/dewaterkanthouse-cape-town1.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','verified_high_staff_cleanliness_location_and_local_tip_praise_plus_specialist_lgbtq_approval_balanced_by_basic_breakfast_and_layout_notes','source_urls',to_jsonb(array['https://www.booking.com/reviews/za/hotel/dewaterkanthouse-cape-town1.html','https://www.expedia.com/Cape-Town-Hotels-De-Waterkant-House.h101986973.Hotel-Information','https://www.travelgay.com/hotels/de-waterkant-house-cape-town']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id = 666;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1771,1763,1769,1766,666,1316,667,1303)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
