-- Queer Atlas venue intelligence: global review-led editorial pass, batch 56.
-- Eight Caracas and Cartagena records checked against current official pages, local reporting, listings and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, never in reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (921::bigint, jsonb_build_object(
      'queue_wait', 'Sabana Grande regulars often walk in early, while weekend shows and Sunday drag can create a compact door after midnight. A minimum spend or entry condition has appeared in reviews, so ask before committing. Arrive with the current flyer, small notes and a clear ride-home plan.',
      'best_nights', 'Sunday drag is the signature; Friday and Saturday bring the liveliest pop-and-dance crowd upstairs. Earlier hours work for beer, stools and conversation before the room turns clubby. Programming shifts, so choose the performer or theme rather than assuming every weekend feels identical.',
      'crowd_mix', 'Caracas gay men form the core, joined by drag followers, queer friends, women, allies and occasional travellers. It is local and social rather than tourist-polished. Familiar faces make the room warmer, though a first visit can feel more insider-led once the late crowd takes over.',
      'dress_code', 'There is no reliable formal code: neat casual clothes, trainers and a brighter drag-night look all fit. The practical details matter more—dress for heat, keep valuables close and check whether the floor you want is open. A themed show may reward glamour without demanding it.',
      'staff_inclusivity', 'Many guests describe a friendly queer meeting place with approachable performers and bar staff. The counterweight is repeated criticism of mandatory consumption, unclear charging or uneven management at entry. Confirm the terms calmly before ordering and keep each payment visible.',
      'venue_classification', 'active_long_running_local_gay_bar_and_weekend_dance_space_in_sabana_grande_with_sunday_drag_pop_music_upstairs_social_early_hours_gay_male_core_broad_queer_visitors_and_mixed_entry_charge_management_consensus',
      'identity_note', 'La Fragata VIP+ is a local gay bar and club in Sabana Grande rather than a polished destination megaclub. Review sources disagree on exact weekly hours and entry terms, making same-day flyer verification important.',
      'source_urls', to_jsonb(array['https://gaytravelr.com/venezuela/caracas/bars-and-clubs/la-fragata-vip','https://caracas.gaycities.com/bars/311025-la-fragata-vip?vibe=drag-shows','https://wanderlog.com/es/place/details/7190186/la-fragata-bar-de-ambiente','https://qlist.app/venues/Caracas/La-Fragata-Bar-de-Ambiente/bXlPSm02eDdidlc2M05STTBzcHd0UQ','https://es.cybo.com/VE-biz/la-fragata-vip','https://www.reddit.com/r/vzla/comments/1v7192i','https://lanacionweb.com/nacional/tras-el-arresto-de-los-33-de-carabobo-como-es-una-noche-en-un-local-lgbti-en-caracas/','https://www.cruisinggays.com/caracas/bars/24128-la-fragata/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','early_walkin_weekend_sunday_drag_compact_door_and_reported_minimum_spend_entry_variation','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/7190186/la-fragata-bar-de-ambiente','https://qlist.app/venues/Caracas/La-Fragata-Bar-de-Ambiente/bXlPSm02eDdidlc2M05STTBzcHd0UQ','https://es.cybo.com/VE-biz/la-fragata-vip']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','sunday_drag_friday_saturday_pop_dance_and_early_beer_conversation_variation','source_urls',to_jsonb(array['https://caracas.gaycities.com/bars/311025-la-fragata-vip?vibe=drag-shows','https://gaytravelr.com/venezuela/caracas/bars-and-clubs/la-fragata-vip','https://www.reddit.com/r/vzla/comments/1v7192i']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_gay_male_core_drag_queer_friend_woman_ally_and_occasional_traveller_mix','source_urls',to_jsonb(array['https://lanacionweb.com/nacional/tras-el-arresto-de-los-33-de-carabobo-como-es-una-noche-en-un-local-lgbti-en-caracas/','https://qlist.app/venues/Caracas/La-Fragata-Bar-de-Ambiente/bXlPSm02eDdidlc2M05STTBzcHd0UQ']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_verified_formal_code_with_neat_casual_drag_glamour_heat_and_security_practicality','source_urls',to_jsonb(array['https://gaytravelr.com/venezuela/caracas/bars-and-clubs/la-fragata-vip','https://es.cybo.com/VE-biz/la-fragata-vip']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_queer_bar_performer_consensus_balanced_against_minimum_consumption_charge_and_management_complaints','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/7190186/la-fragata-bar-de-ambiente','https://qlist.app/venues/Caracas/La-Fragata-Bar-de-Ambiente/bXlPSm02eDdidlc2M05STTBzcHd0UQ']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (924::bigint, jsonb_build_object(
      'queue_wait', 'There is no verified daily café counter or permanent walk-in queue. This is an LGBTQ+ rights organisation and event network whose workshops, exhibitions and community sessions use announced locations. Register when the programme asks; never travel to a generic “hub” pin without the current invitation.',
      'best_nights', 'Choose a published workshop, art exhibition, training or community gathering—the programme is the place. Some work happens in daylight, some in evening cultural sessions, and much is project-based. The best visit is one you have confirmed directly, not an invented weekly café night.',
      'crowd_mix', 'LGBTQ+ activists, artists, community organisers, conflict survivors, programme participants and allies meet through its work, with an emphasis on people facing layered exclusion across Colombia’s Caribbean region. This is purposeful community space, not a tourist social bar.',
      'dress_code', 'Wear what lets you participate comfortably: everyday clothes for a workshop, something expressive for an exhibition, or practical layers for field activity. There is no hospitality door code. Respect privacy, ask before photographing and follow any safeguarding guidance for sensitive sessions.',
      'staff_inclusivity', 'Inclusion is the organisation’s actual mission, grounded in LGBTQ+ rights, peacebuilding, culture and support for people affected by violence. That is stronger evidence than generic service reviews. Still, attendance, accessibility and confidentiality arrangements belong to each programme—confirm them directly.',
      'venue_classification', 'active_colombian_caribbean_lgbtq_rights_organisation_and_event_network_with_arts_culture_training_peacebuilding_and_support_programmes_but_no_verified_permanent_public_cafe_or_daily_walkin_venue_at_stored_record',
      'record_status', 'organization_event_network_not_verified_as_permanent_walk_in_cafe_hide_from_venue_search_maps_sitemap_city_counts_and_current_venue_intelligence_scoring_until_fixed_location_is_confirmed',
      'identity_note', 'País Plural is an LGBTQ+ organisation and programme platform, not a verified daily cafe. Events may use different locations and registration rules; the record should not imply a permanent public hospitality venue.',
      'source_urls', to_jsonb(array['https://www.paisplural.org/','https://www.paisplural.org/blog','https://www.paisplural.org/event-details/segunda-exposicion-de-arte-de-la-vie-en-queer','https://editorial.lavidadenos.com/la-subita-conviccion-que-lo-desperto/','https://fln.dk/media/05gcbly2/vene243.pdf','https://www.reddit.com/r/vzla/comments/1ix22wn']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_verified_daily_cafe_or_walkin_queue_with_event_registration_and_announced_location_requirement','source_urls',to_jsonb(array['https://www.paisplural.org/','https://www.paisplural.org/event-details/segunda-exposicion-de-arte-de-la-vie-en-queer']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','programme_led_workshop_exhibition_training_and_community_gathering_without_fixed_weekly_hospitality_schedule','source_urls',to_jsonb(array['https://www.paisplural.org/blog','https://www.paisplural.org/event-details/segunda-exposicion-de-arte-de-la-vie-en-queer']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','lgbtq_activist_artist_organiser_conflict_survivor_participant_and_ally_programme_mix','source_urls',to_jsonb(array['https://www.paisplural.org/','https://editorial.lavidadenos.com/la-subita-conviccion-que-lo-desperto/','https://fln.dk/media/05gcbly2/vene243.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_hospitality_code_with_activity_specific_comfort_privacy_consent_and_safeguarding_norms','source_urls',to_jsonb(array['https://www.paisplural.org/event-details/segunda-exposicion-de-arte-de-la-vie-en-queer','https://www.paisplural.org/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','mission_based_lgbtq_rights_peacebuilding_cultural_and_violence_affected_community_inclusion_with_event_specific_access','source_urls',to_jsonb(array['https://www.paisplural.org/','https://fln.dk/media/05gcbly2/vene243.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (925::bigint, jsonb_build_object(
      'queue_wait', 'There is no single line: Sabana Grande is a nightlife corridor, not one managed venue. Pressure appears at individual bar doors on Friday and Saturday, while pavements and outdoor tables stay fluid. Check each destination’s live listing and do not follow a stale pin into an unfamiliar side street.',
      'best_nights', 'Friday and Saturday offer the clearest chance of finding several queer rooms active within one area. Earlier evening suits a drink and orientation; after midnight becomes louder and more fragmented. Recent local advice matters more than old “gay strip” mythology, because operators and safe routes change.',
      'crowd_mix', 'Local gay men and queer friends anchor the visible nightlife, with drag followers, allies and a small visitor presence moving between businesses. It is far more local than tourist-designed. Every doorway creates its own mix, so the corridor should never be described as one uniform or universally welcoming crowd.',
      'dress_code', 'There is no district dress code. Neat casual clothes and expressive nightlife looks both work, but choose shoes for walking and carry little. Keep your phone discreet between venues, use a known ride service late and read the actual bar’s theme before assuming the street sets the rules.',
      'staff_inclusivity', 'A street has no staff, safeguarding team or single complaints process. Inclusion depends on the bar, performer and security crew you choose that night. Use current community recommendations, meet friends at a named doorway and leave any room whose charging, consent or welcome feels unclear.',
      'venue_classification', 'active_historic_queer_nightlife_corridor_in_sabana_grande_comprising_independent_bars_drag_and_social_spaces_with_friday_saturday_peak_local_first_crowd_no_single_door_team_policy_or_uniform_safety_standard',
      'record_status', 'area_context_record_not_single_managed_venue_verify_each_business_live_listing_route_and_safety_conditions_before_visit',
      'identity_note', 'Sabana Grande Night Strip describes a changing urban nightlife area, not a single venue. Queue, dress, crowd and staff conditions belong to the individual businesses operating there.',
      'source_urls', to_jsonb(array['https://www.reddit.com/r/vzla/comments/1v7192i','https://www.reddit.com/r/vzla/comments/1fkxugh','https://lambda-venezuela.blogspot.com/p/caracas-gay.html','https://lanacionweb.com/nacional/tras-el-arresto-de-los-33-de-carabobo-como-es-una-noche-en-un-local-lgbti-en-caracas/','https://caracas.gaycities.com/','https://qlist.app/cities/Venezuela/Caracas/133','https://es.wikipedia.org/wiki/Cultura_LGBT_en_Venezuela']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_single_queue_with_independent_weekend_bar_door_pressure_and_live_listing_route_requirement','source_urls',to_jsonb(array['https://www.reddit.com/r/vzla/comments/1v7192i','https://qlist.app/cities/Venezuela/Caracas/133']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_area_peak_early_orientation_late_fragmentation_and_current_local_advice_priority','source_urls',to_jsonb(array['https://www.reddit.com/r/vzla/comments/1v7192i','https://caracas.gaycities.com/','https://lambda-venezuela.blogspot.com/p/caracas-gay.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_gay_queer_drag_ally_and_small_visitor_flow_varying_by_independent_door','source_urls',to_jsonb(array['https://lanacionweb.com/nacional/tras-el-arresto-de-los-33-de-carabobo-como-es-una-noche-en-un-local-lgbti-en-caracas/','https://qlist.app/cities/Venezuela/Caracas/133']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_district_code_with_individual_theme_walking_phone_and_late_transport_practicality','source_urls',to_jsonb(array['https://www.reddit.com/r/vzla/comments/1v7192i','https://caracas.gaycities.com/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_single_staff_or_safeguarding_system_with_business_specific_welcome_charging_and_consent_assessment','source_urls',to_jsonb(array['https://www.reddit.com/r/vzla/comments/1fkxugh','https://lanacionweb.com/nacional/tras-el-arresto-de-los-33-de-carabobo-como-es-una-noche-en-un-local-lgbti-en-caracas/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1236::bigint, jsonb_build_object(
      'queue_wait', 'This smaller club is easier before midnight; Friday, Saturday and drag-led dates can leave a short line once both music rooms are moving. Current sources disagree on the exact address and schedule, so confirm the flyer before travelling. Carry the cover separately and ask what it includes.',
      'best_nights', 'Saturday is the safest bet for a full floor; Friday works for a more relaxed start. Two music spaces and show nights give the place its personality, while an ordinary early weekday can feel thin. Let the current performer or DJ post decide—Cartagena’s queer calendar changes quickly.',
      'crowd_mix', 'Local gay men and LGBTQ+ friends make up the heart, with straight women, allies and tourists joining on weekends. The mood is approachable rather than ultra-curated. Cartagena visitors are visible, but locals carry the songs, requests and late-night social web that make the room feel specific.',
      'dress_code', 'No formal policy is published. Smart-casual tropical clothes, trainers and a colourful dance look fit; breathable fabric beats heavy club armour. Keep valuables close, verify the correct entrance and wear shoes you are comfortable using for a booked ride pickup after closing.',
      'staff_inclusivity', 'Available reviews frame Avatar as an affirming LGBTQ+ dance space and praise its lively atmosphere, but the review pool is much smaller than for Cartagena’s larger gay club. Treat the welcome as promising rather than proven in every detail, and confirm prices before ordering.',
      'venue_classification', 'active_small_cartagena_lgbtq_dance_club_with_two_music_rooms_weekend_and_show_led_peak_local_gay_core_mixed_queer_ally_tourist_crowd_tropical_casual_style_and_limited_but_positive_current_review_consensus',
      'identity_note', 'Avatar is listed as an LGBTQ+ dance club in Cartagena, but current directories show inconsistent location details. Verify the same-day flyer and map pin before departure.',
      'source_urls', to_jsonb(array['https://www.tripadvisor.co/Attraction_Review-g297476-d23879063-Reviews-Avatar_Gastro_Bar-Cartagena_Cartagena_District_Bolivar_Department.html','https://qlist.app/venues/Cartagena/Avatar-Disco-Bar/SE14QTA0TGY1YWhnbnZGT25qTXNSQQ','https://es.cybo.com/CO-biz/avatar-disco-bar','https://www.gayout.com/south-america/colombia/cartagena/bars/avatar-disco-bar','https://wanderlog.com/place/details/12913188','https://www.gaybnbtravel.com/place/avatar-disco-bar']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_club_early_ease_weekend_show_peak_and_current_address_schedule_verification_need','source_urls',to_jsonb(array['https://qlist.app/venues/Cartagena/Avatar-Disco-Bar/SE14QTA0TGY1YWhnbnZGT25qTXNSQQ','https://wanderlog.com/place/details/12913188','https://es.cybo.com/CO-biz/avatar-disco-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','saturday_peak_friday_relaxed_two_room_show_and_live_programme_variation','source_urls',to_jsonb(array['https://www.tripadvisor.co/Attraction_Review-g297476-d23879063-Reviews-Avatar_Gastro_Bar-Cartagena_Cartagena_District_Bolivar_Department.html','https://qlist.app/venues/Cartagena/Avatar-Disco-Bar/SE14QTA0TGY1YWhnbnZGT25qTXNSQQ']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_gay_lgbtq_friend_woman_ally_and_weekend_tourist_mix','source_urls',to_jsonb(array['https://qlist.app/venues/Cartagena/Avatar-Disco-Bar/SE14QTA0TGY1YWhnbnZGT25qTXNSQQ','https://www.gaybnbtravel.com/place/avatar-disco-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_code_with_tropical_smart_casual_expressive_breathable_and_late_transport_practicality','source_urls',to_jsonb(array['https://www.tripadvisor.co/Attraction_Review-g297476-d23879063-Reviews-Avatar_Gastro_Bar-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.gayout.com/south-america/colombia/cartagena/bars/avatar-disco-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','affirming_lgbtq_atmosphere_signal_with_small_review_pool_and_price_confirmation_caution','source_urls',to_jsonb(array['https://qlist.app/venues/Cartagena/Avatar-Disco-Bar/SE14QTA0TGY1YWhnbnZGT25qTXNSQQ','https://wanderlog.com/place/details/12913188']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1225::bigint, jsonb_build_object(
      'queue_wait', 'This is a community organisation, not a drop-in cafe or club. Casa Afirmativa activities are programme-led: workshops, cultural work, rights support and community processes may require contact or registration. Use the current organisation channel before visiting rather than relying on this generic pin.',
      'best_nights', 'There is no weekly “best night.” Go for a confirmed training, arts programme, community meeting or support appointment that matches your needs. Much of the work happens by project and in daytime hours; public cultural dates can be livelier, but the invitation sets the time and place.',
      'crowd_mix', 'LGBTQ+ people from Cartagena and the wider Caribbean region are central, especially communities affected by violence, displacement and structural exclusion. Activists, artists, participants and allies join around specific programmes. It is local, purposeful and not designed as tourist entertainment.',
      'dress_code', 'Everyday, respectful and activity-ready is right. There is no nightlife fashion gate. For sensitive support or rights work, privacy and consent matter more than appearance; do not photograph people or share locations without permission. Follow the organiser’s accessibility and safeguarding notes.',
      'staff_inclusivity', 'The organisation exists to defend LGBTQ+ rights and build safer community conditions through culture, training, advocacy and care. That mission is substantive evidence of inclusion, but it is not a promise that every programme is open access. Contact the team about confidentiality, language and support needs.',
      'venue_classification', 'active_lgbtq_rights_and_community_organisation_programme_in_cartagena_with_caribbean_regional_advocacy_culture_training_support_and_conflict_affected_population_focus_but_not_a_verified_daily_public_hospitality_venue',
      'record_status', 'community_organisation_programme_not_walk_in_cafe_verify_current_office_event_location_registration_and_access_before_visit',
      'identity_note', 'Casa Afirmativa is part of Caribe Afirmativo’s community strategy, not a conventional cafe. Public access, location and hours depend on the active programme.',
      'source_urls', to_jsonb(array['https://www.caribeafirmativo.lgbt/','https://www.caribeafirmativo.lgbt/casas-caribe-afirmativo/nuestras-casas/','https://www.caribeafirmativo.lgbt/category/agenda/','https://www.atlantico.gov.co/images/stories/ciad/investigaciones/cifras_caribe_afirmativo_2007_2011.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','community_organisation_without_hospitality_queue_and_programme_contact_registration_requirement','source_urls',to_jsonb(array['https://www.caribeafirmativo.lgbt/','https://www.caribeafirmativo.lgbt/casas-caribe-afirmativo/nuestras-casas/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','confirmed_training_arts_meeting_support_or_public_culture_programme_instead_of_weekly_night','source_urls',to_jsonb(array['https://www.caribeafirmativo.lgbt/category/agenda/','https://www.caribeafirmativo.lgbt/casas-caribe-afirmativo/nuestras-casas/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_caribbean_lgbtq_conflict_affected_activist_artist_participant_and_ally_programme_mix','source_urls',to_jsonb(array['https://www.caribeafirmativo.lgbt/casas-caribe-afirmativo/nuestras-casas/','https://www.atlantico.gov.co/images/stories/ciad/investigaciones/cifras_caribe_afirmativo_2007_2011.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_fashion_gate_with_activity_readiness_privacy_consent_accessibility_and_safeguarding_priority','source_urls',to_jsonb(array['https://www.caribeafirmativo.lgbt/','https://www.caribeafirmativo.lgbt/casas-caribe-afirmativo/nuestras-casas/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','mission_grounded_lgbtq_rights_culture_training_advocacy_and_care_with_programme_specific_access','source_urls',to_jsonb(array['https://www.caribeafirmativo.lgbt/','https://www.caribeafirmativo.lgbt/casas-caribe-afirmativo/nuestras-casas/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1230::bigint, jsonb_build_object(
      'queue_wait', 'Before 23:30 the door and bars are usually manageable; weekends fill the lower dance area and can create a cover line later. Ask the price before paying—reviews repeatedly disagree on cover and drink transparency. Book a known ride for the Pie del Cerro pickup rather than improvising outside.',
      'best_nights', 'Friday and especially Saturday show the full three-level idea: an intimate bar, bigger indoor-outdoor dance area with DJ and dancers, then a darker upper floor. A Monday can still be social but much smaller. Go after 23:30 for heat; earlier if you want to map the rooms first.',
      'crowd_mix', 'Local gay men are the anchor, joined by LGBTQ+ friends and a steady stream of international visitors searching for Cartagena’s dedicated queer nightlife. Weekends feel broader and friendlier; quiet nights expose the local regular network. The upper dark room is men-focused even when the club floor is mixed.',
      'dress_code', 'Tropical club casual works: trainers, fitted tees, shorts or a bolder dance look. There is no reported fashion gate, and ventilation matters more than tailoring. Bring minimal valuables, clarify every charge and remember that a dark-room floor changes the context—not the need for consent.',
      'staff_inclusivity', 'Many reviews single out friendly bartenders, good music and teams who work hard to lift a quiet night. Others report unclear cover, inconsistent pricing or an intimidating late pickup area. The room is explicitly gay; operational trust is strongest when costs are agreed before service.',
      'venue_classification', 'active_multi_level_gay_nightclub_in_pie_del_cerro_cartagena_with_intimate_bar_indoor_outdoor_dance_floor_dj_gogo_performance_upper_dark_room_weekend_peak_local_core_international_visitors_and_mixed_price_transparency_consensus',
      'identity_note', 'Gabanna is a dedicated gay club just outside Cartagena’s central tourist core. Reviews consistently describe multiple levels, but also make transport planning and upfront price confirmation important.',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/6698995/gabanna-bar-club-cartagena','https://qlist.app/venues/Cartagena-de-Indias/Gabanna-Bar-Club-Cartagena/NmtCMENvbU9oanM0VUJuZlJwanRFdw','https://www.reddit.com/r/cartagena/comments/1gayrrt','https://www.reddit.com/r/gaytravel/comments/1eiwakv']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','pre_2330_ease_weekend_late_cover_line_repeated_price_transparency_and_planned_ride_need','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6698995/gabanna-bar-club-cartagena','https://qlist.app/venues/Cartagena-de-Indias/Gabanna-Bar-Club-Cartagena/NmtCMENvbU9oanM0VUJuZlJwanRFdw']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_three_level_full_operation_with_late_peak_and_quieter_weekday_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6698995/gabanna-bar-club-cartagena','https://qlist.app/venues/Cartagena-de-Indias/Gabanna-Bar-Club-Cartagena/NmtCMENvbU9oanM0VUJuZlJwanRFdw']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_gay_male_core_lgbtq_friend_international_visitor_and_men_focused_upper_dark_room_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6698995/gabanna-bar-club-cartagena','https://www.reddit.com/r/gaytravel/comments/1eiwakv']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_fashion_gate_with_tropical_dancewear_ventilation_valuables_charge_and_dark_room_consent_practicality','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6698995/gabanna-bar-club-cartagena']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_bartender_music_and_effort_praise_balanced_against_cover_price_and_pickup_area_concerns','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6698995/gabanna-bar-club-cartagena','https://qlist.app/venues/Cartagena-de-Indias/Gabanna-Bar-Club-Cartagena/NmtCMENvbU9oanM0VUJuZlJwanRFdw']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1249::bigint, jsonb_build_object(
      'queue_wait', 'Hotel arrival is orderly, but the rooftop pool and sunset tables are the scarce currency. Check-in can gather in mid-afternoon; restaurant and terrace reservations are smarter in high season. The walled-city position saves time later—you can walk out rather than wait for nightlife transport.',
      'best_nights', 'Stay for a slow rooftop sunset, then step into the old city for dinner and dancing. Friday and Saturday feel festive outside; a weekday gives the former convent’s courtyards more quiet. This is heritage luxury, not a queer party hotel, so let Cartagena provide the night.',
      'crowd_mix', 'Affluent international couples, celebration trips, families and heritage-minded travellers dominate, alongside Colombian guests. LGBTQ+ couples fit into a mainstream luxury mix rather than a visible community scene. The balance is distinctly visitor-heavy, especially around the rooftop and breakfast.',
      'dress_code', 'Polished resort wear suits the colonial setting: linen, dresses, tailored shorts and a smart dinner layer. There is no evidence of a discriminatory fashion door, but public spaces lean elegant rather than beach-casual. Pack shoes for old-city stone and something light enough for the heat.',
      'staff_inclusivity', 'Recent verified guests praise kind, available staff, immaculate rooms and notably attentive restaurant service; location and comfort score highest. No dedicated LGBTQ+ policy or training evidence surfaced, so the safest claim is excellent general hospitality. Couples should state bedding preferences clearly at booking.',
      'venue_classification', 'active_mainstream_five_star_heritage_hotel_in_former_walled_city_convent_with_rooftop_pool_courtyards_restaurants_affluent_international_and_colombian_guest_mix_strong_verified_service_cleanliness_location_consensus',
      'identity_note', 'Charleston Santa Teresa is a mainstream luxury heritage hotel, not a queer-specific property. Its relevance is a central walled-city location and strong general hospitality evidence, not dedicated LGBTQ+ programming.',
      'source_urls', to_jsonb(array['https://www.booking.com/reviews/co/hotel/charleston-santa-teresa.en-gb.html','https://www.booking.com/hotel/co/charleston-santa-teresa.html','https://www.tripadvisor.com/Hotel_Review-g297476-d301962-Reviews-Hotel_Charleston_Santa_Teresa-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.expedia.com/Cartagena-Hotels-Charleston-Santa-Teresa-Cartagena.h889840.Hotel-Information','https://seguimientopot.cartagena.gov.co/sites/default/files/documentos/normativa/2025-01/RES%2C%201959%20ABRIL%2011-2024%20%20HOTELES%20CHARESTON%20S.A.S%20EXT-AMC-0020867-2024%20notificado.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','orderly_hotel_arrival_afternoon_checkin_rooftop_sunset_capacity_high_season_reservation_and_walkable_location','source_urls',to_jsonb(array['https://www.booking.com/hotel/co/charleston-santa-teresa.html','https://www.booking.com/reviews/co/hotel/charleston-santa-teresa.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','rooftop_sunset_weekend_old_city_energy_and_quieter_weekday_heritage_stay_variation','source_urls',to_jsonb(array['https://www.booking.com/hotel/co/charleston-santa-teresa.html','https://www.tripadvisor.com/Hotel_Review-g297476-d301962-Reviews-Hotel_Charleston_Santa_Teresa-Cartagena_Cartagena_District_Bolivar_Department.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','affluent_international_couple_celebration_family_heritage_and_colombian_mainstream_visitor_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/charleston-santa-teresa.en-gb.html','https://www.expedia.com/Cartagena-Hotels-Charleston-Santa-Teresa-Cartagena.h889840.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','polished_resort_heritage_elegance_without_verified_formal_or_discriminatory_door_code','source_urls',to_jsonb(array['https://www.booking.com/hotel/co/charleston-santa-teresa.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_kind_available_restaurant_service_cleanliness_and_comfort_consensus_without_verified_lgbtq_specific_training','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/charleston-santa-teresa.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297476-d301962-Reviews-Hotel_Charleston_Santa_Teresa-Cartagena_Cartagena_District_Bolivar_Department.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1227::bigint, jsonb_build_object(
      'queue_wait', 'This 40-storey resort hotel processes arrivals efficiently, though afternoon check-in, breakfast and the infinity-pool lifts can bunch in high season. There is no nightlife door. Reserve dining at peak hours and leave margin for elevators if sunset at the pools is part of the plan.',
      'best_nights', 'Choose a clear evening for the pool-deck view, then ride into Getsemaní or the walled city when you want character and nightlife. Weekends bring families and celebration groups; weekdays can feel calmer and more businesslike. Bocagrande offers ease and beach access, not a queer scene downstairs.',
      'crowd_mix', 'International holidaymakers, Colombian families, couples, conference guests and loyalty travellers create a large mainstream mix. LGBTQ+ couples are part of that flow, not a distinct house crowd. Visitors overwhelmingly outnumber locals except at meetings, restaurants and invited celebrations.',
      'dress_code', 'Modern resort casual works everywhere outside formal functions: swimwear at the pools, covered-up clothes in lifts and lobby, linen or smart casual for dinner. No fashion gate is reported. Air-conditioning is strong, sun is stronger, and the polished tower still rewards practical layers.',
      'staff_inclusivity', 'Large-sample reviews praise friendly staff, cleanliness and responsive service, with occasional billing or tax complaints. No property-specific LGBTQ+ training evidence was found. Confirm taxes, bedding and guest names in writing; the general record supports expecting professional handling.',
      'venue_classification', 'active_large_mainstream_five_star_bocagrande_waterfront_hotel_with_infinity_pools_restaurants_conference_and_family_facilities_international_colombian_leisure_business_mix_and_strong_large_sample_general_service_consensus',
      'identity_note', 'Hyatt Regency Cartagena is a mainstream waterfront hotel in Bocagrande, not an LGBTQ+ hotel. Its value is reliable full-service infrastructure and beach proximity; dedicated queer nightlife requires travel elsewhere.',
      'source_urls', to_jsonb(array['https://www.hyatt.com/hyatt-regency/en-US/ctgrc-hyatt-regency-cartagena','https://www.hyatt.com/hyatt-regency/en-US/ctgrc-hyatt-regency-cartagena/reviews','https://www.booking.com/reviews/co/hotel/hyatt-regency-cartagena.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297476-d10273630-Reviews-Hyatt_Regency_Cartagena-Cartagena_Cartagena_District_Bolivar_Department.html','https://assets.hyatt.com/content/dam/hyatt/hyattdam/documents/2019/12/12/1215/Hyatt-Regency-Cartagena-Fact-Sheet-English.pdf','https://www.reddit.com/r/cartagena/comments/1uef5ez/hyatt_regency/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','large_hotel_afternoon_checkin_breakfast_pool_lift_peak_without_nightlife_door_and_dining_reservation_need','source_urls',to_jsonb(array['https://www.hyatt.com/hyatt-regency/en-US/ctgrc-hyatt-regency-cartagena','https://www.booking.com/reviews/co/hotel/hyatt-regency-cartagena.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','clear_pool_sunset_weekend_family_celebration_weekday_business_and_offsite_old_city_nightlife_variation','source_urls',to_jsonb(array['https://assets.hyatt.com/content/dam/hyatt/hyattdam/documents/2019/12/12/1215/Hyatt-Regency-Cartagena-Fact-Sheet-English.pdf','https://www.reddit.com/r/cartagena/comments/1uef5ez/hyatt_regency/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','international_colombian_family_couple_conference_loyalty_and_mainstream_lgbtq_guest_mix','source_urls',to_jsonb(array['https://www.hyatt.com/hyatt-regency/en-US/ctgrc-hyatt-regency-cartagena/reviews','https://www.booking.com/reviews/co/hotel/hyatt-regency-cartagena.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','modern_resort_casual_pool_coverup_smart_dinner_and_weather_airconditioning_practicality_without_reported_gate','source_urls',to_jsonb(array['https://www.hyatt.com/hyatt-regency/en-US/ctgrc-hyatt-regency-cartagena','https://assets.hyatt.com/content/dam/hyatt/hyattdam/documents/2019/12/12/1215/Hyatt-Regency-Cartagena-Fact-Sheet-English.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_large_sample_friendly_responsive_service_consensus_with_tax_billing_consistency_caveats_and_no_verified_lgbtq_training','source_urls',to_jsonb(array['https://www.hyatt.com/hyatt-regency/en-US/ctgrc-hyatt-regency-cartagena/reviews','https://www.booking.com/reviews/co/hotel/hyatt-regency-cartagena.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297476-d10273630-Reviews-Hyatt_Regency_Cartagena-Cartagena_Cartagena_District_Bolivar_Department.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (924);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (921,924,925,1236,1225,1230,1249,1227)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
