-- Queer Atlas venue intelligence: global review-led editorial pass, batch 40.
-- Eight Bogota records, individually researched and rewritten.
-- General hotels and mixed clubs are not presented as dedicated LGBTQ+ venues without supporting evidence.
-- Checked 2026-08-06. Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1679::bigint, jsonb_build_object(
      'queue_wait', 'The desk runs 24 hours, and arrivals are usually straightforward. Room readiness matters more: check-in starts at 3pm, so an early flight may mean storing bags. Guests praise efficient service; request airport transfer, early access or two beds ahead rather than negotiating after arrival.',
      'best_nights', 'Choose this for a calm Zona G base when dinner and sleep matter more than being above a club. Weeknights suit business travellers; weekends put Chapinero dining and queer nightlife within a short ride while keeping the room quieter. Ask for breakfast inclusion, since recent guests like it but want more variety.',
      'crowd_mix', 'Colombian business guests, couples, families and international travellers share a polished four-star hotel. It is certified as an LGBTQ+-friendly business, yet the public areas are mainstream and mixed—not a queer social hotel. You gain a comfortable base and recognised welcome, not a built-in community crowd.',
      'dress_code', 'There is no guest dress code. Smart casual works for the restaurant and Zona G; comfortable layers suit the room and Bogotá’s cool mornings. Pack a slightly sharper dinner look if you want it, but reception is used to luggage and travel clothes. Rooms have no air-conditioning, so light sleepwear can still be useful.',
      'staff_inclusivity', 'The hotel carries recognised LGBTQ+-friendly certification, and 2026 verified guests score the team especially highly for kindness and service. Cleanliness, spacious rooms and Wi-Fi also rate well. Public trans-specific procedures are not detailed, so add names, pronouns and any privacy request to the booking.',
      'venue_classification', 'active_four_star_zona_g_hotel_with_formal_lgbtq_friendly_business_recognition_spacious_clean_rooms_strong_current_staff_scores_and_mainstream_mixed_guest_profile',
      'source_urls', to_jsonb(array['https://www.estelarsuitesjones.com/en/','https://www.booking.com/reviews/co/hotel/estelar-suite-jones.en-gb.html','https://www.travelgay.com/hotels/hotel-estelar-suites-jones-bogota-colombia','https://www.expedia.com/Bogota-Hotels-Hotel-Estelar-Suites-Jones.h1378317.Hotel-Information','https://www.idt.gov.co/sites/default/files/Guia-LGBTI-Digital.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','twenty_four_hour_desk_three_pm_checkin_and_strong_current_service_consensus','source_urls',to_jsonb(array['https://www.estelarsuitesjones.com/en/','https://www.booking.com/reviews/co/hotel/estelar-suite-jones.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','zona_g_quiet_business_weeknight_weekend_dining_nightlife_base_and_breakfast_feedback','source_urls',to_jsonb(array['https://www.estelarsuitesjones.com/en/','https://www.booking.com/reviews/co/hotel/estelar-suite-jones.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294074-d1208258-Reviews-Hotel_Estelar_Suites_Jones-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','business_couple_family_and_international_guest_mix_with_official_friendly_biz_recognition_but_no_queer_social_identity','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/estelar-suite-jones.en-gb.html','https://www.idt.gov.co/sites/default/files/Guia-LGBTI-Digital.pdf','https://www.travelgay.com/hotels/hotel-estelar-suites-jones-bogota-colombia']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','general_hotel_zona_g_restaurant_cool_weather_and_no_air_conditioning_context_without_guest_code','source_urls',to_jsonb(array['https://www.estelarsuitesjones.com/en/','https://www.booking.com/reviews/co/hotel/estelar-suite-jones.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','formal_lgbtq_friendly_recognition_and_high_current_staff_cleanliness_room_wifi_scores_with_trans_process_gap','source_urls',to_jsonb(array['https://www.idt.gov.co/sites/default/files/Guia-LGBTI-Digital.pdf','https://www.booking.com/reviews/co/hotel/estelar-suite-jones.en-gb.html','https://www.expedia.com/Bogota-Hotels-Hotel-Estelar-Suites-Jones.h1378317.Hotel-Information']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1669::bigint, jsonb_build_object(
      'queue_wait', 'Reserve before you go: even prepaid groups report arguments at the door, extra cover for late arrivals and crowding once inside. A booking can reduce or remove cover on some nights, but save the confirmation and arrive together. Confirm the exact charge before entry; the rooftop can be packed even on Monday.',
      'best_nights', 'Saturday’s day-party brunch and weekend fiestas show the glossy rooftop at full volume; a weekday is easier for skyline drinks and conversation. Music moves through Latin, urban and electronic sets rather than one underground lane. Choose the event, reserve, and expect a long night—the current schedule runs to 5am.',
      'crowd_mix', 'Zona T locals, birthday groups, couples, corporate parties and international visitors mix across ages. Queer guests are present in a cosmopolitan crowd, but no reliable current evidence establishes an LGBTQ+-majority floor or trans-specific safe-space programme. Treat it as mainstream nightlife, not a community venue.',
      'dress_code', 'Go polished rather than sporty: rooftop partywear, smart separates and clean shoes fit the photo-conscious setting. A published universal code was not found, but door discretion is real. Add a light layer for the open-air edge, then keep the outfit breathable—the interior is often described as hot and overfilled.',
      'staff_inclusivity', 'Many guests praise courteous staff, cocktails and atmosphere. The risk signal is unusually consistent: foreigners report inflated totals, undisclosed service charges and reservation disputes. Check the menu, terminal amount and tip before paying. A current listing marks the venue as not wheelchair accessible.',
      'venue_classification', 'active_mainstream_zona_t_rooftop_nightclub_with_weeklong_late_hours_mixed_local_visitor_crowd_reservation_value_and_material_overcharge_door_crowding_access_concerns',
      'source_urls', to_jsonb(array['https://federalrooftop.com/','https://es.restaurantguru.com/Federal-Rooftop-Bogota-Bogota','https://restaurantguru.com/Federal-Rooftop-Bogota-Bogota','https://wanderlog.com/place/details/6610688/federal-rooftop--the-best-nightclub-in-bogot%C3%A1','https://wanderlog.com/list/geoCategory/1806675/best-rooftop-spots-in-bogota']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','reservation_cover_prepaid_group_late_arrival_door_dispute_and_even_monday_crowding_reports','source_urls',to_jsonb(array['https://es.restaurantguru.com/Federal-Rooftop-Bogota-Bogota','https://wanderlog.com/place/details/6610688/federal-rooftop--the-best-nightclub-in-bogot%C3%A1']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','saturday_day_party_weekend_fiesta_weekday_rooftop_and_current_five_am_schedule','source_urls',to_jsonb(array['https://federalrooftop.com/','https://wanderlog.com/place/details/6610688/federal-rooftop--the-best-nightclub-in-bogot%C3%A1','https://es.restaurantguru.com/Federal-Rooftop-Bogota-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','zona_t_local_birthday_couple_corporate_and_international_mixed_age_mainstream_crowd_without_verified_lgbtq_majority','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6610688/federal-rooftop--the-best-nightclub-in-bogot%C3%A1','https://es.restaurantguru.com/Federal-Rooftop-Bogota-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','polished_photo_conscious_rooftop_door_discretion_cold_air_and_hot_crowded_interior_context_without_written_code','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6610688/federal-rooftop--the-best-nightclub-in-bogot%C3%A1','https://wanderlog.com/list/geoCategory/1806675/best-rooftop-spots-in-bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','courteous_service_cocktail_atmosphere_praise_balanced_against_multiple_foreigner_overcharge_tip_reservation_and_access_reports','source_urls',to_jsonb(array['https://es.restaurantguru.com/Federal-Rooftop-Bogota-Bogota','https://restaurantguru.com/Federal-Rooftop-Bogota-Bogota','https://wanderlog.com/place/details/6610688/federal-rooftop--the-best-nightclub-in-bogot%C3%A1']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1678::bigint, jsonb_build_object(
      'queue_wait', 'Reception is open around the clock and check-in starts at 3pm. Guests describe friendly, organised arrivals, but make room requests before travel. If stairs or sleep matter, ask for a quiet one-level room away from the ground-floor restaurant—not whichever loft remains on arrival.',
      'best_nights', 'Use it as a good-value Chapinero base with breakfast and an easy ride to queer nightlife. A weekday is calmer; weekend stays need a room away from the restaurant, which some guests hear into early morning. The stylish split-level rooms look fun, but a single-level layout is the smarter choice after a 5am club night.',
      'crowd_mix', 'Solo travellers, couples, families and international guests share this small artsy hotel. The neighbourhood is queer-visible, but the property is a general boutique stay without verified LGBTQ+-specific programming. Expect a mixed crowd and welcoming staff, not a queer-community social lobby.',
      'dress_code', 'No dress code—arrive in travel clothes and save the sparkle for Chapinero. Practical details matter more: warm layers for Bogotá, secure shoes on loft stairs and a small night bag for rides home. If mobility or balance is a concern, request a one-level room; some spiral staircases are described as difficult at night.',
      'staff_inclusivity', 'Verified guests praise patient, friendly reception, help across language differences and strong cleanliness. No public trans, same-gender-couple or anti-discrimination policy was found. State names and pronouns in advance; treat the warm service record as encouraging, not formal proof.',
      'venue_classification', 'active_general_boutique_chapinero_hotel_with_strong_current_staff_cleanliness_value_and_breakfast_reviews_mixed_traveller_profile_and_material_room_noise_stair_access_considerations',
      'source_urls', to_jsonb(array['https://www.hotelesgrace.com/grace-chapinero/','https://www.booking.com/hotel/co/grace-chapinero.en-gb.html','https://www.expedia.com/Bogota-Hotels-Grace-Chapinero.h88611203.Hotel-Information','https://www.hotels.com/en/ho2836558496/grace-chapinero-bogota-colombia/','https://en.planetofhotels.com/colombia/bogota/grace-chapinero']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','twenty_four_hour_reception_three_pm_checkin_friendly_arrival_and_prebooked_room_layout_noise_request_context','source_urls',to_jsonb(array['https://www.hotelesgrace.com/grace-chapinero/','https://www.booking.com/hotel/co/grace-chapinero.en-gb.html','https://www.hotels.com/en/ho2836558496/grace-chapinero-bogota-colombia/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekday_quiet_weekend_restaurant_noise_chapinero_nightlife_base_and_single_level_postclub_room_guidance','source_urls',to_jsonb(array['https://www.expedia.com/Bogota-Hotels-Grace-Chapinero.h88611203.Hotel-Information','https://www.hotels.com/en/ho2836558496/grace-chapinero-bogota-colombia/','https://en.planetofhotels.com/colombia/bogota/grace-chapinero']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','solo_couple_family_international_general_boutique_guest_mix_without_verified_lgbtq_specific_programme','source_urls',to_jsonb(array['https://www.booking.com/hotel/co/grace-chapinero.en-gb.html','https://www.expedia.com/Bogota-Hotels-Grace-Chapinero.h88611203.Hotel-Information']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','general_hotel_travelwear_cold_weather_night_bag_and_material_loft_spiral_stair_access_context','source_urls',to_jsonb(array['https://www.hotels.com/en/ho2836558496/grace-chapinero-bogota-colombia/','https://www.booking.com/hotel/co/grace-chapinero.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_verified_patient_friendly_language_help_and_cleanliness_scores_without_published_queer_specific_policy','source_urls',to_jsonb(array['https://www.booking.com/hotel/co/grace-chapinero.en-gb.html','https://www.expedia.com/Bogota-Hotels-Grace-Chapinero.h88611203.Hotel-Information','https://en.planetofhotels.com/colombia/bogota/grace-chapinero']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1193::bigint, jsonb_build_object(
      'queue_wait', 'Arrival is usually calm, with 24-hour reception and consistently helpful front-desk reviews. Check room size before booking: the smallest doubles and angled bathrooms can feel tight, so changing category at the desk may be hard when full. For early arrival, request bag storage and confirm whether breakfast is included.',
      'best_nights', 'This leafy, design-led house is best when you want a peaceful return after Chapinero rather than nightlife in the building. Any night works, but rooms above the restaurant can hear constant music; ask for the opposite side or third floor. The veranda breakfast and garden-like common spaces shine on a slow morning.',
      'crowd_mix', 'Solo travellers, design-minded couples, business guests and international visitors mingle over breakfast and in the courtyard. The hotel sits near queer Bogotá but is not documented as an LGBTQ+-specific property. Its mood is intimate and cosmopolitan, with more quiet guests and food travellers than party groups.',
      'dress_code', 'No dress code: relaxed city clothes fit the plant-filled rooms. Pack layers because there is no air-conditioning and open windows shift from warm to chilly. For a late return, use a secure small bag and app-based ride; the hotel is calm enough that full clubwear simply reads as your night out.',
      'staff_inclusivity', 'Verified reviews give reception and housekeeping strong marks for friendly help, cleanliness and quick room changes. Restaurant service varies, with missed orders and slow breakfast reported. No written queer or trans policy was found, so communicate names and privacy needs before arrival.',
      'venue_classification', 'active_general_design_boutique_hotel_in_quieter_chapinero_with_high_current_location_cleanliness_comfort_and_staff_scores_mixed_guest_profile_and_room_restaurant_noise_service_variation',
      'source_urls', to_jsonb(array['https://www.habhotel.com/','https://www.booking.com/reviews/co/hotel/hab-bogota.en-gb.html','https://www.booking.com/reviews/co/hotel/hab-bogota.es.html','https://www.tripadvisor.com/Hotel_Review-g294074-d23367951-Reviews-Hab_Hotel-Bogota.html','https://wanderlog.com/place/details/2355480']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','calm_twenty_four_hour_arrival_helpful_front_desk_room_size_and_early_bag_breakfast_context','source_urls',to_jsonb(array['https://www.habhotel.com/','https://www.booking.com/reviews/co/hotel/hab-bogota.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','quiet_return_veranda_garden_morning_and_material_restaurant_music_room_location_guidance','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/hab-bogota.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294074-d23367951-Reviews-Hab_Hotel-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','solo_design_couple_business_international_food_traveller_mix_without_lgbtq_specific_property_identity','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/hab-bogota.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294074-d23367951-Reviews-Hab_Hotel-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_design_hotel_no_air_conditioning_open_window_weather_and_late_ride_practical_context','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/hab-bogota.en-gb.html','https://www.habhotel.com/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_reception_housekeeping_cleanliness_and_room_change_praise_balanced_against_restaurant_service_variation_and_policy_gap','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/hab-bogota.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294074-d23367951-Reviews-Hab_Hotel-Bogota.html','https://wanderlog.com/place/details/2355480']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1675::bigint, jsonb_build_object(
      'queue_wait', 'This tiny hotel uses a locked entrance and doorbell rather than a large lobby. One staff member may cover both reception and cleaning, so entry can take a moment—and the bell is audible throughout the building. Tell the desk when you expect to return late, and confirm bag storage before an early arrival.',
      'best_nights', 'Pick it for budget-friendly proximity to Chapinero bars, not resort facilities. Weeknights reduce street and neighbouring-room noise; weekends put you close to the action but may interrupt sleep. The advertised sauna was reported out of service in 2026, so book for the clean room and location, never for that amenity.',
      'crowd_mix', 'Solo travellers, couples, locals and budget-conscious international guests use this small three-star property. It sits in a queer nightlife district but has no verified LGBTQ+-specific hotel identity. Reviews describe a local-neighbourhood feel with few tourist trappings, not an on-site social scene.',
      'dress_code', 'There is no dress code. Travel basics and a warm layer are enough; use shoes and a small bag suited to walking between nearby venues. The more important check is the room itself: locks, safe, hot water and toiletries receive mixed reports. Inspect them after check-in while staff can still help.',
      'staff_inclusivity', 'The dominant signal is kind, helpful staff and very good location, with many guests praising cleanliness. A minority report shabby rooms, weak locks, night noise and staff not resolving loud music. No explicit queer or trans policy is published, so confirm privacy, visitor and ID-name needs directly before booking.',
      'venue_classification', 'active_small_budget_chapinero_hotel_with_friendly_staff_cleanliness_and_location_strength_but_no_verified_lgbtq_specific_identity_and_material_doorbell_noise_lock_water_and_sauna_issues',
      'source_urls', to_jsonb(array['https://www.booking.com/hotel/co/boutique-san-sebastian-bogota.es.html','https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.en-gb.html','https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.es.html','https://www.tripadvisor.com.br/Hotel_Review-g294074-d2504274-Reviews-Hotel_Boutique_San_Sebastian-Bogota.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','locked_door_doorbell_single_staff_late_return_and_early_bag_context','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','budget_nightlife_location_weeknight_noise_advantage_weekend_sleep_tradeoff_and_broken_sauna_report','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.en-gb.html','https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.es.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','solo_couple_local_budget_international_general_hotel_mix_with_local_neighbourhood_feel_and_no_lgbtq_specific_identity','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.en-gb.html','https://www.tripadvisor.com.br/Hotel_Review-g294074-d2504274-Reviews-Hotel_Boutique_San_Sebastian-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','general_hotel_travelwear_late_walk_and_material_lock_safe_hot_water_toiletry_inspection_context','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.en-gb.html','https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.es.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_kind_helpful_cleanliness_location_consensus_balanced_against_room_lock_noise_resolution_issues_and_no_queer_policy','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.en-gb.html','https://www.booking.com/reviews/co/hotel/boutique-san-sebastian-bogota.es.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1672::bigint, jsonb_build_object(
      'queue_wait', 'The 4,500-square-metre former school absorbs crowds, but major festivals and international acts still pressure ticket checks. Buy for the exact programme and arrive early to learn the maze of rooms. Current visitors call the block rougher than the club itself, so use a direct ride.',
      'best_nights', 'Follow the lineup, not a generic Saturday rule. One edition may spread techno, acid, disco and live electronics through classrooms and courtyards; another may centre a concert, cinema or workshop. The sprawling multi-room festivals are the signature, while a smaller programme is better if you want space to explore.',
      'crowd_mix', 'Bogotá electronic regulars, artists, students, fashion-minded groups, queer dancers and visiting music fans move between the rooms. The concept aims beyond one nightlife enclave and attracts several subcultures, but it is not verified as LGBTQ+-majority every night. The artist and promoter reshape the balance.',
      'dress_code', 'Creative, durable clubwear wins: layers for patios, breathable pieces for packed rooms and shoes made for corridors and stairs. No reliable venue-wide fashion code was found. Read the ticket for special rules, travel light and choose a look that survives both an art installation and hard dancing.',
      'staff_inclusivity', 'The architecture, varied rooms and places to pause earn praise; visitors call the atmosphere relaxed across tastes. Queer artists and crowds appear in programming, but no detailed public anti-harassment, trans-inclusion or access policy was found. Free water and step-free routes need confirmation.',
      'venue_classification', 'active_large_multispace_bogota_electronic_art_food_and_festival_complex_in_former_school_with_diverse_queer_present_crowd_but_no_verified_every_night_lgbtq_majority_or_detailed_policy',
      'source_urls', to_jsonb(array['https://proyectokinder.com/','https://elpais.com/america-colombia/branded/los-lideres-de-colombia/2025-12-11/sector-9-el-colectivo-que-sigue-reinventando-la-noche-bogotana.html','https://caracol.com.co/2025/12/12/kinder-una-propuesta-que-reinventa-la-rumba-en-bogota-presenta-sector-9-le-contamos/','https://www.las2orillas.co/proyecto-kinder-abrio-sus-puertas-el-nuevo-templo-nocturno-que-bogota-esperaba/','https://es.ra.co/guide/co/bogota','https://pt.ra.co/events/2393557','https://www.reddit.com/r/Bogota/comments/1s5h157/joost_klein_en_bogot%C3%A1h/','https://www.reddit.com/r/Bogota/comments/1tz1gix/tengo_ganas_de_salir_pero_no_con_qui%C3%A9n_salir/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','large_capacity_major_event_ticket_check_maze_early_arrival_and_current_external_block_safety_context','source_urls',to_jsonb(array['https://elpais.com/america-colombia/branded/los-lideres-de-colombia/2025-12-11/sector-9-el-colectivo-que-sigue-reinventando-la-noche-bogotana.html','https://es.ra.co/guide/co/bogota','https://www.reddit.com/r/Bogota/comments/1s5h157/joost_klein_en_bogot%C3%A1h/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','lineup_led_multigenre_multispace_concert_cinema_workshop_and_large_festival_identity','source_urls',to_jsonb(array['https://caracol.com.co/2025/12/12/kinder-una-propuesta-que-reinventa-la-rumba-en-bogota-presenta-sector-9-le-contamos/','https://es.ra.co/guide/co/bogota','https://pt.ra.co/events/2393557']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','electronic_artist_student_fashion_queer_dancer_and_visiting_music_fan_mix_with_promoter_specific_variation','source_urls',to_jsonb(array['https://elpais.com/america-colombia/branded/los-lideres-de-colombia/2025-12-11/sector-9-el-colectivo-que-sigue-reinventando-la-noche-bogotana.html','https://pt.ra.co/events/2393557','https://www.reddit.com/r/Bogota/comments/1tz1gix/tengo_ganas_de_salir_pero_no_con_qui%C3%A9n_salir/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','former_school_patios_corridors_stairs_multispace_clubwear_and_event_specific_rule_context_without_venuewide_code','source_urls',to_jsonb(array['https://caracol.com.co/2025/12/12/kinder-una-propuesta-que-reinventa-la-rumba-en-bogota-presenta-sector-9-le-contamos/','https://www.las2orillas.co/proyecto-kinder-abrio-sus-puertas-el-nuevo-templo-nocturno-que-bogota-esperaba/','https://pt.ra.co/events/2393557']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','varied_room_pause_and_relaxed_taste_diversity_praise_with_queer_programming_but_no_detailed_public_safety_access_policy','source_urls',to_jsonb(array['https://www.reddit.com/r/Bogota/comments/1tz1gix/tengo_ganas_de_salir_pero_no_con_qui%C3%A9n_salir/','https://pt.ra.co/events/2393557','https://proyectokinder.com/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1682::bigint, jsonb_build_object(
      'queue_wait', 'Most people reserve a table rather than queue at a door. The heritage house is popular for dates, birthdays and pre-club dinners, so book Friday or Saturday and mention decoration needs in advance. Walk-ins are easier early; food is cooked to order, which keeps the mood unhurried but can lengthen a busy meal.',
      'best_nights', 'Friday and Saturday run to 3am and work beautifully as dinner, cocktails and a soft launch into Chapinero. A weekday is more romantic and conversational. English- and Spanish-language pop-rock, the garden-house feel and a long drinks list matter more here than a dance-floor climax. Sunday is the gentlest date.',
      'crowd_mix', 'Gay Bogotanos, couples, birthday groups, old regulars and queer visitors share a place woven into Chapinero’s memory since 2003. Locals lead, while travellers come for the historic gay-café character. It is multigenerational and social rather than a men-only bar, with friends and mixed companion groups at ease.',
      'dress_code', 'Romantic casual is perfect: clean jeans, colour, a date shirt or something celebratory. There is no selection-based club door. Dress for dinner and photos in the restored house, then add a jacket for Bogotá after midnight. If you are continuing to a club, choose shoes that can handle both a table and a dance floor.',
      'staff_inclusivity', 'A large review base praises the cosy atmosphere, appealing staff and professional service; reservations welcome couples and celebrations. Food is less consistent, with recent criticism of overcooked dishes and weak cocktails. It is listed as wheelchair accessible, but confirm the heritage-house route.',
      'venue_classification', 'active_historic_chapinero_gay_cafe_restaurant_and_pop_rock_bar_with_multigenerational_local_couple_group_crowd_reservable_celebrations_and_current_food_drink_variation',
      'identity_note', 'This is the current primary La Estación Café Chapinero record at Calle 62 #7-13/19. Place ID 1201 appears to duplicate the same physical venue and should be merged rather than shown twice.',
      'source_urls', to_jsonb(array['https://www.estacioncafecolombia.com/chapinero.html','https://www.tripadvisor.com.mx/Attraction_Review-g294074-d15585117-Reviews-La_Estacion_Cafe-Bogota.html','https://restaurantguru.com/La-Estacion-Bogota-4','https://es.restaurantguru.com/La-Estacion-Bogota-4','https://www.idt.gov.co/sites/default/files/4.2%20Gu%C3%ADa%20LGBTI%20Espa%C3%B1ol.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','free_reservation_friday_saturday_date_birthday_preclub_demand_and_cooked_to_order_timing_context','source_urls',to_jsonb(array['https://www.estacioncafecolombia.com/chapinero.html','https://restaurantguru.com/La-Estacion-Bogota-4']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','official_late_friday_saturday_weekday_romantic_sunday_date_and_bilingual_pop_rock_identity','source_urls',to_jsonb(array['https://www.estacioncafecolombia.com/chapinero.html','https://www.tripadvisor.com.mx/Attraction_Review-g294074-d15585117-Reviews-La_Estacion_Cafe-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_bogotano_couple_birthday_regular_queer_visitor_multigenerational_and_mixed_companion_group_consensus','source_urls',to_jsonb(array['https://www.estacioncafecolombia.com/chapinero.html','https://www.tripadvisor.com.mx/Attraction_Review-g294074-d15585117-Reviews-La_Estacion_Cafe-Bogota.html','https://www.idt.gov.co/sites/default/files/4.2%20Gu%C3%ADa%20LGBTI%20Espa%C3%B1ol.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','romantic_casual_dinner_celebration_heritage_house_cold_night_and_preclub_context_without_door_code','source_urls',to_jsonb(array['https://www.estacioncafecolombia.com/chapinero.html','https://www.tripadvisor.com.mx/Attraction_Review-g294074-d15585117-Reviews-La_Estacion_Cafe-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','large_cozy_appealing_professional_service_consensus_couple_celebration_welcome_and_listed_access_balanced_against_food_cocktail_variation','source_urls',to_jsonb(array['https://restaurantguru.com/La-Estacion-Bogota-4','https://es.restaurantguru.com/La-Estacion-Bogota-4','https://www.estacioncafecolombia.com/chapinero.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1192::bigint, jsonb_build_object(
      'queue_wait', 'The bar opens early and runs late, so entry is easier before karaoke, contests and the 1am drag show gather a crowd. There may be cover plus expected consumption; a late-2025 guest found both expensive. Ask what entry includes, then claim your preferred room before the three environments fill.',
      'best_nights', 'Come for the format: karaoke and singing contests are the most distinctive social choice, while a drag night peaks around 1am and the other rooms move through reggaetón, house and varied party music. An early evening suits solo arrivals; Friday or Saturday is the full multi-room marathon until roughly 5am.',
      'crowd_mix', 'LGBTQ+ Bogotanos, gay regulars, mixed friend groups, karaoke extroverts and foreign visitors share the three rooms. Locals set the tone, but current reviews specifically describe a welcome for outsiders. Ages and music tastes spread across the environments, making it broader than a single circuit-male floor.',
      'dress_code', 'Casual partywear is enough: jeans, colour, dance shoes or a playful karaoke look. No stable fashion code is published. Dress for a long indoor night with several rooms rather than a polished Zona T door, and carry a layer for the trip home. Save themed drag styling for nights when the official flyer asks for it.',
      'staff_inclusivity', 'Current sources repeatedly describe a lively LGBTQ+ room, friendly staff and help for visitors, with praise for service and atmosphere. The balance is price and upkeep: guests report expensive cover and drinks, implied consumption pressure, inconsistent service and broken chairs. Confirm costs and inspect your seat.',
      'venue_classification', 'active_multienvironment_chapinero_lgbtq_karaoke_drag_reggaeton_house_and_party_bar_with_local_led_mixed_crowd_warm_current_welcome_and_material_cover_price_upkeep_concerns',
      'source_urls', to_jsonb(array['https://www.instagram.com/leosbar_mistica/','https://wanderlog.com/es/place/details/978667/leos-bar-m%C3%ADstica-llgbtq--chapinero','https://qlist.app/venues/Bogota/LEOS-BAR-MSTICA-LGBTIQ-CHAPINERO/SVZIOE56Kzg2dHRwaFJscHVhV0hHZw','https://restaurantguru.com/Leos-Bar-Mistica-Bogota','https://restaurantguru.com/Leos-Bar-Mistica-Chapinero-Bogota']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','early_entry_cover_consumption_cost_one_am_show_and_three_environment_capacity_context','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/978667/leos-bar-m%C3%ADstica-llgbtq--chapinero','https://qlist.app/venues/Bogota/LEOS-BAR-MSTICA-LGBTIQ-CHAPINERO/SVZIOE56Kzg2dHRwaFJscHVhV0hHZw']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_karaoke_contests_one_am_drag_reggaeton_house_multienvironment_and_late_weekend_pattern','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/978667/leos-bar-m%C3%ADstica-llgbtq--chapinero','https://qlist.app/venues/Bogota/LEOS-BAR-MSTICA-LGBTIQ-CHAPINERO/SVZIOE56Kzg2dHRwaFJscHVhV0hHZw','https://www.instagram.com/leosbar_mistica/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','lgbtq_bogotano_gay_regular_mixed_friend_karaoke_foreign_visitor_mixed_age_and_music_taste_consensus','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/978667/leos-bar-m%C3%ADstica-llgbtq--chapinero','https://qlist.app/venues/Bogota/LEOS-BAR-MSTICA-LGBTIQ-CHAPINERO/SVZIOE56Kzg2dHRwaFJscHVhV0hHZw']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_long_indoor_multienvironment_karaoke_drag_and_late_transport_context_without_stable_code','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/978667/leos-bar-m%C3%ADstica-llgbtq--chapinero','https://www.instagram.com/leosbar_mistica/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_lgbtq_friendly_staff_visitor_help_service_and_atmosphere_praise_balanced_against_cover_price_consumption_service_and_chair_concerns','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/978667/leos-bar-m%C3%ADstica-llgbtq--chapinero','https://qlist.app/venues/Bogota/LEOS-BAR-MSTICA-LGBTIQ-CHAPINERO/SVZIOE56Kzg2dHRwaFJscHVhV0hHZw','https://restaurantguru.com/Leos-Bar-Mistica-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1679,1669,1678,1193,1675,1672,1682,1192)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
