-- Queer Atlas venue intelligence: global review-led editorial pass, batch 43.
-- Eight Bologna records, checked against current official pages, local guides and guest reviews on 2026-08-06.
-- Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1468::bigint, jsonb_build_object(
      'queue_wait', 'This is a hotel check-in, not a nightlife door: there is no regular public queue. Book ahead for strong dates and allow normal reception time at arrival. The seventh-floor terrace and summer jacuzzi are for hotel guests, so a room reservation—not a bar line—is what unlocks the skyline view.',
      'best_nights', 'Choose this stay when you want a quiet reset within roughly a 15–20 minute walk of the historic centre. Summer gives the guest-only rooftop, solarium and jacuzzi their moment; breakfast is the daily highlight. It works especially well after a late queer night when calm rooms matter more than being above the bars.',
      'crowd_mix', 'The guest mix is international leisure couples, solo city-break travellers and business visitors rather than a built-in queer social scene. You may meet other LGBTQ+ guests, but this is a polished mainstream four-star base, not a community hotel. Head into central Bologna for connection and return here for quiet.',
      'dress_code', 'No dress code beyond ordinary four-star ease. Clean travel clothes work at reception and breakfast; smart-casual feels right for the restaurant and rooftop drinks, while swimwear belongs around the seasonal jacuzzi. The mood is modern and unfussy, so there is no need to dress as if passing a club door.',
      'staff_inclusivity', 'Guests repeatedly describe the team as prepared, accommodating and quick to solve problems, praising reception and breakfast service. There is no strong body of venue-specific queer testimony, so treat the welcome as well-supported hospitality rather than a verified LGBTQ+ programme or community credential.',
      'venue_classification', 'active_modern_four_star_city_hotel_with_quiet_rooms_breakfast_guest_only_rooftop_and_seasonal_jacuzzi_international_mainstream_crowd_and_strong_service_consensus',
      'source_urls', to_jsonb(array['https://www.aemiliahotel.it/en/','https://www.tripadvisor.com/Hotel_Review-g187801-d286576-Reviews-Aemilia_Hotel-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://www.booking.com/hotel/it/aemiliahotelbologna.html','https://www.therooftopguide.com/rooftop-bars-in-bologna/aemelia-hotel-bologna.html','https://www.oyster.com/bologna/hotels/aemilia-hotel/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','hotel_checkin_no_public_rooftop_queue_advance_room_booking_and_guest_only_terrace_access','source_urls',to_jsonb(array['https://www.aemiliahotel.it/en/','https://www.therooftopguide.com/rooftop-bars-in-bologna/aemelia-hotel-bologna.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','quiet_city_base_walk_time_summer_rooftop_jacuzzi_and_consistently_praised_breakfast','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g187801-d286576-Reviews-Aemilia_Hotel-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://www.booking.com/hotel/it/aemiliahotelbologna.html','https://www.therooftopguide.com/rooftop-bars-in-bologna/aemelia-hotel-bologna.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','international_mainstream_business_leisure_and_couple_mix_without_verified_queer_social_programme','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g187801-d286576-Reviews-Aemilia_Hotel-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://www.booking.com/hotel/it/aemiliahotelbologna.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','ordinary_modern_four_star_casual_smart_casual_and_seasonal_rooftop_swimwear_context_without_door_selection','source_urls',to_jsonb(array['https://www.aemiliahotel.it/en/','https://www.therooftopguide.com/rooftop-bars-in-bologna/aemelia-hotel-bologna.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_prepared_accommodating_problem_solving_service_consensus_without_specific_lgbtq_programme_evidence','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g187801-d286576-Reviews-Aemilia_Hotel-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://www.booking.com/hotel/it/aemiliahotelbologna.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1472::bigint, jsonb_build_object(
      'queue_wait', 'The line changes completely with the programme. A major disco night can mean an hour outside plus another wait at the bar; quieter talks and summer aperitivo events are simpler. Pre-register for membership, bring valid ID and arrive before the late rush. Some summer dates need neither card nor ticket.',
      'best_nights', 'Follow the calendar, not a weekday rule. Wednesday disco can be good value and properly alive after 1am, while summer evenings bring pop aperitivo, ballroom practice, labels and community culture into the courtyard. Big Pride and guest nights deliver scale; daytime services reveal the institution beyond dancing.',
      'crowd_mix', 'Students, Bologna regulars, activists, artists and regional visitors share this historic LGBTQIA+ centre. The mix shifts from broad, intergenerational community work by day to a young, dense queer dancefloor at night. It can feel like everyone already knows someone, yet the room is not built around tourists.',
      'dress_code', 'Queer self-expression is enough for most discos: trainers, denim, mesh, colour and gender-play all fit. Read the event page because special productions can set a theme. Membership nights require valid ID; the practical door issue is paperwork and timing, not looking expensive or conventionally polished.',
      'staff_inclusivity', 'The centre supports rights work, anti-discrimination services, culture and an alias identity option when documents have not been amended. That mission is substantial. Nightlife reviews are more divided: many feel welcomed, while others report abrupt security, confusing entry and poorly managed peak crowds.',
      'venue_classification', 'active_historic_bologna_lgbtqia_community_centre_rights_culture_services_courtyard_events_and_membership_disco_with_event_specific_access_queue_and_crowd_conditions',
      'source_urls', to_jsonb(array['https://cassero.it/','https://cassero.it/tesseramento/','https://cassero.it/accessibilita/','https://www.bolognawelcome.com/en/events/miscellaneous/cassero-lgbtqia-laltra-sponda-en','https://www.tripadvisor.it/Attraction_Review-g187801-d9453286-Reviews-Cassero_LGBTI_Center-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://app.wanderlog.com/place/details/1820641/cassero-lgbtqia-center']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','event_specific_entry_and_bar_queues_membership_valid_id_preregistration_and_some_card_free_summer_dates','source_urls',to_jsonb(array['https://cassero.it/tesseramento/','https://www.tripadvisor.it/Attraction_Review-g187801-d9453286-Reviews-Cassero_LGBTI_Center-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://www.bolognawelcome.com/en/events/miscellaneous/cassero-lgbtqia-laltra-sponda-en']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','calendar_led_wednesday_disco_late_peak_summer_aperitivo_ballroom_label_community_and_pride_variation','source_urls',to_jsonb(array['https://cassero.it/','https://www.bolognawelcome.com/en/events/miscellaneous/cassero-lgbtqia-laltra-sponda-en','https://www.tripadvisor.it/Attraction_Review-g187801-d9453286-Reviews-Cassero_LGBTI_Center-Bologna_Province_of_Bologna_Emilia_Romagna.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','student_local_activist_artist_regional_visitor_intergenerational_day_and_young_dense_night_mix','source_urls',to_jsonb(array['https://cassero.it/','https://www.gayplaces.co/city/bologna/event-space/cassero-lgbtqia-center','https://www.gayout.com/europe/italy/bologna/bars/cassero-bologna']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','expressive_informal_default_with_event_specific_themes_and_id_membership_as_primary_door_requirements','source_urls',to_jsonb(array['https://cassero.it/tesseramento/','https://www.bolognawelcome.com/en/events/miscellaneous/cassero-lgbtqia-laltra-sponda-en']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','substantial_rights_antidiscrimination_alias_identity_and_access_support_balanced_against_security_entry_crowd_complaints','source_urls',to_jsonb(array['https://cassero.it/','https://cassero.it/tesseramento/','https://cassero.it/accessibilita/','https://app.wanderlog.com/place/details/1820641/cassero-lgbtqia-center']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1465::bigint, jsonb_build_object(
      'queue_wait', 'Usually this is reception paperwork, not a street queue. First-timers should budget at least 15 minutes for ID, the venue’s own annual membership and admission; recent visitors strongly disagree about the added cost. The entrance hides in a courtyard near Centrale, so finding the bell can take longer than waiting.',
      'best_nights', 'Weekend afternoons and early evenings are the safer bet for company; weekday visits can drop to a handful of men. Sunday has recent praise for easy conversation, warmth and a sociable bar. Go for a slower, mature sauna mood rather than a guaranteed party, and check the current timetable before crossing town.',
      'crowd_mix', 'This is a men’s sauna with a notably mature local clientele, plus some younger men and rail travellers using the handy station location. Regulars value polite company and a low-pressure pace; tourists are present, but the separate membership fee has left some one-time visitors feeling that the welcome costs too much.',
      'dress_code', 'Once changed, the towel is the uniform; bring valid photo ID and ask what membership and entry include before paying. There is no fashion selection. The club spans ground and basement levels, with sauna, steam, jacuzzi, cinema, dark areas and a bar, so wear shoes that make the discreet courtyard approach easy.',
      'staff_inclusivity', 'Regulars praise courteous reception, a kind bar team and visible cleaning; other visitors describe an unsmiling welcome, dated rooms, weak ventilation, excessive chlorine or too little upkeep. The evidence is split. Newcomers deserve clear prices and can leave if the air or wet areas do not feel right.',
      'venue_classification', 'active_station_adjacent_membership_mens_sauna_with_mature_local_weekend_crowd_bar_jacuzzi_steam_cinema_and_dark_areas_mixed_welcome_ventilation_cleanliness_and_value_reports',
      'source_urls', to_jsonb(array['https://www.cosmosclub.eu/','https://wanderlog.com/place/details/7690937/cosmos-club','https://www.gayout.com/europe/italy/bologna/bars/cosmos-club','https://www.travelgay.com/bologna-gay-saunas']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','short_reception_but_first_time_id_private_membership_and_price_explanation_delay_plus_hidden_courtyard_entry','source_urls',to_jsonb(array['https://wanderlog.com/place/details/7690937/cosmos-club','https://www.gayout.com/europe/italy/bologna/bars/cosmos-club']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekend_afternoon_early_evening_and_sunday_social_strength_against_quiet_weekdays','source_urls',to_jsonb(array['https://wanderlog.com/place/details/7690937/cosmos-club','https://www.gayout.com/europe/italy/bologna/bars/cosmos-club']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','primarily_mature_local_men_with_some_younger_guests_and_station_arriving_tourists_plus_membership_value_tension','source_urls',to_jsonb(array['https://wanderlog.com/place/details/7690937/cosmos-club','https://www.gayout.com/europe/italy/bologna/bars/cosmos-club']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','towel_inside_valid_id_and_clear_membership_terms_with_ground_basement_wet_cruise_and_bar_layout','source_urls',to_jsonb(array['https://wanderlog.com/place/details/7690937/cosmos-club','https://www.travelgay.com/bologna-gay-saunas']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','courteous_reception_bar_and_cleaning_praise_balanced_against_welcome_upkeep_ventilation_chlorine_and_value_complaints','source_urls',to_jsonb(array['https://www.gayout.com/europe/italy/bologna/bars/cosmos-club','https://wanderlog.com/place/details/7690937/cosmos-club']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1469::bigint, jsonb_build_object(
      'queue_wait', 'The room is compact, so Friday and Saturday can feel full fast, but this is normally a walk-in bar rather than a velvet-rope queue. Arrive around aperitivo for breathing space and a seat; later, expect a cheerful squeeze. Posted hours have proved unreliable before, so check the day’s social update.',
      'best_nights', 'Come early for aperitivo, conversation and the bar’s neighbourhood soul; choose Friday or Saturday for louder music and a busier queer room before dancing elsewhere. Small exhibitions, performances and community moments can change the evening, making the programme more useful than any fixed “best night.”',
      'crowd_mix', 'A fluid local crowd brings together LGBTQ+ regulars, students, activists, alternative kids, trans guests, hipsters and friends. Travellers find it, but it reads as a lived-in Bologna queer bar rather than a tourist attraction. Groups may know one another; the small footprint still makes casual conversation possible.',
      'dress_code', 'Wear what feels like you: band tees, denim, trainers, colour, makeup and softly chaotic student style all make sense here. There is no evidence of a selective fashion door. The practical choice is something comfortable for standing close, playing table football or carrying the night on toward a club.',
      'staff_inclusivity', 'Recent guests call the team lovely, friendly and attentive, praising affordable drinks and a genuinely queer atmosphere. Community accounts also describe visible trans presence and political life beyond nightlife. The main caution is operational rather than social: compact-room pressure and hours that can shift.',
      'venue_classification', 'active_compact_central_queer_cafe_bar_with_aperitivo_cocktails_music_foosball_small_cultural_events_activist_student_trans_and_mixed_lgbtq_local_identity',
      'source_urls', to_jsonb(array['https://www.facebook.com/barattolo.bo/','https://wanderlog.com/place/details/2091984/il-barattolo','https://www.gayplaces.co/city/bologna/bar/il-barattolo','https://www.travelgay.com/venue/il-barattolo','https://www.reddit.com/r/bologna/comments/1gppmh2/barpub_alternativi_eo_lgbt/','https://www.reddit.com/r/bologna/comments/1fri0j4/locali_compagnie_ed_eventi_per_trav_e_trans/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','compact_walkin_room_weekend_capacity_early_aperitivo_space_and_social_hour_verification','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2091984/il-barattolo','https://www.gayplaces.co/city/bologna/bar/il-barattolo','https://www.travelgay.com/venue/il-barattolo']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','early_aperitivo_weekend_build_and_programme_led_exhibition_performance_community_variation','source_urls',to_jsonb(array['https://www.gayplaces.co/city/bologna/bar/il-barattolo','https://www.travelgay.com/venue/il-barattolo','https://wanderlog.com/place/details/2091984/il-barattolo']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_lgbtq_student_activist_alternative_trans_hipster_friend_and_smaller_visitor_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2091984/il-barattolo','https://www.reddit.com/r/bologna/comments/1fri0j4/locali_compagnie_ed_eventi_per_trav_e_trans/','https://www.reddit.com/r/bologna/comments/1gppmh2/barpub_alternativi_eo_lgbt/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_expressive_student_alternative_style_without_evidence_of_selective_door','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2091984/il-barattolo','https://www.travelgay.com/venue/il-barattolo']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','repeated_friendly_attentive_affordable_and_queer_atmosphere_praise_with_trans_visibility_and_operational_hour_caution','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2091984/il-barattolo','https://www.reddit.com/r/bologna/comments/1fri0j4/locali_compagnie_ed_eventi_per_trav_e_trans/','https://www.travelgay.com/venue/il-barattolo']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1471::bigint, jsonb_build_object(
      'queue_wait', 'Big guest, Pride and Saturday nights can produce a real membership bottleneck. Regulars have asked for separate lines for existing cardholders and new sign-ups, so arrive before midnight, carry valid ID and sort the current club card in advance. Inside, the bar’s pay-first system can create a second queue.',
      'best_nights', 'Friday leans techno; Saturday is the broadest bet for drag, pop, commercial sounds and a full LGBTQIA+ dancefloor. Pride, foam and major guest nights are the spectacle dates, while some parties continue into the garage, dark room or pool zone. Pick the event identity first—RED is not one musical room every week.',
      'crowd_mix', 'The core is local and regional LGBTQIA+ clubbers, drag fans and groups celebrating together, with visitors drawn by major performers. It is primarily queer, not a generic tourist disco. Most accounts describe a festive mix, though one recent foreign guest felt outsiders and straight allies were received coolly.',
      'dress_code', 'Normal drag-and-dance nights welcome club casual, sparkle, sportswear and expressive queer looks. Read the flyer: fetish or BDSM productions can enforce a strict theme and may seal phones at the door. Bring ID and membership details whatever you wear; for foam or pool events, pack for the actual format.',
      'staff_inclusivity', 'Guests praise polite teams handling large crowds, good bartending and thoughtful coat-check help. That sits beside reports of brusque treatment toward outsiders and serious complaints about heat and air circulation. Inclusion is strongest in the queer programme; peak operations and ventilation remain material cautions.',
      'venue_classification', 'active_large_out_of_centre_lgbtqia_disco_with_friday_techno_saturday_drag_pop_major_guests_pool_dark_and_garage_zones_membership_queues_and_material_ventilation_reports',
      'source_urls', to_jsonb(array['https://www.redbologna.it/','https://www.redbologna.it/programma/archivio-eventi/','https://www.tripadvisor.it/Attraction_Review-g187801-d23837705-Reviews-Red_Club_Bologna-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://wanderlog.com/place/details/6563592/red-bologna','https://www.thegayagenda.fyi/bologna/businesses/red/','https://www.reddit.com/r/bologna/comments/162rh9n/any_bdsm_people_here/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','major_night_membership_bottleneck_existing_new_card_line_and_internal_pay_first_bar_queue','source_urls',to_jsonb(array['https://www.tripadvisor.it/Attraction_Review-g187801-d23837705-Reviews-Red_Club_Bologna-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://wanderlog.com/place/details/6563592/red-bologna']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_techno_saturday_drag_pop_and_calendar_specific_pride_foam_guest_garage_dark_pool_formats','source_urls',to_jsonb(array['https://www.tripadvisor.it/Attraction_Review-g187801-d23837705-Reviews-Red_Club_Bologna-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://www.redbologna.it/programma/archivio-eventi/','https://www.redbologna.it/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','primarily_local_regional_lgbtqia_drag_fan_group_and_guest_performer_visitor_mix_with_outsider_welcome_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6563592/red-bologna','https://www.thegayagenda.fyi/bologna/businesses/red/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','expressive_club_casual_default_with_strict_fetish_bdsm_theme_and_phone_policy_on_specific_events','source_urls',to_jsonb(array['https://www.redbologna.it/programma/archivio-eventi/','https://www.reddit.com/r/bologna/comments/162rh9n/any_bdsm_people_here/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','polite_high_volume_bar_and_coatcheck_praise_balanced_against_outsider_treatment_heat_and_airflow_complaints','source_urls',to_jsonb(array['https://www.tripadvisor.it/Attraction_Review-g187801-d23837705-Reviews-Red_Club_Bologna-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://wanderlog.com/place/details/6563592/red-bologna']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1467::bigint, jsonb_build_object(
      'queue_wait', 'There are no reservations, and the line is part of the deal. Recent waits commonly land around 15–30 minutes, but peak lunch or the final hour before the 8pm kitchen cutoff can stretch toward an hour—and late arrivals may not be seated. Go near opening or mid-afternoon, not at the edge of service.',
      'best_nights', 'Think early meal, not night out. Arrive near 11:30 for the cleanest shot at lunch, or use the mid-afternoon lull; an early dinner before the kitchen stops taking orders at 8pm can work if the line is short. The reward is fresh egg pasta that moves between Bologna classics and a playful weekly menu.',
      'crowd_mix', 'This famous pasta counter draws many visitors, Italian food travellers, couples and local fans, with plenty arriving from online recommendations. It is mainstream rather than queer-owned or queer-programmed. The communal, low-pressure room can feel open, but it is not a place to seek LGBTQ+ community.',
      'dress_code', 'Come exactly as you have explored the city: casual clothes and walking shoes are ideal for standing in line, eating at simple shared tables and heading back out. There is no fashion door and no need for dinner polish. In warm weather, dress for an uncovered wait outside rather than for the photogenic pasta counter.',
      'staff_inclusivity', 'Most guests praise fast, friendly service once seated, with water and a small side included. Recent reports also describe rude exchanges and poor communication when the last queue exceeded kitchen capacity. No queer policy is evidenced, so the fairest reading is mainstream hospitality with peak-time inconsistency.',
      'venue_classification', 'active_high_demand_mainstream_fresh_pasta_restaurant_and_shop_with_no_reservations_early_kitchen_cutoff_traditional_and_weekly_menus_tourist_local_mix_and_peak_queue_service_variation',
      'source_urls', to_jsonb(array['https://www.sfogliarina.it/en/','https://www.sfogliarina.it/en/contacts/','https://www.sfogliarina.it/cucina-tipica-bolognese/','https://www.tripadvisor.com/Restaurant_Review-g187801-d9728731-Reviews-Sfoglia_Rina-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://wanderlog.com/it/place/details/912474/sfoglia-rina','https://www.reddit.com/r/bologna/comments/14fzy3k/looking_for_tips_for_a_chef_in_bologna/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','official_no_reservations_common_fifteen_to_thirty_minute_wait_peak_hour_risk_and_eight_pm_order_cutoff','source_urls',to_jsonb(array['https://www.sfogliarina.it/en/contacts/','https://www.tripadvisor.com/Restaurant_Review-g187801-d9728731-Reviews-Sfoglia_Rina-Bologna_Province_of_Bologna_Emilia_Romagna.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','early_lunch_midafternoon_or_early_dinner_strategy_with_fresh_classic_and_weekly_pasta_menu','source_urls',to_jsonb(array['https://www.sfogliarina.it/en/contacts/','https://www.sfogliarina.it/cucina-tipica-bolognese/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','high_profile_mainstream_international_food_visitor_italian_couple_and_local_fan_mix_without_queer_programme','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g187801-d9728731-Reviews-Sfoglia_Rina-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://www.reddit.com/r/bologna/comments/14fzy3k/looking_for_tips_for_a_chef_in_bologna/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','casual_walking_clothes_for_outdoor_queue_and_simple_shared_table_restaurant_without_selection','source_urls',to_jsonb(array['https://www.sfogliarina.it/en/','https://www.tripadvisor.com/Restaurant_Review-g187801-d9728731-Reviews-Sfoglia_Rina-Bologna_Province_of_Bologna_Emilia_Romagna.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','predominantly_fast_friendly_helpful_service_balanced_against_recent_rude_interaction_and_last_queue_communication_failures_without_specific_queer_policy','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g187801-d9728731-Reviews-Sfoglia_Rina-Bologna_Province_of_Bologna_Emilia_Romagna.html','https://wanderlog.com/it/place/details/912474/sfoglia-rina']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1466::bigint, jsonb_build_object(
      'queue_wait', 'A street queue is unusual, but first entry can slow down over ID, membership and pricing. Sunday afternoon is the clear crowd peak—one report counted roughly 200 men—while Friday can feel much thinner. Ask for the full non-member cost before committing and check whether every wet facility is working that day.',
      'best_nights', 'Sunday from late afternoon into early evening has the strongest evidence for a lively, sociable room across ages. Saturday is generally busier than Friday; quieter weekdays suit an unhurried soak but offer less certainty of company. The jacuzzi, Turkish bath, sauna, cabins, dark basement and bar shape a longer visit.',
      'crowd_mix', 'Men across a wide age range use the sauna, with the centre of gravity often described as 30–50 or over 40 and a smaller young contingent. Sundays bring locals in force; rail-side access also draws visitors. Some guests socialise quickly, while others see age-based pricing and one-time membership costs as unwelcoming.',
      'dress_code', 'Towel and valid ID, not nightclub clothes. Confirm card, membership and entry charges at reception, then keep footwear suitable for wet floors. Condoms may need to be requested at the bar rather than handed over at entry, and reports on supplies vary—bringing your own safer-sex kit is sensible.',
      'staff_inclusivity', 'Many guests describe a kind front desk, warm bar team and family-like social tone. Others report curt treatment of tourists, unclear charges and inconsistent hygiene, especially in the Turkish bath and lower dark area. Reviews conflict enough that checking cleanliness and functioning facilities on arrival matters.',
      'venue_classification', 'active_mens_gay_sauna_with_sunday_peak_cross_age_local_crowd_jacuzzi_turkish_dry_sauna_cabins_dark_basement_bar_membership_pricing_and_material_hygiene_service_variation',
      'source_urls', to_jsonb(array['https://saunasteam.it/','https://www.bolognatoday.it/dossier/sociale/sauna-gay-omosessuale-steam.html','https://www.thegayagenda.fyi/bologna/businesses/steam-sauna/','https://zaubee.com/biz/steam-sauna-b1awqkgo','https://wanderlog.com/pl/place/details/10400506/steam-sauna','https://qlist.app/venues/Bologna/Steam-Sauna/YjAwZ2o5OHhiK0FNSTNTK05kNU1OQQ']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','little_street_queue_but_first_time_membership_price_delay_sunday_peak_and_facility_function_check','source_urls',to_jsonb(array['https://zaubee.com/biz/steam-sauna-b1awqkgo','https://wanderlog.com/pl/place/details/10400506/steam-sauna','https://www.thegayagenda.fyi/bologna/businesses/steam-sauna/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','sunday_late_afternoon_strongest_crowd_saturday_over_friday_and_weekday_relaxation_tradeoff','source_urls',to_jsonb(array['https://zaubee.com/biz/steam-sauna-b1awqkgo','https://www.thegayagenda.fyi/bologna/businesses/steam-sauna/','https://wanderlog.com/pl/place/details/10400506/steam-sauna']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','men_only_cross_age_but_thirty_to_fifty_or_over_forty_centre_with_local_sunday_strength_and_visitor_membership_tension','source_urls',to_jsonb(array['https://qlist.app/venues/Bologna/Steam-Sauna/YjAwZ2o5OHhiK0FNSTNTK05kNU1OQQ','https://wanderlog.com/pl/place/details/10400506/steam-sauna','https://zaubee.com/biz/steam-sauna-b1awqkgo']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','towel_valid_id_membership_price_confirmation_wet_floor_footwear_and_variable_safer_sex_supply_context','source_urls',to_jsonb(array['https://wanderlog.com/pl/place/details/10400506/steam-sauna','https://www.bolognatoday.it/dossier/sociale/sauna-gay-omosessuale-steam.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','kind_reception_bar_and_social_praise_balanced_against_tourist_charge_courtesy_and_material_hygiene_complaints','source_urls',to_jsonb(array['https://www.thegayagenda.fyi/bologna/businesses/steam-sauna/','https://zaubee.com/biz/steam-sauna-b1awqkgo','https://wanderlog.com/pl/place/details/10400506/steam-sauna']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1470::bigint, jsonb_build_object(
      'queue_wait', 'The real delay is membership, not a pavement line. Bring valid ID and check eligibility before setting out: current listings agree that a club card is mandatory, while one says tourists are not admitted. Friday and Saturday can take longer at reception; quieter lounge-led evenings should be straightforward.',
      'best_nights', 'Friday and Saturday run latest and are strongest for a fuller bar-to-cruising rhythm. Monday and Sunday are shorter and suit conversation first; themed nights may move from aperitivo toward kinkier play. Check the programme, since this club changes tone more than its discreet station-side doorway suggests.',
      'crowd_mix', 'The space is designed for gay and bi men, with local members forming the base and some regional visitors. A large bar encourages conversation before the cruising area and private rooms. Do not count on tourist access without asking directly: published guidance is inconsistent enough to verify first.',
      'dress_code', 'Street clothes are fine in the lounge; move toward fetish, underwear or less as the specific event and cruising area invite. There is no evidence of a luxury fashion door, but themed nights can set a real code. Bring ID, respect consent and privacy, and never photograph people in the play spaces.',
      'staff_inclusivity', 'The recent pattern is a friendly, professional team, a well-run bar and clean, modern rooms. Criticism focuses on high admission, slow mandatory membership and an open cruising layout that some find short on privacy or equipment. Ask the team about boundaries, access and room etiquette on arrival.',
      'venue_classification', 'active_central_membership_gay_bi_mens_social_and_cruise_club_with_large_cocktail_lounge_spacious_private_rooms_weekend_late_hours_and_access_price_privacy_cautions',
      'source_urls', to_jsonb(array['https://www.styxclub.it/','https://www.arco.lgbt/en/club/stix/','https://qlist.app/venues/Bologna/Styx-club/SnM0UnBLOHhXaE5lNUkwdGQ3RVpIQQ','https://www.patroc.com/gay/bologna/d/styx-club.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','membership_and_id_processing_more_material_than_street_queue_with_conflicting_tourist_eligibility_guidance','source_urls',to_jsonb(array['https://qlist.app/venues/Bologna/Styx-club/SnM0UnBLOHhXaE5lNUkwdGQ3RVpIQQ','https://www.patroc.com/gay/bologna/d/styx-club.html','https://www.arco.lgbt/en/club/stix/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_latest_fuller_bar_cruise_flow_with_shorter_monday_sunday_and_event_specific_tone','source_urls',to_jsonb(array['https://www.arco.lgbt/en/club/stix/','https://www.patroc.com/gay/bologna/d/styx-club.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_bi_men_local_member_base_regional_visitors_social_bar_and_uncertain_tourist_admission','source_urls',to_jsonb(array['https://www.arco.lgbt/en/club/stix/','https://qlist.app/venues/Bologna/Styx-club/SnM0UnBLOHhXaE5lNUkwdGQ3RVpIQQ']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','streetwear_lounge_and_event_led_fetish_underwear_cruise_context_with_consent_privacy_no_photography_guidance','source_urls',to_jsonb(array['https://www.arco.lgbt/en/club/stix/','https://qlist.app/venues/Bologna/Styx-club/SnM0UnBLOHhXaE5lNUkwdGQ3RVpIQQ']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_professional_clean_modern_bar_and_room_praise_balanced_against_price_membership_open_layout_privacy_and_equipment_criticism','source_urls',to_jsonb(array['https://qlist.app/venues/Bologna/Styx-club/SnM0UnBLOHhXaE5lNUkwdGQ3RVpIQQ','https://www.arco.lgbt/en/club/stix/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1468,1472,1465,1469,1471,1467,1466,1470)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
