-- Queer Atlas venue intelligence: global review-led editorial pass, batch 59.
-- Seven Chicago records and one Cologne record checked against current official pages, listings and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, never in reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (476::bigint, jsonb_build_object(
      'queue_wait', 'The narrow room is easy early but can build a brisk ID line for themed pop nights, Pride and festival weekends. Buy tickets when the event requires them and bring physical 21+ ID. Once full, the real wait is often for bar space rather than admission.',
      'best_nights', 'Choose the theme: pop-diva tributes, dance parties and queer takeovers each reshape the room. Friday and Saturday bring the biggest release, while an earlier weekday feels more social. The calendar is the guide; arrive before the headline set if dancing space matters.',
      'crowd_mix', 'Young gay men are prominent, joined by queer women, trans and nonbinary guests, allies and pop devotees. Recent locals also see a growing lesbian presence on some nights. The crowd is energetic, mixed and fandom-led rather than a single male-only scene.',
      'dress_code', 'Expressive pop-night style, tees, tanks, denim, trainers and statement looks all fit. There is no reliable formal code, but dress for a hot, tight floor and check the theme. Bring valid ID, minimal baggage and hearing protection if you plan to stay by the speakers.',
      'staff_inclusivity', 'Reviews praise friendly energy, themed programming and a room where people can be themselves; crowded nights generate the usual complaints about service pace and space. Its LGBTQ+ identity is explicit. Keep your drink close and flag unwanted contact quickly.',
      'venue_classification', 'active_compact_northalsted_lgbtq_pop_dance_bar_with_diva_theme_and_queer_takeover_nights_young_gay_male_core_growing_lesbian_trans_nonbinary_ally_mix_peak_lines_and_positive_high_energy_consensus',
      'identity_note', 'Scarlet Bar is an active LGBTQ+ pop and dance bar at 3320 N Halsted. Its audience varies substantially by themed event and is broader than a gay-men-only label.',
      'source_urls', to_jsonb(array['https://www.scarletchicago.com/','https://www.instagram.com/scarletbarchicago/','https://www.restaurantji.com/il/chicago/scarlet-bar-/','https://chicago.gaycities.com/bars/159-scarlet','https://www.reddit.com/r/chicagogaybros/comments/1svp5eb/gay_bars_alone_as_a_visitor/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','early_ease_theme_pride_festival_id_line_ticket_variation_and_inside_bar_space_pressure','source_urls',to_jsonb(array['https://www.scarletchicago.com/','https://www.instagram.com/scarletbarchicago/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','pop_diva_dance_queer_takeover_event_led_weekend_peak_and_earlier_weekday_social_variation','source_urls',to_jsonb(array['https://www.scarletchicago.com/','https://www.restaurantji.com/il/chicago/scarlet-bar-/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_gay_male_queer_woman_trans_nonbinary_ally_and_pop_fan_mix_with_event_variation','source_urls',to_jsonb(array['https://www.reddit.com/r/chicagogaybros/comments/1svp5eb/gay_bars_alone_as_a_visitor/','https://chicago.gaycities.com/bars/159-scarlet']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','expressive_pop_casual_theme_style_hot_floor_minimal_bag_id_and_hearing_protection_practicality','source_urls',to_jsonb(array['https://www.scarletchicago.com/','https://www.instagram.com/scarletbarchicago/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_self_expression_theme_energy_praise_balanced_by_peak_space_and_service_pace','source_urls',to_jsonb(array['https://www.restaurantji.com/il/chicago/scarlet-bar-/','https://chicago.gaycities.com/bars/159-scarlet']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (957::bigint, jsonb_build_object(
      'queue_wait', 'Most regular nights move quickly, but major touring DJs, all-building events and Sunday Queen! can sell out or form a late line. Buy advance tickets, bring physical 21+ ID and read the no-reentry and coat-check details for the specific event.',
      'best_nights', 'Sunday Queen! is the queer house institution; Friday and Saturday follow the booked DJ across house, techno and left-field dance music. Go for the artist, not generic clubbing. The floor often finds its deepest groove after midnight and rewards staying to close.',
      'crowd_mix', 'Serious dancers, house heads, queer regulars, gay men, women, trans and nonbinary clubgoers, and straight music fans share the basement. Queen! is distinctly queer; other nights are mixed. The unifying identity is music knowledge and dance-floor commitment.',
      'dress_code', 'Wear comfortable, sweat-ready clothes and proper dancing shoes; black tees, denim and expressive queer looks all belong. Queen! can be more visibly styled without requiring costume. Earplugs are wise, physical ID is essential and large bags can slow entry.',
      'staff_inclusivity', 'The club’s queer Sunday institution and music-first ethos support a strong welcome for diverse dancers. Reviews prize sound, bookings and an unpretentious floor, though sold-out nights can feel overwhelming and door experiences vary. Respect space and seek staff when consent fails.',
      'venue_classification', 'active_music_first_chicago_house_and_techno_basement_club_with_legendary_sunday_queer_queen_party_touring_djs_serious_mixed_dancers_event_specific_queer_intensity_and_strong_sound_booking_consensus',
      'identity_note', 'smartbar is a mixed electronic-music club below Metro, not a full-time gay bar. Its weekly Sunday Queen! party is explicitly queer and central to the listing’s relevance.',
      'source_urls', to_jsonb(array['https://smartbarchicago.com/','https://smartbarchicago.com/queen/','https://www.instagram.com/smartbarchicago/','https://www.reddit.com/r/chicagoEDM/comments/1sh1kyu/im_always_so_confused/','https://www.reddit.com/r/AskChicago/comments/1mjmick/whats_the_crowd_like_at_smartbar_what_should_i/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','regular_quick_entry_major_dj_all_building_queen_sellout_line_with_ticket_id_and_event_rule_need','source_urls',to_jsonb(array['https://smartbarchicago.com/','https://smartbarchicago.com/queen/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','sunday_queer_house_queen_party_and_friday_saturday_artist_led_house_techno_after_midnight_peak','source_urls',to_jsonb(array['https://smartbarchicago.com/queen/','https://smartbarchicago.com/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','serious_dancer_house_head_queer_gay_woman_trans_nonbinary_and_straight_music_fan_mix_by_event','source_urls',to_jsonb(array['https://www.reddit.com/r/chicagoEDM/comments/1sh1kyu/im_always_so_confused/','https://smartbarchicago.com/queen/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','comfortable_sweat_ready_music_first_style_with_queen_expression_dance_shoes_earplugs_id_and_bag_practicality','source_urls',to_jsonb(array['https://www.reddit.com/r/AskChicago/comments/1mjmick/whats_the_crowd_like_at_smartbar_what_should_i/','https://smartbarchicago.com/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','queer_sunday_and_unpretentious_music_floor_strength_balanced_by_sellout_overwhelm_and_door_variability','source_urls',to_jsonb(array['https://smartbarchicago.com/queen/','https://www.reddit.com/r/chicagoEDM/comments/1sh1kyu/im_always_so_confused/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (438::bigint, jsonb_build_object(
      'queue_wait', 'The club is open 24 hours, but peak Saturday nights, Pride, Market Days and major events can create long outdoor waits. Buy the required membership, reserve a room or locker when possible, carry accepted ID and skip the rush if the line feels unsafe or exhausting.',
      'best_nights', 'Late Saturday into early Sunday is the fullest; weekday evenings are calmer and easier for a first visit. Event weekends intensify every floor. Arrive around 22:00 to learn the layout before the midnight surge, or choose daylight for a lower-pressure introduction.',
      'crowd_mix', 'Adult men span local regulars, tourists, many ages, races, body types and sexual interests. Peak events can skew younger or more visitor-heavy, but the baseline is broad. This is a men’s bathhouse and cruise club, not an all-gender queer spa.',
      'dress_code', 'You change into a towel or permitted clubwear; secure street clothes and valuables in your locker or room. Shower footwear is practical. Carry condoms and lube if desired, watch your drink, and treat every encounter—from eye contact onward—as consent that can be withdrawn.',
      'staff_inclusivity', 'Guests praise the extensive wet areas, multiple floors and 24-hour convenience, while service, cleaning closures and entry lines receive mixed reports. The gay-men focus is explicit. Learn house rules, identify exits and report harassment or health concerns immediately.',
      'venue_classification', 'active_24_hour_membership_based_gay_mens_bathhouse_and_cruise_club_in_northalsted_with_multilevel_wet_gym_lounge_private_space_facilities_broad_male_crowd_peak_event_lines_and_mixed_service_cleaning_consensus',
      'identity_note', 'Steamworks Chicago is a 24-hour membership-based gay men’s bathhouse at 3246 N Halsted, not a general sauna or wellness center. Entry, locker and room rules are integral.',
      'source_urls', to_jsonb(array['https://www.steamworksbaths.com/chicago','https://www.steamworksbaths.com/','https://www.reddit.com/r/chicagogaybros/comments/1szdzex/my_review_of_steamworks/','https://www.reddit.com/r/AskGaybrosOver30/comments/1f78cr5/just_had_my_first_evening_at_steamworks_in_chicago/','https://www.reddit.com/r/chicagogaybros/comments/1mmab21/steamworks_line/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','24_hour_operation_with_saturday_pride_market_days_event_line_membership_id_and_room_locker_planning','source_urls',to_jsonb(array['https://www.steamworksbaths.com/chicago','https://www.reddit.com/r/chicagogaybros/comments/1mmab21/steamworks_line/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','late_saturday_sunday_peak_weekday_evening_calm_and_2200_layout_orientation_before_midnight_surge','source_urls',to_jsonb(array['https://www.reddit.com/r/AskGaybrosOver30/comments/1f78cr5/just_had_my_first_evening_at_steamworks_in_chicago/','https://www.steamworksbaths.com/chicago']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','adult_men_local_tourist_multi_age_race_body_and_interest_mix_with_event_demographic_shifts','source_urls',to_jsonb(array['https://www.reddit.com/r/chicagogaybros/comments/1szdzex/my_review_of_steamworks/','https://www.reddit.com/r/AskGaybrosOver30/comments/1f78cr5/just_had_my_first_evening_at_steamworks_in_chicago/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','towel_or_permitted_clubwear_locker_security_shower_footwear_safer_sex_drink_and_consent_practicality','source_urls',to_jsonb(array['https://www.steamworksbaths.com/chicago','https://www.steamworksbaths.com/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','facility_scale_and_24_hour_praise_balanced_by_service_cleaning_closure_and_entry_line_variability','source_urls',to_jsonb(array['https://www.reddit.com/r/chicagogaybros/comments/1szdzex/my_review_of_steamworks/','https://www.steamworksbaths.com/chicago']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (959::bigint, jsonb_build_object(
      'queue_wait', 'The tiny room is usually a simple walk-in, but Pride, Market Days and late Saturday hours can fill it wall to wall. There is often no meaningful queue—just no space. Bring physical ID, arrive earlier for a stool and expect the city’s licensed late close.',
      'best_nights', 'Sunday karaoke and late weekend drinking show its personality; weekday afternoons and evenings are better for conversation. Come before midnight if you want to meet people, after for dense singalong energy. Special neighborhood weekends can overwhelm the small footprint.',
      'crowd_mix', 'Lesbians and queer women are the historic heart, joined by gay men, trans and nonbinary regulars, allies and visitors. The mix shifts broadly on big weekends. It remains one of the neighborhood’s few women-rooted queer bars, even though everyone respectful is welcome.',
      'dress_code', 'Anything comfortable works: jeans, tees, boots, trainers and an uncomplicated night-out look. There is no fashion gate. Pack light because the bar is genuinely small, bring valid ID and choose layers you can manage without a coat pile.',
      'staff_inclusivity', 'Many guests love the unpretentious conversation, lively bartenders and all-queer welcome. The counterweight is a serious record of complaints about door aggression, pricing and uneven treatment. Trust your read, keep the bill clear and leave or seek help if security escalates.',
      'venue_classification', 'active_tiny_long_running_lesbian_rooted_lgbtq_late_bar_in_lakeview_with_karaoke_conversation_gay_trans_nonbinary_ally_mix_no_pretension_and_mixed_current_service_door_safety_consensus',
      'identity_note', 'The Closet is a small, lesbian-rooted LGBTQ+ bar at 3325 N Broadway, not a men-only Boystown club. Its long hours and karaoke coexist with documented door and pricing concerns.',
      'source_urls', to_jsonb(array['https://www.theclosetchicago.com/','https://www.tripadvisor.com/Attraction_Review-g35805-d549371-Reviews-The_Closet-Chicago_Illinois.html','https://wanderlog.com/place/details/2234937/the-closet','https://www.travelgay.com/venue/the-closet-chicago','https://www.theinfatuation.com/chicago/reviews/the-closet']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','simple_walkin_tiny_capacity_pride_market_days_saturday_wall_to_wall_and_early_stool_strategy','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g35805-d549371-Reviews-The_Closet-Chicago_Illinois.html','https://www.travelgay.com/venue/the-closet-chicago']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','sunday_karaoke_late_weekend_density_weekday_conversation_and_special_weekend_overflow','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2234937/the-closet','https://www.tripadvisor.com/Attraction_Review-g35805-d549371-Reviews-The_Closet-Chicago_Illinois.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','lesbian_queer_woman_core_with_gay_male_trans_nonbinary_ally_and_visitor_mix','source_urls',to_jsonb(array['https://www.travelgay.com/venue/the-closet-chicago','https://www.theinfatuation.com/chicago/reviews/the-closet']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_fashion_gate_with_simple_casual_valid_id_light_baggage_and_small_space_layer_practicality','source_urls',to_jsonb(array['https://www.theinfatuation.com/chicago/reviews/the-closet','https://www.tripadvisor.com/Attraction_Review-g35805-d549371-Reviews-The_Closet-Chicago_Illinois.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','unpretentious_bartender_conversation_queer_welcome_praise_balanced_by_serious_door_aggression_price_and_treatment_complaints','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2234937/the-closet','https://www.tripadvisor.com/Attraction_Review-g35805-d549371-Reviews-The_Closet-Chicago_Illinois.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (955::bigint, jsonb_build_object(
      'queue_wait', 'The intimate Andersonville room is generally walk-in friendly, but Friday shows, piano karaoke and weekend brunch can consume its seats. Reserve when booking is offered or arrive before 19:00. There is no club door; the wait is for a good table and attentive cocktail service.',
      'best_nights', 'Tuesday and Thursday piano karaoke, Friday Haus of Elixir and weekend brunch give the lounge distinct personalities. A quiet Monday or Wednesday is best for date-night cocktails. Check the live calendar, because this is programme-led hospitality rather than one fixed scene.',
      'crowd_mix', 'Queer Andersonville locals, couples, friends, cocktail enthusiasts and mixed neighborhood diners share the room. Gay men are visible without owning the entire atmosphere. Shows and karaoke broaden the age and gender mix; brunch is especially relaxed and social.',
      'dress_code', 'Smart casual fits the low-lit room: denim, a good shirt, dresses, boots or polished trainers. No formal code is published. Dress for a date or a lingering drink rather than a sweaty club, and bring a layer for patio weather or strong winter air-conditioning.',
      'staff_inclusivity', 'Recent guests praise professional bartenders, balanced cocktails, warm hospitality and a room designed for lingering. The operator also publishes inclusion values. Prices lean upscale and busy programmes can slow service, but the evidence supports a thoughtful queer-friendly welcome.',
      'venue_classification', 'active_queer_friendly_andersonville_cocktail_lounge_and_kitchen_with_piano_karaoke_drag_show_brunch_date_night_programming_mixed_lgbtq_neighborhood_crowd_and_strong_cocktail_hospitality_consensus',
      'identity_note', 'The Elixir Lounge record refers to Elixir Andersonville at 1509 W Balmoral, an active cocktail lounge and kitchen. It should not be confused with the separate Lakeview Elixir location.',
      'source_urls', to_jsonb(array['https://elixirandersonville.com/','https://elixirchicago.com/values/','https://www.opentable.com/r/elixir-andersoneville-chicago','https://chicago.gaycities.com/bars/302156-elixir-lounge','https://www.chicagomag.com/dining-drinking/september-2015/sots-replay-elixir/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','walkin_friendly_with_friday_show_piano_karaoke_weekend_brunch_seat_constraint_and_early_reservation_strategy','source_urls',to_jsonb(array['https://elixirandersonville.com/','https://www.opentable.com/r/elixir-andersoneville-chicago']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','tuesday_thursday_piano_karaoke_friday_show_weekend_brunch_and_quiet_date_night_variation','source_urls',to_jsonb(array['https://elixirandersonville.com/','https://www.opentable.com/r/elixir-andersoneville-chicago']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','queer_andersonville_local_couple_friend_cocktail_fan_and_mixed_neighborhood_diner_mix','source_urls',to_jsonb(array['https://chicago.gaycities.com/bars/302156-elixir-lounge','https://www.chicagomag.com/dining-drinking/september-2015/sots-replay-elixir/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','smart_casual_date_lounge_style_without_formal_code_and_with_patio_winter_layer_practicality','source_urls',to_jsonb(array['https://elixirandersonville.com/','https://www.opentable.com/r/elixir-andersoneville-chicago']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','professional_bartender_balanced_cocktail_warm_hospitality_and_published_values_consensus_with_upscale_price_busy_service_caveat','source_urls',to_jsonb(array['https://elixirandersonville.com/','https://elixirchicago.com/values/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (958::bigint, jsonb_build_object(
      'queue_wait', 'Most afternoons and ordinary game nights are easy walk-ins. Cubs, Bears and major playoff broadcasts can fill the tables, pool area and bar without creating a formal club line. Arrive before kickoff or first pitch, bring physical ID and expect seat competition.',
      'best_nights', 'Choose a major game for communal cheering, karaoke for a looser night, or an off-peak weekday for pool, darts and conversation. Weekend afternoons can be more social than midnight. The sports calendar—not a DJ schedule—is the best planning tool.',
      'crowd_mix', 'Gay men are the longstanding core, with queer friends, allies, neighborhood regulars and sports fans across a broad age range. The room feels local and low-key rather than image-driven. Big Chicago games widen the mix while keeping the LGBTQ+ identity visible.',
      'dress_code', 'Team jerseys, hoodies, jeans, tees and trainers are entirely at home. There is no fashion gate. Wear what works for pool or darts, bring a layer for patio weather and keep valid ID handy. Game-day colors will earn more conversation than clubwear.',
      'staff_inclusivity', 'Reviews consistently describe friendly bartenders, professional handling of difficult moments and a welcoming neighborhood atmosphere. A simple service model keeps expectations clear. Peak games can slow drinks, but the consensus is notably warmer and steadier than many late clubs.',
      'venue_classification', 'active_long_running_northalsted_gay_sports_and_neighborhood_bar_with_many_tvs_pool_darts_karaoke_game_day_peaks_broad_age_local_gay_core_queer_allies_and_strong_friendly_professional_staff_consensus',
      'identity_note', 'The North End is an active gay sports and neighborhood bar at 3733 N Halsted. It is not a dance club, and food availability should not be assumed beyond outside-food policies.',
      'source_urls', to_jsonb(array['https://www.northendchicago.com/','https://wanderlog.com/place/details/3441726/the-north-end','https://www.tripadvisor.com/Restaurant_Review-g35805-d3737040-Reviews-The_North_End-Chicago_Illinois.html','https://www.theinfatuation.com/chicago/reviews/north-end','https://www.travelgay.com/venue/the-north-end-chicago']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','ordinary_walkin_major_chicago_game_table_bar_pool_capacity_without_typical_club_line','source_urls',to_jsonb(array['https://www.northendchicago.com/','https://wanderlog.com/place/details/3441726/the-north-end']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','major_game_communal_peak_karaoke_social_night_and_off_peak_pool_darts_conversation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/3441726/the-north-end','https://www.travelgay.com/venue/the-north-end-chicago']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_gay_male_core_queer_friend_ally_neighbor_sports_fan_and_broad_age_mix','source_urls',to_jsonb(array['https://www.theinfatuation.com/chicago/reviews/north-end','https://www.tripadvisor.com/Restaurant_Review-g35805-d3737040-Reviews-The_North_End-Chicago_Illinois.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','sports_jersey_hoodie_jeans_tee_trainer_casual_with_id_and_patio_layer_practicality','source_urls',to_jsonb(array['https://www.northendchicago.com/','https://wanderlog.com/place/details/3441726/the-north-end']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_professional_difficult_situation_handling_and_welcoming_neighborhood_consensus_with_game_peak_slowdown','source_urls',to_jsonb(array['https://wanderlog.com/place/details/3441726/the-north-end','https://www.tripadvisor.com/Restaurant_Review-g35805-d3737040-Reviews-The_North_End-Chicago_Illinois.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (956::bigint, jsonb_build_object(
      'queue_wait', 'The tiny cocktail room has no club line, but its few seats disappear quickly on Friday and Saturday. Happy hour or a weekday gives the easiest landing; summer sidewalk tables add capacity. Reservations are not the norm, so have a nearby second stop in mind.',
      'best_nights', 'Weekday happy hour is best for thoughtful cocktails and conversation; Saturday is buzzy but cramped. Summer evenings add people-watching outside. This is a pre-dinner or date-night lounge, not a late queer dance destination, and most visits last about an hour.',
      'crowd_mix', 'Lakeview couples, cocktail regulars, LGBTQ+ neighbors, restaurant guests and mixed friends share the intimate room. Its location and history make it queer-friendly, but it is not a dedicated gay bar. The crowd comes for drinks and atmosphere more than community programming.',
      'dress_code', 'Smart casual suits the dark, theatrical interior: denim, a good shirt, dresses, boots or polished trainers. There is no dress code. Choose a look for a close-set date table, and bring a light layer if you hope to use the sidewalk seats.',
      'staff_inclusivity', 'Recent reviews are exceptionally positive about attentive bartenders, imaginative drinks and warm service. The welcome appears broadly LGBTQ-friendly rather than mission-led. Limited seating and cocktail pacing are the main constraints; ask for guidance if the Asian-inspired menu feels unfamiliar.',
      'venue_classification', 'active_tiny_asian_inspired_lakeview_cocktail_lounge_connected_to_wakamono_with_dark_theatrical_decor_happy_hour_sidewalk_seating_mixed_lgbtq_friendly_neighborhood_crowd_and_strong_drink_service_consensus',
      'identity_note', 'Wang’s is an active Asian-inspired cocktail lounge at 3317 N Broadway, attached to Wakamono. It is LGBTQ-friendly by neighborhood and audience, not a dedicated gay bar.',
      'source_urls', to_jsonb(array['https://www.wakamono-chicago.com/wangs','https://www.timeout.com/chicago/bars/wangs','https://www.restaurantji.com/il/chicago/wangs-/','https://wanderlog.com/place/details/4040411/wangs','https://chicago.gaycities.com/bars/3644-wangs']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_club_line_tiny_weekend_seat_constraint_weekday_happy_hour_ease_and_summer_sidewalk_capacity','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4040411/wangs','https://www.restaurantji.com/il/chicago/wangs-/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekday_happy_hour_conversation_saturday_buzz_summer_sidewalk_and_short_date_pre_dinner_visit','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4040411/wangs','https://www.timeout.com/chicago/bars/wangs']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','lakeview_couple_cocktail_regular_lgbtq_neighbor_restaurant_guest_and_mixed_friend_crowd_not_dedicated_gay_bar','source_urls',to_jsonb(array['https://chicago.gaycities.com/bars/3644-wangs','https://www.timeout.com/chicago/bars/wangs']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','smart_casual_intimate_date_lounge_style_without_code_and_with_sidewalk_layer_practicality','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4040411/wangs','https://www.timeout.com/chicago/bars/wangs']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','exceptionally_positive_attentive_bartender_creative_drink_warm_service_consensus_with_limited_seating_and_cocktail_pacing','source_urls',to_jsonb(array['https://www.restaurantji.com/il/chicago/wangs-/','https://wanderlog.com/place/details/4040411/wangs']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (245::bigint, jsonb_build_object(
      'queue_wait', 'Small theatre events are orderly, while popular techno nights can create a selective door and late queue. Buy tickets in advance, bring accepted photo ID and know the event name and sound. Arriving before midnight usually improves both access and orientation.',
      'best_nights', 'Follow the programme: hard techno, house, live concerts, theatre and local showcases occupy different rooms and attract different people. A strong club booking on Friday or Saturday runs deep into morning; cultural events begin earlier. This is never one generic gay night.',
      'crowd_mix', 'Cologne clubbers, artists, students, queer people, international visitors and straight electronic-music fans mix by event. Queer guests are visible and some nights lean distinctly queer, but the venue itself is mixed. Music commitment matters more than sexuality.',
      'dress_code', 'For club nights, wear comfortable dark or expressive clothes, sturdy dancing shoes and hearing protection; theatre and concert audiences can stay casual. There is no universal costume, but a coherent event-aware look helps at the door. Pack light and plan the late trip home.',
      'staff_inclusivity', 'Local dancers value the sound, varied rooms and less glossy atmosphere, while door selectivity and reports of heavy drug use complicate the picture. Queer attendance is established, not exclusive. Stay with friends, guard drinks and seek the awareness or security team when needed.',
      'venue_classification', 'active_mixed_multispace_cologne_ehrenfeld_cultural_venue_and_electronic_club_with_theatre_concerts_house_hard_techno_local_showcases_event_specific_queer_presence_music_first_crowd_and_selective_door_safety_caveats',
      'identity_note', 'Artheater in Köln-Ehrenfeld is a mixed theatre, concert and electronic-club complex, not a dedicated gay club. Queer relevance depends on the specific event and crowd.',
      'source_urls', to_jsonb(array['https://artheater.de/','https://artheater.de/veranstaltungen/','https://www.instagram.com/artheater_cologne/','https://www.reddit.com/r/cologne/comments/1sutw1r/question_for_gays_in_cologne/','https://www.reddit.com/r/cologne/comments/1rkm06n/nachtclubs_in_k%C3%B6ln/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','orderly_theatre_popular_techno_selective_late_door_with_advance_ticket_id_event_knowledge_and_early_arrival','source_urls',to_jsonb(array['https://artheater.de/veranstaltungen/','https://www.instagram.com/artheater_cologne/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','programme_led_hard_techno_house_concert_theatre_local_showcase_and_weekend_late_club_variation','source_urls',to_jsonb(array['https://artheater.de/','https://artheater.de/veranstaltungen/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','cologne_clubber_artist_student_queer_international_and_straight_electronic_music_fan_mix_by_event','source_urls',to_jsonb(array['https://www.reddit.com/r/cologne/comments/1sutw1r/question_for_gays_in_cologne/','https://www.reddit.com/r/cologne/comments/1rkm06n/nachtclubs_in_k%C3%B6ln/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','event_aware_comfortable_dark_or_expressive_clubwear_dance_shoes_hearing_protection_light_bag_and_late_transport','source_urls',to_jsonb(array['https://www.instagram.com/artheater_cologne/','https://artheater.de/veranstaltungen/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','valued_sound_multispace_unglossy_queer_attendance_balanced_by_selective_door_and_drug_safety_concerns','source_urls',to_jsonb(array['https://www.reddit.com/r/cologne/comments/1sutw1r/question_for_gays_in_cologne/','https://www.reddit.com/r/cologne/comments/1f9t0ow/whats_the_most_druggy_club_in_k%C3%B6ln/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (476,957,438,959,955,958,956,245)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
