-- Queer Atlas venue intelligence: global review-led editorial pass, batch 57.
-- Eight Cartagena and Chiang Mai records checked against current official pages, listings and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, never in reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1243::bigint, jsonb_build_object(
      'queue_wait', 'No reliable current door or queue can be confirmed. The surviving reviews describe a tiny room and cover charge, but they are years old. Treat this as a legacy listing: do not travel to the saved pin unless a same-day official post proves that the bar has reopened.',
      'best_nights', 'There is no defensible current best night. Historic accounts point to a compact gay bar with weekend energy, yet no fresh programme, hours or active official channel surfaced. Choose a verified Cartagena venue instead of building an evening around this record.',
      'crowd_mix', 'Older reviews describe gay men, couples and international visitors in a very small room. That is historical context, not a promise about today. With no current operation verified, there is no responsible basis for describing a live crowd or community role.',
      'dress_code', 'No current dress policy exists in the evidence. Historic visitors arrived in easy tropical night-out clothes, but even that detail is secondary to the closure uncertainty. If the name reappears, verify the operator, address and door terms before planning what to wear.',
      'staff_inclusivity', 'Past guests sometimes found the staff kind, while others questioned cover and tourist pricing. Those dated, mixed accounts cannot establish a current service culture. The honest guidance is to withhold a recommendation until an active operator and recent community feedback are found.',
      'venue_classification', 'legacy_cartagena_gay_bar_listing_with_only_dated_small_room_cover_and_mixed_price_service_reviews_no_verified_current_official_presence_hours_programme_or_operation',
      'record_status', 'closed_or_unverified_legacy_listing_hide_from_search_maps_sitemap_city_counts_and_recommendations_until_current_operation_is_proven',
      'identity_note', 'Le Petit is supported only by dated visitor reviews; no current official operation, programme or dependable hours were verified in the 2026 review.',
      'source_urls', to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g297476-d12198682-Reviews-Le_Petit_Restaurante-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.tripadvisor.com.br/Restaurant_Review-g297476-d12198682-Reviews-Le_Petit_Restaurante-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.gayout.com/south-america/colombia/cartagena/bars']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_current_queue_hours_or_door_verified_with_only_dated_tiny_room_and_cover_reports','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g297476-d12198682-Reviews-Le_Petit_Restaurante-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.gayout.com/south-america/colombia/cartagena/bars']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','no_current_programme_or_best_night_verified_and_legacy_weekend_context_only','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g297476-d12198682-Reviews-Le_Petit_Restaurante-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.gayout.com/south-america/colombia/cartagena/bars']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_gay_male_couple_and_visitor_mix_not_valid_as_current_crowd_evidence','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g297476-d12198682-Reviews-Le_Petit_Restaurante-Cartagena_Cartagena_District_Bolivar_Department.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_current_dress_policy_with_only_historic_tropical_casual_context','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g297476-d12198682-Reviews-Le_Petit_Restaurante-Cartagena_Cartagena_District_Bolivar_Department.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','dated_kind_staff_reports_balanced_against_cover_and_tourist_price_concerns_not_current_consensus','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g297476-d12198682-Reviews-Le_Petit_Restaurante-Cartagena_Cartagena_District_Bolivar_Department.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1237::bigint, jsonb_build_object(
      'queue_wait', 'The small room is easiest early; Friday and Saturday can bunch at the entrance once the crossover music and rumba gather momentum. Current evidence is limited, so confirm the night’s flyer and any cover before leaving the old city for the Boston-area address.',
      'best_nights', 'Friday and Saturday offer the clearest chance of a lively floor. Earlier hours suit drinks and conversation; later brings the crossover soundtrack and party feel. Let a current post settle the schedule, because Cartagena’s smaller queer bars can change nights without much notice.',
      'crowd_mix', 'Local gay men and LGBTQ+ friends form the base, with allies and curious visitors joining on busier nights. It feels neighborhood-led rather than tourist-built. The modest review pool supports a warm, social crowd, but not a claim that every evening will be full.',
      'dress_code', 'Light smart-casual clothes, stylish shorts, a fitted shirt and clean trainers suit the tropical bar setting. No formal code is published. Prioritize breathable fabric and a planned ride home; the location is outside the most walkable visitor core.',
      'staff_inclusivity', 'Current listings and reviews consistently frame the bar as welcoming and friendly, though the evidence base is small. Expect an explicitly gay space rather than a polished megaclub. Confirm prices before ordering and judge the welcome by the actual team on duty.',
      'venue_classification', 'active_small_neighborhood_cartagena_gay_bar_in_boston_area_with_crossover_music_weekend_rumba_local_lgbtq_core_allies_and_visitors_positive_but_limited_current_review_consensus',
      'identity_note', 'Patio Bonito Cartagena is a small gay bar outside the old-city nightlife core, not a luxury patio venue. Current programme and transport should be checked before travel.',
      'source_urls', to_jsonb(array['https://qlist.app/venues/Cartagena-de-Indias/Patio-bonito-Cartagena/elhjdWZiQ3ViTTlWVEVud1RvOVlFZw','https://wanderlog.com/es/place/details/12913187/patio-bonito-cartagena','https://www.gaybnbtravel.com/place/patio-bonito-cartagena','https://www.gayout.com/south-america/colombia/cartagena/bars']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_room_early_ease_weekend_door_bunching_and_live_cover_schedule_verification','source_urls',to_jsonb(array['https://qlist.app/venues/Cartagena-de-Indias/Patio-bonito-Cartagena/elhjdWZiQ3ViTTlWVEVud1RvOVlFZw','https://wanderlog.com/es/place/details/12913187/patio-bonito-cartagena']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_crossover_rumba_peak_with_current_flyer_priority','source_urls',to_jsonb(array['https://qlist.app/venues/Cartagena-de-Indias/Patio-bonito-Cartagena/elhjdWZiQ3ViTTlWVEVud1RvOVlFZw','https://www.gayout.com/south-america/colombia/cartagena/bars']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_gay_lgbtq_friend_ally_and_occasional_visitor_neighborhood_mix_with_small_sample','source_urls',to_jsonb(array['https://www.gaybnbtravel.com/place/patio-bonito-cartagena','https://qlist.app/venues/Cartagena-de-Indias/Patio-bonito-Cartagena/elhjdWZiQ3ViTTlWVEVud1RvOVlFZw']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_formal_code_with_tropical_smart_casual_and_transport_practicality','source_urls',to_jsonb(array['https://www.gayout.com/south-america/colombia/cartagena/bars','https://www.gaybnbtravel.com/place/patio-bonito-cartagena']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','explicitly_gay_friendly_social_consensus_limited_by_small_current_review_pool','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/12913187/patio-bonito-cartagena','https://qlist.app/venues/Cartagena-de-Indias/Patio-bonito-Cartagena/elhjdWZiQ3ViTTlWVEVud1RvOVlFZw']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1235::bigint, jsonb_build_object(
      'queue_wait', 'Most visits are straightforward, with the busiest door on Saturday and Sunday evenings. Pay at the entrance, ask what is included and keep the receipt; recent reviews disagree sharply about one security interaction. The saved address is in Barrio España, not the old city.',
      'best_nights', 'Saturday and Sunday are the reliable social peaks. Go around early evening for a drink and conversation, later for Latino pop, the video room and darker upstairs spaces. This is a men-focused social and cruise bar, not a conventional tourist dance club.',
      'crowd_mix', 'Local men dominate, joined by Colombian visitors and a smaller international contingent. Ages and body types are varied, and the tone moves from convivial bar chat to cruising. The dedicated male focus is much clearer than the broader mixed crowd found at Cartagena’s dance clubs.',
      'dress_code', 'Casual clothes and easy footwear are enough; lockers are reportedly available if you want to change. Bring little, keep your key secure and treat every darker room as consent-led space. No fashionable door code is evident, but practical awareness matters.',
      'staff_inclusivity', 'Many guests praise attentive bartenders, fair prices and help arranging a safe taxi. A serious recent complaint about security and the owner response prevents an unqualified endorsement. State boundaries clearly, keep payment visible and leave if an interaction feels coercive.',
      'venue_classification', 'active_men_focused_gay_video_and_cruise_bar_in_barrio_espana_cartagena_with_latino_pop_video_room_dark_spaces_weekend_peak_local_core_and_mixed_service_security_consensus',
      'identity_note', 'ROMA CLUB VIDEO BAR and Video Bar Geminis are the same men-focused venue at Calle 31 #44-54; it is not a generic nightclub in Cartagena’s tourist center.',
      'source_urls', to_jsonb(array['https://restaurantguru.com/Geminis-Cartagena','https://wanderlog.com/place/details/6699036/roma-club-video-bar-video-bar-geminis','https://www.waze.com/es-419/live-map/directions/co/bolivar/cartagena-de-indias/roma-club-video-bar-%28video-bar-geminis%29?to=place.ChIJXZ2Jn50l9o4RfvIFBCQjuNY','https://es.restaurantguru.com/Geminis-Cartagena']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','straightforward_entry_saturday_sunday_peak_receipt_terms_and_recent_security_dispute','source_urls',to_jsonb(array['https://restaurantguru.com/Geminis-Cartagena','https://wanderlog.com/place/details/6699036/roma-club-video-bar-video-bar-geminis']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','saturday_sunday_social_peak_with_latino_pop_video_and_dark_room_progression','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6699036/roma-club-video-bar-video-bar-geminis','https://restaurantguru.com/Geminis-Cartagena']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_male_core_colombian_and_international_visitors_varied_age_body_and_cruise_intent','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6699036/roma-club-video-bar-video-bar-geminis','https://es.restaurantguru.com/Geminis-Cartagena']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','casual_no_fashion_gate_with_reported_lockers_minimal_valuables_and_consent_practicality','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6699036/roma-club-video-bar-video-bar-geminis']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','attentive_bartender_taxi_and_value_praise_balanced_against_serious_recent_security_complaint','source_urls',to_jsonb(array['https://restaurantguru.com/Geminis-Cartagena','https://wanderlog.com/place/details/6699036/roma-club-video-bar-video-bar-geminis']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1241::bigint, jsonb_build_object(
      'queue_wait', 'Hotel arrival is usually polished, but afternoon check-in, Sunday brunch and courtyard dining can compress in high season. Reserve restaurant, spa and celebration plans ahead. There is no nightlife door, and the walled-city address makes most evening outings walkable.',
      'best_nights', 'A weekday best reveals the convent courtyards at their calmest; weekends add weddings, brunch and old-city energy. Begin with a courtyard or pool drink, then walk to dinner. The hotel is heritage luxury rather than a queer party base, so the city supplies the late night.',
      'crowd_mix', 'International luxury travellers, Colombian couples, wedding groups, families and cultural visitors make up the house. LGBTQ+ guests join a mainstream upscale mix rather than a visible community scene. Public areas become especially visitor-heavy around brunch and the pool.',
      'dress_code', 'Polished tropical resort wear fits: linen, dresses, tailored shorts and a light dinner layer. Swimwear belongs by the pool, with a cover-up through the cloisters. No discriminatory fashion gate surfaced, though the historic five-star setting leans elegant.',
      'staff_inclusivity', 'Reviews often praise warm, attentive service and the memorable historic setting, while some recent guests report uneven room upkeep or slower response at peak times. No property-specific LGBTQ+ training proof surfaced; state bedding and celebration details clearly in writing.',
      'venue_classification', 'active_mainstream_five_star_heritage_hotel_in_restored_cartagena_convent_with_courtyards_pool_spa_restaurants_luxury_international_colombian_guest_mix_and_strong_but_not_uniform_service_consensus',
      'identity_note', 'Sofitel Legend Santa Clara is a mainstream luxury heritage hotel, not an LGBTQ+-specific property. Its queer relevance is general hospitality and a central location, not dedicated programming.',
      'source_urls', to_jsonb(array['https://all.accor.com/hotel/1871/index.en.shtml','https://www.sofitellegendsantaclara.com/','https://www.booking.com/reviews/co/hotel/sofitel-santa-clara.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297476-d299634-Reviews-Sofitel_Legend_Santa_Clara_Cartagena-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.reddit.com/r/cartagena/comments/1bf7yrm']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','polished_arrival_with_high_season_checkin_brunch_dining_spa_capacity_and_reservation_need','source_urls',to_jsonb(array['https://all.accor.com/hotel/1871/index.en.shtml','https://www.booking.com/reviews/co/hotel/sofitel-santa-clara.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','calmer_weekday_heritage_stay_weekend_wedding_brunch_energy_and_walkable_old_city_evening','source_urls',to_jsonb(array['https://www.sofitellegendsantaclara.com/','https://www.tripadvisor.com/Hotel_Review-g297476-d299634-Reviews-Sofitel_Legend_Santa_Clara_Cartagena-Cartagena_Cartagena_District_Bolivar_Department.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','international_luxury_colombian_couple_wedding_family_and_cultural_mainstream_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/sofitel-santa-clara.en-gb.html','https://all.accor.com/hotel/1871/index.en.shtml']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','polished_tropical_resort_and_dinner_style_without_verified_discriminatory_door_code','source_urls',to_jsonb(array['https://www.sofitellegendsantaclara.com/','https://all.accor.com/hotel/1871/index.en.shtml']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','frequent_warm_attentive_service_praise_with_peak_response_and_upkeep_caveats_no_verified_lgbtq_training','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/sofitel-santa-clara.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297476-d299634-Reviews-Sofitel_Legend_Santa_Clara_Cartagena-Cartagena_Cartagena_District_Bolivar_Department.html','https://www.reddit.com/r/cartagena/comments/1bf7yrm']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1511::bigint, jsonb_build_object(
      'queue_wait', 'The room is seated and usually easy to enter before the first show; later arrivals may wait for a better table rather than a long street line. No cover is commonly reported, but drinks for hosts are optional and separate. Ask the sequence and prices before settling in.',
      'best_nights', 'Any advertised show night can work because performance, not a single weekend crush, is the point. Arrive before the first set for a clear view; stay for male dance, cabaret and drag. Check the current programme, as cast and show times can shift.',
      'crowd_mix', 'Gay men are central, with international visitors, expats, local Thai guests and some women or allies watching the show. The hosts are part of the social format, so the mood is more cabaret and flirtation than anonymous clubbing. Mixed ages are normal.',
      'dress_code', 'Neat casual evening clothes are right: a clean shirt, shorts or trousers and presentable shoes. There is no published formal code. Dress for an air-conditioned seated show, carry enough for your own drinks and decide your boundaries before host interaction begins.',
      'staff_inclusivity', 'Recent guests praise the friendly owner, performers and lack of pressure, though host-drink customs can be unfamiliar. The venue is explicitly for gay nightlife, and consent should stay simple: invitations are optional, prices should be clear and a polite no should be enough.',
      'venue_classification', 'active_long_running_chiang_mai_gay_male_cabaret_and_host_bar_with_seated_male_dance_drag_and_singer_shows_tourist_expat_local_mix_optional_host_drinks_and_positive_recent_welcome_consensus',
      'identity_note', 'Adam’s Apple Club is a gay male cabaret and host bar in Chang Phueak, not a general dance club. The core experience is a seated show with optional social interaction.',
      'source_urls', to_jsonb(array['https://www.adamsappleclub.com/','https://www.tripadvisor.com/Attraction_Review-g17484209-d27476102-Reviews-Adam_s_Apple_Club-Chang_Phueak_Chiang_Mai.html','https://www.travelgay.com/venue/adams-apple-club','https://www.gay-in-chiangmai.com/main/media/2021/04/gay-chiang-mai-venues-quick-reference-list-v12.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','seated_early_entry_later_table_choice_no_cover_reports_and_optional_host_drink_terms','source_urls',to_jsonb(array['https://www.adamsappleclub.com/','https://www.tripadvisor.com/Attraction_Review-g17484209-d27476102-Reviews-Adam_s_Apple_Club-Chang_Phueak_Chiang_Mai.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','advertised_show_led_visit_with_early_arrival_for_male_dance_cabaret_drag_and_singers','source_urls',to_jsonb(array['https://www.adamsappleclub.com/','https://www.travelgay.com/venue/adams-apple-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_male_core_with_international_expat_thai_woman_and_ally_show_audience_across_ages','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g17484209-d27476102-Reviews-Adam_s_Apple_Club-Chang_Phueak_Chiang_Mai.html','https://www.travelgay.com/venue/adams-apple-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','neat_casual_air_conditioned_seated_show_style_without_published_formal_code','source_urls',to_jsonb(array['https://www.adamsappleclub.com/','https://www.tripadvisor.com/Attraction_Review-g17484209-d27476102-Reviews-Adam_s_Apple_Club-Chang_Phueak_Chiang_Mai.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_owner_performer_low_pressure_consensus_with_optional_host_drink_boundary_and_price_clarity','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g17484209-d27476102-Reviews-Adam_s_Apple_Club-Chang_Phueak_Chiang_Mai.html','https://www.adamsappleclub.com/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1507::bigint, jsonb_build_object(
      'queue_wait', 'This tiny open-front bar rarely has a formal line; the challenge is finding a seat after about 21:00. Drop in earlier for the easy Night Bazaar mood. Hours shown by directories conflict at the edges, so confirm close time if it is your final stop.',
      'best_nights', 'Friday and Saturday bring the broadest mix, but the bar’s charm is a relaxed drink on any evening after the market. Around 20:00–22:00 balances conversation, music and local company. It is a wind-down bar, not a late dance-floor destination.',
      'crowd_mix', 'Local LGBTQ+ regulars and staff mingle with gay travellers, expats, friends and open-minded market visitors. The room is small enough that people actually talk. Gay identity is clear, but the welcome is broader than a men-only host bar.',
      'dress_code', 'Market-night casual is perfect: shorts, tees, sandals or trainers and a rain-ready layer in wet season. There is no fashion gate. Choose comfort for outdoor seating and nearby walking, while keeping bags tucked close in the busy bazaar area.',
      'staff_inclusivity', 'The strongest review pattern is unusually warm: guests describe staff who remember newcomers, share food and make solo visitors feel at home. Prices are also praised as fair. It remains a small informal bar, so accessibility and service pace depend on the space available.',
      'venue_classification', 'active_tiny_open_front_gay_bar_behind_chiang_mai_night_bazaar_with_outdoor_seating_affordable_drinks_food_music_local_lgbtq_traveller_expat_mix_and_exceptionally_warm_small_sample_service_consensus',
      'identity_note', 'Chiang Mai 19 Bar is a small gay bar behind the Night Bazaar with outdoor seating and food, not a large club. Its current reviews support an active operation.',
      'source_urls', to_jsonb(array['https://www.travelgay.com/venue/chiang-mai-19-bar','https://wanderlog.com/place/details/4602005','https://www.gay-in-chiangmai.com/main/media/2019/01/gay-chiang-mai-venues-quick-reference-list-v10.pdf','https://www.gay-in-chiangmai.com/main/media/2020/02/gay-chiang-mai-venues-quick-reference-list-v11.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_formal_line_tiny_seating_constraint_after_2100_and_directory_close_time_variation','source_urls',to_jsonb(array['https://www.travelgay.com/venue/chiang-mai-19-bar','https://wanderlog.com/place/details/4602005']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_broadest_mix_with_2000_2200_conversation_music_market_wind_down_sweet_spot','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4602005','https://www.travelgay.com/venue/chiang-mai-19-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_lgbtq_staff_regular_gay_traveller_expat_friend_and_open_minded_market_visitor_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4602005','https://www.travelgay.com/venue/chiang-mai-19-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_fashion_gate_with_market_casual_outdoor_weather_and_bag_practicality','source_urls',to_jsonb(array['https://www.travelgay.com/venue/chiang-mai-19-bar','https://wanderlog.com/place/details/4602005']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','exceptionally_warm_home_like_solo_friendly_and_fair_price_consensus_with_small_informal_space_limits','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4602005','https://www.travelgay.com/venue/chiang-mai-19-bar']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1505::bigint, jsonb_build_object(
      'queue_wait', 'Check-in is personal rather than corporate, and the compact heritage house can slow when several guests arrive together. Send your arrival time, especially late. The attached men’s sauna becomes active after 15:00, but lodging guests and day visitors use different access flows.',
      'best_nights', 'Stay when you want riverside calm by day and the men’s sauna social scene from late afternoon. Friday and Saturday feel livelier; a weekday is quieter in the teak house. The property is a short ride from the center, so plan transport for other nightlife.',
      'crowd_mix', 'Gay men are the explicit audience: solo travellers, couples, regional visitors, expats and local sauna guests across a wide age and body range. Hotel residents share facilities with day visitors after 15:00, giving the property a social, adult men-only character.',
      'dress_code', 'Casual resort clothes work for breakfast and the river terrace; swimwear or the issued towel suits wet facilities. Heritage rooms can transmit sound, so pack earplugs. Sandals are useful around the pool and showers, and consent remains the only meaningful rule in cruise areas.',
      'staff_inclusivity', 'Large verified-review samples praise warm, helpful staff and value, while a minority report weak English, noise handling, charges or dated upkeep. The gay-men focus is unambiguous. Confirm room type, guest policy and any fees in writing before arrival.',
      'venue_classification', 'active_gay_men_only_guesthouse_in_historic_ping_river_teak_house_with_breakfast_pool_gym_and_integrated_mens_sauna_social_scene_strong_value_staff_consensus_balanced_by_age_noise_and_service_variability',
      'identity_note', 'Club One Seven Gay Men Guesthouse is the accommodation component of the riverside men’s complex; it shares facilities and atmosphere with the separately accessible sauna.',
      'source_urls', to_jsonb(array['https://www.cluboneseven.net/','https://www.agoda.com/en-gb/club-one-seven-gay-men-hotel-chiang-mai/hotel/chiang-mai-th.html','https://www.hotels.com/ho460334/club-one-seven-gaymen-chiang-mai/','https://www.gay-in-chiangmai.com/news/2024/club-one-seven-gay-guesthouse-chiang-mai/','https://www.oyster.com/chiang-mai/hotels/club-one-seven-chiang-mai/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','personal_compact_guesthouse_checkin_arrival_notice_and_separate_lodging_day_sauna_access_flows','source_urls',to_jsonb(array['https://www.cluboneseven.net/','https://www.hotels.com/ho460334/club-one-seven-gaymen-chiang-mai/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','late_afternoon_sauna_social_weekend_energy_weekday_heritage_quiet_and_offsite_transport_need','source_urls',to_jsonb(array['https://www.agoda.com/en-gb/club-one-seven-gay-men-hotel-chiang-mai/hotel/chiang-mai-th.html','https://www.gay-in-chiangmai.com/news/2024/club-one-seven-gay-guesthouse-chiang-mai/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_men_only_solo_couple_regional_expat_and_local_sauna_guest_mix_across_age_and_body_range','source_urls',to_jsonb(array['https://www.agoda.com/en-gb/club-one-seven-gay-men-hotel-chiang-mai/hotel/chiang-mai-th.html','https://www.cluboneseven.net/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','casual_riverside_swimwear_towel_sandals_earplugs_and_cruise_consent_practicality','source_urls',to_jsonb(array['https://www.oyster.com/chiang-mai/hotels/club-one-seven-chiang-mai/','https://www.agoda.com/en-gb/club-one-seven-gay-men-hotel-chiang-mai/hotel/chiang-mai-th.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_warm_helpful_value_consensus_balanced_by_language_noise_charge_and_dated_upkeep_complaints','source_urls',to_jsonb(array['https://www.agoda.com/en-gb/club-one-seven-gay-men-hotel-chiang-mai/hotel/chiang-mai-th.html','https://www.hotels.com/ho460334/club-one-seven-gaymen-chiang-mai/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1508::bigint, jsonb_build_object(
      'queue_wait', 'Entry is usually quick after the 15:00 opening: pay outside, take the receipt inside, then collect a locker key and towel. Weekend peaks may slow reception briefly. Current reports place admission around 160 baht, but confirm price and re-entry terms on arrival.',
      'best_nights', 'Saturday from roughly 18:00 to 21:00 gives the fullest pool, steam and cruise areas; weekdays around 19:00 can still be sociable. Earlier suits swimming and the river view, while later is more purposeful. Crowds can change quickly, so allow time rather than chasing one exact hour.',
      'crowd_mix', 'Thai men form the majority, joined by East Asian visitors, Western travellers and guesthouse residents. Recent reports span twenties through sixties and many body types, with a relaxed local-first tone. It is an adult men-only environment rather than an all-gender queer spa.',
      'dress_code', 'You change into a towel; sandals are sensible on concrete and wet floors. Bring minimal valuables and consider paying for a larger towel if offered. In the dark maze and private rooms, enthusiastic consent, safer-sex choices and an easy path to leave matter more than appearance.',
      'staff_inclusivity', 'Guests often find the atmosphere easygoing and facilities good value, with clean pool and private-room reports. Criticism centers on occasional reception gaps, small towels and uneven floor cleanliness. Staff instructions at entry should be followed; raise practical needs before changing.',
      'venue_classification', 'active_men_only_gay_sauna_and_cruise_club_on_ping_river_with_pool_gym_steam_dry_sauna_dark_maze_private_rooms_local_thai_majority_weekend_evening_peak_and_good_value_mixed_facility_service_consensus',
      'identity_note', 'Club One Seven Sauna is the day-entry men’s sauna within the same riverside complex as the guesthouse; it is not a separate city-center address or a general wellness spa.',
      'source_urls', to_jsonb(array['https://www.cluboneseven.net/','https://gayandasia.com/en/venue/review/clubonesevensauna','https://www.gayout.com/asia-aus/thailand/chiang-mai/saunas/club-one-seven-sauna-2098','https://www.gay-in-chiangmai.com/news/2024/club-one-seven-gay-guesthouse-chiang-mai/','https://www.reddit.com/r/gaytravel/comments/1j23w0u']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','quick_receipt_to_locker_entry_after_1500_weekend_reception_slowdown_and_current_price_confirmation','source_urls',to_jsonb(array['https://gayandasia.com/en/venue/review/clubonesevensauna','https://www.cluboneseven.net/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','saturday_1800_2100_fullest_weekday_1900_social_and_earlier_pool_later_cruise_progression','source_urls',to_jsonb(array['https://gayandasia.com/en/venue/review/clubonesevensauna','https://www.gayout.com/asia-aus/thailand/chiang-mai/saunas/club-one-seven-sauna-2098']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','thai_male_majority_east_asian_western_guesthouse_and_varied_age_body_mix','source_urls',to_jsonb(array['https://gayandasia.com/en/venue/review/clubonesevensauna','https://www.reddit.com/r/gaytravel/comments/1j23w0u']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','towel_sandals_minimal_valuables_larger_towel_option_and_dark_area_consent_safer_sex_practicality','source_urls',to_jsonb(array['https://gayandasia.com/en/venue/review/clubonesevensauna','https://www.cluboneseven.net/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','easygoing_good_value_clean_pool_room_consensus_balanced_by_reception_towel_and_floor_cleanliness_issues','source_urls',to_jsonb(array['https://gayandasia.com/en/venue/review/clubonesevensauna','https://www.gayout.com/asia-aus/thailand/chiang-mai/saunas/club-one-seven-sauna-2098']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (1243);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1243,1237,1235,1241,1511,1507,1505,1508)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
