-- Queer Atlas venue intelligence: global review-led editorial pass, batch 33.
-- Eight remaining Beirut records, individually researched and rewritten.
-- Hilton Beirut Habtoor Grand is renamed and placed on booking hold after a 2026 group exit announcement.
-- Le Vendome remains permanently closed and must not be offered as active lodging.
-- Checked 2026-08-06. Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1778::bigint, jsonb_build_object(
      'queue_wait', 'Check-in is personal rather than grand-hotel formal, but message your arrival if you are coming late or carrying heavy bags: the old Saint Nicolas stairway building has no lift. Dorm turnover can add a short reception pause. The café terrace is easier; take a seat once staff confirm what is free.',
      'best_nights', 'Choose this base for Gemmayzeh and Mar Mikhael rather than an in-house party. Friday and Saturday put bars close at hand, while a weekday gives you quieter stairs and a more social breakfast. Light sleepers should request a room away from dorm doors and the generator before a weekend stay.',
      'crowd_mix', 'Solo travellers, backpackers, creative visitors, regional guests and budget-minded couples share dorms, private rooms, breakfast and the street terrace. The tone is international but connected to the neighbourhood. It is not a gay hotel, though recent queer travellers call it a comfortable, friendly option.',
      'dress_code', 'Pack for stairs and shared-space living: comfortable shoes, easy layers, sleepwear you can cross a corridor in and earplugs for creaky doors or generator hum. A private room gives more ease for couples; dorm guests should keep valuables locked and respect the room’s gender and quiet-hour setup.',
      'staff_inclusivity', 'The clearest current pattern is warmth: guests repeatedly praise kind, attentive staff, practical local advice and help carrying luggage. Recent queer-community recommendations add a positive signal, but there is no published LGBTQ+ policy. Ask discreetly about room setup if travelling as a couple.',
      'venue_classification', 'active_social_budget_hotel_hostel_on_saint_nicolas_steps_with_strong_staff_reviews_and_current_queer_friendly_signal',
      'source_urls', to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-grand-meshmosh.en-gb.html','https://www.hostelworld.com/hotels/p/264089/the-grand-meshmosh-hotel/','https://www.tripadvisor.co.uk/Hotel_Review-g294005-d8932229-Reviews-The_Grand_Meshmosh_Hotel-Beirut.html','https://www.reddit.com/r/LGBTLebanon/comments/1ule6s9/hotels_apartments_gay_friendly/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_personal_checkin_no_lift_stair_access_and_social_terrace_context','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-grand-meshmosh.en-gb.html','https://www.hostelworld.com/hotels/p/264089/the-grand-meshmosh-hotel/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_gemmayzeh_bar_access_social_breakfast_and_noise_generator_consensus','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-grand-meshmosh.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g294005-d8932229-Reviews-The_Grand_Meshmosh_Hotel-Beirut.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_solo_backpacker_couple_business_and_international_traveller_mix_with_queer_friendly_signal','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-grand-meshmosh.en-gb.html','https://www.reddit.com/r/LGBTLebanon/comments/1ule6s9/hotels_apartments_gay_friendly/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','old_building_stairs_shared_bath_dorm_noise_and_private_room_context','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-grand-meshmosh.en-gb.html','https://www.hostelworld.com/hotels/p/264089/the-grand-meshmosh-hotel/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_kind_helpful_staff_consensus_plus_recent_queer_traveller_recommendation_without_formal_policy','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-grand-meshmosh.en-gb.html','https://www.reddit.com/r/LGBTLebanon/comments/1ule6s9/hotels_apartments_gay_friendly/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1780::bigint, jsonb_build_object(
      'queue_wait', 'Do not book from the legacy Hilton name without direct written confirmation. The property was renamed Al Habtoor Grand, then its owner announced in January 2026 that Lebanese operations and employment would cease. Booking shells and early-2026 reviews remain online, so current check-in status is unresolved.',
      'best_nights', 'There is no responsible stay recommendation until the operator confirms that rooms, spa and staff are functioning now. Historically the high-rise suited conferences, mall access and pool downtime more than central nightlife. If it reopens under a new team, judge a specific live rate and service list.',
      'crowd_mix', 'Before the ownership dispute, this was a large mainstream luxury and conference hotel serving business delegations, Gulf visitors, families and tour groups in Sin El Fil. It was never a queer hotel. No current guest mix should be inferred from pre-closure reviews or the former international brand.',
      'dress_code', 'Not applicable while operation is uncertain. For any verified successor, normal upscale-hotel clothing and government ID would be enough, with swimwear and spa attire confined to those facilities. Confirm the legal hotel name on the reservation so an old loyalty-brand label does not strand you at arrival.',
      'staff_inclusivity', 'Late-2025 and January-2026 guests praised friendly, helpful reception, but the owner then announced layoffs across its Lebanese operations. Those reviews cannot describe a future team. No current LGBTQ+ policy was found; inclusion and even staffing must be reconfirmed before this returns to sale.',
      'venue_classification', 'renamed_former_hilton_luxury_conference_hotel_with_unresolved_operation_after_january_2026_owner_exit_announcement',
      'record_status', 'editorial_hold_do_not_book_until_current_operator_and_open_status_are_directly_verified',
      'identity_note', 'The hotel is no longer Hilton-branded and is now listed as Al Habtoor Grand. In January 2026 the owner announced it would cease Lebanese operations and terminate employees; remaining booking pages are not sufficient evidence of continued operation.',
      'source_urls', to_jsonb(array['https://apnews.com/article/66b09d25b4e543bb0b43950efa8058fe','https://today.lorientlejour.com/article/1457854/khalaf-al-habtoors-new-bold-project-dismantle-and-transfer-metropolitan-beirut.html','https://www.habtoor.com/en/10/divisions/hospitality/','https://www.booking.com/reviews/lb/hotel/hilton-beirut-habtoor-grand-hotel.en-gb.html','https://uk.hotels.com/ho232451/hilton-beirut-habtoor-grand-sin-el-fil-lebanon/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','confirmed_rebrand_and_january_2026_exit_announcement_conflicting_with_live_booking_shells','source_urls',to_jsonb(array['https://apnews.com/article/66b09d25b4e543bb0b43950efa8058fe','https://today.lorientlejour.com/article/1457854/khalaf-al-habtoors-new-bold-project-dismantle-and-transfer-metropolitan-beirut.html','https://www.booking.com/reviews/lb/hotel/hilton-beirut-habtoor-grand-hotel.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_conference_mall_pool_profile_without_verified_post_exit_service_operation','source_urls',to_jsonb(array['https://www.habtoor.com/en/10/divisions/hospitality/','https://uk.hotels.com/ho232451/hilton-beirut-habtoor-grand-sin-el-fil-lebanon/','https://apnews.com/article/66b09d25b4e543bb0b43950efa8058fe']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_mainstream_business_gulf_family_and_group_hotel_without_current_or_queer_specific_mix','source_urls',to_jsonb(array['https://www.habtoor.com/en/10/divisions/hospitality/','https://www.booking.com/reviews/lb/hotel/hilton-beirut-habtoor-grand-hotel.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','inactive_uncertain_operator_legal_name_id_and_facility_verification_context','source_urls',to_jsonb(array['https://apnews.com/article/66b09d25b4e543bb0b43950efa8058fe','https://today.lorientlejour.com/article/1457854/khalaf-al-habtoors-new-bold-project-dismantle-and-transfer-metropolitan-beirut.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','positive_pre_exit_staff_reviews_invalidated_by_announced_termination_and_no_current_lgbtq_policy','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/hilton-beirut-habtoor-grand-hotel.en-gb.html','https://apnews.com/article/66b09d25b4e543bb0b43950efa8058fe']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1783::bigint, jsonb_build_object(
      'queue_wait', 'Arrival is polished and reservation-led, not queue-based. Rooftop tables can fill, especially around sunset, so hotel guests should still book dinner or drinks ahead. Standard check-in begins at 3 pm with photo ID and card; send your arrival time if you want the old-school service to feel seamless.',
      'best_nights', 'Use a clear evening for rooftop cocktails, sunset over the city and dinner around the pool; reserve early in summer. A weekday protects the mansion’s slow, romantic mood, while Friday or Saturday makes a luxurious launch into Achrafieh nightlife. The hotel itself rewards lingering more than rushing out.',
      'crowd_mix', 'Affluent Beirut residents at the rooftop, international couples, design travellers and discreet luxury regulars shape the room. It is intimate rather than scene-heavy, with locals especially visible at dinner. Queer guests are explicitly welcomed, but this is an elegant mixed hotel, not an LGBTQ+ social hub.',
      'dress_code', 'Lean into relaxed elegance: linen, a crisp shirt, a fluid dress, polished flats or smart trainers work from the library to the rooftop. Swimwear belongs by the pool, not at dinner. The handpicked interiors reward personality and texture; loud labels are less useful than clothes that feel considered.',
      'staff_inclusivity', 'Current stays praise professional, service-minded care from reception through housekeeping, and the hotel actively presents itself as LGBTQ+-welcoming through a specialist travel partnership. One account found smiles restrained, but the broader pattern is discreet, competent hospitality rather than performative fuss.',
      'venue_classification', 'active_luxury_achrafieh_mansion_hotel_with_rooftop_pool_strong_service_consensus_and_explicit_lgbtq_welcome',
      'source_urls', to_jsonb(array['https://www.albergobeirut.com/','https://www.booking.com/hotel/lb/albergo.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294005-d306317-Reviews-Hotel_Albergo-Beirut.html','https://www.travelgay.com/gay-beirut-hotels/','https://www.tripadvisor.co.uk/Restaurant_Review-g294005-d2490955-Reviews-Albergo_Rooftop-Beirut.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_three_pm_checkin_id_arrival_notice_and_rooftop_advance_booking_evidence','source_urls',to_jsonb(array['https://www.booking.com/hotel/lb/albergo.en-gb.html','https://www.tripadvisor.co.uk/Restaurant_Review-g294005-d2490955-Reviews-Albergo_Rooftop-Beirut.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_sunset_rooftop_pool_dinner_and_achrafieh_weekend_launch_context','source_urls',to_jsonb(array['https://www.albergobeirut.com/','https://www.booking.com/hotel/lb/albergo.en-gb.html','https://www.tripadvisor.co.uk/Restaurant_Review-g294005-d2490955-Reviews-Albergo_Rooftop-Beirut.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_affluent_local_international_couple_design_traveller_and_explicit_queer_guest_welcome','source_urls',to_jsonb(array['https://www.travelgay.com/gay-beirut-hotels/','https://www.booking.com/hotel/lb/albergo.en-gb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_mansion_rooftop_pool_and_elegant_dining_context_without_published_strict_code','source_urls',to_jsonb(array['https://www.albergobeirut.com/','https://www.travelgay.com/gay-beirut-hotels/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_professional_service_consensus_and_explicit_lgbtq_partnership_with_minor_warmth_variation','source_urls',to_jsonb(array['https://www.booking.com/hotel/lb/albergo.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294005-d306317-Reviews-Hotel_Albergo-Beirut.html','https://www.travelgay.com/gay-beirut-hotels/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1788::bigint, jsonb_build_object(
      'queue_wait', 'This Achrafieh branch is an early sweets counter, reportedly open around 6 am to 1 pm, so the only real wait comes with breakfast and knafeh runs. Service moves quickly, but popular trays can sell through. Go before noon and confirm the branch pin; the chain has many locations with different hours.',
      'best_nights', 'There is no night scene here. Make it a morning stop for warm knafeh, syrupy pastries and coffee, ideally before the late-breakfast rush. It works beautifully after an early start or the morning after dancing; arriving at evening hours risks finding this particular branch already closed.',
      'crowd_mix', 'Neighbourhood families, hospital and office workers, school-run regulars and visitors chasing a classic Lebanese sweet share the counter. Queer travellers blend into an entirely mainstream local food ritual. This is closer to everyday Achrafieh than a tourist attraction or LGBTQ+ meeting place.',
      'dress_code', 'Breakfast-casual wins: trainers, denim, work clothes or last night’s jacket over a clean tee. You may be eating a cheese-filled pastry with syrup, so choose something forgiving and keep napkins close. No social code is attached to the visit beyond an orderly counter and respect for the morning rush.',
      'staff_inclusivity', 'Current reviews focus on the distinctive knafeh rather than hospitality detail, and the business publishes no LGBTQ+ policy. Treat the welcome as ordinary retail service, not a safe-space guarantee. Its value to a queer guide is delicious local routine in a relatively easy district, not community programming.',
      'venue_classification', 'active_mainstream_achrafieh_oriental_sweets_counter_and_morning_knafeh_stop_not_dedicated_lgbtq_venue',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/2264209/labeille-dor','https://makanilebanon.com/portal/en-US/directory/group/labeille-dor/36/labeille-dor-ashrafieh/9207/','https://www.linkedin.com/company/labeille-d-or','https://nomadicboys.com/beirut-gay-travel-guide/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_early_branch_hours_fast_counter_and_popular_knafeh_evidence','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2264209/labeille-dor','https://makanilebanon.com/portal/en-US/directory/group/labeille-dor/36/labeille-dor-ashrafieh/9207/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','morning_knafeh_sweets_and_early_close_context_without_nightlife_function','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2264209/labeille-dor','https://nomadicboys.com/beirut-gay-travel-guide/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mainstream_neighbourhood_family_worker_and_food_visitor_counter_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2264209/labeille-dor','https://makanilebanon.com/portal/en-US/directory/group/labeille-dor/36/labeille-dor-ashrafieh/9207/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','casual_takeaway_breakfast_syrup_pastry_and_morning_rush_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2264209/labeille-dor','https://nomadicboys.com/beirut-gay-travel-guide/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','insufficient_current_service_detail_and_no_published_lgbtq_policy_for_mainstream_chain_branch','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2264209/labeille-dor','https://www.linkedin.com/company/labeille-d-or']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1781::bigint, jsonb_build_object(
      'queue_wait', 'There is no check-in: the hotel has been closed since 2020 and a 2024 traveller confirmed it permanently shut. Old comparison sites may still display the Corniche address, sea-view rooms or rate buttons. Do not send payment or arrive with luggage unless a new owner announces a dated reopening.',
      'best_nights', 'No active stay or rooftop evening exists under this listing. Historically, guests came for Mediterranean views, old-world interiors and the rooftop bar, but those memories cannot become a current recommendation. Choose an operating Corniche hotel and keep this record only as hospitality history.',
      'crowd_mix', 'Before closure, this was an intimate luxury hotel for international visitors, Beirut regulars, couples and business guests, with an explicitly queer-friendly welcome. There is no present crowd. Carrying old audience labels forward would mislead travellers and inflate a venue that is now inactive.',
      'dress_code', 'Not applicable while closed. The former mood leaned polished and discreet, but no outfit can solve an inactive front desk. If the building returns under new ownership, reassess its name, room inventory, ID policy, rooftop access and LGBTQ+ welcome from scratch before restoring any advice.',
      'staff_inclusivity', 'The former hotel was warmly rated and explicitly welcomed LGBTQ+ guests, but that team and management agreement ended years ago. No current staff can be scored. Preserve the positive history in archives, not as a promise attached to a closed door or a future operator.',
      'venue_classification', 'permanently_closed_former_luxury_corniche_boutique_hotel_with_historic_explicit_lgbtq_welcome',
      'record_status', 'closed_do_not_book_archive_or_remove_from_active_results',
      'source_urls', to_jsonb(array['https://www.travelgay.com/hotels/le-vendome-beirut','https://www.businessnews.com.lb/cms/Story/StoryDetails/8689/Le-Vendome-hotel-sold-to-Qatari-investors','https://www.tripadvisor.com/Hotel_Review-g294005-d299158-Reviews-Le_Vendome_Beirut-Beirut.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','direct_permanently_closed_report_and_2020_sale_without_reopening_evidence','source_urls',to_jsonb(array['https://www.travelgay.com/hotels/le-vendome-beirut','https://www.businessnews.com.lb/cms/Story/StoryDetails/8689/Le-Vendome-hotel-sold-to-Qatari-investors']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_sea_view_rooftop_profile_only_with_no_current_operation','source_urls',to_jsonb(array['https://www.travelgay.com/hotels/le-vendome-beirut','https://www.tripadvisor.com/Hotel_Review-g294005-d299158-Reviews-Le_Vendome_Beirut-Beirut.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_luxury_international_couple_business_and_queer_guest_mix_without_present_crowd','source_urls',to_jsonb(array['https://www.travelgay.com/hotels/le-vendome-beirut','https://www.tripadvisor.com/Hotel_Review-g294005-d299158-Reviews-Le_Vendome_Beirut-Beirut.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','closed_property_future_operator_requires_full_identity_and_policy_reassessment','source_urls',to_jsonb(array['https://www.businessnews.com.lb/cms/Story/StoryDetails/8689/Le-Vendome-hotel-sold-to-Qatari-investors','https://www.travelgay.com/hotels/le-vendome-beirut']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','historic_explicit_lgbtq_welcome_but_management_and_team_no_longer_current','source_urls',to_jsonb(array['https://www.travelgay.com/hotels/le-vendome-beirut','https://www.businessnews.com.lb/cms/Story/StoryDetails/8689/Le-Vendome-hotel-sold-to-Qatari-investors']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1785::bigint, jsonb_build_object(
      'queue_wait', 'Om opens in the late afternoon, so early drinks are usually gentler than the post-dinner surge. Friday and Saturday run latest and can tighten around the small dance area. Check the live event post before travelling, especially for drag: security conditions matter after the targeted 2023 attack.',
      'best_nights', 'Start around 8 or 9 pm for cocktails, food and actual conversation, then let the Arabic-pop and old-school R&B pull the room toward dancing. A drag or community fundraiser is the night with most meaning; a weekday gives the same warmth with less volume and more room to meet people.',
      'crowd_mix', 'Queer women, gay men, trans guests, drag artists, allies and Mar Mikhael regulars create one of Beirut’s genuinely mixed LGBTQ+ rooms. Locals carry the culture while visitors are welcomed into it. The crowd ranges wider than a male-only club and feels closer to a community living room after dark.',
      'dress_code', 'Come expressive but street-smart: denim, mesh, a sharp shirt, colour, makeup or a full drag-night look can all belong. Keep bags small, arrange direct transport and ask before filming anyone. Visibility is part of the joy here, but leaving discreetly can still be the wiser choice in Beirut.',
      'staff_inclusivity', 'The venue has repeatedly opened its room to drag, health outreach and broad queer community life, and its manager stood with guests after a violent anti-LGBTQ+ attack. Older reviews split between warm, affordable hospitality and rude service or weak security. Community courage is clear; every shift may not be flawless.',
      'venue_classification', 'active_mixed_lgbtq_bar_lounge_and_drag_space_in_mar_mikhael_with_strong_community_role_and_material_external_security_history',
      'source_urls', to_jsonb(array['https://nomadicboys.com/beirut-gay-travel-guide/','https://www.beirut.com/en/62712/madame-om-is-back-om-bar-room-now-open-in-mar-mikhael/','https://lebmash.org/resources-for-lgbt-individuals/','https://www.newarab.com/video/beirut-bar-attacked-targeted-assault-lgbtq-community','https://www.amnesty.org/en/latest/news/2023/08/lebanon-attack-on-lgbti-bar-another-ominous-sign-of-deteriorating-rights-situation','https://wanderlog.com/place/details/1464470']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_late_afternoon_open_weekend_late_peak_and_event_security_context','source_urls',to_jsonb(array['https://nomadicboys.com/beirut-gay-travel-guide/','https://www.beirut.com/en/62712/madame-om-is-back-om-bar-room-now-open-in-mar-mikhael/','https://www.newarab.com/video/beirut-bar-attacked-targeted-assault-lgbtq-community']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','arabic_pop_rnb_drag_community_event_and_early_conversation_pattern','source_urls',to_jsonb(array['https://nomadicboys.com/beirut-gay-travel-guide/','https://www.beirut.com/en/62712/madame-om-is-back-om-bar-room-now-open-in-mar-mikhael/','https://lebmash.org/resources-for-lgbt-individuals/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_queer_women_gay_men_trans_drag_ally_local_and_visitor_community_room','source_urls',to_jsonb(array['https://lebmash.org/resources-for-lgbt-individuals/','https://www.beirut.com/en/62712/madame-om-is-back-om-bar-room-now-open-in-mar-mikhael/','https://www.amnesty.org/en/latest/news/2023/08/lebanon-attack-on-lgbti-bar-another-ominous-sign-of-deteriorating-rights-situation']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','expressive_drag_bar_privacy_direct_transport_and_post_attack_visibility_context','source_urls',to_jsonb(array['https://www.newarab.com/video/beirut-bar-attacked-targeted-assault-lgbtq-community','https://nomadicboys.com/beirut-gay-travel-guide/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','documented_drag_health_outreach_and_manager_resilience_balanced_against_mixed_service_security_reviews','source_urls',to_jsonb(array['https://www.amnesty.org/en/latest/news/2023/08/lebanon-attack-on-lgbti-bar-another-ominous-sign-of-deteriorating-rights-situation','https://wanderlog.com/place/details/1464470','https://lebmash.org/resources-for-lgbt-individuals/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1784::bigint, jsonb_build_object(
      'queue_wait', 'Doors open around 11 pm on the active weekend programme, but the room builds later and security can be the real delay. The map pin has confused visitors, so use the current event location and direct transport. Carry original ID and expect a firmer check than at a casual queer bar.',
      'best_nights', 'Friday and Saturday deliver the core gay-club energy; Sunday’s Arabic-pop night is the campier local favourite. Expect Arabic and English mixes, performers and two to three-and-a-half hours inside before some guests continue to an afterparty. Let the dated theme choose your night.',
      'crowd_mix', 'Local gay men dominate, joined by a wider age range, queer friends, regional visitors and foreign travellers. The atmosphere is proudly Beirut rather than an imported circuit clone, especially on Arabic night. Women are present but this is still a male-centred gay club, not an evenly mixed all-genders room.',
      'dress_code', 'Go club-ready and camera-aware: fitted tees, dark denim, trainers, shine or sharp monochrome all work. Bring original ID, minimal valuables and a layer for the rooftop. The door appears to care more about control and presentation than one formal style rule, so arrive composed and know your plan home.',
      'staff_inclusivity', 'The dance floor remains a major queer gathering point, but a January 2026 visitor described entrance security as aggressive and hostile. Other guests find people inside friendly and the atmosphere inclusive. Treat that door report seriously: stay calm, keep ID ready and leave rather than argue if treatment turns rough.',
      'venue_classification', 'active_weekend_rooftop_gay_club_with_local_arabic_pop_identity_male_centred_crowd_and_serious_current_security_concern',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/9557917/posh-club-beirut','https://qlist.app/venues/Matn/Posh-Club-Beirut/dTVEbWFyamZCS1FCYm9GemVCbnpVdw','https://www.travelgay.com/beirut-gay-dance-clubs','https://nomadicboys.com/beirut-gay-travel-guide/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_eleven_pm_weekend_open_map_confusion_original_id_and_security_led_entry','source_urls',to_jsonb(array['https://qlist.app/venues/Matn/Posh-Club-Beirut/dTVEbWFyamZCS1FCYm9GemVCbnpVdw','https://wanderlog.com/place/details/9557917/posh-club-beirut','https://nomadicboys.com/beirut-gay-travel-guide/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_core_sunday_arabic_pop_and_two_to_three_half_hour_visit_pattern','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9557917/posh-club-beirut','https://nomadicboys.com/beirut-gay-travel-guide/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','predominantly_local_gay_male_wider_age_queer_friend_regional_and_foreign_visitor_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9557917/posh-club-beirut','https://qlist.app/venues/Matn/Posh-Club-Beirut/dTVEbWFyamZCS1FCYm9GemVCbnpVdw']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','rooftop_gay_club_original_id_security_presentation_and_belongings_context_without_strict_published_code','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9557917/posh-club-beirut','https://qlist.app/venues/Matn/Posh-Club-Beirut/dTVEbWFyamZCS1FCYm9GemVCbnpVdw']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','major_queer_role_balanced_against_specific_january_2026_aggressive_security_report_and_friendlier_inside_crowd','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9557917/posh-club-beirut','https://qlist.app/venues/Matn/Posh-Club-Beirut/dTVEbWFyamZCS1FCYm9GemVCbnpVdw']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1779::bigint, jsonb_build_object(
      'queue_wait', 'Reception is a smooth hotel check-in rather than a queue, with current guests praising patient, flexible staff. Holiday and event arrivals can crowd the lobby, so share your timing. A refundable deposit may be requested even on prepaid stays; confirm the amount and release method before handing over a card.',
      'best_nights', 'Stay here when Badaro’s restaurants and the National Museum fit your route. Summer brings the seasonal rooftop pool, while New Year and big hotel events create a livelier house. A weekday is calmer for spa time and work; a weekend better connects the stay to bars without placing you inside a party hotel.',
      'crowd_mix', 'Beirut staycation couples, families, business guests, regional visitors and international travellers share the bold superhero-themed tower. Queer locals and couples have long named it a comfortable option, but the atmosphere remains mixed and upscale. You will blend into hotel life rather than enter a queer scene.',
      'dress_code', 'Smart-casual carries almost everywhere: trainers, polished streetwear and a light layer work for lobby, restaurant and Badaro. Pack swimwear for the seasonal rooftop and something sharper for dinner or an event. The playful design welcomes colour; discretion in public affection remains a personal safety choice.',
      'staff_inclusivity', 'Current reviews give the team outstanding marks for patience, flexibility and a genuinely warm welcome. Local queer accounts repeatedly identify the hotel as friendly and recall visible Pride support, though that symbolism became quieter under pressure. The strongest signal is lived reputation plus consistent service.',
      'venue_classification', 'active_upscale_badaro_design_hotel_with_rooftop_pool_strong_current_service_and_longstanding_local_queer_friendly_reputation',
      'source_urls', to_jsonb(array['https://www.thesmallville.com/','https://www.booking.com/reviews/lb/hotel/the-smallville.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294005-d4700651-Reviews-The_Smallville_Hotel-Beirut.html','https://www.beirut.com/en/63654/7-queer-friendly-spots-around-beirut/','https://www.reddit.com/r/lebanon/comments/1n4u0hc/traveling_as_a_gay_couple_in_beirut/','https://www.reddit.com/r/LGBTLebanon/comments/1ule6s9/hotels_apartments_gay_friendly/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_smooth_flexible_checkin_with_holiday_event_peak_and_deposit_report','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-smallville.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294005-d4700651-Reviews-The_Smallville_Hotel-Beirut.html','https://www.agoda.com/the-smallville-hotel/hotel/beirut-lb.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','badaro_museum_seasonal_rooftop_new_year_event_spa_and_weekday_weekend_context','source_urls',to_jsonb(array['https://www.booking.com/hotel/lb/the-smallville.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g294005-d4700651-Reviews-The_Smallville_Hotel-Beirut.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_local_staycation_family_business_regional_international_and_queer_couple_guest_profile','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-smallville.en-gb.html','https://www.reddit.com/r/lebanon/comments/1n4u0hc/traveling_as_a_gay_couple_in_beirut/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','design_hotel_rooftop_pool_restaurant_badaro_and_public_discretion_context','source_urls',to_jsonb(array['https://www.thesmallville.com/','https://www.booking.com/hotel/lb/the-smallville.en-gb.html','https://www.beirut.com/en/63654/7-queer-friendly-spots-around-beirut/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_staff_consensus_and_repeated_local_queer_friendly_pride_support_reputation','source_urls',to_jsonb(array['https://www.booking.com/reviews/lb/hotel/the-smallville.en-gb.html','https://www.reddit.com/r/lebanon/comments/1n4u0hc/traveling_as_a_gay_couple_in_beirut/','https://www.reddit.com/r/LGBTLebanon/comments/1ule6s9/hotels_apartments_gay_friendly/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1778,1780,1783,1788,1781,1785,1784,1779)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
