-- Queer Atlas venue intelligence: global review-led editorial pass, batch 35.
-- Six remaining Belfast records, individually researched and rewritten.
-- Fitzwilliam has a current explicit LGBTQ-friendly partnership; other hotels are not labelled queer without evidence.
-- Maverick and Union Street remain important queer venues while current door and security criticism is retained.
-- Checked 2026-08-06. Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1587::bigint, jsonb_build_object(
      'queue_wait', 'Check-in is usually quick and easy in current stays, with valet drop-off removing much of the city-centre arrival stress. The pre-theatre restaurant is the busier clock: reserve around performance times next door. If driving, ask about valet or the current alternative car park before reaching Great Victoria Street.',
      'best_nights', 'Book around a show at the Grand Opera House: early dinner, curtain, then a final cocktail without chasing a taxi. A weekday feels calm and properly luxurious; Friday or Saturday gives more city energy. The station and queer quarter remain walkable, so it also works as a polished base for Pride or nightlife.',
      'crowd_mix', 'Theatre couples, celebration stays, business guests, families and international city breakers share this intimate five-star hotel. Queer couples are explicitly welcomed through an active specialist partnership. It is not a social gay hotel, but LGBTQ+ guests belong in its broad, upscale audience.',
      'dress_code', 'Modern smart-casual fits the room: clean trainers, tailoring, dresses, soft knitwear or a bright evening jacket all travel from breakfast to cocktails. Robes stay upstairs; theatre-night guests often sharpen the look. There is no queer presentation test, and the hotel signals welcome across identities.',
      'staff_inclusivity', 'An active LGBTQ-friendly partnership states that community members are accepted, while thousands of current verified stays give staff exceptional marks for warmth, housekeeping and attention. Couples repeatedly describe feeling comfortable; this is one of Belfast’s stronger luxury signals.',
      'venue_classification', 'active_five_star_theatre_district_hotel_with_explicit_current_lgbtq_friendly_partnership_and_exceptional_2026_service_consensus',
      'source_urls', to_jsonb(array['https://www.fitzwilliamhotelbelfast.com/','https://www.fitzwilliamhotelbelfast.com/dining.html','https://www.booking.com/reviews/gb/hotel/the-fitzwilliam-belfast.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d1200616-Reviews-The_Fitzwilliam_Hotel_Belfast-Belfast_Northern_Ireland.html','https://www.travelgay.com/hotels/fitzwilliam-hotel-belfast']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_quick_checkin_valet_arrival_and_pre_theatre_reservation_pattern','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Hotel_Review-g186470-d1200616-Reviews-The_Fitzwilliam_Hotel_Belfast-Belfast_Northern_Ireland.html','https://www.fitzwilliamhotelbelfast.com/dining.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_grand_opera_house_pre_theatre_weekday_weekend_station_and_queer_nightlife_location_context','source_urls',to_jsonb(array['https://www.fitzwilliamhotelbelfast.com/','https://www.travelgay.com/hotels/fitzwilliam-hotel-belfast']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_theatre_celebration_business_family_international_and_explicitly_welcomed_queer_couple_guest_profile','source_urls',to_jsonb(array['https://www.booking.com/reviews/gb/hotel/the-fitzwilliam-belfast.en-gb.html','https://www.travelgay.com/hotels/fitzwilliam-hotel-belfast']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','modern_five_star_restaurant_cocktail_theatre_context_and_explicit_identity_welcome_without_formal_code','source_urls',to_jsonb(array['https://www.fitzwilliamhotelbelfast.com/','https://www.travelgay.com/hotels/fitzwilliam-hotel-belfast']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','explicit_current_lgbtq_friendly_partnership_and_exceptional_2026_verified_staff_housekeeping_and_couple_comfort_consensus','source_urls',to_jsonb(array['https://www.travelgay.com/hotels/fitzwilliam-hotel-belfast','https://www.booking.com/reviews/gb/hotel/the-fitzwilliam-belfast.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d1200616-Reviews-The_Fitzwilliam_Hotel_Belfast-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1582::bigint, jsonb_build_object(
      'queue_wait', 'Check-in and checkout are repeatedly described as fast, and the small reception keeps arrival simpler than a full-service hotel. Share your time if arriving late. The central address can be busy, but there is no restaurant queue downstairs; every studio has a kitchenette and the property leaves dining to the city.',
      'best_nights', 'Stay here when you want independence: cook breakfast, use the free laundry and walk out for bars or a concert. A weekday maximises value and quiet; on Friday or Saturday request a higher or calmer room because nearby nightlife can travel. It is a base for your Belfast night, not a night inside the hotel.',
      'crowd_mix', 'Independent couples, solo travellers, longer-stay guests and visitors who prefer an apartment feel over hotel ritual dominate. The central location brings many international guests. No current queer programme or formal LGBTQ+ welcome was found, so the audience should be described as broadly mixed rather than scene-led.',
      'dress_code', 'Pack like the room is your compact city flat: comfortable walking shoes, easy layers and something for the night you have actually booked. Kitchen and free laundry make light packing realistic. There is no lobby theatre or dress rule, and nobody expects you to perform luxury on the way past reception.',
      'staff_inclusivity', 'Most current stays praise friendly, practical staff who solve requests and recommend nearby food; verified scores remain strong. A minority report limited staff presence or a cleanliness miss. There is no explicit LGBTQ+ policy, but the low-fuss, self-contained model gives couples privacy and little social friction.',
      'venue_classification', 'active_central_apartment_style_studio_hotel_with_kitchenettes_free_laundry_strong_staff_consensus_and_no_verified_queer_specific_identity',
      'source_urls', to_jsonb(array['https://www.theflintbelfast.com/','https://www.theflintbelfast.com/rooms','https://www.booking.com/hotel/gb/the-flint.html','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d14194476-Reviews-The_Flint-Belfast_Northern_Ireland.html','https://uk.hotels.com/ho720141952/the-flint-belfast-united-kingdom/','https://www.agoda.com/the-flint/hotel/belfast-gb.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_fast_small_reception_arrival_and_self_catering_no_restaurant_context','source_urls',to_jsonb(array['https://www.theflintbelfast.com/','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d14194476-Reviews-The_Flint-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_kitchenette_free_laundry_central_nightlife_and_weekend_noise_pattern','source_urls',to_jsonb(array['https://www.theflintbelfast.com/rooms','https://uk.hotels.com/ho720141952/the-flint-belfast-united-kingdom/','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d14194476-Reviews-The_Flint-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_independent_couple_solo_long_stay_and_international_apartment_style_guest_profile_without_queer_programme','source_urls',to_jsonb(array['https://www.booking.com/hotel/gb/the-flint.html','https://www.theflintbelfast.com/rooms']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','self_catering_laundry_walkable_city_base_context_without_formal_public_room_code','source_urls',to_jsonb(array['https://www.theflintbelfast.com/','https://www.theflintbelfast.com/rooms']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_practical_friendly_staff_consensus_with_minor_presence_cleanliness_variation_and_no_lgbtq_policy','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Hotel_Review-g186470-d14194476-Reviews-The_Flint-Belfast_Northern_Ireland.html','https://www.agoda.com/the-flint/hotel/belfast-gb.html','https://uk.hotels.com/ho720141952/the-flint-belfast-united-kingdom/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1580::bigint, jsonb_build_object(
      'queue_wait', 'Entry is currently advertised as free, and the bar opens from 5 pm, so early drinks rarely need a line. Pride, weekend drag and karaoke can pack the small room; arriving before the headline act protects a view. Door decisions remain discretionary, with some 2025–26 guests reporting abrupt refusals or removals.',
      'best_nights', 'Wednesday pairs live vocals with karaoke; the newer drag-lab format gives emerging performers room to experiment. Weekends are louder and fuller, while an early weekday pint makes conversation possible around the pool table. Pick the named host you enjoy: the bar programmes free entertainment seven nights a week.',
      'crowd_mix', 'Gay men, queer women, trans and non-binary regulars, drag fans, allies and visitors share a compact bar that currently skews more mixed—and some nights more female—than an old-school men-only pub. Locals keep it sociable, tourists are common, and the room stays recognisably queer despite straight crossover.',
      'dress_code', 'Casual queer bar rules: denim, trainers, drag, a football-night tee or full karaoke sparkle can all work. There is no cover or published formal code. Arrive steady and respectful, because security makes intoxication calls firmly; an expressive outfit does not protect anyone from a disputed door decision.',
      'staff_inclusivity', 'Recent queer visitors praise bartenders who arrange taxis, friendly regulars, strong drinks and security that can make the room feel safe. Other guests report humiliating refusals or removal despite feeling sober. The bar remains an important queer home, but the current welcome is not uniformly experienced at the door.',
      'venue_classification', 'active_free_entry_seven_night_queer_bar_with_drag_karaoke_pool_table_mixed_lgbtq_crowd_and_material_door_consistency_concerns',
      'source_urls', to_jsonb(array['https://www.tripadvisor.co.uk/Attraction_Review-g186470-d8860758-Reviews-The_Maverick_Belfast-Belfast_Northern_Ireland.html','https://www.travelgay.com/venue/maverick-bar','https://www.corner.inc/place/pLFcEh5HN3Ae','https://www.findglocal.com/GB/Belfast/537771372963649/The-Maverick','https://wanderlog.com/place/details/2231419/the-maverick','https://www.reddit.com/r/northernireland/comments/1usquos/meeting_gay_people_in_northern_ireland/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_free_entry_five_pm_open_small_room_pride_performance_peak_and_discretionary_door_pattern','source_urls',to_jsonb(array['https://www.corner.inc/place/pLFcEh5HN3Ae','https://www.findglocal.com/GB/Belfast/537771372963649/The-Maverick','https://www.tripadvisor.co.uk/Attraction_Review-g186470-d8860758-Reviews-The_Maverick_Belfast-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_wednesday_karaoke_new_drag_lab_weekend_peak_pool_table_and_daily_free_entertainment','source_urls',to_jsonb(array['https://www.findglocal.com/GB/Belfast/537771372963649/The-Maverick','https://www.corner.inc/place/pLFcEh5HN3Ae','https://www.reddit.com/r/northernireland/comments/1usquos/meeting_gay_people_in_northern_ireland/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_mixed_gay_men_queer_women_trans_nonbinary_drag_fan_ally_local_and_visitor_crowd','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2231419/the-maverick','https://www.corner.inc/place/pLFcEh5HN3Ae','https://www.tripadvisor.co.uk/Attraction_Review-g186470-d8860758-Reviews-The_Maverick_Belfast-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_expressive_queer_bar_without_formal_code_but_firm_intoxication_discretion','source_urls',to_jsonb(array['https://www.corner.inc/place/pLFcEh5HN3Ae','https://www.tripadvisor.co.uk/Attraction_Review-g186470-d8860758-Reviews-The_Maverick_Belfast-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','polarised_current_taxi_help_safe_room_and_friendly_regular_praise_balanced_against_repeated_abrupt_refusal_and_removal_reports','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Attraction_Review-g186470-d8860758-Reviews-The_Maverick_Belfast-Belfast_Northern_Ireland.html','https://www.corner.inc/place/pLFcEh5HN3Ae']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1588::bigint, jsonb_build_object(
      'queue_wait', 'Hotel arrival is concierge-led, with current guests praising luggage help and a polished welcome rather than a queue. The Great Room, cocktail bar, jazz room and spa are destinations in their own right, so reserve the experience you care about. Weekend afternoon tea and live-jazz tables are the likeliest pinch points.',
      'best_nights', 'Friday or Saturday suits a dressed-up dinner followed by live jazz or serious cocktails; a weekday gives the spa and grand banking-hall interiors more breathing room. Stay here for an anniversary or indulgent queer city break, not to be close to a hotel party. The actual gay bars are a short walk away.',
      'crowd_mix', 'Affluent couples, anniversary guests, international luxury travellers, business visitors and Belfast residents celebrating over dinner or drinks fill the building. Queer couples blend into a polished mainstream audience in a queer-friendly quarter. No current LGBTQ+ programme or formal hotel commitment was found.',
      'dress_code', 'This is the place for velvet, tailoring, jewellery, a fluid evening look or the sharp coat waiting for an occasion. Smart-casual remains enough for daytime and spa access, but dinner and cocktails invite theatre. Nobody publishes a gendered rule; elegant self-expression works better than stiff conformity.',
      'staff_inclusivity', 'Verified 2026 stays give staff outstanding scores for friendly, attentive service, especially concierge and doormen. The Cathedral Quarter is broadly queer-friendly, but no explicit hotel LGBTQ+ policy was found. Trust the strong service record without making a claim the hotel has not made.',
      'venue_classification', 'active_landmark_five_star_cathedral_quarter_hotel_with_destination_dining_jazz_cocktails_spa_and_strong_service_but_no_formal_queer_identity',
      'source_urls', to_jsonb(array['https://www.themerchanthotel.com/','https://www.themerchanthotel.com/uploads/docs/TMH_Reception_Restaurants_WEB_APR22_V3.pdf','https://www.themerchanthotel.com/uploads/docs/Cocktail-Bar-Menu-Oct-23-v2.pdf','https://www.booking.com/reviews/gb/hotel/the-merchant.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d598106-Reviews-The_Merchant_Hotel-Belfast_Northern_Ireland.html','https://www.reddit.com/r/Belfast/comments/13hgvpl/nice_hotels_in_belfast/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_concierge_arrival_and_advance_reservation_context_for_destination_dining_cocktails_jazz_spa_and_afternoon_tea','source_urls',to_jsonb(array['https://www.booking.com/reviews/gb/hotel/the-merchant.en-gb.html','https://www.themerchanthotel.com/uploads/docs/TMH_Reception_Restaurants_WEB_APR22_V3.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_weekend_dinner_jazz_cocktail_and_weekday_spa_context_with_walkable_queer_quarter','source_urls',to_jsonb(array['https://www.themerchanthotel.com/uploads/docs/TMH_Reception_Restaurants_WEB_APR22_V3.pdf','https://www.booking.com/reviews/gb/hotel/the-merchant.en-gb.html','https://www.reddit.com/r/Belfast/comments/13hgvpl/nice_hotels_in_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_affluent_couple_anniversary_international_business_and_local_celebration_mix_without_lgbtq_programme','source_urls',to_jsonb(array['https://www.booking.com/reviews/gb/hotel/the-merchant.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d598106-Reviews-The_Merchant_Hotel-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','grand_hotel_restaurant_cocktail_jazz_and_spa_context_without_published_gendered_code','source_urls',to_jsonb(array['https://www.themerchanthotel.com/uploads/docs/TMH_Reception_Restaurants_WEB_APR22_V3.pdf','https://www.themerchanthotel.com/uploads/docs/Cocktail-Bar-Menu-Oct-23-v2.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','exceptional_current_concierge_doorman_and_service_consensus_with_queer_friendly_district_but_no_explicit_hotel_policy','source_urls',to_jsonb(array['https://www.booking.com/reviews/gb/hotel/the-merchant.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g186470-d598106-Reviews-The_Merchant_Hotel-Belfast_Northern_Ireland.html','https://www.reddit.com/r/Belfast/comments/13hgvpl/nice_hotels_in_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1581::bigint, jsonb_build_object(
      'queue_wait', 'The bar is tiny, so Friday after-work crowds can make the ground floor feel full before there is a formal line. Upstairs may have space, but one bartender can mean a slow round. Arrive early for a seat. Current visitors also report a 21+ door interpretation and repeat ID checks, so carry original photo ID.',
      'best_nights', 'Go early on Thursday or Friday for rum cocktails, rock-and-roll energy and the room at its warmest; stay later only if you enjoy a crush. A quiet weekday lets the eccentric religious-and-tattoo décor breathe. This is a characterful first drink before queer venues nearby, not a dedicated LGBTQ+ programme.',
      'crowd_mix', 'Cathedral Quarter regulars, bartenders on days off, cocktail hunters, couples and visitors squeeze together in a famously compact room. Locals describe the crowd as broadly LGBTQ-friendly, but it remains a mainstream bar. Expect more neighbourhood crossover and tourists than an organised queer community night.',
      'dress_code', 'Rock-bar casual wins: black denim, boots, trainers, band tees, vintage pieces or something sharply camp all sit naturally under the irreverent décor. No formal fashion rule is published, but age checks appear stricter than the look. Bring ID even if you are well over 18 and keep bags small.',
      'staff_inclusivity', 'Many recent guests praise friendly bartenders, music requests and a good-natured crowd; locals often recommend the room as LGBTQ-friendly. Others describe double ID checks, an apparent 21+ policy or poor cocktails on strained shifts. The social signal is positive, but the age-door policy needs clearer publication.',
      'venue_classification', 'active_tiny_cathedral_quarter_rum_and_cocktail_bar_with_queer_friendly_mixed_crowd_and_unclear_current_twenty_one_plus_door_policy',
      'source_urls', to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d886988-Reviews-The_Spaniard-Belfast_Northern_Ireland.html','https://www.belfastbar.co.uk/the-spaniard-review.htm','https://www.reddit.com/r/Belfast/comments/1qp9otn/gay_bars_in_belfast/','https://www.reddit.com/r/northernireland/comments/126wb0g/good_cocktail_bar_belfast/','https://www.reddit.com/r/northernireland/comments/1p2u8hn/belfast_bar_set_to_extend_opening_hours_to_3am_in/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_tiny_friday_peak_slow_round_upstairs_space_and_reported_twenty_one_plus_repeat_id_pattern','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d886988-Reviews-The_Spaniard-Belfast_Northern_Ireland.html','https://www.reddit.com/r/northernireland/comments/126wb0g/good_cocktail_bar_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','early_thursday_friday_rum_cocktail_rock_energy_and_quieter_weekday_context','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d886988-Reviews-The_Spaniard-Belfast_Northern_Ireland.html','https://www.belfastbar.co.uk/the-spaniard-review.htm']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_local_regular_hospitality_cocktail_couple_and_visitor_crowd_with_local_lgbtq_friendly_signal','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d886988-Reviews-The_Spaniard-Belfast_Northern_Ireland.html','https://www.reddit.com/r/Belfast/comments/1qp9otn/gay_bars_in_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_rock_bar_small_room_and_strict_age_id_context_without_published_fashion_code','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d886988-Reviews-The_Spaniard-Belfast_Northern_Ireland.html','https://www.belfastbar.co.uk/the-spaniard-review.htm']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','mostly_friendly_bartender_music_and_queer_friendly_local_consensus_balanced_against_id_policy_and_cocktail_service_complaints','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d886988-Reviews-The_Spaniard-Belfast_Northern_Ireland.html','https://www.reddit.com/r/Belfast/comments/1qp9otn/gay_bars_in_belfast/','https://www.reddit.com/r/northernireland/comments/126wb0g/good_cocktail_bar_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1585::bigint, jsonb_build_object(
      'queue_wait', 'Daytime brunch and early drinks are the easy entry; ticketed drag, Pride fundraisers and the upstairs club can create a door line. Book headline events, carry ID and arrive before showtime. Reviews praise the refurbished room, while older and recent guests flag security as the least predictable part.',
      'best_nights', 'Sunday drag bingo is the signature, Saturday adds brunch, a DJ and afternoon karaoke, and the weekly calendar layers quizzes, live music and club nights around them. Pride week turns the whole block into an all-day party. For conversation, choose Tuesday or Wednesday before entertainment takes over.',
      'crowd_mix', 'Gay men, queer women, trans guests, drag audiences, older regulars, students, tourists, allies and hen groups use this large bar. The core is still LGBTQ+, but it is not an exclusive bubble. Some locals find the scene diluted; the strongest queer concentration follows a named show or fundraiser.',
      'dress_code', 'Brunch can be casual; bingo welcomes camp; the upstairs dance floor rewards clubwear and shoes you can stand in. No single dress rule covers the whole building. Current reviews say alternative looks can feel welcome, yet door discretion remains real, so bring ID, arrive composed and keep a second plan nearby.',
      'staff_inclusivity', 'The 2026 refurbishment brought strong praise for attentive table service, warmth and a revived atmosphere. The venue also hosts a major LGBTQ+ charity fundraiser. Balance that with recurring reports of hostile security and older trans-specific warnings. Inside culture looks improved; the door still needs work.',
      'venue_classification', 'active_large_refurbished_lgbtq_bar_cabaret_and_club_complex_with_daily_programming_broad_mixed_crowd_and_persistent_security_consistency_concern',
      'source_urls', to_jsonb(array['https://www.theunion.bar/whatson','https://visitbelfast.com/listing/union-street-bar-%26-restaurant/97622101/','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d5316180-Reviews-Union_Street_Bar-Belfast_Northern_Ireland.html','https://wanderlog.com/place/details/1482264/union-street-bar','https://www.yelp.co.uk/biz/the-union-street-bar-belfast','https://drags2riches.show/','https://www.reddit.com/r/Belfast/comments/118fggf/what_nightclubs_are_safest_for_a_transwoman_in/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_easy_daytime_ticketed_show_pride_and_upstairs_club_peak_with_persistent_security_variation','source_urls',to_jsonb(array['https://www.theunion.bar/whatson','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d5316180-Reviews-Union_Street_Bar-Belfast_Northern_Ireland.html','https://wanderlog.com/place/details/1482264/union-street-bar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_sunday_drag_bingo_saturday_brunch_dj_karaoke_weekly_entertainment_and_pride_fundraiser_calendar','source_urls',to_jsonb(array['https://www.theunion.bar/whatson','https://visitbelfast.com/listing/union-street-bar-%26-restaurant/97622101/','https://drags2riches.show/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','broad_gay_queer_women_trans_drag_older_student_tourist_ally_and_hen_group_mix_with_event_led_queer_concentration','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1482264/union-street-bar','https://www.yelp.co.uk/biz/the-union-street-bar-belfast','https://www.reddit.com/r/Belfast/comments/1qp9otn/gay_bars_in_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','multi_space_brunch_cabaret_and_club_context_with_alternative_look_welcome_but_real_door_discretion','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1482264/union-street-bar','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d5316180-Reviews-Union_Street_Bar-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_post_refurbishment_service_and_lgbtq_charity_evidence_balanced_against_recurring_hostile_security_and_trans_specific_warnings','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d5316180-Reviews-Union_Street_Bar-Belfast_Northern_Ireland.html','https://www.theunion.bar/whatson','https://www.reddit.com/r/Belfast/comments/118fggf/what_nightclubs_are_safest_for_a_transwoman_in/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1587,1582,1580,1588,1581,1585)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 6 then raise exception 'Expected 6 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
