-- Queer Atlas venue intelligence: global review-led editorial pass, batch 49.
-- One Bucharest and seven Budapest records checked against current pages and reviews on 2026-08-07.

begin;

with reviewed(id, patch) as (
  values
    (751::bigint, jsonb_build_object(
      'queue_wait','The small bar rarely has a formal line. Quiet weeknights and early hours can mean immediate seating; Friday and Saturday build later, with the pavement tables and dark room filling before it feels like a club. Recent listings conflict on branding, so confirm the current name and operator before travelling.',
      'best_nights','Late Friday and Saturday bring the strongest regular-and-visitor mix, while a weekday drink is better for conversation with whoever is behind the bar. The attraction is human contact, not production: good music, affordable drinks and introductions. Do not expect a scheduled drag show or a packed dance floor.',
      'crowd_mix','The established pattern is gay men, loyal Bucharest regulars and international visitors, with English widely workable. Some nights are very quiet. Recent feedback disputes whether the original gay-bar identity still applies, so treat it as a small bar requiring confirmation, not a guaranteed queer anchor.',
      'dress_code','There was never a fashion door: casual shirts, jeans, trainers and a post-theatre drink fit the low-lit room. Dress for outdoor tables and the walk from the centre. Because branding appears to have shifted, clothing matters less than checking that the current operation matches your expectations.',
      'staff_inclusivity','Many guests recall warm introductions, kind English-speaking service and an owner who made solo visitors feel at home. A recent detailed complaint says the bar was rebranded and alleges hostile remarks about lesbians. That conflict means the old safe-space reputation needs qualification.',
      'venue_classification','active_or_rebranded_small_bucharest_bar_at_valter_maracineanu_with_historic_gay_male_regular_and_visitor_identity_strong_old_host_praise_but_material_recent_operator_identity_and_inclusivity_conflict',
      'identity_note','Current maps place Thor''s Hammer at Piata Valter Maracineanu 4, while older directories still cite Strada Blanari 12. A recent review alleges rebranding and changed community character; verify current operator identity before promoting it as a dedicated gay bar.',
      'source_urls',to_jsonb(array['https://wanderlog.com/place/details/4726152','https://www.gayplaces.co/city/bucharest/bar/thors-hammer','https://restaurantguru.com/Thors-Hammer-Gay-Bar-Bucharest-Bucharest','https://www.tripadvisor.com/Attraction_Review-g294458-d13325904-Reviews-Thor_s_Hammer_Gay_Bar-Bucharest.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','small_walkin_bar_with_weekend_late_build_and_current_brand_confirmation_needed','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4726152','https://www.gayplaces.co/city/bucharest/bar/thors-hammer','https://restaurantguru.com/Thors-Hammer-Gay-Bar-Bucharest-Bucharest']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','late_weekend_regular_visitor_mix_and_weekday_host_conversation_without_reliable_show_floor','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4726152','https://www.gayplaces.co/city/bucharest/bar/thors-hammer']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','historic_gay_male_local_regular_international_mix_with_quiet_night_and_current_identity_uncertainty','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4726152','https://restaurantguru.com/Thors-Hammer-Gay-Bar-Bucharest-Bucharest']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','historic_no_fashion_door_casual_low_lit_bar_and_current_operation_check','source_urls',to_jsonb(array['https://www.gayplaces.co/city/bucharest/bar/thors-hammer','https://wanderlog.com/place/details/4726152']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','strong_historic_warm_english_host_consensus_materially_conflicted_by_recent_rebrand_and_lesbian_hostility_allegation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4726152','https://restaurantguru.com/Thors-Hammer-Gay-Bar-Bucharest-Bucharest']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (457::bigint, jsonb_build_object(
      'queue_wait','Friday and Saturday open at 22:00 but the basement usually comes alive after midnight. Arriving around the drag show can create a modest line; major weekends get crowded without a Berlin-length wait. Go earlier for an easier coat check and clear stage view, and read every card-terminal amount before paying.',
      'best_nights','Saturday is the fullest flagship night; Friday can be equally fun with a little more breathing room. The midnight drag show is the signature, followed by pop, retro and Hungarian favourites across the dance floor. This is not a techno pilgrimage: come for camp performance, singalong recognition and social dancing.',
      'crowd_mix','Budapest gay men anchor the room, joined by lesbians, mixed queer groups, women friends and international visitors across a broad age range. English-speaking guests report easy social contact. Weekends skew younger around the floor, while the show gathers generations; tourists are visible but locals set the tone.',
      'dress_code','Smart-casual clubwear, jeans and trainers are normal; expressive looks and drag are welcome. Avoid beach shorts and arrive looking like you chose a nightclub rather than stumbled in. The real practical code is a light layer for the basement, a small bag and attention to any event-specific note at the door.',
      'staff_inclusivity','Many guests praise quick bartenders, clean facilities, a secure smoking area and a welcoming mixed-age crowd. Recent reviews also allege gruff security, pushing and confusing bar charges. The drag-led queer identity is clear; service consistency at the entrance and terminal is the recurring weakness.',
      'venue_classification','active_budapest_weekend_gay_basement_club_at_dessewffy_33_with_midnight_drag_pop_retro_hungarian_music_broad_local_visitor_age_mix_and_mixed_security_payment_consensus',
      'identity_note','AlterEgo is active at Dessewffy utca 33, Budapest, Friday and Saturday nights. Current evidence supports a weekend club with a midnight drag signature, not the stored Sunday schedule.',
      'source_urls',to_jsonb(array['https://www.facebook.com/AlterEgoBudapest/','https://wanderlog.com/place/details/2609183/alterego','https://www.tripadvisor.com/Attraction_Review-g274887-d6748608-Reviews-Alter_Ego_Club-Budapest_Central_Hungary.html','https://www.travelgay.com/venue/alterego','https://budapest.gaycities.com/bars/301121-alterego']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','weekend_2200_open_post_midnight_build_drag_show_line_early_coat_stage_and_terminal_check','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2609183/alterego','https://www.tripadvisor.com/Attraction_Review-g274887-d6748608-Reviews-Alter_Ego_Club-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','saturday_flagship_friday_space_midnight_drag_pop_retro_hungarian_music_not_techno','source_urls',to_jsonb(array['https://www.travelgay.com/venue/alterego','https://budapest.gaycities.com/bars/301121-alterego','https://www.reddit.com/r/budapest/comments/190b6xm/gay_bars_on_sunday_and_mondays/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','gay_male_core_lesbian_mixed_queer_women_friend_international_broad_age_local_led_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2609183/alterego','https://www.tripadvisor.com/Attraction_Review-g274887-d6748608-Reviews-Alter_Ego_Club-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','smart_casual_jeans_trainers_expressive_drag_with_beach_short_and_basement_practicality','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2609183/alterego','https://www.travelgay.com/venue/alterego']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','bartender_facility_smoking_area_and_welcome_praise_balanced_against_security_and_charge_complaints','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2609183/alterego','https://www.tripadvisor.com/Attraction_Review-g274887-d6748608-Reviews-Alter_Ego_Club-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (492::bigint, jsonb_build_object(
      'queue_wait','This tiny Thursday-to-Saturday room is more likely to run out of chairs than build a formal queue. Arrive near opening for a table and sightline; drag nights compress everyone quickly. There is no cloakroom, so winter coats become furniture. Check the payment amount before approving, especially as a visitor.',
      'best_nights','Go when a named local queen or small live act is advertised. The Hungarian-language drag is intimate, funny and communal even when you miss a joke. Earlier hours suit drinks and conversation; the show gives the short evening its peak. It closes around midnight rather than becoming an all-night club.',
      'crowd_mix','A local LGBTQ+ crowd, gay men, mixed queer friends and a small number of curious visitors share the compact room. Hungarian dominates, but reviewers say language need not block the fun. It feels more neighbourhood and performance-led than tourist circuit, which is precisely its charm.',
      'dress_code','There is no formal code: casual, colourful and drag-ready looks all fit. Think small cafe-bar, not glossy superclub. The practical rule is to travel light because there is no coat check and little spare floor. A warm layer you can fold beats a statement coat with nowhere to live.',
      'staff_inclusivity','Guests often describe an authentic welcome, friendly service and affordable drinks. A recent solo visitor reported a severe card overcharge and no follow-up, so verify the terminal before paying. The room''s queer warmth is genuine in many accounts, but financial trust needs equal care.',
      'venue_classification','active_small_budapest_lgbtq_cafe_bar_at_rokk_szilard_14_with_thursday_saturday_short_hours_hungarian_drag_local_crowd_no_cloakroom_warm_consensus_and_payment_caution',
      'identity_note','Freedom Club is active at Rokk Szilard utca 14, Budapest, formerly Rainbow – The Coffee & The Club. It is unrelated to the city''s fetish venue Ministry of Freedom.',
      'source_urls',to_jsonb(array['https://www.facebook.com/Rainbow.TheCoffee.TheClub','https://wanderlog.com/place/details/4735214/freedom-club','https://www.patroc.com/gay/budapest/d/rainbow-the-coffee-the-club.html','https://www.logaytor.at/en/venues/budapest-1/bars/freedom-club/','https://www.szorakozasturul.eu/profile-163536-freedom-club']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','tiny_room_table_and_show_capacity_no_cloakroom_early_arrival_and_payment_terminal_check','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4735214/freedom-club','https://www.logaytor.at/en/venues/budapest-1/bars/freedom-club/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','named_hungarian_drag_live_act_intimate_show_peak_and_midnight_close','source_urls',to_jsonb(array['https://www.patroc.com/gay/budapest/d/rainbow-the-coffee-the-club.html','https://wanderlog.com/place/details/4735214/freedom-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','local_lgbtq_gay_male_mixed_queer_friend_and_small_visitor_performance_led_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4735214/freedom-club','https://www.logaytor.at/en/venues/budapest-1/bars/freedom-club/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_formal_code_casual_colour_drag_and_no_cloakroom_small_space_practicality','source_urls',to_jsonb(array['https://www.logaytor.at/en/venues/budapest-1/bars/freedom-club/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','strong_authentic_friendly_affordable_consensus_balanced_against_recent_unresolved_card_overcharge','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4735214/freedom-club','https://www.szorakozasturul.eu/profile-163536-freedom-club']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (494::bigint, jsonb_build_object(
      'queue_wait','The Danube-facing cafe-bar is normally an easy walk-in, though terrace tables become the prize at sunset and weekend brunch. Reserve if river views matter to a group; otherwise the friendly room usually finds a place. This is food-and-cocktails hospitality, not a cover-charge door.',
      'best_nights','Come before sunset for the river, then let dinner turn into cocktails. Friday and Saturday stretch later; weekend brunch feels most neighbourhood-like. Taco specials, screenings or a community date add energy, but the real strength is an unhurried day-to-evening handover rather than club escalation.',
      'crowd_mix','Queer locals, international residents, travellers, straight friends, couples, families and dogs make an unusually easy mix. The American-Hungarian personality and river location bring visitors, but Ujlipotvaros neighbours keep it from feeling like a tourist theme bar. It is openly gay-friendly, not men-only.',
      'dress_code','Terrace casual works from brunch to cocktails: denim, summer dresses, trainers and expressive looks all belong. There is no door test. Dress for river wind and bring the dog if your plan allows; the room''s style is cheerful and personal rather than polished Budapest nightlife theatre.',
      'staff_inclusivity','Owner and team warmth dominate reviews: guests remember personal greetings, multinational conversation, queer and pet friendliness and staff who turn a quick pre-boat drink into a reason to return. The hospitality feels hosted rather than transactional, with no repeated exclusion concern in the reviewed material.',
      'venue_classification','active_gay_friendly_budapest_danube_side_american_hungarian_cafe_restaurant_cocktail_bar_with_terrace_brunch_food_local_international_family_friend_and_pet_mix_and_exceptional_host_consensus',
      'identity_note','Gaby''s is active at Katona Jozsef utca 41, Budapest, beside the Danube in Ujlipotvaros. It is a gay-friendly all-day restaurant-bar, not a late-night gay club.',
      'source_urls',to_jsonb(array['https://gabys.hu/','https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d23346161-Reviews-Gaby_s-Budapest_Central_Hungary.html','https://www.reddit.com/r/budapest/comments/138fti5/gay_club_in_budapest/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','easy_walkin_with_sunset_terrace_and_weekend_brunch_table_pressure','source_urls',to_jsonb(array['https://gabys.hu/','https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d23346161-Reviews-Gaby_s-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','sunset_dinner_cocktail_weekend_brunch_special_and_screening_day_to_evening_value','source_urls',to_jsonb(array['https://gabys.hu/','https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d23346161-Reviews-Gaby_s-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','queer_local_international_resident_traveller_ally_couple_family_and_pet_mix','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d23346161-Reviews-Gaby_s-Budapest_Central_Hungary.html','https://www.reddit.com/r/budapest/comments/138fti5/gay_club_in_budapest/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_door_test_terrace_brunch_to_cocktail_casual_and_river_weather_practicality','source_urls',to_jsonb(array['https://gabys.hu/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','exceptionally_personal_multinational_queer_pet_friendly_owner_and_team_consensus','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d23346161-Reviews-Gaby_s-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (493::bigint, jsonb_build_object(
      'queue_wait','The discreet doorway opens into a genuinely small two-level bar. Early evening is simple; karaoke, piano and drag dates can take every seat without creating a club-style line. Arrive before the programme for the upstairs nook. The current address is near Astoria, not older listings that still point elsewhere.',
      'best_nights','Karaoke and piano evenings turn the room into one shared table; drag adds a livelier peak. On an ordinary night, come after sightseeing for cheap generous pours and conversation rather than dancing. It is one of the useful gay options before midnight, and often works better solo than a large club group.',
      'crowd_mix','Gay local regulars form the heart, with couples, solo travellers, straight friends and return visitors folded in easily. The crowd spans ages and leans conversational. Tourists are visible but do not overwhelm the Hungarian neighbourhood rhythm; the tiny room makes introductions feel natural rather than staged.',
      'dress_code','There is no code and no reason to perform one. Day clothes, jeans, a date shirt or sparkle for karaoke all fit the quirky furniture. Travel light for the narrow levels and stairs. This is a pub-scale social room where warmth and willingness to join in count more than nightlife polish.',
      'staff_inclusivity','Recent reviews are unusually affectionate about the owner, bartenders and patrons welcoming solo guests, gay couples and straight visitors alike. Cheap prices, free restroom access and generous pours reinforce the ease. One older disturbing screen-content report exists, but it is not the dominant current pattern.',
      'venue_classification','active_long_running_small_budapest_gay_bar_near_astoria_with_two_levels_karaoke_piano_drag_cheap_generous_drinks_local_regular_core_solo_traveller_strength_and_warm_owner_patron_consensus',
      'identity_note','Habrolo has operated since 2006 and moved in 2021. Current official information places it near Astoria; third-party pages conflict between Sip utca 5 and Szep utca 1, so the operator page should control navigation.',
      'source_urls',to_jsonb(array['https://www.habrolo.hu/?lang=en&page_id=460','https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d10193969-Reviews-Habrolo_Bisztro-Budapest_Central_Hungary.html','https://www.travelgay.com/venue/habrolo','https://www.reddit.com/r/budapest/comments/190b6xm/gay_bars_on_sunday_and_mondays/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','small_two_level_bar_programme_seat_capacity_early_arrival_and_current_address_conflict','source_urls',to_jsonb(array['https://www.habrolo.hu/?lang=en&page_id=460','https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d10193969-Reviews-Habrolo_Bisztro-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','karaoke_piano_drag_shared_room_and_ordinary_early_social_solo_value','source_urls',to_jsonb(array['https://www.habrolo.hu/?lang=en&page_id=460','https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d10193969-Reviews-Habrolo_Bisztro-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','gay_local_regular_couple_solo_traveller_straight_friend_return_visitor_broad_age_mix','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d10193969-Reviews-Habrolo_Bisztro-Budapest_Central_Hungary.html','https://www.travelgay.com/venue/habrolo']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_code_day_clothes_date_sparkle_and_narrow_stair_practicality','source_urls',to_jsonb(array['https://www.habrolo.hu/?lang=en&page_id=460']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','strong_current_owner_bartender_patron_welcome_generous_value_consensus_with_one_older_screen_content_concern','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g274887-d10193969-Reviews-Habrolo_Bisztro-Budapest_Central_Hungary.html','https://www.travelgay.com/venue/habrolo']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (459::bigint, jsonb_build_object(
      'queue_wait','Weekday admission is usually quick, but Friday evening and weekend special periods can produce a real line outside; one recent guest saw it long around 22:00. The large complex absorbs people after lockers. Read the day''s gender and event rules, bring identification and keep the locker key secure.',
      'best_nights','Friday evening is the strongest bet for a broad, busy gay crowd; weekend late hours build the most action. A calmer weekday is better for learning the 550-square-metre layout, sauna, steam, whirlpool and cabins. Monday programming may be mixed, so check the calendar if a men-only environment matters.',
      'crowd_mix','Local gay and bisexual men mix with international visitors from roughly 18 to 55-plus; busy times bring more social groups and younger guests. Some advertised days broaden admission beyond men. Reviews show real local use rather than a tourist-only sauna, though occasional nationality friction is reported.',
      'dress_code','Reception takes street clothes; inside, towel, sandals and clean sauna etiquette replace fashion. Bring personal toiletries if you are particular, watch your towel and respect a clear no. Cabins and dark areas invite cruising, never entitlement. Event-day admission rules matter more than what you wore outside.',
      'staff_inclusivity','Recent praise highlights helpful English-speaking reception, professional massage, cleanliness and orderly guests. Negative reports allege uneven showers, odour, tourist pricing confusion and occasional cold treatment. Confirm every charge, ask for rules in writing and report consent issues immediately.',
      'venue_classification','active_large_long_running_budapest_adult_sauna_at_csepreghy_2_with_sauna_steam_whirlpool_cabins_dark_areas_weekend_peaks_local_international_broad_age_mix_and_mixed_price_facility_consensus',
      'identity_note','Magnum Sauna is active at Csepreghy utca 2, Budapest. Current branding uses gaysaunabudapest.com; schedules include long weekend hours and may include mixed admission on specific days.',
      'source_urls',to_jsonb(array['https://gaysaunabudapest.com/','https://wanderlog.com/place/details/4210371/magnum-sauna','https://www.tripadvisor.com/Attraction_Review-g274887-d28126113-Reviews-Magnum_Sauna-Budapest_Central_Hungary.html','https://www.top-rated.online/cities/Budapest/place/p/14486203/Magnum%2BSauna']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','weekday_fast_friday_weekend_real_line_large_post_locker_absorption_id_and_key_practicality','source_urls',to_jsonb(array['https://gaysaunabudapest.com/','https://wanderlog.com/place/details/4210371/magnum-sauna']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','friday_broad_busy_weekend_late_action_weekday_layout_learning_and_day_specific_gender_rules','source_urls',to_jsonb(array['https://gaysaunabudapest.com/','https://wanderlog.com/place/details/4210371/magnum-sauna']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','local_gay_bi_international_roughly_18_55_plus_with_event_day_admission_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4210371/magnum-sauna','https://www.top-rated.online/cities/Budapest/place/p/14486203/Magnum%2BSauna']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','locker_towel_sandal_hygiene_and_consent_etiquette_with_event_admission_over_fashion','source_urls',to_jsonb(array['https://gaysaunabudapest.com/','https://wanderlog.com/place/details/4210371/magnum-sauna']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','helpful_english_professional_clean_orderly_praise_balanced_against_shower_odour_tourist_price_and_cold_service_reports','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4210371/magnum-sauna','https://www.tripadvisor.com/Attraction_Review-g274887-d28126113-Reviews-Magnum_Sauna-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (2009::bigint, jsonb_build_object(
      'queue_wait','Concerts and major electronic nights can stack a short courtyard line; talks, exhibitions and early programmes are usually easy. A March 2026 order shut the venue for thirty days, so check the live calendar because stale listings may miss interruptions. Buy ahead for ticketed nights.',
      'best_nights','Choose the room and curator: Hungarian bands, techno, house, trance or acid after dark, and daytime workshops, exhibitions or yoga reveal different sides. Queer-friendly events are strongest when a named collective hosts; Turbina itself is broad cultural infrastructure, not a nightly gay club.',
      'crowd_mix','Budapest musicians, artists, students, electronic dancers and neighbourhood regulars meet international acts and visitors. Queer people are visible, but the baseline audience is mixed. A local concert feels Hungarian-heavy; a touring DJ or Pride-linked date travels wider.',
      'dress_code','There is no single code across a cultural centre. Day programmes suit everyday clothes; concerts invite band tees; electronic nights reward trainers and breathable layers. Follow any promoter-specific theme. The practical constant is respect for the multi-use building, not performing a generic techno uniform.',
      'staff_inclusivity','The venue frames itself as an arts and community space; its 2026 account says inspectors praised security and professional care before a temporary closure. Reviews value community-building and variety. Queer safety still depends on the host and night, so include the named organiser in your check.',
      'venue_classification','active_independent_budapest_eighth_district_multiroom_cultural_center_with_concerts_techno_house_trance_acid_art_workshops_mixed_local_scene_queer_friendly_events_and_resolved_2026_temporary_closure',
      'identity_note','Turbina is a broad cultural centre in Budapest, not a dedicated LGBTQ+ venue. Authorities ordered a thirty-day closure beginning 4 March 2026; current programme status should be checked on the official calendar.',
      'source_urls',to_jsonb(array['https://turbinabudapest.hu/en/info','https://turbinabudapest.hu/en/events/they-have-shut-us-down-for-30-days-but-the-story-does-not-end-here','https://turbinabudapest.hu/en/news/not-just-a-budapest-techno-club','https://wanderlog.com/place/details/3934583/turbina-cultural-center','https://www.reddit.com/r/budapest/comments/138fti5/gay_club_in_budapest/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','programme_scaled_courtyard_line_advance_ticket_and_live_calendar_check_after_march_2026_thirty_day_closure','source_urls',to_jsonb(array['https://turbinabudapest.hu/en/info','https://turbinabudapest.hu/en/events/they-have-shut-us-down-for-30-days-but-the-story-does-not-end-here','https://wanderlog.com/place/details/3934583/turbina-cultural-center']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','curator_room_specific_live_band_techno_house_trance_acid_day_art_workshop_and_named_queer_host_variation','source_urls',to_jsonb(array['https://turbinabudapest.hu/en/info','https://turbinabudapest.hu/en/news/not-just-a-budapest-techno-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','musician_artist_student_electronic_neighbourhood_international_and_visible_queer_mixed_crowd_by_programme','source_urls',to_jsonb(array['https://wanderlog.com/place/details/3934583/turbina-cultural-center','https://www.reddit.com/r/budapest/comments/138fti5/gay_club_in_budapest/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_single_cultural_center_code_day_concert_and_electronic_practical_variation','source_urls',to_jsonb(array['https://turbinabudapest.hu/en/info','https://turbinabudapest.hu/en/news/not-just-a-budapest-techno-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','community_space_mission_and_inspection_security_professional_care_praise_with_host_specific_queer_safety','source_urls',to_jsonb(array['https://turbinabudapest.hu/en/events/they-have-shut-us-down-for-30-days-but-the-story-does-not-end-here','https://wanderlog.com/place/details/3934583/turbina-cultural-center']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (458::bigint, jsonb_build_object(
      'queue_wait','The riverfront cafe-bar is normally walk-in from daytime onward. Sunset, Eurovision screenings and weekend evenings can fill the narrow terrace and window tables, so arrive earlier for a Danube view. There is no selective club queue; if the first room is busy, the rhythm is drinks and patience rather than a door test.',
      'best_nights','Sunset is the daily sweet spot, with dinner traffic, cocktails and the bridge view overlapping. Eurovision, karaoke, drag or community screenings create the most collective nights; Friday and Saturday run latest. A weekday afternoon is better for lunch and an easy chat before Budapest nightlife starts elsewhere.',
      'crowd_mix','Gay men and LGBTQ+ locals share the bar with tourists, couples, mixed-age friends and straight guests who stop for the river. Early hours are visibly mixed; later community programmes turn queerer and more social. Its central waterfront location brings more visitors than a hidden local pub, without losing regulars.',
      'dress_code','Anything from sightseeing layers to a date-night shirt, summer dress or expressive queer look works. There is no fashion door. Dress for river wind on the terrace and a long city walk; save fetish or high-production styling for the event that asks for it. The atmosphere is liberal, relaxed and publicly visible.',
      'staff_inclusivity','Friendly bartenders, travel help, good cocktails and a warm welcome recur, including for queer couples and mixed groups. Service can slow on a packed terrace, but no consistent exclusion pattern appears. The street-facing format feels less hidden than many Budapest gay venues.',
      'venue_classification','active_budapest_danube_riverfront_lgbtq_cafe_bar_with_day_food_sunset_terrace_late_weekends_eurovision_karaoke_drag_and_screenings_gay_local_tourist_mixed_age_crowd_and_warm_staff_consensus',
      'identity_note','Why Not Cafe & Bar is active at Belgrad rakpart 3, Budapest. Current map hours begin in daytime and run late, so the stored daily 18:00 opening understates its cafe role.',
      'source_urls',to_jsonb(array['https://whynotcafe.hu/','https://maps.apple.com/place?place-id=I4DCFA9D95BD10431','https://www.tripadvisor.com/Restaurant_Review-g274887-d7208020-Reviews-Why_Not_Cafe_and_Bar_Budapest-Budapest_Central_Hungary.html','https://www.reddit.com/r/budapest/comments/1e251eb/could_you_suggest_some_places_where_people_who/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','normal_walkin_with_sunset_screening_weekend_terrace_and_window_table_pressure','source_urls',to_jsonb(array['https://maps.apple.com/place?place-id=I4DCFA9D95BD10431','https://www.tripadvisor.com/Restaurant_Review-g274887-d7208020-Reviews-Why_Not_Cafe_and_Bar_Budapest-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','sunset_daily_sweet_spot_eurovision_karaoke_drag_screening_weekend_late_and_weekday_lunch_variation','source_urls',to_jsonb(array['https://whynotcafe.hu/','https://maps.apple.com/place?place-id=I4DCFA9D95BD10431']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','gay_lgbtq_local_tourist_couple_mixed_age_friend_and_straight_guest_mix_with_later_queer_shift','source_urls',to_jsonb(array['https://maps.apple.com/place?place-id=I4DCFA9D95BD10431','https://www.reddit.com/r/budapest/comments/1e251eb/could_you_suggest_some_places_where_people_who/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_fashion_door_sightseeing_date_summer_expressive_style_and_river_weather_practicality','source_urls',to_jsonb(array['https://whynotcafe.hu/','https://maps.apple.com/place?place-id=I4DCFA9D95BD10431']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','friendly_bartender_travel_help_cocktail_and_queer_mixed_group_welcome_with_peak_service_slowdown','source_urls',to_jsonb(array['https://maps.apple.com/place?place-id=I4DCFA9D95BD10431','https://www.tripadvisor.com/Restaurant_Review-g274887-d7208020-Reviews-Why_Not_Cafe_and_Bar_Budapest-Budapest_Central_Hungary.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (751,457,492,494,493,459,2009,458)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
