-- Queer Atlas venue intelligence: global review-led editorial pass, batch 62.
-- Eight Copenhagen records checked against current official pages, local reporting, listings and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, never in reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1981::bigint, jsonb_build_object(
      'queue_wait','This compact boutique hotel usually has an orderly desk, but standard check-in and breakfast can bunch. The 24-hour room-use concept rewards direct booking and early coordination rather than a door line. Reserve popular weekends and request a courtyard-facing room if street or nightlife noise concerns you.','best_nights','Friday and Saturday put Vesterbro restaurants, bars and the Meatpacking District at their liveliest; a weekday gives a calmer base close to Central Station. The wine hour is sociable but this is not a party hotel. Its central location makes queer nightlife elsewhere easy to reach.','crowd_mix','International couples, solo city breakers, friends and design-minded leisure guests dominate, with a polished boutique feel rather than a hostel scene. LGBTQ+ travellers have long appeared in its marketing and guest mix, but current operations remain broadly mainstream and welcome many kinds of city visitor.','dress_code','Colourful smart casual suits the interiors, though there is no dress requirement. Trainers and weather layers work for Vesterbro exploration; a sharper option is useful for dinner. Rooms vary in size, so pack compactly and keep a rain layer ready rather than treating the hotel as a formal occasion.','staff_inclusivity','The property has a long history of LGBTQ+ outreach, while current reviews praise helpful, warm service, location and the sociable wine hour. Some guests report small rooms, heat or noise. Inclusion evidence is stronger than for a generic hotel, but communicate bedding, identity and access needs clearly.','venue_classification','active_independent_vesterbro_boutique_hotel_near_copenhagen_central_station_with_colourful_design_wine_hour_direct_booking_twenty_four_hour_room_concept_international_couple_solo_mix_and_longstanding_lgbtq_outreach','identity_note','Andersen Boutique Hotel is a mainstream boutique property with documented historic LGBTQ+ outreach; it is not an exclusively queer hotel.','source_urls',to_jsonb(array['https://andersen-hotel.dk/en/','https://www.booking.com/reviews/dk/hotel/andersen-boutique.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d232238-Reviews-Andersen_Boutique_Hotel-Copenhagen_Zealand.html','https://www.trustindex.io/reviews/andersen-hotel.dk-en']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','orderly_compact_hotel_checkin_breakfast_direct_booking_and_noise_room_request_context','source_urls',to_jsonb(array['https://andersen-hotel.dk/en/','https://www.booking.com/reviews/dk/hotel/andersen-boutique.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_vesterbro_energy_weekday_calm_wine_hour_sociality_and_offsite_queer_nightlife_access','source_urls',to_jsonb(array['https://andersen-hotel.dk/en/','https://www.tripadvisor.com/Hotel_Review-g189541-d232238-Reviews-Andersen_Boutique_Hotel-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','international_couple_solo_friend_design_leisure_and_visible_lgbtq_guest_mix','source_urls',to_jsonb(array['https://andersen-hotel.dk/en/','https://www.trustindex.io/reviews/andersen-hotel.dk-en']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','colourful_smart_casual_without_requirement_and_compact_room_weather_layer_practicality','source_urls',to_jsonb(array['https://andersen-hotel.dk/en/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','longstanding_lgbtq_outreach_and_warm_helpful_service_consensus_with_room_heat_noise_caveats','source_urls',to_jsonb(array['https://andersen-hotel.dk/en/','https://www.booking.com/reviews/dk/hotel/andersen-boutique.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d232238-Reviews-Andersen_Boutique_Hotel-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1984::bigint, jsonb_build_object(
      'queue_wait','Reception is conventional, while spa access, breakfast and the courtyard can become the capacity points. Book the spa treatment or access conditions with the room because some facilities may carry fees. Central Station and Meatpacking District proximity keep onward waits short, but weekend rooms sell early.','best_nights','A Friday or Saturday works for dinner and dancing in Vesterbro followed by the sauna, steam room or courtyard calm; a weekday is quieter for spa use. The hotel’s Bali-inspired retreat atmosphere is the feature. It does not host a verified recurring queer party.','crowd_mix','Couples, wellness travellers, design-conscious city breakers and international leisure guests predominate, with some business visitors. LGBTQ+ couples fit into a relaxed Vesterbro mainstream. The sensual spa and four-poster aesthetic can feel romantic, but there is no fixed gay house crowd.','dress_code','Bohemian resort-casual fits: soft layers, linen, trainers and swimwear for the spa, with something warmer for Copenhagen weather. No formal code is published. Confirm robe, slipper and spa arrangements rather than assuming they are included, and use ordinary covered clothing outside wellness areas.','staff_inclusivity','Reviews often praise kind staff, atmosphere, organic breakfast and central position, while room size, ventilation, noise and spa value divide opinion. The brand communicates sustainability and open-minded hospitality, but no property-specific LGBTQ+ training was verified. State bedding and privacy needs in advance.','venue_classification','active_bali_inspired_sustainable_boutique_and_spa_hotel_in_copenhagen_vesterbro_with_courtyard_sauna_steam_hot_tub_organic_food_couple_wellness_international_mix_and_positive_atmosphere_but_room_spa_value_caveats','identity_note','Axel Guldsmeden is a mainstream sustainable boutique spa hotel in queer-friendly Vesterbro, not an LGBTQ+-exclusive property.','source_urls',to_jsonb(array['https://guldsmedenhotels.com/axel-guldsmeden/','https://www.booking.com/reviews/dk/hotel/axel-guldsmeden.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d234079-Reviews-Axel_Guldsmeden_Hotel-Copenhagen_Zealand.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','standard_reception_with_spa_breakfast_courtyard_fee_and_weekend_room_capacity_pressure','source_urls',to_jsonb(array['https://guldsmedenhotels.com/axel-guldsmeden/','https://www.booking.com/reviews/dk/hotel/axel-guldsmeden.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_vesterbro_nightlife_plus_spa_and_quieter_weekday_wellness_without_inhouse_queer_party','source_urls',to_jsonb(array['https://guldsmedenhotels.com/axel-guldsmeden/','https://www.tripadvisor.com/Hotel_Review-g189541-d234079-Reviews-Axel_Guldsmeden_Hotel-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','couple_wellness_design_international_business_and_mainstream_lgbtq_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/dk/hotel/axel-guldsmeden.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d234079-Reviews-Axel_Guldsmeden_Hotel-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','bohemian_resort_casual_swimwear_and_weather_layers_without_formal_code_and_with_spa_inclusion_checks','source_urls',to_jsonb(array['https://guldsmedenhotels.com/axel-guldsmeden/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','kind_staff_atmosphere_breakfast_location_praise_with_room_ventilation_noise_spa_value_caveats_and_no_verified_training','source_urls',to_jsonb(array['https://www.booking.com/reviews/dk/hotel/axel-guldsmeden.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d234079-Reviews-Axel_Guldsmeden_Hotel-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (227::bigint, jsonb_build_object(
      'queue_wait','The intimate room can fill quickly for drag, karaoke, quiz and weekend pop nights. Friday and Saturday run until early morning, so a compact late queue is plausible; arrive earlier for a seat or clear view. Photo ID helps, and the venue enforces a strict no-smoking rule indoors.','best_nights','Choose the programme: karaoke, drag, cabaret, retro themes and musical or diva-led pop give each night a distinct shape. Friday and Saturday bring the longest party, while a quiz or weekday show feels more conversational. Check the calendar rather than assuming a generic dance night.','crowd_mix','LGBTQ+ regulars, drag followers, musical-theatre fans, visitors, mixed queer friendship groups and allies share the former Cosy Bar room. It aims for broad community belonging rather than one age or gender. Specific retro and performance nights naturally pull their own generations and fandoms.','dress_code','Expressive but optional is the mood: everyday bar clothes, glitter, drag-inspired glamour and musical-fan looks all work. No formal fashion code is stated. Travel light in the intimate room, respect the indoor smoking ban and never confuse theatrical flirtation with consent.','staff_inclusivity','The venue states an LGBT+ inclusion mission and programs community performance, giving stronger evidence than a generic bar label. Its operating history is still short, so long-run review consensus is developing. Respect staff instructions, report harassment and assess each busy shift on its conduct.','venue_classification','active_lgbtq_bar_and_intimate_performance_venue_in_former_cosy_bar_copenhagen_with_pop_musicals_drag_karaoke_cabaret_quiz_weekend_late_hours_broad_community_mission_and_developing_review_consensus','identity_note','Centre Stage is the active LGBT+ successor in the former Cosy Bar premises, opened in August 2024; it should not be confused with the closed Cosy identity.','source_urls',to_jsonb(array['https://www.centrestage.dk/','https://www.centrestage.dk/about-us','https://www.visitcopenhagen.com/copenhagen/planning/centre-stage-gdk436188','https://www.centrestage.dk/menu']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','intimate_capacity_weekend_late_and_performance_event_crowding_with_id_and_strict_no_smoking_rule','source_urls',to_jsonb(array['https://www.centrestage.dk/','https://www.centrestage.dk/about-us']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','calendar_led_karaoke_drag_cabaret_retro_quiz_and_weekend_long_party_variation','source_urls',to_jsonb(array['https://www.centrestage.dk/','https://www.visitcopenhagen.com/copenhagen/planning/centre-stage-gdk436188']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','broad_lgbtq_regular_drag_musical_fan_visitor_friend_group_and_ally_mix','source_urls',to_jsonb(array['https://www.centrestage.dk/about-us','https://www.visitcopenhagen.com/copenhagen/planning/centre-stage-gdk436188']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','optional_expressive_glamour_or_everyday_barwear_with_room_smoking_and_consent_practicality','source_urls',to_jsonb(array['https://www.centrestage.dk/','https://www.centrestage.dk/menu']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','explicit_lgbtq_inclusion_mission_and_community_programming_with_shorter_operating_history','source_urls',to_jsonb(array['https://www.centrestage.dk/about-us','https://www.centrestage.dk/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1986::bigint, jsonb_build_object(
      'queue_wait','Kiosk-led check-in is normally quick, with ambassadors helping when the technology stalls. Breakfast and standard arrival hours can bunch; rooms are intentionally compact and have one wall-to-wall bed. Book early for summer and Pride, and confirm whether an early check-in or late checkout costs extra.','best_nights','Friday and Saturday place City Hall Square and nearby Studiestræde at maximum energy; a weekday makes the large living-room lobby calmer for work or drinks. The hotel’s own bar is sociable around the clock, but queer nightlife is off-site and reached on foot.','crowd_mix','Solo travellers, couples, business guests and international visitors dominate, with locals and remote workers sometimes using the public living room. LGBTQ+ guests blend into the modern mainstream crowd. The tiny room and bed-against-window layout suits intimate pairs better than companions wanting separation.','dress_code','Modern travel casual is ideal; there is no dress gate. Trainers, layers and a smart dinner piece cover the city and lobby. Pack lightly because storage and floor space are limited, and review the glass bathroom and bed layout with your companion before booking.','staff_inclusivity','Reviews commonly praise upbeat ambassadors, central location, cleanliness and help with the kiosks; room size, privacy, breakfast value and technology frustrate some guests. No specific LGBTQ+ training evidence surfaced. Human help is available, so request it and state names, bedding and access needs clearly.','venue_classification','active_mainstream_technology_led_citizenm_hotel_on_copenhagen_city_hall_square_with_compact_smart_rooms_large_social_living_room_bar_solo_couple_business_international_mix_and_positive_ambassador_location_consensus','identity_note','citizenM Copenhagen Radhuspladsen is a mainstream compact-room hotel close to LGBTQ+ nightlife, not a dedicated queer property.','source_urls',to_jsonb(array['https://www.marriott.com/en-gb/hotels/cphrp-citizenm-copenhagen-radhuspladsen/','https://www.booking.com/reviews/dk/hotel/citizenm-copenhagen-radhuspladsen.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g189541-d15051151-Reviews-CitizenM_Copenhagen_Radhuspladsen-Copenhagen_Zealand.html','https://www.expedia.com/Copenhagen-Hotels-CitizenM-Copenhagen-Radhuspladsen.h24946846.Hotel-Information']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','kiosk_checkin_with_ambassador_help_breakfast_arrival_peak_and_paid_timing_option_context','source_urls',to_jsonb(array['https://www.marriott.com/en-gb/hotels/cphrp-citizenm-copenhagen-radhuspladsen/','https://www.booking.com/reviews/dk/hotel/citizenm-copenhagen-radhuspladsen.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_city_hall_studiestraede_energy_and_quieter_weekday_living_room_use_with_offsite_queer_scene','source_urls',to_jsonb(array['https://www.marriott.com/en-gb/hotels/cphrp-citizenm-copenhagen-radhuspladsen/','https://www.tripadvisor.co.uk/Hotel_Review-g189541-d15051151-Reviews-CitizenM_Copenhagen_Radhuspladsen-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','solo_couple_business_shortstay_international_local_worker_and_mainstream_lgbtq_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/dk/hotel/citizenm-copenhagen-radhuspladsen.en-gb.html','https://www.expedia.com/Copenhagen-Hotels-CitizenM-Copenhagen-Radhuspladsen.h24946846.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','modern_travel_casual_without_gate_and_compact_storage_bed_bathroom_layout_practicality','source_urls',to_jsonb(array['https://www.marriott.com/en-gb/hotels/cphrp-citizenm-copenhagen-radhuspladsen/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','upbeat_helpful_ambassador_location_cleanliness_praise_with_space_privacy_value_technology_caveats_and_no_specific_training','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Hotel_Review-g189541-d15051151-Reviews-CitizenM_Copenhagen_Radhuspladsen-Copenhagen_Zealand.html','https://www.booking.com/reviews/dk/hotel/citizenm-copenhagen-radhuspladsen.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (229::bigint, jsonb_build_object(
      'queue_wait','Friday and Saturday electronic bills can create a door line after midnight, especially for international headliners. Advance tickets, valid ID and arriving in the first open hour reduce friction; many events include a first drink then. Read the event-specific age limit and safer-space code before joining.','best_nights','Choose the DJ and room: Friday and Saturday are the core, with Black Box and Red Box offering different scale and intensity. Early hours can be sparse before Copenhagen’s late crowd lands. House and techno dominate, while emerging-artist showcases or label nights can produce the most committed floor.','crowd_mix','Local electronic regulars, international ravers, students, older club devotees and queer guests mix around the music rather than a gay identity. The crowd can be cosmopolitan and serious about dancing, though weak bills may feel touristy or thin. Promoter, headliner and arrival hour strongly shape the room.','dress_code','Functional clubwear is safest: dark or expressive layers, trainers and minimal baggage. There is no published all-black rule. Know the lineup and attitude code, keep phones discreet on the floor and dress for a warm room plus a cold journey home. Intoxication can override any outfit at the door.','staff_inclusivity','The club publishes a safer-space code and zero-tolerance drug policy, and some guests report feeling very welcome. Others describe abrupt selection, high cover or an empty-feeling night. Queer inclusion is policy-backed but not identity-specific; seek the care team or staff early if boundaries are crossed.','venue_classification','active_central_copenhagen_two_room_electronic_music_club_with_house_techno_international_and_emerging_djs_late_weekend_peak_advance_ticket_door_selection_music_led_mixed_crowd_and_published_safer_space_policy','identity_note','Culture Box is a general electronic-music club with a published safer-space code, not an LGBTQ+-specific venue.','source_urls',to_jsonb(array['https://culture-box.com/about/','https://culture-box.com/events/','https://culture-box.com/attitude-code/','https://www.tripadvisor.dk/Attraction_Review-g189541-d24181546-Reviews-Culture_Box-Copenhagen_Zealand.html','https://dk.trustpilot.com/review/www.culture-box.com']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','weekend_headliner_postmidnight_door_with_advance_ticket_id_first_hour_drink_and_event_age_rules','source_urls',to_jsonb(array['https://culture-box.com/about/','https://culture-box.com/events/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','friday_saturday_dj_room_and_label_led_house_techno_with_late_arrival_and_bill_quality_variation','source_urls',to_jsonb(array['https://culture-box.com/events/','https://culture-box.com/about/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','local_international_student_older_devotee_queer_and_music_led_raver_mix_shaped_by_promoter','source_urls',to_jsonb(array['https://www.tripadvisor.dk/Attraction_Review-g189541-d24181546-Reviews-Culture_Box-Copenhagen_Zealand.html','https://dk.trustpilot.com/review/www.culture-box.com']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','functional_expressive_clubwear_without_all_black_rule_and_with_lineup_attitude_phone_weather_practicality','source_urls',to_jsonb(array['https://culture-box.com/attitude-code/','https://culture-box.com/events/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','published_safer_space_and_zero_tolerance_policy_with_welcome_praise_but_door_cover_and_energy_complaints','source_urls',to_jsonb(array['https://culture-box.com/attitude-code/','https://dk.trustpilot.com/review/www.culture-box.com']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (230::bigint, jsonb_build_object(
      'queue_wait','This Refshaleøen warehouse operates on announced dates, not as a nightly walk-in. Summer and major techno bills can produce a ticket and security line; buy ahead, carry ID and budget extra journey time to the industrial waterfront. Late transport planning matters as much as the door.','best_nights','Summer events make the most of the large outdoor yard, while strong Friday or Saturday techno and house lineups carry the room after dark. Winter use is more intermittent and indoor. Pick the collective or artist, check last entry and plan the route home before committing.','crowd_mix','Copenhagen ravers, queer clubbers, students, artists, international visitors and experienced electronic fans form a relaxed but music-focused mix. Big summer dates feel broader and more festival-like; harder underground bills attract committed dancers. It is queer-welcoming rather than a dedicated LGBTQ+ club.','dress_code','Practical warehouse clothing wins: sturdy trainers, layers for an outdoor yard, ear protection and a compact bag. Black is common but not compulsory. Know the lineup, avoid costume-tourism and keep phones secondary on the floor. Weather and the industrial journey are more selective than fashion.','staff_inclusivity','Recent local accounts praise respectful door staff, safety messaging and an approachable dance crowd, including solo visitors. As with any event-led warehouse, promoter and night determine execution. Read the safer-space guidance, locate staff on arrival and report unwanted contact instead of trying to manage it alone.','venue_classification','active_event_led_electronic_warehouse_and_outdoor_club_on_copenhagen_refshaleoen_with_summer_strength_house_techno_collective_programming_music_focused_queer_welcoming_crowd_and_transport_weather_specific_planning','identity_note','Hangaren is an event-led electronic venue on Refshaleøen, not an LGBTQ+-specific or nightly club. Current lineup, season and transport must be checked.','source_urls',to_jsonb(array['https://hangaren.dk/','https://www.instagram.com/hangaren_cph/','https://ra.co/clubs/136494','https://www.reddit.com/r/copenhagen/comments/1uni912/how_is_the_rave_crowd_in_copenhagen/','https://www.reddit.com/r/Techno/comments/1ldktod/copenhagen_any_opinions_on_culturebox_and_hangaren/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','announced_event_ticket_security_line_with_refshaleoen_journey_and_late_transport_requirements','source_urls',to_jsonb(array['https://hangaren.dk/','https://ra.co/clubs/136494']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','summer_outdoor_strength_and_lineup_led_friday_saturday_house_techno_with_seasonal_variation','source_urls',to_jsonb(array['https://www.instagram.com/hangaren_cph/','https://www.reddit.com/r/Techno/comments/1ldktod/copenhagen_any_opinions_on_culturebox_and_hangaren/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','local_raver_queer_student_artist_international_and_experienced_electronic_fan_mix_shaped_by_bill','source_urls',to_jsonb(array['https://ra.co/clubs/136494','https://www.reddit.com/r/copenhagen/comments/1uni912/how_is_the_rave_crowd_in_copenhagen/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','practical_warehouse_trainers_layers_ear_protection_and_small_bag_without_black_requirement','source_urls',to_jsonb(array['https://hangaren.dk/','https://www.reddit.com/r/NewToDenmark/comments/1tp1beq/first_time_exploring_copenhagens_techno_scene_as/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','respectful_door_safety_and_solo_visitor_praise_with_promoter_specific_execution','source_urls',to_jsonb(array['https://www.reddit.com/r/copenhagen/comments/1uni912/how_is_the_rave_crowd_in_copenhagen/','https://www.instagram.com/hangaren_cph/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1985::bigint, jsonb_build_object(
      'queue_wait','Check-in is generally straightforward, while breakfast, wine hour, rooftop seating and the small lift can bunch. Reserve a rooftop table or dinner when available and request a quiet room before arrival. Summer, Pride and major events sell the central inventory early; there is no club queue.','best_nights','A clear summer evening suits the rooftop view, then Friday or Saturday puts Tivoli, City Hall and queer bars within a short walk. Weekdays are calmer for design and wine hour. The property itself is a mainstream boutique hotel, so nightlife comes from the surrounding centre.','crowd_mix','Couples, design-conscious city breakers, families, solo guests and business visitors create an international mainstream mix. Locals appear at rooftop and dining spaces. LGBTQ+ guests benefit from the central location but do not form a separate house scene; room type and city calendar influence the feel.','dress_code','Nordic smart casual works: trainers, layers, understated tailoring and a rooftop wind layer. There is no formal code. Some rooms are compact, so pack lightly; practical rain gear and walking shoes are more useful than occasionwear when moving between the hotel and central nightlife.','staff_inclusivity','Reviews often praise friendly staff, location, wine hour and rooftop atmosphere, while small rooms, heat, street noise, cleaning and value produce mixed notes. No specific LGBTQ+ training evidence surfaced. Confirm room position, bedding and accessibility, especially if privacy or mobility matters.','venue_classification','active_mainstream_central_copenhagen_boutique_design_hotel_with_rooftop_wine_hour_restaurant_tivoli_city_hall_access_international_couple_family_business_mix_and_positive_location_staff_but_room_heat_noise_value_caveats','identity_note','Hotel Danmark is a mainstream boutique hotel close to Copenhagen’s queer nightlife, not an LGBTQ+-specific property.','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-danmark/','https://www.booking.com/reviews/dk/hotel/hoteldanmarkcopenhagen.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d206754-Reviews-Hotel_Danmark-Copenhagen_Zealand.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','checkin_breakfast_wine_hour_rooftop_lift_and_peak_city_inventory_capacity_without_club_door','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-danmark/','https://www.booking.com/reviews/dk/hotel/hoteldanmarkcopenhagen.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','clear_summer_rooftop_weekend_central_nightlife_and_quieter_weekday_design_wine_hour_variation','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-danmark/','https://www.tripadvisor.com/Hotel_Review-g189541-d206754-Reviews-Hotel_Danmark-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','international_couple_design_family_solo_business_local_rooftop_and_mainstream_lgbtq_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/dk/hotel/hoteldanmarkcopenhagen.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d206754-Reviews-Hotel_Danmark-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','nordic_smart_casual_without_code_and_with_rooftop_rain_walking_compact_room_practicality','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-danmark/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','friendly_location_wine_hour_rooftop_praise_with_room_heat_noise_cleaning_value_caveats_and_no_specific_training','source_urls',to_jsonb(array['https://www.booking.com/reviews/dk/hotel/hoteldanmarkcopenhagen.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d206754-Reviews-Hotel_Danmark-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1979::bigint, jsonb_build_object(
      'queue_wait','The boutique lobby is compact, so check-in, breakfast and complimentary wine hour can feel busy even without a formal line. Reserve dinner and book early for summer, Pride or conferences. Ask for a courtyard or upper room if street noise matters, and confirm lift access for the assigned category.','best_nights','Friday and Saturday energise the Latin Quarter restaurants and bars, while a weekday lets the lobby, design and wine hour breathe. A rooftop room is most rewarding in fair weather. Studiestræde nightlife is close, but the hotel has no verified recurring queer event of its own.','crowd_mix','Design-oriented couples, solo travellers, families, business visitors and international weekenders dominate, with locals joining the attached restaurants and café. LGBTQ+ guests are part of an urban mainstream mix. Public spaces can feel fashionable and social without becoming a dedicated community venue.','dress_code','Understated Copenhagen smart casual fits: trainers, clean layers, denim and a sharper evening piece. There is no formal gate. Pack for rain and cycling, and consider room size before bringing large luggage. Restaurant crowds may look polished, but comfort and weather readiness matter more.','staff_inclusivity','Large review samples praise central location, welcoming staff, breakfast and wine hour, while small rooms, ventilation, noise, maintenance and value recur as caveats. No property-specific LGBTQ+ training evidence was found. Put bedding, quiet-room and accessibility requests in writing and verify at check-in.','venue_classification','active_mainstream_latin_quarter_copenhagen_boutique_design_hotel_with_wine_hour_restaurants_cafe_rooftop_room_options_international_couple_solo_family_business_mix_and_positive_location_staff_but_space_noise_ventilation_consensus','identity_note','Hotel SP34 is a mainstream design hotel near central LGBTQ+ nightlife, not a dedicated queer property.','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-sp34/','https://www.booking.com/reviews/dk/hotel/hotel-sp34.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g189541-d5888190-Reviews-Hotel_SP34-Copenhagen_Zealand.html','https://www.wallpaper.com/travel/hotels/best-copenhagen-hotels']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','compact_lobby_checkin_breakfast_wine_hour_dinner_peak_and_quiet_room_lift_coordination','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-sp34/','https://www.booking.com/reviews/dk/hotel/hotel-sp34.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_latin_quarter_energy_quiet_weekday_social_spaces_and_fair_weather_rooftop_room_variation','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-sp34/','https://www.wallpaper.com/travel/hotels/best-copenhagen-hotels']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','design_couple_solo_family_business_international_local_dining_and_mainstream_lgbtq_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/dk/hotel/hotel-sp34.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g189541-d5888190-Reviews-Hotel_SP34-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','understated_smart_casual_without_gate_and_with_rain_cycling_room_size_luggage_practicality','source_urls',to_jsonb(array['https://www.brochner-hotels.com/hotel-sp34/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','welcoming_staff_location_breakfast_wine_hour_praise_with_space_ventilation_noise_maintenance_value_caveats_and_no_specific_training','source_urls',to_jsonb(array['https://www.booking.com/reviews/dk/hotel/hotel-sp34.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g189541-d5888190-Reviews-Hotel_SP34-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1981,1984,227,1986,229,230,1985,1979)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
