-- Queer Atlas venue intelligence: global review-led editorial pass, batch 41.
-- Eight Bogota records, individually researched and rewritten.
-- Mixed clubs are not presented as dedicated LGBTQ+ venues; material door, pricing and access issues are retained.
-- Checked 2026-08-06. Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1676::bigint, jsonb_build_object(
      'queue_wait', 'Check-in is usually easy and reception rates highly. There is no lift, so request a lower-floor apartment before arrival if stairs are an issue. The self-contained rooms attract longer stays; confirm early bag storage, airport pickup and breakfast because service formats have changed.',
      'best_nights', 'Choose this for space, a kitchenette and value rather than a hotel social scene. Midweek can soften street noise; weekends suit travellers using Chapinero by day and night. Light sleepers should request an inward-facing room and pack earplugs. Breakfast is simple and may arrive in-room or come from a nearby bakery.',
      'crowd_mix', 'Solo visitors, couples, friend groups, families and longer-stay international guests use the apartment-style rooms. Queer travellers value the Chapinero position, but no formal LGBTQ+-specific hotel programme was verified. It feels residential and independent, with repeat guests rather than a party-lobby crowd.',
      'dress_code', 'No dress code. Pack comfortable city layers and indoor clothes for cooking or working in the apartment. Shoes that handle stairs matter because there is no lift. Rooms can turn warm when windows close against traffic, so light sleepwear and earplugs are more useful than a polished hotel outfit.',
      'staff_inclusivity', 'Current guests repeatedly praise warm, responsive reception and housekeeping, including help across language differences. Cleanliness and room size score well. Noise, ageing details and one poorly handled burst-pipe flood temper the picture. No written trans or same-gender-couple policy was found.',
      'venue_classification', 'active_general_apartment_style_chapinero_hotel_with_spacious_kitchenette_rooms_strong_staff_value_cleanliness_reviews_and_material_no_lift_traffic_noise_ageing_and_incident_response_context',
      'source_urls', to_jsonb(array['https://www.hotelesgrace.com/hotel-living-55-2/','https://www.booking.com/reviews/co/hotel/apartamentos-living-55.en-gb.html','https://www.booking.com/reviews/co/hotel/apartamentos-living-55.es-mx.html','https://www.booking.com/hotel/co/apartamentos-living-55.html','https://www.hotelscombined.com/Hotel/Hotel_Living_55.htm','https://www.gayout.com/es/south-america/colombia/bogota/hotels/hotel-living-55']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','easy_high_scoring_reception_no_lift_lower_floor_and_changing_breakfast_arrival_service_context','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/apartamentos-living-55.en-gb.html','https://www.booking.com/hotel/co/apartamentos-living-55.html','https://www.hotelscombined.com/Hotel/Hotel_Living_55.htm']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','spacious_kitchenette_value_midweek_noise_weekend_city_use_and_variable_breakfast_delivery_context','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/apartamentos-living-55.es-mx.html','https://www.booking.com/hotel/co/apartamentos-living-55.html','https://www.gayout.com/es/south-america/colombia/bogota/hotels/hotel-living-55']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','solo_couple_friend_family_long_stay_international_and_queer_traveller_mix_without_verified_lgbtq_specific_programme','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/apartamentos-living-55.en-gb.html','https://www.booking.com/reviews/co/hotel/apartamentos-living-55.es-mx.html','https://www.gayout.com/es/south-america/colombia/bogota/hotels/hotel-living-55']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','general_apartment_hotel_city_layers_stair_warm_room_traffic_noise_and_sleepwear_context','source_urls',to_jsonb(array['https://www.booking.com/hotel/co/apartamentos-living-55.html','https://www.booking.com/reviews/co/hotel/apartamentos-living-55.es-mx.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_warm_responsive_staff_language_help_cleanliness_size_consensus_balanced_against_noise_age_and_flood_response','source_urls',to_jsonb(array['https://www.booking.com/reviews/co/hotel/apartamentos-living-55.en-gb.html','https://www.booking.com/reviews/co/hotel/apartamentos-living-55.es-mx.html','https://www.hotelscombined.com/Hotel/Hotel_Living_55.htm']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1671::bigint, jsonb_build_object(
      'queue_wait', 'Arrive early for cocktails by the upstairs firepits and easy movement through three rooms; later it gets body-to-body hot. A grave 2025 account says a solo Black guest was falsely told the club was closed while white and Latino guests entered, so door fairness cannot be assumed.',
      'best_nights', 'Wednesday through Saturday can work, but the selector matters more than the weekday. Start early for house and conversation, then move through electronic, retro, hip-hop and Latin rooms as the night builds. This is an upscale, flexible music night rather than Bogotá’s darkest techno bunker. Bring earplugs.',
      'crowd_mix', 'Electronic regulars, stylish Zona T groups, record lovers, international visitors and queer guests share a mixed, cosmopolitan room. Locals anchor the music culture; travellers are common. It is broad rather than LGBTQ+-majority, and the reported racial door incident seriously complicates its inclusive image.',
      'dress_code', 'Stylish casual works: dark separates, clean sneakers and a layer for the terrace. No dependable written code was found. The room is polished but designed for dancing and lounging, so avoid fragile fashion and carry earplugs. Given the reported selective door, a neat outfit does not guarantee equal treatment.',
      'staff_inclusivity', 'Most reviewers praise friendly staff, fair drinks, cleanliness and a comfortable atmosphere. That positive consensus must sit beside the detailed allegation that a sober Black solo guest was denied while others entered. The venue needs transparent admission rules, anti-racism training and a public complaint route.',
      'venue_classification', 'active_mixed_zona_t_multienvironment_house_techno_retro_hiphop_latin_club_and_radio_space_with_strong_music_staff_reviews_and_material_racial_door_discrimination_allegation',
      'source_urls', to_jsonb(array['https://madradio.co/spot/bogota/','https://wanderlog.com/place/details/9165759/mad-radio-bogot%C3%A1','https://wanderlog.com/es/place/details/9165759/mad-radio-bogot%C3%A1','https://ra.co/clubs/co/bogota','https://www.reddit.com/r/Bogota_Capital/comments/1uxfdj2/que_sitios_de_m%C3%BAsica_electr%C3%B3nica_recomiendan_para/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','early_firepit_arrival_late_body_to_body_heat_visit_duration_and_material_2025_racial_door_allegation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9165759/mad-radio-bogot%C3%A1','https://wanderlog.com/es/place/details/9165759/mad-radio-bogot%C3%A1']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','wednesday_saturday_selector_led_house_electronic_retro_hiphop_latin_early_conversation_and_earplug_context','source_urls',to_jsonb(array['https://madradio.co/spot/bogota/','https://wanderlog.com/place/details/9165759/mad-radio-bogot%C3%A1','https://ra.co/clubs/co/bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','electronic_style_zona_t_record_international_queer_mixed_crowd_without_lgbtq_majority_and_with_racial_door_tension','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9165759/mad-radio-bogot%C3%A1','https://ra.co/clubs/co/bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','polished_terrace_lounge_dance_and_high_volume_context_without_written_code_and_with_selective_door_report','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9165759/mad-radio-bogot%C3%A1','https://wanderlog.com/es/place/details/9165759/mad-radio-bogot%C3%A1']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_friendly_clean_fair_price_comfort_consensus_balanced_against_detailed_solo_black_guest_door_discrimination_allegation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/9165759/mad-radio-bogot%C3%A1']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1670::bigint, jsonb_build_object(
      'queue_wait', 'Buy through the official channel and arrive before the headline rush: recent guests say some events are sold beyond comfortable capacity. VIP tables can be reserved. The door has a history of inconsistent dress-code refusals, so save the ticket terms, confirm entry requirements and keep another electronic option ready.',
      'best_nights', 'Thursday can be the cleanest entry into the house-and-techno sound; Friday and Saturday bring the largest DJs and heaviest crowd. Choose by lineup, not reputation alone. Current official hours are Thursday to Saturday from 10pm, while third-party listings disagree on whether the closing time is 4, 5 or 6am.',
      'crowd_mix', 'Bogotá house and techno devotees, higher-spend groups, local scene regulars and international DJ followers fill the multi-level club. Queer dancers are part of the electronic mix, but no current evidence makes it LGBTQ+-majority. The culture can feel status-aware, especially at the door and VIP tables.',
      'dress_code', 'The official line is free style, dark tones and a cosmic vibe: considered black or expressive electronic clubwear with dance shoes. An older guest was refused while similar outfits entered, so published freedom has not always matched door practice. Avoid beachwear and save the rule.',
      'staff_inclusivity', 'The sound system, DJs and atmosphere earn durable praise, and many guests rate staff well. Recent complaints are material: oversold events, rude service and drink totals above the menu price. The venue is listed as not wheelchair accessible. Check every charge and ask for the access route before buying.',
      'venue_classification', 'active_mainstream_multilevel_house_and_techno_club_with_official_dark_cosmic_free_style_code_strong_sound_lineups_and_material_capacity_door_pricing_service_and_access_concerns',
      'source_urls', to_jsonb(array['https://www.octavaclub.com/','https://www.octavaclub.com/faq','https://www.tripadvisor.com/Attraction_Review-g294074-d10839080-Reviews-Octava_Club-Bogota.html','https://es.restaurantguru.com/club-octava-Bogota','https://www.reddit.com/r/Bogota_Capital/comments/1uxfdj2/que_sitios_de_m%C3%BAsica_electr%C3%B3nica_recomiendan_para/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','official_ticket_vip_table_current_overselling_and_historic_inconsistent_dress_refusal_context','source_urls',to_jsonb(array['https://www.octavaclub.com/faq','https://es.restaurantguru.com/club-octava-Bogota','https://www.tripadvisor.com/Attraction_Review-g294074-d10839080-Reviews-Octava_Club-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','official_thursday_saturday_schedule_lineup_led_house_techno_pattern_and_conflicting_close_times','source_urls',to_jsonb(array['https://www.octavaclub.com/faq','https://www.octavaclub.com/','https://es.restaurantguru.com/club-octava-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','house_techno_higher_spend_local_scene_and_international_dj_follower_mix_without_verified_lgbtq_majority','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g294074-d10839080-Reviews-Octava_Club-Bogota.html','https://es.restaurantguru.com/club-octava-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','official_free_style_dark_tones_cosmic_vibe_balanced_against_inconsistent_historic_door_enforcement','source_urls',to_jsonb(array['https://www.octavaclub.com/faq','https://es.restaurantguru.com/club-octava-Bogota','https://www.tripadvisor.com/Attraction_Review-g294074-d10839080-Reviews-Octava_Club-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','sound_dj_atmosphere_and_staff_praise_balanced_against_current_overselling_rude_service_menu_overcharge_and_no_wheelchair_access_listing','source_urls',to_jsonb(array['https://es.restaurantguru.com/club-octava-Bogota','https://www.tripadvisor.com/Attraction_Review-g294074-d10839080-Reviews-Octava_Club-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1680::bigint, jsonb_build_object(
      'queue_wait', 'This pink bakery is a daytime walk-in, not a door scene. Weekends and cake-decorating workshops can fill tables, so reserve the class or a celebration. Ordinary coffee visits move gently from 8am to 8pm. For a custom cake, order ahead; the finished work and patient guidance are part of what guests value.',
      'best_nights', 'Come for breakfast, brunch, matcha and an afternoon slice rather than nightlife. A cake workshop is the most memorable community experience; Pride brunch adds explicit queer celebration when scheduled. Weekday mornings are calm for conversation, while weekend afternoons bring more groups and sweet-toothed families.',
      'crowd_mix', 'Trans staff, migrants, LGBTQ+ regulars, neighbours, couples, families and dessert pilgrims share the pastel room. It is queer-rooted with a broad customer base, not a café borrowing inclusion through décor. Locals lead daily service; visitors arrive for the employment story and rainbow desserts.',
      'dress_code', 'No code at all: daytime casual, work clothes, bright pink, soft queer style or family brunch basics all belong. If you book a decorating workshop, choose sleeves you can roll and clothes that forgive icing. The signature overalls belong to the team; guests only need appetite and a camera-ready tolerance for colour.',
      'staff_inclusivity', 'Inclusion is structural: the bakery creates formal employment for trans people and migrants, with its team central to the identity. Guests praise patient workshop guidance, attentive service and feeling welcome. Food ratings vary more, so choose the celebrated cakes, cheesecake or brownies.',
      'venue_classification', 'active_trans_and_migrant_employing_queer_rooted_chapinero_bakery_cafe_with_broad_local_customer_mix_cake_workshops_pride_programming_and_strong_current_welcome_service_evidence',
      'source_urls', to_jsonb(array['https://www.instagram.com/petuniareposteria/','https://es.restaurantguru.com/Petunia-Reposteria-con-Alma-Bogota','https://www.degusta.com.co/bogota/restaurante/petunia-reposteria-con-alma_106209.html','https://www.wradio.com.co/2023/07/25/petunia-una-reposteria-diversa-que-contrata-a-personas-trans-y-migrantes-en-bogota/','https://www.semana.com/amp/mejor-colombia/articulo/petunia-la-reposteria-que-le-abre-las-puertas-laborales-a-la-comunidad-lgbti/202455/','https://planbogota.bogotadc.travel/drpl/sites/default/files/2022-12/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','daytime_walkin_weekend_group_workshop_reservation_and_custom_cake_preorder_context','source_urls',to_jsonb(array['https://es.restaurantguru.com/Petunia-Reposteria-con-Alma-Bogota','https://www.instagram.com/petuniareposteria/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','breakfast_brunch_afternoon_cake_workshop_pride_brunch_and_weekday_weekend_usage_pattern','source_urls',to_jsonb(array['https://es.restaurantguru.com/Petunia-Reposteria-con-Alma-Bogota','https://www.semana.com/amp/mejor-colombia/articulo/petunia-la-reposteria-que-le-abre-las-puertas-laborales-a-la-comunidad-lgbti/202455/','https://planbogota.bogotadc.travel/drpl/sites/default/files/2022-12/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','trans_staff_migrant_lgbtq_neighbour_couple_family_and_dessert_visitor_mix_with_local_everyday_core','source_urls',to_jsonb(array['https://www.wradio.com.co/2023/07/25/petunia-una-reposteria-diversa-que-contrata-a-personas-trans-y-migrantes-en-bogota/','https://www.semana.com/amp/mejor-colombia/articulo/petunia-la-reposteria-que-le-abre-las-puertas-laborales-a-la-comunidad-lgbti/202455/','https://es.restaurantguru.com/Petunia-Reposteria-con-Alma-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_code_daytime_bright_family_workshop_and_icing_practical_context','source_urls',to_jsonb(array['https://es.restaurantguru.com/Petunia-Reposteria-con-Alma-Bogota','https://www.wradio.com.co/2023/07/25/petunia-una-reposteria-diversa-que-contrata-a-personas-trans-y-migrantes-en-bogota/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','documented_formal_trans_migrant_employment_patient_workshop_attentive_service_welcome_and_variable_food_ratings','source_urls',to_jsonb(array['https://www.wradio.com.co/2023/07/25/petunia-una-reposteria-diversa-que-contrata-a-personas-trans-y-migrantes-en-bogota/','https://www.semana.com/amp/mejor-colombia/articulo/petunia-la-reposteria-que-le-abre-las-puertas-laborales-a-la-comunidad-lgbti/202455/','https://es.restaurantguru.com/Petunia-Reposteria-con-Alma-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1197::bigint, jsonb_build_object(
      'queue_wait', 'This afternoon-and-evening sauna rarely behaves like a late club queue. Weekends bring more groups and social energy, while off-peak hours feel quieter. Ask the full entry and service price before changing—older guests report surprise charges. Friday and Saturday stay open later than the rest of the week.',
      'best_nights', 'Saturday offers the longest window and strongest group atmosphere; a weekday afternoon is calmer for the steam, sauna and cabins. Recent weekend visitors praise the temperature, music and order. The venue closes by 9–11pm depending on day, so make it an early social or cruising stop, not an after-hours finish.',
      'crowd_mix', 'Gay and bi men of varied ages, bodies and preferences use the wet areas and private cabins. Bogotanos and established regulars lead; travellers join a familiar local sauna rhythm. Group visits appear in current reviews. It is a men-seeking-men environment, not an all-genders wellness spa.',
      'dress_code', 'Lock away street clothes, then choose a towel, briefs or nothing according to the zone. Rubber sandals and a spare tee make the second-floor wet circuit easier; smoke can cling even with a designated area. A cabin is never automatic permission—read the room, ask clearly and leave in dry clothes.',
      'staff_inclusivity', 'A cluster of February 2026 reviews praises excellent staff, clean spaces, comfortable temperature and orderly facilities. The longer record is mixed, citing hidden costs, uneven friendliness and maintenance needs. Ask prices first and inspect the areas you plan to use; current warmth does not erase older patterns.',
      'venue_classification', 'active_men_seeking_men_chapinero_sauna_with_mixed_age_local_crowd_steam_cabins_later_weekend_hours_strong_current_cleanliness_service_reviews_and_historic_price_maintenance_concerns',
      'source_urls', to_jsonb(array['https://www.instagram.com/saintmoritzsauna/','https://saintmoritzsaunas.com/','https://wanderlog.com/es/place/details/6062001/sauna-saint-moritz','https://wanderlog.com/place/details/6062001/sauna-saint-moritz','https://www.reddit.com/r/gaytravel/comments/1jf6s30/visiting_bogot%C3%A1_in_2025_need_advice_on_lgbtq_bars/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','afternoon_evening_weekend_group_offpeak_quiet_later_friday_saturday_and_full_price_confirmation_context','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/6062001/sauna-saint-moritz','https://saintmoritzsaunas.com/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','longest_saturday_window_weekday_calm_current_weekend_temperature_music_order_and_pre_nightlife_close_context','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/6062001/sauna-saint-moritz','https://www.instagram.com/saintmoritzsauna/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_bi_men_mixed_age_body_preference_bogotano_regular_traveller_and_group_visit_mix','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/6062001/sauna-saint-moritz','https://wanderlog.com/place/details/6062001/sauna-saint-moritz']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','towel_swimwear_nudity_flipflop_toiletry_storage_consent_smoking_and_fresh_clothes_context','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/6062001/sauna-saint-moritz','https://saintmoritzsaunas.com/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_february_2026_staff_clean_temperature_order_consensus_balanced_against_historic_hidden_cost_friendliness_and_maintenance_reports','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/6062001/sauna-saint-moritz']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1198::bigint, jsonb_build_object(
      'queue_wait', 'This intimate luxury hotel has 24-hour reception, and current arrivals are remembered for personal welcome rather than lines. Check-in timing still follows the booking policy; ask ahead for early access or luggage care. If a request matters, use the concierge—service is strongest when the right team member owns it.',
      'best_nights', 'Stay when Zona T dining, shopping and a quiet premium bed matter. Weekend nightlife is steps away, while business nights stay composed inside. Breakfast is repeatedly called exceptional; a slow morning may beat squeezing in another club. Even street-facing rooms can be quiet.',
      'crowd_mix', 'Luxury couples, tour groups, business travellers, families and international guests share a small, polished property. It holds recognised LGBTQ+-friendly certification but is not a queer social hotel. The crowd is affluent and mixed; value lies in trusted treatment and location, not majority identity.',
      'dress_code', 'No hotel dress code. Smart casual suits the restaurant and Zona T; travelwear is normal at reception. A refined dinner layer is useful, but the room welcomes what survived your flight or night out. Bogotá evenings stay cool, so pack tailoring or clubwear that works with a jacket.',
      'staff_inclusivity', 'The property carries recognised LGBTQ+-friendly certification, and 2026 guests praise name-level attention from reception, concierge, restaurant and housekeeping. Cleanliness and comfort are exceptionally strong. One concierge was unhelpful on a gym request, showing that individual follow-through can still vary.',
      'venue_classification', 'active_intimate_luxury_zona_t_hotel_with_formal_lgbtq_friendly_recognition_exceptional_current_service_breakfast_cleanliness_comfort_and_mixed_affluent_traveller_profile',
      'source_urls', to_jsonb(array['https://sofitel.accor.com/en/hotels/0561.html','https://www.tripadvisor.com/Hotel_Review-g294074-d299375-Reviews-Sofitel_Bogota_Victoria_Regia-Bogota.html','https://www.trip.com/hotels/bogota-hotel-detail-2269062/sofitel-bogota-victoria-regia/review.html','https://www.booking.com/hotel/co/sofitel-bogota-victoria-regia.html','https://visitbogota.co/sites/default/files/2026-06/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf','https://files.visitbogota.co/sites/default/files/2025-12/2025-12-10-version-final-guia-de-turismo-accesible-de-bogota.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','twenty_four_hour_intimate_personal_arrival_early_access_luggage_and_concierge_request_ownership_context','source_urls',to_jsonb(array['https://sofitel.accor.com/en/hotels/0561.html','https://www.tripadvisor.com/Hotel_Review-g294074-d299375-Reviews-Sofitel_Bogota_Victoria_Regia-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','zona_t_weekend_nightlife_business_night_quiet_room_and_exceptional_breakfast_consensus','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g294074-d299375-Reviews-Sofitel_Bogota_Victoria_Regia-Bogota.html','https://www.trip.com/hotels/bogota-hotel-detail-2269062/sofitel-bogota-victoria-regia/review.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','luxury_couple_tour_business_family_international_mixed_affluent_guest_profile_with_formal_lgbtq_friendly_recognition','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g294074-d299375-Reviews-Sofitel_Bogota_Victoria_Regia-Bogota.html','https://visitbogota.co/sites/default/files/2026-06/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','general_luxury_hotel_smart_casual_restaurant_zona_t_and_cold_evening_layer_context_without_guest_code','source_urls',to_jsonb(array['https://sofitel.accor.com/en/hotels/0561.html','https://www.tripadvisor.com/Hotel_Review-g294074-d299375-Reviews-Sofitel_Bogota_Victoria_Regia-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','formal_lgbtq_friendly_recognition_and_exceptional_current_name_level_service_cleanliness_comfort_with_individual_followthrough_variation','source_urls',to_jsonb(array['https://visitbogota.co/sites/default/files/2026-06/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf','https://www.tripadvisor.com/Hotel_Review-g294074-d299375-Reviews-Sofitel_Bogota_Victoria_Regia-Bogota.html','https://www.trip.com/hotels/bogota-hotel-detail-2269062/sofitel-bogota-victoria-regia/review.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1677::bigint, jsonb_build_object(
      'queue_wait', 'This is a private hosted home, so arrival is arranged rather than queued. The host currently answers within 12 hours and check-in starts at noon. Share your timing through the booking platform and never move payment off-platform. Because it is intimate and clothing-optional, align on house rules before confirming.',
      'best_nights', 'Book for community, breakfast and fireside conversation—not hotel anonymity. A longer stay lets hosts tailor queer tips and makes fellow guests familiar. Any night works; the sweetest moments described are slow mornings, shared kitchen time and relaxed nude evenings, not a scheduled party.',
      'crowd_mix', 'Gay nudist travellers and LGBTQ+ guests seeking body freedom form the heart, with international visitors mixing with local hosts and housemates. It is deliberately social but small, so each booking changes the chemistry. Clothing is optional, not compulsory; one clothed guest still reported feeling completely at ease.',
      'dress_code', 'Clothing-optional means your choice: nude in shared spaces, dressed in your room, or anything between with mutual respect. Bring a robe, slippers and warm layers for Bogotá. Smoking belongs only in designated common areas. Ask before assuming photography, touch or sexual availability; nudity never replaces consent.',
      'staff_inclusivity', 'The gay host sets respect, diversity and care as the golden rule. Verified guests praise warmth, navigation help, clean private rooms and vegetarian or vegan breakfast; ratings are exceptional. This is hosted community, so state boundaries clearly and use the platform if expectations diverge.',
      'venue_classification', 'active_gay_hosted_clothing_optional_social_bed_and_breakfast_with_private_rooms_shared_fireplace_kitchen_patios_local_tips_strong_verified_welcome_and_explicit_respect_rules',
      'source_urls', to_jsonb(array['https://www.misterbandb.com/rooms/1024977','https://www.misterbandb.com/es/rooms/1013423','https://www.naturistbnb.com/owners/pfprojet/','https://www.gayout.com/es/south-america/colombia/bogota/hotels/the-nudist-mansion','https://www.top-rated.online/cities/Bogota/place/p/10887960/The%2BNudist%2BMansion']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','private_hosted_prearranged_noon_checkin_sub_twelve_hour_response_platform_payment_and_rule_alignment_context','source_urls',to_jsonb(array['https://www.misterbandb.com/rooms/1024977','https://www.misterbandb.com/es/rooms/1013423']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','community_breakfast_fireside_kitchen_local_tip_longer_stay_and_relaxed_evening_pattern_without_scheduled_party','source_urls',to_jsonb(array['https://www.misterbandb.com/rooms/1024977','https://www.gayout.com/es/south-america/colombia/bogota/hotels/the-nudist-mansion','https://www.naturistbnb.com/owners/pfprojet/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_nudist_lgbtq_international_local_host_housemate_small_social_and_clothing_optional_guest_mix','source_urls',to_jsonb(array['https://www.misterbandb.com/rooms/1024977','https://www.gayout.com/es/south-america/colombia/bogota/hotels/the-nudist-mansion']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','clothing_optional_robe_slipper_cold_weather_designated_smoking_photography_touch_and_consent_context','source_urls',to_jsonb(array['https://www.misterbandb.com/rooms/1024977','https://www.misterbandb.com/es/rooms/1013423','https://www.naturistbnb.com/owners/pfprojet/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','explicit_respect_diversity_care_rules_and_strong_verified_host_navigation_clean_room_dietary_breakfast_praise','source_urls',to_jsonb(array['https://www.misterbandb.com/rooms/1024977','https://www.gayout.com/es/south-america/colombia/bogota/hotels/the-nudist-mansion','https://www.top-rated.online/cities/Bogota/place/p/10887960/The%2BNudist%2BMansion']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1199::bigint, jsonb_build_object(
      'queue_wait', 'Friday and Saturday are the operating nights; arriving near 9pm protects dance space before three floors build. Popular DJs tighten entry, though guests describe easier access and lower cover than some rivals. Security can feel intrusive. Water is expensive, so check the refill policy.',
      'best_nights', 'Choose the lineup, then roam: electronic and techno in one room, reggaetón and perreo under the disco ball, house on the open terrace. Friday can feel looser; Saturday draws the fuller circuit. The pleasure is changing sound without changing venue. Official posts should decide the DJ and opening time.',
      'crowd_mix', 'Bogotá electronic regulars, perreo crews, birthdays, alternative locals, queer dancers and visiting club fans mix across three floors. The floor is often described as respectful and less stiff than upscale rivals, but the club is mixed rather than LGBTQ+-majority. Locals lead; tourists can enter the rhythm easily.',
      'dress_code', 'Relaxed, trend-aware clubwear works: dark basics, colour, good sneakers and a layer for the rooftop. No reliable strict fashion code was found. Dress to move between heat and cold, and keep bags light for security checks. An event flyer may add rules, so the current lineup post outranks generic advice.',
      'staff_inclusivity', 'Recent guests praise friendly ticket and security teams, quick drinks and a safe, respectful dance floor. Others find security overly close, the reggaetón sound too quiet and water overpriced. The overall signal is warmer than many large clubs, but no detailed queer, trans or anti-harassment policy was found.',
      'venue_classification', 'active_mixed_three_floor_chapinero_electronic_techno_reggaeton_perreo_and_rooftop_house_club_with_respectful_crowd_strong_staff_reviews_and_security_water_price_policy_gaps',
      'source_urls', to_jsonb(array['https://www.instagram.com/videoclubx/','https://wanderlog.com/place/details/1783713/video-club','https://es.restaurantguru.com/Video-Club-Bogota','https://ra.co/clubs/co/bogota','https://www.luxuriacity.com/en/colombia/bogota/entertainment/video-club']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','friday_saturday_nine_pm_early_space_popular_dj_entry_lower_relative_cover_active_security_and_water_price_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1783713/video-club','https://es.restaurantguru.com/Video-Club-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','lineup_led_electronic_techno_reggaeton_perreo_rooftop_house_friday_looser_saturday_fuller_pattern','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1783713/video-club','https://ra.co/clubs/co/bogota','https://www.instagram.com/videoclubx/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','electronic_perreo_birthday_alternative_local_queer_dancer_and_visiting_club_fan_mix_without_lgbtq_majority','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1783713/video-club','https://ra.co/clubs/co/bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','relaxed_trend_aware_multifloor_heat_rooftop_cold_security_check_and_event_specific_context_without_strict_code','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1783713/video-club','https://www.instagram.com/videoclubx/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_friendly_ticket_security_quick_service_safe_respectful_floor_praise_balanced_against_intrusive_security_sound_water_and_policy_gaps','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1783713/video-club','https://es.restaurantguru.com/Video-Club-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1676,1671,1670,1680,1197,1198,1677,1199)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
