-- Queer Atlas venue intelligence: global review-led editorial pass, batch 34.
-- First eight Belfast records, individually researched and rewritten.
-- Boombox and Kremlin retain current queer-nightlife value but carry material door-policy warnings.
-- Spaghetti Arms closed its sit-in restaurant in June 2026; only the night hatch was announced to continue.
-- Checked 2026-08-06. Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1579::bigint, jsonb_build_object(
      'queue_wait', 'This is a small upstairs club, and the pinch point is the door rather than a predictable minute count. Arrive near the 10 pm opening for the easiest attempt. Recent guests report separate ticket queues, variable £3–£10 charges and refusals tied to regular or queer-community status, even when no line looked long.',
      'best_nights', 'Choose a dated drag, cabaret or guest-DJ night if you want the room at its most unmistakably queer. Friday and Saturday stay open latest and draw the fuller dance floor; a weeknight can feel looser but still check the live post first. Pop, camp and performance are a safer bet than underground club music.',
      'crowd_mix', 'Queer Belfast regulars anchor the room, joined by students, visitors, allies and plenty of people arriving from the bar downstairs. It feels more explicitly LGBTQ+ than its famous neighbour, yet the mix changes fast after midnight. Some tourists love the welcome; others say the door treated non-regulars with suspicion.',
      'dress_code', 'No formal look is published: clubwear, denim, trainers, colour, makeup and drag all make sense. The practical code is to arrive composed, know which event is on and avoid looking like a random late-night group hunting any dance floor. Expressive clothes help the mood, but they do not guarantee entry.',
      'staff_inclusivity', 'Inside, recent guests praise helpful staff, drag talent, good-value drinks and a night that felt safe. The door tells a rougher story: queer women and visitors describe being challenged to prove belonging, turned away as non-regulars or handled aggressively. Treat inclusion as inconsistent and keep a backup venue.',
      'venue_classification', 'active_small_upstairs_lgbtq_nightclub_with_drag_pop_and_strong_queer_identity_but_serious_current_door_consistency_concerns',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/1820861/boombox-belfast','https://www.belfastbar.co.uk/boombox-review.htm','https://www.reddit.com/r/Belfast/comments/1qp9otn/gay_bars_in_belfast/','https://www.reddit.com/r/LGBTireland/comments/1mih12f/lgbt_scene_in_belfast/','https://www.reddit.com/r/northernireland/comments/1mfzh75']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_small_room_early_arrival_ticket_queue_variable_charge_and_selective_door_consensus_without_reliable_minute_range','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820861/boombox-belfast','https://www.reddit.com/r/Belfast/comments/1qp9otn/gay_bars_in_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_drag_guest_dj_pop_event_and_later_weekend_close_pattern','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820861/boombox-belfast','https://www.belfastbar.co.uk/boombox-review.htm','https://www.reddit.com/r/LGBTireland/comments/1mih12f/lgbt_scene_in_belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','explicit_queer_regular_student_visitor_ally_and_downstairs_bar_crossover_with_variable_late_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820861/boombox-belfast','https://www.reddit.com/r/Belfast/comments/1qp9otn/gay_bars_in_belfast/','https://www.reddit.com/r/northernireland/comments/1mfzh75']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_formal_code_expressive_clubwear_and_door_belonging_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820861/boombox-belfast','https://www.reddit.com/r/Belfast/comments/1ffv9dv']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','polarised_current_inside_welcome_and_safety_praise_balanced_against_repeated_door_exclusion_and_aggression_reports','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820861/boombox-belfast','https://www.reddit.com/r/Belfast/comments/1e1d5eq']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1591::bigint, jsonb_build_object(
      'queue_wait', 'Check-in starts at 3 pm and current guests usually call it quick, with staff sometimes releasing rooms early. The real wait is upstairs: reserve rooftop restaurant tables, while garden and bar access can tighten around weekend DJs. The pedestrian entrance means taxis stop nearby, not at the door.',
      'best_nights', 'Friday or Saturday gives the full version: courtyard drinks, rooftop dinner and DJs without needing another address. Choose Sunday for a softer brunch-to-cocktails rhythm, or a weekday if sleep and work matter more than buzz. During Pride, the five-minute walk to the main gathering point is the standout advantage.',
      'crowd_mix', 'City-break couples, concert groups, business travellers and Belfast friends meeting for food create a young, design-conscious mix. It is a mainstream hotel, not a queer property, but LGBTQ+ travel groups have used it for Pride and the surrounding Cathedral Quarter brings a naturally mixed local-and-visitor crowd.',
      'dress_code', 'Think polished streetwear rather than hotel formality: trainers, denim, a good jacket and personality travel easily from the compact rooms to the roof. Brunch is relaxed; rooftop dinner or the hidden cocktail bar rewards one sharper layer. Pack light because the smallest rooms are genuinely small.',
      'staff_inclusivity', 'Verified 2026 stays praise friendly staff, early-room flexibility, local tips and support for wheelchair users. A recent LGBTQ+ press group stayed here comfortably for Pride, adding a useful lived signal. No explicit hotel-wide LGBTQ+ policy was found, so this is strong practice rather than a formal promise.',
      'venue_classification', 'active_central_design_hotel_with_rooftop_weekend_djs_strong_current_service_and_recent_pride_travel_group_signal_not_dedicated_queer_hotel',
      'source_urls', to_jsonb(array['https://bullitthotel.com/','https://bullitthotel.com/faqs/','https://www.booking.com/reviews/gb/hotel/bullitt.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g186470-d10643677-Reviews-Bullitt_Hotel-Belfast_Northern_Ireland.html','https://passportmagazine.com/celebrating-pride-belfast/','https://bullitthotel.com/app/uploads/2024/09/BLT_MAP_Bullitt-recommends_WEB_SEPT24_v1.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_three_pm_checkin_early_room_flexibility_rooftop_reservation_and_pedestrian_arrival_evidence','source_urls',to_jsonb(array['https://bullitthotel.com/faqs/','https://www.booking.com/reviews/gb/hotel/bullitt.en-gb.html','https://bullitthotel.com/app/uploads/2023/01/BLT_IN-ROOM-AZ_JAN23_V3.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_friday_saturday_rooftop_djs_sunday_brunch_weekday_quiet_and_pride_location_context','source_urls',to_jsonb(array['https://bullitthotel.com/','https://bullitthotel.com/app/uploads/2024/09/BLT_MAP_Bullitt-recommends_WEB_SEPT24_v1.pdf','https://passportmagazine.com/celebrating-pride-belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_couple_group_business_local_diner_and_lgbtq_pride_press_guest_mix','source_urls',to_jsonb(array['https://bullitthotel.com/stay/corporate-stays/','https://www.booking.com/reviews/gb/hotel/bullitt.en-gb.html','https://passportmagazine.com/celebrating-pride-belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','design_led_compact_room_courtyard_rooftop_brunch_and_cocktail_context_without_formal_code','source_urls',to_jsonb(array['https://bullitthotel.com/','https://bullitthotel.com/stay/biggy-room/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_2026_verified_staff_and_accessibility_consensus_plus_recent_lgbtq_pride_group_stay_without_formal_policy','source_urls',to_jsonb(array['https://www.booking.com/reviews/gb/hotel/bullitt.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g186470-d10643677-Reviews-Bullitt_Hotel-Belfast_Northern_Ireland.html','https://passportmagazine.com/celebrating-pride-belfast/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1590::bigint, jsonb_build_object(
      'queue_wait', 'The 300-room scale can create a reception or lift wait at conference and weekend peaks, though recent check-ins are mostly praised. Reserve the top-floor cocktail lounge online even as a guest: walk-ins have been redirected to the booking system. Valet arrival is smoother than circling Bedford Street.',
      'best_nights', 'Pick a clear evening and book the top floor before sunset; the panorama is the reason to be here. Thursday suits a polished drink without full weekend traffic, while Friday or Saturday works for a celebratory stay. If uninterrupted sleep matters, ask for a room away from works and report any plumbing noise early.',
      'crowd_mix', 'Luxury weekenders, conference delegates, couples, tour groups and Belfast residents dressed for cocktails fill this large city hotel. The rooftop brings locals into an otherwise visitor-heavy building. There is no credible sign of a dedicated queer crowd or programme, so expect a conventional, mixed five-star audience.',
      'dress_code', 'Smart-casual is the sweet spot: a sharp coat, tailored trousers, dresses, knitwear or clean trainers fit the lobby and skyline bar. Daytime guests can stay relaxed, but the grand interiors make a little polish feel natural. There is no published queer or fashion gate; reservations matter more than labels.',
      'staff_inclusivity', 'Current verified stays call reception, concierge and housekeeping professional, friendly and highly competent. Isolated reports mention indifferent bar service or awkward access after a late return. No explicit LGBTQ+ commitment was located, so score service strongly while keeping the inclusion claim modest.',
      'venue_classification', 'active_large_luxury_linen_quarter_hotel_with_destination_skyline_bar_strong_current_service_and_no_verified_queer_specific_identity',
      'source_urls', to_jsonb(array['https://www.hastingshotels.com/our-hotels/','https://www.hastingshotels.com/hastings-golf/grandcentralhotel.html','https://www.hastingshotels.com/grand-central/upload/docs/gch-opening-brochure_web.pdf','https://www.booking.com/reviews/gb/hotel/hastings-grand-central.en-gb.html?page=1','https://www.reddit.com/r/northernireland/comments/1jf1hk3/grand_central_hotel/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_large_hotel_checkin_lift_valet_and_observatory_online_reservation_pattern','source_urls',to_jsonb(array['https://www.booking.com/reviews/gb/hotel/hastings-grand-central.en-gb.html?page=1','https://www.reddit.com/r/northernireland/comments/1jf1hk3/grand_central_hotel/','https://www.hastingshotels.com/our-hotels/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_clear_sunset_skyline_bar_weekday_weekend_and_room_noise_context','source_urls',to_jsonb(array['https://www.hastingshotels.com/grand-central/upload/docs/gch-opening-brochure_web.pdf','https://www.booking.com/reviews/gb/hotel/hastings-grand-central.en-gb.html?page=1','https://www.reddit.com/r/northernireland/comments/1jf1hk3/grand_central_hotel/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_luxury_weekender_conference_couple_tour_group_and_local_cocktail_mix_without_queer_specific_programme','source_urls',to_jsonb(array['https://www.hastingshotels.com/our-hotels/','https://www.hastingshotels.com/hastings-golf/grandcentralhotel.html','https://www.booking.com/reviews/gb/hotel/hastings-grand-central.en-gb.html?page=1']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','luxury_lobby_restaurant_and_skyline_cocktail_context_without_published_strict_code','source_urls',to_jsonb(array['https://www.hastingshotels.com/grand-central/upload/docs/gch-opening-brochure_web.pdf','https://www.hastingshotels.com/hastings-golf/grandcentralhotel.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_professional_staff_consensus_balanced_against_isolated_bar_and_late_access_issues_without_lgbtq_policy','source_urls',to_jsonb(array['https://www.booking.com/reviews/gb/hotel/hastings-grand-central.en-gb.html?page=1','https://www.reddit.com/r/northernireland/comments/1jf1hk3/grand_central_hotel/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1584::bigint, jsonb_build_object(
      'queue_wait', 'Ticket holders may have their own line, and recent guests describe entry charges reaching roughly £10–£30 depending on the night. The loyalty app advertises free-entry rewards, but that is not a universal guest list. Arrive before the late surge, carry ID and check the exact ticket terms before joining any queue.',
      'best_nights', 'Follow the dated event rather than the old legend. A themed LGBTQ+ night can still deliver big pop tunes and a packed dance floor; a standard weekend now reads to many locals as a general nightclub with a straighter mix. If an unmistakably queer room matters, compare the same-night programme next door first.',
      'crowd_mix', 'The club remains gay-owned in its public history and still draws queer regulars, visitors and couples, but current locals repeatedly describe a much straighter, mainstream weekend crowd. Expect a younger party mix rather than a protected gay bubble. The balance changes by promotion, so the event name matters.',
      'dress_code', 'The door enforces a real presentation rule even though the website does not explain it. One recent visitor was refused in tracksuit bottoms; clean trainers, dark jeans and intentional clubwear are safer. Bring ID, avoid sportswear and do not assume a paid ticket overrides dress or intoxication decisions.',
      'staff_inclusivity', 'Experiences are sharply divided. Some guests love the music and long-running queer institution; many recent reviews report rude bar service, rough removal, hostile security or gay couples feeling unsafe. The pattern is too consistent to hide. Stay with friends, note staff names and leave if the room turns tense.',
      'venue_classification', 'active_historic_gay_owned_large_nightclub_with_theme_events_increasingly_mainstream_crowd_and_material_current_security_service_concerns',
      'source_urls', to_jsonb(array['https://www.kremlin-belfast.com/','https://wanderlog.com/place/details/1820814/kremlin','https://www.tripadvisor.com/Attraction_Review-g186470-d596706-Reviews-Kremlin-Belfast_Northern_Ireland.html','https://whereis.gay/listing/kremlin/','https://www.reddit.com/r/Belfast/comments/1qyuq1r/belfast_nightlife/','https://www.reddit.com/r/northernireland/comments/1mfzh75']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_ticket_queue_variable_entry_cost_loyalty_reward_id_and_early_arrival_evidence','source_urls',to_jsonb(array['https://www.kremlin-belfast.com/','https://wanderlog.com/place/details/1820814/kremlin']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','event_led_queer_theme_night_value_balanced_against_mainstream_standard_weekend_shift','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820814/kremlin','https://www.reddit.com/r/Belfast/comments/1qyuq1r/belfast_nightlife/','https://www.reddit.com/r/northernireland/comments/1mfzh75']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_gay_owned_queer_regular_and_visitor_base_with_repeated_current_straighter_mainstream_crowd_reports','source_urls',to_jsonb(array['https://whereis.gay/listing/kremlin/','https://www.reddit.com/r/Belfast/comments/1qyuq1r/belfast_nightlife/','https://www.reddit.com/r/northernireland/comments/1mfzh75']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','current_tracksuit_refusal_and_ticket_not_overriding_door_discretion','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820814/kremlin','https://www.tripadvisor.com/Attraction_Review-g186470-d596706-Reviews-Kremlin-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','polarised_institutional_queer_value_balanced_against_repeated_current_hostile_security_bar_and_couple_safety_reports','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1820814/kremlin','https://www.tripadvisor.com/Attraction_Review-g186470-d596706-Reviews-Kremlin-Belfast_Northern_Ireland.html','https://whereis.gay/listing/kremlin/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1586::bigint, jsonb_build_object(
      'queue_wait', 'The snug Church Lane rooms fill quickly after work and on weekend evenings. There is no dependable timed queue, but guests warn that cocktails can take a while when the bar is packed. Go before 7 pm for an easier seat, or reserve if the current channel allows it; the small scale is part of the charm.',
      'best_nights', 'Early evening is the sweet spot: enough hum for the hanging-lingerie room to feel playful, still enough space to taste the gin-led drinks. A weeknight suits a date; Friday and Saturday bring celebrations and noise. One-off cocktail sessions reward booking, but this is a bar-crawl stop, not a queer event anchor.',
      'crowd_mix', 'Shoppers, after-work locals, couples, birthday groups and visitors share the eccentric little rooms. The décor attracts a flamboyant, mixed audience, yet the venue does not present itself as an LGBTQ+ bar. Queer guests can blend into Cathedral Quarter nightlife without expecting community programming.',
      'dress_code', 'Wear whatever takes you from city wandering to cocktails: denim, boots, a bright shirt or date-night layers all fit. There is no published dress code and the room rewards wit more than polish. Keep bags compact because tables and passages are tight, and bring a rain layer if you hope to sit outside.',
      'staff_inclusivity', 'Recent summaries lean toward friendly bartenders, generous atmosphere and capable cocktail guidance, with some complaints about slow or uneven service when busy. No LGBTQ+ policy or queer-led programme was found. Treat it as an easy mixed bar with personality, not as a formally moderated safe space.',
      'venue_classification', 'active_quirky_small_church_lane_cocktail_bar_with_mixed_mainstream_crowd_and_no_verified_dedicated_lgbtq_identity',
      'source_urls', to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d1770521-Reviews-Muriel_s_Cafe_Bar-Belfast_Northern_Ireland.html','https://wanderlog.com/place/details/1186785/muriels-cafe-bar','https://restaurantguru.com/Muriels-Cafe-Bar-Belfast','https://www.belfastwhiskeyweek.com/products/classic-cocktails-after-dark-muriels-28-07-2026','https://minutes.belfastcity.gov.uk/documents/g12332/Public%20reports%20pack%2022nd-Apr-2026%2017.15%20Licensing%20Committee.pdf?T=10']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_small_busy_room_early_arrival_seating_and_slow_peak_cocktail_pattern_without_reliable_minute_range','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1186785/muriels-cafe-bar','https://restaurantguru.com/Muriels-Cafe-Bar-Belfast','https://www.reddit.com/r/northernireland/comments/126wb0g']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_early_evening_date_weekend_celebration_and_one_off_cocktail_event_context','source_urls',to_jsonb(array['https://restaurantguru.com/Muriels-Cafe-Bar-Belfast','https://www.belfastwhiskeyweek.com/products/classic-cocktails-after-dark-muriels-28-07-2026']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mixed_shopper_worker_couple_celebration_and_visitor_bar_without_queer_specific_programme','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d1770521-Reviews-Muriel_s_Cafe_Bar-Belfast_Northern_Ireland.html','https://wanderlog.com/place/details/1186785/muriels-cafe-bar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_quirky_compact_bar_and_outdoor_seating_context_without_published_code','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1186785/muriels-cafe-bar','https://restaurantguru.com/Muriels-Cafe-Bar-Belfast']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','generally_friendly_cocktail_service_with_busy_shift_variation_and_no_published_lgbtq_policy','source_urls',to_jsonb(array['https://restaurantguru.com/Muriels-Cafe-Bar-Belfast','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d1770521-Reviews-Muriel_s_Cafe_Bar-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1592::bigint, jsonb_build_object(
      'queue_wait', 'Browsing is drop-in, Wednesday to Sunday from 11 am to 8 pm, with no expected line. The room is small, so launches and workshops can fill and may use advance tickets. Use the current North Street address: an older official access page still points to the former mill and should not guide your journey.',
      'best_nights', 'Choose the specific reading, workshop or community gathering that speaks to you; those are the moments the shop becomes more than retail. For slow browsing and coffee, a weekday afternoon leaves more room to talk books. Sunday is useful for an unhurried visit, and you never have to buy something just to stay.',
      'crowd_mix', 'Trans and non-binary readers, queer teens and elders, writers, parents, allies and people searching for one very specific story all belong here. Belfast locals give the space its heartbeat, while visitors are welcomed without needing scene knowledge. It is community infrastructure first and a tourist stop second.',
      'dress_code', 'There is no performance test here: soft layers, pronoun pins, office clothes, full colour or a low-energy hoodie all fit. Come as you are and handle the small room gently. If noise or access is a concern, contact the shop before travelling because the published accessibility directions have not caught up with the move.',
      'staff_inclusivity', 'Queer ownership comes with practical care: a borrowable shelf without late fees, reading without buying, researched ordering help and low-cost access for community events. Reviews praise warm, knowledgeable staff. The stale access page is a real flaw, but the social welcome is unusually concrete.',
      'venue_classification', 'active_queer_owned_city_centre_bookshop_coffee_and_community_space_with_explicit_low_pressure_welcome_and_stale_official_access_directions',
      'identity_note', 'The current address is 162 North Street. The official accessibility page still describes the former third-floor Blackstaff Mill unit, so visitors needing step-free or sensory details should contact the shop for current North Street information.',
      'source_urls', to_jsonb(array['https://www.paperxclips.com/','https://www.paperxclips.com/faqs','https://www.paperxclips.com/accessibility','https://uk.bookshop.org/shop/paperxclips','https://qlist.app/venues/Belfast/Paperxclips-Books/SHJZUzgyODFhVWVVM3Y4am1xNVcrdw','https://www.reddit.com/r/Belfast/comments/1ry8oyl/best_independent_book_shops_in_belfast/','https://northbelfastfestival.com/wp-content/uploads/Look_North_2026_Brochure_FINAL_single_pages.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_drop_in_hours_small_event_capacity_and_current_address_conflict_with_stale_access_page','source_urls',to_jsonb(array['https://www.paperxclips.com/','https://www.paperxclips.com/accessibility','https://www.paperxclips.com/faqs']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_event_reading_workshop_weekday_browsing_sunday_and_no_purchase_required_context','source_urls',to_jsonb(array['https://www.paperxclips.com/','https://www.paperxclips.com/faqs','https://northbelfastfestival.com/wp-content/uploads/Look_North_2026_Brochure_FINAL_single_pages.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','explicit_trans_owned_intergenerational_queer_reader_writer_parent_ally_local_and_visitor_community','source_urls',to_jsonb(array['https://www.paperxclips.com/','https://uk.bookshop.org/shop/paperxclips','https://qlist.app/venues/Belfast/Paperxclips-Books/SHJZUzgyODFhVWVVM3Y4am1xNVcrdw']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','explicit_low_pressure_community_space_with_current_access_information_gap_after_move','source_urls',to_jsonb(array['https://www.paperxclips.com/','https://www.paperxclips.com/accessibility']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','concrete_borrowing_read_without_buying_ordering_and_low_cost_event_practices_plus_warm_staff_consensus','source_urls',to_jsonb(array['https://www.paperxclips.com/faqs','https://qlist.app/venues/Belfast/Paperxclips-Books/SHJZUzgyODFhVWVVM3Y4am1xNVcrdw','https://www.reddit.com/r/transgenderUK/comments/1i6tfhb']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1583::bigint, jsonb_build_object(
      'queue_wait', 'This compact lunch room is walk-in only. Recent diners report a real midday queue, especially on Saturday, while people arriving near noon often slip in before it forms. Aim for 11:30 am or after 2 pm, and expect a short table wait at peak rather than a booking system you can rely on.',
      'best_nights', 'There is no night programme: the café closes around 5 pm and Sunday is closed. Make it a weekday lunch for the calmer version, or arrive early Saturday before shoppers fill the arcade. Traditional plates, generous sandwiches and an Irish coffee are the draw; this is daytime fuel, not a queer evening destination.',
      'crowd_mix', 'Arcade shoppers, city workers, older regulars, couples, families and tourists make up the room. Local accents are common, but the central position keeps a healthy visitor share. Nothing suggests an LGBTQ+ venue or scene crowd; queer guests enter the same relaxed lunch mix as everyone else.',
      'dress_code', 'Shopping-day casual is exactly right: coats, trainers, office clothes and rain-ready layers all pass without comment. The surroundings look more ornate than the café feels. Keep bulky bags close in the narrow room and dress for comfort if you may wait in the arcade; no formal rule is published.',
      'staff_inclusivity', 'Current reviews usually praise personable, hardworking service and describe staff handling a difficult guest calmly, though some diners note loud language or inattentive moments. No LGBTQ+ policy or community role was found. Expect ordinary Belfast hospitality, with the usual variation of a busy small lunch shift.',
      'venue_classification', 'active_walk_in_daytime_arcade_cafe_bar_with_generous_lunches_mainstream_mixed_crowd_and_no_verified_lgbtq_specific_role',
      'source_urls', to_jsonb(array['https://www.queensarcadebelfast.com/stores/queens-cafe-bar/','https://visitbelfast.com/listing/queens-caf%C3%A9-bar/97527101/','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d3831086-Reviews-Queens_Cafe_Bar-Belfast_Northern_Ireland.html','https://restaurantguru.com/Queens-Cafe-bar-Belfast-2']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_walk_in_only_midday_saturday_queue_and_early_arrival_consensus','source_urls',to_jsonb(array['https://visitbelfast.com/listing/queens-caf%C3%A9-bar/97527101/','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d3831086-Reviews-Queens_Cafe_Bar-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_daytime_only_weekday_saturday_and_sunday_closed_context','source_urls',to_jsonb(array['https://www.queensarcadebelfast.com/stores/queens-cafe-bar/','https://visitbelfast.com/listing/queens-caf%C3%A9-bar/97527101/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_shopper_worker_regular_couple_family_and_tourist_lunch_mix_without_lgbtq_identity','source_urls',to_jsonb(array['https://www.queensarcadebelfast.com/stores/queens-cafe-bar/','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d3831086-Reviews-Queens_Cafe_Bar-Belfast_Northern_Ireland.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_arcade_lunch_and_compact_room_context_without_published_code','source_urls',to_jsonb(array['https://www.queensarcadebelfast.com/stores/queens-cafe-bar/','https://visitbelfast.com/listing/queens-caf%C3%A9-bar/97527101/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','generally_personable_hardworking_and_calm_service_with_some_busy_shift_variation_and_no_lgbtq_policy','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d3831086-Reviews-Queens_Cafe_Bar-Belfast_Northern_Ireland.html','https://restaurantguru.com/Queens-Cafe-bar-Belfast-2']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1589::bigint, jsonb_build_object(
      'queue_wait', 'The sit-in restaurant closed in June 2026, so old booking advice is obsolete. The owners said the original night hatch would remain, but no dependable post-change hours or wait were published. Check the same-day social update before joining the Union Street flow; late club exits can create a food surge.',
      'best_nights', 'If the hatch confirms service, Friday or Saturday after nearby bars is its natural moment: messy comfort food eaten standing up, not the former roast-dinner experience. Do not plan a seated date or Sunday lunch here. Treat the counter as a bonus at the end of a queer night, not the evening itself.',
      'crowd_mix', 'The former dining room drew loyal locals, couples, families and destination food fans; the hatch inherits late-night clubbers from Belfast’s queer strip. Expect LGBTQ+ regulars, allies and hungry passers-by in one takeaway line. It is queer-adjacent through location and ownership links, not a standalone social venue.',
      'dress_code', 'Night-out clothes are fine because this is now a street-food stop: clubwear, drag, denim and trainers all belong at the hatch. Bring a layer for waiting outside and choose something that can survive sauce. There is no door code, but respectful queue behaviour matters when several venues empty at once.',
      'staff_inclusivity', 'Before closure, guests warmly praised the owners and team for kindness, vegan flexibility and looking after fussy eaters. Community grief at the announcement supports that reputation. The hatch may use a different shift, so carry the warmth forward as history, not a guarantee of identical service.',
      'venue_classification', 'partially_closed_former_queer_quarter_sit_in_restaurant_with_night_hatch_announced_to_continue_and_post_change_hours_unverified',
      'record_status', 'editorial_hold_hide_restaurant_booking_keep_only_as_unverified_night_hatch_until_current_hours_are_confirmed',
      'identity_note', 'The sit-in restaurant closed in June 2026. Owners announced that the original night hatch would remain open, but the active hours and menu after the transition require direct verification.',
      'source_urls', to_jsonb(array['https://www.belfasttelegraph.co.uk/area/belfast/popular-belfast-city-centre-restaurant-to-close-as-owners-announce-decision-with-a-heavy-heart/a/157586365.html','https://evoke.ie/2026/06/25/food/restaurants/spaghetti-arms-restaurant','https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d23751981-Reviews-Spaghetti_Arms_Restaurant-Belfast_Northern_Ireland.html','https://restaurantguru.com/Spaghetti-Arms-Belfast','https://belfast.gaycities.com/restaurants/312487-spaghetti-arms','https://greatplacenorthbelfast.com/wp-content/uploads/2026/06/Place-Shaping-Plan-Donegall-Street-Full-Report-launch-3-June-2026.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','confirmed_june_2026_sit_in_closure_and_hatch_continuation_without_verified_post_change_hours_or_wait','source_urls',to_jsonb(array['https://www.belfasttelegraph.co.uk/area/belfast/popular-belfast-city-centre-restaurant-to-close-as-owners-announce-decision-with-a-heavy-heart/a/157586365.html','https://evoke.ie/2026/06/25/food/restaurants/spaghetti-arms-restaurant']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','surviving_night_hatch_queer_quarter_weekend_exit_context_not_former_seated_dining','source_urls',to_jsonb(array['https://evoke.ie/2026/06/25/food/restaurants/spaghetti-arms-restaurant','https://belfast.gaycities.com/restaurants/312487-spaghetti-arms']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_local_couple_family_food_fan_mix_and_current_hatch_exposure_to_queer_strip_clubbers','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d23751981-Reviews-Spaghetti_Arms_Restaurant-Belfast_Northern_Ireland.html','https://greatplacenorthbelfast.com/wp-content/uploads/2026/06/Place-Shaping-Plan-Donegall-Street-Full-Report-launch-3-June-2026.pdf','https://belfast.gaycities.com/restaurants/312487-spaghetti-arms']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','street_hatch_clubwear_outdoor_wait_and_queer_night_exit_context_without_door_code','source_urls',to_jsonb(array['https://belfast.gaycities.com/restaurants/312487-spaghetti-arms','https://evoke.ie/2026/06/25/food/restaurants/spaghetti-arms-restaurant']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','exceptionally_warm_pre_closure_service_vegan_flexibility_and_community_reputation_not_yet_verified_for_new_hatch_only_operation','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Restaurant_Review-g186470-d23751981-Reviews-Spaghetti_Arms_Restaurant-Belfast_Northern_Ireland.html','https://restaurantguru.com/Spaghetti-Arms-Belfast','https://evoke.ie/2026/06/25/food/restaurants/spaghetti-arms-restaurant']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1579,1591,1590,1584,1586,1592,1583,1589)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
