-- Queer Atlas venue intelligence: global review-led editorial pass, batch 36.
-- Eight remaining Berlin records, individually researched and rewritten.
-- B:EAST, Cafe Fatal and Capture are held from active recommendations until a dated new event or reopening is verified.
-- Current operating evidence overrides older closure rumours for Ficken 3000.
-- Checked 2026-08-06. Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1064::bigint, jsonb_build_object(
      'queue_wait', 'Do not travel for this name without a dated ticket. The latest listing describes the large multi-floor rave but shows no event; its producer now foregrounds other 2026 parties and a 2027 Easter weekend. When it returns, advance tickets and early arrival are wiser than gambling on a host-club door line.',
      'best_nights', 'There is no verified next B:EAST night to recommend. Historically it worked as a special-event techno blowout rather than a weekly club: two dance floors, a large play zone and an overnight finish. Follow the producer, confirm the exact host venue and date, then judge that edition on its lineup—not on an old pin.',
      'crowd_mix', 'The concept is multisexual: LGBTQ+ ravers, open-minded friends, gay men, queer women and a young techno crowd rather than a single-gender sex party. Host-venue reviews describe many shirtless men alongside women and tourists. No present crowd exists until a new B:EAST date is actually announced.',
      'dress_code', 'Past editions invited expressive, body-positive ravewear without the narrow men-only rule used by some sister events. Mesh, harnesses, sportswear, colour and comfortable dance shoes fit the concept. For any return, read that ticket page from scratch: venue, play-space policy and door expectations can all change.',
      'staff_inclusivity', 'The producer frames the series around equality and freedom, while the former host venue receives mixed reports on security, crowding, cleanliness and bar waits. That is not enough to score a future edition. Inclusion must be reassessed against the named host, door team and awareness policy when a real date appears.',
      'venue_classification', 'event_series_without_current_dated_beast_edition_formerly_multisexual_large_scale_techno_rave_with_play_area',
      'record_status', 'editorial_hold_hide_from_active_events_until_new_dated_official_beast_ticket_and_host_venue_are_verified',
      'source_urls', to_jsonb(array['https://pinksider.com/berlin/clubs-bars/b65/beast-party-berlin/','https://revolverparty2024.live-website.com/about/','https://pinksider.com/en/berlin/cruising-fun/sexpositive-partys/','https://wanderlog.com/place/details/2593010/club-ost','https://www.berlin.de/clubs-und-party/clubguide/8871804-2857960-ost.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_current_dated_beast_event_with_historic_ticket_and_former_host_queue_context','source_urls',to_jsonb(array['https://pinksider.com/berlin/clubs-bars/b65/beast-party-berlin/','https://revolverparty2024.live-website.com/about/','https://wanderlog.com/place/details/2593010/club-ost']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_special_event_multi_floor_techno_play_area_format_without_verified_next_edition','source_urls',to_jsonb(array['https://pinksider.com/berlin/clubs-bars/b65/beast-party-berlin/','https://pinksider.com/en/berlin/cruising-fun/sexpositive-partys/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_multisexual_lgbtq_friend_gay_male_queer_women_and_young_techno_mix_without_present_crowd','source_urls',to_jsonb(array['https://pinksider.com/berlin/clubs-bars/b65/beast-party-berlin/','https://wanderlog.com/place/details/2593010/club-ost']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_expressive_multisexual_ravewear_context_requiring_new_ticket_specific_verification','source_urls',to_jsonb(array['https://revolverparty2024.live-website.com/about/','https://pinksider.com/berlin/clubs-bars/b65/beast-party-berlin/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','producer_equality_claim_balanced_against_mixed_former_host_security_cleanliness_and_crowding_reviews_not_transferable_to_future_edition','source_urls',to_jsonb(array['https://revolverparty2024.live-website.com/about/','https://wanderlog.com/place/details/2593010/club-ost']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1108::bigint, jsonb_build_object(
      'queue_wait', 'The basement is tiny, so the practical wait is for bar space and a drink rather than a long formal queue. Arrive before midnight if you want a seat or a real conversation; weekend DJ nights compress quickly. Current reports are split between fast, affectionate service and visitors being passed over at the bar.',
      'best_nights', 'Friday or Saturday gives the disco-ball version: DJs, packed bodies and a useful launch into a longer Mitte night. Choose a weekday for strawberry daiquiris and actual flirting across the room. This is best as a first or last stop, not an all-night mega-club; check the current event post before crossing town.',
      'crowd_mix', 'Mitte queer regulars, gay men, mixed LGBTQ+ friend groups, expats and tourists fill a room small enough to change character with ten arrivals. It feels intimate and visibly queer, with more neighbourhood warmth than circuit scale. Visitors are common, though regulars can receive attention faster on a busy shift.',
      'dress_code', 'There is no published gatekeeping uniform. Black denim, a tiny top, office clothes loosened after work, vintage sparkle or polished trainers all fit under the oversized disco ball. Dress for a close, warm basement and bring little baggage; individuality matters more than performing a standard Berlin-techno costume.',
      'staff_inclusivity', 'Many 2026 guests call the team lovely, personal and genuinely welcoming, while one visitor of colour felt selectively ignored as others were served first. That specific account matters beside the praise. Most nights sound warm, but the service record is not universal; speak up or leave if the bar pattern feels wrong.',
      'venue_classification', 'active_tiny_mitte_queer_basement_bar_with_djs_cocktails_intimate_mixed_crowd_and_one_material_current_selective_service_report',
      'source_urls', to_jsonb(array['https://www.gayout.com/europe/germany/berlin/bars/betty-f-bar-1915','https://wanderlog.com/place/details/2452281/betty-f-bar','https://whereis.gay/listing/betty-f/','https://www.theinfatuation.com/berlin/reviews/betty-f','https://www.reddit.com/r/berlinsocialclub/comments/1rvzbb2/lgbtqia_bars/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_tiny_basement_weekend_compression_and_polarised_bar_service_pattern_without_timed_queue','source_urls',to_jsonb(array['https://www.gayout.com/europe/germany/berlin/bars/betty-f-bar-1915','https://wanderlog.com/place/details/2452281/betty-f-bar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_weekend_dj_disco_energy_and_weekday_cocktail_conversation_use','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2452281/betty-f-bar','https://www.theinfatuation.com/berlin/reviews/betty-f']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_mitte_queer_regular_gay_male_mixed_friend_expat_and_tourist_crowd','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2452281/betty-f-bar','https://whereis.gay/listing/betty-f/','https://www.reddit.com/r/berlinsocialclub/comments/1rvzbb2/lgbtqia_bars/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_intimate_disco_basement_context_without_published_code','source_urls',to_jsonb(array['https://www.theinfatuation.com/berlin/reviews/betty-f','https://wanderlog.com/place/details/2452281/betty-f-bar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_current_warm_personal_service_consensus_balanced_against_specific_person_of_colour_selective_service_report','source_urls',to_jsonb(array['https://www.gayout.com/europe/germany/berlin/bars/betty-f-bar-1915','https://whereis.gay/listing/betty-f/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1099::bigint, jsonb_build_object(
      'queue_wait', 'This is a compact local pub, not a velvet-rope club. Early evening usually means immediate service; the room tightens when regulars gather, especially at weekends. There is no reliable minute-based queue pattern. If every stool is taken, patience and a friendly hello work better than hovering.',
      'best_nights', 'Wednesday has historically carried the half-price-until-midnight pull, while Friday and Saturday bring the fuller bear-bar atmosphere. Go earlier for conversation and later for louder 1970s-to-now pop. Sunday is commonly listed closed, so confirm hours before travelling across Berlin for a quiet neighbourhood nightcap.',
      'crowd_mix', 'Bears, cubs, otters, admirers and older gay regulars form the centre, with all ages and body sizes explicitly welcomed. The Prenzlauer Berg location keeps it more local and less tourist-saturated than Schöneberg. Visitors who enjoy conversation can fold in; this is a bar for people, not posing.',
      'dress_code', 'Come comfortable and recognisably yourself: jeans, plaid, leather, a bear tee, workwear or ordinary street clothes all belong. There is no fetish mandate or beauty standard, and the room explicitly welcomes varied ages and sizes. Indoor smoke may matter more than style, so choose washable layers.',
      'staff_inclusivity', 'Long-running accounts emphasise kind bartenders, cheap drinks, easy conversation and welcome across body types. Evidence is thinner than for tourist-heavy bars, so avoid turning warmth into perfection. Its strongest inclusion signal is a durable bear-community identity since 1999.',
      'venue_classification', 'active_long_running_prenzlauer_berg_bear_bar_with_local_conversational_crowd_body_size_welcome_and_limited_recent_review_volume',
      'source_urls', to_jsonb(array['https://de.travelgay.com/berlin-gay-bars','https://berlin.gaycities.com/bars/1472-b%C3%A4renh%C3%B6hle','https://whereis.gay/barenhohle-2','https://www.pankow-weissensee-prenzlauerberg.berlin/system/files/document/Pocket%20Guide%20Queeres%20Leben_ENG%20WEB.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_local_pub_early_service_regular_peak_and_no_reliable_timed_queue_pattern','source_urls',to_jsonb(array['https://berlin.gaycities.com/bars/1472-b%C3%A4renh%C3%B6hle','https://whereis.gay/barenhohle-2']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','listed_wednesday_discount_weekend_bear_bar_peak_and_sunday_closure_context','source_urls',to_jsonb(array['https://de.travelgay.com/berlin-gay-bars','https://berlin.gaycities.com/bars/1472-b%C3%A4renh%C3%B6hle']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','explicit_bear_cub_otter_admirer_older_regular_all_age_and_body_size_local_crowd','source_urls',to_jsonb(array['https://de.travelgay.com/berlin-gay-bars','https://berlin.gaycities.com/bars/1472-b%C3%A4renh%C3%B6hle','https://whereis.gay/barenhohle-2']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_bear_pub_body_size_welcome_and_smoking_context_without_fetish_mandate','source_urls',to_jsonb(array['https://de.travelgay.com/berlin-gay-bars','https://berlin.gaycities.com/bars/1472-b%C3%A4renh%C3%B6hle']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','consistent_friendly_bartender_value_conversation_and_body_inclusion_reputation_with_low_recent_review_volume','source_urls',to_jsonb(array['https://berlin.gaycities.com/bars/1472-b%C3%A4renh%C3%B6hle','https://whereis.gay/barenhohle-2']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (963::bigint, jsonb_build_object(
      'queue_wait', 'Do not assume the historic Sunday tea dance is running. Current queer guides still describe it, but the official 2026 ticket calendar shows many other events and no dated Café Fatal edition. Until the venue publishes a fresh ticket or programme entry, there is no honest queue, door time or admission price to give.',
      'best_nights', 'Historically Sunday began with an hour of ballroom instruction, then standard, Latin, rock, pop and Schlager for gays, lesbians and friends. That format is distinctive, but not a current recommendation without a new date. Use the official calendar and choose another named queer event if it stays absent.',
      'crowd_mix', 'The long-running concept brought gay men, lesbians, queer couples, straight friends, beginners and experienced ballroom dancers into one intergenerational room. There is no verified present-day crowd. Do not convert a beloved history dating to 1995 into a promise that the same community still meets this Sunday.',
      'dress_code', 'The old format called for shoes you can turn in, breathable layers and a little Sunday sparkle—not fetishwear or techno camouflage. If a revival is announced, check floor rules and bring proper dance shoes if requested. For now, no outfit advice should imply that an unlisted event is operating.',
      'staff_inclusivity', 'The concept has a strong inclusive legacy and its host remains an active queer and political cultural venue, but current staff practice for Café Fatal cannot be scored while no 2026 date is published. A revival should be reassessed for access, teaching language, partner rotation and door handling before endorsement.',
      'venue_classification', 'historic_sunday_queer_ballroom_and_pop_tea_dance_at_active_host_venue_without_current_officially_dated_2026_edition',
      'record_status', 'editorial_hold_hide_from_active_events_until_new_official_cafe_fatal_date_is_published',
      'source_urls', to_jsonb(array['https://www.so36.com/tickets','https://www.so36.com/produkte','https://www.travelgay.com/venue/cafe-fatal','https://pinksider.com/en/berlin/clubs-bars/b786/cafe-fatal-so36/','https://de.wikipedia.org/wiki/SO36']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','historic_directory_listing_conflicts_with_absence_from_current_official_2026_ticket_calendar','source_urls',to_jsonb(array['https://www.so36.com/tickets','https://www.so36.com/produkte','https://www.travelgay.com/venue/cafe-fatal']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_sunday_one_hour_ballroom_lesson_then_multigenre_dance_without_current_date','source_urls',to_jsonb(array['https://www.travelgay.com/venue/cafe-fatal','https://de.wikipedia.org/wiki/SO36']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_intergenerational_gay_lesbian_queer_friend_beginner_and_ballroom_dancer_mix_without_present_crowd','source_urls',to_jsonb(array['https://www.travelgay.com/venue/cafe-fatal','https://de.wikipedia.org/wiki/SO36']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_ballroom_shoe_breathable_sunday_party_context_not_current_operating_advice','source_urls',to_jsonb(array['https://pinksider.com/en/berlin/clubs-bars/b786/cafe-fatal-so36/','https://de.wikipedia.org/wiki/SO36']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_host_queer_legacy_but_no_current_event_specific_staff_access_teaching_or_door_evidence','source_urls',to_jsonb(array['https://www.so36.com/tickets','https://de.wikipedia.org/wiki/SO36']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1107::bigint, jsonb_build_object(
      'queue_wait', 'Do not head to Wühlischstraße expecting an open bar. One current specialist listing shows every day closed, while the readable profiles and reviews describe the 2019–20 launch rather than a 2026 operation. No recent official schedule or reopening notice was found, so there is no defensible current wait estimate.',
      'best_nights', 'There is no verified active night. The former bar was built for relaxed conversation that could turn into a small DJ dance floor, with occasional art and mixed-queer events. Keep that history in the archive, but choose a venue with a dated current programme rather than relying on an old “weekend” recommendation.',
      'crowd_mix', 'At launch, gay men, Turkish and migrant queer guests, alternative LGBTQ+ groups and friends were intentionally invited into a diverse Friedrichshain room. That ambition mattered, but it cannot describe a crowd today. An inactive or unverified listing has no locals-versus-tourists ratio to report.',
      'dress_code', 'Not applicable while operation is unverified. The old mood was easy neighbourhood barwear—denim, tees, colour and whatever let you move if a DJ started—but no outfit turns an outdated listing into an open door. Any successor at the address needs a fresh identity and policy check.',
      'staff_inclusivity', 'The founder explicitly wanted a broad welcome, including more Turkish gay men and lesbians, and early coverage praised unusually friendly staff. Those are valuable historical signals, not evidence about a 2026 team. Do not publish a current inclusion score until an operator, hours and staffed event are confirmed.',
      'venue_classification', 'apparently_inactive_former_friedrichshain_gay_bar_with_historic_migrant_queer_inclusion_and_no_verified_2026_operation',
      'record_status', 'editorial_hold_hide_from_active_results_until_current_operator_hours_and_reopening_are_directly_verified',
      'source_urls', to_jsonb(array['https://de.travelgay.com/venue/capture-bar','https://www.the-berliner.com/politics/capture-bar/','https://www.siegessaeule.de/magazin/4470-ich-w%C3%BCrde-mich-freuen-wenn-vermehrt-t%C3%BCrkische-schwule-und-lesben-vorbei-kommen/','https://www.tagesspiegel.de/gesellschaft/queerspiegel/friedrichshain-hat-noch-queeres-potenzial-5024938.html','https://pinksider.com/en/berlin/clubs-bars/b527/capture-bar/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_all_days_closed_listing_and_no_recent_official_schedule_against_old_launch_coverage','source_urls',to_jsonb(array['https://de.travelgay.com/venue/capture-bar','https://www.the-berliner.com/politics/capture-bar/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_conversation_dj_art_and_mixed_queer_event_format_without_verified_active_night','source_urls',to_jsonb(array['https://www.the-berliner.com/politics/capture-bar/','https://pinksider.com/en/berlin/clubs-bars/b527/capture-bar/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_gay_turkish_migrant_alternative_lgbtq_and_friend_mix_without_current_crowd','source_urls',to_jsonb(array['https://www.siegessaeule.de/magazin/4470-ich-w%C3%BCrde-mich-freuen-wenn-vermehrt-t%C3%BCrkische-schwule-und-lesben-vorbei-kommen/','https://www.tagesspiegel.de/gesellschaft/queerspiegel/friedrichshain-hat-noch-queeres-potenzial-5024938.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_informal_neighbourhood_bar_context_not_applicable_to_unverified_operation','source_urls',to_jsonb(array['https://www.the-berliner.com/politics/capture-bar/','https://pinksider.com/en/berlin/clubs-bars/b527/capture-bar/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','explicit_historic_migrant_queer_welcome_and_friendly_staff_coverage_without_current_operator_or_team','source_urls',to_jsonb(array['https://www.siegessaeule.de/magazin/4470-ich-w%C3%BCrde-mich-freuen-wenn-vermehrt-t%C3%BCrkische-schwule-und-lesben-vorbei-kommen/','https://www.the-berliner.com/politics/capture-bar/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (965::bigint, jsonb_build_object(
      'queue_wait', 'Entry depends on the specific party and its audience, not a generic club night. Published base charges run from €15–€28 plus a €7–€10 minimum bar spend; weekends vary. Bring cash only, read the gender icons and arrive within the listed window. The door checks whether you fit that night’s safer-space brief.',
      'best_nights', 'Monday is naked men-only, Tuesday centres trans guests while remaining open to all, Wednesday rotates men’s themes, Thursday is mixed, and later-week events vary. Pick the exact sexual format you want, not merely the weekday. The programme matters more than DJ prestige; this is a play club with light electronic music.',
      'crowd_mix', 'The calendar moves between gay men, trans guests, lesbians, straight and flexible visitors, mixed kink communities, newcomers and experienced players. Some nights exclude by design to protect a specific encounter. Read the icon as the kind of contact the event supports, not a simplistic label imposed on your identity.',
      'dress_code', 'Street clothes go into the cloakroom; arrive in the announced fetish, naked or theme look, or bring it and change inside. Cash is essential. Free condoms, lubricant and gloves are available, and valuables can be left at the bar. Fantasy is welcome, but the individual event description outranks improvisation.',
      'staff_inclusivity', 'The team publishes an awareness role, free safer-sex supplies and zero tolerance for demeaning behaviour. A serious recent account says a disabled guest was refused because staff deemed stairs impossible. Sexual diversity is explicit; disability inclusion and access communication need urgent improvement.',
      'venue_classification', 'active_multi_orientation_sex_positive_play_club_with_event_specific_access_cash_only_policy_awareness_team_and_material_disability_access_concern',
      'source_urls', to_jsonb(array['https://www.club-culture-houze.de/der-club/','https://www.club-culture-houze.de/programm/','https://www.club-culture-houze.de/preise/','https://www.club-culture-houze.de/Veranstaltung/naked-together/','https://www.gayout.com/europe/germany/berlin/bars/club-culture-houze-1954','https://www.joyclub.de/club/veranstaltungen/1710896.club_culture_houze.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_event_specific_entry_cash_only_base_charge_minimum_spend_gender_icon_and_door_fit_policy','source_urls',to_jsonb(array['https://www.club-culture-houze.de/preise/','https://www.club-culture-houze.de/der-club/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_monday_naked_men_tuesday_trans_open_wednesday_men_thursday_mixed_and_variable_weekend_programme','source_urls',to_jsonb(array['https://www.club-culture-houze.de/preise/','https://www.club-culture-houze.de/programm/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','explicit_gay_trans_lesbian_straight_flexible_mixed_newcomer_and_experienced_event_specific_audiences','source_urls',to_jsonb(array['https://www.club-culture-houze.de/der-club/','https://www.club-culture-houze.de/preise/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','current_event_specific_fetish_naked_or_theme_code_cloakroom_cash_and_free_safer_sex_supply_evidence','source_urls',to_jsonb(array['https://www.club-culture-houze.de/der-club/','https://www.club-culture-houze.de/Veranstaltung/naked-together/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','published_awareness_and_anti_exclusion_practice_balanced_against_specific_recent_ableist_door_incident_report','source_urls',to_jsonb(array['https://www.club-culture-houze.de/der-club/','https://www.gayout.com/europe/germany/berlin/bars/club-culture-houze-1954']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1101::bigint, jsonb_build_object(
      'queue_wait', 'Early drinks usually mean quick service and the leafy terrace adds space in warm weather. Later, the compact smoking bar can tighten around karaoke or regulars, but current accounts do not support a long formal line. Go before 9 pm for a seat; expect smoke indoors once the outside becomes too cold.',
      'best_nights', 'Karaoke is the social catalyst, while a summer evening on the tucked-away terrace gives the bar its gentlest charm. Visit late for one last Schöneberg drink or earlier if you want to meet the neighbourhood. It opens daily into the small hours, so the right night depends more on weather and event than weekday hype.',
      'crowd_mix', 'Older gay men and Schöneberg regulars anchor the room, joined by couples, neighbours and visitors from the hotel opposite. The audience is more mature and conversational than a dance club, but not closed to younger guests or women. Local familiarity is visible without making every tourist feel like an intruder.',
      'dress_code', 'Neighbourhood-bar comfort is enough: jeans, a polo, leather jacket, knitwear or everyday street clothes. Karaoke welcomes a little flourish, but there is no fetish or fashion demand. Choose washable layers if smoke bothers you and a warmer outer layer if the terrace is the only breathable seat on a cold night.',
      'staff_inclusivity', 'Recent reports often praise trained, friendly staff and a living-room welcome for locals and city visitors. A smaller group describes rude service, especially toward non-German guests. The overall tone is warm but not flawless; basic German helps, and the terrace offers an easy reset if the indoor shift feels brusque.',
      'venue_classification', 'active_long_running_mature_schoeneberg_gay_neighbourhood_smoking_bar_with_karaoke_terrace_and_generally_warm_but_mixed_service_reports',
      'source_urls', to_jsonb(array['https://www.tripadvisor.de/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html','https://www.tripadvisor.com/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html','https://www.travelgay.com/venue/der-neue-oldtimer','https://oldergay.men/places/der-neue-oldtimer']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_early_quick_service_terrace_capacity_karaoke_regular_peak_and_indoor_smoke_pattern','source_urls',to_jsonb(array['https://www.tripadvisor.de/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html','https://www.travelgay.com/venue/der-neue-oldtimer']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_karaoke_summer_terrace_late_nightcap_daily_open_and_weather_led_use','source_urls',to_jsonb(array['https://www.tripadvisor.de/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html','https://www.travelgay.com/venue/der-neue-oldtimer']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mature_gay_regular_couple_neighbour_and_nearby_hotel_visitor_mix','source_urls',to_jsonb(array['https://oldergay.men/places/der-neue-oldtimer','https://www.tripadvisor.com/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_neighbourhood_karaoke_terrace_and_smoking_bar_context_without_fashion_code','source_urls',to_jsonb(array['https://www.tripadvisor.de/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html','https://www.travelgay.com/venue/der-neue-oldtimer']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','mostly_warm_professional_living_room_service_consensus_balanced_against_smaller_non_german_guest_rudeness_pattern','source_urls',to_jsonb(array['https://www.tripadvisor.de/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html','https://www.tripadvisor.com/Attraction_Review-g187323-d5947257-Reviews-Der_Neue_Oldtimer-Berlin.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (966::bigint, jsonb_build_object(
      'queue_wait', 'Current 2026 reports confirm the Urbanstraße bar still operates despite older lease rumours. Entry varies by event, with guests quoting roughly €10–€15; late nights can pack bar and basement. Check the same-day post, bring cash and arrive before the downstairs dance floor and darkroom fill.',
      'best_nights', 'Follow the rotating theme or DJ. A busy Friday or Saturday gives the notorious upstairs-bar, downstairs-dance-and-cruise blend; a quieter weeknight is easier for a drink and looking around. Choose an audience that fits you, because the balance can swing from gay cruising to broadly mixed queer.',
      'crowd_mix', 'Gay men remain central, joined by queer friends, sex-positive straight guests, locals, expats and tourists. Some enjoy the diversity; others resent straight spectators mocking queer people in the darkroom. It is no longer a sealed male enclave, and respect for cruising culture matters more than labels.',
      'dress_code', 'No single fetish uniform applies every night. Dark streetwear, mesh, leather, underwear layers and solid dancing shoes all work, but read the theme before stripping down. Pack light, expect smoke and close quarters, protect valuables and never treat the darkroom as a spectacle. Consent outranks costume.',
      'staff_inclusivity', 'Friendly bartenders and an open atmosphere still earn praise, including a returned lost wallet. Against that sit complaints about rude staff, dirt, ventilation and straight guests ridiculing queer play. The venue remains culturally queer, but staff must protect the darkroom from spectators more consistently.',
      'venue_classification', 'active_legendary_urbanstrasse_queer_cruising_bar_with_basement_darkroom_djs_mixed_audience_and_material_smoke_cleanliness_and_spectator_concerns',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/2222549/ficken-3000','https://qlist.app/venues/Berlin/FUCK-3000/eGE4UFVZSVcwZkMyYnJRTk1rNm0xZw','https://www.gayplaces.co/city/berlin/bar/ficken-3000','https://www.corner.inc/place/p6SADShR6Jvu','https://speisekarte.menu/restaurants/berlin/ficken-3000/reviews','https://www.reddit.com/r/AskGaybrosOver30/comments/1nf50bm/single_gay_american_i_know_i_know_were_cooked/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','confirmed_current_operation_variable_event_entry_and_late_bar_dancefloor_darkroom_crowding','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2222549/ficken-3000','https://qlist.app/venues/Berlin/FUCK-3000/eGE4UFVZSVcwZkMyYnJRTk1rNm0xZw','https://www.corner.inc/place/p6SADShR6Jvu']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_rotating_theme_dj_weekend_peak_and_quieter_weeknight_pattern','source_urls',to_jsonb(array['https://www.gayplaces.co/city/berlin/bar/ficken-3000','https://wanderlog.com/place/details/2222549/ficken-3000','https://qlist.app/venues/Berlin/FUCK-3000/eGE4UFVZSVcwZkMyYnJRTk1rNm0xZw']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','current_gay_male_core_mixed_queer_straight_sex_positive_local_expat_tourist_mix_with_spectator_tension','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2222549/ficken-3000','https://qlist.app/venues/Berlin/FUCK-3000/eGE4UFVZSVcwZkMyYnJRTk1rNm0xZw']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','theme_specific_dark_streetwear_mesh_leather_underwear_smoke_close_quarters_and_consent_context','source_urls',to_jsonb(array['https://www.gayplaces.co/city/berlin/bar/ficken-3000','https://wanderlog.com/place/details/2222549/ficken-3000']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_bartender_open_atmosphere_and_lost_property_praise_balanced_against_staff_cleanliness_ventilation_and_darkroom_spectator_complaints','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2222549/ficken-3000','https://speisekarte.menu/restaurants/berlin/ficken-3000/reviews','https://www.reddit.com/r/Berghain_Community/comments/1guekmm/to_the_girl_who_stopped_me_near_berghain_bar/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1064,1108,1099,963,1107,965,1101,966)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
