-- Queer Atlas venue intelligence: global review-led editorial pass, batch 61.
-- Seven Cologne records and one Copenhagen record checked against current official pages, local reporting, listings and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, never in reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (242::bigint, jsonb_build_object(
      'queue_wait','Early cocktails are relaxed; later on Friday, Saturday, Carnival and Pride the tables move and a compact dance crowd forms. The narrow Schaafenstraße setting can create a short door and slower drinks rather than a huge club line. Arrive before the DJ peak if conversation or a seat matters.','best_nights','Friday and Saturday deliver the lounge-to-dance transformation, while karaoke and special parties add a more participatory night. Earlier weeknights suit serious cocktails without the crush. Pride and Carnival are maximum-energy dates; check the current post because programming is not identical each week.','crowd_mix','Gay men, lesbians, trans and non-binary guests, queer friendship groups, straight companions and visitors all appear, with local recommendations often calling it one of the street’s broader rooms. The balance shifts later toward dancing and younger groups, but cocktails keep an intergenerational social layer.','dress_code','Smart casual with personality works: trainers, a good shirt, denim, dresses or expressive queer nightlife looks. No formal code is published. The room becomes close once tables move, so travel light and use the street cloakroom on major weekends rather than guarding a heavy coat.','staff_inclusivity','The official city guide highlights friendly staff, and queer recommendations often point mixed-gender groups toward Iron. Reviews vary around busy-night speed and individual interactions. Its consensus is broader than several neighbours, but guests should flag any problem rather than treating that as guaranteed.','venue_classification','active_lgbtq_cocktail_lounge_on_cologne_schaafenstrasse_with_house_drinks_weekend_dj_lounge_to_dance_transition_broad_queer_and_ally_mix_and_generally_positive_mixed_gender_staff_welcome_consensus','identity_note','Iron Cocktail Lounge is an LGBTQ+ cocktail bar with a comparatively broad queer crowd, not a men-only venue.','source_urls',to_jsonb(array['https://iron-bar.com/','https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://www.tripadvisor.co.uk/Restaurant_Review-g187371-d10186322-Reviews-Iron_Cocktail_Lounge-Cologne_North_Rhine_Westphalia.html','https://www.gayplaces.co/city/cologne/bar/iron-cocktail-lounge']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','early_lounge_ease_with_weekend_pride_carnival_compact_door_and_bar_pressure','source_urls',to_jsonb(array['https://iron-bar.com/','https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','friday_saturday_lounge_to_dance_karaoke_special_party_and_quieter_weeknight_cocktail_variation','source_urls',to_jsonb(array['https://iron-bar.com/','https://www.gayplaces.co/city/cologne/bar/iron-cocktail-lounge']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','broad_gay_lesbian_trans_nonbinary_queer_friend_ally_local_and_visitor_mix','source_urls',to_jsonb(array['https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://www.gayplaces.co/city/cologne/bar/iron-cocktail-lounge']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','personality_led_smart_casual_without_formal_code_and_crowded_room_cloakroom_practicality','source_urls',to_jsonb(array['https://iron-bar.com/','https://www.tripadvisor.co.uk/Restaurant_Review-g187371-d10186322-Reviews-Iron_Cocktail_Lounge-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','official_friendly_staff_signal_and_local_broad_mixed_gender_recommendations_with_busy_shift_variation','source_urls',to_jsonb(array['https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://www.tripadvisor.co.uk/Restaurant_Review-g187371-d10186322-Reviews-Iron_Cocktail_Lounge-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1823::bigint, jsonb_build_object(
      'queue_wait','This small family-run boutique hotel has limited rooms, so availability matters more than a lobby line. Confirm after-hours arrival because access can require contact, and reserve breakfast if offered with your rate. Pride, Carnival and fair dates reward early booking; there is no nightlife door.','best_nights','A weekend puts the Belgian Quarter, Neumarkt and queer nightlife within walking distance, while a weekday makes the intimate, residential atmosphere quieter. Breakfast and a balcony room are the property pleasures. It has no recurring party programme, so let the surrounding city define the evening.','crowd_mix','Couples, solo city-break guests, small families, creatives and business travellers form a personal, international mix. LGBTQ+ couples are part of the mainstream boutique clientele rather than a separate scene. Its small scale feels domestic and independent, not like a chain or social hostel.','dress_code','Relaxed design-conscious citywear fits: trainers, denim and a smarter dinner layer. There is no dress gate. Some rooms include kitchenettes or balconies, so pack for a lived-in city stay; comfortable shoes matter more than polish when walking between the hotel and nightlife.','staff_inclusivity','Recent verified reviews praise warm, attentive, family-style care, safety for solo travellers, cleanliness and help. No explicit LGBTQ+ training or policy was found, so describe it as excellent general hospitality. Communicate arrival, bedding and accessibility needs directly because staffing is intimate.','venue_classification','active_small_family_run_cologne_boutique_hotel_near_neumarkt_belgian_quarter_and_queer_nightlife_with_individual_rooms_apartments_breakfast_international_citybreak_mix_and_exceptionally_warm_staff_consensus','identity_note','Maison Marsil is an independent mainstream boutique hotel near Cologne’s queer scene, not an LGBTQ+-specific hotel.','source_urls',to_jsonb(array['https://www.maison-marsil.de/','https://www.booking.com/reviews/de/hotel/marsil.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g187371-d679482-Reviews-Maison_Marsil-Cologne_North_Rhine_Westphalia.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','limited_inventory_afterhours_contact_breakfast_and_major_event_advance_booking_without_nightlife_queue','source_urls',to_jsonb(array['https://www.maison-marsil.de/','https://www.booking.com/reviews/de/hotel/marsil.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_neighbourhood_access_and_quiet_weekday_boutique_stay_without_inhouse_party_programme','source_urls',to_jsonb(array['https://www.maison-marsil.de/','https://www.tripadvisor.com/Hotel_Review-g187371-d679482-Reviews-Maison_Marsil-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','couple_solo_family_creative_business_and_lgbtq_mainstream_boutique_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/de/hotel/marsil.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g187371-d679482-Reviews-Maison_Marsil-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','relaxed_design_citywear_without_gate_and_walkable_neighbourhood_practicality','source_urls',to_jsonb(array['https://www.maison-marsil.de/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','exceptional_warm_attentive_safe_clean_helpful_consensus_without_verified_lgbtq_specific_training','source_urls',to_jsonb(array['https://www.booking.com/reviews/de/hotel/marsil.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g187371-d679482-Reviews-Maison_Marsil-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1827::bigint, jsonb_build_object(
      'queue_wait','The vast atrium hotel handles volume, but check-in, breakfast, lifts and the pool area bunch around conventions and weekend departures. Parking is costly and popular. Book early for trade fairs, Pride or Carnival, and allow a little extra time when a conference releases hundreds of guests at once.','best_nights','Its Old Town and Rhine position makes Friday or Saturday convenient for walking to dinner and nightlife; weekdays can be dominated by conferences. The indoor pool and atrium are useful in poor weather. This is a full-service base, not a queer party hotel, and some restaurants may close seasonally.','crowd_mix','Conference delegates, tour groups, families, couples, business travellers and international city visitors create a large mainstream mix. LGBTQ+ guests blend into that flow. The cavernous atrium can feel lively but impersonal, and the balance changes dramatically with each convention or city festival.','dress_code','Mainstream hotel casual works, with swimwear reserved for the wellness area and smart casual suitable for dinner. No fashion gate is reported. Bring a light layer for the atrium, walking shoes for the old city and check pool changing arrangements if privacy matters.','staff_inclusivity','Guests praise location, scale, cleanliness and many helpful employees, but recent reviews also describe stressed breakfast service, uneven warmth, dated rooms and temperature issues. No verified LGBTQ+ training surfaced. Expect professional systems, yet put couple, bedding and privacy needs in the booking.','venue_classification','active_large_mainstream_rhinefront_conference_hotel_in_cologne_old_town_with_atrium_pool_restaurants_business_group_family_and_citybreak_mix_excellent_location_and_mixed_dated_room_breakfast_temperature_service_consensus','identity_note','Maritim Hotel Köln is a mainstream conference and leisure hotel, not a dedicated LGBTQ+ property.','source_urls',to_jsonb(array['https://www.maritim.com/en/hotels/germany/hotel-cologne','https://www.maritim.com/en/hotels/germany/hotel-cologne/reviews','https://www.booking.com/reviews/de/hotel/maritim-koln.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g187371-d230377-Reviews-Maritim_Hotel_Koln-Cologne_North_Rhine_Westphalia.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','conference_scale_checkin_breakfast_lift_pool_parking_and_major_event_capacity_pressure','source_urls',to_jsonb(array['https://www.maritim.com/en/hotels/germany/hotel-cologne','https://www.booking.com/reviews/de/hotel/maritim-koln.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_old_town_nightlife_access_weekday_conference_mix_and_weatherproof_pool_atrium_use','source_urls',to_jsonb(array['https://www.maritim.com/en/hotels/germany/hotel-cologne','https://www.tripadvisor.co.uk/Hotel_Review-g187371-d230377-Reviews-Maritim_Hotel_Koln-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','large_conference_group_family_couple_business_international_and_lgbtq_mainstream_guest_mix','source_urls',to_jsonb(array['https://www.maritim.com/en/hotels/germany/hotel-cologne/reviews','https://www.booking.com/reviews/de/hotel/maritim-koln.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','hotel_casual_swimwear_wellness_and_smart_dinner_norms_without_fashion_gate','source_urls',to_jsonb(array['https://www.maritim.com/en/hotels/germany/hotel-cologne']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','helpful_professional_large_hotel_signal_balanced_by_stressed_breakfast_uneven_warmth_and_no_specific_lgbtq_training','source_urls',to_jsonb(array['https://www.maritim.com/en/hotels/germany/hotel-cologne/reviews','https://www.booking.com/reviews/de/hotel/maritim-koln.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (240::bigint, jsonb_build_object(
      'queue_wait','Friday evenings, weekend afternoons and Pride dates are busiest; weekday evenings can be notably quieter. Admission includes the venue’s locker-and-towel process, so first-timers should allow time for orientation. Check current prices and themed specials, carry photo ID and do not arrive expecting instant action.','best_nights','Friday and Saturday bring the broadest turnout. The recurring under-29 special on selected Tuesdays shifts the age mix younger, while daytime can favour wellness over social energy. Pride, Carnival and holiday weekends intensify attendance. Choose for crowd fit and facilities, then verify the live calendar.','crowd_mix','Gay, bi and queer men from Cologne mix with international visitors across a wide adult age range. Time and specials matter more than a fixed stereotype: younger guests cluster on discounted youth dates, regulars use quieter hours and weekends produce the most varied body types, ages and nationalities.','dress_code','Street clothes go into a locker; towels, swim sandals and body comfort define the inside. Follow hygiene rules, sit on a towel in dry saunas and treat every erotic area as consent-based, never assumed. Bring minimal valuables and check whether extra towels or footwear cost more.','staff_inclusivity','Guests praise clean facilities, friendly English-speaking staff and respectful consent norms, including reassuring first visits. Others report high prices, odour, slippery areas or dismissive treatment. The men-only model is intentional; within that scope, ask for orientation and report boundary issues promptly.','venue_classification','active_men_only_gay_sauna_in_central_cologne_with_multiple_saunas_steam_whirlpool_maze_bar_massage_erotic_zones_weekend_and_youth_special_crowd_variation_and_generally_positive_cleanliness_staff_consent_consensus','identity_note','Phoenix Sauna Köln is an adult men-only gay bathhouse and wellness venue. Inclusion claims apply within that stated entry model, not to the whole LGBTQ+ community.','source_urls',to_jsonb(array['https://koeln.phoenixsaunen.net/','https://wanderlog.com/place/details/1821024','https://www.reddit.com/r/cologne/comments/1ssqx03/first_time_to_phoenix_sauna_as_a_teenager/','https://de.trustpilot.com/review/www.phoenixsauna-koeln.de']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','friday_weekend_pride_peak_weekday_quiet_and_first_visit_locker_towel_orientation_process','source_urls',to_jsonb(array['https://koeln.phoenixsaunen.net/','https://wanderlog.com/place/details/1821024']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','friday_saturday_broad_peak_selected_tuesday_under29_shift_and_daytime_wellness_variation','source_urls',to_jsonb(array['https://koeln.phoenixsaunen.net/','https://www.reddit.com/r/cologne/comments/1ssqx03/first_time_to_phoenix_sauna_as_a_teenager/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','gay_bi_queer_men_wide_age_body_and_nationality_mix_shaped_by_time_and_specials','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1821024','https://www.reddit.com/r/cologne/comments/1ssqx03/first_time_to_phoenix_sauna_as_a_teenager/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','locker_towel_sandal_hygiene_and_explicit_consent_norms_for_wellness_and_erotic_areas','source_urls',to_jsonb(array['https://koeln.phoenixsaunen.net/','https://www.reddit.com/r/cologne/comments/1ssqx03/first_time_to_phoenix_sauna_as_a_teenager/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','clean_friendly_english_speaking_respectful_first_visit_praise_balanced_by_price_odour_slip_and_service_complaints','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1821024','https://de.trustpilot.com/review/www.phoenixsauna-koeln.de']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1824::bigint, jsonb_build_object(
      'queue_wait','Digital self-check-in is central to the lean-luxury model, with staff available at the bar when technology or bookings need help. Mid-afternoon arrivals and breakfast can bunch; reserve limited parking and book early for fairs, Pride and Carnival. There is no nightlife entrance queue.','best_nights','Friday and Saturday make the 24-hour bar and nearby Belgian Quarter feel livelier; weekdays are calmer for work and sleep. The former radio-building design is the attraction rather than a nightly programme. Use it as a base for Cologne nightlife, not as a queer party hotel.','crowd_mix','Young professionals, couples, solo city visitors, business guests and design-conscious international travellers dominate. Locals may use the bar, while LGBTQ+ guests blend into a contemporary mainstream crowd. The atmosphere is independent-minded but the property now sits within a global hotel group.','dress_code','Lean-luxury casual fits: clean trainers, denim, simple tailoring or a bright evening look. There is no formal code, and the bar stays relaxed. Rooms are compact and storage is limited, so pack selectively; nearby nightlife venues may have their own door rules.','staff_inclusivity','Recent reviews often praise a warm welcome, helpful local tips, comfortable beds and friendly bar staff, while self-service friction, room size and housekeeping divide opinion. No specific LGBTQ+ training evidence was found. Ask a team member rather than struggling with the kiosk, and confirm bedding in advance.','venue_classification','active_design_led_lean_luxury_hotel_and_twenty_four_hour_bar_in_former_cologne_radio_building_with_digital_checkin_compact_rooms_citybreak_business_couple_mix_and_generally_friendly_staff_but_self_service_space_consensus','identity_note','Ruby Ella Hotel Cologne is an active mainstream design hotel and bar, now marketed with IHG, not an LGBTQ+-specific property.','source_urls',to_jsonb(array['https://www.ruby-hotels.com/en/hotels-destinations/cologne/ruby-ella','https://www.ihg.com/ruby-hotels/hotels/gb/en/cologne/cgnel/hoteldetail','https://www.booking.com/hotel/de/ruby-ella-cologne.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g187371-d21504443-Reviews-Ruby_Ella_Hotel_Cologne_by_IHG-Cologne_North_Rhine_Westphalia.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','digital_self_checkin_afternoon_breakfast_parking_and_major_event_capacity_without_nightlife_door','source_urls',to_jsonb(array['https://www.ruby-hotels.com/en/hotels-destinations/cologne/ruby-ella','https://www.booking.com/hotel/de/ruby-ella-cologne.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_bar_and_neighbourhood_energy_quiet_weekday_and_design_base_without_queer_party_programme','source_urls',to_jsonb(array['https://www.ruby-hotels.com/en/hotels-destinations/cologne/ruby-ella','https://www.ihg.com/ruby-hotels/hotels/gb/en/cologne/cgnel/hoteldetail']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','young_professional_couple_solo_business_design_international_and_mainstream_lgbtq_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/hotel/de/ruby-ella-cologne.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g187371-d21504443-Reviews-Ruby_Ella_Hotel_Cologne_by_IHG-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','lean_luxury_casual_without_gate_and_compact_room_selective_packing_practicality','source_urls',to_jsonb(array['https://www.ruby-hotels.com/en/hotels-destinations/cologne/ruby-ella']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','warm_helpful_bar_team_bed_praise_balanced_by_kiosk_room_size_housekeeping_friction_and_no_specific_lgbtq_training','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Hotel_Review-g187371-d21504443-Reviews-Ruby_Ella_Hotel_Cologne_by_IHG-Cologne_North_Rhine_Westphalia.html','https://www.booking.com/hotel/de/ruby-ella-cologne.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (244::bigint, jsonb_build_object(
      'queue_wait','There is no single queue: this is a 150-metre nightlife street made up of independent doors. Lines appear outside specific bars on Friday, Saturday, Carnival, Pride and the street festival. Start early, use the central cloakroom when operating and never assume one venue’s entry covers another.','best_nights','Friday and Saturday offer the fullest bar-hop, while early weekday evenings are easier for conversation. ColognePride, Carnival and the pre-Pride street festival transform the whole block and bring extreme crowds. Match the bar to your music and crowd rather than treating the street as one uniform club.','crowd_mix','Gay men remain highly visible, alongside lesbians, trans and non-binary people, queer friends, allies, locals and international visitors. The street is celebrated as broadly LGBTQ+, yet community reports note that some individual doors feel cis-gay-male centred. Crowd and welcome vary venue by venue.','dress_code','The street has no dress code. Casual Kölsch-bar clothes, cocktail polish and bright dance looks all coexist; individual fetish or party events may add rules. Wear shoes for standing and bar-hopping, travel light and keep your cloakroom token, phone and payment secure during festival crowds.','staff_inclusivity','A street has no single staff team. Official tourism presents the area as welcoming, while queer community reports range from joyful mixed-group nights to gendered or trans exclusion at particular businesses. Choose named venues, keep friends informed and direct complaints to the responsible operator.','venue_classification','active_cologne_lgbtq_nightlife_district_and_bar_hopping_corridor_with_multiple_independent_cocktail_pop_dance_pub_sauna_and_event_venues_weekend_pride_carnival_peaks_broad_but_door_specific_inclusion','record_status','area_context_record_not_single_managed_venue_verify_each_business_current_hours_entry_crowd_and_inclusion_conditions','identity_note','Schaafenstraße is Cologne’s LGBTQ+ nightlife district, not one venue. Queue, staff, dress and safeguarding conditions belong to each independent business.','source_urls',to_jsonb(array['https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://magazine.cologne-tourism.com/cologne/queer-cologne-top-tips-for-a-night-out-on-the-town/','https://www.travelgay.com/cologne-gay-bars','https://www.reddit.com/r/cologne/comments/17ps7u9/']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','no_single_queue_with_independent_weekend_pride_carnival_festival_doors_and_central_cloakroom','source_urls',to_jsonb(array['https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://magazine.cologne-tourism.com/cologne/queer-cologne-top-tips-for-a-night-out-on-the-town/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','friday_saturday_barhop_weekday_conversation_and_extreme_pride_carnival_street_festival_variation','source_urls',to_jsonb(array['https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://www.travelgay.com/cologne-gay-bars']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','broad_lgbtq_ally_local_visitor_mix_with_some_individual_doors_reported_as_cis_gay_male_centred','source_urls',to_jsonb(array['https://magazine.cologne-tourism.com/cologne/queer-cologne-top-tips-for-a-night-out-on-the-town/','https://www.reddit.com/r/cologne/comments/17ps7u9/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','no_street_code_with_venue_specific_theme_and_barhop_festival_security_practicality','source_urls',to_jsonb(array['https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://www.travelgay.com/cologne-gay-bars']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','no_single_staff_team_with_official_welcome_claim_and_material_venue_specific_gender_trans_exclusion_reports','source_urls',to_jsonb(array['https://www.koelntourismus.de/kunst-kultur/sehenswuerdigkeiten/detail/schaafenstrasse','https://www.reddit.com/r/cologne/comments/17ps7u9/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (246::bigint, jsonb_build_object(
      'queue_wait','The basement room is event-led: sold-out concerts and busy club nights create a stair and security queue, while there is no reason to visit without a listed bill. Buy first, note age limits and arrive around doors for live shows. Bahnhof Ehrenfeld makes access easy but the entrance can be missed.','best_nights','Pick a concert, showcase or DJ night whose sound suits you; alternative pop, hip-hop, electronic and emerging live acts all appear. Friday and Saturday often run later, but an excellent midweek tour date can be the better visit. It is not a standing weekly queer club.','crowd_mix','Young music fans, students, Ehrenfeld locals, touring-act followers and international visitors shape each night. Queer guests are common in Cologne’s alternative scene, and some promoters are explicitly inclusive, but the room has no fixed LGBTQ+ constituency. Artist and age limit predict the mix best.','dress_code','Casual gig clothes and comfortable trainers are the norm; there is no published general fashion test. Bring a small bag, light layers for a warm basement and any required ID. Themed promoters can impose additional rules, so their ticket page outranks generic club advice.','staff_inclusivity','The venue’s broad programme provides inclusion signals, but door, sound and crowd experience varies by promoter and sold-out pressure. No permanent LGBTQ+ service policy was verified. Ask security about access before descending, identify the responsible event team and report harassment immediately.','venue_classification','active_small_basement_concert_and_club_room_at_cologne_ehrenfeld_station_with_event_specific_alternative_pop_hiphop_electronic_live_programming_young_music_crowd_and_no_fixed_lgbtq_night_or_house_audience','identity_note','YUCA is a general event-led music club associated with the Ehrenfeld station complex, not a dedicated LGBTQ+ venue.','source_urls',to_jsonb(array['https://www.yuca.club/','https://www.yuca.club/programm','https://www.songkick.com/venues/1318016-yuca','https://www.tripadvisor.com/Attraction_Review-g187371-d13384611-Reviews-YUCA-Cologne_North_Rhine_Westphalia.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','ticketed_event_soldout_stair_security_age_check_and_station_entrance_context','source_urls',to_jsonb(array['https://www.yuca.club/','https://www.yuca.club/programm']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','bill_led_concert_showcase_and_dj_choice_with_weekend_late_but_strong_midweek_tour_variation','source_urls',to_jsonb(array['https://www.yuca.club/programm','https://www.songkick.com/venues/1318016-yuca']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','artist_age_and_promoter_defined_young_student_local_international_music_fan_mix_without_fixed_queer_constituency','source_urls',to_jsonb(array['https://www.yuca.club/programm','https://www.songkick.com/venues/1318016-yuca']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','casual_gigwear_small_bag_id_and_warm_basement_practicality_with_promoter_rule_priority','source_urls',to_jsonb(array['https://www.yuca.club/','https://www.tripadvisor.com/Attraction_Review-g187371-d13384611-Reviews-YUCA-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','broad_programme_inclusion_signal_with_promoter_door_sound_and_soldout_execution_variation','source_urls',to_jsonb(array['https://www.yuca.club/','https://www.tripadvisor.com/Attraction_Review-g187371-d13384611-Reviews-YUCA-Cologne_North_Rhine_Westphalia.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1983::bigint, jsonb_build_object(
      'queue_wait','Reception sits above the old university-school entrance, so first arrival can involve steps, a hidden lift and a moment of orientation. Check-in and breakfast bunch at standard hours; reserve the restaurant and ask for housekeeping under the current on-request system. Central location reduces transport waits later.','best_nights','Friday and Saturday animate the restaurant, bar and central streets, while Sunday or a weekday makes the sauna, lounges and design easier to enjoy. The hotel is a strong base between Nørreport and Kongens Nytorv, not a queer nightlife venue; walk to Studiestræde when that is the plan.','crowd_mix','Design-focused couples, solo travellers, families, business guests and international city breakers dominate, with locals joining at dining and drinks. LGBTQ+ guests sit within a cosmopolitan mainstream mix. Open bathroom layouts suit intimate travellers better than companions who need strong privacy.','dress_code','Creative Copenhagen smart casual fits the colourful schoolhouse setting: trainers, layers and a sharper dinner option. There is no formal gate. Pack for cycling and rain, and examine room layouts before booking because transparent shower elements can matter far more than clothes.','staff_inclusivity','Large verified samples praise friendly, flexible teams, central location and playful amenities, while housekeeping, unexpected fees and consistency draw criticism. No dedicated LGBTQ+ training was verified. Confirm cleaning, deposits, bedding and bathroom privacy before arrival.','venue_classification','active_mainstream_design_hotel_in_former_copenhagen_university_school_with_neni_restaurant_bar_sauna_lounges_bikes_central_international_guest_mix_and_strong_location_design_but_mixed_housekeeping_fee_service_consensus','identity_note','25hours Hotel Indre By is a mainstream Copenhagen design hotel, not an LGBTQ+-specific property. Its relevance is central access and cosmopolitan hospitality.','source_urls',to_jsonb(array['https://25hours-hotels.com/copenhagen/indre-by/','https://www.tripadvisor.com/Hotel_Review-g189541-d23794712-Reviews-25hours_Hotel_Indre_By-Copenhagen_Zealand.html','https://www.expedia.com/Copenhagen-Hotels-25Hours-Hotel-Indre-By.h74711314.Hotel-Information','https://www.booking.com/hotel/dk/25hours-indre-by.en-gb.html']::text[]),
      'topic_evidence',jsonb_build_object(
        'queue_wait',jsonb_build_object('status','unusual_reception_access_standard_checkin_breakfast_restaurant_and_on_request_housekeeping_friction','source_urls',to_jsonb(array['https://25hours-hotels.com/copenhagen/indre-by/','https://www.tripadvisor.com/Hotel_Review-g189541-d23794712-Reviews-25hours_Hotel_Indre_By-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights',jsonb_build_object('status','weekend_public_space_energy_and_quieter_weekday_sauna_design_use_with_central_offsite_nightlife_access','source_urls',to_jsonb(array['https://25hours-hotels.com/copenhagen/indre-by/','https://www.expedia.com/Copenhagen-Hotels-25Hours-Hotel-Indre-By.h74711314.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix',jsonb_build_object('status','design_couple_solo_family_business_international_and_local_dining_mix_with_open_bathroom_privacy_caveat','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g189541-d23794712-Reviews-25hours_Hotel_Indre_By-Copenhagen_Zealand.html','https://www.expedia.com/Copenhagen-Hotels-25Hours-Hotel-Indre-By.h74711314.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code',jsonb_build_object('status','creative_smart_casual_cycling_rain_and_room_privacy_layout_practicality_without_gate','source_urls',to_jsonb(array['https://25hours-hotels.com/copenhagen/indre-by/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity',jsonb_build_object('status','friendly_flexible_service_praise_balanced_by_housekeeping_fee_consistency_caveats_and_no_verified_lgbtq_training','source_urls',to_jsonb(array['https://www.expedia.com/Copenhagen-Hotels-25Hours-Hotel-Indre-By.h74711314.Hotel-Information','https://www.tripadvisor.com/Hotel_Review-g189541-d23794712-Reviews-25hours_Hotel_Indre_By-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (242,1823,1827,240,1824,244,246,1983)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
