-- Queer Atlas venue intelligence: global review-led editorial pass, batch 50.
-- Eight Buenos Aires records checked against current operator pages, local coverage and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (797::bigint, jsonb_build_object(
      'queue_wait', 'This is a mega-club, and the entrance can turn slow once its Almagro floors are already heaving. Buy through the current event link, arrive near opening and keep your phone and wallet close in the crush. The open-bar format creates a second wave of queues inside.',
      'best_nights', 'Choose the advertised party rather than trusting an old weekly schedule. The full-scale experience is a late weekend: multiple rooms, Latin pop, house, cumbia and commercial dance building after 02:00. Go earlier if you want to learn the layout before thousands arrive.',
      'crowd_mix', 'Gay men remain the core, but this is one of the city''s most mixed queer institutions: lesbians, trans guests, straight friends, drag performers, locals and Brazilian or international visitors all appear. It feels less intimate than a neighbourhood bar and much more like a carnival-sized disco.',
      'dress_code', 'There is no polished fashion gate. Trainers, jeans, club tops and shirtless dancing all fit once the room heats up. Wear something breathable and use a zipped pocket or secure bag; crowds, smoke and constant movement matter more here than making a door-look statement.',
      'staff_inclusivity', 'Many guests describe efficient bars, visible security and freedom to dance without judgement. Others report watered drinks, overcrowding, smoke and stolen phones, so inclusive energy does not remove practical risk. Ask security for help early and never leave belongings loose.',
      'venue_classification', 'active_landmark_large_capacity_buenos_aires_lgbtq_megaclub_in_almagro_with_multiple_rooms_open_bar_formats_mixed_queer_and_ally_crowd_late_weekend_peak_and_material_crowding_smoke_pickpocket_risk',
      'identity_note', 'Amerika remains an active LGBTQ+ mega-club at Gascón 1040 in Almagro. Current dates and ticket mechanics should be taken from the operator''s social channel because weekly listings and open-bar formats change.',
      'source_urls', to_jsonb(array['https://www.instagram.com/amerikadiscooficial/','https://wanderlog.com/place/details/2385277/amerika','https://wander-argentina.com/amerika-buenos-aires-largest-lgbt-nightclub/','https://buenosaires.gaycities.com/bars/1859-amerika','https://www.agcba.gob.ar/docs/inf-20250312_2405---AGC-FISCALIZACION-Y-CONTROL-DE-LOCALES-BAILABLES-CLASE-C..pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','large_capacity_weekend_entry_and_internal_bar_pressure_with_current_event_link_and_property_security_advice','source_urls',to_jsonb(array['https://www.instagram.com/amerikadiscooficial/','https://wanderlog.com/place/details/2385277/amerika','https://buenosaires.gaycities.com/bars/1859-amerika']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','event_led_late_weekend_multiple_room_latin_pop_house_cumbia_and_commercial_dance_pattern','source_urls',to_jsonb(array['https://www.instagram.com/amerikadiscooficial/','https://wander-argentina.com/amerika-buenos-aires-largest-lgbt-nightclub/','https://wanderlog.com/place/details/2385277/amerika']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_core_with_lesbian_trans_drag_ally_local_brazilian_and_international_mega_club_mix','source_urls',to_jsonb(array['https://wander-argentina.com/amerika-buenos-aires-largest-lgbt-nightclub/','https://buenosaires.gaycities.com/bars/1859-amerika','https://wanderlog.com/place/details/2385277/amerika']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_breathable_clubwear_shirtless_dancing_and_secure_belonging_practicality_without_published_fashion_gate','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2385277/amerika','https://buenosaires.gaycities.com/bars/1859-amerika']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','efficient_security_and_nonjudgmental_dancing_praise_balanced_against_crowding_smoke_drink_and_theft_complaints','source_urls',to_jsonb(array['https://wanderlog.com/place/details/2385277/amerika','https://buenosaires.gaycities.com/bars/1859-amerika']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (838::bigint, jsonb_build_object(
      'queue_wait', 'There is no door or formal line: this is a large public park, not a managed venue. Encounters are reported after dark around quieter wooded edges, but exact activity shifts. Do not wait visibly in one spot; agree boundaries clearly and leave if the setting feels exposed.',
      'best_nights', 'Warm Friday and Saturday nights bring more foot traffic, yet later is not automatically better. Daylight is for the lakes, gardens and general park crowd; cruising reports concern darker hours. Pair up for the journey, use a ride to the edge and avoid isolated paths after activity thins.',
      'crowd_mix', 'By day, runners, families and tourists dominate. After dark, men seeking men and trans sex workers have long been visible in parts of the woods, alongside ordinary passers-by. It is not a queer social venue, and nobody in the park should be assumed available or interested.',
      'dress_code', 'Dress for walking and weather: low-key layers, closed shoes and nothing that advertises valuables. There is no fetish code and no staff-controlled zone. Keep your phone discreet, carry only what you need and remember that clothing or presence in a known area never signals consent.',
      'staff_inclusivity', 'There is no venue team, host or safeguarding system. Police presence and public attitudes can vary, while theft risk is repeatedly raised in local discussion. Share your location with someone, keep transport ready and choose a staffed queer bar instead if you want accountable support.',
      'venue_classification', 'public_park_with_historic_after_dark_men_seeking_men_and_trans_sex_worker_cruising_reports_not_a_managed_venue_no_host_no_fixed_boundary_and_heightened_isolation_theft_consent_and_personal_safety_considerations',
      'identity_note', 'Bosques de Palermo is the public Parque Tres de Febrero, not a licensed cruising venue. Reports describe shifting after-dark activity rather than a stable operator, entrance or bounded address.',
      'source_urls', to_jsonb(array['https://buenosaires.gob.ar/espaciopublicoehigieneurbana/parque-tres-de-febrero','https://www.cruisinggays.com/buenos-aires/c/areas/','https://www.reddit.com/r/BuenosAires/comments/xx6jo8','https://www.reddit.com/r/BuenosAires/comments/17jt3r6','https://en.wikipedia.org/wiki/Parque_Tres_de_Febrero']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','public_park_without_door_queue_operator_or_fixed_cruising_boundary_and_after_dark_activity_variation','source_urls',to_jsonb(array['https://buenosaires.gob.ar/espaciopublicoehigieneurbana/parque-tres-de-febrero','https://www.cruisinggays.com/buenos-aires/c/areas/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','warm_weekend_after_dark_signal_with_isolation_transport_and_falling_activity_safety_limits','source_urls',to_jsonb(array['https://www.cruisinggays.com/buenos-aires/c/areas/','https://www.reddit.com/r/BuenosAires/comments/xx6jo8']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','daytime_general_public_and_after_dark_msm_trans_worker_and_passerby_mix_without_assumed_interest','source_urls',to_jsonb(array['https://buenosaires.gob.ar/espaciopublicoehigieneurbana/parque-tres-de-febrero','https://www.reddit.com/r/BuenosAires/comments/17jt3r6']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_code_with_weather_walking_closed_shoe_discreet_valuable_and_explicit_consent_practicality','source_urls',to_jsonb(array['https://buenosaires.gob.ar/espaciopublicoehigieneurbana/parque-tres-de-febrero','https://www.cruisinggays.com/buenos-aires/c/areas/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_staff_host_or_safeguarding_with_local_theft_isolation_and_variable_policing_concerns','source_urls',to_jsonb(array['https://www.reddit.com/r/BuenosAires/comments/xx6jo8','https://www.reddit.com/r/BuenosAires/comments/17jt3r6']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (420::bigint, jsonb_build_object(
      'queue_wait', 'The room opens late and can be packed by about 02:00, especially for the signature performance party. Presale is the calmer route; the entrance and dance floor both tighten once the first big show lands. Arriving around 01:00 gives you time to settle before the spectacle starts.',
      'best_nights', 'Follow the current Club 69 date at Niceto rather than assuming every night is the same. The classic formula pairs house, nu-disco or tech-house DJs with drag, dancers, acrobatics and a changing stage production. The strongest energy comes after 02:00, between show bursts.',
      'crowd_mix', 'Young gay men are highly visible, but this is performance-led and genuinely mixed: queer regulars, straight friends, visitors and Niceto music fans share the floor. Recent gay guests describe a shirtless, judgment-free pocket; other nights can feel more broadly gay-friendly than specifically gay.',
      'dress_code', 'Jeans, T-shirts and trainers are normal, and there is no reported formal code. Dress light because the floor gets hot and compressed; bolder queer looks make sense beside the cabaret without being required. Skip the heavy coat and large bag when possible.',
      'staff_inclusivity', 'Recent guests praise lively staging, friendly security and a crowd comfortable with queer expression. The recurring drawback is physical density, not a hostile door. Stay aware near bathrooms and packed passages, and tell security early if enthusiastic chaos crosses a boundary.',
      'venue_classification', 'active_event_brand_at_niceto_club_with_late_house_nu_disco_tech_house_djs_drag_dancers_acrobatics_changing_stage_productions_mixed_queer_and_mainstream_crowd_informal_dress_and_high_peak_density',
      'identity_note', 'Club 69 is an event format hosted at Niceto Club, Avenida Coronel Niceto Vega 5510. Its schedule has shifted over time; use the current event channel rather than treating stored Thursday and Saturday hours as permanent.',
      'source_urls', to_jsonb(array['https://www.instagram.com/club69.ba/','https://www.tripadvisor.co/Attraction_Review-g312741-d10850406-Reviews-Club_69-Buenos_Aires_Capital_Federal_District.html','https://wanderlog.com/place/details/4333701/club-69','https://www.cntraveler.com/activities/buenos-aires/niceto-club','https://buenosaires.gaycities.com/bars/1865-niceto-club']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','late_opening_peak_by_0200_presale_and_early_arrival_before_first_stage_show','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4333701/club-69','https://www.cntraveler.com/activities/buenos-aires/niceto-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','current_event_led_house_nu_disco_tech_house_drag_dancer_acrobatics_and_rotating_stage_formula','source_urls',to_jsonb(array['https://www.instagram.com/club69.ba/','https://www.tripadvisor.co/Attraction_Review-g312741-d10850406-Reviews-Club_69-Buenos_Aires_Capital_Federal_District.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_gay_visible_with_queer_straight_visitor_and_niceto_music_fan_variation_by_event','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4333701/club-69','https://buenosaires.gaycities.com/bars/1865-niceto-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','reported_no_formal_code_with_jeans_tshirt_trainers_bold_queer_looks_and_heat_led_light_packing','source_urls',to_jsonb(array['https://www.tripadvisor.com/Attraction_Review-g312741-d807861-Reviews-Niceto_Club-Buenos_Aires_Capital_Federal_District.html','https://www.cntraveler.com/activities/buenos-aires/niceto-club']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_security_performance_and_queer_expression_praise_with_peak_density_as_main_boundary_risk','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4333701/club-69','https://buenosaires.gaycities.com/bars/1865-niceto-club']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1133::bigint, jsonb_build_object(
      'queue_wait', 'There is no current queue. The celebrated basement club is listed as permanently closed, and the stored Avenida Rivadavia 1910 pin is not its documented doorway. Do not travel there for a party or buy a ticket using the old name unless a new operator publishes a verifiable address.',
      'best_nights', 'Its remembered peak was the deep Friday-to-morning techno session: dark basement, serious local and international DJs, forceful sound and very little interest in commercial gloss. That is nightlife history now, not a current recommendation or a reusable weekly schedule.',
      'crowd_mix', 'Historically, dedicated techno dancers, queer night people, artists and international club pilgrims shared an intimate, gritty room. The music mattered more than identity branding. No present crowd can be described because the club is closed and later mentions often recycle its reputation.',
      'dress_code', 'The old room rewarded practical underground clothing: dark layers, trainers and nothing precious in a sweaty basement. It was not remembered for a polished fashion gate. There is no current policy, so an archived aesthetic must not be presented as admission advice.',
      'staff_inclusivity', 'Past reviews praised courteous staff, intense sound and a place where dancers could disappear into the music. Those memories do not verify a current safety or hospitality team. Keep the archive, suppress the active listing and review any genuine revival as a new entity.',
      'venue_classification', 'permanently_closed_former_gritty_buenos_aires_basement_techno_institution_at_historic_rivadavia_878_with_serious_local_international_djs_music_led_queer_adjacent_crowd_and_no_verified_current_operator_or_programme',
      'record_status', 'closed_former_nightclub_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring_until_verified_revival',
      'identity_note', 'Cocoliche is listed as permanently closed. The well-documented historic address is Avenida Rivadavia 878, not the stored Avenida Rivadavia 1910; no current operator or programme verifies a revival.',
      'source_urls', to_jsonb(array['https://restaurantguru.com/Cocoliche-Buenos-Aires','https://buenosaires.gaycities.com/bars/310492-cocoliche','https://ww1.prweb.com/prfiles/2008/02/26/277432/nightlifeguide.pdf','https://www.instagram.com/cocoliche_official/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','permanently_closed_with_no_current_queue_and_stored_address_mismatch_against_documented_historic_door','source_urls',to_jsonb(array['https://restaurantguru.com/Cocoliche-Buenos-Aires','https://ww1.prweb.com/prfiles/2008/02/26/277432/nightlifeguide.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_friday_weekend_all_morning_techno_identity_only_without_current_programme','source_urls',to_jsonb(array['https://buenosaires.gaycities.com/bars/310492-cocoliche','https://restaurantguru.com/Cocoliche-Buenos-Aires']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_techno_dancer_artist_queer_nightlife_and_international_club_pilgrim_mix_not_current','source_urls',to_jsonb(array['https://buenosaires.gaycities.com/bars/310492-cocoliche','https://restaurantguru.com/Cocoliche-Buenos-Aires']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_practical_dark_basement_dancewear_without_verified_current_door_policy','source_urls',to_jsonb(array['https://buenosaires.gaycities.com/bars/310492-cocoliche','https://restaurantguru.com/Cocoliche-Buenos-Aires']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','historic_courteous_staff_sound_and_immersive_room_praise_cannot_verify_current_team','source_urls',to_jsonb(array['https://restaurantguru.com/Cocoliche-Buenos-Aires','https://buenosaires.gaycities.com/bars/310492-cocoliche']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1131::bigint, jsonb_build_object(
      'queue_wait', 'Arriving near the 20:00 opening is the smart move: the patios are easier, food lands faster and ticketed shows are simpler to navigate. Fridays and Saturdays can produce long entrance, payment and bar waits. After 01:00 there is no re-entry, so finish any outside plans first.',
      'best_nights', 'Pick your format: Wednesday and Thursday after-work drinks are conversational; the monthly drag cabaret and Sunday talent stage foreground local artists; Friday splits pop from perreo, while Saturday turns fully late and dance-led. The calendar is more useful than a blanket “best night.”',
      'crowd_mix', 'This is a broad cuir home: queer women, trans and non-binary people, drag artists, gay men, friends and first-timers occupy different rooms of the old house. Locals shape the culture, while visitors are welcomed when they understand it is community space, not an exotic nightlife exhibit.',
      'dress_code', 'Wear whatever lets you move between patios, theatre, karaoke and dance floor: everyday layers, glitter, drag and gender-expansive looks all belong. The meaningful code is conduct. Harassment and non-consensual behaviour are zero-tolerance, and the venue explicitly centres LGBTQ+ safety.',
      'staff_inclusivity', 'The venue tells guests to approach any staff member if someone makes them uncomfortable and promises belief and immediate help. Reviews praise warmth, art and queer freedom, but also flag slow two-stage drink queues and uneven event timing. Come early and escalate concerns directly.',
      'venue_classification', 'active_lgbtiq_cuir_social_and_cultural_club_in_almagro_house_with_patios_food_drag_theatre_karaoke_talent_pop_perreo_and_afterwork_formats_broad_gender_mix_explicit_consent_policy_and_peak_service_waits',
      'identity_note', 'Feliza is active at Avenida Córdoba 3271, open Wednesday through Sunday from evening into 05:00 or 06:00 depending on the night. Its official calendar, 18+ rule, accessibility note and anti-harassment policy are current.',
      'source_urls', to_jsonb(array['https://www.felizarcoiris.com/','https://www.tripadvisor.co/Attraction_Review-g312741-d12708533-Reviews-Feliza_Gay_Bar-Buenos_Aires_Capital_Federal_District.html','https://wanderlog.com/place/details/2385289/feliza-gay-lesbian-bar','https://www.postcard.inc/places/feliza-gay-and-lesbian-bar-buenos-aires-RoVDBU8j2Vv','https://buenosaires.gob.ar/fiba/experiencias-arcoiris-infrarrojo']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','early_opening_advantage_with_weekend_entrance_payment_bar_waits_and_official_no_reentry_after_0100','source_urls',to_jsonb(array['https://www.felizarcoiris.com/','https://www.tripadvisor.co/Attraction_Review-g312741-d12708533-Reviews-Feliza_Gay_Bar-Buenos_Aires_Capital_Federal_District.html','https://www.postcard.inc/places/feliza-gay-and-lesbian-bar-buenos-aires-RoVDBU8j2Vv']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','calendar_specific_afterwork_drag_cabaret_talent_pop_perreo_and_saturday_late_dance_variation','source_urls',to_jsonb(array['https://www.felizarcoiris.com/','https://buenosaires.gob.ar/fiba/experiencias-arcoiris-infrarrojo']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','broad_queer_woman_trans_nonbinary_drag_gay_friend_newcomer_local_and_respectful_visitor_mix','source_urls',to_jsonb(array['https://www.felizarcoiris.com/','https://wanderlog.com/place/details/2385289/feliza-gay-lesbian-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_fashion_gate_with_everyday_drag_glitter_gender_expression_and_explicit_consent_behaviour_code','source_urls',to_jsonb(array['https://www.felizarcoiris.com/','https://www.tripadvisor.co/Attraction_Review-g312741-d12708533-Reviews-Feliza_Gay_Bar-Buenos_Aires_Capital_Federal_District.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','official_immediate_staff_support_and_belief_policy_plus_warmth_praise_balanced_against_service_and_timing_delays','source_urls',to_jsonb(array['https://www.felizarcoiris.com/','https://wanderlog.com/place/details/2385289/feliza-gay-lesbian-bar','https://www.postcard.inc/places/feliza-gay-and-lesbian-bar-buenos-aires-RoVDBU8j2Vv']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (421::bigint, jsonb_build_object(
      'queue_wait', 'The compact downtown party opens around 23:30 and the practical rush comes after midnight. Current reviews praise fair prices and strong atmosphere, so expect a busier entrance on Friday and Saturday. Use the latest social post for tickets and go before 01:00 if you dislike a compressed floor.',
      'best_nights', 'Friday and Saturday are the dependable run, with Sunday hours sometimes reflecting the Saturday spill past midnight. The musical identity is playful rather than fixed: pop roots, cumbia, Brazilian tracks and left-turn singalongs can share one set. Go for the crowd as much as the playlist.',
      'crowd_mix', 'Young LGBTQ+ locals, queer friend groups and budget-minded dancers dominate, with visitors folded into a notably good-natured room. Reviewers love the atmosphere even when they disagree about the music. It is more social and pop-cultural than hard electronic or men-only cruising.',
      'dress_code', 'There is no reported style test. Trainers, casual clubwear, crop tops and expressive party looks all make sense in a six-hour dance session. Keep it light, bring only a small secure bag and choose shoes for standing; the venue is reported as not wheelchair accessible.',
      'staff_inclusivity', 'Recent guests single out the staff as excellent and the overall mood as welcoming, with accessible pricing helping newcomers join. Music complaints are the sharper criticism, especially from people wanting more current pop. Ask before buying whether that night''s set matches your taste.',
      'venue_classification', 'active_weekend_lgbtq_party_at_viamonte_638_with_young_local_social_crowd_fair_price_consensus_pop_cumbia_brazilian_and_eclectic_music_variation_informal_dress_positive_staff_feedback_and_reported_accessibility_limit',
      'identity_note', 'Fiesta Nix is active at Viamonte 638, not 630. Current listings show Friday and Saturday doors around 23:30 with dancing until approximately 06:00; exact music and tickets remain event-led.',
      'source_urls', to_jsonb(array['https://www.instagram.com/fiestanixba/','https://es.restaurantguru.com/Fiesta-Whip-Buenos-Aires-3','https://www.google.com/maps/search/?api=1&query=Fiesta+Nix+Viamonte+638+Buenos+Aires']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','weekend_2330_opening_post_midnight_pressure_current_ticket_check_and_early_arrival_for_space','source_urls',to_jsonb(array['https://www.instagram.com/fiestanixba/','https://es.restaurantguru.com/Fiesta-Whip-Buenos-Aires-3']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_core_with_pop_cumbia_brazilian_and_eclectic_song_variation_by_set','source_urls',to_jsonb(array['https://www.instagram.com/fiestanixba/','https://es.restaurantguru.com/Fiesta-Whip-Buenos-Aires-3']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_lgbtq_local_queer_friend_budget_dancer_and_visitor_social_mix_not_cruising_or_hard_electronic','source_urls',to_jsonb(array['https://es.restaurantguru.com/Fiesta-Whip-Buenos-Aires-3','https://www.instagram.com/fiestanixba/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_reported_style_gate_with_light_casual_expressive_dancewear_secure_bag_and_reported_wheelchair_limit','source_urls',to_jsonb(array['https://es.restaurantguru.com/Fiesta-Whip-Buenos-Aires-3']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','recent_staff_and_atmosphere_praise_with_music_selection_as_primary_negative_consensus','source_urls',to_jsonb(array['https://es.restaurantguru.com/Fiesta-Whip-Buenos-Aires-3']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1130::bigint, jsonb_build_object(
      'queue_wait', 'This is a touring party inside the large Teatro Vorterix rather than a permanent bar. Saturday ticket checks build after 01:00 and popular editions can fill the hall fast. Buy from the current event link and arrive before the headline set; an old venue pin does not prove tonight''s door.',
      'best_nights', 'The correct night is whichever Saturday the brand announces. Expect a shameless blend of pop, cumbia, reggaetón and big communal choruses rather than a purist electronic set. The theatrical Vorterix scale suits birthdays, groups and people who want maximum singalong energy.',
      'crowd_mix', 'The floor draws a young, mixed LGBTQ+ public, large friend groups, drag-fluent regulars and straight allies. It is more celebratory than intimate and more pan-queer than men-only. Locals dominate the cultural references, while visitors can join easily once the chorus hits.',
      'dress_code', 'Go playful, breathable and ready for a concert-sized room: trainers, colour, mesh and a ridiculous pop look all work. No formal code is documented. A small zipped bag beats loose pockets, and hearing protection is sensible near the stage and speaker stacks.',
      'staff_inclusivity', 'Reviews describe a fun queer atmosphere and a strong party concept, though detailed current hospitality reporting is thin. Treat venue security and party production as separate teams, locate exits on arrival and report harassment immediately rather than assuming a celebratory crowd polices itself.',
      'venue_classification', 'active_touring_lgbtq_saturday_party_brand_commonly_at_teatro_vorterix_with_pop_cumbia_reggaeton_singalong_programming_large_concert_room_young_mixed_queer_ally_groups_informal_expressive_dress_and_limited_current_service_consensus',
      'identity_note', 'Fiesta Puerca operates as an event brand, commonly at Teatro Vorterix, Avenida Federico Lacroze 3455. Dates are not nightly venue hours and must be verified through the current operator feed.',
      'source_urls', to_jsonb(array['https://www.instagram.com/instapuerca/','https://wanderlog.com/place/details/5660419/fiesta-puerca','https://www.gayout.com/south-america/argentina/cqh/bars/fiesta-puerca-9423','https://www.instagram.com/teatrovorterix/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','touring_event_not_permanent_bar_with_saturday_post_0100_ticket_pressure_and_current_event_link_requirement','source_urls',to_jsonb(array['https://www.instagram.com/instapuerca/','https://wanderlog.com/place/details/5660419/fiesta-puerca','https://www.instagram.com/teatrovorterix/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','announced_saturday_only_with_pop_cumbia_reggaeton_and_large_room_communal_singalong_identity','source_urls',to_jsonb(array['https://www.instagram.com/instapuerca/','https://wanderlog.com/place/details/5660419/fiesta-puerca']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_mixed_lgbtq_group_drag_fluent_regular_local_and_straight_ally_concert_party_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5660419/fiesta-puerca','https://www.gayout.com/south-america/argentina/cqh/bars/fiesta-puerca-9423']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_documented_formal_code_with_playful_breathable_concert_clubwear_secure_bag_and_hearing_protection_practicality','source_urls',to_jsonb(array['https://www.instagram.com/instapuerca/','https://www.instagram.com/teatrovorterix/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','positive_queer_party_concept_consensus_but_thin_current_service_reporting_and_separate_venue_security_responsibility','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5660419/fiesta-puerca','https://www.gayout.com/south-america/argentina/cqh/bars/fiesta-puerca-9423']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1129::bigint, jsonb_build_object(
      'queue_wait', 'Wednesday is the ritual, and the early 21:00 start lets the room grow from bar-like to full party without a brutal club queue. Later arrivals can meet a tighter door and floor. Check the current post first: Jolie is an event, and archived weekend hours are less reliable than its announced date.',
      'best_nights', 'The classic choice is Wednesday—Buenos Aires'' gloriously extra “second Saturday.” Start with drinks, stay through pop, Latin hits and crowd-pleasing anthems, then dance into the morning. A special Friday or Saturday can work, but only when the organiser actually announces one.',
      'crowd_mix', 'Gay men, lesbians, trans and non-binary guests, mixed queer groups, locals and travellers share a relaxed midweek floor. The early social stretch suits meeting people; after midnight it becomes younger, louder and more group-led. It is openly LGBT rather than narrowly coded to one scene.',
      'dress_code', 'The practical uniform is casual partywear: trainers, jeans, crop tops, colour and whatever survives a long Wednesday. There is no published couture test. Bring a light layer for the early bar hours and keep valuables zipped once the room turns into a proper club.',
      'staff_inclusivity', 'Long-running reviews frame Jolie as friendly, uncomplicated and easy for mixed LGBT groups, with its midweek timing part of the charm. Current detailed service evidence is limited, so verify the active host and venue before travelling and raise any problem with both production and door staff.',
      'venue_classification', 'active_long_running_buenos_aires_lgbtq_event_brand_best_known_for_wednesday_early_bar_to_late_pop_latin_anthem_party_with_broad_queer_mix_casual_dress_social_opening_and_current_date_verification_required',
      'identity_note', 'Fiesta Jolie is an event brand historically associated with Avenida Juan B. Justo 1658 and its signature Wednesday party. Current dates and host venue must be checked on the organiser''s feed; stored Friday-Saturday hours should not be treated as fixed.',
      'source_urls', to_jsonb(array['https://www.instagram.com/fiestajolie/','https://www.tripadvisor.com.ar/Attraction_Review-g312741-d10289104-Reviews-Fiesta_Jolie-Buenos_Aires_Capital_Federal_District.html','https://wanderlog.com/place/details/3840105','https://ar.todosnegocios.com/fiesta-jolie_2Q-011-1111-1111']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','signature_wednesday_early_2100_social_opening_with_later_capacity_and_current_event_verification_need','source_urls',to_jsonb(array['https://www.instagram.com/fiestajolie/','https://wanderlog.com/place/details/3840105']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','long_running_wednesday_second_saturday_identity_with_pop_latin_anthems_and_only_announced_special_weekends','source_urls',to_jsonb(array['https://www.tripadvisor.com.ar/Attraction_Review-g312741-d10289104-Reviews-Fiesta_Jolie-Buenos_Aires_Capital_Federal_District.html','https://wanderlog.com/place/details/3840105']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','broad_gay_lesbian_trans_nonbinary_queer_local_and_traveller_mix_shifting_from_early_social_to_late_group_floor','source_urls',to_jsonb(array['https://wanderlog.com/place/details/3840105','https://www.tripadvisor.com.ar/Attraction_Review-g312741-d10289104-Reviews-Fiesta_Jolie-Buenos_Aires_Capital_Federal_District.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_fashion_gate_with_casual_colourful_long_session_clubwear_and_secure_valuable_practicality','source_urls',to_jsonb(array['https://www.instagram.com/fiestajolie/','https://wanderlog.com/place/details/3840105']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','historic_friendly_easy_mixed_lgbt_consensus_with_limited_current_service_detail_and_dual_production_venue_responsibility','source_urls',to_jsonb(array['https://www.tripadvisor.com.ar/Attraction_Review-g312741-d10289104-Reviews-Fiesta_Jolie-Buenos_Aires_Capital_Federal_District.html','https://wanderlog.com/place/details/3840105']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),
      'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (1133);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (797,838,420,1133,1131,421,1130,1129)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
