-- Queer Atlas venue intelligence: global review-led editorial pass, batch 52.
-- Eight Busan records checked against current operator pages, booking data, queer guides and review consensus on 2026-08-07.

begin;

with reviewed(id, patch) as (
  values
    (1772::bigint, jsonb_build_object(
      'queue_wait', 'The basement is discreet and usually walk-in friendly, but Friday and Saturday fill after 22:00 as groups begin their Beomil circuit. Save the map and Korean address before leaving Wi-Fi. An early drink gives you the cyberpunk room without the late crush; the bar can then run until 06:00.',
      'best_nights', 'Thursday keeps the electronic soundtrack and leaves more space to talk. Friday and Saturday switch toward K-pop and bring the younger, more social crowd, making them better for pre-club energy. Start here around 21:00, then follow the room''s movement into neighbouring late bars.',
      'crowd_mix', 'Young local gay men form the core, with solo visitors and small friend groups both reported as comfortable. Foreign travellers are a minority but the pregame format is easier to enter than a private karaoke room. This is a gay men''s bar, not a broad all-gender queer venue.',
      'dress_code', 'Dark streetwear, trainers, denim and neon details suit the industrial room, but no formal dress code is published. Keep it light for a long Beomil crawl and ask before photographing anyone; a visually striking bar still sits inside a privacy-conscious local scene.',
      'staff_inclusivity', 'Guides frame BUNKER as easy for both solo guests and groups, with a casual rather than status-heavy atmosphere. Detailed independent service reviews remain scarce, so carry a translation app, confirm the bill as you order and treat the official social feed as the final word on opening.',
      'venue_classification', 'active_thursday_to_saturday_underground_gay_mens_bar_in_beomil_dong_with_industrial_cyberpunk_design_electronic_weekday_kpop_weekend_music_young_local_core_solo_group_pregame_use_and_limited_independent_review_depth',
      'identity_note', 'Busan BUNKER is currently promoted at basement level in Beomil-dong and on @busan_bunker, with Thursday-Saturday operation. The stored address formatting is imprecise; users should verify the latest map post before travelling.',
      'source_urls', to_jsonb(array['https://www.instagram.com/busan_bunker/','https://www.travelgay.com/venue/busan-bunker','https://gay-travelnavi.com/allspot/korea/bunker/','https://es.travelgay.com/busan-gay-bars']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','discreet_basement_walkin_with_post_2200_weekend_build_early_space_and_map_preparation_need','source_urls',to_jsonb(array['https://www.instagram.com/busan_bunker/','https://www.travelgay.com/venue/busan-bunker','https://gay-travelnavi.com/allspot/korea/bunker/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','thursday_electronic_conversation_versus_friday_saturday_kpop_younger_pregame_energy','source_urls',to_jsonb(array['https://www.travelgay.com/venue/busan-bunker','https://gay-travelnavi.com/allspot/korea/bunker/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_local_gay_men_core_with_solo_and_group_access_and_smaller_foreign_visitor_presence','source_urls',to_jsonb(array['https://www.travelgay.com/venue/busan-bunker','https://gay-travelnavi.com/allspot/korea/bunker/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_code_with_dark_streetwear_neon_trainer_fit_and_strong_no_photo_privacy_norm','source_urls',to_jsonb(array['https://www.instagram.com/busan_bunker/','https://gay-travelnavi.com/allspot/korea/bunker/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','solo_and_group_casual_access_signal_but_thin_independent_service_consensus_translation_bill_and_schedule_checks_needed','source_urls',to_jsonb(array['https://www.travelgay.com/venue/busan-bunker','https://gay-travelnavi.com/allspot/korea/bunker/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1765::bigint, jsonb_build_object(
      'queue_wait', 'The small 24-hour desk is generally uncomplicated, though early rooms are not guaranteed and weekend Seomyeon arrivals can bunch. Leave luggage, take the short walk from Jeonpo or Seomyeon station and return after check-in. Larger suites are worth confirming by exact room name.',
      'best_nights', 'Angel works best when you want Jeonpo cafés and Seomyeon nightlife outside rather than inside the hotel. Friday-Saturday maximise late food and bars; weekdays make this an efficient Line 1/2 sightseeing base. Reviews favour the better suites, so room choice matters more than the night itself.',
      'crowd_mix', 'Budget travellers, couples, friends and Asian and international city visitors make a mainstream mixed crowd. It is not queer-branded, but its central setting and neutral hotel rhythm suit travellers who value discretion. Beomil''s gay lanes are a short transit or taxi hop away.',
      'dress_code', 'No hotel dress code applies. Tourist clothes, café looks and late-night outfits all pass through the lobby. The building is older, so pack for function: comfortable walking shoes, a light layer and your preferred toiletries rather than expecting boutique polish from every room.',
      'staff_inclusivity', 'Recent guests call the location convenient and the overall stay good value, with service typically practical rather than elaborate. Room age and condition vary more than hospitality. Same-sex couples should book normally; no evidence supports calling it LGBTQ+-specialist, only a discreet mainstream base.',
      'venue_classification', 'active_older_value_hotel_at_46_7_jungang_daero_692beon_gil_between_jeonpo_and_seomyeon_with_24_hour_desk_mainstream_mixed_guest_profile_strong_nightlife_transit_location_and_room_quality_variation',
      'identity_note', 'Angel Hotel is active at 46-7 Jungang-daero 692beon-gil, Busanjin-gu. It is a mainstream value hotel near Seomyeon, not a dedicated LGBTQ+ hotel.',
      'source_urls', to_jsonb(array['http://www.angelhotel.co.kr/','https://www.booking.com/hotel/kr/angel.html','https://www.trip.com/hotels/busan-hotel-detail-689091/angel-hotel/review.html','https://angel.busanhotelsweb.com/en/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_24_hour_desk_weekend_arrival_bunching_bag_drop_and_exact_suite_confirmation','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/angel.html','https://angel.busanhotelsweb.com/en/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekend_jeonpo_seomyeon_food_nightlife_versus_weekday_line_one_two_base_with_room_choice_priority','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/angel.html','https://www.trip.com/hotels/busan-hotel-detail-689091/angel-hotel/review.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mainstream_budget_couple_friend_asian_and_international_city_guest_mix_not_queer_branded','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/angel.html','https://www.trip.com/hotels/busan-hotel-detail-689091/angel-hotel/review.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_code_with_tourist_cafe_and_nightlife_style_plus_older_building_functional_packing','source_urls',to_jsonb(array['https://angel.busanhotelsweb.com/en/','https://www.booking.com/hotel/kr/angel.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','practical_value_service_and_location_consensus_with_room_condition_variation_and_no_false_lgbtq_specialist_claim','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/angel.html','https://www.trip.com/hotels/busan-hotel-detail-689091/angel-hotel/review.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1776::bigint, jsonb_build_object(
      'queue_wait', 'The 24-hour desk is tucked above Gwangbok shopping streets and the entrance can be tricky on first arrival. Weekend check-in is busiest because the hotel sells strongly; bag storage is the easy fallback. Security is open-lift rather than resort-style, so keep your room number and key private.',
      'best_nights', 'Stay Friday-Saturday for BIFF Square, Jagalchi and Nampo shopping at full glow; choose weekdays for easier lifts, laundry and old-city sightseeing. This is the western Busan base, far from Haeundae and not beside Beomil nightlife, so geography should decide more than hotel programming.',
      'crowd_mix', 'Families, friend groups, couples and repeat visitors from Japan, Singapore and beyond dominate. The hotel is mainstream and busy, not queer-social. LGBTQ+ travellers gain anonymity and central access, while anyone wanting a visible gay scene will still need a ride toward Beomil.',
      'dress_code', 'There is no dress rule. Market-day layers, shopping bags and dinner clothes are all routine. Rooms are generous enough for luggage, and laundry makes light packing possible. Use ordinary discretion in public corridors and do not treat a neutral business hotel as a place for nightlife display.',
      'staff_inclusivity', 'Verified guests praise friendly multilingual help, including swift room solutions during illness. Criticism centres on occasional cleaning misses, soft pillows and inconsistent response to a complaint. Service trends kind and capable, but this remains general hospitality rather than documented queer programming.',
      'venue_classification', 'active_high_value_nampo_hotel_at_6_gwangbok_ro_39beon_gil_with_spacious_rooms_laundry_free_coffee_old_city_market_shopping_access_mixed_family_couple_international_crowd_and_strong_staff_location_consensus',
      'identity_note', 'Aventree Hotel Busan is active at 6 Gwangbok-ro 39beon-gil, Jung-gu. The stored parcel-style address is outdated; the hotel is a mainstream Nampo property, not an LGBTQ+-specific venue.',
      'source_urls', to_jsonb(array['https://www.booking.com/hotel/kr/aventree-busan.en-gb.html','https://www.booking.com/reviews/kr/hotel/aventree-busan.en-gb.html','https://www.trip.com/hotels/busan-hotel-detail-1460900/aventree-hotel-busan/review.html','https://www.agoda.com/hotel-aventree-busan/hotel/busan-kr.html','https://www.tripadvisor.co.uk/Hotel_Review-g297884-d6200589-Reviews-Aventree_Hotel_Busan-Busan.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','hidden_first_arrival_entrance_weekend_checkin_demand_bag_storage_and_open_lift_security_consideration','source_urls',to_jsonb(array['https://www.booking.com/reviews/kr/hotel/aventree-busan.en-gb.html','https://www.trip.com/hotels/busan-hotel-detail-1460900/aventree-hotel-busan/review.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekend_biff_jagalchi_nampo_energy_versus_weekday_laundry_old_city_ease_and_east_city_distance_tradeoff','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/aventree-busan.en-gb.html','https://www.booking.com/reviews/kr/hotel/aventree-busan.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','family_friend_couple_repeat_japanese_singaporean_and_broad_international_mainstream_guest_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/kr/hotel/aventree-busan.en-gb.html','https://www.agoda.com/hotel-aventree-busan/hotel/busan-kr.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_code_with_market_shopping_dinner_style_spacious_luggage_and_laundry_practicality','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/aventree-busan.en-gb.html','https://www.booking.com/reviews/kr/hotel/aventree-busan.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_multilingual_and_exceptional_problem_solving_praise_balanced_against_cleaning_and_complaint_response_variation','source_urls',to_jsonb(array['https://www.booking.com/reviews/kr/hotel/aventree-busan.en-gb.html','https://www.trip.com/hotels/busan-hotel-detail-1460900/aventree-hotel-busan/review.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1773::bigint, jsonb_build_object(
      'queue_wait', 'Do not book or queue for an ibis at this address. The Accor-branded hotel is marked permanently closed and 777 Jungang-daero now trades as Central Seven Hotel. Old booking pages and event PDFs remain online, but they do not establish a current ibis reception.',
      'best_nights', 'The former ibis was useful for Bujeon Market, Seomyeon and the subway directly outside. Those location advantages now belong to the successor hotel, not this brand record. Compare Central Seven on its own current terms; do not transfer old breakfast, loyalty or room promises.',
      'crowd_mix', 'Past guests were budget travellers, couples, business visitors and Accor members. There is no present ibis crowd because the operation has changed identity. The successor appears mainstream and mixed, but it needs its own review record rather than inherited queer-friendly assumptions.',
      'dress_code', 'There is no current ibis dress policy or lobby to enter. Historical business-hotel casual is irrelevant to a closed brand listing. If Queer Atlas adds Central Seven, assess its current facilities, access and guest experience independently instead of relabelling this page.',
      'staff_inclusivity', 'Old reviews ranged from kind, meticulous housekeeping to serious after-hours service failures. None proves the successor team''s conduct. Closing this listing protects travellers and staff alike: hospitality, inclusion and complaint handling must be attributed to the operator actually on site.',
      'venue_classification', 'closed_rebranded_former_ibis_ambassador_busan_city_centre_at_777_jungang_daero_now_operating_as_central_seven_hotel_with_old_accor_pages_and_reviews_not_transferable_to_successor_identity',
      'record_status', 'closed_rebranded_hotel_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring_create_separate_successor_record_if_needed',
      'identity_note', 'ibis Ambassador Busan City Centre is permanently closed. The same address, 777 Jungang-daero, now operates as Central Seven Hotel by Kwon Busan Seomyeon; this record must not redirect users as if the Accor property still existed.',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/1742893/ibis-ambassador-busan-city-centre-permanently-closed','https://www.google.com/maps/search/?api=1&query=ibis+Ambassador+Busan+City+Centre','https://www.expedia.com.sg/Busan-Hotels-Busan-Central-7-Hotel.h4672750.Hotel-Information','https://www.koreanwonexchange.com/exchange/wowpass/199/','https://www.booking.com/hotel/kr/ibis-ambassador-busan.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','permanently_closed_ibis_brand_with_current_central_seven_reception_at_same_address_and_stale_pages_online','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1742893/ibis-ambassador-busan-city-centre-permanently-closed','https://www.expedia.com.sg/Busan-Hotels-Busan-Central-7-Hotel.h4672750.Hotel-Information','https://www.koreanwonexchange.com/exchange/wowpass/199/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_bujeon_seomyeon_location_benefit_not_transferable_to_successor_facilities_breakfast_or_loyalty','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/ibis-ambassador-busan.html','https://www.expedia.com.sg/Busan-Hotels-Busan-Central-7-Hotel.h4672750.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_budget_business_couple_accor_guest_mix_only_with_no_current_ibis_crowd','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1742893/ibis-ambassador-busan-city-centre-permanently-closed','https://www.booking.com/hotel/kr/ibis-ambassador-busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_current_ibis_lobby_or_policy_and_successor_requires_separate_entity_review','source_urls',to_jsonb(array['https://www.expedia.com.sg/Busan-Hotels-Busan-Central-7-Hotel.h4672750.Hotel-Information','https://www.koreanwonexchange.com/exchange/wowpass/199/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','historic_mixed_housekeeping_and_afterhours_service_reviews_not_valid_for_successor_team','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1742893/ibis-ambassador-busan-city-centre-permanently-closed','https://www.expedia.com.sg/Busan-Hotels-Busan-Central-7-Hotel.h4672750.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1768::bigint, jsonb_build_object(
      'queue_wait', 'Check-in is small-hotel simple, but ask when the seawater spa pass becomes valid before planning your day. Beomil Station is about five minutes away. Recent guests report occasional room hot-water trouble, so test the shower early while the desk can still solve it.',
      'best_nights', 'Choose Lamer when Beomil''s gay lanes are the priority: Friday-Saturday puts the bars close enough for an easy return, while a weekday gives the spa and gym more breathing room. The mineral-water complex is the distinctive daytime feature; the hotel itself stays quiet and functional.',
      'crowd_mix', 'Domestic spa users, business travellers, couples and budget-conscious international guests share the property. Queer travellers value proximity to the gay area, but the hotel and public spa are mainstream spaces. Be discreet in gender-segregated facilities and follow posted bathing etiquette.',
      'dress_code', 'The lobby is casual; the attached spa has its own Korean bath rules, where swimwear may not be the norm in gender-segregated wet areas. Ask before entering if that setup affects your comfort. For nightlife, simple clothes and a small bag make the short walk back easier.',
      'staff_inclusivity', 'Most verified guests praise cleanliness, value and kind staff, with the spa a major plus. A smaller set reports rude communication, room hot-water gaps and uneven amenities. LGBTQ+ proximity is not a service guarantee; use the desk for practical issues and the spa only where you feel comfortable.',
      'venue_classification', 'active_value_hotel_and_seawater_spa_at_9_jobang_ro_34beon_gil_near_beomil_station_and_gay_nightlife_with_clean_room_spa_gym_strengths_mainstream_guest_mix_and_service_hot_water_variation',
      'identity_note', 'Lamer Hotel & Seawater Spa Busan is active at 9 Jobang-ro 34beon-gil, Dong-gu. The stored parcel address is obsolete; the property is queer-convenient by location, not LGBTQ+-exclusive.',
      'source_urls', to_jsonb(array['https://lamerhotel.southkrhotel.com/en/','https://www.trip.com/hotels/busan-hotel-detail-1460546/lamer-hotel-seawater-spa-busan/review.html','https://www.expedia.com/Busan-Hotels-La-Mer-Hotel.h6004425.Hotel-Information','https://www.agoda.com/busan-lamer-hotel/reviews/busan-kr.html','https://www.booking.com/reviews/kr/hotel/lamer.en-gb.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','simple_checkin_spa_pass_timing_five_minute_station_access_and_early_room_hot_water_test','source_urls',to_jsonb(array['https://www.trip.com/hotels/busan-hotel-detail-1460546/lamer-hotel-seawater-spa-busan/review.html','https://www.agoda.com/busan-lamer-hotel/reviews/busan-kr.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekend_beomil_gay_nightlife_access_versus_quieter_weekday_spa_gym_use','source_urls',to_jsonb(array['https://www.expedia.com/Busan-Hotels-La-Mer-Hotel.h6004425.Hotel-Information','https://www.booking.com/reviews/kr/hotel/lamer.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','domestic_spa_business_couple_budget_international_mainstream_mix_with_queer_location_convenience_not_exclusivity','source_urls',to_jsonb(array['https://www.trip.com/hotels/busan-hotel-detail-1460546/lamer-hotel-seawater-spa-busan/review.html','https://www.expedia.com/Busan-Hotels-La-Mer-Hotel.h6004425.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','casual_lobby_and_korean_gender_segregated_bath_etiquette_with_comfort_check_before_spa_entry','source_urls',to_jsonb(array['https://lamerhotel.southkrhotel.com/en/','https://www.expedia.com/Busan-Hotels-La-Mer-Hotel.h6004425.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','majority_clean_value_kind_staff_praise_balanced_against_rude_interaction_hot_water_and_amenity_complaints','source_urls',to_jsonb(array['https://www.expedia.com/Busan-Hotels-La-Mer-Hotel.h6004425.Hotel-Information','https://www.agoda.com/busan-lamer-hotel/reviews/busan-kr.html','https://www.booking.com/reviews/kr/hotel/lamer.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1770::bigint, jsonb_build_object(
      'queue_wait', 'Do not make MARU your only plan. One current map-based review source marks the bar permanently closed, while a queer guide still publishes daily hours and an older directory only verifies it in 2018. With no current operator channel found, there is no trustworthy live queue or doorway promise.',
      'best_nights', 'Historically, this was an easy nightly soju stop: Korean side dishes, beer, photos on the walls and a younger crowd before later bars. That remembered role explains its appeal, but it is not enough to recommend a current Friday or Saturday. Use an active Beomil listing instead.',
      'crowd_mix', 'Past descriptions point to younger local gay men, friends sharing food and a small number of foreigners welcomed by staff. It was conversational rather than a dance club. No current crowd can be claimed until the operator or recent independent visitors confirm that the bar is trading.',
      'dress_code', 'The old format called for ordinary casual bar clothes, not a door look. There is no valid current dress code. If a successor appears at the address, confirm its name, pricing and audience before entering; Korean soju-bar customs cannot simply be inherited by a new business.',
      'staff_inclusivity', 'Historical guides called the staff foreigner-friendly and the atmosphere homelike, but the evidence is stale and conflicts with a closure marker. Those compliments should remain history, not present-tense safety assurance. Suppress the record until fresh operator and guest evidence agree.',
      'venue_classification', 'closed_or_unverified_former_young_gay_soju_bar_at_23_beomil_ro_89beon_gil_with_historic_korean_side_dishes_beer_foreigner_friendly_staff_and_conflicting_stale_open_listing_versus_current_permanent_closure_marker',
      'record_status', 'closed_or_unverified_bar_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring_until_operator_and_recent_independent_confirmation',
      'identity_note', 'MARU opened in 2018 at 23 Beomil-ro 89beon-gil. A current map-derived listing marks it permanently closed while Travel Gay still shows hours; no active operator page was found, so closure/unverified status is the safe editorial decision.',
      'source_urls', to_jsonb(array['https://www.travelgay.com/venue/maru-soju-bar','https://wanderlog.com/place/details/6023470/maru','https://www.utopia-asia.com/pusbars.htm','https://www.google.com/maps/search/?api=1&query=MARU+23+Beomil-ro+89beon-gil+Busan']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','conflicting_current_permanent_closure_marker_and_stale_published_hours_without_operator_channel_or_live_door_verification','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6023470/maru','https://www.travelgay.com/venue/maru-soju-bar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','historic_daily_young_soju_side_dish_predrink_role_only_not_current_recommendation','source_urls',to_jsonb(array['https://www.travelgay.com/venue/maru-soju-bar','https://www.utopia-asia.com/pusbars.htm']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','historic_younger_local_gay_friend_group_and_small_foreign_visitor_mix_without_current_crowd_evidence','source_urls',to_jsonb(array['https://www.travelgay.com/venue/maru-soju-bar','https://www.utopia-asia.com/pusbars.htm']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','historic_casual_soju_bar_norm_with_no_valid_current_policy_or_successor_identity_transfer','source_urls',to_jsonb(array['https://www.travelgay.com/venue/maru-soju-bar','https://wanderlog.com/place/details/6023470/maru']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','historic_foreigner_friendly_homelike_staff_description_too_stale_to_verify_current_service','source_urls',to_jsonb(array['https://www.travelgay.com/venue/maru-soju-bar','https://www.utopia-asia.com/pusbars.htm']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1774::bigint, jsonb_build_object(
      'queue_wait', 'The grand lobby handles volume, but beach weekends, holidays and Cimer spa sessions can create check-in and facility queues. Complete arrival details early and reserve any timed experience. The outdoor spa may feel extremely crowded at peak, even when the hotel desk itself moves well.',
      'best_nights', 'Book for a Haeundae weekend when walking straight onto the beach matters, then use a weekday or early-morning spa slot for calm. Summer and festival dates bring maximum atmosphere and maximum bodies. Ocean-facing rooms turn sunrise into the strongest “event” without leaving bed.',
      'crowd_mix', 'Korean families, couples, casino visitors, luxury travellers and international beach guests create a large resort mix. It is mainstream rather than queer-scene based. Same-sex couples gain polished anonymity, but Beomil nightlife is across the city and not part of the hotel''s social world.',
      'dress_code', 'Resort casual covers the lobby; swimwear and robes belong only in designated pool or spa zones, while restaurants and casino call for a cleaner evening look. Bring layers for the sea wind. Check tattoo and gender-segregated facility rules in advance if they affect your comfort.',
      'staff_inclusivity', 'Reviews often praise friendly staff, excellent breakfast and well-run facilities, but service consistency and crowd control dip during peaks. No dedicated LGBTQ+ programme is documented. Expect professional five-star hospitality, state bed preferences plainly and escalate any couple-related assumption.',
      'venue_classification', 'active_large_five_star_haeundae_beachfront_resort_at_296_haeundaehaebyeon_ro_with_ocean_rooms_cimer_spa_pool_casino_breakfast_family_couple_international_mix_and_peak_facility_crowding',
      'identity_note', 'Paradise Hotel Busan is active at 296 Haeundaehaebyeon-ro. It is a mainstream luxury beachfront resort, not an LGBTQ+-specific hotel.',
      'source_urls', to_jsonb(array['https://www.busanparadisehotel.co.kr/','https://www.booking.com/hotel/kr/paradise-busan.html','https://www.booking.com/reviews/kr/hotel/paradise-busan.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297884-d302440-Reviews-Paradise_Hotel_Busan-Busan.html','https://www.reddit.com/r/koreatravel/comments/1rnhoo9/hotel_advice_busan/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','large_lobby_with_beach_holiday_checkin_and_timed_cimer_facility_peak_queue_crowding','source_urls',to_jsonb(array['https://www.busanparadisehotel.co.kr/','https://www.tripadvisor.com/Hotel_Review-g297884-d302440-Reviews-Paradise_Hotel_Busan-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekend_beach_energy_weekday_early_spa_calm_summer_festival_tradeoff_and_ocean_sunrise_room_value','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/paradise-busan.html','https://www.reddit.com/r/koreatravel/comments/1rnhoo9/hotel_advice_busan/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','korean_family_couple_casino_luxury_and_international_beach_guest_mainstream_resort_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/kr/hotel/paradise-busan.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297884-d302440-Reviews-Paradise_Hotel_Busan-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','resort_casual_designated_swim_robe_zones_cleaner_restaurant_casino_style_and_facility_rule_check','source_urls',to_jsonb(array['https://www.busanparadisehotel.co.kr/','https://www.booking.com/hotel/kr/paradise-busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_staff_breakfast_and_facility_praise_with_peak_service_variation_and_no_dedicated_lgbtq_programme','source_urls',to_jsonb(array['https://www.booking.com/reviews/kr/hotel/paradise-busan.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297884-d302440-Reviews-Paradise_Hotel_Busan-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1767::bigint, jsonb_build_object(
      'queue_wait', 'Arrival is polished, but the lobby sits high in the tower and busy breakfast or wedding periods can slow lifts and desks. Send room and view preferences before check-in; marina and bridge orientation materially changes the stay. Valet or taxi is easier than treating the hotel as beach-adjacent.',
      'best_nights', 'Choose a clear evening when Gwangan Bridge lights across the windows and breakfast can repeat the view next morning. Weekdays make the pool, spa and high-floor dining calmer; holiday weekends feel more cinematic but less private. This is a marina retreat, not a doorstep nightlife hotel.',
      'crowd_mix', 'Affluent Korean couples, families, business guests, Hyatt loyalists and international luxury travellers share a quiet, design-led tower. It is mainstream rather than queer-social. Same-sex couples blend naturally into the mix, while Busan''s gay bars require a deliberate cross-city trip.',
      'dress_code', 'Refined casual is ideal: relaxed tailoring, clean trainers and a smarter dinner layer. Pool and spa areas have separate rules, while the Living Room and Dining Room feel polished without demanding black tie. Pack for photographs, but let comfort win over costume in the calm marble spaces.',
      'staff_inclusivity', 'The dominant pattern is exceptional: attentive staff, careful recovery of lost property and thoughtful repeat-guest recognition. A few reviews describe missed room-service orders or uneven individual warmth. No queer programme is claimed, so judge inclusion through professional handling of your actual booking.',
      'venue_classification', 'active_ultra_premium_marine_city_hotel_at_51_marine_city_1_ro_with_gwangan_bridge_marina_ocean_views_large_rooms_pool_spa_high_floor_dining_affluent_mixed_guest_profile_and_strong_service_consensus',
      'identity_note', 'Park Hyatt Busan is active at 51 Marine City 1-ro, Haeundae-gu. It is a mainstream luxury hotel with strong privacy and service reviews, not an LGBTQ+-exclusive property.',
      'source_urls', to_jsonb(array['https://www.hyatt.com/park-hyatt/en-US/pusph-park-hyatt-busan','https://www.booking.com/hotel/kr/park-hyatt-busan.en-gb.html','https://www.booking.com/reviews/kr/hotel/park-hyatt-busan.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297884-d3813531-Reviews-Park_Hyatt_Busan-Busan.html','https://www.reddit.com/r/hyatt/comments/1lwvrmj/positive_experience_at_park_hyatt_busan_bag_found/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','high_tower_lobby_lift_breakfast_wedding_pressure_with_advance_room_view_request_and_vehicle_access_advantage','source_urls',to_jsonb(array['https://www.hyatt.com/park-hyatt/en-US/pusph-park-hyatt-busan','https://www.booking.com/reviews/kr/hotel/park-hyatt-busan.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','clear_gwangan_bridge_evening_weekday_pool_spa_dining_calm_and_holiday_cinematic_privacy_tradeoff','source_urls',to_jsonb(array['https://www.booking.com/hotel/kr/park-hyatt-busan.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297884-d3813531-Reviews-Park_Hyatt_Busan-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','affluent_korean_couple_family_business_hyatt_loyalist_and_international_luxury_mainstream_mix','source_urls',to_jsonb(array['https://www.booking.com/reviews/kr/hotel/park-hyatt-busan.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g297884-d3813531-Reviews-Park_Hyatt_Busan-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','refined_casual_clean_trainer_smart_dinner_layer_and_separate_pool_spa_rules_without_black_tie_requirement','source_urls',to_jsonb(array['https://www.hyatt.com/park-hyatt/en-US/pusph-park-hyatt-busan','https://www.tripadvisor.com/Hotel_Review-g297884-d3813531-Reviews-Park_Hyatt_Busan-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','exceptional_attentive_lost_property_and_repeat_guest_service_consensus_balanced_against_isolated_order_and_warmth_lapses','source_urls',to_jsonb(array['https://www.booking.com/reviews/kr/hotel/park-hyatt-busan.en-gb.html','https://www.reddit.com/r/hyatt/comments/1lwvrmj/positive_experience_at_park_hyatt_busan_bag_found/','https://www.tripadvisor.com/Hotel_Review-g297884-d3813531-Reviews-Park_Hyatt_Busan-Busan.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (1770,1773);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1772,1765,1776,1773,1768,1770,1774,1767)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
