-- Queer Atlas venue intelligence: global review-led editorial pass, batch 55.
-- Eight Cape Town and Caracas records checked against current official pages, local reporting, listings and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, never in reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1308::bigint, jsonb_build_object(
      'queue_wait', 'This is a beach bar, not a velvet-rope club. Lunch is usually easy; sunset, happy hour and weekend celebrations can pack the terrace and push service into a slower rhythm. If the sea view matters, arrive before the after-work crowd claims the outdoor tables.',
      'best_nights', 'Friday and Saturday carry the most energy, sometimes with a house DJ and plenty of dancing after dinner. A sunny late afternoon is the sweeter local move: pizza, cold drinks and the Blouberg sunset before the room loosens into an unforced queer-friendly night.',
      'crowd_mix', 'Blouberg regulars, surfers, skaters and a notably strong queer and lesbian following share the tables with sunset tourists and birthday groups. It feels local-first and mixed rather than a formal LGBTQ+ venue; later weekends are younger, louder and more visibly celebratory.',
      'dress_code', 'Come in beach-to-bar clothes: denim, trainers, shorts, summer layers or a playful night-out look all fit. There is no fashion inspection. Wind off the bay is the only real stylist, so bring one warm layer if you plan to keep the sunset table after dark.',
      'staff_inclusivity', 'Community accounts repeatedly describe queer staff, lesbian ownership and bouncers who take homophobia, transphobia and aggressive behaviour seriously. Food and floor teams also earn warm reviews. Management disputes appear in a minority of feedback, but the welcome is a defining strength.',
      'venue_classification', 'active_queer_welcoming_lesbian_owned_blouberg_beach_bar_with_sunset_terrace_food_weekend_dancing_local_regulars_and_strong_boundary_setting_against_homophobia_transphobia_and_aggression',
      'identity_note', 'The Boardhouse is an all-day Blouberg beach bar with a substantial queer and lesbian regular community, not a dedicated nightclub. After 19:00, community reports indicate an over-21 door policy.',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/356694/board-house','https://www.reddit.com/r/capetown/comments/1ien4w2','https://www.travelgay.com/venue/the-boardhouse','https://www.wcla.gov.za/sites/default/files/2025-02/Valid%20Licences%20as%20at%203%20February%202025.pdf','https://www.reddit.com/r/capetown/comments/1tp9ovb']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','beach_bar_without_club_queue_and_sunset_happy_hour_weekend_terrace_capacity_pressure','source_urls',to_jsonb(array['https://wanderlog.com/place/details/356694/board-house','https://www.travelgay.com/venue/the-boardhouse']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_house_dj_dancing_and_sunset_food_drink_pattern','source_urls',to_jsonb(array['https://www.reddit.com/r/capetown/comments/1ien4w2','https://wanderlog.com/place/details/356694/board-house']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','blouberg_local_surfer_skater_queer_lesbian_tourist_and_celebration_mix','source_urls',to_jsonb(array['https://www.reddit.com/r/capetown/comments/1ien4w2','https://www.travelgay.com/venue/the-boardhouse']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_reported_code_with_casual_beach_weather_practical_style','source_urls',to_jsonb(array['https://wanderlog.com/place/details/356694/board-house','https://www.travelgay.com/venue/the-boardhouse']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','queer_staff_lesbian_ownership_and_active_bouncer_boundary_consensus_balanced_against_minority_management_complaints','source_urls',to_jsonb(array['https://www.reddit.com/r/capetown/comments/1ien4w2','https://wanderlog.com/place/details/356694/board-house']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1304::bigint, jsonb_build_object(
      'queue_wait', 'There is no nightlife queue: this is a serviced-apartment hotel with a staffed reception. Check-in can bunch around standard afternoon arrival, while lifts and the rooftop feel busiest near sunset. Restaurant bookings are wiser than expecting a walk-in table above the city.',
      'best_nights', 'Use it as a De Waterkant base rather than the night itself. Sunset drinks on the rooftop work before dinner, then the neighbourhood is at your feet. Weekends feel leisure-led; weekdays bring more business travellers and make the generous suites especially calm for longer stays.',
      'crowd_mix', 'International couples, families, business guests and longer-stay travellers dominate. Its position beside queer De Waterkant makes it convenient for LGBTQ+ visitors, but the property is mainstream rather than community-led. Expect more tourists than local social traffic inside the hotel.',
      'dress_code', 'Lobby and breakfast are relaxed-smart: linen, resort wear, work clothes and polished evening looks all pass naturally. Pool and rooftop spaces suit elevated holiday casual. Nothing suggests a door test; dress for heat, air-conditioning and wherever you are heading after sunset.',
      'staff_inclusivity', 'Recent guests overwhelmingly praise warm, attentive service, fast help and teams who remember details; the staff score is a standout. A smaller thread describes cool reception or weak follow-up, so ask directly when something matters. No dedicated queer training claim could be verified.',
      'venue_classification', 'active_mainstream_luxury_serviced_apartment_hotel_on_de_waterkant_edge_with_spacious_suites_rooftop_dining_sunset_views_business_and_international_leisure_mix_and_strong_general_service_consensus',
      'identity_note', 'The Capital Mirage is not a queer-specific hotel. Its value to Queer Atlas is location: it sits on the edge of De Waterkant, within easy reach of the neighbourhood nightlife and central Cape Town.',
      'source_urls', to_jsonb(array['https://thecapital.co.za/mirage/','https://compendium.thecapital.co.za/landing/mirage/dining','https://www.booking.com/reviews/za/hotel/the-capital-mirage.html','https://www.tripadvisor.com/Hotel_Review-g312659-d8319268-Reviews-The_Capital_Mirage_Hotel-Cape_Town_Central_Western_Cape.html','https://thecapital.co.za/docs/factsheets/The%20Capital%20Mirage%20E-fact%20Sheet%2014.03.2023.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','hotel_checkin_rooftop_and_restaurant_peak_flow_not_club_queue','source_urls',to_jsonb(array['https://thecapital.co.za/mirage/','https://compendium.thecapital.co.za/landing/mirage/dining']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','sunset_rooftop_de_waterkant_base_and_weekend_leisure_weekday_business_variation','source_urls',to_jsonb(array['https://thecapital.co.za/mirage/','https://compendium.thecapital.co.za/landing/mirage/dining']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','international_couple_family_business_and_long_stay_mix_at_mainstream_hotel_near_queer_district','source_urls',to_jsonb(array['https://www.booking.com/reviews/za/hotel/the-capital-mirage.html','https://thecapital.co.za/docs/factsheets/The%20Capital%20Mirage%20E-fact%20Sheet%2014.03.2023.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','relaxed_smart_lobby_resort_pool_and_rooftop_style_without_reported_door_test','source_urls',to_jsonb(array['https://thecapital.co.za/mirage/','https://compendium.thecapital.co.za/landing/mirage/dining']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_warm_attentive_service_consensus_balanced_against_minor_cool_reception_followup_reports_and_no_verified_queer_training','source_urls',to_jsonb(array['https://www.booking.com/reviews/za/hotel/the-capital-mirage.html','https://www.tripadvisor.com/Hotel_Review-g312659-d8319268-Reviews-The_Capital_Mirage_Hotel-Cape_Town_Central_Western_Cape.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1315::bigint, jsonb_build_object(
      'queue_wait', 'Reception is intimate rather than congested. The pressure point is the little rooftop Skybar: sunset tables disappear quickly in warm months, while the bar normally closes for the wet winter stretch from June to September. Confirm access before building an evening around it.',
      'best_nights', 'A warm Friday or Saturday suits rooftop cocktails before walking into De Waterkant; a quiet weekday better reveals the boutique character and breakfast. The best plan changes with weather, because the Skybar is seasonal. Rooms facing lively streets can hear the neighbourhood at night.',
      'crowd_mix', 'Couples, design-minded visitors and independent travellers make up the hotel crowd, with LGBTQ+ guests drawn by its De Waterkant address. It is a small mainstream boutique hotel, not a gay resort. Tourists outweigh locals upstairs; locals are more likely to appear for drinks.',
      'dress_code', 'Cape Town boutique casual lands perfectly: linen, denim, a sharp shirt or an expressive dinner look. The rooftop rewards polish but publishes no dress rule. Pack for wind and sudden weather, and choose practical shoes if the rest of your night continues through the steep city streets.',
      'staff_inclusivity', 'The strongest review thread is personal care: guests call the team exceptionally friendly, available and quick with local help. That small-hotel warmth matters for queer couples seeking an easy stay. Compact rooms, street noise and seasonal bar closure are more common caveats than hospitality.',
      'venue_classification', 'active_small_mainstream_boutique_hotel_in_de_waterkant_with_seasonal_rooftop_skybar_strong_location_and_staff_reviews_compact_rooms_possible_street_noise_and_lgbtq_relevance_from_neighbourhood_access',
      'identity_note', 'The Grey Hotel is a general boutique property in Cape Town’s historically queer De Waterkant district. Its Skybar is weather-dependent and normally closes annually from June through September.',
      'source_urls', to_jsonb(array['https://thegreyhotel.co.za/','https://www.booking.com/hotel/za/the-grey.html','https://www.booking.com/reviews/za/hotel/the-grey.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g312659-d11889653-Reviews-The_Grey_Hotel-Cape_Town_Central_Western_Cape.html']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_reception_with_warm_season_sunset_skybar_capacity_and_june_september_closure','source_urls',to_jsonb(array['https://thegreyhotel.co.za/','https://www.booking.com/reviews/za/hotel/the-grey.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','warm_weekend_rooftop_predrink_quiet_weekday_boutique_and_weather_noise_variation','source_urls',to_jsonb(array['https://thegreyhotel.co.za/','https://www.booking.com/reviews/za/hotel/the-grey.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','couple_design_independent_and_lgbtq_neighbourhood_visitor_mix_at_mainstream_boutique_hotel','source_urls',to_jsonb(array['https://www.booking.com/hotel/za/the-grey.html','https://www.tripadvisor.co.uk/Hotel_Review-g312659-d11889653-Reviews-The_Grey_Hotel-Cape_Town_Central_Western_Cape.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_reported_code_with_boutique_casual_rooftop_weather_and_walking_practicality','source_urls',to_jsonb(array['https://thegreyhotel.co.za/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','exceptionally_friendly_available_local_help_consensus_with_facility_not_hospitality_caveats','source_urls',to_jsonb(array['https://www.booking.com/reviews/za/hotel/the-grey.en-gb.html','https://www.tripadvisor.co.uk/Hotel_Review-g312659-d11889653-Reviews-The_Grey_Hotel-Cape_Town_Central_Western_Cape.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (668::bigint, jsonb_build_object(
      'queue_wait', 'Friday and Saturday build late; before 23:00 is the easier door, while themed nights and Pride dates can leave a Strand Street line. Cover and re-entry conditions can change, so check the current post and keep payment proof. Inside, the bar queue grows faster than the doorway.',
      'best_nights', 'Saturday delivers the biggest commercial-pop and house release; Friday can feel looser and more social. Drag, dancers and special themes change the room, so follow the programme rather than habit. Arrive early for space, after midnight for full-volume Cape Town queer nightlife.',
      'crowd_mix', 'The floor is predominantly young gay men, with queer friends, women, allies, travellers and straight groups in the mix. Locals still set the rhythm, but the central address brings visitors. It is broad enough for mixed parties, though current community voices describe it as male-centred.',
      'dress_code', 'There is no published formal code. Dance-ready trainers, fitted clubwear, colour, mesh and a polished casual look all make sense; costume energy rises on theme nights. Keep valuables close and avoid anything you cannot move in—the room can become hot, tight and wonderfully unruly.',
      'staff_inclusivity', 'Many guests praise friendly bartenders, energetic performers and a door that welcomes mixed groups. Others report uneven service, pricing confusion and weak handling of safety concerns. The venue is visibly queer, but trans and gender-diverse guests should not mistake visibility for guaranteed consistency.',
      'venue_classification', 'active_central_cape_town_lgbtq_nightclub_with_friday_saturday_commercial_pop_house_drag_dancers_young_gay_male_core_mixed_visitors_theme_nights_and_materially_mixed_service_safety_consensus',
      'identity_note', 'Pink Candy is a current LGBTQ+ nightclub at 120 Strand Street. It has a broad queer-facing programme but community discussion consistently characterises the regular crowd as more gay-male-centred than lesbian-centred.',
      'source_urls', to_jsonb(array['https://www.capetown.gov.za/family%20and%20home/meet-the-city/city-council/meeting-calendar/subcouncil-meeting-detail/subcouncil-resolution?MeetingItemId=158904','https://www.capetownmagazine.com/nightclubs','https://www.travelgay.com/venue/the-pink-candy-night-club','https://qlist.app/venues/Cape-Town/The-Pink-Candy-Night-Club/VVVZT3BYM1VpM0ZnQjZSb0hRdDFadw','https://iol.co.za/travel/south-africa/2026-07-10-two-cape-town-venues-make-time-outs-global-list-of-the-worlds-greatest-lgbtq-nightlife-spots/','https://wanderlog.com/place/details/871194','https://www.reddit.com/r/capetown/comments/1u7lls3','https://www.reddit.com/r/capetown/comments/1f0ug94']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','late_weekend_theme_pride_door_and_internal_bar_pressure_with_variable_cover','source_urls',to_jsonb(array['https://www.travelgay.com/venue/the-pink-candy-night-club','https://wanderlog.com/place/details/871194']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','saturday_peak_friday_social_and_programme_led_drag_dancer_theme_variation','source_urls',to_jsonb(array['https://www.capetownmagazine.com/nightclubs','https://qlist.app/venues/Cape-Town/The-Pink-Candy-Night-Club/VVVZT3BYM1VpM0ZnQjZSb0hRdDFadw','https://iol.co.za/travel/south-africa/2026-07-10-two-cape-town-venues-make-time-outs-global-list-of-the-worlds-greatest-lgbtq-nightlife-spots/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_gay_male_core_with_queer_women_ally_traveller_and_straight_group_mix','source_urls',to_jsonb(array['https://www.reddit.com/r/capetown/comments/1u7lls3','https://www.reddit.com/r/capetown/comments/1f0ug94','https://wanderlog.com/place/details/871194']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_published_formal_code_with_dance_ready_expressive_theme_led_style_and_capacity_practicality','source_urls',to_jsonb(array['https://www.travelgay.com/venue/the-pink-candy-night-club','https://www.capetownmagazine.com/nightclubs']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_bar_performer_and_mixed_group_praise_balanced_against_service_price_safety_and_gender_consistency_concerns','source_urls',to_jsonb(array['https://wanderlog.com/place/details/871194','https://www.reddit.com/r/capetown/comments/1u7lls3']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (670::bigint, jsonb_build_object(
      'queue_wait', 'Do not look for a Cape Town door. The Rec Room operates in Ferndale, Randburg, and Queer Atlas already has that Johannesburg venue under record 1598. This duplicate has no valid Cape Town address, hours or queue. Hide it before it sends anyone across the wrong city.',
      'best_nights', 'There is no Cape Town programme to recommend. The real Johannesburg sauna publishes its own admission schedule and should be read on record 1598. Keeping two city identities would split reviews, misstate distance and turn useful venue intelligence into unsafe directions.',
      'crowd_mix', 'No Cape Town crowd belongs to this record. Reviews describe the actual Randburg venue as a men-focused sauna with local regulars and visitors, but that evidence belongs only to its Johannesburg page. Do not recycle those ratings into a fictional Cape Town branch.',
      'dress_code', 'No Cape Town dress policy exists. The Johannesburg business has sauna-specific admission and facility norms on its official site; use record 1598 for those details. This page should disappear from maps, recommendations and city totals rather than imitate a second venue.',
      'staff_inclusivity', 'There is no Cape Town team to assess. Feedback for the Randburg operation ranges from friendly welcome to complaints about bar manner and maintenance, all of which must remain attached to the real Johannesburg entity. The inclusive action here is correcting the database.',
      'venue_classification', 'duplicate_wrong_city_record_for_active_men_focused_sauna_in_ferndale_randburg_johannesburg_already_represented_by_place_1598_with_no_verified_cape_town_branch_address_team_or_programme',
      'record_status', 'duplicate_wrong_city_hide_from_search_maps_sitemap_city_counts_recommendations_and_current_venue_intelligence_scoring',
      'identity_note', 'The Rec Room is in Ferndale, Randburg, Johannesburg and already exists as Queer Atlas place 1598. No evidence supports a second Cape Town location.',
      'source_urls', to_jsonb(array['https://recroom.co.za/','https://recroom.co.za/admission-charges/','https://www.gayout.com/africa/south-africa/sandton/bars/the-rec-room','https://rsa.worldorgs.com/catalog/randburg/gay-bar/the-rec-room','https://www.top-rated.online/cities/Randburg/place/p/3450290/The%2BRec%2BRoom','https://www.queeratlas.app/johannesburg/venues/the-rec-room--1598']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_cape_town_door_and_verified_randburg_johannesburg_identity_already_on_place_1598','source_urls',to_jsonb(array['https://recroom.co.za/','https://www.queeratlas.app/johannesburg/venues/the-rec-room--1598']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','no_cape_town_programme_and_official_johannesburg_schedule_belongs_to_existing_record','source_urls',to_jsonb(array['https://recroom.co.za/admission-charges/','https://www.queeratlas.app/johannesburg/venues/the-rec-room--1598']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','no_cape_town_crowd_and_randburg_review_identity_must_not_be_duplicated','source_urls',to_jsonb(array['https://www.gayout.com/africa/south-africa/sandton/bars/the-rec-room','https://rsa.worldorgs.com/catalog/randburg/gay-bar/the-rec-room']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_cape_town_policy_and_sauna_norms_belong_only_to_verified_johannesburg_entity','source_urls',to_jsonb(array['https://recroom.co.za/admission-charges/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_cape_town_team_with_mixed_randburg_service_maintenance_reviews_reserved_for_real_record','source_urls',to_jsonb(array['https://www.gayout.com/africa/south-africa/sandton/bars/the-rec-room','https://www.top-rated.online/cities/Randburg/place/p/3450290/The%2BRec%2BRoom']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1313::bigint, jsonb_build_object(
      'queue_wait', 'This tiny vegan counter has no formal line, but lunch and sunny weekend hours can use every seat quickly. Most people order and move on; takeaway is the smoothest choice when the handful of stools are full. Allow a little time because the food is made with care, not assembly-line speed.',
      'best_nights', 'It closes in the evening, so think bright lunch rather than nightlife. Go after a Sea Point walk for a burger, smoothie or sprouted plate, then take it toward the promenade. Mid-afternoon is calmer than the lunch peak and gives the small team more room to talk you through the menu.',
      'crowd_mix', 'Sea Point locals, vegans, wellness regulars, curious omnivores and travellers form an easy daytime mix. The atmosphere is broadly LGBTQ-friendly rather than explicitly queer. Locals give it its neighbourhood warmth; tourists arrive through plant-based recommendations and promenade traffic.',
      'dress_code', 'Come exactly as the day finds you: gym kit, beach layers, sandals, work clothes or a colourful casual look. There is no door and no performance of polish. The room is tiny, so comfort and a light bag beat elaborate layers—especially if you end up eating outside.',
      'staff_inclusivity', 'The owner-led welcome is a recurring reason people return: reviews describe patient menu guidance, generous conversation and food made with visible pride. Some waits reflect the small kitchen, not indifference. Listings also identify the cafe as LGBTQ-friendly and a trans-safe space.',
      'venue_classification', 'active_tiny_owner_led_african_vegan_cafe_and_takeaway_in_three_anchor_bay_with_sprouted_organic_food_local_wellness_and_traveller_mix_strong_personal_service_consensus_and_lgbtq_trans_safe_listing',
      'identity_note', 'The Sunshine Food Sprouting Co is a small daytime vegan cafe and takeaway, not a nightlife venue. Its queer relevance is an explicitly LGBTQ-friendly and trans-safe welcome rather than queer-only programming.',
      'source_urls', to_jsonb(array['https://restaurantguru.com/The-Sunshine-Food-Sprouting-Co-Cape-Town','https://www.ubereats.com/za/store/the-sunshine-food-sprouting-co-vegan-cafe/pcVHOJx0STKc3UWf1uwbGw','https://blog.rhinoafrica.com/2025/10/01/cape-town-vegetarian-vegan/','https://www.thehealthfoundation.org.za/wp-content/uploads/2025/05/Learner-Guide-for-Health-Plant-based-Cooking-290119.pdf','https://the-sunshine-food-sprouting-co-african-vegan-cafe.goto-where.com/','https://www.reddit.com/r/capetown/comments/1bs4rwz']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','tiny_counter_limited_seating_lunch_weekend_pressure_takeaway_and_small_kitchen_timing','source_urls',to_jsonb(array['https://restaurantguru.com/The-Sunshine-Food-Sprouting-Co-Cape-Town','https://blog.rhinoafrica.com/2025/10/01/cape-town-vegetarian-vegan/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','daytime_only_lunch_promenade_takeaway_and_quieter_midafternoon_pattern','source_urls',to_jsonb(array['https://www.ubereats.com/za/store/the-sunshine-food-sprouting-co-vegan-cafe/pcVHOJx0STKc3UWf1uwbGw','https://restaurantguru.com/The-Sunshine-Food-Sprouting-Co-Cape-Town']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','sea_point_local_vegan_wellness_omnivore_traveller_and_broad_lgbtq_friendly_day_mix','source_urls',to_jsonb(array['https://blog.rhinoafrica.com/2025/10/01/cape-town-vegetarian-vegan/','https://the-sunshine-food-sprouting-co-african-vegan-cafe.goto-where.com/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_door_or_code_with_gym_beach_work_and_casual_small_space_practicality','source_urls',to_jsonb(array['https://restaurantguru.com/The-Sunshine-Food-Sprouting-Co-Cape-Town']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','owner_led_patient_generous_menu_help_consensus_and_explicit_lgbtq_friendly_trans_safe_listing','source_urls',to_jsonb(array['https://restaurantguru.com/The-Sunshine-Food-Sprouting-Co-Cape-Town','https://the-sunshine-food-sprouting-co-african-vegan-cafe.goto-where.com/','https://www.thehealthfoundation.org.za/wp-content/uploads/2025/05/Learner-Guide-for-Health-Plant-based-Cooking-290119.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (923::bigint, jsonb_build_object(
      'queue_wait', 'This long-running men’s sauna is generally walk-in, with no club-style queue. Weekends bring the busiest changing room and shared facilities; weekday mornings are calmer. Reviews call it affordable and central, but also basic, so expect function over spa theatre and ask the current tariff at entry.',
      'best_nights', 'Daytime is the plan: the published rhythm runs morning to early evening, not after-hours. Saturday and Sunday offer the widest mix and most social energy; a weekday visit is quieter and better for exploring without a crowd. Verify hours before crossing Caracas, as directory times vary.',
      'crowd_mix', 'A broad age and body mix of local gay and bisexual men forms the core, with occasional visitors finding it through Sabana Grande. It is male-focused rather than a general LGBTQ+ wellness space. The crowd grows more varied on weekends, while regulars give weekdays a familiar tone.',
      'dress_code', 'Street clothes end at the locker. Inside, towel-and-sandal practicality matters more than body type or style; bring personal essentials and do not treat nudity as consent. Facilities include dry and steam heat, bar and darker social areas, but reviews warn that finishes can feel worn.',
      'staff_inclusivity', 'Its longevity and returning clientele suggest a team accustomed to discreet male guests, and positive reviews value the affordable, unpretentious welcome. Feedback is thinner on individual staff care and more critical of ageing facilities. Ask clearly about rules, storage and services before changing.',
      'venue_classification', 'active_long_running_affordable_men_focused_gay_sauna_in_sabana_grande_with_dry_and_steam_heat_bar_food_massage_social_and_dark_areas_broad_local_age_mix_weekend_peak_and_basic_ageing_facility_consensus',
      'identity_note', 'Baños Turcos Suecos is a men-focused gay sauna, reportedly operating for more than four decades. Public directories disagree slightly on hours, so same-day verification is advisable.',
      'source_urls', to_jsonb(array['https://www.facebook.com/banosturcossuecos/','https://qlist.app/venues/Caracas/Banos-Turcos-Suecos-CA/eUo1SmRVUVpnUVVnSG1FZExZWkpnQQ/es','https://spartacus.gayguide.travel/saunas/southamerica/venezuela/caracas-distritocapital/9543_Ba','https://gaytravelr.com/venezuela/caracas/saunas/swedish-turkish-baths-gay-sauna-sabana-grande']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','walkin_sauna_without_club_queue_weekend_facility_peak_weekday_calm_and_affordable_basic_consensus','source_urls',to_jsonb(array['https://qlist.app/venues/Caracas/Banos-Turcos-Suecos-CA/eUo1SmRVUVpnUVVnSG1FZExZWkpnQQ/es','https://gaytravelr.com/venezuela/caracas/saunas/swedish-turkish-baths-gay-sauna-sabana-grande']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','daytime_operation_weekend_social_peak_weekday_quiet_and_variable_directory_hours','source_urls',to_jsonb(array['https://www.facebook.com/banosturcossuecos/','https://spartacus.gayguide.travel/saunas/southamerica/venezuela/caracas-distritocapital/9543_Ba','https://gaytravelr.com/venezuela/caracas/saunas/swedish-turkish-baths-gay-sauna-sabana-grande']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','broad_age_body_local_gay_bisexual_male_core_with_weekend_visitor_variation','source_urls',to_jsonb(array['https://qlist.app/venues/Caracas/Banos-Turcos-Suecos-CA/eUo1SmRVUVpnUVVnSG1FZExZWkpnQQ/es','https://gaytravelr.com/venezuela/caracas/saunas/swedish-turkish-baths-gay-sauna-sabana-grande']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','locker_towel_sandal_sauna_norms_with_dry_steam_bar_dark_area_and_ageing_finish_context','source_urls',to_jsonb(array['https://gaytravelr.com/venezuela/caracas/saunas/swedish-turkish-baths-gay-sauna-sabana-grande','https://qlist.app/venues/Caracas/Banos-Turcos-Suecos-CA/eUo1SmRVUVpnUVVnSG1FZExZWkpnQQ/es']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','long_running_discreet_unpretentious_returning_guest_signal_with_limited_staff_specific_evidence_and_facility_caveats','source_urls',to_jsonb(array['https://www.facebook.com/banosturcossuecos/','https://qlist.app/venues/Caracas/Banos-Turcos-Suecos-CA/eUo1SmRVUVpnUVVnSG1FZExZWkpnQQ/es']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (922::bigint, jsonb_build_object(
      'queue_wait', 'Big guest-DJ and Pride-adjacent dates can form a late line; an ordinary Wednesday is far easier. The room comes alive after midnight, but arriving around 23:00 gives you time to settle before the floor tightens. Cover, reservations and operating nights move with the event calendar.',
      'best_nights', 'Friday and Saturday carry the fullest electronic and Latin-pop pulse, while a named international DJ can transform the whole week. The club’s women-led roots still matter, though current parties are broadly queer. Follow the live flyer—the best night is the one with a bill you actually want.',
      'crowd_mix', 'Queer women and lesbian regulars remain part of its identity, joined by gay men, gender-diverse friends, allies and visiting clubbers. Caracas locals outnumber tourists; major bookings widen the circle. Some nights feel community-first, others like a polished mixed electronic party.',
      'dress_code', 'No stable formal code is published. Caracas night-out polish, breathable dancewear, trainers and expressive queer style all appear; headline dates invite a sharper look. Confirm any theme before leaving, carry only what you need and agree the ride home before the late finish.',
      'staff_inclusivity', 'Positive reviews describe respectful, friendly attention and a comfortable place to dance, while others mention valet friction, music choices or uneven service. Its LGBTQ+ identity is established, but current event production varies. Keep the bill clear and raise any problem early, not at closing.',
      'venue_classification', 'active_caracas_lgbtq_nightclub_with_lesbian_and_queer_women_roots_broad_current_queer_mix_electronic_latin_pop_guest_dj_events_late_weekend_peak_and_mixed_but_generally_positive_service_consensus',
      'identity_note', 'Copas is currently active in El Rosal and hosts public events. A temporary 2023 administrative closure should not be presented as current; subsequent listings and 2026 ticketed events confirm later operation.',
      'source_urls', to_jsonb(array['https://www.goliiive.com/xpaceisland','https://ege.electronicgroove.com/xpace-e-island-beats-se-unen-para-traer-a-giorgio-maulini-a-caracas/','https://infoguia.com/is.asp?ciud=41&clte=99676359&emp=copas-disco-club-caracas','https://www.gayout.com/south-america/venezuela/caracas/bars/copa-s','https://caracas.gaycities.com/bars/311026-copas','https://www.ntn24.com/noticias-actualidad/reapertura-de-famosa-disco-gay-en-caracas-termino-en-cierre-legal-412486']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','guest_dj_and_pride_date_late_line_ordinary_midweek_ease_midnight_peak_and_calendar_led_cover','source_urls',to_jsonb(array['https://www.goliiive.com/xpaceisland','https://infoguia.com/is.asp?ciud=41&clte=99676359&emp=copas-disco-club-caracas']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_peak_named_international_dj_variation_and_live_flyer_priority','source_urls',to_jsonb(array['https://www.goliiive.com/xpaceisland','https://ege.electronicgroove.com/xpace-e-island-beats-se-unen-para-traer-a-giorgio-maulini-a-caracas/','https://www.gayout.com/south-america/venezuela/caracas/bars/copa-s']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','queer_women_lesbian_root_with_gay_gender_diverse_ally_local_and_guest_booking_visitor_mix','source_urls',to_jsonb(array['https://caracas.gaycities.com/bars/311026-copas','https://www.gayout.com/south-america/venezuela/caracas/bars/copa-s']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_stable_published_code_with_polished_breathable_expressive_headliner_variation_and_late_trip_practicality','source_urls',to_jsonb(array['https://www.goliiive.com/xpaceisland','https://infoguia.com/is.asp?ciud=41&clte=99676359&emp=copas-disco-club-caracas']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','respectful_friendly_comfort_praise_balanced_against_valet_music_and_service_variation','source_urls',to_jsonb(array['https://www.gayout.com/south-america/venezuela/caracas/bars/copa-s','https://caracas.gaycities.com/bars/311026-copas']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (670);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1308,1304,1315,668,670,1313,923,922)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
