-- Queer Atlas venue intelligence: global review-led editorial pass, batch 44.
-- Two Boston records and six Brighton records, checked 2026-08-06.
-- Includes current-address warnings, one duplicate club component and one non-venue neighbourhood record.

begin;

with reviewed(id, patch) as (
  values
    (1939::bigint, jsonb_build_object(
      'queue_wait', 'This small, long-awaited sapphic bar can pull a serious line: opening-era and Pride reports describe 100 people or more, and regulars still joke about the wait. Arrive before 9pm for a normal night, reserve drag brunch, and buy ticketed-event entry early. A quiet weekday can be almost the opposite.',
      'best_nights', 'Weekend drag brunch starts bright and communal; Thursday through Saturday brings the late-night rush. For conversation without the crush, try a game night, book club, bingo, over-40 mixer or another calendar-led weekday. Pride is huge but least intimate—choose it for spectacle, not an easy first drink.',
      'crowd_mix', 'Queer women, lesbians, trans and non-binary people are the heart of the room, with a near-all-LGBTQ+ crowd reported on busy nights. Ages and identities widen through brunches and mixers. Respectful allies may attend, but this is one of Boston’s rare femme-centred spaces, not a generic bar waiting to be taken over.',
      'dress_code', 'Casual and expressive wins: denim, boots, glitter, soft masc, high femme and whatever feels like your night. Brunch guests often dress for the show, but there is no formal rule. Bring valid ID, tip performers and read ticket details. The real door test is respecting the sapphic, trans and non-binary centre of gravity.',
      'staff_inclusivity', 'Guests praise warm servers, quick food and teams who make change for performer tips; management has also defended trans women when harassment was reported. Others describe slow bar service, confusing downstairs waits and mixed welcome. It is community-built and meaningful, but busy-night communication still needs care.',
      'venue_classification', 'active_2024_boston_sapphic_queer_bar_centring_lesbian_trans_and_nonbinary_community_with_drag_brunch_weekly_mixers_games_shows_pride_events_and_highly_variable_queues',
      'source_urls', to_jsonb(array['https://www.danisqueerbar.com/','https://www.danisqueerbar.com/drag-brunch','https://www.opentable.com/r/danis-queer-bar-boston','https://wanderlog.com/place/details/11141838/danis-queer-bar','https://www.timeout.com/boston/bars/danis-queer-bar','https://www.reddit.com/r/boston/comments/1frgwv1/has_anyone_been_to_danis_queer_bar_yet/','https://www.axios.com/local/boston/2024/09/12/danis-queer-bar-boston-opens']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_room_hundred_plus_peak_line_pride_pressure_early_arrival_brunch_reservation_and_quiet_weekday_variation','source_urls',to_jsonb(array['https://www.reddit.com/r/boston/comments/1frgwv1/has_anyone_been_to_danis_queer_bar_yet/','https://www.danisqueerbar.com/drag-brunch','https://www.opentable.com/r/danis-queer-bar-boston']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekend_drag_brunch_late_thursday_saturday_and_calendar_led_games_books_bingo_over_forty_pride_tradeoffs','source_urls',to_jsonb(array['https://www.danisqueerbar.com/','https://www.danisqueerbar.com/drag-brunch','https://www.reddit.com/r/boston/comments/1frgwv1/has_anyone_been_to_danis_queer_bar_yet/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','queer_women_lesbian_trans_nonbinary_near_all_lgbtq_peak_crowd_with_age_event_variation_and_ally_boundary','source_urls',to_jsonb(array['https://www.axios.com/local/boston/2024/09/12/danis-queer-bar-boston-opens','https://www.reddit.com/r/boston/comments/1frgwv1/has_anyone_been_to_danis_queer_bar_yet/','https://www.timeout.com/boston/bars/danis-queer-bar']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','casual_expressive_brunch_show_style_without_formal_code_plus_id_tipping_and_community_respect','source_urls',to_jsonb(array['https://www.opentable.com/r/danis-queer-bar-boston','https://www.danisqueerbar.com/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','warm_quick_tip_support_and_trans_guest_defence_praise_balanced_against_service_downstairs_wait_and_welcome_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/11141838/danis-queer-bar','https://www.reddit.com/r/boston/comments/1frgwv1/has_anyone_been_to_danis_queer_bar_yet/','https://www.opentable.com/r/danis-queer-bar-boston']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1940::bigint, jsonb_build_object(
      'queue_wait', 'No nightlife line: this is a 24-hour boutique-hotel desk with check-in from 4pm. Busy weekends can mean rooms are not ready early, so book ahead and store bags rather than hovering in the lobby. Read the final price carefully—the nightly amenity fee has surprised guests more often than reception has delayed them.',
      'best_nights', 'Use it as a playful South End base when you want Back Bay and downtown on foot but a quieter street at bedtime. Weekends add breakfast at the attached bar; the hotel lends bikes in season. It suits a city break more than a resort stay—small rooms and excellent beds reward travellers who spend the day outside.',
      'crowd_mix', 'Couples, solo travellers, business guests, pet owners and international visitors share a cheeky mainstream boutique hotel. The South End gives easy access to Boston’s queer history and nightlife, but the property is not a social LGBTQ+ hotel. Expect privacy and location, not an instant community room.',
      'dress_code', 'Anything travel-comfortable works. Robes, playful branding and compact rooms keep the mood relaxed; smart-casual is enough for the attached bar. There is no fashion door. Pack lightly because storage and bathrooms run smaller than a typical American hotel, and confirm what your room includes.',
      'staff_inclusivity', 'Verified guests score the staff highly and describe a warm, helpful welcome for couples and solo travellers. The strongest complaints concern room size and fee transparency, not identity-based treatment. Queer-specific testimony is thin, so call this friendly mainstream service—not a verified community programme.',
      'venue_classification', 'active_playful_south_end_boutique_hotel_with_small_well_designed_rooms_highly_praised_beds_cleanliness_location_and_staff_plus_material_nightly_amenity_fee_transparency_caution',
      'source_urls', to_jsonb(array['https://www.staypineapple.com/south-end-boston','https://www.staypineapple.com/south-end-boston/frequently-asked-questions','https://www.booking.com/reviews/us/hotel/staypineapple-south-end.html','https://www.tripadvisor.com/Hotel_Review-g60745-d89568-Reviews-Staypineapple_A_Delightful_Hotel_South_End_Boston-Boston_Massachusetts.html','https://www.hotels.com/ho111989/staypineapple-a-delightful-hotel-south-end-boston-united-states-of-america/','https://www.expedia.com/Boston-Hotels-Staypineapple.h4054.Hotel-Information']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','routine_four_pm_hotel_checkin_busy_weekend_room_timing_bag_storage_and_material_amenity_fee_disclosure','source_urls',to_jsonb(array['https://www.staypineapple.com/south-end-boston/frequently-asked-questions','https://www.expedia.com/Boston-Hotels-Staypineapple.h4054.Hotel-Information','https://www.booking.com/reviews/us/hotel/staypineapple-south-end.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','walkable_quiet_south_end_base_weekend_breakfast_seasonal_bikes_small_room_and_excellent_bed_tradeoff','source_urls',to_jsonb(array['https://www.staypineapple.com/south-end-boston','https://www.booking.com/reviews/us/hotel/staypineapple-south-end.html','https://www.hotels.com/ho111989/staypineapple-a-delightful-hotel-south-end-boston-united-states-of-america/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mainstream_couple_solo_business_pet_and_international_city_break_mix_in_queer_historic_area_without_social_lgbtq_programme','source_urls',to_jsonb(array['https://www.staypineapple.com/south-end-boston','https://www.booking.com/reviews/us/hotel/staypineapple-south-end.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','relaxed_boutique_hotel_and_attached_bar_clothing_with_compact_room_packing_context_and_no_door_selection','source_urls',to_jsonb(array['https://www.staypineapple.com/south-end-boston','https://www.tripadvisor.com/Hotel_Feature-g60745-d89568-zft1-Staypineapple_A_Delightful_Hotel_South_End_Boston.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','consistently_high_warm_helpful_service_scores_without_strong_queer_specific_testimony_and_with_fee_room_size_issues','source_urls',to_jsonb(array['https://www.booking.com/reviews/us/hotel/staypineapple-south-end.html','https://www.tripadvisor.com/Hotel_Review-g60745-d89568-Reviews-Staypineapple_A_Delightful_Hotel_South_End_Boston-Boston_Massachusetts.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (401::bigint, jsonb_build_object(
      'queue_wait', 'Most nights are easy walk-ins, and staff have fitted in last-minute karaoke guests. Ticketed cabaret, drag or private bookings need planning; recent complaints show upstairs plans can change. Sunday open mic is free and gentler. The current venue is at 10 Steine Street, not the address stored on this record.',
      'best_nights', 'Sunday’s free karaoke and open mic is the warmest join-in night. Choose a listed cabaret, drag or musical-theatre show for polished stage energy; Friday and Saturday build later around showtunes and singalongs. This is best for people who want to perform with the room, not disappear into anonymous club music.',
      'crowd_mix', 'Musical-theatre queers, drag fans, regulars, birthday groups and visitors who know every key change fill the room. The crowd is broadly LGBTQ+ with enthusiastic allies and skews social rather than cruisy. Hen groups appear, but the happiest nights are led by people there for the performers and songs.',
      'dress_code', 'No formal code: camp casual, theatre merch, sparkle, a character reference or ordinary jeans all land well. Dress for singing, standing and possibly taking the mic. The current listing says the venue is not wheelchair accessible, so contact the bar before relying on upstairs entertainment or a particular seating route.',
      'staff_inclusivity', 'Many guests praise funny, friendly hosts who rescue last-minute plans and turn karaoke into a shared queer night. Others report arrogant service or poor communication around private hire and cancelled upstairs access. The room can be wonderfully personal, but confirm important group arrangements in writing.',
      'venue_classification', 'active_brighton_gay_village_musical_theatre_cabaret_drag_and_karaoke_bar_at_current_10_steine_street_with_join_in_crowd_friendly_host_praise_and_booking_access_variation',
      'identity_note', 'Current 2026 sources place Bar Broadway at 10 Steine Street, Brighton BN2 1TE. The stored 16 Old Steine address is outdated and must be corrected before map directions are trusted.',
      'source_urls', to_jsonb(array['https://barbroadway.com/','https://brightonpubguide.co.uk/venue/bar-broadway/','https://wanderlog.com/place/details/4639796/bar-broadway','https://www.tripadvisor.co.uk/Attraction_Review-g186273-d23605336-Reviews-Bar_Broadway-Brighton_East_Sussex_England.html','https://restaurantguru.com/Bar-Broadway-Brighton','https://www.sluurpy.co.uk/brighton/restaurant/8506989/bar-broadway/reviews']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','mostly_walkin_last_minute_help_ticket_private_booking_risk_free_sunday_and_verified_current_address','source_urls',to_jsonb(array['https://brightonpubguide.co.uk/venue/bar-broadway/','https://www.sluurpy.co.uk/brighton/restaurant/8506989/bar-broadway/reviews','https://restaurantguru.com/Bar-Broadway-Brighton']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','free_sunday_open_mic_and_programme_led_cabaret_drag_musical_theatre_with_later_weekend_singalong','source_urls',to_jsonb(array['https://brightonpubguide.co.uk/venue/bar-broadway/','https://barbroadway.com/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','lgbtq_musical_theatre_drag_local_birthday_visitor_and_ally_social_mix_with_group_event_presence','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4639796/bar-broadway','https://www.tripadvisor.co.uk/Attraction_Review-g186273-d23605336-Reviews-Bar_Broadway-Brighton_East_Sussex_England.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_camp_theatre_sparkle_or_denim_without_formal_code_plus_reported_wheelchair_access_limit','source_urls',to_jsonb(array['https://restaurantguru.com/Bar-Broadway-Brighton','https://barbroadway.com/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_fun_last_minute_host_praise_balanced_against_arrogance_private_hire_and_upstairs_booking_communication_reports','source_urls',to_jsonb(array['https://wanderlog.com/place/details/4639796/bar-broadway','https://www.tripadvisor.co.uk/Attraction_Review-g186273-d23605336-Reviews-Bar_Broadway-Brighton_East_Sussex_England.html','https://restaurantguru.com/Bar-Broadway-Brighton']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (399::bigint, jsonb_build_object(
      'queue_wait', 'There is no gate or queue: this is public pebble beach. For the queer and clothing-optional stretch, walk about a mile east of the Palace Pier toward Black Rock; signs and pebble banks mark the official naturist zone. The stored Marine Parade address points to a building, not the beach, and must not drive navigation.',
      'best_nights', 'Sunny weekday mornings are calmest; warm weekend afternoons bring the broadest queer and naturist mix. Pride and heatwaves can swamp the central seafront, so continue east for room. Daylight is safer. After dark, the beach and nearby cruising paths require stronger personal-safety judgment.',
      'crowd_mix', 'Brighton residents, London day-trippers, swimmers, naturists and queer visitors mix along the coast. LGBTQ+ people informally gather toward the eastern Kemptown and naturist stretch, but it is open public space, not a gay-only beach. Summer tourism can outnumber locals and change the tone quickly.',
      'dress_code', 'Layers, sturdy beach shoes and wind protection beat glamour on these pebbles. Swimwear is normal on the wider beach; nudity is permitted only in the signed naturist section near Black Rock. Bring water and sun protection, respect photography consent, and never read naturism itself as sexual availability.',
      'staff_inclusivity', 'No venue staff manage this public space. Lifeguard and facility coverage is seasonal, while community accounts range from liberating queer visibility to staring, harassment and late-night safety concerns. Stay in populated daylight areas, watch drinks and belongings, and use emergency or council services when needed.',
      'venue_classification', 'public_brighton_pebble_seafront_with_informal_queer_eastern_gathering_and_official_black_rock_naturist_section_not_a_staffed_venue_with_material_navigation_privacy_and_night_safety_cautions',
      'record_status', 'location_correction_required_stored_address_is_not_the_beach_route_to_official_black_rock_naturist_section_before_publication',
      'identity_note', 'This record should route to Brighton Naturist Beach, officially Cliff Bathing Beach, at Black Rock, Madeira Drive, Brighton BN2 1FG. Stored 11-12 Marine Parade is a building address and is incorrect.',
      'source_urls', to_jsonb(array['https://www.visitbrighton.com/things-to-do/brighton-naturist-beach-p628201/overview-t9474','https://www.brighton-hove.gov.uk/our-plans-black-rock','https://www.gayout.com/europe/united-kingdom/brighton/beaches/gay-beach-brighton','https://www.travelgay.com/editorial/gay-cruising-in-brighton','https://discoverbrighton.org/avoiding-the-crowds-during-pride/','https://www.reddit.com/r/brighton/comments/1l8nwt6/bit_nervous_about_traveling_to_brighton_alone_do/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','ungated_public_beach_one_mile_east_signed_naturist_zone_and_stored_building_address_error','source_urls',to_jsonb(array['https://www.visitbrighton.com/things-to-do/brighton-naturist-beach-p628201/overview-t9474','https://www.brighton-hove.gov.uk/our-plans-black-rock']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','calm_weekday_morning_warm_weekend_afternoon_pride_heatwave_crowding_and_daylight_over_night_safety','source_urls',to_jsonb(array['https://discoverbrighton.org/avoiding-the-crowds-during-pride/','https://www.reddit.com/r/brighton/comments/1l8nwt6/bit_nervous_about_traveling_to_brighton_alone_do/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_daytripper_swimmer_naturist_queer_and_large_summer_tourist_mix_with_informal_eastern_lgbtq_congregation','source_urls',to_jsonb(array['https://www.gayout.com/europe/united-kingdom/brighton/beaches/gay-beach-brighton','https://www.visitbrighton.com/things-to-do/brighton-naturist-beach-p628201/overview-t9474']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','pebble_footwear_layers_swimwear_and_signed_naturist_nudity_with_sun_water_photo_consent_guidance','source_urls',to_jsonb(array['https://www.visitbrighton.com/things-to-do/brighton-naturist-beach-p628201/overview-t9474','https://www.gayout.com/europe/united-kingdom/brighton/beaches/gay-beach-brighton']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_venue_staff_seasonal_public_services_and_mixed_liberation_staring_harassment_night_safety_accounts','source_urls',to_jsonb(array['https://www.gayout.com/europe/united-kingdom/brighton/beaches/gay-beach-brighton','https://www.reddit.com/r/brighton/comments/1l8nwt6/bit_nervous_about_traveling_to_brighton_alone_do/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (396::bigint, jsonb_build_object(
      'queue_wait', 'Reception is usually quick, with no famous street line. The uninterrupted Friday-to-Sunday opening can create busy pockets, but Friday late afternoon has also been almost empty. Buy the right day or weekend pass, keep the ticket for re-entry and use the discreet rear door if privacy matters.',
      'best_nights', 'A weekday afternoon suits a first visit and a proper tour; weekend evenings offer more bodies and longer hours. Friday can start slowly, while the round-the-clock weekend lets the mood build on its own clock. Check event listings rather than assuming youth or crowd size—the mix changes sharply by hour.',
      'crowd_mix', 'This is a men’s sauna with locals, South Coast regulars, weekend visitors and a wide age range. Quiet periods can lean older; busier nights bring a broader mix. Some guests come to cruise, others use the steam, jacuzzi, sauna, cinema and café. No body type or age guarantees attention, and none is owed.',
      'dress_code', 'Towel inside; valid ID and sensible shoes for the walk to the current Grand Parade address. Free condoms and lube are advertised. The sauna frames body language as part of consent, but a clear no always overrides signals. Store valuables, follow wet-area rules and ask for a tour if the multi-level layout is new.',
      'staff_inclusivity', 'Recent visitors describe staff as friendly, explanatory and quick to put nervous first-timers at ease, with improving cleanliness. A few mention blunt security, weak showers or removed equipment. The stated no-attitude welcome is credible, but judge the actual room and leave if boundaries slip.',
      'venue_classification', 'active_mens_gay_sauna_at_current_grand_parade_site_with_steam_jacuzzi_sauna_cinema_cafe_weekend_continuous_opening_cross_age_mix_consent_resources_and_mixed_facility_reports',
      'identity_note', 'The official current address is 75/76 Grand Parade, Brighton BN2 9JA, with an optional rear entrance on Grand Parade Mews. The stored 13 St James’s Street address is obsolete.',
      'source_urls', to_jsonb(array['https://www.thebrightonsauna.com/','https://www.thebrightonsauna.com/prices-times/','https://wanderlog.com/place/details/8308493/the-brighton-sauna','https://brighton.cylex-uk.co.uk/company/the-brighton-sauna-19985379.html','https://queerhub.co.uk/listing/the-brighton-sauna-the-south-easts-premier-destination/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','generally_quick_reception_variable_weekend_pockets_pass_reentry_discreet_door_and_current_address','source_urls',to_jsonb(array['https://www.thebrightonsauna.com/prices-times/','https://www.thebrightonsauna.com/','https://wanderlog.com/place/details/8308493/the-brighton-sauna']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','weekday_first_visit_weekend_extended_build_quiet_friday_afternoon_and_hour_specific_mix','source_urls',to_jsonb(array['https://www.thebrightonsauna.com/prices-times/','https://wanderlog.com/place/details/8308493/the-brighton-sauna']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','men_only_local_south_coast_weekend_visitor_cross_age_and_quiet_period_older_mix_with_cruise_and_facility_users','source_urls',to_jsonb(array['https://www.thebrightonsauna.com/','https://wanderlog.com/place/details/8308493/the-brighton-sauna']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','towel_id_safe_footwear_free_condom_lube_clear_consent_storage_and_first_time_tour_context','source_urls',to_jsonb(array['https://www.thebrightonsauna.com/','https://www.thebrightonsauna.com/prices-times/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_explanatory_first_timer_and_cleanliness_praise_balanced_against_security_shower_and_removed_equipment_reports','source_urls',to_jsonb(array['https://wanderlog.com/place/details/8308493/the-brighton-sauna','https://queerhub.co.uk/listing/the-brighton-sauna-the-south-easts-premier-destination/','https://brighton.cylex-uk.co.uk/company/the-brighton-sauna-19985379.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (394::bigint, jsonb_build_object(
      'queue_wait', 'Daytime and early evening are normally easy, with strong marks for short waits. Drag, bottomless brunch, Eurovision and late weekend sessions deserve a booking; the big room can still become loud and dense. The current entrance is 8 Marine Parade, so the stored St James’s Street address needs correction.',
      'best_nights', 'Late afternoon gives the softest version: drinks, food, cards and chat in a spacious queer pub. Book a drag show, cabaret, quiz or bottomless brunch for hosted energy, then choose Saturday for DJs and dancing. This place changes gear across the day, making timing more useful than a single “best” night.',
      'crowd_mix', 'Brighton LGBTQ+ locals, visiting queer groups, drag audiences, brunch parties, dogs and allies all pass through. Early hours feel intergenerational and pub-like; event nights skew louder and more celebratory. It is a visible community hub, though large group occasions can briefly make the room feel less locally rooted.',
      'dress_code', 'Pub casual by day, sparkle and going-out looks for drag or DJs. No selective fashion door is reported, and guests describe feeling safe as visibly LGBTQIA+. Bring ear protection if sound sensitivity matters—multiple reviews found special-event volume overwhelming—and confirm access needs when reserving.',
      'staff_inclusivity', 'Guests praise professional, welcoming teams, attentive brunch service and careful handling of allergies. One cabaret was criticised for jokes targeting lesbians, and food or volume can miss. The overall welcome is strong, but queer safety also means performers and management taking audience feedback seriously.',
      'venue_classification', 'active_large_kemptown_gay_pub_at_current_marine_parade_site_with_food_terrace_drag_cabaret_quiz_brunch_djs_intergenerational_day_mix_and_event_sound_content_variation',
      'identity_note', 'Current official and review evidence places Charles Street Tap at 8 Marine Parade, Brighton BN2 1TA. The stored 126-127 St James’s Street address is outdated.',
      'source_urls', to_jsonb(array['https://www.charlesstreettap.co.uk/','https://www.thefork.co.uk/restaurant/charles-street-tap-r816378/reviews','https://wanderlog.com/place/details/1327214/charles-street-tap','https://www.tripadvisor.co.uk/Restaurant_Review-g186273-d3330463-Reviews-Charles_Street_Tap-Brighton_East_Sussex_England.html','https://www.travelgay.com/venue/charles-street-bar-and-club','https://restaurantguru.com/Charles-Street-Tap-Brighton']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','easy_day_early_entry_high_wait_score_event_booking_loud_peak_and_verified_current_address','source_urls',to_jsonb(array['https://www.thefork.co.uk/restaurant/charles-street-tap-r816378/reviews','https://wanderlog.com/place/details/1327214/charles-street-tap','https://www.charlesstreettap.co.uk/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','relaxed_late_afternoon_programme_led_drag_cabaret_quiz_brunch_and_saturday_dj_variation','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1327214/charles-street-tap','https://www.tripadvisor.co.uk/Restaurant_Review-g186273-d3330463-Reviews-Charles_Street_Tap-Brighton_East_Sussex_England.html','https://www.travelgay.com/venue/charles-street-bar-and-club']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','local_lgbtq_visitor_drag_brunch_dog_ally_intergenerational_day_and_louder_group_event_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/1327214/charles-street-tap','https://www.tripadvisor.co.uk/Restaurant_Review-g186273-d3330463-Reviews-Charles_Street_Tap-Brighton_East_Sussex_England.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','pub_casual_day_expressive_event_style_no_selection_visible_lgbtq_safety_and_sound_sensitivity_caution','source_urls',to_jsonb(array['https://www.thefork.co.uk/restaurant/charles-street-tap-r816378/reviews','https://www.tripadvisor.co.uk/Restaurant_Review-g186273-d3330463-Reviews-Charles_Street_Tap-Brighton_East_Sussex_England.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','professional_welcoming_attentive_allergy_care_praise_balanced_against_lesbian_targeted_cabaret_food_and_volume_criticism','source_urls',to_jsonb(array['https://www.thefork.co.uk/restaurant/charles-street-tap-r816378/reviews','https://wanderlog.com/place/details/1327214/charles-street-tap','https://www.tripadvisor.co.uk/Restaurant_Review-g186273-d3330463-Reviews-Charles_Street_Tap-Brighton_East_Sussex_England.html']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (402::bigint, jsonb_build_object(
      'queue_wait', 'There is no separate “Club Revenge Basement” entrance or venue. This row duplicates the multi-floor Revenge nightclub stored as place 393, whose real address is 32-34 Old Steine. Advance tickets can skip the real club’s queue. The Marine Parade address on this duplicate belongs to another business.',
      'best_nights', 'No independent programme exists for this record. Alternative Monday, student Thursday and major Friday-Saturday nights belong to canonical Revenge place 393, along with its performances and rooftop. Merge this row rather than inventing a second basement calendar that would mislead guests and split community signals.',
      'crowd_mix', 'There is no second crowd here. The one Revenge club serves a predominantly LGBTQ+ mix across its floors, with strong lesbian and wider community safety reports. Those guests belong to place 393. Keeping this row visible would falsely double one venue and attach queer club traffic to the wrong address.',
      'dress_code', 'The real club has no general dress code, but rejects loose beach footwear; fancy dress and groups over eight need approval. That guidance belongs to canonical place 393. This duplicate has no separate door policy and should be hidden instead of offering instructions for a venue that does not exist.',
      'staff_inclusivity', 'No separate staff team operates this record. The friendly bar, security and cloakroom reports—as well as accessibility and safe-space policies—belong to the real Revenge at place 393. Merge any ratings there, suppress this page and correct the address before users are sent toward an unrelated venue.',
      'venue_classification', 'duplicate_database_component_of_active_multifloor_lgbtq_nightclub_revenge_place_393_with_no_independent_entrance_programme_crowd_dress_policy_staff_or_marine_parade_identity',
      'record_status', 'duplicate_merge_required_hide_from_search_maps_sitemap_city_counts_and_recommendations_canonical_place_id_393',
      'identity_note', 'Duplicate of Revenge Club place ID 393 at 32-34 Old Steine, Brighton BN1 1EL. Stored 19-23 Marine Parade is not Revenge and overlaps the separate Patterns venue area.',
      'canonical_place_id', 393,
      'source_urls', to_jsonb(array['https://revenge.co.uk/','https://revenge.co.uk/revenge/','https://revenge.co.uk/faqs/','https://www.brightonfringe.org/venues/club-revenge/','https://www.tripadvisor.co.uk/Attraction_Review-g186273-d547478-Reviews-Revenge-Brighton_East_Sussex_England.html','https://patternsbrighton.com/contact-us/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','confirmed_no_separate_basement_venue_same_multifloor_revenge_canonical_393_real_old_steine_address_and_advance_queue_skip','source_urls',to_jsonb(array['https://revenge.co.uk/revenge/','https://revenge.co.uk/faqs/','https://www.brightonfringe.org/venues/club-revenge/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','no_independent_programme_all_real_weekday_weekend_performance_and_rooftop_activity_owned_by_canonical_393','source_urls',to_jsonb(array['https://revenge.co.uk/','https://revenge.co.uk/revenge/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','no_second_crowd_and_all_lgbtq_lesbian_wider_community_guest_evidence_owned_by_canonical_393','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Attraction_Review-g186273-d547478-Reviews-Revenge-Brighton_East_Sussex_England.html','https://revenge.co.uk/revenge/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_independent_door_policy_with_real_no_general_code_beach_footwear_fancy_dress_and_large_group_rules_owned_by_393','source_urls',to_jsonb(array['https://revenge.co.uk/faqs/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_independent_team_with_service_security_cloakroom_accessibility_safe_space_and_rating_evidence_to_merge_to_393','source_urls',to_jsonb(array['https://www.tripadvisor.co.uk/Attraction_Review-g186273-d547478-Reviews-Revenge-Brighton_East_Sussex_England.html','https://revenge.co.uk/revenge/']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (400::bigint, jsonb_build_object(
      'queue_wait', 'Kemptown is a neighbourhood, not a bar with a door. Walk straight in via St James’s Street, the seafront or the surrounding lanes; queues belong to individual venues and become exceptional around Pride. This record shares a venue address by mistake and must not appear as another nightlife choice.',
      'best_nights', 'Start in daylight for coffee, vintage shops, bookshops and the seafront, then let St James’s Street carry you into dinner and queer bars. Friday and Saturday are liveliest; weekdays show more of the resident village. Pride brings scale and road changes, but ordinary weekends better reveal the neighbourhood.',
      'crowd_mix', 'LGBTQ+ residents give the area its long-standing identity, joined by independent traders, dog walkers, students, couples, nightlife visitors and summer tourists. St James’s Street is the visible queer spine, but Kemptown stretches much farther east. Pride can flip the local-to-visitor balance in a single afternoon.',
      'dress_code', 'There is no district dress code. Daywear, beach layers, vintage finds, nightlife looks and visible trans or gender-nonconforming style belong on these streets. Pebbles, hills and long walks reward practical shoes. Each club can set its own door rules, so neighbourhood openness does not guarantee entry everywhere.',
      'staff_inclusivity', 'No single team runs Kemptown. Many independent businesses actively serve LGBTQ+ locals, while community accounts also mention noise, antisocial behaviour and occasional hate incidents around busy streets. Choose places with clear policies, support queer-run shops, and use normal city awareness late at night.',
      'venue_classification', 'non_venue_brighton_neighbourhood_and_lgbtq_quarter_centring_st_jamess_street_with_resident_community_independent_daylife_seafront_nightlife_and_pride_visitors',
      'record_status', 'non_venue_area_move_to_neighbourhood_or_city_guide_hide_from_venue_search_maps_counts_and_venue_intelligence_scoring',
      'identity_note', 'Kemptown is a broad Brighton neighbourhood and LGBTQ+ quarter, not a bar at 126-127 St James’s Street. Preserve it as guide geography, not as a place competing with real venues.',
      'source_urls', to_jsonb(array['https://www.visitbrighton.com/itineraries/kemptown','https://www.visitbrighton.com/food-and-drink/areas-to-explore/kemptown','https://www.visitbrighton.com/plan-your-visit/about-the-area/lgbtqia','https://www.visitbrighton.com/plan-your-visit/about-the-area','https://www.reddit.com/r/brighton/comments/1s3plh4/living_in_kemptown/','https://www.reddit.com/r/brighton/comments/1t5opic/recommendations_for_a_visiting_queer_couple/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','confirmed_neighbourhood_without_entrance_individual_venue_and_pride_queues_plus_false_shared_address','source_urls',to_jsonb(array['https://www.visitbrighton.com/itineraries/kemptown','https://www.visitbrighton.com/food-and-drink/areas-to-explore/kemptown']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','daytime_independents_seafront_to_st_jamess_evening_weekend_liveliness_weekday_locality_and_pride_scale_tradeoff','source_urls',to_jsonb(array['https://www.visitbrighton.com/itineraries/kemptown','https://www.visitbrighton.com/food-and-drink/areas-to-explore/kemptown']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','lgbtq_resident_trader_dog_walker_student_couple_nightlife_and_summer_pride_visitor_neighbourhood_mix','source_urls',to_jsonb(array['https://www.visitbrighton.com/plan-your-visit/about-the-area/lgbtqia','https://www.reddit.com/r/brighton/comments/1s3plh4/living_in_kemptown/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_area_code_with_day_beach_vintage_nightlife_and_gender_expression_mix_plus_venue_specific_rules','source_urls',to_jsonb(array['https://www.visitbrighton.com/food-and-drink/areas-to-explore/kemptown','https://www.visitbrighton.com/plan-your-visit/about-the-area/lgbtqia']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_single_team_with_many_lgbtq_serving_independents_balanced_against_noise_antisocial_and_occasional_hate_context','source_urls',to_jsonb(array['https://www.reddit.com/r/brighton/comments/1s3plh4/living_in_kemptown/','https://www.visitbrighton.com/plan-your-visit/about-the-area/lgbtqia']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

update public.places
set seo_indexable = false,
    seo_quality_status = 'rejected'
where id in (402,400);

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1939,1940,401,399,396,394,402,400)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
  if exists (select 1 from public.places where id in (402,400) and coalesce(seo_indexable,true)) then
    raise exception 'Duplicate and non-venue records must be non-indexable';
  end if;
end $$;

commit;
