-- Queer Atlas venue intelligence: global review-led editorial pass, batch 63.
-- Eight Copenhagen and Crete records checked against current official pages, local guides, listings and review consensus on 2026-08-07.
-- Source names remain in evidence metadata, never in reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1980::bigint, jsonb_build_object(
      'queue_wait', 'Hotel check-in is usually smooth, but the indoor Junglefish pool is the pressure point: loungers and photogenic edges can fill on busy afternoons. Reserve rooftop dining and treatments ahead, and ask when children or outside pass-holders may share the pool.',
      'best_nights', 'A pool session before dinner and a rooftop drink make the strongest in-house evening. Friday and Saturday feel more celebratory; a weekday is calmer around the atrium. The hotel is an atmospheric base, not queer nightlife, with the Latin Quarter and city bars a walk away.',
      'crowd_mix', 'Design-minded couples, friends, families and international city-break guests dominate, with a polished social-media-aware mood around the pool. LGBTQ+ guests join a mainstream luxury crowd rather than a house queer scene. The 87-suite scale keeps it intimate but not secluded.',
      'dress_code', 'Relaxed boutique-hotel style fits: swimwear and a robe by the pool, covered casual clothes through shared areas, and smart resort wear upstairs. No formal door code is reported. Bring a light layer for the roof and shoes that handle the short walk into central Copenhagen.',
      'staff_inclusivity', 'Recent guests repeatedly praise warm, polite and helpful service, alongside strong cleanliness and atmosphere scores. No property-specific LGBTQ+ programme was verified, so inclusion is best described as professional mainstream hospitality. Confirm bedding and pool access in writing.',
      'venue_classification', 'active_mainstream_upper_upscale_87_suite_copenhagen_design_hotel_with_junglefish_indoor_pool_rooftop_restaurant_spa_and_sustainability_led_brand_couple_friend_family_city_break_mix_and_strong_service_consensus',
      'identity_note', 'Manon Les Suites is a mainstream design hotel, not an LGBTQ+-specific property. Its queer-travel value is central access and broadly praised hospitality, not dedicated programming or a community-only pool.',
      'source_urls', to_jsonb(array['https://guldsmedenhotels.com/manon-les-suites/','https://www.tripadvisor.com/Hotel_Review-g189541-d12392057-Reviews-Manon_Les_Suites_Guldsmeden_Hotels-Copenhagen_Zealand.html','https://www.expedia.ca/Copenhagen-Hotels-Manon-LES-Suites-Guldsmeden.h1413976.Hotel-Information','https://www.cntraveler.com/hotels/copenhagen/manon-les-suites']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','smooth_hotel_arrival_with_busy_afternoon_pool_lounger_and_rooftop_dining_capacity_pressure','source_urls',to_jsonb(array['https://guldsmedenhotels.com/manon-les-suites/','https://www.tripadvisor.com/Hotel_Review-g189541-d12392057-Reviews-Manon_Les_Suites_Guldsmeden_Hotels-Copenhagen_Zealand.html','https://www.cntraveler.com/hotels/copenhagen/manon-les-suites']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','pool_rooftop_evening_weekend_celebration_and_calmer_weekday_hotel_atmosphere','source_urls',to_jsonb(array['https://guldsmedenhotels.com/manon-les-suites/','https://www.tripadvisor.com/Hotel_Feature-g189541-d12392057-zft11257-Manon_Les_Suites_Guldsmeden_Hotels.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','design_minded_couple_friend_family_and_international_city_break_mainstream_guest_mix','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g189541-d12392057-Reviews-Manon_Les_Suites_Guldsmeden_Hotels-Copenhagen_Zealand.html','https://www.cntraveler.com/hotels/copenhagen/manon-les-suites']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','relaxed_boutique_pool_coverup_smart_rooftop_and_weather_walking_practicality_without_formal_code','source_urls',to_jsonb(array['https://guldsmedenhotels.com/manon-les-suites/','https://www.cntraveler.com/hotels/copenhagen/manon-les-suites']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_warm_polite_helpful_mainstream_service_consensus_without_verified_property_specific_lgbtq_programme','source_urls',to_jsonb(array['https://www.tripadvisor.com/Hotel_Review-g189541-d12392057-Reviews-Manon_Les_Suites_Guldsmeden_Hotels-Copenhagen_Zealand.html','https://www.expedia.ca/Copenhagen-Hotels-Manon-LES-Suites-Guldsmeden.h1413976.Hotel-Information']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (234::bigint, jsonb_build_object(
      'queue_wait', 'Afternoons and early evenings are easy; the compact two-level room can feel packed on Friday and Saturday after 22:00 even without a formal club queue. There is no dance floor, and indoor smoking is permitted. Arrive early for conversation, a seat and clearer air.',
      'best_nights', 'Friday and Saturday run latest and deliver the fullest bar atmosphere, while Sunday has a loyal regular rhythm. Go around 20:00 for talk and a neighbourhood-pub feel; later hours become louder and more spontaneous. Special games or Pride dates should be checked live.',
      'crowd_mix', 'Gay men and long-time Copenhagen regulars remain central, with LGBTQ+ visitors, friends, women and allies across a broad age range. It is more local bar than tourist club. Some guests value that easy intergenerational mix; others find the tiny room less community-focused when crowded.',
      'dress_code', 'Everyday bar clothes, denim, trainers and a brighter weekend look all fit. No formal code is published. The practical choice is removable layers because the rooms are small and smoking is allowed; keep outerwear simple and do not expect nightclub changing or cloakroom infrastructure.',
      'staff_inclusivity', 'The bar explicitly presents itself as an LGBT+ safe space, and recent guests often praise friendly, conversational staff. A smaller set reports poor handling, exclusion or discriminatory treatment, so the consensus is positive but not uniform. Raise concerns promptly with the duty lead.',
      'venue_classification', 'active_long_running_two_level_copenhagen_neighbourhood_gay_bar_and_lgbt_safe_space_with_daily_afternoon_to_late_opening_no_dance_floor_indoor_smoking_broad_age_local_core_and_mixed_but_mainly_positive_service_consensus',
      'identity_note', 'Masken remains an active gay bar at Studiestræde 33. It is a compact, conversation-led neighbourhood venue rather than a nightclub, and its permitted indoor smoking materially shapes the experience.',
      'source_urls', to_jsonb(array['https://maskenbar.dk/about/','https://www.visitdenmark.com/denmark/plan-your-trip/masken-bar-gdk655853','https://www.top-rated.online/cities/Copenhagen/place/p/1711543/Masken%2BBar','https://www.gayout.com/europe/denmark/copenhagen/bars/masken-bar-cafe-copenhagen','https://restaurantguru.com/Masken-Bar-Copenhagen']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','easy_early_arrival_compact_weekend_capacity_no_dance_floor_and_indoor_smoking','source_urls',to_jsonb(array['https://maskenbar.dk/about/','https://www.visitdenmark.com/denmark/plan-your-trip/masken-bar-gdk655853','https://www.gayout.com/europe/denmark/copenhagen/bars/masken-bar-cafe-copenhagen']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_late_peak_sunday_regular_pattern_and_early_conversation_window','source_urls',to_jsonb(array['https://maskenbar.dk/about/','https://restaurantguru.com/Masken-Bar-Copenhagen']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_male_regular_lgbtq_visitor_friend_woman_ally_and_broad_age_local_bar_mix','source_urls',to_jsonb(array['https://www.visitdenmark.com/denmark/plan-your-trip/masken-bar-gdk655853','https://www.top-rated.online/cities/Copenhagen/place/p/1711543/Masken%2BBar']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_formal_code_with_everyday_barwear_and_small_smoking_room_layering_practicality','source_urls',to_jsonb(array['https://maskenbar.dk/about/','https://www.visitdenmark.com/denmark/plan-your-trip/masken-bar-gdk655853']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','explicit_lgbt_safe_space_and_frequent_friendly_staff_praise_balanced_by_exclusion_discrimination_and_incident_complaints','source_urls',to_jsonb(array['https://maskenbar.dk/about/','https://www.top-rated.online/cities/Copenhagen/place/p/1711543/Masken%2BBar','https://dk.trustpilot.com/review/www.maskenbar.dk']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (224::bigint, jsonb_build_object(
      'queue_wait', 'The Axeltorv basement is spacious, but Friday and Saturday arrivals after midnight can meet a proper club door. Entry experiences are mixed, so carry photo ID, arrive together and stay calm if refused. Earlier opening is easier; current listings disagree on which weekdays operate.',
      'best_nights', 'Friday and Saturday offer the biggest pop floor and a run to 07:00; Wednesday, Thursday or Sunday can be looser when scheduled. Eurovision, Pride and themed offers add energy. Check the current calendar first, because older sources still describe daily opening that is no longer consistent.',
      'crowd_mix', 'A broad queer party crowd fills the dance floor: gay men remain visible, alongside lesbians, trans and non-binary guests, drag fans, friends and pop-loving allies. It skews younger and more international than the old bars, though locals still anchor the late-night rhythm.',
      'dress_code', 'All attires are advertised as welcome, from trainers and tees to sequins, wigs and sheer party looks. Prioritise danceable shoes and a layer for the trip home. Freedom of expression is part of the proposition, but photo ID and respectful conduct matter more than fashion at the door.',
      'staff_inclusivity', 'The published safe-space policy rejects racism, sexism, homophobia, transphobia, violence and consent breaches. Many listings describe multilingual staff, while reviews include serious allegations of racist or arbitrary door treatment. The stated standard is strong; lived consensus is uneven.',
      'venue_classification', 'active_large_central_copenhagen_lgbtq_pop_nightclub_in_axeltorv_basement_with_large_dance_floor_lounges_late_weekend_hours_diverse_queer_and_ally_crowd_expressive_dress_safe_space_policy_and_materially_mixed_door_consensus',
      'identity_note', 'Never Mind is active at Axeltorv 3, not its former Studiestræde address. It is a late-night LGBTQ+ pop club with a published safe-space policy; current operating nights should be checked live.',
      'source_urls', to_jsonb(array['https://www.visitcopenhagen.com/copenhagen/planning/never-mind-night-club-gdk558203','https://www.travelgay.com/venue/never-mind','https://whereis.gay/never-mind','https://www.reddit.com/r/copenhagen/comments/1fxane2','https://www.reddit.com/r/copenhagen/comments/1ntoqnm']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','spacious_club_with_late_weekend_door_pressure_mixed_entry_experiences_and_weekday_schedule_variation','source_urls',to_jsonb(array['https://www.visitcopenhagen.com/copenhagen/planning/never-mind-night-club-gdk558203','https://www.travelgay.com/venue/never-mind','https://www.reddit.com/r/copenhagen/comments/1fxane2']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_pop_peak_to_0700_with_variable_midweek_sunday_and_theme_programming','source_urls',to_jsonb(array['https://www.visitcopenhagen.com/copenhagen/planning/never-mind-night-club-gdk558203','https://www.travelgay.com/venue/never-mind']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','young_international_gay_lesbian_trans_nonbinary_drag_friend_and_pop_ally_mix','source_urls',to_jsonb(array['https://www.visitcopenhagen.com/copenhagen/planning/never-mind-night-club-gdk558203','https://www.reddit.com/r/copenhagen/comments/1ntoqnm']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','all_attires_expressive_partywear_and_dance_practicality_with_id_and_conduct_priority','source_urls',to_jsonb(array['https://www.visitcopenhagen.com/copenhagen/planning/never-mind-night-club-gdk558203','https://www.travelgay.com/venue/never-mind']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_published_anti_discrimination_consent_policy_and_multilingual_staff_claim_balanced_by_serious_door_discrimination_reports','source_urls',to_jsonb(array['https://www.visitcopenhagen.com/copenhagen/planning/never-mind-night-club-gdk558203','https://www.travelgay.com/venue/never-mind']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (233::bigint, jsonb_build_object(
      'queue_wait', 'Daytime coffee and early drinks are easy; sunny terrace seats on Rainbow Square disappear first, and the bar can become shoulder-to-shoulder on Friday, Saturday and Pride dates. Go early if sitting matters. Table service can slow at peak, so make polite eye contact at the bar.',
      'best_nights', 'A bright afternoon turning into early evening is Oscar at its best, especially when the terrace is open. Friday and Saturday are liveliest, while weekdays suit food and conversation. This is a social café-bar, not a late dance club; pair it with a later venue if you want a full night.',
      'crowd_mix', 'Gay men and LGBTQ+ locals remain the heart, joined by queer visitors, friends and allies across ages. The terrace attracts a noticeably broader city-centre mix. It is accessible to tourists without losing its community role, though peak seating can leave regulars competing with large groups.',
      'dress_code', 'Copenhagen casual works from lunch through drinks: denim, knitwear, trainers or a sharper evening layer. There is no reported fashion gate. Dress for the terrace weather and for sitting close to other guests; Pride brings colour, but neither glamour nor formalwear is required.',
      'staff_inclusivity', 'The venue explicitly welcomes the LGBTQI+ community and allies, and many recent guests describe an unusually warm manager, sociable patrons and attentive staff. Other recent reviews report being ignored or treated coldly. Expect an affirming setting, with service consistency less certain at busy moments.',
      'venue_classification', 'active_central_copenhagen_lgbtqi_cafe_bar_and_casual_restaurant_on_rainbow_square_with_prominent_summer_terrace_day_to_evening_service_gay_community_core_broad_ally_visitor_mix_and_mixed_recent_service_consensus',
      'identity_note', 'Oscar Bar & Café is an active LGBTQI+ café-bar and restaurant on Regnbuepladsen. Its signature is daytime-to-evening terrace sociability, not a dedicated dance-club programme.',
      'source_urls', to_jsonb(array['https://www.oscarbarcafe.dk/','https://www.tripadvisor.com/Restaurant_Review-g189541-d3372583-Reviews-Oscar_Bar_Cafe-Copenhagen_Zealand.html','https://dk.trustpilot.com/review/oscarbarcafe.dk','https://copenhagen.gaycities.com/bars/1970-oscar-bar-caf%C3%A9','https://www.gayplaces.co/city/copenhagen/bar/oscar-bar-cafe']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','easy_daytime_entry_with_sunny_terrace_weekend_pride_capacity_and_peak_service_delay','source_urls',to_jsonb(array['https://www.oscarbarcafe.dk/','https://www.tripadvisor.com/Restaurant_Review-g189541-d3372583-Reviews-Oscar_Bar_Cafe-Copenhagen_Zealand.html','https://www.gayplaces.co/city/copenhagen/bar/oscar-bar-cafe']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','terrace_afternoon_early_evening_signature_with_friday_saturday_peak_and_weekday_conversation','source_urls',to_jsonb(array['https://www.oscarbarcafe.dk/','https://www.gayplaces.co/city/copenhagen/bar/oscar-bar-cafe']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_lgbtq_local_queer_visitor_friend_ally_and_broad_terrace_city_mix','source_urls',to_jsonb(array['https://dk.trustpilot.com/review/oscarbarcafe.dk','https://www.tripadvisor.com/Restaurant_Review-g189541-d3372583-Reviews-Oscar_Bar_Cafe-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_copenhagen_day_to_evening_style_with_terrace_weather_practicality_and_no_verified_gate','source_urls',to_jsonb(array['https://www.oscarbarcafe.dk/','https://copenhagen.gaycities.com/bars/1970-oscar-bar-caf%C3%A9']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','explicit_lgbtqi_ally_welcome_and_frequent_warm_service_praise_balanced_by_recent_ignored_or_cold_service_reports','source_urls',to_jsonb(array['https://www.tripadvisor.com/Restaurant_Review-g189541-d3372583-Reviews-Oscar_Bar_Cafe-Copenhagen_Zealand.html','https://dk.trustpilot.com/review/oscarbarcafe.dk']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1982::bigint, jsonb_build_object(
      'queue_wait', 'Self-service kiosks help at arrival, but a 390-room hotel can bunch at afternoon check-in, breakfast and the rooftop pool. Pool capacity is the recurring pinch point when occupancy is high. Confirm access rules, then choose an off-peak swim rather than assuming a lounger.',
      'best_nights', 'The heated rooftop pool and sauna are memorable in clear weather, then the station-side location makes the rest of Copenhagen easy. Weekends make the courtyard and bars feel celebratory; weekdays are calmer and more businesslike. The hotel itself is not queer nightlife.',
      'crowd_mix', 'International couples, design travellers, families, conference guests and Danish staycationers share a large mainstream luxury hotel. LGBTQ+ couples are part of that broad flow, not a distinct house crowd. The former post-office setting attracts architecture-focused visitors as much as social ones.',
      'dress_code', 'Modern city-hotel casual suits the lobby and courtyard; use swimwear and a robe only in the pool zone, then smart casual for dinner or drinks. No formal fashion barrier is reported. Pack a layer for the rooftop and comfortable shoes for Tivoli, the station and central streets.',
      'staff_inclusivity', 'Large-sample reviews strongly praise friendly staff, cleanliness, comfort and location. A minority describe uneven check-in guidance or service below five-star expectations. No property-specific LGBTQ+ training evidence surfaced, so the defensible promise is professional mainstream welcome.',
      'venue_classification', 'active_large_mainstream_five_star_copenhagen_design_hotel_in_restored_central_post_office_with_390_rooms_courtyard_dining_heated_rooftop_pool_sauna_and_broad_international_leisure_business_family_mix',
      'identity_note', 'Villa Copenhagen is a mainstream five-star design hotel, not an LGBTQ+-specific property. Its relevance is central transport access and strong general hospitality, with pool crowding the most consistent practical caveat.',
      'source_urls', to_jsonb(array['https://villacopenhagen.com/','https://villacopenhagen.com/wp-content/uploads/2024/08/Official-Press-kit-Villa_-Copenhagen.pdf','https://www.booking.com/hotel/dk/villa-copenhagen-kobenhavn.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d17626250-Reviews-Villa_Copenhagen-Copenhagen_Zealand.html','https://www.hotels.com/ho1169166720/villa-copenhagen-copenhagen-denmark/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','kiosk_supported_arrival_with_large_hotel_checkin_breakfast_and_high_occupancy_rooftop_pool_pressure','source_urls',to_jsonb(array['https://www.booking.com/hotel/dk/villa-copenhagen-kobenhavn.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d17626250-Reviews-Villa_Copenhagen-Copenhagen_Zealand.html','https://www.hotels.com/ho1169166720/villa-copenhagen-copenhagen-denmark/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','clear_rooftop_pool_sauna_evening_weekend_courtyard_energy_and_quieter_weekday_variation','source_urls',to_jsonb(array['https://villacopenhagen.com/','https://www.booking.com/hotel/dk/villa-copenhagen-kobenhavn.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','international_couple_design_family_conference_and_danish_staycation_mainstream_mix','source_urls',to_jsonb(array['https://villacopenhagen.com/wp-content/uploads/2024/08/Official-Press-kit-Villa_-Copenhagen.pdf','https://www.tripadvisor.com/Hotel_Review-g189541-d17626250-Reviews-Villa_Copenhagen-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','modern_city_hotel_casual_pool_zone_coverup_smart_dining_and_rooftop_weather_practicality','source_urls',to_jsonb(array['https://villacopenhagen.com/','https://www.booking.com/hotel/dk/villa-copenhagen-kobenhavn.en-gb.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_large_sample_staff_cleanliness_comfort_consensus_with_some_checkin_service_gaps_and_no_verified_lgbtq_training','source_urls',to_jsonb(array['https://www.booking.com/hotel/dk/villa-copenhagen-kobenhavn.en-gb.html','https://www.tripadvisor.com/Hotel_Review-g189541-d17626250-Reviews-Villa_Copenhagen-Copenhagen_Zealand.html']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (941::bigint, jsonb_build_object(
      'queue_wait', 'There is no door or queue: this is a municipal public park used by walkers, families and picnickers. Cruising is informal and historically associated with quieter areas after dark. Do not treat vegetation as a private venue; stay aware of other park users and changing conditions.',
      'best_nights', 'Daylight is best for the lake, lawns and ordinary park life. Men seeking the historic cruising scene report more activity after dusk and in warmer months, but no night is programmed or guaranteed. Choose visibility and an easy exit over isolation, and check local conditions before going.',
      'crowd_mix', 'By day the park belongs to a broad city mix: residents, students, families, runners and visitors. After dark, some gay and bisexual men use quieter edges for cruising. Those uses overlap rather than forming a managed queer zone, so discretion, boundaries and respect for bystanders are essential.',
      'dress_code', 'Wear normal weather-ready park clothes and shoes suited to damp paths. There is no venue code and public nudity should never be assumed acceptable here. Keep valuables minimal, stay on routes you can navigate, and remember that consent includes privacy, distance and a clear no.',
      'staff_inclusivity', 'A public park has no hospitality staff, queer host or consent monitor. Municipal maintenance and police are not substitutes for venue safeguarding. Visit with your own safety plan, do not expose uninvolved people to sexual activity, and leave immediately if an interaction feels coercive.',
      'venue_classification', 'active_central_copenhagen_municipal_public_landscape_park_with_daytime_recreation_and_longstanding_informal_after_dark_gay_bisexual_male_cruising_association_but_no_managed_venue_door_staff_programme_or_guaranteed_scene',
      'record_status', 'public_area_context_record_not_managed_venue_do_not_publish_as_bar_club_or_staffed_cruising_facility_and_apply_public_space_consent_safety_context',
      'identity_note', 'Ørstedsparken is a public municipal park, not a gay venue. Its queer relevance is a longstanding but informal cruising association that coexists with ordinary park use and provides no staff, privacy or safeguarding.',
      'source_urls', to_jsonb(array['https://en.wikipedia.org/wiki/%C3%98rstedsparken','https://www.tripadvisor.dk/Attraction_Review-g189541-d593429-Reviews-Oerstedsparken-Copenhagen_Zealand.html','https://www.cruisinggays.com/copenhagen/areas/33694-orstedsparken/','https://www.reddit.com/r/copenhagen/comments/1p0hzp6/gay_events_in_copenhagen/','https://www.gjss.org/sites/default/files/issues/Journal-05-02_Full-Issue_0.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','municipal_public_park_without_door_queue_or_private_venue_and_informal_quiet_area_cruising','source_urls',to_jsonb(array['https://en.wikipedia.org/wiki/%C3%98rstedsparken','https://www.cruisinggays.com/copenhagen/areas/33694-orstedsparken/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','daylight_recreation_and_unprogrammed_warm_season_after_dusk_cruising_with_no_guaranteed_activity','source_urls',to_jsonb(array['https://www.tripadvisor.dk/Attraction_Review-g189541-d593429-Reviews-Oerstedsparken-Copenhagen_Zealand.html','https://www.reddit.com/r/copenhagen/comments/1p0hzp6/gay_events_in_copenhagen/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','broad_daytime_public_mix_overlapping_with_after_dark_gay_bisexual_male_cruising','source_urls',to_jsonb(array['https://www.tripadvisor.dk/Attraction_Review-g189541-d593429-Reviews-Oerstedsparken-Copenhagen_Zealand.html','https://www.gjss.org/sites/default/files/issues/Journal-05-02_Full-Issue_0.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','no_code_with_weather_path_safety_public_nudity_boundary_and_consent_practicality','source_urls',to_jsonb(array['https://en.wikipedia.org/wiki/%C3%98rstedsparken','https://www.cruisinggays.com/copenhagen/areas/33694-orstedsparken/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','no_venue_staff_host_consent_monitor_or_private_safeguarding_system_in_public_park','source_urls',to_jsonb(array['https://en.wikipedia.org/wiki/%C3%98rstedsparken','https://www.gjss.org/sites/default/files/issues/Journal-05-02_Full-Issue_0.pdf']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1459::bigint, jsonb_build_object(
      'queue_wait', 'This all-day café, cocktail bar and gallery usually has no formal line, but its small Old Town setting fills quickly for late drinks. Go before 21:00 for a table and the artwork; later hours are more compressed. Seasonal schedules can shift, so check the same-day listing.',
      'best_nights', 'Start with coffee or an early cocktail, then stay as the music and bar energy rise. Friday and Saturday are busiest; a warm weekday suits the courtyard-like street atmosphere and conversation. It is a creative gay-friendly bar, not a dedicated gay club or guaranteed party every night.',
      'crowd_mix', 'Artists, local regulars, queer visitors, couples and mixed friend groups create an eclectic Chania crowd. LGBTQ+ travellers are visible and welcome, but the venue is not exclusively queer. Tourism is stronger in summer, while local creative character keeps it from feeling like a generic resort bar.',
      'dress_code', 'Creative casual is natural here: shorts, trainers, colour and relaxed evening clothes all work. No formal door policy is published. Dress for Chania heat and close seating, keep bags compact, and let the playful gallery setting inspire you without expecting a costume-led event.',
      'staff_inclusivity', 'Travel and local listings consistently frame the space as welcoming and gay-friendly, with cocktails, music and eclectic design praised most often. The direct review pool is modest and no formal LGBTQ+ policy was found, so describe the welcome as well established but informal.',
      'venue_classification', 'active_independent_all_day_cafe_cocktail_bar_and_art_gallery_in_chania_old_town_with_creative_eclectic_gay_friendly_identity_small_space_late_weekend_peak_and_mixed_local_queer_visitor_crowd',
      'identity_note', 'Ababa is an active gay-friendly café-bar and gallery at Isodion 12, not an exclusively gay bar. Its queer relevance comes from a longstanding welcoming creative crowd rather than a formal identity policy.',
      'source_urls', to_jsonb(array['https://www.travelgay.com/venue/ababa-bar','https://apollo.social/destinations/greece/crete','https://www.tripadvisor.it/Attraction_Review-g189415-d7162339-Reviews-Ababa_Bar-Chania_Town_Chania_Prefecture_Crete.html','https://www.rental-center-crete.com/blog/is-crete-gay-friendly/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','no_formal_line_with_small_old_town_late_drink_capacity_and_seasonal_schedule_variation','source_urls',to_jsonb(array['https://www.travelgay.com/venue/ababa-bar','https://www.tripadvisor.it/Attraction_Review-g189415-d7162339-Reviews-Ababa_Bar-Chania_Town_Chania_Prefecture_Crete.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','all_day_coffee_to_cocktail_arc_with_friday_saturday_peak_and_warm_weekday_conversation','source_urls',to_jsonb(array['https://www.travelgay.com/venue/ababa-bar','https://apollo.social/destinations/greece/crete']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','artist_local_queer_visitor_couple_and_mixed_friend_creative_summer_tourism_mix','source_urls',to_jsonb(array['https://www.travelgay.com/venue/ababa-bar','https://www.rental-center-crete.com/blog/is-crete-gay-friendly/']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','creative_casual_heat_ready_style_without_published_formal_door_policy','source_urls',to_jsonb(array['https://www.travelgay.com/venue/ababa-bar','https://www.tripadvisor.it/Attraction_Review-g189415-d7162339-Reviews-Ababa_Bar-Chania_Town_Chania_Prefecture_Crete.html']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','consistent_informal_gay_friendly_welcome_signal_with_modest_review_pool_and_no_formal_policy','source_urls',to_jsonb(array['https://www.travelgay.com/venue/ababa-bar','https://apollo.social/destinations/greece/crete','https://www.rental-center-crete.com/blog/is-crete-gay-friendly/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    )),
    (1462::bigint, jsonb_build_object(
      'queue_wait', 'Tickets must be bought online in advance and are not sold at the door. That makes booking, not queuing, the real constraint; popular Chania and Heraklion summer dates can sell out. Use only the venue named on your ticket, because the series moves between cities and rooms.',
      'best_nights', 'Choose a published Thursday, Friday or Saturday summer date in the city that fits your route. The 2026 calendar shows recurring Chania nights and selected Heraklion editions rather than a permanent weekly club. The strongest night is the actual ticketed event, not an old map pin.',
      'crowd_mix', 'Queer locals, island workers, LGBTQ+ holidaymakers, friends and allies meet across Chania and Heraklion. The seasonal format creates a visitor-heavy but genuinely mixed room. It is one of the clearest dedicated queer party options on Crete, without implying every host venue is queer-owned.',
      'dress_code', 'Party-ready summer clothes, trainers, mesh, colour and expressive looks fit the published atmosphere. No formal fashion code was found. Bring valid ticket details and ID, travel light, and respect consent on the floor; the exact host venue may impose additional practical rules.',
      'staff_inclusivity', 'The organiser explicitly builds the event around a dedicated gay and queer-friendly space where guests can be themselves. That mission is direct evidence, but staffing and accessibility can vary by host venue. Ask ahead about step-free access, cloakroom, security and support needs.',
      'venue_classification', 'active_seasonal_ticketed_roving_gay_and_queer_party_series_across_chania_and_heraklion_with_advance_online_sales_no_door_tickets_summer_thursday_friday_saturday_dates_and_mixed_local_island_worker_visitor_ally_crowd',
      'record_status', 'event_series_not_permanent_venue_publish_only_with_current_dated_ticket_link_host_city_and_exact_location_and_remove_stale_static_map_pin',
      'identity_note', 'Apollo Party Crete is an active seasonal event series, not a permanent bar or club. Each date has its own city, host venue and ticket conditions; 2026 tickets are advance-sale only.',
      'source_urls', to_jsonb(array['https://www.apollopartycrete.com/','https://apollo.social/destinations/greece/crete','https://www.reddit.com/r/crete/comments/1em4bfh','https://www.rental-center-crete.com/blog/is-crete-gay-friendly/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','advance_online_ticket_required_no_door_sales_and_event_specific_city_venue_verification','source_urls',to_jsonb(array['https://www.apollopartycrete.com/','https://apollo.social/destinations/greece/crete']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'best_nights', jsonb_build_object('status','published_summer_thursday_friday_saturday_chania_heraklion_dates_without_permanent_weekly_club','source_urls',to_jsonb(array['https://www.apollopartycrete.com/','https://www.reddit.com/r/crete/comments/1em4bfh']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','queer_local_island_worker_lgbtq_holidaymaker_friend_and_ally_roving_party_mix','source_urls',to_jsonb(array['https://www.apollopartycrete.com/','https://apollo.social/destinations/greece/crete']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'dress_code', jsonb_build_object('status','expressive_summer_partywear_with_ticket_id_consent_and_host_venue_rule_practicality','source_urls',to_jsonb(array['https://www.apollopartycrete.com/','https://apollo.social/destinations/greece/crete']::text[]),'checked_at','2026-08-07T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','organiser_declared_dedicated_gay_queer_friendly_mission_with_host_specific_access_security_variation','source_urls',to_jsonb(array['https://www.apollopartycrete.com/','https://www.rental-center-crete.com/blog/is-crete-gay-friendly/']::text[]),'checked_at','2026-08-07T00:00:00Z')
      ),'research_status','editorial_review_consensus','updated_at','2026-08-07T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1980,234,224,233,1982,941,1459,1462)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-07T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
