-- Queer Atlas venue intelligence: global review-led editorial pass, batch 39.
-- Eight Bogota records, individually researched and rewritten.
-- Diosa, Disco Jaguar and El Coq are inclusive or mixed spaces, not verified dedicated LGBTQ+ venues.
-- Checked 2026-08-06. Source names remain in evidence metadata, not reader-facing topic copy.

begin;

with reviewed(id, patch) as (
  values
    (1200::bigint, jsonb_build_object(
      'queue_wait', 'This men-only spa is built for a long visit, not a nightclub dash. Thursday can be lively without feeling jammed; regulars describe roughly four-hour stays. Arrive before the late-afternoon swell for first choice of lockers and facilities. Entry is 18+, and you may need your own underwear and soap.',
      'best_nights', 'Thursday has the clearest social pulse, with a drag or stripper show reported alongside a full, mixed-age house. Any afternoon works for the Roman pool, salt jacuzzi, steam and sauna; choose earlier hours for calm, later for cruising. It closes at 9pm, so this is a warm-up rather than an afterparty.',
      'crowd_mix', 'Gay and bi men across age groups make up the room, with Bogotanos at the core and travellers drawn by its long history. Bodies and levels of undress vary: one regular counted a near-even split between underwear and nude. It is explicitly men-only, so it is not a broad all-genders queer venue.',
      'dress_code', 'There is no fashion test after check-in. Underwear, towel or nudity are the practical modes, depending on the zone and your comfort. Bring clean underwear, flip-flops and personal toiletries because supplies and signage have disappointed some guests. Consent matters more than confidence in the cruising areas.',
      'staff_inclusivity', 'Recent reviewers repeatedly praise the clean facilities and friendly, knowledgeable team; the small gay-history collection gives the place unusual character. Criticism focuses on unclear wayfinding, cold showers and a play layout some find underwhelming. Accessibility details are not published clearly.',
      'venue_classification', 'active_men_only_gay_spa_with_long_bogota_history_pool_jacuzzis_sauna_steam_cruising_show_programming_and_strong_cleanliness_service_consensus',
      'source_urls', to_jsonb(array['https://complicesspa.com/quienes-somos/','https://wanderlog.com/place/details/6023902/c%C3%B3mplices-spa','https://www.top-rated.online/cities/Bogota/place/p/13156985/C%C3%B3mplices%2BSPA','https://www.thegayagenda.fyi/bogota/businesses/complices-spa/','https://linktr.ee/ComplicesSpa']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','official_hours_long_visit_pattern_thursday_crowding_and_practical_checkin_supply_context','source_urls',to_jsonb(array['https://complicesspa.com/quienes-somos/','https://wanderlog.com/place/details/6023902/c%C3%B3mplices-spa']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','thursday_show_social_energy_and_official_daily_facility_schedule','source_urls',to_jsonb(array['https://complicesspa.com/quienes-somos/','https://wanderlog.com/place/details/6023902/c%C3%B3mplices-spa','https://linktr.ee/ComplicesSpa']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','men_only_gay_bi_mixed_age_local_traveller_and_variable_undress_consensus','source_urls',to_jsonb(array['https://complicesspa.com/quienes-somos/','https://wanderlog.com/place/details/6023902/c%C3%B3mplices-spa','https://www.thegayagenda.fyi/bogota/businesses/complices-spa/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','underwear_towel_nudity_flipflop_toiletry_and_consent_context_without_fashion_door','source_urls',to_jsonb(array['https://complicesspa.com/quienes-somos/','https://wanderlog.com/place/details/6023902/c%C3%B3mplices-spa']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_clean_friendly_knowledgeable_service_consensus_balanced_against_wayfinding_shower_layout_and_access_gaps','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6023902/c%C3%B3mplices-spa','https://www.top-rated.online/cities/Bogota/place/p/13156985/C%C3%B3mplices%2BSPA']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (589::bigint, jsonb_build_object(
      'queue_wait', 'This is a neighbourhood-scale gay bar, so the pressure point is usually the bar rather than a velvet-rope queue. Thursday starts gently; Friday and Saturday build after dinner and can tighten toward midnight. Published hours currently end at 3am. Ask the price before ordering, as recent guests flag costly beer.',
      'best_nights', 'Friday and Saturday give the fullest dance-bar energy; Thursday is better when you want room to talk. The appeal is straightforward music, drinks and local company rather than a giant production. Check the live page first, because regulars say the offer has changed and attendance has softened.',
      'crowd_mix', 'Gay men and queer Chapinero regulars lead, with friends and travellers folding into a mostly local room. It feels less like a destination megaclub and more like a familiar stop on the neighbourhood circuit. The crowd can be thinner than older accounts suggest, especially when prices or programming miss the mood.',
      'dress_code', 'Casual night-out clothes work: fitted tee, jeans, sneakers or a brighter party look. No reliable formal code is published, and the venue is praised more for ventilation and an easy atmosphere than door theatre. Dress for dancing until 3am and keep valuables close when moving through Chapinero late.',
      'staff_inclusivity', 'Many guests describe friendly service, pleasant music and a comfortable setup. The weaker signal is commercial: newer reviews question steep beer prices and changed offerings, while an older complaint alleges dishonest service. Confirm prices aloud, keep the receipt and raise any mismatch before leaving the bar.',
      'venue_classification', 'active_chapinero_gay_neighbourhood_dance_bar_with_thursday_to_saturday_hours_local_regular_energy_good_ventilation_and_material_price_value_concerns',
      'identity_note', 'Current directory evidence places Coyote Crazy at Carrera 9 #59-09; the stored record has no street address and needs location verification before routing.',
      'source_urls', to_jsonb(array['https://www.thegayagenda.fyi/bogota/businesses/coyote-crazy/','https://es.restaurantguru.com/Coyote-Crazy-Disco-Dance-Bogota']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','small_bar_weekend_build_published_three_am_close_and_current_beer_price_context','source_urls',to_jsonb(array['https://www.thegayagenda.fyi/bogota/businesses/coyote-crazy/','https://es.restaurantguru.com/Coyote-Crazy-Disco-Dance-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','thursday_conversation_friday_saturday_energy_and_current_programming_attendance_change_reports','source_urls',to_jsonb(array['https://www.thegayagenda.fyi/bogota/businesses/coyote-crazy/','https://es.restaurantguru.com/Coyote-Crazy-Disco-Dance-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_queer_chapinero_regular_friend_and_traveller_mix_with_variable_current_attendance','source_urls',to_jsonb(array['https://www.thegayagenda.fyi/bogota/businesses/coyote-crazy/','https://es.restaurantguru.com/Coyote-Crazy-Disco-Dance-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_dance_bar_good_ventilation_and_late_chapinero_practical_context_without_formal_code','source_urls',to_jsonb(array['https://www.thegayagenda.fyi/bogota/businesses/coyote-crazy/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','friendly_service_music_and_facility_praise_balanced_against_price_value_and_older_honesty_complaint','source_urls',to_jsonb(array['https://www.thegayagenda.fyi/bogota/businesses/coyote-crazy/','https://es.restaurantguru.com/Coyote-Crazy-Disco-Dance-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (592::bigint, jsonb_build_object(
      'queue_wait', 'Because the sauna and hostel run around the clock, there is rarely one nightclub-style arrival line. Early morning is repeatedly described as surprisingly busy; quieter periods vary. At peak times, the real wait may be for a locker or a favoured wet area. Confirm the day rate before entering the hostel-sauna complex.',
      'best_nights', 'This is one place where “best night” misses the point: recent visitors find energy after midnight and into early morning. Go then for the strongest social and cruising pulse; choose daytime for a calmer circuit through the sauna, steam and whirlpool. Twenty-four-hour access is the defining advantage.',
      'crowd_mix', 'Gay and bi men form the core, mixing Bogotanos, hostel travellers and international visitors across ages and body types. The overnight rhythm is more transient than a neighbourhood bar. English-speaking guests report no language barrier, but this remains a men-focused sauna, not an all-genders space.',
      'dress_code', 'Street clothes end at the locker; towel, swimwear or nudity depends on the zone and your comfort. Bring flip-flops and basic toiletries, stay hydrated and keep consent explicit in dark or cruising areas. There is no fashion door, but hostel guests should separate valuables and room keys from wet-area belongings.',
      'staff_inclusivity', 'Current 2026 reviews praise clean, working facilities and a professional, attentive team; guests say limited Spanish was manageable. That outweighs older mixed ratings. Detailed mobility access, trans inclusion and written consent procedures were not found, so verify specific needs directly.',
      'venue_classification', 'active_twenty_four_hour_men_focused_gay_sauna_and_hostel_with_overnight_early_morning_energy_diverse_traveller_mix_and_strong_current_cleanliness_service_reviews',
      'identity_note', 'Current directory evidence places Dagoas at Calle 59 #9-34; the stored record has no street address and should be verified before directions are shown.',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/5759998','https://qlist.app/venues/Bogota/Dagoas-Sauna-Hostel-Gay/WFpjTVEvMER5RVdReko1Z0x4ek9rQQ','https://es.travelgay.com/venue/dagoas-sauna-hostel']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','current_twenty_four_hour_operation_early_morning_peak_and_facility_capacity_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5759998','https://qlist.app/venues/Bogota/Dagoas-Sauna-Hostel-Gay/WFpjTVEvMER5RVdReko1Z0x4ek9rQQ']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','overnight_early_morning_social_cruising_peak_and_quieter_daytime_pattern','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5759998','https://qlist.app/venues/Bogota/Dagoas-Sauna-Hostel-Gay/WFpjTVEvMER5RVdReko1Z0x4ek9rQQ','https://es.travelgay.com/venue/dagoas-sauna-hostel']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_bi_men_local_hostel_traveller_international_mixed_age_and_body_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5759998','https://qlist.app/venues/Bogota/Dagoas-Sauna-Hostel-Gay/WFpjTVEvMER5RVdReko1Z0x4ek9rQQ']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','locker_towel_swimwear_nudity_flipflop_hydration_consent_and_hostel_valuables_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5759998','https://es.travelgay.com/venue/dagoas-sauna-hostel']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_2026_clean_working_facility_professional_attentive_and_language_access_praise_with_policy_gaps','source_urls',to_jsonb(array['https://wanderlog.com/place/details/5759998','https://qlist.app/venues/Bogota/Dagoas-Sauna-Hostel-Gay/WFpjTVEvMER5RVdReko1Z0x4ek9rQQ']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1681::bigint, jsonb_build_object(
      'queue_wait', 'This is a craft-beer café, not a door-controlled club. Walk-ins usually make sense, but brunch and cultural sessions can slow the kitchen; one recent guest waited more than an hour while later tables were served first. Reserve if a book event matters, and allow extra time when the room is visibly busy.',
      'best_nights', 'Come in daylight or early evening for beer, books and conversation. The women-founded project suits a thoughtful date, feminist reading stop or soft start before nightlife—not late dancing. Check the Teusaquillo calendar itself; events advertised by its Candelaria sister may not happen here.',
      'crowd_mix', 'Women, readers, craft-beer drinkers, neighbourhood creatives, couples and queer-friendly groups shape the room. Its feminist story challenges beer culture as male territory. The welcome is meaningful, but the venue is not documented as LGBTQ+-majority; expect locals and mainstream visitors together.',
      'dress_code', 'Anything clean and relaxed works: daytime layers, denim, a date-night shirt or colourful queer casual. There is no reported selection at the door. Bogotá evenings cool quickly, and the venue offers outdoor seating, so carry a light jacket. The atmosphere rewards curiosity about beer and books more than a polished look.',
      'staff_inclusivity', 'The project’s women-led, feminist identity is a strong cultural welcome, and the Teusaquillo branch is listed with wheelchair access. Service evidence is thinner and one 2026 brunch account describes severe delays and unfair order handling. Ask about step-free routing and flag timing needs before placing a meal order.',
      'venue_classification', 'active_teusaquillo_women_founded_feminist_craft_beer_cafe_and_bookish_cultural_space_with_broad_queer_friendly_welcome_but_no_verified_lgbtq_majority',
      'source_urls', to_jsonb(array['https://www.facebook.com/diosacerveceria/','https://es.restaurantguru.com/Diosa-Cerveceria-Bogota','https://www.elespectador.com/el-magazin-cultural/daniela-villamizar-la-mujer-que-quiso-devolverle-la-feminidad-a-la-cerveza/','https://www.lafm.com.co/sociedad/matorral-libros-y-cerveza-en-un-rincon-unico-de-bogota-358080','https://www.bienalbogota.com/sites/default/files/2025-09/Bog25_Directorio_Distritos_Creativos_Agenda_Alterna_v20250925.pdf','https://visitbogota.co/sites/default/files/2026-06/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','walkin_cafe_context_with_material_current_brunch_delay_and_order_fairness_report','source_urls',to_jsonb(array['https://es.restaurantguru.com/Diosa-Cerveceria-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','daytime_early_evening_beer_books_feminist_culture_and_branch_specific_programming_context','source_urls',to_jsonb(array['https://www.elespectador.com/el-magazin-cultural/daniela-villamizar-la-mujer-que-quiso-devolverle-la-feminidad-a-la-cerveza/','https://www.lafm.com.co/sociedad/matorral-libros-y-cerveza-en-un-rincon-unico-de-bogota-358080','https://www.bienalbogota.com/sites/default/files/2025-09/Bog25_Directorio_Distritos_Creativos_Agenda_Alterna_v20250925.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','women_reader_craft_beer_creative_couple_queer_friendly_and_mainstream_local_mix_without_lgbtq_majority','source_urls',to_jsonb(array['https://www.elespectador.com/el-magazin-cultural/daniela-villamizar-la-mujer-que-quiso-devolverle-la-feminidad-a-la-cerveza/','https://www.lafm.com.co/sociedad/matorral-libros-y-cerveza-en-un-rincon-unico-de-bogota-358080','https://visitbogota.co/sites/default/files/2026-06/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_cafe_date_outdoor_and_cool_evening_context_without_door_selection','source_urls',to_jsonb(array['https://es.restaurantguru.com/Diosa-Cerveceria-Bogota','https://www.elespectador.com/el-magazin-cultural/daniela-villamizar-la-mujer-que-quiso-devolverle-la-feminidad-a-la-cerveza/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','women_led_feminist_mission_and_listed_wheelchair_access_balanced_against_current_service_delay_report','source_urls',to_jsonb(array['https://www.elespectador.com/el-magazin-cultural/daniela-villamizar-la-mujer-que-quiso-devolverle-la-feminidad-a-la-cerveza/','https://es.restaurantguru.com/Diosa-Cerveceria-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1194::bigint, jsonb_build_object(
      'queue_wait', 'A popular Friday or Saturday can mean a cover queue and congestion between rooms. Four hours is a common full visit, so arrive before midnight to explore before the floors compress. Thursday listings vary; older safety complaints make it wise to confirm the cover and payment method at entry.',
      'best_nights', 'Friday and Saturday deliver the complete multi-room sweep: salsa and merengue beside electronic, reggaetón, soul, disco and funk. Pick Thursday only after confirming it is active. Go for a Colombian crossover night with options, not a guaranteed queer programme; the room can change personality with each DJ.',
      'crowd_mix', 'Bogotanos over 30 are repeatedly visible, joined by younger groups, dancers and international visitors. The club appears in LGBTQ+ city guides, but the working crowd is mixed rather than queer-majority. Locals outnumber destination tourists on ordinary weekends; familiar Colombian rhythms are the social glue.',
      'dress_code', 'Smart-casual party clothes fit the polished multi-room setting, but no dependable written code was found. Wear shoes that can move from salsa to electronic floors and keep a secure layer for the journey home. A neat look is prudent; do not mistake inclusion in a queer guide for a no-discretion door.',
      'staff_inclusivity', 'Many guests enjoy the musical range and lively local atmosphere. The review record also contains serious complaints about security, dismissive staff, cover handling and card disputes, alongside newer criticism of the DJ mix. Confirm every charge, protect your drink and seek help early if something feels wrong.',
      'venue_classification', 'active_mixed_multiroom_bogota_crossover_club_included_in_lgbtq_guides_with_local_over_thirty_strength_but_no_verified_queer_majority_and_material_service_safety_complaints',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/978671/disco-jaguar','https://es.restaurantguru.com/Disco-Jaguar-Bogota','https://www.idt.gov.co/sites/default/files/Guia-LGBTI-Digital.pdf','https://revistadc.com/wp-content/uploads/2026/03/MAPA-BOGOTA-FEBRERO-web.pdf','https://www.travelgay.com/bogota-gay-bars']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','popular_weekend_cover_multiroom_congestion_four_hour_visit_and_payment_safety_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978671/disco-jaguar','https://es.restaurantguru.com/Disco-Jaguar-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_multiroom_salsa_merengue_electronic_reggaeton_soul_disco_funk_and_variable_thursday','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978671/disco-jaguar','https://es.restaurantguru.com/Disco-Jaguar-Bogota','https://revistadc.com/wp-content/uploads/2026/03/MAPA-BOGOTA-FEBRERO-web.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','mostly_local_over_thirty_younger_group_dancer_and_international_mix_without_verified_queer_majority','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978671/disco-jaguar','https://www.idt.gov.co/sites/default/files/Guia-LGBTI-Digital.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','polished_multiroom_smart_casual_context_without_reliable_published_code','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978671/disco-jaguar','https://es.restaurantguru.com/Disco-Jaguar-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','music_and_atmosphere_praise_balanced_against_material_security_staff_cover_card_and_current_dj_complaints','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978671/disco-jaguar','https://es.restaurantguru.com/Disco-Jaguar-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1673::bigint, jsonb_build_object(
      'queue_wait', 'The door can be the whole story. A named DJ night draws a line, and entry is often cash; recent guests report expensive cover, list disputes and selective refusals. Arrive early with the event details saved, confirm cover before joining, and carry a backup plan. Inside, the compact room and terrace fill quickly.',
      'best_nights', 'Wednesday’s electronic series is the clearest recurring anchor; Thursday can have sharper local energy, while weekends depend on the DJ. Go for eclectic house and electronic curation, not generic crossover. Check the lineup: a strong selector is what turns this small room into a destination.',
      'crowd_mix', 'Style-conscious Zona T locals, electronic regulars, creative groups and visiting DJ followers lead the floor. Queer guests are part of the mix, but current evidence does not establish an LGBTQ+-majority room. It can feel socially polished and insider-led, with list culture creating a sharper local-outsider divide.',
      'dress_code', 'A considered look helps: dark clubwear, tailored casual, interesting texture or clean minimal pieces fit the vintage-industrial room. No clear written code exists, yet a 2025 guest reports rejection framed around clothing. Treat the door as discretionary, avoid beachwear and keep another electronic option ready.',
      'staff_inclusivity', 'Praise centres on the DJs, atmosphere and some warm Thursday staff. Counter-signals are substantial: reports of elitist admission, dress-based discrimination, poor ventilation, self-service at high prices and a card overcharge later reversed. Pay cash only with a clear price, or check the terminal before approving.',
      'venue_classification', 'active_zona_t_electronic_house_club_with_stylish_local_insider_crowd_cash_entry_and_material_door_discrimination_payment_ventilation_and_value_concerns_not_verified_lgbtq_majority',
      'source_urls', to_jsonb(array['https://wanderlog.com/es/place/details/1826714/el-coq','https://co.iqos.com/es/noticias/vida-nocturna-bogota-el-coq-bogota','https://www.idt.gov.co/sites/default/files/4.2%20Gu%C3%ADa%20LGBTI%20Espa%C3%B1ol.pdf','https://observatorio.desarrolloeconomico.gov.co/wp-content/uploads/2025/03/cuaderno40.pdf','https://www.instagram.com/elcoqcoq/']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','dj_event_line_cash_cover_list_dispute_selective_door_and_compact_capacity_reports','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/1826714/el-coq','https://www.instagram.com/elcoqcoq/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','recurring_wednesday_electronic_thursday_local_energy_and_lineup_led_weekend_pattern','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/1826714/el-coq','https://co.iqos.com/es/noticias/vida-nocturna-bogota-el-coq-bogota','https://observatorio.desarrolloeconomico.gov.co/wp-content/uploads/2025/03/cuaderno40.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','style_conscious_zona_t_local_electronic_creative_and_visiting_dj_follower_mix_without_lgbtq_majority','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/1826714/el-coq','https://observatorio.desarrolloeconomico.gov.co/wp-content/uploads/2025/03/cuaderno40.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','stylish_electronic_room_discretionary_door_and_material_2025_dress_based_refusal_report_without_written_code','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/1826714/el-coq']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','dj_atmosphere_and_some_staff_praise_balanced_against_elitist_door_discrimination_ventilation_value_and_card_charge_reports','source_urls',to_jsonb(array['https://wanderlog.com/es/place/details/1826714/el-coq']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (587::bigint, jsonb_build_object(
      'queue_wait', 'Circuit-scale nights can produce a real line and costly cover; quieter editions move faster. Reviews include efficient entry, a denied-admission complaint and a disputed 120,000 COP charge. Buy through the official event link, save the terms and arrive before the headline set.',
      'best_nights', 'Friday and Saturday are the main play, especially when the rooftop and a named circuit event are active. This is polished, high-energy El Mozo—not the old neighbourhood-bar portrait some guides copy. Follow the current flyer for music, hosts and venue because the brand has used more than one address.',
      'crowd_mix', 'Gay men are the visible centre, joined by circuit regulars, polished Zona Rosa groups, queer friends and international party travellers. Locals give the room its social code, but big events draw more visitors than a Chapinero beer bar. Expect a dressier, more male and image-aware crowd.',
      'dress_code', 'Lean polished and party-ready: fitted separates, fashion sneakers, clubwear or a sharper circuit look. The terrace rewards a layer for Bogotá’s cold air; the dance floor needs breathable fabric. No stable written code was found, and one guest reports rude refusal, so confirm themed requirements and keep a backup.',
      'staff_inclusivity', 'Recent reviews praise the design, shows, atmosphere and fast service; the venue also has historic public recognition for anti-discrimination values. That sits beside a denied-entry complaint and disputed-cover refund request. Inclusion must be judged at today’s door, with pricing shown clearly.',
      'venue_classification', 'active_zona_rosa_gay_male_led_rooftop_and_circuit_club_with_polished_local_traveller_crowd_strong_show_design_praise_and_material_door_cover_transparency_concerns',
      'identity_note', 'Current venue evidence places El Mozo at Avenida Calle 85 #12-51. Some current guides still conflate it with an older Chapinero address, so event posts should control routing.',
      'source_urls', to_jsonb(array['https://www.instagram.com/elmozocolombia1/','https://wanderlog.com/place/details/978673/el-mozo-club','https://www.gayout.com/south-america/colombia/bogota/bars/el-mozo-bogota','https://historico.participacionbogota.gov.co/el-mozo-primer-establecimiento-publico-libre-de-discriminacion-en-bogota','https://www.gaytravel4u.es/event/el-mozo-circuit-events-bogota/','https://visitbogota.co/sites/default/files/2026-06/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','circuit_event_line_cover_efficiency_denial_and_disputed_charge_reports_with_official_ticket_guidance','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978673/el-mozo-club','https://www.gayout.com/south-america/colombia/bogota/bars/el-mozo-bogota','https://www.gaytravel4u.es/event/el-mozo-circuit-events-bogota/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','friday_saturday_rooftop_named_circuit_event_and_current_flyer_led_identity','source_urls',to_jsonb(array['https://www.instagram.com/elmozocolombia1/','https://wanderlog.com/place/details/978673/el-mozo-club','https://www.gaytravel4u.es/event/el-mozo-circuit-events-bogota/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','gay_male_circuit_polished_zona_rosa_local_queer_friend_and_international_party_traveller_mix','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978673/el-mozo-club','https://www.gaytravel4u.es/event/el-mozo-circuit-events-bogota/','https://visitbogota.co/sites/default/files/2026-06/Gu%C3%ADa%20LGBTI%20Digital%20ok.pdf']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','polished_circuit_rooftop_cold_air_dance_floor_and_unclear_door_code_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978673/el-mozo-club','https://www.gaytravel4u.es/event/el-mozo-circuit-events-bogota/']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','current_design_show_atmosphere_service_praise_and_historic_anti_discrimination_recognition_balanced_against_door_cover_reports','source_urls',to_jsonb(array['https://wanderlog.com/place/details/978673/el-mozo-club','https://www.gayout.com/south-america/colombia/bogota/bars/el-mozo-bogota','https://historico.participacionbogota.gov.co/el-mozo-primer-establecimiento-publico-libre-de-discriminacion-en-bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    )),
    (1196::bigint, jsonb_build_object(
      'queue_wait', 'The room is intimate and usually works as a first stop rather than a queue marathon. Arrive before the live drag on Wednesday or karaoke on Thursday if you want a seat and an easy song request; later, groups spill in before larger clubs. Confirm opening on the day because published weekly hours do not agree.',
      'best_nights', 'Wednesday brings live drag; Thursday turns the old romantic videos into communal karaoke. Friday and Saturday are best for the full nostalgic singalong before crossing to a bigger dance floor. Come for boleros, Latin heartbreak and memory—not current-chart club music. The songs, more than the clock, run the room.',
      'crowd_mix', 'Queer Bogotanos, gay men across generations, drag regulars, couples, friend groups and curious visitors share a proudly sentimental local bar. Tourists arrive because of its history and proximity to bigger clubs, yet Spanish-language songs keep the centre of gravity unmistakably Colombian and neighbourhood-led.',
      'dress_code', 'Wear what lets you sing: relaxed jeans, a date-night shirt, vintage colour or camp romantic detail. There is no known fashion door, and the kitsch, memory-covered room rewards personality over polish. Bogotá gets cold after midnight, so bring a layer for the walk between bars and keep your phone tucked away outside.',
      'staff_inclusivity', 'Local storytelling and many guest accounts describe a warm gay institution built around songs and shared memories. A serious 2026 review alleges theft and drug dealing; that is not proven fact, but cannot be ignored. Watch your drink and belongings, stay with friends and report concerns immediately.',
      'venue_classification', 'active_historic_bogota_gay_video_singalong_drag_and_karaoke_bar_with_multigenerational_local_crowd_warm_community_identity_and_material_current_safety_allegation',
      'source_urls', to_jsonb(array['https://wanderlog.com/place/details/6062060/the-dog-and-the-calandria','https://es.travelgay.com/venue/el-perro-y-la-calandria-bogota','https://www.tripadvisor.ca/Attraction_Review-g294074-d10036093-Reviews-El_Perro_y_la_Calandria-Bogota.html','https://es.restaurantguru.com/El-Perro-Y-La-Calandria-Bogota','https://www.sudakas.co/post/el-perro-y-la-calandria-el-bar-bogotano-que-colecciona-recuerdos-escondidos-en-canciones']::text[]),
      'topic_evidence', jsonb_build_object(
        'queue_wait', jsonb_build_object('status','intimate_first_stop_early_seating_drag_karaoke_song_request_and_conflicting_hours_context','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6062060/the-dog-and-the-calandria','https://es.travelgay.com/venue/el-perro-y-la-calandria-bogota','https://www.tripadvisor.ca/Attraction_Review-g294074-d10036093-Reviews-El_Perro_y_la_Calandria-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'best_nights', jsonb_build_object('status','wednesday_live_drag_thursday_karaoke_weekend_warmup_and_romantic_latin_singalong_identity','source_urls',to_jsonb(array['https://wanderlog.com/place/details/6062060/the-dog-and-the-calandria','https://www.sudakas.co/post/el-perro-y-la-calandria-el-bar-bogotano-que-colecciona-recuerdos-escondidos-en-canciones','https://es.travelgay.com/venue/el-perro-y-la-calandria-bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'crowd_mix', jsonb_build_object('status','multigenerational_queer_bogotano_gay_drag_couple_friend_and_curious_visitor_mix_with_local_song_centre','source_urls',to_jsonb(array['https://www.sudakas.co/post/el-perro-y-la-calandria-el-bar-bogotano-que-colecciona-recuerdos-escondidos-en-canciones','https://wanderlog.com/place/details/6062060/the-dog-and-the-calandria','https://www.tripadvisor.ca/Attraction_Review-g294074-d10036093-Reviews-El_Perro_y_la_Calandria-Bogota.html']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'dress_code', jsonb_build_object('status','informal_kitsch_romantic_singalong_and_cold_late_bogota_context_without_fashion_door','source_urls',to_jsonb(array['https://www.sudakas.co/post/el-perro-y-la-calandria-el-bar-bogotano-que-colecciona-recuerdos-escondidos-en-canciones','https://es.travelgay.com/venue/el-perro-y-la-calandria-bogota']::text[]),'checked_at','2026-08-06T00:00:00Z'),
        'staff_inclusivity', jsonb_build_object('status','strong_warm_affectionate_community_identity_balanced_against_single_material_2026_theft_and_drug_allegation','source_urls',to_jsonb(array['https://www.sudakas.co/post/el-perro-y-la-calandria-el-bar-bogotano-que-colecciona-recuerdos-escondidos-en-canciones','https://wanderlog.com/place/details/6062060/the-dog-and-the-calandria','https://es.restaurantguru.com/El-Perro-Y-La-Calandria-Bogota']::text[]),'checked_at','2026-08-06T00:00:00Z')
      ),
      'research_status', 'editorial_review_consensus','updated_at', '2026-08-06T00:00:00Z'
    ))
)
update public.places as p
set venue_intel = coalesce(p.venue_intel, '{}'::jsonb) || reviewed.patch
from reviewed
where p.id = reviewed.id;

do $$
declare updated_count integer;
begin
  select count(*) into updated_count from public.places
  where id in (1200,589,592,1681,1194,1673,587,1196)
    and venue_intel->>'research_status' = 'editorial_review_consensus'
    and venue_intel->>'updated_at' = '2026-08-06T00:00:00Z';
  if updated_count <> 8 then raise exception 'Expected 8 globally reviewed venue rows, found %', updated_count; end if;
end $$;

commit;
