import json,re,pathlib
root=pathlib.Path(r'C:\Users\anfeb\Desktop\Websida\gay-guide')
rows=[
('All She Wrote Books','boston','75 Washington Street, Somerville, MA 02143, United States',42.3868,-71.0836,'https://www.allshewrotebooks.com/','Monday closed; Tuesday-Wednesday 11:00-18:00; Thursday-Saturday 11:00-19:00; Sunday 12:00-17:00.','Somerville’s queer-owned feminist bookstore gives underrepresented writers the whole room: intersectional fiction, politics and children’s books live beside author talks and community conversations.','warm East Somerville reading room with a radical spine','Intersectional feminist and queer books across genres, gifts, events and community resources.','Visit midweek for thoughtful recommendations; event nights trade quiet browsing for lively conversation.','The web catalogue, gift cards and ordering extend the shop beyond Boston; checkout sets delivery terms.','Online checkout and the Washington Street register expose their current methods; ask about institutional orders.','Queer-owned, survivor-informed and explicitly designed as a safe, supportive all-ages gathering space.'),
('Good Vibrations Brookline','boston','308A Harvard Street, Brookline, MA 02446, United States',42.3427,-71.1215,'https://www.goodvibes.com/content/c/Good-Vibes-Store-Locations/','Monday-Thursday 11:00-19:00; Friday-Saturday 12:30-20:30; Sunday 12:00-18:00.','Brookline’s sex-positive boutique replaces adult-shop awkwardness with informed conversation, body-safe pleasure products and an educational tradition shaped by women and queer communities.','bright, expert pleasure shopping without shame or sleaze','Toys, lubricants, safer-sex supplies, books, lingerie and practical product education.','Early weekday hours offer the calmest window for private questions and side-by-side product comparison.','The full web store ships separately from branch inventory; verify pickup and delivery in checkout.','Current cards and wallets appear at checkout; opened intimate products can carry hygiene restrictions.','The operator marks Brookline wheelchair accessible and builds service around inclusive, nonjudgmental education.'),
('Out of the Closet - Dallas','dallas','3920 Cedar Springs Road, Dallas, TX 75219, United States',32.8114,-96.8095,'https://outofthecloset.org/locations/dallas-thrift-store/','Monday-Saturday 10:00-19:00; Sunday 10:00-18:00.','At the heart of Oak Lawn, this thrift store turns rotating vintage racks and home finds into funding for HIV prevention, treatment and free testing through AIDS Healthcare Foundation.','Cedar Springs bargain hunt with healthcare built into the mission','Second-hand clothing, shoes, books, records, decor and household goods plus donation intake and health services.','Arrive near opening for fresh rails; phone first when testing or a large furniture donation is the priority.','Selected chain finds appear on Poshmark, while Dallas floor stock remains an in-person surprise.','Bring a mainstream card and confirm branch cash or wallet support; donations use a separate receipt process.','An official LGBTQIA+ safe space with discreet HIV testing; branch clinical schedules should be confirmed.'),
('Skivvies','dallas','4001 Cedar Springs Road, Unit C, Dallas, TX 75219, United States',32.8122,-96.8088,'https://skivviesdallas.myshopify.com/','Sunday 11:00-22:00; Monday-Thursday 10:00-22:00; Friday-Saturday 10:00-23:00.','A long-running Cedar Springs outfitter where designer underwear, jocks, club shirts and cheeky gifts are selected for the gay Dallas calendar rather than a generic menswear floor.','Oak Lawn confidence shop with late hours and serious underwear range','Designer underwear, swimwear, casual shirts, Pride pieces, adult novelties, caps and home gifts.','Go before Friday evening for sizing help; Pride and party weekends reward buying the essential look early.','The Shopify storefront supports advance browsing; stock and collection options are finalized online.','Apple Pay, contactless and credit cards are reported in store; review intimate-apparel return limits first.','Gay-community specialist with wheelchair access reported; adult items share space with ordinary apparel.'),
('(dis)obedience','denver','3605 West Colfax Avenue, Denver, CO 80204, United States',39.7402,-105.0352,'https://www.disobediencedenver.com/','Wednesday-Saturday 12:00-19:00; Sunday-Tuesday closed.','Denver’s queer-owned adult shop edits out needless gender labels and fills the shelves with trans-inclusive, size-inclusive pleasure products, safer materials and patient education.','West Colfax resistance, body safety and playful kink in one affirming room','Gender-neutral toys, packers, harnesses, apparel, lubricants, BDSM gear and queer-maker products.','Wednesday afternoon is best for unhurried education; the four-day week makes advance planning worthwhile.','Tracked USPS Priority shipping is standard and orders over USD 70 qualify for free shipping.','Afterpay is advertised online; sealed returns may receive exchange or credit within fourteen days.','Queer-owned, trans and nonbinary centred; orders ship in discreet, nondescript packaging.'),
('Vanilla Kink','denver','1111 Broadway, Suite 209, Denver, CO 80203, United States',39.7341,-104.9874,'https://www.vanillakinkdenver.com/','Monday-Saturday 11:00-20:00; Sunday 12:00-18:00.','Upstairs in the METLO, this queer-owned fetish emporium mixes upscale presentation with Colorado-made rope, leather and imaginative equipment for shoppers from curious beginner to committed kinkster.','Golden Triangle boutique polish with community-powered kink knowledge','Bondage, impact gear, fetishwear, lingerie, furniture, rope, queer gear and locally made equipment.','Weekday daylight leaves space for detailed material and safety questions; allow time to find the second-floor suite.','The online shop carries broad collections, though oversized furniture and local makers may follow special fulfilment.','Checkout shows current cards; ask before purchase about strict hygiene rules for intimate merchandise.','A shame-free queer shop focused on informed exploration; contact staff about lift and mobility access.'),
('The Little Gay Shop','austin','1902 East 12th Street, Austin, TX 78702, United States',30.2744,-97.7198,'https://thelittlegayshop.com/pages/austin','Sunday-Thursday 11:00-18:00; Friday-Saturday 11:00-19:00.','Austin’s compact queer culture store packs books, art, magazines and sharp political gifts from hundreds of LGBTQ+ makers into a space that also powers markets and free book clubs.','East Austin rainbow cabinet of curiosities made by the community itself','Queer books by identity and genre, original art, apparel, pins, magazines and work from independent makers.','Browse weekday afternoons for conversation; markets and club dates are better when meeting creators is the goal.','The web shop carries books and maker goods beyond the physical selection; checkout confirms shipping.','Secure checkout lists online methods; use free street parking and avoid the tow-prone dirt lot nearby.','Queer-owned and community-first, supporting hundreds of makers and hosting inclusive market programmes.'),
('BookWoman','austin','5501 North Lamar Boulevard, Suite A-105, Austin, TX 78751, United States',30.3275,-97.7273,'https://ebookwoman.com/','Monday-Friday 10:00-19:00; Saturday 10:00-18:00; Sunday 12:00-16:00.','Austin’s LGBTQ-owned feminist bookstore has spent more than four decades pairing fearless shelves with poetry, open mics and hybrid discussions that keep Texas literary resistance social.','old-school feminist bookselling with a live Austin poetry pulse','Feminist and queer fiction, poetry, politics, spirituality and children’s books plus readings and groups.','A weekday morning suits deep browsing; second-Thursday poetry is the choice for local voices and community.','The official catalogue supports ordering and event titles; availability and delivery resolve at checkout.','Web methods appear in secure checkout; call for phone orders or a book needed for same-day pickup.','LGBTQ-owned, all-ages and openly progressive, with hybrid events extending access beyond the room.'),
('TOLA. Fire Island Pines','fireisland','Main Harbor, Fire Island Pines, NY 11782, United States',40.6644,-73.0694,'https://tolanewyork.com/','Seasonal spring-autumn opening; daily hours shift through the Fire Island season.','The Pines harbour boutique translates island life into swimwear, jewellery, home objects and locally branded pieces, including the Boys of Fire Island collection that helps fund island nonprofits.','salt-air treasure hunt at the social centre of the Pines','Swimwear, apparel, jewellery, gifts, home accessories and exclusive Fire Island Pines merchandise.','Stop just after the ferry before popular sizes disappear; confirm hours in shoulder season or rough weather.','Digital gift cards work across locations, but much Pines-specific stock is best discovered on the island.','The harbour register controls seasonal methods; confirm gift-card use and returns before leaving by ferry.','A warm local fixture inside a historic queer enclave; part of partner merchandise proceeds supports nonprofits.'),
('FIG - Fire Island Goods','fireisland','160 Main Walk, Cherry Grove, NY 11782, United States',40.6613,-73.0908,'https://www.fireislandgoods.com/','Seasonal May-October; daily hours vary with the ferry season and weather.','Cherry Grove’s seasonal design shop turns mermaids, beach nostalgia and unapologetic Pride into house-label tees, swim pieces and accessories that feel born on the boardwalk.','playful Grove iconography, beach colour and collectable queer-island style','Original FIG apparel, Pride wear, swimwear, beach accessories and Cherry Grove graphic designs.','Shop early in a weekend for size choice; ferry traffic, weather and season edges can alter opening times.','The official site sells signature designs online, useful after the island shop closes for winter.','Online checkout sets cards and shipping; ask in store about exchanges that would otherwise require another ferry.','Located in the historic LGBTQ+ community of Cherry Grove; the boardwalk route is car-free and seasonal.'),
]
data=[]
for n,c,l,lat,lng,u,h,d,v,w,b,o,p,pr in rows:
 data.append(dict(name=n,city=c,type='store',description=d,hours=h,link=u,location=l,lat=lat,lng=lng,vibe=v,what=w,best=b,online=o,payment=p,privacy=pr,hours_source=u,sources=[u]))
src=(root/'supabase/city-usa-stores-batch-03-v1.sql').read_text(encoding='utf8')
src=src.replace('batch 03: New Orleans, Orlando, Washington DC, Seattle, Atlanta','batch 04: Boston, Dallas, Denver, Austin, Fire Island').replace('batch_03','batch_04')
src=re.sub(r'\$qa_usa_stores_batch_04\$\s*\[[\s\S]*?\]\s*\$qa_usa_stores_batch_04\$', '$qa_usa_stores_batch_04$\n  '+json.dumps(data,ensure_ascii=False,indent=2)+'\n  $qa_usa_stores_batch_04$',src,1)
src=src.replace("('new_orleans'),('orlando'),('washington_dc'),('seattle'),('atlanta')","('boston'),('dallas'),('denver'),('austin'),('fireisland')")
src=src.replace("('new_orleans','orlando','washington_dc','seattle','atlanta')","('boston','dallas','denver','austin','fireisland')")
(root/'supabase/city-usa-stores-batch-04-v1.sql').write_text(src,encoding='utf8')
