export const COLOMBO_CITY_SLUGS = new Set(["colombo"]);

const place = (entry) => ({ avgRating: null, reviewCount: 0, seeded: true, ...entry });

export const colomboSeedPlaces = [
  place({ id: "seed-place-colombo-love-bar", city: "colombo", name: "The Love Bar at Flamingo House", type: "bar", vibe: "maximalist Colombo 7 cocktail theatre with a quietly queer following", description: "A hidden bar inside Flamingo House where tropical colour, mischievous interiors and late cocktails replace any need for a rainbow sign. Love Bar is mixed, but its recurring queer reputation and Colombo 7 setting make it one of the city's more useful public social rooms when there is no permanent dedicated gay bar.", hours: "Evening-led and programme-dependent; verify the current opening night and reservation policy directly before travel.", link: "https://www.facebook.com/TheLoveBarColombo/", location: "58A Horton Place, Colombo 07, Sri Lanka", lat: 6.9148, lng: 79.8716 }),
  place({ id: "seed-place-colombo-barefoot", city: "colombo", name: "Barefoot Garden Café", type: "cafe", vibe: "leafy Galle Road courtyard where books, jazz and Colombo's progressive circles mingle", description: "Behind Barefoot's handloom shop sits a garden that has spent decades mixing lunch, wine, Sunday jazz, theatre, art launches and political conversation. It is a mainstream café rather than an LGBTQ+ venue, yet its creative programme and community reputation make it a low-pressure daytime meeting point with genuine local texture.", hours: "Mon-Sat 10:00-19:00; Sunday and Poya days 10:00-18:00. Event hours may differ.", link: "https://barefootceylon.com/pages/cafe", location: "704 Galle Road, Colombo 03, Sri Lanka", lat: 6.8888, lng: 79.8563 }),
  place({ id: "seed-place-colombo-jetwing-seven", city: "colombo", name: "Jetwing Colombo Seven", type: "hotel", vibe: "Cinnamon Gardens calm capped by an infinity pool and skyline bar", description: "A contemporary city hotel on the Ward Place side of Colombo 7, with an infinity pool and rooftop bar above the traffic. It gives couples a quieter residential base near museums and cafés, plus a staffed retreat from a scene where discretion still matters more than proximity to a gay district.", hours: "Hotel open daily; Sri Lankan standard hotel times are approximately check-in 14:00 and check-out 12:00. Confirm on the reservation.", link: "https://www.jetwinghotels.com/jetwingcolomboseven/", location: "57 Ward Place, Colombo 07, Sri Lanka", lat: 6.9140, lng: 79.8734 }),
  place({ id: "seed-place-colombo-cinnamon-grand", city: "colombo", name: "Cinnamon Grand Colombo", type: "hotel", vibe: "grand-scale Colombo 3 hospitality with enough dining to build a night indoors", description: "A 501-room institution on Galle Road with a deep restaurant bench, pool and spa beside Crescat and the seafront corridor. The scale creates anonymity and choice: useful for travellers who want full service, several meeting options and fewer reasons to explain a private evening plan outside the hotel.", hours: "Hotel open daily; flexible arrival products are offered. Confirm the booked check-in and checkout conditions directly.", link: "https://www.cinnamonhotels.com/cinnamon-grand-colombo", location: "77 Galle Road, Colombo 03, Sri Lanka", lat: 6.9187, lng: 79.8483 }),
  place({ id: "seed-place-colombo-shangrila", city: "colombo", name: "Shangri-La Colombo", type: "hotel", vibe: "oceanfront high-rise sanctuary connected to One Galle Face", description: "Ocean views, seven restaurants and bars, a spa and direct mall access make this the most contained luxury landing pad on Galle Face. It works when controlled transport, staffed public areas and a broad international crowd matter more than neighbourhood intimacy or a local boutique mood.", hours: "Hotel open daily; check-in 14:00 and check-out 12:00.", link: "https://www.shangri-la.com/colombo/shangrila/", location: "1 Galle Face, Colombo 02, Sri Lanka", lat: 6.9285, lng: 79.8444 }),
];

// Colombo Pride 2026 has ended; no verified 2027 programme is published yet.
export const colomboSeedEvents = [];
