export const CYPRUS_CITY_SLUGS = new Set(["cyprus"]);

export const cyprusSeedPlaces = [
  {
    id: "seed-place-cyprus-ithaki",
    city: "cyprus",
    name: "Ithaki",
    type: "bar",
    vibe: "camp pop nights with burgers on the side",
    description: "Nicosia queer favorite where sugary cocktails, loud pop, cheeky hosts, and burgers from next door turn a small bar into a Friday-night personality test. Come ready to sing along and leave your serious face at home.",
    hours: "Wed-Thu 19:00-02:00, Fri-Sat 19:00-03:00, Sun-Tue closed. Verify before travel.",
    link: "https://www.facebook.com/Ithaki33/",
    location: "Nikiforou Foka 33, Nicosia 1017, Cyprus",
    lat: 35.1742,
    lng: 33.37085,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-lube-bar",
    city: "cyprus",
    name: "Lube Bar",
    type: "bar",
    vibe: "neon karaoke and sweaty weekend dancing",
    description: "Larnaca's LGBTQ bar keeps things delightfully unsubtle with neon light, karaoke Fridays, DJ Saturdays, and a dance floor that understands the assignment. The name makes a promise; the weekend crowd supplies the sparkle.",
    hours: "Wed-Fri and Sun 20:00-02:00, Sat 20:00-03:30, Mon-Tue closed. Verify before travel.",
    link: "https://www.facebook.com/lubebar/",
    location: "Stavrou Poskoti 19, Larnaca 6058, Cyprus",
    lat: 34.9310058,
    lng: 33.6380261,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-diamonds-showbar",
    city: "cyprus",
    name: "Diamonds Showbar",
    type: "bar",
    vibe: "full-volume drag cabaret by the coast",
    description: "Protaras showbar serving cocktails, food, live music, and a nightly drag spectacle with enough lashes and costume changes to make sunset feel underdressed. It is proudly mixed, tourist-friendly, and gloriously theatrical.",
    hours: "2026 season: Mon-Sat from 18:00, showtime 21:30; also Sun June-Sep. Seasonal.",
    link: "https://diamondsshowbar.com/",
    location: "342 Leoforos Protara-Cavo Greco, Protaras 5296, Cyprus",
    lat: 35.0183858,
    lng: 34.0446722,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-different-bar",
    city: "cyprus",
    name: "Different Bar",
    type: "bar",
    vibe: "retro-pop daiquiri camp in Paphos",
    description: "A compact Paphos gay bar where Madonna, Gaga, Cyndi, and the Pet Shop Boys share custody of the playlist. Order the strawberry daiquiri, embrace the Bar Street holiday energy, and let chronology become someone else's problem.",
    hours: "Daily 19:00-03:00 according to the latest travel guide; verify on the official page before going.",
    link: "https://www.facebook.com/Differentbar/",
    location: "Agias Napas, Bar Street, Paphos 8041, Cyprus",
    lat: 34.7578768,
    lng: 32.4159066,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-downtown-live",
    city: "cyprus",
    name: "DownTown Live",
    type: "club",
    vibe: "live-music room with monthly drag sparkle",
    description: "Nicosia live-music venue that periodically swaps the usual stage energy for a ticketed drag night. It is not a permanent queer club, but when the queens arrive the room gets a welcome dose of jokes, glitter, and affectionate public humiliation.",
    hours: "Venue schedule varies; drag programming has run on selected Sundays 20:00-00:00. Check the official calendar.",
    link: "https://www.facebook.com/downtownlivenicosia/",
    location: "Emanouil Roidi 2, Agioi Omologites, Nicosia 1095, Cyprus",
    lat: 35.1650029,
    lng: 33.3498425,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-zester",
    city: "cyprus",
    name: "Zester Bar",
    type: "bar",
    vibe: "leafy mixed garden with a camp little wink",
    description: "Gay-friendly Limassol bar with cocktails, dance music, and a plant-filled beer garden built for warm-night flirting. Mostly mixed, pleasantly liberated, and ideal when you want queer signal without committing to a full glitter emergency.",
    hours: "Wed-Sun until around 23:00, Mon-Tue closed. Verify before travel.",
    link: "https://www.facebook.com/zester.bar/",
    location: "Eleftherias 108, Limassol, Cyprus",
    lat: 34.6740,
    lng: 33.0402,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-kermia-beach",
    city: "cyprus",
    name: "Kermia Gay Beach",
    type: "cruising_area",
    vibe: "rocky naturist hideaway near Ayia Napa",
    description: "Unofficial queer and naturist stretch near Limnara Beach, reached across rocky ground from the Kermia area. The water is cinematic, the access is not: bring proper shoes, daylight, water, and respect for everyone sharing the cove.",
    hours: "Public coast; daylight visits only. No managed facilities at the queer section.",
    link: "https://nomadicboys.com/gay-cyprus/",
    location: "Kermia/Limnara coastal access, Ayia Napa 5330, Cyprus",
    lat: 34.973,
    lng: 34.033167,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-pissouri-gay-beach",
    city: "cyprus",
    name: "Pissouri Gay Beach",
    type: "cruising_area",
    vibe: "secluded naturist cove beyond the rocks",
    description: "The unofficial gay end of Pissouri Bay sits beyond the general naturist stretch and rewards the extra walk with privacy and big Mediterranean drama. Wear shoes for the rocks and pack like your beach bag has common sense.",
    hours: "Public beach; daylight visits recommended. Access and sea conditions vary.",
    link: "https://nomadicboys.com/gay-cyprus/",
    location: "East end of Pissouri Bay, Pissouri 4607, Cyprus",
    lat: 34.648263,
    lng: 32.73526,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-governors-gay-beach",
    city: "cyprus",
    name: "Governor's Gay Beach",
    type: "cruising_area",
    vibe: "white-rock coves and low-key queer sun",
    description: "Unofficial queer cove in the white-rock Governor's Beach area between Limassol and Larnaca. The scenery is pure editorial fantasy; the cliff and rock access are a practical reminder to wear shoes and arrive before the light starts fading.",
    hours: "Public coast; daylight visits only. Facilities are near the main beach, not the secluded section.",
    link: "https://nomadicboys.com/gay-cyprus/",
    location: "White Rocks, Governor's Beach, Pentakomo 4528, Cyprus",
    lat: 34.7182236,
    lng: 33.2755541,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-annabelle",
    city: "cyprus",
    name: "Annabelle",
    type: "hotel",
    vibe: "five-star palms, spa calm, and rooftop romance",
    description: "Gay-welcoming Paphos grande dame with layered pools, sea-facing rooms, a serious wellness program, and the Ouranos rooftop bar for couples who believe nightcaps deserve a horizon. Polished, romantic, and very good at making doing nothing feel important.",
    hours: "Hotel operates daily; reception and guest services follow the booking confirmation.",
    link: "https://www.annabelle.com.cy/",
    location: "10 Poseidonos Avenue, Paphos 8125, Cyprus",
    lat: 34.7552807,
    lng: 32.4174452,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-leonardo-cypria-maris",
    city: "cyprus",
    name: "Leonardo Plaza Cypria Maris Beach Hotel & Spa",
    type: "hotel",
    vibe: "adults-only honeymoon energy without the side-eye",
    description: "Adults-only Paphos beachfront resort with pools, spa treatments, restaurants, and an easy welcome for same-sex couples. It is the sort of place where a double-bed request is boring in the best possible way and the fish spa becomes the strangest member of your group chat.",
    hours: "Hotel operates daily; reception is available 24/7.",
    link: "https://www.leonardo-hotels-cyprus.com/hotels-in-paphos/leonardo-plaza-cypria-maris-beach",
    location: "10 Theas Afroditis Avenue, Geroskipou 8204, Paphos, Cyprus",
    lat: 34.7415984,
    lng: 32.4316015,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-napa-suites",
    city: "cyprus",
    name: "Hotel Napa Suites",
    type: "hotel",
    vibe: "adults-only rooftop glamour above Ayia Napa",
    description: "Gay-friendly adults-only stay with a rooftop infinity pool, Asian dining, and the kind of breakfast view that makes sunglasses feel ceremonial. Close enough to Ayia Napa's chaos for fun, elevated enough to pretend you are above it.",
    hours: "Hotel operates daily in season; reception and guest services follow the booking confirmation.",
    link: "https://napasuites.com/",
    location: "29-31 Demokratias Street, Ayia Napa 5330, Cyprus",
    lat: 34.9938483,
    lng: 34.0005544,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-cyprus-melissi-beach",
    city: "cyprus",
    name: "Melissi Beach Hotel & Spa",
    type: "hotel",
    vibe: "beachfront wellness with Ayia Napa in reserve",
    description: "Gay-friendly four-star beach hotel with pools, restaurants, sports facilities, and Apis Spa's sauna-and-steam recovery circuit. It gives you blue-flag beach calm by day and keeps Ayia Napa's louder decisions within walking distance.",
    hours: "Hotel operates daily in season; reception and guest services follow the booking confirmation.",
    link: "https://melissi.com/",
    location: "30 Kryou Nerou, Ayia Napa 5330, Cyprus",
    lat: 34.9855554,
    lng: 34.0095031,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
];

export const cyprusSeedEvents = [
  {
    id: "seed-event-cyprus-pride-2026",
    city: "cyprus",
    name: "Cyprus Pride 2026",
    description: "Accept-LGBTI Cyprus's annual Nicosia Pride program, combining a public march, rights visibility, community gathering, and the kind of stage energy that makes a divided capital briefly feel beautifully united.",
    link: "https://accept.cy/",
    date: "",
    lat: 35.1694388,
    lng: 33.3618491,
    seeded: true,
  },
  {
    id: "seed-event-cyprus-queer-cyprus-pride-2026",
    city: "cyprus",
    name: "Queer Cyprus Pride 2026",
    description: "North Nicosia Pride march and culture program organized by Queer Cyprus Association, pairing public visibility with performances, community solidarity, and a proudly border-defying queer pulse.",
    link: "https://www.queercyprus.org/",
    date: "2026-05-17",
    lat: 35.1856,
    lng: 33.3645,
    seeded: true,
  },
  {
    id: "seed-event-cyprus-diamonds-drag-season-2026",
    city: "cyprus",
    name: "Diamonds Drag Show Season 2026",
    description: "Season-long Protaras drag cabaret with live vocals, comedy, costumes, cocktails, and a 21:30 showtime that turns an ordinary resort evening into a full production number.",
    link: "https://diamondsshowbar.com/",
    date: "",
    lat: 35.0183858,
    lng: 34.0446722,
    seeded: true,
  },
  {
    id: "seed-event-cyprus-lube-summer-boat-party",
    city: "cyprus",
    name: "Lube Bar Summer Boat Party",
    description: "Occasional summer queer boat party promoted through Lube Bar in Larnaca. Dates move and details travel through official social channels, so consider this your reminder to check before packing the tiny swimwear.",
    link: "https://www.facebook.com/lubebar/",
    date: "",
    lat: 34.9167,
    lng: 33.6369,
    seeded: true,
  },
];
