export const JOHANNESBURG_CITY_SLUGS = new Set(["johannesburg"]);

const place = (entry) => ({
  avgRating: null,
  reviewCount: 0,
  seeded: true,
  ...entry,
});

export const johannesburgSeedPlaces = [
  place({
    id: "seed-place-johannesburg-ratz",
    city: "johannesburg",
    name: "Ratz Bar",
    type: "bar",
    vibe: "compact Melville gay bar with pop, cocktails and pre-drink energy",
    description: "An established gay bar on Melville's 7th Street with pop-heavy music, themed cocktails and an easy pre-club atmosphere.",
    hours: "Daily 16:00-02:00.",
    link: "https://www.ratzbar.co.za/",
    location: "9 7th Street, Melville, Johannesburg, Gauteng 2092, South Africa",
    lat: -26.194193,
    lng: 28.015783,
  }),
  place({
    id: "seed-place-johannesburg-liquid-blue",
    city: "johannesburg",
    name: "Liquid Blue",
    type: "bar",
    vibe: "POC-popular Melville bar with late crowds and student Thursdays",
    description: "An LGBTQ-popular mixed bar with especially strong support from Johannesburg's queer POC community. Thursdays draw students and weekends build queues.",
    hours: "Daily until approximately 03:00; arrive before 23:00 on busy weekends.",
    link: "https://www.facebook.com/profile.php?id=100069415140884",
    location: "8 7th Street, Melville, Johannesburg, Gauteng 2092, South Africa",
    lat: -26.19443,
    lng: 28.01562,
  }),
  place({
    id: "seed-place-johannesburg-kitcheners",
    city: "johannesburg",
    name: "Kitchener's Carvery Bar",
    type: "bar",
    vibe: "historic Braamfontein bar with queer parties and student nights",
    description: "One of Johannesburg's oldest bars and an important mixed queer-friendly room, known for recurring parties, women-focused nights and student Wednesdays.",
    hours: "Mon-Tue and Thu-Sat 11:00-04:00; Wed 11:00-02:00; Sun 11:00-00:00.",
    link: "https://kitcheners.co.za/",
    location: "Corner Juta and De Beer Streets, Braamfontein, Johannesburg, Gauteng 2001, South Africa",
    lat: -26.193203,
    lng: 28.034691,
  }),
  place({
    id: "seed-place-johannesburg-babylon",
    city: "johannesburg",
    name: "Babylon The Joburg Bar",
    type: "club",
    vibe: "large Illovo gay club with commercial pop, drag and dancers",
    description: "Johannesburg's leading large LGBTQ+ nightclub combines commercial pop, drag performers, dancers, VIP booths and an inclusive crowd.",
    hours: "Fri-Sat 20:00-06:00; closed Sun-Thu except announced events.",
    link: "https://babylonbar.co.za/",
    location: "198 Oxford Road, Illovo, Sandton, Johannesburg, Gauteng 2196, South Africa",
    lat: -26.130588,
    lng: 28.049882,
  }),
  place({
    id: "seed-place-johannesburg-tennis-club",
    city: "johannesburg",
    name: "The Tennis Club",
    type: "club",
    vibe: "event-led New Doornfontein club with a queer creative crowd",
    description: "A mixed event venue in the Ellis Park complex that regularly attracts a visible queer crowd for drag balls and special party nights.",
    hours: "Usually Fri 20:00-03:00; special events may use different times.",
    link: "https://www.facebook.com/thetennisclubjhb/",
    location: "Corner Bertram and Miller Streets, New Doornfontein, Johannesburg, Gauteng 2094, South Africa",
    lat: -26.198107,
    lng: 28.063083,
  }),
  place({
    id: "seed-place-johannesburg-rec-room",
    city: "johannesburg",
    name: "The Rec Room",
    type: "sauna",
    vibe: "men-only Randburg sauna with steam, Jacuzzi, cabins and maze areas",
    description: "Johannesburg's dedicated gay sauna offers steam, Jacuzzi, showers, a bar, video lounge, cabins and maze areas for men.",
    hours: "Sun-Thu 12:00-00:00; Fri-Sat 12:00-07:00. Verify current hours.",
    link: "https://nomadicboys.com/gay-johannesburg/",
    location: "Shop 1, Phoenix Centre, Malibongwe Drive and Tungsten Drive, Ferndale, Randburg, Gauteng 2194, South Africa",
    lat: -26.098706,
    lng: 27.986757,
  }),
  place({
    id: "seed-place-johannesburg-factory",
    city: "johannesburg",
    name: "The Factory",
    type: "cruise_club",
    vibe: "men-only Doornfontein cruise club with themed fetish nights",
    description: "A men-only indoor cruise venue with themed masked, boot and incognito nights and a direct adults-only focus.",
    hours: "Mon-Wed 12:00-03:00; Thu-Sun 12:00-06:00. Check current events.",
    link: "https://x.com/The_Factory_Bar",
    location: "6 6th Street, New Doornfontein, Johannesburg, Gauteng, South Africa",
    lat: -26.193175,
    lng: 28.061311,
  }),
  place({
    id: "seed-place-johannesburg-marble",
    city: "johannesburg",
    name: "Marble Restaurant",
    type: "cafe",
    vibe: "Rosebank open-fire dining with skyline cocktails",
    description: "A polished queer-friendly Rosebank restaurant built around open-fire cooking, a dramatic bar and skyline views.",
    hours: "Open for lunch and dinner daily; check current sitting times.",
    link: "https://marble.restaurant/",
    location: "Trumpet on Keyes, Corner Keyes and Jellicoe Avenue, Rosebank, Johannesburg, Gauteng, South Africa",
    lat: -26.143337,
    lng: 28.036461,
  }),
  place({
    id: "seed-place-johannesburg-pablo-dos-manos",
    city: "johannesburg",
    name: "Pablo Dos Manos",
    type: "cafe",
    vibe: "Melville ridge restaurant with breakfast, pizza and views",
    description: "The restaurant at Pablo House combines breakfast, coffee, pizza, cocktails and wide northern views close to Melville's gay bars.",
    hours: "Daily hotel restaurant service; verify current sittings.",
    link: "https://pablohouse.co.za/",
    location: "3 4th Avenue, Melville, Johannesburg, Gauteng 2109, South Africa",
    lat: -26.175702,
    lng: 28.004924,
  }),
  place({
    id: "seed-place-johannesburg-grillhouse",
    city: "johannesburg",
    name: "The Grillhouse Rosebank",
    type: "cafe",
    vibe: "classic Rosebank steakhouse with cocktails and live music",
    description: "A long-running queer-friendly Rosebank steakhouse with dependable service and Katzy's live-music bar attached.",
    hours: "Daily 12:00-21:00; Katzy's Live opens Thu-Sat from 19:00.",
    link: "https://thegrillhouse.co.za/",
    location: "The Firs Centre, Corner Oxford and Biermann Avenue, Rosebank, Johannesburg, Gauteng, South Africa",
    lat: -26.143274,
    lng: 28.042307,
  }),
  place({
    id: "seed-place-johannesburg-yeoville-dinner-club",
    city: "johannesburg",
    name: "Yeoville Dinner Club",
    type: "cafe",
    vibe: "reservation-only pan-African communal table",
    description: "Chef Sanza Sandile's communal table combines Pan-African food, migration stories and Johannesburg neighborhood culture.",
    hours: "Reservation-only dinner experiences; times are confirmed during booking.",
    link: "https://www.yeovilledinnerclub.com/",
    location: "24 Rockey Street, Yeoville, Johannesburg, Gauteng 2198, South Africa",
    lat: -26.181472,
    lng: 28.067635,
  }),
  place({
    id: "seed-place-johannesburg-home-suite",
    city: "johannesburg",
    name: "Home Suite Hotels Rosebank",
    type: "hotel",
    vibe: "warm boutique Rosebank base with rooftop pool",
    description: "A welcoming boutique hotel with a rooftop pool, breakfast and 24-hour security, well placed for Illovo and Rosebank.",
    hours: "Hotel open daily; reception and security operate 24 hours.",
    link: "https://homesuitehotels.com/rosebank/",
    location: "50 Bristol Road, Corner Oxford Road, Rosebank, Johannesburg, Gauteng, South Africa",
    lat: -26.153567,
    lng: 28.04479,
  }),
  place({
    id: "seed-place-johannesburg-pablo-house",
    city: "johannesburg",
    name: "Pablo House",
    type: "hotel",
    vibe: "bohemian Melville boutique hotel near the gay bars",
    description: "A small art-led boutique hotel overlooking the Melville Koppies with a restaurant, pool and fast access to Ratz and Liquid Blue.",
    hours: "Hotel open daily; confirm current check-in arrangements.",
    link: "https://pablohouse.co.za/",
    location: "3 4th Avenue, Melville, Johannesburg, Gauteng 2109, South Africa",
    lat: -26.175702,
    lng: 28.004924,
  }),
  place({
    id: "seed-place-johannesburg-radisson-red",
    city: "johannesburg",
    name: "Radisson RED Johannesburg Rosebank",
    type: "hotel",
    vibe: "modern Oxford Parks hotel with rooftop social energy",
    description: "A contemporary hotel with bright design, rooftop pool, gym, restaurant and a useful position between Rosebank, Illovo and Sandton.",
    hours: "Hotel open daily; reception operates 24 hours.",
    link: "https://www.radissonhotels.com/en-us/hotels/radisson-red-johannesburg-rosebank",
    location: "4 Parks Boulevard, Oxford Parks, Dunkeld, Johannesburg, Gauteng 2196, South Africa",
    lat: -26.141686,
    lng: 28.04305,
  }),
];

export const johannesburgSeedEvents = [
  {
    id: "seed-event-johannesburg-pride-kickoff-2026",
    city: "johannesburg",
    name: "Pride of Africa Month Kick-Off Pool Party 2026",
    description: "Pride of Africa opens its October programme with a social pool-party launch. The final venue is announced by the organizer.",
    link: "https://prideofafrica.org/",
    date: "2026-10-03",
    lat: -26.14465,
    lng: 28.041,
    seeded: true,
  },
  {
    id: "seed-event-johannesburg-pride-drag-brunch-2026",
    city: "johannesburg",
    name: "Pride of Africa Drag Brunch 2026",
    description: "An official Pride of Africa drag brunch bringing food, performance and daytime queer celebration into the October programme.",
    link: "https://prideofafrica.org/",
    date: "2026-10-10",
    lat: -26.14465,
    lng: 28.041,
    seeded: true,
  },
  {
    id: "seed-event-johannesburg-scrt-venue-2026",
    city: "johannesburg",
    name: "SCRT Venue ft Jagermeister 2026",
    description: "Pride of Africa's secret-venue event combines art, music, fashion and queer self-expression at an address released to attendees.",
    link: "https://prideofafrica.org/",
    date: "2026-10-16",
    lat: -26.2041,
    lng: 28.0473,
    seeded: true,
  },
  {
    id: "seed-event-johannesburg-queer-met-gala-2026",
    city: "johannesburg",
    name: "Pride of Africa Queer Met Gala 2026",
    description: "The seventh Queer Met Gala celebrates African queer excellence through high fashion, bold identity and unapologetic glamour.",
    link: "https://prideofafrica.org/",
    date: "2026-10-24",
    lat: -26.14465,
    lng: 28.041,
    seeded: true,
  },
  {
    id: "seed-event-johannesburg-pride-2026",
    city: "johannesburg",
    name: "Johannesburg Pride 2026",
    description: "One of Africa's oldest and largest Pride celebrations marks 37 years with a major Sandton gathering on 31 October.",
    link: "https://prideofafrica.org/",
    date: "2026-10-31",
    lat: -26.110804,
    lng: 28.057193,
    seeded: true,
  },
];
