export const KATHMANDU_CITY_SLUGS = new Set(["kathmandu"]);

const place = (entry) => ({ avgRating: null, reviewCount: 0, seeded: true, ...entry });

export const kathmanduSeedPlaces = [
  place({ id: "seed-place-kathmandu-pink-tiffany", city: "kathmandu", name: "PINK Tiffany", type: "bar", vibe: "trans-founded queer café that turns into Thamel's intimate rainbow living room", description: "Nepal's first openly LGBTQI+-friendly restaurant and bar is both a landmark and a real night out. Founded by trans activist Meghna Lama, PINK Tiffany moves from food and conversation into music, live performance and close-quarters dancing without losing the feeling that half the room already knows each other.", hours: "Restaurant and evening bar hours vary; current listings show regular operation, with the liveliest atmosphere after 21:00. Confirm the same-day schedule.", link: "https://www.facebook.com/pinktiffanynepal/", location: "P886+F24, Chaksibari Marg, Thamel, Kathmandu 44600, Nepal", lat: 27.7162, lng: 85.3118 }),
  place({ id: "seed-place-kathmandu-fire-club", city: "kathmandu", name: "Fire Club", type: "club", vibe: "big Thamel dance floor whose Friday party pulls the city's loudest queer crowd", description: "A mainstream Kathmandu club with one night that changes the room completely: Friday's long-running gay party. Come after PINK Tiffany for the scale-up—commercial pop, a packed floor and the rare Kathmandu moment when the local queer scene occupies a full-size nightclub rather than a discreet corner.", hours: "Evening to late night; Friday is the recurring queer-focused night. Verify the current programme before arrival.", link: "https://fireclub.com.np/", location: "Chaksibari Marg, Thamel, Kathmandu 44600, Nepal", lat: 27.7160, lng: 85.3116 }),
  place({ id: "seed-place-kathmandu-aloft", city: "kathmandu", name: "Aloft Kathmandu Thamel", type: "hotel", vibe: "rooftop-pool polish planted directly inside Thamel's beautiful chaos", description: "A modern five-star base above Chhaya Devi Complex, with a rooftop pool, 24-hour fitness room and W XYZ social bar. The location earns its place: Kathmandu's two most dependable queer nightlife stops sit within the same Thamel grid, so the last journey home can be short and staffed.", hours: "Hotel open daily; check-in 15:00 and check-out 12:00; minimum check-in age 18.", link: "https://www.marriott.com/en-us/hotels/ktmal-aloft-kathmandu-thamel/overview/", location: "Chhaya Devi Complex, Amrit Marg, Thamel, Kathmandu 44600, Nepal", lat: 27.7167, lng: 85.3128 }),
  place({ id: "seed-place-kathmandu-marriott", city: "kathmandu", name: "Kathmandu Marriott Hotel", type: "hotel", vibe: "full-service Naxal retreat with a pool, spa and breathing room beyond Thamel", description: "Six restaurants, a full spa and an outdoor pool make this the decompression option after Kathmandu's dust, traffic and late nights. Naxal places it outside the tight Thamel circuit but closer to a polished international rhythm, useful for couples who want a staffed retreat and do not mind booking a ride to the bars.", hours: "Hotel open daily; check-in 15:00 and check-out 12:00; minimum check-in age 18.", link: "https://www.marriott.com/en-us/hotels/ktmmc-kathmandu-marriott-hotel/overview/", location: "Manakamana Marg, Naxal, Kathmandu 44600, Nepal", lat: 27.7145, lng: 85.3256 }),
  place({ id: "seed-place-kathmandu-hyatt-centric", city: "kathmandu", name: "Hyatt Centric Soalteemode Kathmandu", type: "hotel", vibe: "Newari-inspired resort calm with mountain views on the heritage-city side", description: "A 153-room lifestyle hotel that gives Kathmandu's brick, carved wood and courtyard language a contemporary frame. Its Tahachal setting works for Durbar Square days and poolside recovery; nightlife needs a planned ride, but the trade is space, mountain views and a quieter landing than central Thamel.", hours: "Hotel open daily; check-in and checkout times should be confirmed on the current reservation.", link: "https://www.hyatt.com/hyatt-centric/en-US/ktmzk-hyatt-centric-soalteemode-kathmandu/", location: "PO Box 8801, Tahachal, Kathmandu 44600, Nepal", lat: 27.7009, lng: 85.2927 }),
];

// The 2026 Nepal Pride Parade has ended; 2027 details are not yet published.
export const kathmanduSeedEvents = [];
