export const KOH_SAMUI_CITY_SLUGS = new Set(["koh_samui"]);

export const kohSamuiSeedPlaces = [
  {
    id: "seed-place-koh-samui-pride-bar",
    city: "koh_samui",
    name: "Pride Bar Samui",
    type: "bar",
    vibe: "social cocktails, pop singalongs and regular drag sparkle",
    description: "Samui's queer living room serves cocktails, quick bites, karaoke, retro music, and regular cabaret appearances. Come as a visitor, leave with three new friends and a completely revised plan for Wednesday night.",
    hours: "Daily approximately 18:00-02:00. Wednesday karaoke from 21:00; Thursday Latin Vibes; Saturday Divas Cabaret mini show at 23:40; Sunday retro music.",
    link: "https://www.pridebarsamui.com/",
    location: "166/15 Moo 2, Chaweng Beach Road, Bophut, Koh Samui, Surat Thani 84320, Thailand",
    lat: 9.5327506,
    lng: 100.0648189,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-koh-samui-whisper-bar",
    city: "koh_samui",
    name: "Whisper Gay Bar & Lounge",
    type: "bar",
    vibe: "neon cocktails, pop-diva dancing and playful cruising",
    description: "A stylish and unapologetically queer lounge inside Alpha Gay Resort, built for cocktails, dating, dancing, and a little well-lit drama. Monday brings Cruising Night, Friday belongs to the pop divas, and subtlety has wisely taken the evening off.",
    hours: "Mon-Sat 18:00-late; Sunday closed. Cruising Night on Monday and pop-diva dance parties on Friday.",
    link: "https://www.alphagayresort.com/whisper-bar",
    location: "Inside Alpha Gay Resort, 9/34 Moo 2, Bophut, Koh Samui, Surat Thani 84320, Thailand",
    lat: 9.53478,
    lng: 100.05775,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-koh-samui-alpha-gay-resort",
    city: "koh_samui",
    name: "Alpha Gay Resort & Spa",
    type: "hotel",
    vibe: "men-only tropical privacy with clothing-optional pool calm",
    description: "An adult gay men's tropical retreat with private rooms, a dorm, pools, bar, steam facilities, and a clothing-optional social scene. Swimwear is available for the cautious, optional for the confident, and rarely the most interesting part of the conversation.",
    hours: "Hotel operates daily. Pool is available 24 hours for registered guests; resort bar and social facilities usually close around 21:00.",
    link: "https://www.alphagayresort.com/",
    location: "9/34 Moo 2, Bophut, Koh Samui, Surat Thani 84320, Thailand",
    lat: 9.53478,
    lng: 100.05775,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-koh-samui-arkbar",
    city: "koh_samui",
    name: "ARKbar Beach Club & Resort",
    type: "club",
    vibe: "gay-popular beachfront pool parties and nightly fire-show spectacle",
    description: "A mixed but gay-popular Chaweng beach club with oceanfront pools, live DJs, nightly fire shows, and enough party momentum to turn sunset into a scheduling suggestion. The crowd is broad, the music is loud, and the beach has excellent lighting.",
    hours: "Daily 10:00-02:00. Pool party 14:00-19:00; beach party 20:00-02:00; fire show 20:00-00:00.",
    link: "https://www.ark-bar.com/",
    location: "159/89 Moo 2, Chaweng Beach, Bophut, Koh Samui, Surat Thani 84320, Thailand",
    lat: 9.5322,
    lng: 100.0651,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
];

export const kohSamuiSeedEvents = [];
