export const LJUBLJANA_CITY_SLUGS = new Set(["ljubljana"]);

export const ljubljanaSeedPlaces = [
  {
    id: "seed-place-ljubljana-klub-tiffany",
    city: "ljubljana",
    name: "Klub Tiffany",
    type: "club",
    vibe: "Metelkova drag, pop and activist chosen-family energy",
    description: "Ljubljana's queer living room swaps the soft sofa for a dance floor, drag, and enough pop to wake the whole of Metelkova. The club also hosts performances, discussions, and community programming through Cultural Centre Q.",
    hours: "Event-led, usually selected Thu-Sat 23:00-05:00; check the official programme.",
    link: "https://www.kulturnicenterq.org/klub-tiffany/",
    location: "Masarykova cesta 24, 1000 Ljubljana, Slovenia",
    lat: 46.0573193,
    lng: 14.5172985,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ljubljana-klub-monokel",
    city: "ljubljana",
    name: "Klub Monokel",
    type: "club",
    vibe: "lesbian and queer-feminist underground club",
    description: "Lesbian and queer-feminist club culture with electronic beats, art, and a very low tolerance for dull heteronormativity. Its event-led programme makes checking the current calendar part of the ritual.",
    hours: "Event-led, mainly selected Fri-Sat around 23:00-05:00; verify on the official social page.",
    link: "https://www.instagram.com/klubmonokel/",
    location: "Masarykova cesta 24, 1000 Ljubljana, Slovenia",
    lat: 46.0573193,
    lng: 14.5172985,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ljubljana-klub-k4",
    city: "ljubljana",
    name: "Klub K4 / K4 Roza",
    type: "club",
    vibe: "underground electronic club with a recurring queer takeover",
    description: "K4 is a mixed underground electronic club, but recurring K4 Roza nights bring a distinctly queer charge to the basement. When Roza takes over, the bass drops, the wardrobe opens, and the dance floor becomes considerably more fluent.",
    hours: "Event-led, commonly around 23:00-05:00; check the official programme.",
    link: "https://www.klub-k4.si/",
    location: "Kersnikova ulica 4, 1000 Ljubljana, Slovenia",
    lat: 46.0556079,
    lng: 14.5039882,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ljubljana-pritlicje",
    city: "ljubljana",
    name: "Pritličje",
    type: "cafe",
    vibe: "queer-friendly coffee, comics, art and civic culture",
    description: "Coffee, cocktails, comics, exhibitions, and political conversation share the room as if they have always belonged to the same queer group chat. This central cultural cafe regularly participates in LGBTQ+ and Pride programming.",
    hours: "Open daily; cafe, bar, and event hours vary. Check the official programme before visiting.",
    link: "https://www.pritlicje.si/",
    location: "Mestni trg 2, 1000 Ljubljana, Slovenia",
    lat: 46.0497195,
    lng: 14.5068235,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ljubljana-district35",
    city: "ljubljana",
    name: "District35",
    type: "sauna",
    vibe: "gay sauna, cruising and relaxed themed sessions",
    description: "Men-focused gay sauna and cruise club with lockers, showers, sauna facilities, dark areas, a bar, terrace, and recurring themed sessions. Towels, steam, and social chemistry provide considerably more possibilities than the average changing room.",
    hours: "Mon 18:00-00:00, Tue-Thu 17:00-00:00, Fri 17:00-01:00, Sat 15:00-01:00, Sun 15:00-00:00.",
    link: "https://www.district35.si/",
    location: "Stegne 35, 1000 Ljubljana, Slovenia",
    lat: 46.0877287,
    lng: 14.4801775,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
];

export const ljubljanaSeedEvents = [
  {
    id: "seed-event-ljubljana-pride-parade-2026",
    city: "ljubljana",
    name: "Ljubljana Pride Parade 2026",
    description: "Ljubljana's rainbow heart takes to the city centre with community, protest, music, and demonstratively excellent outfits. Confirm the final assembly point and time through the official Pride channels.",
    link: "https://ljubljanapride.org/",
    date: "2026-06-13",
    lat: 46.0513764,
    lng: 14.5059895,
    seeded: true,
  },
  {
    id: "seed-event-ljubljana-pridena-afterparty-2026",
    city: "ljubljana",
    name: "PRIDEn_a - Ljubljana Pride Parade Afterparty",
    description: "Official Pride afterparty across Klub Tiffany and Klub Monokel from 23:00 to 05:00. The parade ends, but Ljubljana's queer battery politely refuses to do the same.",
    link: "https://www.kulturnicenterq.org/pridena-ljubljana-pride-parade-afterparty-13-6-2026-klub-tiffany-in-monokel/",
    date: "2026-06-13",
    lat: 46.0573193,
    lng: 14.5172985,
    seeded: true,
  },
  {
    id: "seed-event-ljubljana-district35-all-gender-2026-06-15",
    city: "ljubljana",
    name: "District35 All Gender Monday - 15 June 2026",
    description: "Inclusive all-gender sauna session from 18:00 to midnight. The doors open to every gender while clothing remains regarded as highly optional.",
    link: "https://www.district35.si/",
    date: "2026-06-15",
    lat: 46.0877287,
    lng: 14.4801775,
    seeded: true,
  },
  {
    id: "seed-event-ljubljana-district35-naked-friday-2026-06-19",
    city: "ljubljana",
    name: "District35 Naked Friday - 19 June 2026",
    description: "Friday sauna theme from 17:00 to 01:00 with a refreshingly unambiguous concept: less fabric, more steam, and no anxiety about the dress code.",
    link: "https://www.district35.si/",
    date: "2026-06-19",
    lat: 46.0877287,
    lng: 14.4801775,
    seeded: true,
  },
];
