export const MARSEILLE_CITY_SLUGS = new Set(["marseille"]);

export const marseilleSeedPlaces = [
  {
    id: "seed-place-marseille-le-pulse",
    city: "marseille",
    name: "Le Pulse",
    type: "bar",
    vibe: "Cours Julien terrace drinks and friendly queer pop energy",
    description: "Cours Julien's rainbow living room, where terrace drinks have a habit of becoming a full evening. Expect cocktails, DJs, a social local crowd, and an easy first stop for reading Marseille's queer pulse.",
    hours: "Wed-Sat 17:00-02:00; check the official Instagram for programme changes.",
    link: "https://www.instagram.com/lepulsebar_/",
    location: "94 Cours Julien, 13006 Marseille, France",
    lat: 43.2930821,
    lng: 5.3831577,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-marseille-le-poli",
    city: "marseille",
    name: "Le Poli (formerly Polikarpov)",
    type: "bar",
    vibe: "harbour-side cocktails, disco confidence and mixed DJ nights",
    description: "Harbour-side cocktails, disco confidence, and enough Mediterranean flirting to delay dinner indefinitely. The former Polikarpov now trades as Le Poli, with an open-to-all crowd and electronic weekend energy.",
    hours: "Open daily, generally late afternoon to 02:00; verify the same-day schedule on Instagram.",
    link: "https://www.instagram.com/lepolibar_/",
    location: "24 Cours Honore d'Estienne d'Orves, 13001 Marseille, France",
    lat: 43.2930308,
    lng: 5.374033,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-marseille-boum",
    city: "marseille",
    name: "BOUM",
    type: "club",
    vibe: "inclusive drag, DJs and chosen-family dance-floor chaos",
    description: "A proudly inclusive queer playground serving drag, DJs, cocktails, and chosen-family chaos. Programme-led nights can move from early happy hour to a considerably louder dance floor.",
    hours: "Programme nights from 18:00; club programming often starts around 23:00. Check Instagram.",
    link: "https://www.instagram.com/boum_marseille/",
    location: "21 Rue Andre Poggioli, 13006 Marseille, France",
    lat: 43.2934672,
    lng: 5.3852497,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-marseille-lannexe",
    city: "marseille",
    name: "L'Annexe Bar made in Marseille",
    type: "bar",
    vibe: "gay terrace gossip, pop and late men-focused club energy",
    description: "A compact gay bar that starts with terrace gossip and ends with shirts mysteriously unbuttoned. It is men-focused, sociable, and louder once the programmed club hours begin.",
    hours: "Programme nights from 19:00; clubbing often runs 22:00-04:00. Check the weekly programme.",
    link: "https://www.instagram.com/annex_marseille/",
    location: "7 Rue Saint-Bazile, 13001 Marseille, France",
    lat: 43.2993834,
    lng: 5.3846734,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-marseille-les-thermes",
    city: "marseille",
    name: "Les Thermes",
    type: "sauna",
    vibe: "classic men-only steam, themed sessions and social cruising",
    description: "A classic men's sauna where steam, themed sessions, and Marseille confidence share the same towel. Facilities include a pool, hammam, bar, cabins, and social cruising areas.",
    hours: "Open daily from around 12:00; verify current closing time before visiting.",
    link: "https://qlist.app/venues/Marseille/Les-Thermes-No-1-Gay-Sauna-in-Marseille/UzJDOWg3NU1zeHM3TDZFLytXbi9FQQ",
    location: "22 Rue Mazagran, 13001 Marseille, France",
    lat: 43.2972957,
    lng: 5.3831556,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-marseille-cargo-sauna",
    city: "marseille",
    name: "Cargo Sauna",
    type: "sauna",
    vibe: "modern men-only spa facilities with a cruising undercurrent",
    description: "A modern men's sauna mixing pool, jacuzzi, hammam, cabins, and spa relaxation with a distinctly less innocent lower deck. Weekend hours run later for visitors who treat recovery as nightlife.",
    hours: "Mon-Thu and Sun 14:00-21:00; Fri-Sat 14:00-02:00.",
    link: "https://qlist.app/venues/Marseille/Cargo-Sauna-Marseille/TUhZWjYzUEcvbS9yN25ZUGpjcm0rUQ",
    location: "7 Rue Jean-Pierre-Moustier, 13001 Marseille, France",
    lat: 43.2940692,
    lng: 5.3800257,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-marseille-trash-bar",
    city: "marseille",
    name: "The Trash Bar",
    type: "cruising_area",
    vibe: "men-only leather, fetish and late-night cruising",
    description: "Marseille's leather-and-fetish basement for men who packed fewer inhibitions than outfits. DJs, cabins, showers, dark spaces, and themed nights make the concept refreshingly unambiguous.",
    hours: "Mon and Wed 20:30-02:00; Fri 21:30-02:00; Sat 21:30-03:00; Sun 15:00-00:00; Tue and Thu closed.",
    link: "https://qlist.app/venues/Marseille/The-Trash-Bar/UW50YzMwUjlyRTRQVVRmYktsM1RrQQ",
    location: "28 Rue du Berceau, 13005 Marseille, France",
    lat: 43.2877646,
    lng: 5.3953417,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-marseille-sauna-salvator",
    city: "marseille",
    name: "Sauna Club Salvator",
    type: "sauna",
    vibe: "three floors of old-school men-only sauna and cruising",
    description: "Three floors of steam, cruising, and unapologetically old-school gay sauna energy. It is a central daytime-to-evening option for men who prefer their Marseille sightseeing with considerably fewer layers.",
    hours: "Open daily around 12:00-20:00; verify current hours before visiting.",
    link: "https://qlist.app/venues/Marseille/Sauna-Club-Salvator/akh6bndJbW5LbFdsWTA0L2hYTU5OZw",
    location: "20 Boulevard Louis Salvator, 13006 Marseille, France",
    lat: 43.290997,
    lng: 5.3821944,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
];

export const marseilleSeedEvents = [
  {
    id: "seed-event-marseille-auto-hypnose-2026",
    city: "marseille",
    name: "Atelier d'auto-hypnose - 25 June 2026",
    description: "A free LGBTQIA+ community self-hypnosis workshop from 18:30 to 20:00. This session explores meeting the different parts of yourself, with less pressure than a group chat and considerably better breathing.",
    link: "https://centrelgbtqiamarseille.org/agenda/atelier-dauto-hypnose-6/",
    date: "2026-06-25",
    lat: 43.298013,
    lng: 5.3717676,
    seeded: true,
  },
  {
    id: "seed-event-marseille-etoiles-drag-2026",
    city: "marseille",
    name: "Les Etoiles du Drag 2026",
    description: "Two days of drag competition, showcases, meet-and-greets, and cabaret spectacle. Marseille puts the stars on stage and politely asks subtlety to wait outside.",
    link: "https://billetterie.cabaretletoilebleue.fr/",
    date: "2026-06-26",
    lat: 43.2942156,
    lng: 5.3980995,
    seeded: true,
  },
  {
    id: "seed-event-marseille-pride-march-2026",
    city: "marseille",
    name: "Marseille Pride March and Village 2026",
    description: "Pride village from 12:00, march from Place Castellane at 16:30, and a free evening concert near the Vieux-Port from 19:00. Protest, celebration, Mediterranean volume, and demonstratively excellent outfits share the route.",
    link: "https://www.pride-marseille.com/",
    date: "2026-07-04",
    lat: 43.2859177,
    lng: 5.3837376,
    seeded: true,
  },
  {
    id: "seed-event-marseille-pride-party-2026",
    city: "marseille",
    name: "Marseille Pride Official Party 2026",
    description: "The official Pride party runs from 22:00 to 05:00 across two rooms at La Plateforme. DJs, drag, queer performance, and a city that has absolutely no intention of going quietly home.",
    link: "https://www.pride-marseille.com/soiree-officielle-2026/",
    date: "2026-07-04",
    lat: 43.3146893,
    lng: 5.3677456,
    seeded: true,
  },
  {
    id: "seed-event-marseille-trans-handies-2026",
    city: "marseille",
    name: "Permanence Trans and Handi.e.s - 9 July 2026",
    description: "A free drop-in peer space from 18:30 to 22:00 for trans and non-binary disabled or neurodivergent people. Come as you are; nobody needs to compress an identity into one tidy checkbox.",
    link: "https://centrelgbtqiamarseille.org/agenda/permanence-trans-handi-e-s/",
    date: "2026-07-09",
    lat: 43.298013,
    lng: 5.3717676,
    seeded: true,
  },
];
