export const OTTAWA_CITY_SLUGS = new Set(["ottawa"]);

export const ottawaSeedPlaces = [
  {
    id: "seed-place-ottawa-lookout",
    city: "ottawa",
    name: "The Lookout Bar",
    type: "club",
    vibe: "ByWard drag, dancing and all-welcoming queer nightlife",
    description: "Ottawa's best-known LGBTQ+ nightclub combines recurring drag, karaoke, drinks, and a lively dance floor above York Street. It is the clearest first stop when the plan calls for a recognizably queer night rather than a subtle hint.",
    hours: "Mon closed; Tue 19:00-00:00; Wed-Fri 19:00-02:00; Sat 15:00-02:00; Sun 15:00-23:00.",
    link: "https://www.thelookoutbar.com/",
    location: "41 York Street, 2nd Floor, Ottawa, ON K1N 5S7, Canada",
    lat: 45.428191,
    lng: -75.693734,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-swizzles",
    city: "ottawa",
    name: "Swizzles Bar & Grill",
    type: "bar",
    vibe: "bias-free community bar with karaoke, drag and comedy",
    description: "A proudly bias-free downtown bar built around community rather than velvet-rope theatre. Karaoke, drag, comedy, and regulars give Swizzles the useful feeling of somewhere you can arrive alone and still acquire a night.",
    hours: "Mon 19:00-00:00; Tue closed; Wed-Fri 16:00-02:00; Sat 19:00-02:00; Sun 17:00-02:00. Verify same-day hours.",
    link: "https://www.swizzles.ca/",
    location: "246 Queen Street, Ottawa, ON, Canada",
    lat: 45.42017,
    lng: -75.701396,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-ts-pub",
    city: "ottawa",
    name: "T's Pub",
    type: "bar",
    vibe: "Village pub, patio drinks and recurring queer socials",
    description: "A relaxed LGBTQ+ pub in the heart of the Village with a patio, karaoke, drag, sports, and community meetups. T's is useful as both an easy first drink and the place where an allegedly quiet afternoon changes its mind.",
    hours: "Mon-Wed 15:00-02:00; Thu-Sun 11:00-02:00. Check socials for event-led changes.",
    link: "https://ottawa.gaycities.com/",
    location: "323 Somerset Street West, Ottawa, ON K2P 0J8, Canada",
    lat: 45.416157,
    lng: -75.695107,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-pour-boy",
    city: "ottawa",
    name: "Pour Boy Pub",
    type: "bar",
    vibe: "inclusive Centretown pub with trivia, comedy and open mic",
    description: "An inclusive Centretown neighborhood pub with affordable food, trivia, open mic, comedy, and a crowd that does not require a costume change. It is a useful low-pressure bridge between daytime wandering and louder queer plans.",
    hours: "Event programme includes Tue trivia, Wed open mic, Thu comedy and Fri Blingo; verify current opening hours directly.",
    link: "https://pourboypub.com/",
    location: "495 Somerset Street West, Ottawa, ON K1R 5J7, Canada",
    lat: 45.413863,
    lng: -75.700468,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-atomic-rooster",
    city: "ottawa",
    name: "Atomic Rooster",
    type: "restaurant",
    vibe: "art-lined Bank Street bistro with brunch and live music",
    description: "An art-lined Bank Street bar and bistro serving brunch, late food, karaoke, and live music in an easy mixed setting. The Rooster is a reliable Village-adjacent option when one person wants dinner and another has already emotionally committed to nightlife.",
    hours: "Mon-Tue 16:00-02:00; Wed-Fri 12:00-02:00; Sat-Sun 10:00-02:00; kitchen open until 01:00.",
    link: "https://www.atomicrooster.ca/",
    location: "303 Bank Street, Ottawa, ON K2P 1X7, Canada",
    lat: 45.415094,
    lng: -75.695721,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-house-of-targ",
    city: "ottawa",
    name: "House of TARG",
    type: "club",
    vibe: "pinball, perogies, punk shows and playful mixed dance nights",
    description: "Part live-music venue, part vintage arcade, part perogy bunker, House of TARG is one of Ottawa's most entertaining mixed-night detours. Inclusive policies, dance parties, free-play sessions, and a crowd comfortable with joyful oddness do the rest.",
    hours: "Mon closed; Tue-Thu 17:00-23:00; Fri 17:00-01:00; Sat 12:00-01:00; Sun 12:00-00:00. Shows may alter access.",
    link: "https://www.houseoftarg.com/",
    location: "1077 Bank Street, Ottawa, ON K1S 3W9, Canada",
    lat: 45.394531,
    lng: -75.683277,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-club-ottawa",
    city: "ottawa",
    name: "Club Ottawa",
    type: "sauna",
    vibe: "men-only sauna, private rooms and continuous weekend hours",
    description: "Ottawa's dedicated gay bathhouse and men's sauna offers lockers, private rooms, steam, showers, and themed specials. The concept is direct, the Wellington West location is easy to reach, and the weekend schedule permits unusually ambitious relaxation.",
    hours: "Mon-Wed 10:00-00:00; open continuously Thu 10:00-Sun 23:00.",
    link: "https://www.clubottawa.com/",
    location: "1069 Wellington Street West, Ottawa, ON K1Y 2Y2, Canada",
    lat: 45.403633,
    lng: -75.724977,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-bridgehead-roastery",
    city: "ottawa",
    name: "Bridgehead Roastery and Coffeehouse",
    type: "cafe",
    vibe: "local fair-trade coffee, daytime reset and casual conversation",
    description: "The working roastery of Ottawa's homegrown fair-trade coffee chain is a practical daytime reset near Chinatown and Little Italy. Come for coffee, lunch, Wi-Fi, and the radical vacation concept of hearing your own thoughts before the next event.",
    hours: "Daily daytime coffeehouse hours vary; check the official location listing before visiting.",
    link: "https://www.bridgehead.ca/",
    location: "130 Anderson Street, Ottawa, ON K1R 6T7, Canada",
    lat: 45.407218,
    lng: -75.712987,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-alt-hotel",
    city: "ottawa",
    name: "Alt Hotel Ottawa Downtown",
    type: "hotel",
    vibe: "modern downtown base with walkable access to the queer core",
    description: "A modern 148-room downtown hotel within walking distance of Parliament, Centretown, and the Village. The design is clean, the location is efficient, and the lobby lounge is useful when the weather has opinions.",
    hours: "Hotel open daily; reception and booking services operate 24 hours.",
    link: "https://www.germainhotels.com/en/alt-hotel/ottawa",
    location: "185 Slater Street, Ottawa, ON K1P 0C8, Canada",
    lat: 45.41993,
    lng: -75.698991,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-andaz",
    city: "ottawa",
    name: "Andaz Ottawa ByWard Market",
    type: "hotel",
    vibe: "boutique luxury beside The Lookout with a rooftop bar",
    description: "A contemporary boutique hotel in ByWard Market with locally designed rooms and Ottawa's highest rooftop lounge. It is the polished choice for travelers who want The Lookout nearby and Parliament views waiting upstairs.",
    hours: "Hotel open daily; reception and booking services operate 24 hours.",
    link: "https://www.hyatt.com/andaz/en-US/yowaz-andaz-ottawa-byward-market",
    location: "325 Dalhousie Street, Ottawa, ON K1N 7G1, Canada",
    lat: 45.428756,
    lng: -75.690719,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-lord-elgin",
    city: "ottawa",
    name: "Lord Elgin Hotel",
    type: "hotel",
    vibe: "locally owned heritage hotel between Parliament and Centretown",
    description: "A locally owned heritage hotel opposite Confederation Park, positioned between Parliament, Elgin Street, and the Village. It offers classic capital-city atmosphere without making queer nightlife a cross-city expedition.",
    hours: "Hotel open daily; reception and booking services operate 24 hours.",
    link: "https://lordelginhotel.ca/",
    location: "100 Elgin Street, Ottawa, ON K1P 5K8, Canada",
    lat: 45.421324,
    lng: -75.693741,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
  {
    id: "seed-place-ottawa-chateau-laurier",
    city: "ottawa",
    name: "Fairmont Chateau Laurier",
    type: "hotel",
    vibe: "landmark luxury, art-deco pool and central grand-hotel drama",
    description: "Ottawa's castle delivers landmark grandeur, an art-deco pool, dining, and immediate access to Parliament and ByWard Market. It is not the budget answer, but it understands the value of making an entrance.",
    hours: "Hotel open daily; check-in from 16:00 and check-out by 12:00.",
    link: "https://www.fairmont.com/en/hotels/ottawa/fairmont-chateau-laurier.html",
    location: "1 Rideau Street, Ottawa, ON K1N 8S7, Canada",
    lat: 45.425665,
    lng: -75.695291,
    avgRating: null,
    reviewCount: 0,
    seeded: true,
  },
];

export const ottawaSeedEvents = [
  {
    id: "seed-event-ottawa-youth-pride-prom-2026",
    city: "ottawa",
    name: "Youth Pride Prom 2026",
    description: "A free, ticketed Pride prom for queer and trans youth at the Horticulture Building from 19:00 to 23:00. Drag, DJs, dancing, and an accessible venue make room for the formal-night memories everyone deserved the first time.",
    link: "https://capitalpride.ca/signature-events/",
    date: "2026-06-19",
    lat: 45.40078,
    lng: -75.682362,
    seeded: true,
  },
  {
    id: "seed-event-ottawa-capital-pride-festival-2026",
    city: "ottawa",
    name: "Capital Pride Festival 2026",
    description: "Nine days of community events, advocacy, performance, parties, and public queer visibility across Ottawa from 22 to 30 August. The full programme turns the compact capital scene into something considerably less compact.",
    link: "https://capitalpride.ca/2026-festival-applications/",
    date: "2026-08-22",
    lat: 45.41314,
    lng: -75.693502,
    seeded: true,
  },
  {
    id: "seed-event-ottawa-pride-street-festival-2026",
    city: "ottawa",
    name: "Capital Pride Street Festival 2026",
    description: "Bank Street becomes a two-day Pride village from 12:00 to 20:00 on 29 and 30 August, with community organizations, a craft fair, partner activations, and live programming.",
    link: "https://capitalpride.ca/2026-street-festival/",
    date: "2026-08-29",
    lat: 45.41314,
    lng: -75.693502,
    seeded: true,
  },
  {
    id: "seed-event-ottawa-drag-showcase-2026",
    city: "ottawa",
    name: "Happy 200th Birthday, Ottawa! Drag Talent Showcase",
    description: "Capital Pride's main-stage drag talent showcase runs from 17:00 to 19:00 on 29 August. Ottawa marks its bicentennial with the only proportionate response: wigs, talent, and absolutely no administrative beige.",
    link: "https://capitalpride.ca/signature-events/",
    date: "2026-08-29",
    lat: 45.41314,
    lng: -75.693502,
    seeded: true,
  },
  {
    id: "seed-event-ottawa-pride-parade-2026",
    city: "ottawa",
    name: "Capital Pride Parade 2026",
    description: "More than 225 groups and over 11,000 community members take central Ottawa from 13:00 to 16:00. The parade is the festival's loud public heart, mixing celebration, advocacy, music, and drag.",
    link: "https://capitalpride.ca/2026-pride-parade/",
    date: "2026-08-30",
    lat: 45.421324,
    lng: -75.693741,
    seeded: true,
  },
];
