import CityQualityModal from "@/components/city/CityQualityModal";
import CityReportModal from "@/components/city/CityReportModal";
import DetailsPanelBackdrop from "@/components/city/DetailsPanelBackdrop";
import SelectedEventPanel from "@/components/city/SelectedEventPanel";
import SelectedPlacePanel from "@/components/city/SelectedPlacePanel";
import SelectedServicePanel from "@/components/city/SelectedServicePanel";

export default function CityDetailsLayer({
  selectedPlace,
  selectedEvent,
  selectedService,
  closeAllDetails,
  handleDesktopPanelWheel,
  closeService,
  selectedServiceImages,
  cityLabel,
  serviceTypeLabels,
  selectedServiceQuality,
  selectedServiceQualityStatus,
  refreshEntityQuality,
  formatDate,
  canEditSelectedService,
  canDeleteSelectedService,
  serviceAdminOpen,
  toggleServiceAdminEditor,
  serviceAdminDraft,
  setServiceAdminDraft,
  handleAdminSaveServiceAddressOnly,
  isSavingServiceAddressOnly,
  handleAdminSaveService,
  isSavingServiceAdmin,
  handleAdminDeleteService,
  isDeletingServiceAdmin,
  serviceTypes,
  servicePriceTierOptions,
  selectedServiceBookingUrl,
  selectedServiceLinkUrl,
  canShowSelectedServiceOnMap,
  showServiceOnMap,
  handleReportSelectedService,
  closePlace,
  cityName,
  typeLabels,
  selectedPlaceSafetySignal,
  liveVibeSummary,
  liveVibeHeadline,
  liveVibePulse,
  liveVibeConsensus,
  liveVibeUpdatedLabel,
  liveVibeTableMissing,
  handleSubmitLiveVibe,
  isSubmittingLiveVibe,
  liveVibeMyActiveSignalKey,
  liveVibeSubmittingKey,
  liveVibeJustSentKey,
  liveVibeOptions,
  isMember,
  liveVibeSelectedOption,
  isLoadingLiveVibe,
  liveVibeError,
  liveVibeCooldownRemainingSec,
  showLiveVibeMomentum,
  setShowLiveVibeMomentum,
  liveVibeMemberMomentum,
  liveVibeStreakNudge,
  selectedPlaceQuality,
  selectedPlaceQualityStatus,
  trustedPlaceSavesCount,
  isAdmin,
  placeAdminOpen,
  togglePlaceAdminEditor,
  placeAdminDraft,
  setPlaceAdminDraft,
  handleAdminSavePlaceAddressOnly,
  isSavingPlaceAddressOnly,
  handleAdminSavePlace,
  isSavingPlaceAdmin,
  handleAdminDeletePlace,
  isDeletingPlaceAdmin,
  placeTypes,
  handleReport,
  toggleFavorite,
  favorites,
  reviews,
  canReviewSelectedPlace,
  isSubmittingReview,
  handleJoinToPlaceReview,
  rating,
  hoverRating,
  setHoverRating,
  setRating,
  safetyRating,
  hoverSafetyRating,
  setHoverSafetyRating,
  setSafetyRating,
  comment,
  setComment,
  handleSubmitPlaceReview,
  closeEvent,
  eventLiveVibeSignalKey,
  isSubmittingEventLiveVibe,
  eventLiveVibeSubmittingKey,
  eventLiveVibeJustSentKey,
  handleSubmitEventLiveVibe,
  eventLiveVibeSelectedOption,
  selectedEventQuality,
  selectedEventQualityStatus,
  trustedEventSavesCount,
  eventAdminOpen,
  toggleEventAdminEditor,
  eventAdminDraft,
  setEventAdminDraft,
  handleAdminSaveEventAddressOnly,
  isSavingEventAddressOnly,
  handleAdminSaveEvent,
  isSavingEventAdmin,
  handleAdminDeleteEvent,
  isDeletingEventAdmin,
  showEventOnMap,
  reportModalOpen,
  reportDraft,
  setReportDraft,
  reportReasons,
  closeReportModal,
  submitReport,
  qualityModal,
  setQualityModal,
  trustActions,
  closeQualityModal,
  submitQualityModal,
}) {
  return (
    <>
      <DetailsPanelBackdrop
        isOpen={Boolean(selectedPlace || selectedEvent || selectedService)}
        onClose={closeAllDetails}
      />

      {selectedService && (
        <SelectedServicePanel
          selectedService={selectedService}
          onWheel={handleDesktopPanelWheel}
          onClose={closeService}
          selectedServiceImages={selectedServiceImages}
          cityLabel={cityLabel}
          serviceTypeLabels={serviceTypeLabels}
          selectedServiceQuality={selectedServiceQuality}
          selectedServiceQualityStatus={selectedServiceQualityStatus}
          refreshEntityQuality={refreshEntityQuality}
          formatDate={formatDate}
          canEditSelectedService={canEditSelectedService}
          canDeleteSelectedService={canDeleteSelectedService}
          serviceAdminOpen={serviceAdminOpen}
          onToggleServiceAdmin={toggleServiceAdminEditor}
          serviceAdminDraft={serviceAdminDraft}
          setServiceAdminDraft={setServiceAdminDraft}
          onSaveServiceAddressOnly={handleAdminSaveServiceAddressOnly}
          isSavingServiceAddressOnly={isSavingServiceAddressOnly}
          onSaveService={handleAdminSaveService}
          isSavingServiceAdmin={isSavingServiceAdmin}
          onDeleteService={handleAdminDeleteService}
          isDeletingServiceAdmin={isDeletingServiceAdmin}
          serviceTypes={serviceTypes}
          priceTierOptions={servicePriceTierOptions}
          bookingUrl={selectedServiceBookingUrl}
          linkUrl={selectedServiceLinkUrl}
          canShowOnMap={canShowSelectedServiceOnMap}
          onShowOnMap={showServiceOnMap}
          onReportService={handleReportSelectedService}
        />
      )}

      {selectedPlace && (
        <SelectedPlacePanel
          selectedPlace={selectedPlace}
          onWheel={handleDesktopPanelWheel}
          onClose={closePlace}
          cityName={cityName}
          typeLabels={typeLabels}
          selectedPlaceSafetySignal={selectedPlaceSafetySignal}
          liveVibeSummary={liveVibeSummary}
          liveVibeHeadline={liveVibeHeadline}
          liveVibePulse={liveVibePulse}
          liveVibeConsensus={liveVibeConsensus}
          liveVibeUpdatedLabel={liveVibeUpdatedLabel}
          liveVibeTableMissing={liveVibeTableMissing}
          handleSubmitLiveVibe={handleSubmitLiveVibe}
          isSubmittingLiveVibe={isSubmittingLiveVibe}
          liveVibeMyActiveSignalKey={liveVibeMyActiveSignalKey}
          liveVibeSubmittingKey={liveVibeSubmittingKey}
          liveVibeJustSentKey={liveVibeJustSentKey}
          liveVibeOptions={liveVibeOptions}
          isMember={isMember}
          liveVibeSelectedOption={liveVibeSelectedOption}
          isLoadingLiveVibe={isLoadingLiveVibe}
          liveVibeError={liveVibeError}
          liveVibeCooldownRemainingSec={liveVibeCooldownRemainingSec}
          showLiveVibeMomentum={showLiveVibeMomentum}
          setShowLiveVibeMomentum={setShowLiveVibeMomentum}
          liveVibeMemberMomentum={liveVibeMemberMomentum}
          liveVibeStreakNudge={liveVibeStreakNudge}
          selectedPlaceQuality={selectedPlaceQuality}
          selectedPlaceQualityStatus={selectedPlaceQualityStatus}
          refreshEntityQuality={refreshEntityQuality}
          formatDate={formatDate}
          trustedPlaceSavesCount={trustedPlaceSavesCount}
          isAdmin={isAdmin}
          placeAdminOpen={placeAdminOpen}
          onTogglePlaceAdmin={togglePlaceAdminEditor}
          placeAdminDraft={placeAdminDraft}
          setPlaceAdminDraft={setPlaceAdminDraft}
          handleAdminSavePlaceAddressOnly={handleAdminSavePlaceAddressOnly}
          isSavingPlaceAddressOnly={isSavingPlaceAddressOnly}
          handleAdminSavePlace={handleAdminSavePlace}
          isSavingPlaceAdmin={isSavingPlaceAdmin}
          handleAdminDeletePlace={handleAdminDeletePlace}
          isDeletingPlaceAdmin={isDeletingPlaceAdmin}
          placeTypes={placeTypes}
          handleReport={handleReport}
          toggleFavorite={toggleFavorite}
          favorites={favorites}
          reviews={reviews}
          canReviewSelectedPlace={canReviewSelectedPlace}
          isSubmittingReview={isSubmittingReview}
          onJoinToReview={handleJoinToPlaceReview}
          rating={rating}
          hoverRating={hoverRating}
          setHoverRating={setHoverRating}
          setRating={setRating}
          safetyRating={safetyRating}
          hoverSafetyRating={hoverSafetyRating}
          setHoverSafetyRating={setHoverSafetyRating}
          setSafetyRating={setSafetyRating}
          comment={comment}
          setComment={setComment}
          onSubmitReview={handleSubmitPlaceReview}
        />
      )}

      {selectedEvent && (
        <SelectedEventPanel
          selectedEvent={selectedEvent}
          onWheel={handleDesktopPanelWheel}
          onClose={closeEvent}
          cityLabel={cityLabel}
          cityName={cityName}
          liveVibeOptions={liveVibeOptions}
          eventLiveVibeSignalKey={eventLiveVibeSignalKey}
          isSubmittingEventLiveVibe={isSubmittingEventLiveVibe}
          eventLiveVibeSubmittingKey={eventLiveVibeSubmittingKey}
          eventLiveVibeJustSentKey={eventLiveVibeJustSentKey}
          handleSubmitEventLiveVibe={handleSubmitEventLiveVibe}
          isMember={isMember}
          eventLiveVibeSelectedOption={eventLiveVibeSelectedOption}
          selectedEventQuality={selectedEventQuality}
          formatDate={formatDate}
          selectedEventQualityStatus={selectedEventQualityStatus}
          refreshEntityQuality={refreshEntityQuality}
          trustedEventSavesCount={trustedEventSavesCount}
          isAdmin={isAdmin}
          eventAdminOpen={eventAdminOpen}
          onToggleEventAdmin={toggleEventAdminEditor}
          eventAdminDraft={eventAdminDraft}
          setEventAdminDraft={setEventAdminDraft}
          handleAdminSaveEventAddressOnly={handleAdminSaveEventAddressOnly}
          isSavingEventAddressOnly={isSavingEventAddressOnly}
          handleAdminSaveEvent={handleAdminSaveEvent}
          isSavingEventAdmin={isSavingEventAdmin}
          handleAdminDeleteEvent={handleAdminDeleteEvent}
          isDeletingEventAdmin={isDeletingEventAdmin}
          favorites={favorites}
          toggleFavorite={toggleFavorite}
          showEventOnMap={showEventOnMap}
          handleReport={handleReport}
        />
      )}

      <CityReportModal
        open={reportModalOpen}
        reportDraft={reportDraft}
        setReportDraft={setReportDraft}
        reportReasons={reportReasons}
        onClose={closeReportModal}
        onSubmit={submitReport}
      />

      <CityQualityModal
        open={qualityModal.open}
        qualityModal={qualityModal}
        setQualityModal={setQualityModal}
        trustActions={trustActions}
        onClose={closeQualityModal}
        onSubmit={submitQualityModal}
      />
    </>
  );
}
